PYTHON=python3


Cher.CHR_Mono_12:
	-$(PYTHON) "data/multilingual/Cher.CHR/Mono_12/pdf_to_json_test_Cher.CHR_Mono_12.py" > "data/multilingual/Cher.CHR/Mono_12/pdf_to_json_test_Cher.CHR_Mono_12.json" 2>&1
Cher.CHR_Mono_16:
	-$(PYTHON) "data/multilingual/Cher.CHR/Mono_16/pdf_to_json_test_Cher.CHR_Mono_16.py" > "data/multilingual/Cher.CHR/Mono_16/pdf_to_json_test_Cher.CHR_Mono_16.json" 2>&1
Cher.CHR_Mono_8:
	-$(PYTHON) "data/multilingual/Cher.CHR/Mono_8/pdf_to_json_test_Cher.CHR_Mono_8.py" > "data/multilingual/Cher.CHR/Mono_8/pdf_to_json_test_Cher.CHR_Mono_8.json" 2>&1
Cher.CHR_Sans_12:
	-$(PYTHON) "data/multilingual/Cher.CHR/Sans_12/pdf_to_json_test_Cher.CHR_Sans_12.py" > "data/multilingual/Cher.CHR/Sans_12/pdf_to_json_test_Cher.CHR_Sans_12.json" 2>&1
Cher.CHR_Sans_16:
	-$(PYTHON) "data/multilingual/Cher.CHR/Sans_16/pdf_to_json_test_Cher.CHR_Sans_16.py" > "data/multilingual/Cher.CHR/Sans_16/pdf_to_json_test_Cher.CHR_Sans_16.json" 2>&1
Cher.CHR_Sans_8:
	-$(PYTHON) "data/multilingual/Cher.CHR/Sans_8/pdf_to_json_test_Cher.CHR_Sans_8.py" > "data/multilingual/Cher.CHR/Sans_8/pdf_to_json_test_Cher.CHR_Sans_8.json" 2>&1
Cher.CHR_Serif_12:
	-$(PYTHON) "data/multilingual/Cher.CHR/Serif_12/pdf_to_json_test_Cher.CHR_Serif_12.py" > "data/multilingual/Cher.CHR/Serif_12/pdf_to_json_test_Cher.CHR_Serif_12.json" 2>&1
Cher.CHR_Serif_16:
	-$(PYTHON) "data/multilingual/Cher.CHR/Serif_16/pdf_to_json_test_Cher.CHR_Serif_16.py" > "data/multilingual/Cher.CHR/Serif_16/pdf_to_json_test_Cher.CHR_Serif_16.json" 2>&1
Cher.CHR_Serif_8:
	-$(PYTHON) "data/multilingual/Cher.CHR/Serif_8/pdf_to_json_test_Cher.CHR_Serif_8.py" > "data/multilingual/Cher.CHR/Serif_8/pdf_to_json_test_Cher.CHR_Serif_8.json" 2>&1
Cher.CHR_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Cher.CHR/Sun-ExtA_12/pdf_to_json_test_Cher.CHR_Sun-ExtA_12.py" > "data/multilingual/Cher.CHR/Sun-ExtA_12/pdf_to_json_test_Cher.CHR_Sun-ExtA_12.json" 2>&1
Cher.CHR_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Cher.CHR/Sun-ExtA_16/pdf_to_json_test_Cher.CHR_Sun-ExtA_16.py" > "data/multilingual/Cher.CHR/Sun-ExtA_16/pdf_to_json_test_Cher.CHR_Sun-ExtA_16.json" 2>&1
Cher.CHR_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Cher.CHR/Sun-ExtA_8/pdf_to_json_test_Cher.CHR_Sun-ExtA_8.py" > "data/multilingual/Cher.CHR/Sun-ExtA_8/pdf_to_json_test_Cher.CHR_Sun-ExtA_8.json" 2>&1


Cher.CHR_all : Cher.CHR_Mono_12 Cher.CHR_Mono_16 Cher.CHR_Mono_8 Cher.CHR_Sans_12 Cher.CHR_Sans_16 Cher.CHR_Sans_8 Cher.CHR_Serif_12 Cher.CHR_Serif_16 Cher.CHR_Serif_8 Cher.CHR_Sun-ExtA_12 Cher.CHR_Sun-ExtA_16 Cher.CHR_Sun-ExtA_8
