PYTHON=python3


Cyrl.ABK_Mono_12:
	-$(PYTHON) data/multilingual/Cyrl.ABK/Mono_12/pdf_to_json_test_Cyrl.ABK_Mono_12.py > data/multilingual/Cyrl.ABK/Mono_12/pdf_to_json_test_Cyrl.ABK_Mono_12.json 2>&1
Cyrl.ABK_Mono_16:
	-$(PYTHON) data/multilingual/Cyrl.ABK/Mono_16/pdf_to_json_test_Cyrl.ABK_Mono_16.py > data/multilingual/Cyrl.ABK/Mono_16/pdf_to_json_test_Cyrl.ABK_Mono_16.json 2>&1
Cyrl.ABK_Mono_8:
	-$(PYTHON) data/multilingual/Cyrl.ABK/Mono_8/pdf_to_json_test_Cyrl.ABK_Mono_8.py > data/multilingual/Cyrl.ABK/Mono_8/pdf_to_json_test_Cyrl.ABK_Mono_8.json 2>&1
Cyrl.ABK_Sans_12:
	-$(PYTHON) data/multilingual/Cyrl.ABK/Sans_12/pdf_to_json_test_Cyrl.ABK_Sans_12.py > data/multilingual/Cyrl.ABK/Sans_12/pdf_to_json_test_Cyrl.ABK_Sans_12.json 2>&1
Cyrl.ABK_Sans_16:
	-$(PYTHON) data/multilingual/Cyrl.ABK/Sans_16/pdf_to_json_test_Cyrl.ABK_Sans_16.py > data/multilingual/Cyrl.ABK/Sans_16/pdf_to_json_test_Cyrl.ABK_Sans_16.json 2>&1
Cyrl.ABK_Sans_8:
	-$(PYTHON) data/multilingual/Cyrl.ABK/Sans_8/pdf_to_json_test_Cyrl.ABK_Sans_8.py > data/multilingual/Cyrl.ABK/Sans_8/pdf_to_json_test_Cyrl.ABK_Sans_8.json 2>&1
Cyrl.ABK_Serif_12:
	-$(PYTHON) data/multilingual/Cyrl.ABK/Serif_12/pdf_to_json_test_Cyrl.ABK_Serif_12.py > data/multilingual/Cyrl.ABK/Serif_12/pdf_to_json_test_Cyrl.ABK_Serif_12.json 2>&1
Cyrl.ABK_Serif_16:
	-$(PYTHON) data/multilingual/Cyrl.ABK/Serif_16/pdf_to_json_test_Cyrl.ABK_Serif_16.py > data/multilingual/Cyrl.ABK/Serif_16/pdf_to_json_test_Cyrl.ABK_Serif_16.json 2>&1
Cyrl.ABK_Serif_8:
	-$(PYTHON) data/multilingual/Cyrl.ABK/Serif_8/pdf_to_json_test_Cyrl.ABK_Serif_8.py > data/multilingual/Cyrl.ABK/Serif_8/pdf_to_json_test_Cyrl.ABK_Serif_8.json 2>&1
Cyrl.ABK_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Cyrl.ABK/Sun-ExtA_12/pdf_to_json_test_Cyrl.ABK_Sun-ExtA_12.py > data/multilingual/Cyrl.ABK/Sun-ExtA_12/pdf_to_json_test_Cyrl.ABK_Sun-ExtA_12.json 2>&1
Cyrl.ABK_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Cyrl.ABK/Sun-ExtA_16/pdf_to_json_test_Cyrl.ABK_Sun-ExtA_16.py > data/multilingual/Cyrl.ABK/Sun-ExtA_16/pdf_to_json_test_Cyrl.ABK_Sun-ExtA_16.json 2>&1
Cyrl.ABK_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Cyrl.ABK/Sun-ExtA_8/pdf_to_json_test_Cyrl.ABK_Sun-ExtA_8.py > data/multilingual/Cyrl.ABK/Sun-ExtA_8/pdf_to_json_test_Cyrl.ABK_Sun-ExtA_8.json 2>&1


Cyrl.ABK_all : Cyrl.ABK_Mono_12 Cyrl.ABK_Mono_16 Cyrl.ABK_Mono_8 Cyrl.ABK_Sans_12 Cyrl.ABK_Sans_16 Cyrl.ABK_Sans_8 Cyrl.ABK_Serif_12 Cyrl.ABK_Serif_16 Cyrl.ABK_Serif_8 Cyrl.ABK_Sun-ExtA_12 Cyrl.ABK_Sun-ExtA_16 Cyrl.ABK_Sun-ExtA_8
