PYTHON=python3


Latn.FIJ_Mono_12:
	-$(PYTHON) data/multilingual/Latn.FIJ/Mono_12/pdf_to_json_test_Latn.FIJ_Mono_12.py > data/multilingual/Latn.FIJ/Mono_12/pdf_to_json_test_Latn.FIJ_Mono_12.json 2>&1
Latn.FIJ_Mono_16:
	-$(PYTHON) data/multilingual/Latn.FIJ/Mono_16/pdf_to_json_test_Latn.FIJ_Mono_16.py > data/multilingual/Latn.FIJ/Mono_16/pdf_to_json_test_Latn.FIJ_Mono_16.json 2>&1
Latn.FIJ_Mono_8:
	-$(PYTHON) data/multilingual/Latn.FIJ/Mono_8/pdf_to_json_test_Latn.FIJ_Mono_8.py > data/multilingual/Latn.FIJ/Mono_8/pdf_to_json_test_Latn.FIJ_Mono_8.json 2>&1
Latn.FIJ_Sans_12:
	-$(PYTHON) data/multilingual/Latn.FIJ/Sans_12/pdf_to_json_test_Latn.FIJ_Sans_12.py > data/multilingual/Latn.FIJ/Sans_12/pdf_to_json_test_Latn.FIJ_Sans_12.json 2>&1
Latn.FIJ_Sans_16:
	-$(PYTHON) data/multilingual/Latn.FIJ/Sans_16/pdf_to_json_test_Latn.FIJ_Sans_16.py > data/multilingual/Latn.FIJ/Sans_16/pdf_to_json_test_Latn.FIJ_Sans_16.json 2>&1
Latn.FIJ_Sans_8:
	-$(PYTHON) data/multilingual/Latn.FIJ/Sans_8/pdf_to_json_test_Latn.FIJ_Sans_8.py > data/multilingual/Latn.FIJ/Sans_8/pdf_to_json_test_Latn.FIJ_Sans_8.json 2>&1
Latn.FIJ_Serif_12:
	-$(PYTHON) data/multilingual/Latn.FIJ/Serif_12/pdf_to_json_test_Latn.FIJ_Serif_12.py > data/multilingual/Latn.FIJ/Serif_12/pdf_to_json_test_Latn.FIJ_Serif_12.json 2>&1
Latn.FIJ_Serif_16:
	-$(PYTHON) data/multilingual/Latn.FIJ/Serif_16/pdf_to_json_test_Latn.FIJ_Serif_16.py > data/multilingual/Latn.FIJ/Serif_16/pdf_to_json_test_Latn.FIJ_Serif_16.json 2>&1
Latn.FIJ_Serif_8:
	-$(PYTHON) data/multilingual/Latn.FIJ/Serif_8/pdf_to_json_test_Latn.FIJ_Serif_8.py > data/multilingual/Latn.FIJ/Serif_8/pdf_to_json_test_Latn.FIJ_Serif_8.json 2>&1
Latn.FIJ_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.FIJ/Sun-ExtA_12/pdf_to_json_test_Latn.FIJ_Sun-ExtA_12.py > data/multilingual/Latn.FIJ/Sun-ExtA_12/pdf_to_json_test_Latn.FIJ_Sun-ExtA_12.json 2>&1
Latn.FIJ_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.FIJ/Sun-ExtA_16/pdf_to_json_test_Latn.FIJ_Sun-ExtA_16.py > data/multilingual/Latn.FIJ/Sun-ExtA_16/pdf_to_json_test_Latn.FIJ_Sun-ExtA_16.json 2>&1
Latn.FIJ_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.FIJ/Sun-ExtA_8/pdf_to_json_test_Latn.FIJ_Sun-ExtA_8.py > data/multilingual/Latn.FIJ/Sun-ExtA_8/pdf_to_json_test_Latn.FIJ_Sun-ExtA_8.json 2>&1


Latn.FIJ_all : Latn.FIJ_Mono_12 Latn.FIJ_Mono_16 Latn.FIJ_Mono_8 Latn.FIJ_Sans_12 Latn.FIJ_Sans_16 Latn.FIJ_Sans_8 Latn.FIJ_Serif_12 Latn.FIJ_Serif_16 Latn.FIJ_Serif_8 Latn.FIJ_Sun-ExtA_12 Latn.FIJ_Sun-ExtA_16 Latn.FIJ_Sun-ExtA_8
