PYTHON=python3


Latn.MEN_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.MEN/Mono_12/pdf_to_json_test_Latn.MEN_Mono_12.py" > "data/multilingual/Latn.MEN/Mono_12/pdf_to_json_test_Latn.MEN_Mono_12.json" 2>&1
Latn.MEN_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.MEN/Mono_16/pdf_to_json_test_Latn.MEN_Mono_16.py" > "data/multilingual/Latn.MEN/Mono_16/pdf_to_json_test_Latn.MEN_Mono_16.json" 2>&1
Latn.MEN_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.MEN/Mono_8/pdf_to_json_test_Latn.MEN_Mono_8.py" > "data/multilingual/Latn.MEN/Mono_8/pdf_to_json_test_Latn.MEN_Mono_8.json" 2>&1
Latn.MEN_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.MEN/Sans_12/pdf_to_json_test_Latn.MEN_Sans_12.py" > "data/multilingual/Latn.MEN/Sans_12/pdf_to_json_test_Latn.MEN_Sans_12.json" 2>&1
Latn.MEN_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.MEN/Sans_16/pdf_to_json_test_Latn.MEN_Sans_16.py" > "data/multilingual/Latn.MEN/Sans_16/pdf_to_json_test_Latn.MEN_Sans_16.json" 2>&1
Latn.MEN_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.MEN/Sans_8/pdf_to_json_test_Latn.MEN_Sans_8.py" > "data/multilingual/Latn.MEN/Sans_8/pdf_to_json_test_Latn.MEN_Sans_8.json" 2>&1
Latn.MEN_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.MEN/Serif_12/pdf_to_json_test_Latn.MEN_Serif_12.py" > "data/multilingual/Latn.MEN/Serif_12/pdf_to_json_test_Latn.MEN_Serif_12.json" 2>&1
Latn.MEN_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.MEN/Serif_16/pdf_to_json_test_Latn.MEN_Serif_16.py" > "data/multilingual/Latn.MEN/Serif_16/pdf_to_json_test_Latn.MEN_Serif_16.json" 2>&1
Latn.MEN_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.MEN/Serif_8/pdf_to_json_test_Latn.MEN_Serif_8.py" > "data/multilingual/Latn.MEN/Serif_8/pdf_to_json_test_Latn.MEN_Serif_8.json" 2>&1
Latn.MEN_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.MEN/Sun-ExtA_12/pdf_to_json_test_Latn.MEN_Sun-ExtA_12.py" > "data/multilingual/Latn.MEN/Sun-ExtA_12/pdf_to_json_test_Latn.MEN_Sun-ExtA_12.json" 2>&1
Latn.MEN_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.MEN/Sun-ExtA_16/pdf_to_json_test_Latn.MEN_Sun-ExtA_16.py" > "data/multilingual/Latn.MEN/Sun-ExtA_16/pdf_to_json_test_Latn.MEN_Sun-ExtA_16.json" 2>&1
Latn.MEN_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.MEN/Sun-ExtA_8/pdf_to_json_test_Latn.MEN_Sun-ExtA_8.py" > "data/multilingual/Latn.MEN/Sun-ExtA_8/pdf_to_json_test_Latn.MEN_Sun-ExtA_8.json" 2>&1


Latn.MEN_all : Latn.MEN_Mono_12 Latn.MEN_Mono_16 Latn.MEN_Mono_8 Latn.MEN_Sans_12 Latn.MEN_Sans_16 Latn.MEN_Sans_8 Latn.MEN_Serif_12 Latn.MEN_Serif_16 Latn.MEN_Serif_8 Latn.MEN_Sun-ExtA_12 Latn.MEN_Sun-ExtA_16 Latn.MEN_Sun-ExtA_8
