PYTHON=python3


Latn.HLT_Mono_12:
	-$(PYTHON) data/multilingual/Latn.HLT/Mono_12/pdf_to_json_test_Latn.HLT_Mono_12.py > data/multilingual/Latn.HLT/Mono_12/pdf_to_json_test_Latn.HLT_Mono_12.json 2>&1
Latn.HLT_Mono_16:
	-$(PYTHON) data/multilingual/Latn.HLT/Mono_16/pdf_to_json_test_Latn.HLT_Mono_16.py > data/multilingual/Latn.HLT/Mono_16/pdf_to_json_test_Latn.HLT_Mono_16.json 2>&1
Latn.HLT_Mono_8:
	-$(PYTHON) data/multilingual/Latn.HLT/Mono_8/pdf_to_json_test_Latn.HLT_Mono_8.py > data/multilingual/Latn.HLT/Mono_8/pdf_to_json_test_Latn.HLT_Mono_8.json 2>&1
Latn.HLT_Sans_12:
	-$(PYTHON) data/multilingual/Latn.HLT/Sans_12/pdf_to_json_test_Latn.HLT_Sans_12.py > data/multilingual/Latn.HLT/Sans_12/pdf_to_json_test_Latn.HLT_Sans_12.json 2>&1
Latn.HLT_Sans_16:
	-$(PYTHON) data/multilingual/Latn.HLT/Sans_16/pdf_to_json_test_Latn.HLT_Sans_16.py > data/multilingual/Latn.HLT/Sans_16/pdf_to_json_test_Latn.HLT_Sans_16.json 2>&1
Latn.HLT_Sans_8:
	-$(PYTHON) data/multilingual/Latn.HLT/Sans_8/pdf_to_json_test_Latn.HLT_Sans_8.py > data/multilingual/Latn.HLT/Sans_8/pdf_to_json_test_Latn.HLT_Sans_8.json 2>&1
Latn.HLT_Serif_12:
	-$(PYTHON) data/multilingual/Latn.HLT/Serif_12/pdf_to_json_test_Latn.HLT_Serif_12.py > data/multilingual/Latn.HLT/Serif_12/pdf_to_json_test_Latn.HLT_Serif_12.json 2>&1
Latn.HLT_Serif_16:
	-$(PYTHON) data/multilingual/Latn.HLT/Serif_16/pdf_to_json_test_Latn.HLT_Serif_16.py > data/multilingual/Latn.HLT/Serif_16/pdf_to_json_test_Latn.HLT_Serif_16.json 2>&1
Latn.HLT_Serif_8:
	-$(PYTHON) data/multilingual/Latn.HLT/Serif_8/pdf_to_json_test_Latn.HLT_Serif_8.py > data/multilingual/Latn.HLT/Serif_8/pdf_to_json_test_Latn.HLT_Serif_8.json 2>&1
Latn.HLT_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.HLT/Sun-ExtA_12/pdf_to_json_test_Latn.HLT_Sun-ExtA_12.py > data/multilingual/Latn.HLT/Sun-ExtA_12/pdf_to_json_test_Latn.HLT_Sun-ExtA_12.json 2>&1
Latn.HLT_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.HLT/Sun-ExtA_16/pdf_to_json_test_Latn.HLT_Sun-ExtA_16.py > data/multilingual/Latn.HLT/Sun-ExtA_16/pdf_to_json_test_Latn.HLT_Sun-ExtA_16.json 2>&1
Latn.HLT_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.HLT/Sun-ExtA_8/pdf_to_json_test_Latn.HLT_Sun-ExtA_8.py > data/multilingual/Latn.HLT/Sun-ExtA_8/pdf_to_json_test_Latn.HLT_Sun-ExtA_8.json 2>&1


Latn.HLT_all : Latn.HLT_Mono_12 Latn.HLT_Mono_16 Latn.HLT_Mono_8 Latn.HLT_Sans_12 Latn.HLT_Sans_16 Latn.HLT_Sans_8 Latn.HLT_Serif_12 Latn.HLT_Serif_16 Latn.HLT_Serif_8 Latn.HLT_Sun-ExtA_12 Latn.HLT_Sun-ExtA_16 Latn.HLT_Sun-ExtA_8
