PYTHON=python3


Latn.ARN_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.ARN/Mono_12/pdf_to_json_test_Latn.ARN_Mono_12.py" > "data/multilingual/Latn.ARN/Mono_12/pdf_to_json_test_Latn.ARN_Mono_12.json" 2>&1
Latn.ARN_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.ARN/Mono_16/pdf_to_json_test_Latn.ARN_Mono_16.py" > "data/multilingual/Latn.ARN/Mono_16/pdf_to_json_test_Latn.ARN_Mono_16.json" 2>&1
Latn.ARN_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.ARN/Mono_8/pdf_to_json_test_Latn.ARN_Mono_8.py" > "data/multilingual/Latn.ARN/Mono_8/pdf_to_json_test_Latn.ARN_Mono_8.json" 2>&1
Latn.ARN_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.ARN/Sans_12/pdf_to_json_test_Latn.ARN_Sans_12.py" > "data/multilingual/Latn.ARN/Sans_12/pdf_to_json_test_Latn.ARN_Sans_12.json" 2>&1
Latn.ARN_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.ARN/Sans_16/pdf_to_json_test_Latn.ARN_Sans_16.py" > "data/multilingual/Latn.ARN/Sans_16/pdf_to_json_test_Latn.ARN_Sans_16.json" 2>&1
Latn.ARN_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.ARN/Sans_8/pdf_to_json_test_Latn.ARN_Sans_8.py" > "data/multilingual/Latn.ARN/Sans_8/pdf_to_json_test_Latn.ARN_Sans_8.json" 2>&1
Latn.ARN_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.ARN/Serif_12/pdf_to_json_test_Latn.ARN_Serif_12.py" > "data/multilingual/Latn.ARN/Serif_12/pdf_to_json_test_Latn.ARN_Serif_12.json" 2>&1
Latn.ARN_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.ARN/Serif_16/pdf_to_json_test_Latn.ARN_Serif_16.py" > "data/multilingual/Latn.ARN/Serif_16/pdf_to_json_test_Latn.ARN_Serif_16.json" 2>&1
Latn.ARN_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.ARN/Serif_8/pdf_to_json_test_Latn.ARN_Serif_8.py" > "data/multilingual/Latn.ARN/Serif_8/pdf_to_json_test_Latn.ARN_Serif_8.json" 2>&1
Latn.ARN_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.ARN/Sun-ExtA_12/pdf_to_json_test_Latn.ARN_Sun-ExtA_12.py" > "data/multilingual/Latn.ARN/Sun-ExtA_12/pdf_to_json_test_Latn.ARN_Sun-ExtA_12.json" 2>&1
Latn.ARN_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.ARN/Sun-ExtA_16/pdf_to_json_test_Latn.ARN_Sun-ExtA_16.py" > "data/multilingual/Latn.ARN/Sun-ExtA_16/pdf_to_json_test_Latn.ARN_Sun-ExtA_16.json" 2>&1
Latn.ARN_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.ARN/Sun-ExtA_8/pdf_to_json_test_Latn.ARN_Sun-ExtA_8.py" > "data/multilingual/Latn.ARN/Sun-ExtA_8/pdf_to_json_test_Latn.ARN_Sun-ExtA_8.json" 2>&1


Latn.ARN_all : Latn.ARN_Mono_12 Latn.ARN_Mono_16 Latn.ARN_Mono_8 Latn.ARN_Sans_12 Latn.ARN_Sans_16 Latn.ARN_Sans_8 Latn.ARN_Serif_12 Latn.ARN_Serif_16 Latn.ARN_Serif_8 Latn.ARN_Sun-ExtA_12 Latn.ARN_Sun-ExtA_16 Latn.ARN_Sun-ExtA_8
