PYTHON=python3


Latn.SWH_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.SWH/Mono_12/pdf_to_json_test_Latn.SWH_Mono_12.py" > "data/multilingual/Latn.SWH/Mono_12/pdf_to_json_test_Latn.SWH_Mono_12.json" 2>&1
Latn.SWH_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.SWH/Mono_16/pdf_to_json_test_Latn.SWH_Mono_16.py" > "data/multilingual/Latn.SWH/Mono_16/pdf_to_json_test_Latn.SWH_Mono_16.json" 2>&1
Latn.SWH_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.SWH/Mono_8/pdf_to_json_test_Latn.SWH_Mono_8.py" > "data/multilingual/Latn.SWH/Mono_8/pdf_to_json_test_Latn.SWH_Mono_8.json" 2>&1
Latn.SWH_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.SWH/Sans_12/pdf_to_json_test_Latn.SWH_Sans_12.py" > "data/multilingual/Latn.SWH/Sans_12/pdf_to_json_test_Latn.SWH_Sans_12.json" 2>&1
Latn.SWH_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.SWH/Sans_16/pdf_to_json_test_Latn.SWH_Sans_16.py" > "data/multilingual/Latn.SWH/Sans_16/pdf_to_json_test_Latn.SWH_Sans_16.json" 2>&1
Latn.SWH_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.SWH/Sans_8/pdf_to_json_test_Latn.SWH_Sans_8.py" > "data/multilingual/Latn.SWH/Sans_8/pdf_to_json_test_Latn.SWH_Sans_8.json" 2>&1
Latn.SWH_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.SWH/Serif_12/pdf_to_json_test_Latn.SWH_Serif_12.py" > "data/multilingual/Latn.SWH/Serif_12/pdf_to_json_test_Latn.SWH_Serif_12.json" 2>&1
Latn.SWH_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.SWH/Serif_16/pdf_to_json_test_Latn.SWH_Serif_16.py" > "data/multilingual/Latn.SWH/Serif_16/pdf_to_json_test_Latn.SWH_Serif_16.json" 2>&1
Latn.SWH_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.SWH/Serif_8/pdf_to_json_test_Latn.SWH_Serif_8.py" > "data/multilingual/Latn.SWH/Serif_8/pdf_to_json_test_Latn.SWH_Serif_8.json" 2>&1
Latn.SWH_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.SWH/Sun-ExtA_12/pdf_to_json_test_Latn.SWH_Sun-ExtA_12.py" > "data/multilingual/Latn.SWH/Sun-ExtA_12/pdf_to_json_test_Latn.SWH_Sun-ExtA_12.json" 2>&1
Latn.SWH_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.SWH/Sun-ExtA_16/pdf_to_json_test_Latn.SWH_Sun-ExtA_16.py" > "data/multilingual/Latn.SWH/Sun-ExtA_16/pdf_to_json_test_Latn.SWH_Sun-ExtA_16.json" 2>&1
Latn.SWH_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.SWH/Sun-ExtA_8/pdf_to_json_test_Latn.SWH_Sun-ExtA_8.py" > "data/multilingual/Latn.SWH/Sun-ExtA_8/pdf_to_json_test_Latn.SWH_Sun-ExtA_8.json" 2>&1


Latn.SWH_all : Latn.SWH_Mono_12 Latn.SWH_Mono_16 Latn.SWH_Mono_8 Latn.SWH_Sans_12 Latn.SWH_Sans_16 Latn.SWH_Sans_8 Latn.SWH_Serif_12 Latn.SWH_Serif_16 Latn.SWH_Serif_8 Latn.SWH_Sun-ExtA_12 Latn.SWH_Sun-ExtA_16 Latn.SWH_Sun-ExtA_8
