PYTHON=python3


Latn.MAZ_Mono_12:
	-$(PYTHON) data/multilingual/Latn.MAZ/Mono_12/pdf_to_json_test_Latn.MAZ_Mono_12.py > data/multilingual/Latn.MAZ/Mono_12/pdf_to_json_test_Latn.MAZ_Mono_12.json 2>&1
Latn.MAZ_Mono_16:
	-$(PYTHON) data/multilingual/Latn.MAZ/Mono_16/pdf_to_json_test_Latn.MAZ_Mono_16.py > data/multilingual/Latn.MAZ/Mono_16/pdf_to_json_test_Latn.MAZ_Mono_16.json 2>&1
Latn.MAZ_Mono_8:
	-$(PYTHON) data/multilingual/Latn.MAZ/Mono_8/pdf_to_json_test_Latn.MAZ_Mono_8.py > data/multilingual/Latn.MAZ/Mono_8/pdf_to_json_test_Latn.MAZ_Mono_8.json 2>&1
Latn.MAZ_Sans_12:
	-$(PYTHON) data/multilingual/Latn.MAZ/Sans_12/pdf_to_json_test_Latn.MAZ_Sans_12.py > data/multilingual/Latn.MAZ/Sans_12/pdf_to_json_test_Latn.MAZ_Sans_12.json 2>&1
Latn.MAZ_Sans_16:
	-$(PYTHON) data/multilingual/Latn.MAZ/Sans_16/pdf_to_json_test_Latn.MAZ_Sans_16.py > data/multilingual/Latn.MAZ/Sans_16/pdf_to_json_test_Latn.MAZ_Sans_16.json 2>&1
Latn.MAZ_Sans_8:
	-$(PYTHON) data/multilingual/Latn.MAZ/Sans_8/pdf_to_json_test_Latn.MAZ_Sans_8.py > data/multilingual/Latn.MAZ/Sans_8/pdf_to_json_test_Latn.MAZ_Sans_8.json 2>&1
Latn.MAZ_Serif_12:
	-$(PYTHON) data/multilingual/Latn.MAZ/Serif_12/pdf_to_json_test_Latn.MAZ_Serif_12.py > data/multilingual/Latn.MAZ/Serif_12/pdf_to_json_test_Latn.MAZ_Serif_12.json 2>&1
Latn.MAZ_Serif_16:
	-$(PYTHON) data/multilingual/Latn.MAZ/Serif_16/pdf_to_json_test_Latn.MAZ_Serif_16.py > data/multilingual/Latn.MAZ/Serif_16/pdf_to_json_test_Latn.MAZ_Serif_16.json 2>&1
Latn.MAZ_Serif_8:
	-$(PYTHON) data/multilingual/Latn.MAZ/Serif_8/pdf_to_json_test_Latn.MAZ_Serif_8.py > data/multilingual/Latn.MAZ/Serif_8/pdf_to_json_test_Latn.MAZ_Serif_8.json 2>&1
Latn.MAZ_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.MAZ/Sun-ExtA_12/pdf_to_json_test_Latn.MAZ_Sun-ExtA_12.py > data/multilingual/Latn.MAZ/Sun-ExtA_12/pdf_to_json_test_Latn.MAZ_Sun-ExtA_12.json 2>&1
Latn.MAZ_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.MAZ/Sun-ExtA_16/pdf_to_json_test_Latn.MAZ_Sun-ExtA_16.py > data/multilingual/Latn.MAZ/Sun-ExtA_16/pdf_to_json_test_Latn.MAZ_Sun-ExtA_16.json 2>&1
Latn.MAZ_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.MAZ/Sun-ExtA_8/pdf_to_json_test_Latn.MAZ_Sun-ExtA_8.py > data/multilingual/Latn.MAZ/Sun-ExtA_8/pdf_to_json_test_Latn.MAZ_Sun-ExtA_8.json 2>&1


Latn.MAZ_all : Latn.MAZ_Mono_12 Latn.MAZ_Mono_16 Latn.MAZ_Mono_8 Latn.MAZ_Sans_12 Latn.MAZ_Sans_16 Latn.MAZ_Sans_8 Latn.MAZ_Serif_12 Latn.MAZ_Serif_16 Latn.MAZ_Serif_8 Latn.MAZ_Sun-ExtA_12 Latn.MAZ_Sun-ExtA_16 Latn.MAZ_Sun-ExtA_8
