PYTHON=python3


Latn.DEU_Mono_12:
	-$(PYTHON) data/multilingual/Latn.DEU/Mono_12/pdf_to_json_test_Latn.DEU_Mono_12.py > data/multilingual/Latn.DEU/Mono_12/pdf_to_json_test_Latn.DEU_Mono_12.json 2>&1
Latn.DEU_Mono_16:
	-$(PYTHON) data/multilingual/Latn.DEU/Mono_16/pdf_to_json_test_Latn.DEU_Mono_16.py > data/multilingual/Latn.DEU/Mono_16/pdf_to_json_test_Latn.DEU_Mono_16.json 2>&1
Latn.DEU_Mono_8:
	-$(PYTHON) data/multilingual/Latn.DEU/Mono_8/pdf_to_json_test_Latn.DEU_Mono_8.py > data/multilingual/Latn.DEU/Mono_8/pdf_to_json_test_Latn.DEU_Mono_8.json 2>&1
Latn.DEU_Sans_12:
	-$(PYTHON) data/multilingual/Latn.DEU/Sans_12/pdf_to_json_test_Latn.DEU_Sans_12.py > data/multilingual/Latn.DEU/Sans_12/pdf_to_json_test_Latn.DEU_Sans_12.json 2>&1
Latn.DEU_Sans_16:
	-$(PYTHON) data/multilingual/Latn.DEU/Sans_16/pdf_to_json_test_Latn.DEU_Sans_16.py > data/multilingual/Latn.DEU/Sans_16/pdf_to_json_test_Latn.DEU_Sans_16.json 2>&1
Latn.DEU_Sans_8:
	-$(PYTHON) data/multilingual/Latn.DEU/Sans_8/pdf_to_json_test_Latn.DEU_Sans_8.py > data/multilingual/Latn.DEU/Sans_8/pdf_to_json_test_Latn.DEU_Sans_8.json 2>&1
Latn.DEU_Serif_12:
	-$(PYTHON) data/multilingual/Latn.DEU/Serif_12/pdf_to_json_test_Latn.DEU_Serif_12.py > data/multilingual/Latn.DEU/Serif_12/pdf_to_json_test_Latn.DEU_Serif_12.json 2>&1
Latn.DEU_Serif_16:
	-$(PYTHON) data/multilingual/Latn.DEU/Serif_16/pdf_to_json_test_Latn.DEU_Serif_16.py > data/multilingual/Latn.DEU/Serif_16/pdf_to_json_test_Latn.DEU_Serif_16.json 2>&1
Latn.DEU_Serif_8:
	-$(PYTHON) data/multilingual/Latn.DEU/Serif_8/pdf_to_json_test_Latn.DEU_Serif_8.py > data/multilingual/Latn.DEU/Serif_8/pdf_to_json_test_Latn.DEU_Serif_8.json 2>&1
Latn.DEU_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.DEU/Sun-ExtA_12/pdf_to_json_test_Latn.DEU_Sun-ExtA_12.py > data/multilingual/Latn.DEU/Sun-ExtA_12/pdf_to_json_test_Latn.DEU_Sun-ExtA_12.json 2>&1
Latn.DEU_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.DEU/Sun-ExtA_16/pdf_to_json_test_Latn.DEU_Sun-ExtA_16.py > data/multilingual/Latn.DEU/Sun-ExtA_16/pdf_to_json_test_Latn.DEU_Sun-ExtA_16.json 2>&1
Latn.DEU_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.DEU/Sun-ExtA_8/pdf_to_json_test_Latn.DEU_Sun-ExtA_8.py > data/multilingual/Latn.DEU/Sun-ExtA_8/pdf_to_json_test_Latn.DEU_Sun-ExtA_8.json 2>&1


Latn.DEU_all : Latn.DEU_Mono_12 Latn.DEU_Mono_16 Latn.DEU_Mono_8 Latn.DEU_Sans_12 Latn.DEU_Sans_16 Latn.DEU_Sans_8 Latn.DEU_Serif_12 Latn.DEU_Serif_16 Latn.DEU_Serif_8 Latn.DEU_Sun-ExtA_12 Latn.DEU_Sun-ExtA_16 Latn.DEU_Sun-ExtA_8
