PYTHON=python3


Cyrl.TAT_Mono_12:
	-$(PYTHON) "data/multilingual/Cyrl.TAT/Mono_12/pdf_to_json_test_Cyrl.TAT_Mono_12.py" > "data/multilingual/Cyrl.TAT/Mono_12/pdf_to_json_test_Cyrl.TAT_Mono_12.json" 2>&1
Cyrl.TAT_Mono_16:
	-$(PYTHON) "data/multilingual/Cyrl.TAT/Mono_16/pdf_to_json_test_Cyrl.TAT_Mono_16.py" > "data/multilingual/Cyrl.TAT/Mono_16/pdf_to_json_test_Cyrl.TAT_Mono_16.json" 2>&1
Cyrl.TAT_Mono_8:
	-$(PYTHON) "data/multilingual/Cyrl.TAT/Mono_8/pdf_to_json_test_Cyrl.TAT_Mono_8.py" > "data/multilingual/Cyrl.TAT/Mono_8/pdf_to_json_test_Cyrl.TAT_Mono_8.json" 2>&1
Cyrl.TAT_Sans_12:
	-$(PYTHON) "data/multilingual/Cyrl.TAT/Sans_12/pdf_to_json_test_Cyrl.TAT_Sans_12.py" > "data/multilingual/Cyrl.TAT/Sans_12/pdf_to_json_test_Cyrl.TAT_Sans_12.json" 2>&1
Cyrl.TAT_Sans_16:
	-$(PYTHON) "data/multilingual/Cyrl.TAT/Sans_16/pdf_to_json_test_Cyrl.TAT_Sans_16.py" > "data/multilingual/Cyrl.TAT/Sans_16/pdf_to_json_test_Cyrl.TAT_Sans_16.json" 2>&1
Cyrl.TAT_Sans_8:
	-$(PYTHON) "data/multilingual/Cyrl.TAT/Sans_8/pdf_to_json_test_Cyrl.TAT_Sans_8.py" > "data/multilingual/Cyrl.TAT/Sans_8/pdf_to_json_test_Cyrl.TAT_Sans_8.json" 2>&1
Cyrl.TAT_Serif_12:
	-$(PYTHON) "data/multilingual/Cyrl.TAT/Serif_12/pdf_to_json_test_Cyrl.TAT_Serif_12.py" > "data/multilingual/Cyrl.TAT/Serif_12/pdf_to_json_test_Cyrl.TAT_Serif_12.json" 2>&1
Cyrl.TAT_Serif_16:
	-$(PYTHON) "data/multilingual/Cyrl.TAT/Serif_16/pdf_to_json_test_Cyrl.TAT_Serif_16.py" > "data/multilingual/Cyrl.TAT/Serif_16/pdf_to_json_test_Cyrl.TAT_Serif_16.json" 2>&1
Cyrl.TAT_Serif_8:
	-$(PYTHON) "data/multilingual/Cyrl.TAT/Serif_8/pdf_to_json_test_Cyrl.TAT_Serif_8.py" > "data/multilingual/Cyrl.TAT/Serif_8/pdf_to_json_test_Cyrl.TAT_Serif_8.json" 2>&1
Cyrl.TAT_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Cyrl.TAT/Sun-ExtA_12/pdf_to_json_test_Cyrl.TAT_Sun-ExtA_12.py" > "data/multilingual/Cyrl.TAT/Sun-ExtA_12/pdf_to_json_test_Cyrl.TAT_Sun-ExtA_12.json" 2>&1
Cyrl.TAT_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Cyrl.TAT/Sun-ExtA_16/pdf_to_json_test_Cyrl.TAT_Sun-ExtA_16.py" > "data/multilingual/Cyrl.TAT/Sun-ExtA_16/pdf_to_json_test_Cyrl.TAT_Sun-ExtA_16.json" 2>&1
Cyrl.TAT_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Cyrl.TAT/Sun-ExtA_8/pdf_to_json_test_Cyrl.TAT_Sun-ExtA_8.py" > "data/multilingual/Cyrl.TAT/Sun-ExtA_8/pdf_to_json_test_Cyrl.TAT_Sun-ExtA_8.json" 2>&1


Cyrl.TAT_all : Cyrl.TAT_Mono_12 Cyrl.TAT_Mono_16 Cyrl.TAT_Mono_8 Cyrl.TAT_Sans_12 Cyrl.TAT_Sans_16 Cyrl.TAT_Sans_8 Cyrl.TAT_Serif_12 Cyrl.TAT_Serif_16 Cyrl.TAT_Serif_8 Cyrl.TAT_Sun-ExtA_12 Cyrl.TAT_Sun-ExtA_16 Cyrl.TAT_Sun-ExtA_8
