PYTHON=python3


Latn.SUK_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.SUK/Mono_12/pdf_to_json_test_Latn.SUK_Mono_12.py" > "data/multilingual/Latn.SUK/Mono_12/pdf_to_json_test_Latn.SUK_Mono_12.json" 2>&1
Latn.SUK_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.SUK/Mono_16/pdf_to_json_test_Latn.SUK_Mono_16.py" > "data/multilingual/Latn.SUK/Mono_16/pdf_to_json_test_Latn.SUK_Mono_16.json" 2>&1
Latn.SUK_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.SUK/Mono_8/pdf_to_json_test_Latn.SUK_Mono_8.py" > "data/multilingual/Latn.SUK/Mono_8/pdf_to_json_test_Latn.SUK_Mono_8.json" 2>&1
Latn.SUK_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.SUK/Sans_12/pdf_to_json_test_Latn.SUK_Sans_12.py" > "data/multilingual/Latn.SUK/Sans_12/pdf_to_json_test_Latn.SUK_Sans_12.json" 2>&1
Latn.SUK_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.SUK/Sans_16/pdf_to_json_test_Latn.SUK_Sans_16.py" > "data/multilingual/Latn.SUK/Sans_16/pdf_to_json_test_Latn.SUK_Sans_16.json" 2>&1
Latn.SUK_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.SUK/Sans_8/pdf_to_json_test_Latn.SUK_Sans_8.py" > "data/multilingual/Latn.SUK/Sans_8/pdf_to_json_test_Latn.SUK_Sans_8.json" 2>&1
Latn.SUK_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.SUK/Serif_12/pdf_to_json_test_Latn.SUK_Serif_12.py" > "data/multilingual/Latn.SUK/Serif_12/pdf_to_json_test_Latn.SUK_Serif_12.json" 2>&1
Latn.SUK_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.SUK/Serif_16/pdf_to_json_test_Latn.SUK_Serif_16.py" > "data/multilingual/Latn.SUK/Serif_16/pdf_to_json_test_Latn.SUK_Serif_16.json" 2>&1
Latn.SUK_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.SUK/Serif_8/pdf_to_json_test_Latn.SUK_Serif_8.py" > "data/multilingual/Latn.SUK/Serif_8/pdf_to_json_test_Latn.SUK_Serif_8.json" 2>&1
Latn.SUK_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.SUK/Sun-ExtA_12/pdf_to_json_test_Latn.SUK_Sun-ExtA_12.py" > "data/multilingual/Latn.SUK/Sun-ExtA_12/pdf_to_json_test_Latn.SUK_Sun-ExtA_12.json" 2>&1
Latn.SUK_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.SUK/Sun-ExtA_16/pdf_to_json_test_Latn.SUK_Sun-ExtA_16.py" > "data/multilingual/Latn.SUK/Sun-ExtA_16/pdf_to_json_test_Latn.SUK_Sun-ExtA_16.json" 2>&1
Latn.SUK_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.SUK/Sun-ExtA_8/pdf_to_json_test_Latn.SUK_Sun-ExtA_8.py" > "data/multilingual/Latn.SUK/Sun-ExtA_8/pdf_to_json_test_Latn.SUK_Sun-ExtA_8.json" 2>&1


Latn.SUK_all : Latn.SUK_Mono_12 Latn.SUK_Mono_16 Latn.SUK_Mono_8 Latn.SUK_Sans_12 Latn.SUK_Sans_16 Latn.SUK_Sans_8 Latn.SUK_Serif_12 Latn.SUK_Serif_16 Latn.SUK_Serif_8 Latn.SUK_Sun-ExtA_12 Latn.SUK_Sun-ExtA_16 Latn.SUK_Sun-ExtA_8
