PYTHON=python3


Cyrl.EVN_Mono_12:
	-$(PYTHON) "data/multilingual/Cyrl.EVN/Mono_12/pdf_to_json_test_Cyrl.EVN_Mono_12.py" > "data/multilingual/Cyrl.EVN/Mono_12/pdf_to_json_test_Cyrl.EVN_Mono_12.json" 2>&1
Cyrl.EVN_Mono_16:
	-$(PYTHON) "data/multilingual/Cyrl.EVN/Mono_16/pdf_to_json_test_Cyrl.EVN_Mono_16.py" > "data/multilingual/Cyrl.EVN/Mono_16/pdf_to_json_test_Cyrl.EVN_Mono_16.json" 2>&1
Cyrl.EVN_Mono_8:
	-$(PYTHON) "data/multilingual/Cyrl.EVN/Mono_8/pdf_to_json_test_Cyrl.EVN_Mono_8.py" > "data/multilingual/Cyrl.EVN/Mono_8/pdf_to_json_test_Cyrl.EVN_Mono_8.json" 2>&1
Cyrl.EVN_Sans_12:
	-$(PYTHON) "data/multilingual/Cyrl.EVN/Sans_12/pdf_to_json_test_Cyrl.EVN_Sans_12.py" > "data/multilingual/Cyrl.EVN/Sans_12/pdf_to_json_test_Cyrl.EVN_Sans_12.json" 2>&1
Cyrl.EVN_Sans_16:
	-$(PYTHON) "data/multilingual/Cyrl.EVN/Sans_16/pdf_to_json_test_Cyrl.EVN_Sans_16.py" > "data/multilingual/Cyrl.EVN/Sans_16/pdf_to_json_test_Cyrl.EVN_Sans_16.json" 2>&1
Cyrl.EVN_Sans_8:
	-$(PYTHON) "data/multilingual/Cyrl.EVN/Sans_8/pdf_to_json_test_Cyrl.EVN_Sans_8.py" > "data/multilingual/Cyrl.EVN/Sans_8/pdf_to_json_test_Cyrl.EVN_Sans_8.json" 2>&1
Cyrl.EVN_Serif_12:
	-$(PYTHON) "data/multilingual/Cyrl.EVN/Serif_12/pdf_to_json_test_Cyrl.EVN_Serif_12.py" > "data/multilingual/Cyrl.EVN/Serif_12/pdf_to_json_test_Cyrl.EVN_Serif_12.json" 2>&1
Cyrl.EVN_Serif_16:
	-$(PYTHON) "data/multilingual/Cyrl.EVN/Serif_16/pdf_to_json_test_Cyrl.EVN_Serif_16.py" > "data/multilingual/Cyrl.EVN/Serif_16/pdf_to_json_test_Cyrl.EVN_Serif_16.json" 2>&1
Cyrl.EVN_Serif_8:
	-$(PYTHON) "data/multilingual/Cyrl.EVN/Serif_8/pdf_to_json_test_Cyrl.EVN_Serif_8.py" > "data/multilingual/Cyrl.EVN/Serif_8/pdf_to_json_test_Cyrl.EVN_Serif_8.json" 2>&1
Cyrl.EVN_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Cyrl.EVN/Sun-ExtA_12/pdf_to_json_test_Cyrl.EVN_Sun-ExtA_12.py" > "data/multilingual/Cyrl.EVN/Sun-ExtA_12/pdf_to_json_test_Cyrl.EVN_Sun-ExtA_12.json" 2>&1
Cyrl.EVN_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Cyrl.EVN/Sun-ExtA_16/pdf_to_json_test_Cyrl.EVN_Sun-ExtA_16.py" > "data/multilingual/Cyrl.EVN/Sun-ExtA_16/pdf_to_json_test_Cyrl.EVN_Sun-ExtA_16.json" 2>&1
Cyrl.EVN_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Cyrl.EVN/Sun-ExtA_8/pdf_to_json_test_Cyrl.EVN_Sun-ExtA_8.py" > "data/multilingual/Cyrl.EVN/Sun-ExtA_8/pdf_to_json_test_Cyrl.EVN_Sun-ExtA_8.json" 2>&1


Cyrl.EVN_all : Cyrl.EVN_Mono_12 Cyrl.EVN_Mono_16 Cyrl.EVN_Mono_8 Cyrl.EVN_Sans_12 Cyrl.EVN_Sans_16 Cyrl.EVN_Sans_8 Cyrl.EVN_Serif_12 Cyrl.EVN_Serif_16 Cyrl.EVN_Serif_8 Cyrl.EVN_Sun-ExtA_12 Cyrl.EVN_Sun-ExtA_16 Cyrl.EVN_Sun-ExtA_8
