PYTHON=python3


Latn.DUU_Mono_12:
	-$(PYTHON) data/multilingual/Latn.DUU/Mono_12/pdf_to_json_test_Latn.DUU_Mono_12.py > data/multilingual/Latn.DUU/Mono_12/pdf_to_json_test_Latn.DUU_Mono_12.json 2>&1
Latn.DUU_Mono_16:
	-$(PYTHON) data/multilingual/Latn.DUU/Mono_16/pdf_to_json_test_Latn.DUU_Mono_16.py > data/multilingual/Latn.DUU/Mono_16/pdf_to_json_test_Latn.DUU_Mono_16.json 2>&1
Latn.DUU_Mono_8:
	-$(PYTHON) data/multilingual/Latn.DUU/Mono_8/pdf_to_json_test_Latn.DUU_Mono_8.py > data/multilingual/Latn.DUU/Mono_8/pdf_to_json_test_Latn.DUU_Mono_8.json 2>&1
Latn.DUU_Sans_12:
	-$(PYTHON) data/multilingual/Latn.DUU/Sans_12/pdf_to_json_test_Latn.DUU_Sans_12.py > data/multilingual/Latn.DUU/Sans_12/pdf_to_json_test_Latn.DUU_Sans_12.json 2>&1
Latn.DUU_Sans_16:
	-$(PYTHON) data/multilingual/Latn.DUU/Sans_16/pdf_to_json_test_Latn.DUU_Sans_16.py > data/multilingual/Latn.DUU/Sans_16/pdf_to_json_test_Latn.DUU_Sans_16.json 2>&1
Latn.DUU_Sans_8:
	-$(PYTHON) data/multilingual/Latn.DUU/Sans_8/pdf_to_json_test_Latn.DUU_Sans_8.py > data/multilingual/Latn.DUU/Sans_8/pdf_to_json_test_Latn.DUU_Sans_8.json 2>&1
Latn.DUU_Serif_12:
	-$(PYTHON) data/multilingual/Latn.DUU/Serif_12/pdf_to_json_test_Latn.DUU_Serif_12.py > data/multilingual/Latn.DUU/Serif_12/pdf_to_json_test_Latn.DUU_Serif_12.json 2>&1
Latn.DUU_Serif_16:
	-$(PYTHON) data/multilingual/Latn.DUU/Serif_16/pdf_to_json_test_Latn.DUU_Serif_16.py > data/multilingual/Latn.DUU/Serif_16/pdf_to_json_test_Latn.DUU_Serif_16.json 2>&1
Latn.DUU_Serif_8:
	-$(PYTHON) data/multilingual/Latn.DUU/Serif_8/pdf_to_json_test_Latn.DUU_Serif_8.py > data/multilingual/Latn.DUU/Serif_8/pdf_to_json_test_Latn.DUU_Serif_8.json 2>&1
Latn.DUU_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.DUU/Sun-ExtA_12/pdf_to_json_test_Latn.DUU_Sun-ExtA_12.py > data/multilingual/Latn.DUU/Sun-ExtA_12/pdf_to_json_test_Latn.DUU_Sun-ExtA_12.json 2>&1
Latn.DUU_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.DUU/Sun-ExtA_16/pdf_to_json_test_Latn.DUU_Sun-ExtA_16.py > data/multilingual/Latn.DUU/Sun-ExtA_16/pdf_to_json_test_Latn.DUU_Sun-ExtA_16.json 2>&1
Latn.DUU_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.DUU/Sun-ExtA_8/pdf_to_json_test_Latn.DUU_Sun-ExtA_8.py > data/multilingual/Latn.DUU/Sun-ExtA_8/pdf_to_json_test_Latn.DUU_Sun-ExtA_8.json 2>&1


Latn.DUU_all : Latn.DUU_Mono_12 Latn.DUU_Mono_16 Latn.DUU_Mono_8 Latn.DUU_Sans_12 Latn.DUU_Sans_16 Latn.DUU_Sans_8 Latn.DUU_Serif_12 Latn.DUU_Serif_16 Latn.DUU_Serif_8 Latn.DUU_Sun-ExtA_12 Latn.DUU_Sun-ExtA_16 Latn.DUU_Sun-ExtA_8
