PYTHON=python3


Latn.HIL_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.HIL/Mono_12/pdf_to_json_test_Latn.HIL_Mono_12.py" > "data/multilingual/Latn.HIL/Mono_12/pdf_to_json_test_Latn.HIL_Mono_12.json" 2>&1
Latn.HIL_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.HIL/Mono_16/pdf_to_json_test_Latn.HIL_Mono_16.py" > "data/multilingual/Latn.HIL/Mono_16/pdf_to_json_test_Latn.HIL_Mono_16.json" 2>&1
Latn.HIL_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.HIL/Mono_8/pdf_to_json_test_Latn.HIL_Mono_8.py" > "data/multilingual/Latn.HIL/Mono_8/pdf_to_json_test_Latn.HIL_Mono_8.json" 2>&1
Latn.HIL_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.HIL/Sans_12/pdf_to_json_test_Latn.HIL_Sans_12.py" > "data/multilingual/Latn.HIL/Sans_12/pdf_to_json_test_Latn.HIL_Sans_12.json" 2>&1
Latn.HIL_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.HIL/Sans_16/pdf_to_json_test_Latn.HIL_Sans_16.py" > "data/multilingual/Latn.HIL/Sans_16/pdf_to_json_test_Latn.HIL_Sans_16.json" 2>&1
Latn.HIL_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.HIL/Sans_8/pdf_to_json_test_Latn.HIL_Sans_8.py" > "data/multilingual/Latn.HIL/Sans_8/pdf_to_json_test_Latn.HIL_Sans_8.json" 2>&1
Latn.HIL_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.HIL/Serif_12/pdf_to_json_test_Latn.HIL_Serif_12.py" > "data/multilingual/Latn.HIL/Serif_12/pdf_to_json_test_Latn.HIL_Serif_12.json" 2>&1
Latn.HIL_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.HIL/Serif_16/pdf_to_json_test_Latn.HIL_Serif_16.py" > "data/multilingual/Latn.HIL/Serif_16/pdf_to_json_test_Latn.HIL_Serif_16.json" 2>&1
Latn.HIL_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.HIL/Serif_8/pdf_to_json_test_Latn.HIL_Serif_8.py" > "data/multilingual/Latn.HIL/Serif_8/pdf_to_json_test_Latn.HIL_Serif_8.json" 2>&1
Latn.HIL_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.HIL/Sun-ExtA_12/pdf_to_json_test_Latn.HIL_Sun-ExtA_12.py" > "data/multilingual/Latn.HIL/Sun-ExtA_12/pdf_to_json_test_Latn.HIL_Sun-ExtA_12.json" 2>&1
Latn.HIL_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.HIL/Sun-ExtA_16/pdf_to_json_test_Latn.HIL_Sun-ExtA_16.py" > "data/multilingual/Latn.HIL/Sun-ExtA_16/pdf_to_json_test_Latn.HIL_Sun-ExtA_16.json" 2>&1
Latn.HIL_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.HIL/Sun-ExtA_8/pdf_to_json_test_Latn.HIL_Sun-ExtA_8.py" > "data/multilingual/Latn.HIL/Sun-ExtA_8/pdf_to_json_test_Latn.HIL_Sun-ExtA_8.json" 2>&1


Latn.HIL_all : Latn.HIL_Mono_12 Latn.HIL_Mono_16 Latn.HIL_Mono_8 Latn.HIL_Sans_12 Latn.HIL_Sans_16 Latn.HIL_Sans_8 Latn.HIL_Serif_12 Latn.HIL_Serif_16 Latn.HIL_Serif_8 Latn.HIL_Sun-ExtA_12 Latn.HIL_Sun-ExtA_16 Latn.HIL_Sun-ExtA_8
