PYTHON=python3


Latn.BOS_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.BOS/Mono_12/pdf_to_json_test_Latn.BOS_Mono_12.py" > "data/multilingual/Latn.BOS/Mono_12/pdf_to_json_test_Latn.BOS_Mono_12.json" 2>&1
Latn.BOS_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.BOS/Mono_16/pdf_to_json_test_Latn.BOS_Mono_16.py" > "data/multilingual/Latn.BOS/Mono_16/pdf_to_json_test_Latn.BOS_Mono_16.json" 2>&1
Latn.BOS_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.BOS/Mono_8/pdf_to_json_test_Latn.BOS_Mono_8.py" > "data/multilingual/Latn.BOS/Mono_8/pdf_to_json_test_Latn.BOS_Mono_8.json" 2>&1
Latn.BOS_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.BOS/Sans_12/pdf_to_json_test_Latn.BOS_Sans_12.py" > "data/multilingual/Latn.BOS/Sans_12/pdf_to_json_test_Latn.BOS_Sans_12.json" 2>&1
Latn.BOS_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.BOS/Sans_16/pdf_to_json_test_Latn.BOS_Sans_16.py" > "data/multilingual/Latn.BOS/Sans_16/pdf_to_json_test_Latn.BOS_Sans_16.json" 2>&1
Latn.BOS_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.BOS/Sans_8/pdf_to_json_test_Latn.BOS_Sans_8.py" > "data/multilingual/Latn.BOS/Sans_8/pdf_to_json_test_Latn.BOS_Sans_8.json" 2>&1
Latn.BOS_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.BOS/Serif_12/pdf_to_json_test_Latn.BOS_Serif_12.py" > "data/multilingual/Latn.BOS/Serif_12/pdf_to_json_test_Latn.BOS_Serif_12.json" 2>&1
Latn.BOS_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.BOS/Serif_16/pdf_to_json_test_Latn.BOS_Serif_16.py" > "data/multilingual/Latn.BOS/Serif_16/pdf_to_json_test_Latn.BOS_Serif_16.json" 2>&1
Latn.BOS_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.BOS/Serif_8/pdf_to_json_test_Latn.BOS_Serif_8.py" > "data/multilingual/Latn.BOS/Serif_8/pdf_to_json_test_Latn.BOS_Serif_8.json" 2>&1
Latn.BOS_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.BOS/Sun-ExtA_12/pdf_to_json_test_Latn.BOS_Sun-ExtA_12.py" > "data/multilingual/Latn.BOS/Sun-ExtA_12/pdf_to_json_test_Latn.BOS_Sun-ExtA_12.json" 2>&1
Latn.BOS_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.BOS/Sun-ExtA_16/pdf_to_json_test_Latn.BOS_Sun-ExtA_16.py" > "data/multilingual/Latn.BOS/Sun-ExtA_16/pdf_to_json_test_Latn.BOS_Sun-ExtA_16.json" 2>&1
Latn.BOS_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.BOS/Sun-ExtA_8/pdf_to_json_test_Latn.BOS_Sun-ExtA_8.py" > "data/multilingual/Latn.BOS/Sun-ExtA_8/pdf_to_json_test_Latn.BOS_Sun-ExtA_8.json" 2>&1


Latn.BOS_all : Latn.BOS_Mono_12 Latn.BOS_Mono_16 Latn.BOS_Mono_8 Latn.BOS_Sans_12 Latn.BOS_Sans_16 Latn.BOS_Sans_8 Latn.BOS_Serif_12 Latn.BOS_Serif_16 Latn.BOS_Serif_8 Latn.BOS_Sun-ExtA_12 Latn.BOS_Sun-ExtA_16 Latn.BOS_Sun-ExtA_8
