PYTHON=python3


Latn.SAG_Mono_12:
	-$(PYTHON) data/multilingual/Latn.SAG/Mono_12/pdf_to_json_test_Latn.SAG_Mono_12.py > data/multilingual/Latn.SAG/Mono_12/pdf_to_json_test_Latn.SAG_Mono_12.json 2>&1
Latn.SAG_Mono_16:
	-$(PYTHON) data/multilingual/Latn.SAG/Mono_16/pdf_to_json_test_Latn.SAG_Mono_16.py > data/multilingual/Latn.SAG/Mono_16/pdf_to_json_test_Latn.SAG_Mono_16.json 2>&1
Latn.SAG_Mono_8:
	-$(PYTHON) data/multilingual/Latn.SAG/Mono_8/pdf_to_json_test_Latn.SAG_Mono_8.py > data/multilingual/Latn.SAG/Mono_8/pdf_to_json_test_Latn.SAG_Mono_8.json 2>&1
Latn.SAG_Sans_12:
	-$(PYTHON) data/multilingual/Latn.SAG/Sans_12/pdf_to_json_test_Latn.SAG_Sans_12.py > data/multilingual/Latn.SAG/Sans_12/pdf_to_json_test_Latn.SAG_Sans_12.json 2>&1
Latn.SAG_Sans_16:
	-$(PYTHON) data/multilingual/Latn.SAG/Sans_16/pdf_to_json_test_Latn.SAG_Sans_16.py > data/multilingual/Latn.SAG/Sans_16/pdf_to_json_test_Latn.SAG_Sans_16.json 2>&1
Latn.SAG_Sans_8:
	-$(PYTHON) data/multilingual/Latn.SAG/Sans_8/pdf_to_json_test_Latn.SAG_Sans_8.py > data/multilingual/Latn.SAG/Sans_8/pdf_to_json_test_Latn.SAG_Sans_8.json 2>&1
Latn.SAG_Serif_12:
	-$(PYTHON) data/multilingual/Latn.SAG/Serif_12/pdf_to_json_test_Latn.SAG_Serif_12.py > data/multilingual/Latn.SAG/Serif_12/pdf_to_json_test_Latn.SAG_Serif_12.json 2>&1
Latn.SAG_Serif_16:
	-$(PYTHON) data/multilingual/Latn.SAG/Serif_16/pdf_to_json_test_Latn.SAG_Serif_16.py > data/multilingual/Latn.SAG/Serif_16/pdf_to_json_test_Latn.SAG_Serif_16.json 2>&1
Latn.SAG_Serif_8:
	-$(PYTHON) data/multilingual/Latn.SAG/Serif_8/pdf_to_json_test_Latn.SAG_Serif_8.py > data/multilingual/Latn.SAG/Serif_8/pdf_to_json_test_Latn.SAG_Serif_8.json 2>&1
Latn.SAG_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.SAG/Sun-ExtA_12/pdf_to_json_test_Latn.SAG_Sun-ExtA_12.py > data/multilingual/Latn.SAG/Sun-ExtA_12/pdf_to_json_test_Latn.SAG_Sun-ExtA_12.json 2>&1
Latn.SAG_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.SAG/Sun-ExtA_16/pdf_to_json_test_Latn.SAG_Sun-ExtA_16.py > data/multilingual/Latn.SAG/Sun-ExtA_16/pdf_to_json_test_Latn.SAG_Sun-ExtA_16.json 2>&1
Latn.SAG_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.SAG/Sun-ExtA_8/pdf_to_json_test_Latn.SAG_Sun-ExtA_8.py > data/multilingual/Latn.SAG/Sun-ExtA_8/pdf_to_json_test_Latn.SAG_Sun-ExtA_8.json 2>&1


Latn.SAG_all : Latn.SAG_Mono_12 Latn.SAG_Mono_16 Latn.SAG_Mono_8 Latn.SAG_Sans_12 Latn.SAG_Sans_16 Latn.SAG_Sans_8 Latn.SAG_Serif_12 Latn.SAG_Serif_16 Latn.SAG_Serif_8 Latn.SAG_Sun-ExtA_12 Latn.SAG_Sun-ExtA_16 Latn.SAG_Sun-ExtA_8
