PYTHON=python3


Latn.MXV_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.MXV/Mono_12/pdf_to_json_test_Latn.MXV_Mono_12.py" > "data/multilingual/Latn.MXV/Mono_12/pdf_to_json_test_Latn.MXV_Mono_12.json" 2>&1
Latn.MXV_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.MXV/Mono_16/pdf_to_json_test_Latn.MXV_Mono_16.py" > "data/multilingual/Latn.MXV/Mono_16/pdf_to_json_test_Latn.MXV_Mono_16.json" 2>&1
Latn.MXV_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.MXV/Mono_8/pdf_to_json_test_Latn.MXV_Mono_8.py" > "data/multilingual/Latn.MXV/Mono_8/pdf_to_json_test_Latn.MXV_Mono_8.json" 2>&1
Latn.MXV_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.MXV/Sans_12/pdf_to_json_test_Latn.MXV_Sans_12.py" > "data/multilingual/Latn.MXV/Sans_12/pdf_to_json_test_Latn.MXV_Sans_12.json" 2>&1
Latn.MXV_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.MXV/Sans_16/pdf_to_json_test_Latn.MXV_Sans_16.py" > "data/multilingual/Latn.MXV/Sans_16/pdf_to_json_test_Latn.MXV_Sans_16.json" 2>&1
Latn.MXV_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.MXV/Sans_8/pdf_to_json_test_Latn.MXV_Sans_8.py" > "data/multilingual/Latn.MXV/Sans_8/pdf_to_json_test_Latn.MXV_Sans_8.json" 2>&1
Latn.MXV_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.MXV/Serif_12/pdf_to_json_test_Latn.MXV_Serif_12.py" > "data/multilingual/Latn.MXV/Serif_12/pdf_to_json_test_Latn.MXV_Serif_12.json" 2>&1
Latn.MXV_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.MXV/Serif_16/pdf_to_json_test_Latn.MXV_Serif_16.py" > "data/multilingual/Latn.MXV/Serif_16/pdf_to_json_test_Latn.MXV_Serif_16.json" 2>&1
Latn.MXV_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.MXV/Serif_8/pdf_to_json_test_Latn.MXV_Serif_8.py" > "data/multilingual/Latn.MXV/Serif_8/pdf_to_json_test_Latn.MXV_Serif_8.json" 2>&1
Latn.MXV_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.MXV/Sun-ExtA_12/pdf_to_json_test_Latn.MXV_Sun-ExtA_12.py" > "data/multilingual/Latn.MXV/Sun-ExtA_12/pdf_to_json_test_Latn.MXV_Sun-ExtA_12.json" 2>&1
Latn.MXV_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.MXV/Sun-ExtA_16/pdf_to_json_test_Latn.MXV_Sun-ExtA_16.py" > "data/multilingual/Latn.MXV/Sun-ExtA_16/pdf_to_json_test_Latn.MXV_Sun-ExtA_16.json" 2>&1
Latn.MXV_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.MXV/Sun-ExtA_8/pdf_to_json_test_Latn.MXV_Sun-ExtA_8.py" > "data/multilingual/Latn.MXV/Sun-ExtA_8/pdf_to_json_test_Latn.MXV_Sun-ExtA_8.json" 2>&1


Latn.MXV_all : Latn.MXV_Mono_12 Latn.MXV_Mono_16 Latn.MXV_Mono_8 Latn.MXV_Sans_12 Latn.MXV_Sans_16 Latn.MXV_Sans_8 Latn.MXV_Serif_12 Latn.MXV_Serif_16 Latn.MXV_Serif_8 Latn.MXV_Sun-ExtA_12 Latn.MXV_Sun-ExtA_16 Latn.MXV_Sun-ExtA_8
