PYTHON=python3


Latn.LIJ_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.LIJ/Mono_12/pdf_to_json_test_Latn.LIJ_Mono_12.py" > "data/multilingual/Latn.LIJ/Mono_12/pdf_to_json_test_Latn.LIJ_Mono_12.json" 2>&1
Latn.LIJ_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.LIJ/Mono_16/pdf_to_json_test_Latn.LIJ_Mono_16.py" > "data/multilingual/Latn.LIJ/Mono_16/pdf_to_json_test_Latn.LIJ_Mono_16.json" 2>&1
Latn.LIJ_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.LIJ/Mono_8/pdf_to_json_test_Latn.LIJ_Mono_8.py" > "data/multilingual/Latn.LIJ/Mono_8/pdf_to_json_test_Latn.LIJ_Mono_8.json" 2>&1
Latn.LIJ_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.LIJ/Sans_12/pdf_to_json_test_Latn.LIJ_Sans_12.py" > "data/multilingual/Latn.LIJ/Sans_12/pdf_to_json_test_Latn.LIJ_Sans_12.json" 2>&1
Latn.LIJ_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.LIJ/Sans_16/pdf_to_json_test_Latn.LIJ_Sans_16.py" > "data/multilingual/Latn.LIJ/Sans_16/pdf_to_json_test_Latn.LIJ_Sans_16.json" 2>&1
Latn.LIJ_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.LIJ/Sans_8/pdf_to_json_test_Latn.LIJ_Sans_8.py" > "data/multilingual/Latn.LIJ/Sans_8/pdf_to_json_test_Latn.LIJ_Sans_8.json" 2>&1
Latn.LIJ_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.LIJ/Serif_12/pdf_to_json_test_Latn.LIJ_Serif_12.py" > "data/multilingual/Latn.LIJ/Serif_12/pdf_to_json_test_Latn.LIJ_Serif_12.json" 2>&1
Latn.LIJ_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.LIJ/Serif_16/pdf_to_json_test_Latn.LIJ_Serif_16.py" > "data/multilingual/Latn.LIJ/Serif_16/pdf_to_json_test_Latn.LIJ_Serif_16.json" 2>&1
Latn.LIJ_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.LIJ/Serif_8/pdf_to_json_test_Latn.LIJ_Serif_8.py" > "data/multilingual/Latn.LIJ/Serif_8/pdf_to_json_test_Latn.LIJ_Serif_8.json" 2>&1
Latn.LIJ_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.LIJ/Sun-ExtA_12/pdf_to_json_test_Latn.LIJ_Sun-ExtA_12.py" > "data/multilingual/Latn.LIJ/Sun-ExtA_12/pdf_to_json_test_Latn.LIJ_Sun-ExtA_12.json" 2>&1
Latn.LIJ_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.LIJ/Sun-ExtA_16/pdf_to_json_test_Latn.LIJ_Sun-ExtA_16.py" > "data/multilingual/Latn.LIJ/Sun-ExtA_16/pdf_to_json_test_Latn.LIJ_Sun-ExtA_16.json" 2>&1
Latn.LIJ_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.LIJ/Sun-ExtA_8/pdf_to_json_test_Latn.LIJ_Sun-ExtA_8.py" > "data/multilingual/Latn.LIJ/Sun-ExtA_8/pdf_to_json_test_Latn.LIJ_Sun-ExtA_8.json" 2>&1


Latn.LIJ_all : Latn.LIJ_Mono_12 Latn.LIJ_Mono_16 Latn.LIJ_Mono_8 Latn.LIJ_Sans_12 Latn.LIJ_Sans_16 Latn.LIJ_Sans_8 Latn.LIJ_Serif_12 Latn.LIJ_Serif_16 Latn.LIJ_Serif_8 Latn.LIJ_Sun-ExtA_12 Latn.LIJ_Sun-ExtA_16 Latn.LIJ_Sun-ExtA_8
