PYTHON=python3


Sinh.SIN_Mono_12:
	-$(PYTHON) "data/multilingual/Sinh.SIN/Mono_12/pdf_to_json_test_Sinh.SIN_Mono_12.py" > "data/multilingual/Sinh.SIN/Mono_12/pdf_to_json_test_Sinh.SIN_Mono_12.json" 2>&1
Sinh.SIN_Mono_16:
	-$(PYTHON) "data/multilingual/Sinh.SIN/Mono_16/pdf_to_json_test_Sinh.SIN_Mono_16.py" > "data/multilingual/Sinh.SIN/Mono_16/pdf_to_json_test_Sinh.SIN_Mono_16.json" 2>&1
Sinh.SIN_Mono_8:
	-$(PYTHON) "data/multilingual/Sinh.SIN/Mono_8/pdf_to_json_test_Sinh.SIN_Mono_8.py" > "data/multilingual/Sinh.SIN/Mono_8/pdf_to_json_test_Sinh.SIN_Mono_8.json" 2>&1
Sinh.SIN_Sans_12:
	-$(PYTHON) "data/multilingual/Sinh.SIN/Sans_12/pdf_to_json_test_Sinh.SIN_Sans_12.py" > "data/multilingual/Sinh.SIN/Sans_12/pdf_to_json_test_Sinh.SIN_Sans_12.json" 2>&1
Sinh.SIN_Sans_16:
	-$(PYTHON) "data/multilingual/Sinh.SIN/Sans_16/pdf_to_json_test_Sinh.SIN_Sans_16.py" > "data/multilingual/Sinh.SIN/Sans_16/pdf_to_json_test_Sinh.SIN_Sans_16.json" 2>&1
Sinh.SIN_Sans_8:
	-$(PYTHON) "data/multilingual/Sinh.SIN/Sans_8/pdf_to_json_test_Sinh.SIN_Sans_8.py" > "data/multilingual/Sinh.SIN/Sans_8/pdf_to_json_test_Sinh.SIN_Sans_8.json" 2>&1
Sinh.SIN_Serif_12:
	-$(PYTHON) "data/multilingual/Sinh.SIN/Serif_12/pdf_to_json_test_Sinh.SIN_Serif_12.py" > "data/multilingual/Sinh.SIN/Serif_12/pdf_to_json_test_Sinh.SIN_Serif_12.json" 2>&1
Sinh.SIN_Serif_16:
	-$(PYTHON) "data/multilingual/Sinh.SIN/Serif_16/pdf_to_json_test_Sinh.SIN_Serif_16.py" > "data/multilingual/Sinh.SIN/Serif_16/pdf_to_json_test_Sinh.SIN_Serif_16.json" 2>&1
Sinh.SIN_Serif_8:
	-$(PYTHON) "data/multilingual/Sinh.SIN/Serif_8/pdf_to_json_test_Sinh.SIN_Serif_8.py" > "data/multilingual/Sinh.SIN/Serif_8/pdf_to_json_test_Sinh.SIN_Serif_8.json" 2>&1
Sinh.SIN_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Sinh.SIN/Sun-ExtA_12/pdf_to_json_test_Sinh.SIN_Sun-ExtA_12.py" > "data/multilingual/Sinh.SIN/Sun-ExtA_12/pdf_to_json_test_Sinh.SIN_Sun-ExtA_12.json" 2>&1
Sinh.SIN_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Sinh.SIN/Sun-ExtA_16/pdf_to_json_test_Sinh.SIN_Sun-ExtA_16.py" > "data/multilingual/Sinh.SIN/Sun-ExtA_16/pdf_to_json_test_Sinh.SIN_Sun-ExtA_16.json" 2>&1
Sinh.SIN_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Sinh.SIN/Sun-ExtA_8/pdf_to_json_test_Sinh.SIN_Sun-ExtA_8.py" > "data/multilingual/Sinh.SIN/Sun-ExtA_8/pdf_to_json_test_Sinh.SIN_Sun-ExtA_8.json" 2>&1


Sinh.SIN_all : Sinh.SIN_Mono_12 Sinh.SIN_Mono_16 Sinh.SIN_Mono_8 Sinh.SIN_Sans_12 Sinh.SIN_Sans_16 Sinh.SIN_Sans_8 Sinh.SIN_Serif_12 Sinh.SIN_Serif_16 Sinh.SIN_Serif_8 Sinh.SIN_Sun-ExtA_12 Sinh.SIN_Sun-ExtA_16 Sinh.SIN_Sun-ExtA_8
