PYTHON=python3


Latn.TOB_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.TOB/Mono_12/pdf_to_json_test_Latn.TOB_Mono_12.py" > "data/multilingual/Latn.TOB/Mono_12/pdf_to_json_test_Latn.TOB_Mono_12.json" 2>&1
Latn.TOB_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.TOB/Mono_16/pdf_to_json_test_Latn.TOB_Mono_16.py" > "data/multilingual/Latn.TOB/Mono_16/pdf_to_json_test_Latn.TOB_Mono_16.json" 2>&1
Latn.TOB_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.TOB/Mono_8/pdf_to_json_test_Latn.TOB_Mono_8.py" > "data/multilingual/Latn.TOB/Mono_8/pdf_to_json_test_Latn.TOB_Mono_8.json" 2>&1
Latn.TOB_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.TOB/Sans_12/pdf_to_json_test_Latn.TOB_Sans_12.py" > "data/multilingual/Latn.TOB/Sans_12/pdf_to_json_test_Latn.TOB_Sans_12.json" 2>&1
Latn.TOB_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.TOB/Sans_16/pdf_to_json_test_Latn.TOB_Sans_16.py" > "data/multilingual/Latn.TOB/Sans_16/pdf_to_json_test_Latn.TOB_Sans_16.json" 2>&1
Latn.TOB_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.TOB/Sans_8/pdf_to_json_test_Latn.TOB_Sans_8.py" > "data/multilingual/Latn.TOB/Sans_8/pdf_to_json_test_Latn.TOB_Sans_8.json" 2>&1
Latn.TOB_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.TOB/Serif_12/pdf_to_json_test_Latn.TOB_Serif_12.py" > "data/multilingual/Latn.TOB/Serif_12/pdf_to_json_test_Latn.TOB_Serif_12.json" 2>&1
Latn.TOB_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.TOB/Serif_16/pdf_to_json_test_Latn.TOB_Serif_16.py" > "data/multilingual/Latn.TOB/Serif_16/pdf_to_json_test_Latn.TOB_Serif_16.json" 2>&1
Latn.TOB_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.TOB/Serif_8/pdf_to_json_test_Latn.TOB_Serif_8.py" > "data/multilingual/Latn.TOB/Serif_8/pdf_to_json_test_Latn.TOB_Serif_8.json" 2>&1
Latn.TOB_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.TOB/Sun-ExtA_12/pdf_to_json_test_Latn.TOB_Sun-ExtA_12.py" > "data/multilingual/Latn.TOB/Sun-ExtA_12/pdf_to_json_test_Latn.TOB_Sun-ExtA_12.json" 2>&1
Latn.TOB_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.TOB/Sun-ExtA_16/pdf_to_json_test_Latn.TOB_Sun-ExtA_16.py" > "data/multilingual/Latn.TOB/Sun-ExtA_16/pdf_to_json_test_Latn.TOB_Sun-ExtA_16.json" 2>&1
Latn.TOB_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.TOB/Sun-ExtA_8/pdf_to_json_test_Latn.TOB_Sun-ExtA_8.py" > "data/multilingual/Latn.TOB/Sun-ExtA_8/pdf_to_json_test_Latn.TOB_Sun-ExtA_8.json" 2>&1


Latn.TOB_all : Latn.TOB_Mono_12 Latn.TOB_Mono_16 Latn.TOB_Mono_8 Latn.TOB_Sans_12 Latn.TOB_Sans_16 Latn.TOB_Sans_8 Latn.TOB_Serif_12 Latn.TOB_Serif_16 Latn.TOB_Serif_8 Latn.TOB_Sun-ExtA_12 Latn.TOB_Sun-ExtA_16 Latn.TOB_Sun-ExtA_8
