PYTHON=python3


Latn.CRS_Mono_12:
	-$(PYTHON) data/multilingual/Latn.CRS/Mono_12/pdf_to_json_test_Latn.CRS_Mono_12.py > data/multilingual/Latn.CRS/Mono_12/pdf_to_json_test_Latn.CRS_Mono_12.json 2>&1
Latn.CRS_Mono_16:
	-$(PYTHON) data/multilingual/Latn.CRS/Mono_16/pdf_to_json_test_Latn.CRS_Mono_16.py > data/multilingual/Latn.CRS/Mono_16/pdf_to_json_test_Latn.CRS_Mono_16.json 2>&1
Latn.CRS_Mono_8:
	-$(PYTHON) data/multilingual/Latn.CRS/Mono_8/pdf_to_json_test_Latn.CRS_Mono_8.py > data/multilingual/Latn.CRS/Mono_8/pdf_to_json_test_Latn.CRS_Mono_8.json 2>&1
Latn.CRS_Sans_12:
	-$(PYTHON) data/multilingual/Latn.CRS/Sans_12/pdf_to_json_test_Latn.CRS_Sans_12.py > data/multilingual/Latn.CRS/Sans_12/pdf_to_json_test_Latn.CRS_Sans_12.json 2>&1
Latn.CRS_Sans_16:
	-$(PYTHON) data/multilingual/Latn.CRS/Sans_16/pdf_to_json_test_Latn.CRS_Sans_16.py > data/multilingual/Latn.CRS/Sans_16/pdf_to_json_test_Latn.CRS_Sans_16.json 2>&1
Latn.CRS_Sans_8:
	-$(PYTHON) data/multilingual/Latn.CRS/Sans_8/pdf_to_json_test_Latn.CRS_Sans_8.py > data/multilingual/Latn.CRS/Sans_8/pdf_to_json_test_Latn.CRS_Sans_8.json 2>&1
Latn.CRS_Serif_12:
	-$(PYTHON) data/multilingual/Latn.CRS/Serif_12/pdf_to_json_test_Latn.CRS_Serif_12.py > data/multilingual/Latn.CRS/Serif_12/pdf_to_json_test_Latn.CRS_Serif_12.json 2>&1
Latn.CRS_Serif_16:
	-$(PYTHON) data/multilingual/Latn.CRS/Serif_16/pdf_to_json_test_Latn.CRS_Serif_16.py > data/multilingual/Latn.CRS/Serif_16/pdf_to_json_test_Latn.CRS_Serif_16.json 2>&1
Latn.CRS_Serif_8:
	-$(PYTHON) data/multilingual/Latn.CRS/Serif_8/pdf_to_json_test_Latn.CRS_Serif_8.py > data/multilingual/Latn.CRS/Serif_8/pdf_to_json_test_Latn.CRS_Serif_8.json 2>&1
Latn.CRS_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.CRS/Sun-ExtA_12/pdf_to_json_test_Latn.CRS_Sun-ExtA_12.py > data/multilingual/Latn.CRS/Sun-ExtA_12/pdf_to_json_test_Latn.CRS_Sun-ExtA_12.json 2>&1
Latn.CRS_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.CRS/Sun-ExtA_16/pdf_to_json_test_Latn.CRS_Sun-ExtA_16.py > data/multilingual/Latn.CRS/Sun-ExtA_16/pdf_to_json_test_Latn.CRS_Sun-ExtA_16.json 2>&1
Latn.CRS_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.CRS/Sun-ExtA_8/pdf_to_json_test_Latn.CRS_Sun-ExtA_8.py > data/multilingual/Latn.CRS/Sun-ExtA_8/pdf_to_json_test_Latn.CRS_Sun-ExtA_8.json 2>&1


Latn.CRS_all : Latn.CRS_Mono_12 Latn.CRS_Mono_16 Latn.CRS_Mono_8 Latn.CRS_Sans_12 Latn.CRS_Sans_16 Latn.CRS_Sans_8 Latn.CRS_Serif_12 Latn.CRS_Serif_16 Latn.CRS_Serif_8 Latn.CRS_Sun-ExtA_12 Latn.CRS_Sun-ExtA_16 Latn.CRS_Sun-ExtA_8
