PYTHON=python3


Latn.SCO_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.SCO/Mono_12/pdf_to_json_test_Latn.SCO_Mono_12.py" > "data/multilingual/Latn.SCO/Mono_12/pdf_to_json_test_Latn.SCO_Mono_12.json" 2>&1
Latn.SCO_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.SCO/Mono_16/pdf_to_json_test_Latn.SCO_Mono_16.py" > "data/multilingual/Latn.SCO/Mono_16/pdf_to_json_test_Latn.SCO_Mono_16.json" 2>&1
Latn.SCO_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.SCO/Mono_8/pdf_to_json_test_Latn.SCO_Mono_8.py" > "data/multilingual/Latn.SCO/Mono_8/pdf_to_json_test_Latn.SCO_Mono_8.json" 2>&1
Latn.SCO_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.SCO/Sans_12/pdf_to_json_test_Latn.SCO_Sans_12.py" > "data/multilingual/Latn.SCO/Sans_12/pdf_to_json_test_Latn.SCO_Sans_12.json" 2>&1
Latn.SCO_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.SCO/Sans_16/pdf_to_json_test_Latn.SCO_Sans_16.py" > "data/multilingual/Latn.SCO/Sans_16/pdf_to_json_test_Latn.SCO_Sans_16.json" 2>&1
Latn.SCO_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.SCO/Sans_8/pdf_to_json_test_Latn.SCO_Sans_8.py" > "data/multilingual/Latn.SCO/Sans_8/pdf_to_json_test_Latn.SCO_Sans_8.json" 2>&1
Latn.SCO_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.SCO/Serif_12/pdf_to_json_test_Latn.SCO_Serif_12.py" > "data/multilingual/Latn.SCO/Serif_12/pdf_to_json_test_Latn.SCO_Serif_12.json" 2>&1
Latn.SCO_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.SCO/Serif_16/pdf_to_json_test_Latn.SCO_Serif_16.py" > "data/multilingual/Latn.SCO/Serif_16/pdf_to_json_test_Latn.SCO_Serif_16.json" 2>&1
Latn.SCO_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.SCO/Serif_8/pdf_to_json_test_Latn.SCO_Serif_8.py" > "data/multilingual/Latn.SCO/Serif_8/pdf_to_json_test_Latn.SCO_Serif_8.json" 2>&1
Latn.SCO_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.SCO/Sun-ExtA_12/pdf_to_json_test_Latn.SCO_Sun-ExtA_12.py" > "data/multilingual/Latn.SCO/Sun-ExtA_12/pdf_to_json_test_Latn.SCO_Sun-ExtA_12.json" 2>&1
Latn.SCO_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.SCO/Sun-ExtA_16/pdf_to_json_test_Latn.SCO_Sun-ExtA_16.py" > "data/multilingual/Latn.SCO/Sun-ExtA_16/pdf_to_json_test_Latn.SCO_Sun-ExtA_16.json" 2>&1
Latn.SCO_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.SCO/Sun-ExtA_8/pdf_to_json_test_Latn.SCO_Sun-ExtA_8.py" > "data/multilingual/Latn.SCO/Sun-ExtA_8/pdf_to_json_test_Latn.SCO_Sun-ExtA_8.json" 2>&1


Latn.SCO_all : Latn.SCO_Mono_12 Latn.SCO_Mono_16 Latn.SCO_Mono_8 Latn.SCO_Sans_12 Latn.SCO_Sans_16 Latn.SCO_Sans_8 Latn.SCO_Serif_12 Latn.SCO_Serif_16 Latn.SCO_Serif_8 Latn.SCO_Sun-ExtA_12 Latn.SCO_Sun-ExtA_16 Latn.SCO_Sun-ExtA_8
