PYTHON=python3


Latn.DYU_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.DYU/Mono_12/pdf_to_json_test_Latn.DYU_Mono_12.py" > "data/multilingual/Latn.DYU/Mono_12/pdf_to_json_test_Latn.DYU_Mono_12.json" 2>&1
Latn.DYU_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.DYU/Mono_16/pdf_to_json_test_Latn.DYU_Mono_16.py" > "data/multilingual/Latn.DYU/Mono_16/pdf_to_json_test_Latn.DYU_Mono_16.json" 2>&1
Latn.DYU_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.DYU/Mono_8/pdf_to_json_test_Latn.DYU_Mono_8.py" > "data/multilingual/Latn.DYU/Mono_8/pdf_to_json_test_Latn.DYU_Mono_8.json" 2>&1
Latn.DYU_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.DYU/Sans_12/pdf_to_json_test_Latn.DYU_Sans_12.py" > "data/multilingual/Latn.DYU/Sans_12/pdf_to_json_test_Latn.DYU_Sans_12.json" 2>&1
Latn.DYU_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.DYU/Sans_16/pdf_to_json_test_Latn.DYU_Sans_16.py" > "data/multilingual/Latn.DYU/Sans_16/pdf_to_json_test_Latn.DYU_Sans_16.json" 2>&1
Latn.DYU_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.DYU/Sans_8/pdf_to_json_test_Latn.DYU_Sans_8.py" > "data/multilingual/Latn.DYU/Sans_8/pdf_to_json_test_Latn.DYU_Sans_8.json" 2>&1
Latn.DYU_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.DYU/Serif_12/pdf_to_json_test_Latn.DYU_Serif_12.py" > "data/multilingual/Latn.DYU/Serif_12/pdf_to_json_test_Latn.DYU_Serif_12.json" 2>&1
Latn.DYU_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.DYU/Serif_16/pdf_to_json_test_Latn.DYU_Serif_16.py" > "data/multilingual/Latn.DYU/Serif_16/pdf_to_json_test_Latn.DYU_Serif_16.json" 2>&1
Latn.DYU_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.DYU/Serif_8/pdf_to_json_test_Latn.DYU_Serif_8.py" > "data/multilingual/Latn.DYU/Serif_8/pdf_to_json_test_Latn.DYU_Serif_8.json" 2>&1
Latn.DYU_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.DYU/Sun-ExtA_12/pdf_to_json_test_Latn.DYU_Sun-ExtA_12.py" > "data/multilingual/Latn.DYU/Sun-ExtA_12/pdf_to_json_test_Latn.DYU_Sun-ExtA_12.json" 2>&1
Latn.DYU_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.DYU/Sun-ExtA_16/pdf_to_json_test_Latn.DYU_Sun-ExtA_16.py" > "data/multilingual/Latn.DYU/Sun-ExtA_16/pdf_to_json_test_Latn.DYU_Sun-ExtA_16.json" 2>&1
Latn.DYU_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.DYU/Sun-ExtA_8/pdf_to_json_test_Latn.DYU_Sun-ExtA_8.py" > "data/multilingual/Latn.DYU/Sun-ExtA_8/pdf_to_json_test_Latn.DYU_Sun-ExtA_8.json" 2>&1


Latn.DYU_all : Latn.DYU_Mono_12 Latn.DYU_Mono_16 Latn.DYU_Mono_8 Latn.DYU_Sans_12 Latn.DYU_Sans_16 Latn.DYU_Sans_8 Latn.DYU_Serif_12 Latn.DYU_Serif_16 Latn.DYU_Serif_8 Latn.DYU_Sun-ExtA_12 Latn.DYU_Sun-ExtA_16 Latn.DYU_Sun-ExtA_8
