PYTHON=python3


Latn.UND_Mono_12:
	-$(PYTHON) data/multilingual/Latn.UND/Mono_12/pdf_to_json_test_Latn.UND_Mono_12.py > data/multilingual/Latn.UND/Mono_12/pdf_to_json_test_Latn.UND_Mono_12.json 2>&1
Latn.UND_Mono_16:
	-$(PYTHON) data/multilingual/Latn.UND/Mono_16/pdf_to_json_test_Latn.UND_Mono_16.py > data/multilingual/Latn.UND/Mono_16/pdf_to_json_test_Latn.UND_Mono_16.json 2>&1
Latn.UND_Mono_8:
	-$(PYTHON) data/multilingual/Latn.UND/Mono_8/pdf_to_json_test_Latn.UND_Mono_8.py > data/multilingual/Latn.UND/Mono_8/pdf_to_json_test_Latn.UND_Mono_8.json 2>&1
Latn.UND_Sans_12:
	-$(PYTHON) data/multilingual/Latn.UND/Sans_12/pdf_to_json_test_Latn.UND_Sans_12.py > data/multilingual/Latn.UND/Sans_12/pdf_to_json_test_Latn.UND_Sans_12.json 2>&1
Latn.UND_Sans_16:
	-$(PYTHON) data/multilingual/Latn.UND/Sans_16/pdf_to_json_test_Latn.UND_Sans_16.py > data/multilingual/Latn.UND/Sans_16/pdf_to_json_test_Latn.UND_Sans_16.json 2>&1
Latn.UND_Sans_8:
	-$(PYTHON) data/multilingual/Latn.UND/Sans_8/pdf_to_json_test_Latn.UND_Sans_8.py > data/multilingual/Latn.UND/Sans_8/pdf_to_json_test_Latn.UND_Sans_8.json 2>&1
Latn.UND_Serif_12:
	-$(PYTHON) data/multilingual/Latn.UND/Serif_12/pdf_to_json_test_Latn.UND_Serif_12.py > data/multilingual/Latn.UND/Serif_12/pdf_to_json_test_Latn.UND_Serif_12.json 2>&1
Latn.UND_Serif_16:
	-$(PYTHON) data/multilingual/Latn.UND/Serif_16/pdf_to_json_test_Latn.UND_Serif_16.py > data/multilingual/Latn.UND/Serif_16/pdf_to_json_test_Latn.UND_Serif_16.json 2>&1
Latn.UND_Serif_8:
	-$(PYTHON) data/multilingual/Latn.UND/Serif_8/pdf_to_json_test_Latn.UND_Serif_8.py > data/multilingual/Latn.UND/Serif_8/pdf_to_json_test_Latn.UND_Serif_8.json 2>&1
Latn.UND_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.UND/Sun-ExtA_12/pdf_to_json_test_Latn.UND_Sun-ExtA_12.py > data/multilingual/Latn.UND/Sun-ExtA_12/pdf_to_json_test_Latn.UND_Sun-ExtA_12.json 2>&1
Latn.UND_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.UND/Sun-ExtA_16/pdf_to_json_test_Latn.UND_Sun-ExtA_16.py > data/multilingual/Latn.UND/Sun-ExtA_16/pdf_to_json_test_Latn.UND_Sun-ExtA_16.json 2>&1
Latn.UND_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.UND/Sun-ExtA_8/pdf_to_json_test_Latn.UND_Sun-ExtA_8.py > data/multilingual/Latn.UND/Sun-ExtA_8/pdf_to_json_test_Latn.UND_Sun-ExtA_8.json 2>&1


Latn.UND_all : Latn.UND_Mono_12 Latn.UND_Mono_16 Latn.UND_Mono_8 Latn.UND_Sans_12 Latn.UND_Sans_16 Latn.UND_Sans_8 Latn.UND_Serif_12 Latn.UND_Serif_16 Latn.UND_Serif_8 Latn.UND_Sun-ExtA_12 Latn.UND_Sun-ExtA_16 Latn.UND_Sun-ExtA_8
