PYTHON=python3


Latn.ITA_Mono_12:
	-$(PYTHON) data/multilingual/Latn.ITA/Mono_12/pdf_to_json_test_Latn.ITA_Mono_12.py > data/multilingual/Latn.ITA/Mono_12/pdf_to_json_test_Latn.ITA_Mono_12.json 2>&1
Latn.ITA_Mono_16:
	-$(PYTHON) data/multilingual/Latn.ITA/Mono_16/pdf_to_json_test_Latn.ITA_Mono_16.py > data/multilingual/Latn.ITA/Mono_16/pdf_to_json_test_Latn.ITA_Mono_16.json 2>&1
Latn.ITA_Mono_8:
	-$(PYTHON) data/multilingual/Latn.ITA/Mono_8/pdf_to_json_test_Latn.ITA_Mono_8.py > data/multilingual/Latn.ITA/Mono_8/pdf_to_json_test_Latn.ITA_Mono_8.json 2>&1
Latn.ITA_Sans_12:
	-$(PYTHON) data/multilingual/Latn.ITA/Sans_12/pdf_to_json_test_Latn.ITA_Sans_12.py > data/multilingual/Latn.ITA/Sans_12/pdf_to_json_test_Latn.ITA_Sans_12.json 2>&1
Latn.ITA_Sans_16:
	-$(PYTHON) data/multilingual/Latn.ITA/Sans_16/pdf_to_json_test_Latn.ITA_Sans_16.py > data/multilingual/Latn.ITA/Sans_16/pdf_to_json_test_Latn.ITA_Sans_16.json 2>&1
Latn.ITA_Sans_8:
	-$(PYTHON) data/multilingual/Latn.ITA/Sans_8/pdf_to_json_test_Latn.ITA_Sans_8.py > data/multilingual/Latn.ITA/Sans_8/pdf_to_json_test_Latn.ITA_Sans_8.json 2>&1
Latn.ITA_Serif_12:
	-$(PYTHON) data/multilingual/Latn.ITA/Serif_12/pdf_to_json_test_Latn.ITA_Serif_12.py > data/multilingual/Latn.ITA/Serif_12/pdf_to_json_test_Latn.ITA_Serif_12.json 2>&1
Latn.ITA_Serif_16:
	-$(PYTHON) data/multilingual/Latn.ITA/Serif_16/pdf_to_json_test_Latn.ITA_Serif_16.py > data/multilingual/Latn.ITA/Serif_16/pdf_to_json_test_Latn.ITA_Serif_16.json 2>&1
Latn.ITA_Serif_8:
	-$(PYTHON) data/multilingual/Latn.ITA/Serif_8/pdf_to_json_test_Latn.ITA_Serif_8.py > data/multilingual/Latn.ITA/Serif_8/pdf_to_json_test_Latn.ITA_Serif_8.json 2>&1
Latn.ITA_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.ITA/Sun-ExtA_12/pdf_to_json_test_Latn.ITA_Sun-ExtA_12.py > data/multilingual/Latn.ITA/Sun-ExtA_12/pdf_to_json_test_Latn.ITA_Sun-ExtA_12.json 2>&1
Latn.ITA_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.ITA/Sun-ExtA_16/pdf_to_json_test_Latn.ITA_Sun-ExtA_16.py > data/multilingual/Latn.ITA/Sun-ExtA_16/pdf_to_json_test_Latn.ITA_Sun-ExtA_16.json 2>&1
Latn.ITA_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.ITA/Sun-ExtA_8/pdf_to_json_test_Latn.ITA_Sun-ExtA_8.py > data/multilingual/Latn.ITA/Sun-ExtA_8/pdf_to_json_test_Latn.ITA_Sun-ExtA_8.json 2>&1


Latn.ITA_all : Latn.ITA_Mono_12 Latn.ITA_Mono_16 Latn.ITA_Mono_8 Latn.ITA_Sans_12 Latn.ITA_Sans_16 Latn.ITA_Sans_8 Latn.ITA_Serif_12 Latn.ITA_Serif_16 Latn.ITA_Serif_8 Latn.ITA_Sun-ExtA_12 Latn.ITA_Sun-ExtA_16 Latn.ITA_Sun-ExtA_8
