PYTHON=python3


Latn.AFR_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.AFR/Mono_12/pdf_to_json_test_Latn.AFR_Mono_12.py" > "data/multilingual/Latn.AFR/Mono_12/pdf_to_json_test_Latn.AFR_Mono_12.json" 2>&1
Latn.AFR_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.AFR/Mono_16/pdf_to_json_test_Latn.AFR_Mono_16.py" > "data/multilingual/Latn.AFR/Mono_16/pdf_to_json_test_Latn.AFR_Mono_16.json" 2>&1
Latn.AFR_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.AFR/Mono_8/pdf_to_json_test_Latn.AFR_Mono_8.py" > "data/multilingual/Latn.AFR/Mono_8/pdf_to_json_test_Latn.AFR_Mono_8.json" 2>&1
Latn.AFR_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.AFR/Sans_12/pdf_to_json_test_Latn.AFR_Sans_12.py" > "data/multilingual/Latn.AFR/Sans_12/pdf_to_json_test_Latn.AFR_Sans_12.json" 2>&1
Latn.AFR_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.AFR/Sans_16/pdf_to_json_test_Latn.AFR_Sans_16.py" > "data/multilingual/Latn.AFR/Sans_16/pdf_to_json_test_Latn.AFR_Sans_16.json" 2>&1
Latn.AFR_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.AFR/Sans_8/pdf_to_json_test_Latn.AFR_Sans_8.py" > "data/multilingual/Latn.AFR/Sans_8/pdf_to_json_test_Latn.AFR_Sans_8.json" 2>&1
Latn.AFR_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.AFR/Serif_12/pdf_to_json_test_Latn.AFR_Serif_12.py" > "data/multilingual/Latn.AFR/Serif_12/pdf_to_json_test_Latn.AFR_Serif_12.json" 2>&1
Latn.AFR_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.AFR/Serif_16/pdf_to_json_test_Latn.AFR_Serif_16.py" > "data/multilingual/Latn.AFR/Serif_16/pdf_to_json_test_Latn.AFR_Serif_16.json" 2>&1
Latn.AFR_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.AFR/Serif_8/pdf_to_json_test_Latn.AFR_Serif_8.py" > "data/multilingual/Latn.AFR/Serif_8/pdf_to_json_test_Latn.AFR_Serif_8.json" 2>&1
Latn.AFR_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.AFR/Sun-ExtA_12/pdf_to_json_test_Latn.AFR_Sun-ExtA_12.py" > "data/multilingual/Latn.AFR/Sun-ExtA_12/pdf_to_json_test_Latn.AFR_Sun-ExtA_12.json" 2>&1
Latn.AFR_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.AFR/Sun-ExtA_16/pdf_to_json_test_Latn.AFR_Sun-ExtA_16.py" > "data/multilingual/Latn.AFR/Sun-ExtA_16/pdf_to_json_test_Latn.AFR_Sun-ExtA_16.json" 2>&1
Latn.AFR_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.AFR/Sun-ExtA_8/pdf_to_json_test_Latn.AFR_Sun-ExtA_8.py" > "data/multilingual/Latn.AFR/Sun-ExtA_8/pdf_to_json_test_Latn.AFR_Sun-ExtA_8.json" 2>&1


Latn.AFR_all : Latn.AFR_Mono_12 Latn.AFR_Mono_16 Latn.AFR_Mono_8 Latn.AFR_Sans_12 Latn.AFR_Sans_16 Latn.AFR_Sans_8 Latn.AFR_Serif_12 Latn.AFR_Serif_16 Latn.AFR_Serif_8 Latn.AFR_Sun-ExtA_12 Latn.AFR_Sun-ExtA_16 Latn.AFR_Sun-ExtA_8
