PYTHON=python3


Cyrl.UZN_Mono_12:
	-$(PYTHON) data/multilingual/Cyrl.UZN/Mono_12/pdf_to_json_test_Cyrl.UZN_Mono_12.py > data/multilingual/Cyrl.UZN/Mono_12/pdf_to_json_test_Cyrl.UZN_Mono_12.json 2>&1
Cyrl.UZN_Mono_16:
	-$(PYTHON) data/multilingual/Cyrl.UZN/Mono_16/pdf_to_json_test_Cyrl.UZN_Mono_16.py > data/multilingual/Cyrl.UZN/Mono_16/pdf_to_json_test_Cyrl.UZN_Mono_16.json 2>&1
Cyrl.UZN_Mono_8:
	-$(PYTHON) data/multilingual/Cyrl.UZN/Mono_8/pdf_to_json_test_Cyrl.UZN_Mono_8.py > data/multilingual/Cyrl.UZN/Mono_8/pdf_to_json_test_Cyrl.UZN_Mono_8.json 2>&1
Cyrl.UZN_Sans_12:
	-$(PYTHON) data/multilingual/Cyrl.UZN/Sans_12/pdf_to_json_test_Cyrl.UZN_Sans_12.py > data/multilingual/Cyrl.UZN/Sans_12/pdf_to_json_test_Cyrl.UZN_Sans_12.json 2>&1
Cyrl.UZN_Sans_16:
	-$(PYTHON) data/multilingual/Cyrl.UZN/Sans_16/pdf_to_json_test_Cyrl.UZN_Sans_16.py > data/multilingual/Cyrl.UZN/Sans_16/pdf_to_json_test_Cyrl.UZN_Sans_16.json 2>&1
Cyrl.UZN_Sans_8:
	-$(PYTHON) data/multilingual/Cyrl.UZN/Sans_8/pdf_to_json_test_Cyrl.UZN_Sans_8.py > data/multilingual/Cyrl.UZN/Sans_8/pdf_to_json_test_Cyrl.UZN_Sans_8.json 2>&1
Cyrl.UZN_Serif_12:
	-$(PYTHON) data/multilingual/Cyrl.UZN/Serif_12/pdf_to_json_test_Cyrl.UZN_Serif_12.py > data/multilingual/Cyrl.UZN/Serif_12/pdf_to_json_test_Cyrl.UZN_Serif_12.json 2>&1
Cyrl.UZN_Serif_16:
	-$(PYTHON) data/multilingual/Cyrl.UZN/Serif_16/pdf_to_json_test_Cyrl.UZN_Serif_16.py > data/multilingual/Cyrl.UZN/Serif_16/pdf_to_json_test_Cyrl.UZN_Serif_16.json 2>&1
Cyrl.UZN_Serif_8:
	-$(PYTHON) data/multilingual/Cyrl.UZN/Serif_8/pdf_to_json_test_Cyrl.UZN_Serif_8.py > data/multilingual/Cyrl.UZN/Serif_8/pdf_to_json_test_Cyrl.UZN_Serif_8.json 2>&1
Cyrl.UZN_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Cyrl.UZN/Sun-ExtA_12/pdf_to_json_test_Cyrl.UZN_Sun-ExtA_12.py > data/multilingual/Cyrl.UZN/Sun-ExtA_12/pdf_to_json_test_Cyrl.UZN_Sun-ExtA_12.json 2>&1
Cyrl.UZN_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Cyrl.UZN/Sun-ExtA_16/pdf_to_json_test_Cyrl.UZN_Sun-ExtA_16.py > data/multilingual/Cyrl.UZN/Sun-ExtA_16/pdf_to_json_test_Cyrl.UZN_Sun-ExtA_16.json 2>&1
Cyrl.UZN_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Cyrl.UZN/Sun-ExtA_8/pdf_to_json_test_Cyrl.UZN_Sun-ExtA_8.py > data/multilingual/Cyrl.UZN/Sun-ExtA_8/pdf_to_json_test_Cyrl.UZN_Sun-ExtA_8.json 2>&1


Cyrl.UZN_all : Cyrl.UZN_Mono_12 Cyrl.UZN_Mono_16 Cyrl.UZN_Mono_8 Cyrl.UZN_Sans_12 Cyrl.UZN_Sans_16 Cyrl.UZN_Sans_8 Cyrl.UZN_Serif_12 Cyrl.UZN_Serif_16 Cyrl.UZN_Serif_8 Cyrl.UZN_Sun-ExtA_12 Cyrl.UZN_Sun-ExtA_16 Cyrl.UZN_Sun-ExtA_8
