PYTHON=python3


Latn.KQN_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.KQN/Mono_12/pdf_to_json_test_Latn.KQN_Mono_12.py" > "data/multilingual/Latn.KQN/Mono_12/pdf_to_json_test_Latn.KQN_Mono_12.json" 2>&1
Latn.KQN_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.KQN/Mono_16/pdf_to_json_test_Latn.KQN_Mono_16.py" > "data/multilingual/Latn.KQN/Mono_16/pdf_to_json_test_Latn.KQN_Mono_16.json" 2>&1
Latn.KQN_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.KQN/Mono_8/pdf_to_json_test_Latn.KQN_Mono_8.py" > "data/multilingual/Latn.KQN/Mono_8/pdf_to_json_test_Latn.KQN_Mono_8.json" 2>&1
Latn.KQN_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.KQN/Sans_12/pdf_to_json_test_Latn.KQN_Sans_12.py" > "data/multilingual/Latn.KQN/Sans_12/pdf_to_json_test_Latn.KQN_Sans_12.json" 2>&1
Latn.KQN_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.KQN/Sans_16/pdf_to_json_test_Latn.KQN_Sans_16.py" > "data/multilingual/Latn.KQN/Sans_16/pdf_to_json_test_Latn.KQN_Sans_16.json" 2>&1
Latn.KQN_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.KQN/Sans_8/pdf_to_json_test_Latn.KQN_Sans_8.py" > "data/multilingual/Latn.KQN/Sans_8/pdf_to_json_test_Latn.KQN_Sans_8.json" 2>&1
Latn.KQN_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.KQN/Serif_12/pdf_to_json_test_Latn.KQN_Serif_12.py" > "data/multilingual/Latn.KQN/Serif_12/pdf_to_json_test_Latn.KQN_Serif_12.json" 2>&1
Latn.KQN_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.KQN/Serif_16/pdf_to_json_test_Latn.KQN_Serif_16.py" > "data/multilingual/Latn.KQN/Serif_16/pdf_to_json_test_Latn.KQN_Serif_16.json" 2>&1
Latn.KQN_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.KQN/Serif_8/pdf_to_json_test_Latn.KQN_Serif_8.py" > "data/multilingual/Latn.KQN/Serif_8/pdf_to_json_test_Latn.KQN_Serif_8.json" 2>&1
Latn.KQN_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.KQN/Sun-ExtA_12/pdf_to_json_test_Latn.KQN_Sun-ExtA_12.py" > "data/multilingual/Latn.KQN/Sun-ExtA_12/pdf_to_json_test_Latn.KQN_Sun-ExtA_12.json" 2>&1
Latn.KQN_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.KQN/Sun-ExtA_16/pdf_to_json_test_Latn.KQN_Sun-ExtA_16.py" > "data/multilingual/Latn.KQN/Sun-ExtA_16/pdf_to_json_test_Latn.KQN_Sun-ExtA_16.json" 2>&1
Latn.KQN_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.KQN/Sun-ExtA_8/pdf_to_json_test_Latn.KQN_Sun-ExtA_8.py" > "data/multilingual/Latn.KQN/Sun-ExtA_8/pdf_to_json_test_Latn.KQN_Sun-ExtA_8.json" 2>&1


Latn.KQN_all : Latn.KQN_Mono_12 Latn.KQN_Mono_16 Latn.KQN_Mono_8 Latn.KQN_Sans_12 Latn.KQN_Sans_16 Latn.KQN_Sans_8 Latn.KQN_Serif_12 Latn.KQN_Serif_16 Latn.KQN_Serif_8 Latn.KQN_Sun-ExtA_12 Latn.KQN_Sun-ExtA_16 Latn.KQN_Sun-ExtA_8
