PYTHON=python3


Latn.VIE_Mono_12:
	-$(PYTHON) data/multilingual/Latn.VIE/Mono_12/pdf_to_json_test_Latn.VIE_Mono_12.py > data/multilingual/Latn.VIE/Mono_12/pdf_to_json_test_Latn.VIE_Mono_12.json 2>&1
Latn.VIE_Mono_16:
	-$(PYTHON) data/multilingual/Latn.VIE/Mono_16/pdf_to_json_test_Latn.VIE_Mono_16.py > data/multilingual/Latn.VIE/Mono_16/pdf_to_json_test_Latn.VIE_Mono_16.json 2>&1
Latn.VIE_Mono_8:
	-$(PYTHON) data/multilingual/Latn.VIE/Mono_8/pdf_to_json_test_Latn.VIE_Mono_8.py > data/multilingual/Latn.VIE/Mono_8/pdf_to_json_test_Latn.VIE_Mono_8.json 2>&1
Latn.VIE_Sans_12:
	-$(PYTHON) data/multilingual/Latn.VIE/Sans_12/pdf_to_json_test_Latn.VIE_Sans_12.py > data/multilingual/Latn.VIE/Sans_12/pdf_to_json_test_Latn.VIE_Sans_12.json 2>&1
Latn.VIE_Sans_16:
	-$(PYTHON) data/multilingual/Latn.VIE/Sans_16/pdf_to_json_test_Latn.VIE_Sans_16.py > data/multilingual/Latn.VIE/Sans_16/pdf_to_json_test_Latn.VIE_Sans_16.json 2>&1
Latn.VIE_Sans_8:
	-$(PYTHON) data/multilingual/Latn.VIE/Sans_8/pdf_to_json_test_Latn.VIE_Sans_8.py > data/multilingual/Latn.VIE/Sans_8/pdf_to_json_test_Latn.VIE_Sans_8.json 2>&1
Latn.VIE_Serif_12:
	-$(PYTHON) data/multilingual/Latn.VIE/Serif_12/pdf_to_json_test_Latn.VIE_Serif_12.py > data/multilingual/Latn.VIE/Serif_12/pdf_to_json_test_Latn.VIE_Serif_12.json 2>&1
Latn.VIE_Serif_16:
	-$(PYTHON) data/multilingual/Latn.VIE/Serif_16/pdf_to_json_test_Latn.VIE_Serif_16.py > data/multilingual/Latn.VIE/Serif_16/pdf_to_json_test_Latn.VIE_Serif_16.json 2>&1
Latn.VIE_Serif_8:
	-$(PYTHON) data/multilingual/Latn.VIE/Serif_8/pdf_to_json_test_Latn.VIE_Serif_8.py > data/multilingual/Latn.VIE/Serif_8/pdf_to_json_test_Latn.VIE_Serif_8.json 2>&1
Latn.VIE_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.VIE/Sun-ExtA_12/pdf_to_json_test_Latn.VIE_Sun-ExtA_12.py > data/multilingual/Latn.VIE/Sun-ExtA_12/pdf_to_json_test_Latn.VIE_Sun-ExtA_12.json 2>&1
Latn.VIE_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.VIE/Sun-ExtA_16/pdf_to_json_test_Latn.VIE_Sun-ExtA_16.py > data/multilingual/Latn.VIE/Sun-ExtA_16/pdf_to_json_test_Latn.VIE_Sun-ExtA_16.json 2>&1
Latn.VIE_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.VIE/Sun-ExtA_8/pdf_to_json_test_Latn.VIE_Sun-ExtA_8.py > data/multilingual/Latn.VIE/Sun-ExtA_8/pdf_to_json_test_Latn.VIE_Sun-ExtA_8.json 2>&1


Latn.VIE_all : Latn.VIE_Mono_12 Latn.VIE_Mono_16 Latn.VIE_Mono_8 Latn.VIE_Sans_12 Latn.VIE_Sans_16 Latn.VIE_Sans_8 Latn.VIE_Serif_12 Latn.VIE_Serif_16 Latn.VIE_Serif_8 Latn.VIE_Sun-ExtA_12 Latn.VIE_Sun-ExtA_16 Latn.VIE_Sun-ExtA_8
