PYTHON=python3


Laoo.LAO_Mono_12:
	-$(PYTHON) data/multilingual/Laoo.LAO/Mono_12/pdf_to_json_test_Laoo.LAO_Mono_12.py > data/multilingual/Laoo.LAO/Mono_12/pdf_to_json_test_Laoo.LAO_Mono_12.json 2>&1
Laoo.LAO_Mono_16:
	-$(PYTHON) data/multilingual/Laoo.LAO/Mono_16/pdf_to_json_test_Laoo.LAO_Mono_16.py > data/multilingual/Laoo.LAO/Mono_16/pdf_to_json_test_Laoo.LAO_Mono_16.json 2>&1
Laoo.LAO_Mono_8:
	-$(PYTHON) data/multilingual/Laoo.LAO/Mono_8/pdf_to_json_test_Laoo.LAO_Mono_8.py > data/multilingual/Laoo.LAO/Mono_8/pdf_to_json_test_Laoo.LAO_Mono_8.json 2>&1
Laoo.LAO_Sans_12:
	-$(PYTHON) data/multilingual/Laoo.LAO/Sans_12/pdf_to_json_test_Laoo.LAO_Sans_12.py > data/multilingual/Laoo.LAO/Sans_12/pdf_to_json_test_Laoo.LAO_Sans_12.json 2>&1
Laoo.LAO_Sans_16:
	-$(PYTHON) data/multilingual/Laoo.LAO/Sans_16/pdf_to_json_test_Laoo.LAO_Sans_16.py > data/multilingual/Laoo.LAO/Sans_16/pdf_to_json_test_Laoo.LAO_Sans_16.json 2>&1
Laoo.LAO_Sans_8:
	-$(PYTHON) data/multilingual/Laoo.LAO/Sans_8/pdf_to_json_test_Laoo.LAO_Sans_8.py > data/multilingual/Laoo.LAO/Sans_8/pdf_to_json_test_Laoo.LAO_Sans_8.json 2>&1
Laoo.LAO_Serif_12:
	-$(PYTHON) data/multilingual/Laoo.LAO/Serif_12/pdf_to_json_test_Laoo.LAO_Serif_12.py > data/multilingual/Laoo.LAO/Serif_12/pdf_to_json_test_Laoo.LAO_Serif_12.json 2>&1
Laoo.LAO_Serif_16:
	-$(PYTHON) data/multilingual/Laoo.LAO/Serif_16/pdf_to_json_test_Laoo.LAO_Serif_16.py > data/multilingual/Laoo.LAO/Serif_16/pdf_to_json_test_Laoo.LAO_Serif_16.json 2>&1
Laoo.LAO_Serif_8:
	-$(PYTHON) data/multilingual/Laoo.LAO/Serif_8/pdf_to_json_test_Laoo.LAO_Serif_8.py > data/multilingual/Laoo.LAO/Serif_8/pdf_to_json_test_Laoo.LAO_Serif_8.json 2>&1
Laoo.LAO_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Laoo.LAO/Sun-ExtA_12/pdf_to_json_test_Laoo.LAO_Sun-ExtA_12.py > data/multilingual/Laoo.LAO/Sun-ExtA_12/pdf_to_json_test_Laoo.LAO_Sun-ExtA_12.json 2>&1
Laoo.LAO_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Laoo.LAO/Sun-ExtA_16/pdf_to_json_test_Laoo.LAO_Sun-ExtA_16.py > data/multilingual/Laoo.LAO/Sun-ExtA_16/pdf_to_json_test_Laoo.LAO_Sun-ExtA_16.json 2>&1
Laoo.LAO_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Laoo.LAO/Sun-ExtA_8/pdf_to_json_test_Laoo.LAO_Sun-ExtA_8.py > data/multilingual/Laoo.LAO/Sun-ExtA_8/pdf_to_json_test_Laoo.LAO_Sun-ExtA_8.json 2>&1


Laoo.LAO_all : Laoo.LAO_Mono_12 Laoo.LAO_Mono_16 Laoo.LAO_Mono_8 Laoo.LAO_Sans_12 Laoo.LAO_Sans_16 Laoo.LAO_Sans_8 Laoo.LAO_Serif_12 Laoo.LAO_Serif_16 Laoo.LAO_Serif_8 Laoo.LAO_Sun-ExtA_12 Laoo.LAO_Sun-ExtA_16 Laoo.LAO_Sun-ExtA_8
