PYTHON=python3


Latn.BRE_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.BRE/Mono_12/pdf_to_json_test_Latn.BRE_Mono_12.py" > "data/multilingual/Latn.BRE/Mono_12/pdf_to_json_test_Latn.BRE_Mono_12.json" 2>&1
Latn.BRE_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.BRE/Mono_16/pdf_to_json_test_Latn.BRE_Mono_16.py" > "data/multilingual/Latn.BRE/Mono_16/pdf_to_json_test_Latn.BRE_Mono_16.json" 2>&1
Latn.BRE_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.BRE/Mono_8/pdf_to_json_test_Latn.BRE_Mono_8.py" > "data/multilingual/Latn.BRE/Mono_8/pdf_to_json_test_Latn.BRE_Mono_8.json" 2>&1
Latn.BRE_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.BRE/Sans_12/pdf_to_json_test_Latn.BRE_Sans_12.py" > "data/multilingual/Latn.BRE/Sans_12/pdf_to_json_test_Latn.BRE_Sans_12.json" 2>&1
Latn.BRE_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.BRE/Sans_16/pdf_to_json_test_Latn.BRE_Sans_16.py" > "data/multilingual/Latn.BRE/Sans_16/pdf_to_json_test_Latn.BRE_Sans_16.json" 2>&1
Latn.BRE_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.BRE/Sans_8/pdf_to_json_test_Latn.BRE_Sans_8.py" > "data/multilingual/Latn.BRE/Sans_8/pdf_to_json_test_Latn.BRE_Sans_8.json" 2>&1
Latn.BRE_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.BRE/Serif_12/pdf_to_json_test_Latn.BRE_Serif_12.py" > "data/multilingual/Latn.BRE/Serif_12/pdf_to_json_test_Latn.BRE_Serif_12.json" 2>&1
Latn.BRE_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.BRE/Serif_16/pdf_to_json_test_Latn.BRE_Serif_16.py" > "data/multilingual/Latn.BRE/Serif_16/pdf_to_json_test_Latn.BRE_Serif_16.json" 2>&1
Latn.BRE_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.BRE/Serif_8/pdf_to_json_test_Latn.BRE_Serif_8.py" > "data/multilingual/Latn.BRE/Serif_8/pdf_to_json_test_Latn.BRE_Serif_8.json" 2>&1
Latn.BRE_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.BRE/Sun-ExtA_12/pdf_to_json_test_Latn.BRE_Sun-ExtA_12.py" > "data/multilingual/Latn.BRE/Sun-ExtA_12/pdf_to_json_test_Latn.BRE_Sun-ExtA_12.json" 2>&1
Latn.BRE_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.BRE/Sun-ExtA_16/pdf_to_json_test_Latn.BRE_Sun-ExtA_16.py" > "data/multilingual/Latn.BRE/Sun-ExtA_16/pdf_to_json_test_Latn.BRE_Sun-ExtA_16.json" 2>&1
Latn.BRE_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.BRE/Sun-ExtA_8/pdf_to_json_test_Latn.BRE_Sun-ExtA_8.py" > "data/multilingual/Latn.BRE/Sun-ExtA_8/pdf_to_json_test_Latn.BRE_Sun-ExtA_8.json" 2>&1


Latn.BRE_all : Latn.BRE_Mono_12 Latn.BRE_Mono_16 Latn.BRE_Mono_8 Latn.BRE_Sans_12 Latn.BRE_Sans_16 Latn.BRE_Sans_8 Latn.BRE_Serif_12 Latn.BRE_Serif_16 Latn.BRE_Serif_8 Latn.BRE_Sun-ExtA_12 Latn.BRE_Sun-ExtA_16 Latn.BRE_Sun-ExtA_8
