PYTHON=python3


Cyrl.KOI_Mono_12:
	-$(PYTHON) data/multilingual/Cyrl.KOI/Mono_12/pdf_to_json_test_Cyrl.KOI_Mono_12.py > data/multilingual/Cyrl.KOI/Mono_12/pdf_to_json_test_Cyrl.KOI_Mono_12.json 2>&1
Cyrl.KOI_Mono_16:
	-$(PYTHON) data/multilingual/Cyrl.KOI/Mono_16/pdf_to_json_test_Cyrl.KOI_Mono_16.py > data/multilingual/Cyrl.KOI/Mono_16/pdf_to_json_test_Cyrl.KOI_Mono_16.json 2>&1
Cyrl.KOI_Mono_8:
	-$(PYTHON) data/multilingual/Cyrl.KOI/Mono_8/pdf_to_json_test_Cyrl.KOI_Mono_8.py > data/multilingual/Cyrl.KOI/Mono_8/pdf_to_json_test_Cyrl.KOI_Mono_8.json 2>&1
Cyrl.KOI_Sans_12:
	-$(PYTHON) data/multilingual/Cyrl.KOI/Sans_12/pdf_to_json_test_Cyrl.KOI_Sans_12.py > data/multilingual/Cyrl.KOI/Sans_12/pdf_to_json_test_Cyrl.KOI_Sans_12.json 2>&1
Cyrl.KOI_Sans_16:
	-$(PYTHON) data/multilingual/Cyrl.KOI/Sans_16/pdf_to_json_test_Cyrl.KOI_Sans_16.py > data/multilingual/Cyrl.KOI/Sans_16/pdf_to_json_test_Cyrl.KOI_Sans_16.json 2>&1
Cyrl.KOI_Sans_8:
	-$(PYTHON) data/multilingual/Cyrl.KOI/Sans_8/pdf_to_json_test_Cyrl.KOI_Sans_8.py > data/multilingual/Cyrl.KOI/Sans_8/pdf_to_json_test_Cyrl.KOI_Sans_8.json 2>&1
Cyrl.KOI_Serif_12:
	-$(PYTHON) data/multilingual/Cyrl.KOI/Serif_12/pdf_to_json_test_Cyrl.KOI_Serif_12.py > data/multilingual/Cyrl.KOI/Serif_12/pdf_to_json_test_Cyrl.KOI_Serif_12.json 2>&1
Cyrl.KOI_Serif_16:
	-$(PYTHON) data/multilingual/Cyrl.KOI/Serif_16/pdf_to_json_test_Cyrl.KOI_Serif_16.py > data/multilingual/Cyrl.KOI/Serif_16/pdf_to_json_test_Cyrl.KOI_Serif_16.json 2>&1
Cyrl.KOI_Serif_8:
	-$(PYTHON) data/multilingual/Cyrl.KOI/Serif_8/pdf_to_json_test_Cyrl.KOI_Serif_8.py > data/multilingual/Cyrl.KOI/Serif_8/pdf_to_json_test_Cyrl.KOI_Serif_8.json 2>&1
Cyrl.KOI_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Cyrl.KOI/Sun-ExtA_12/pdf_to_json_test_Cyrl.KOI_Sun-ExtA_12.py > data/multilingual/Cyrl.KOI/Sun-ExtA_12/pdf_to_json_test_Cyrl.KOI_Sun-ExtA_12.json 2>&1
Cyrl.KOI_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Cyrl.KOI/Sun-ExtA_16/pdf_to_json_test_Cyrl.KOI_Sun-ExtA_16.py > data/multilingual/Cyrl.KOI/Sun-ExtA_16/pdf_to_json_test_Cyrl.KOI_Sun-ExtA_16.json 2>&1
Cyrl.KOI_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Cyrl.KOI/Sun-ExtA_8/pdf_to_json_test_Cyrl.KOI_Sun-ExtA_8.py > data/multilingual/Cyrl.KOI/Sun-ExtA_8/pdf_to_json_test_Cyrl.KOI_Sun-ExtA_8.json 2>&1


Cyrl.KOI_all : Cyrl.KOI_Mono_12 Cyrl.KOI_Mono_16 Cyrl.KOI_Mono_8 Cyrl.KOI_Sans_12 Cyrl.KOI_Sans_16 Cyrl.KOI_Sans_8 Cyrl.KOI_Serif_12 Cyrl.KOI_Serif_16 Cyrl.KOI_Serif_8 Cyrl.KOI_Sun-ExtA_12 Cyrl.KOI_Sun-ExtA_16 Cyrl.KOI_Sun-ExtA_8
