PYTHON=python3


Latn.MXI_Mono_12:
	-$(PYTHON) data/multilingual/Latn.MXI/Mono_12/pdf_to_json_test_Latn.MXI_Mono_12.py > data/multilingual/Latn.MXI/Mono_12/pdf_to_json_test_Latn.MXI_Mono_12.json 2>&1
Latn.MXI_Mono_16:
	-$(PYTHON) data/multilingual/Latn.MXI/Mono_16/pdf_to_json_test_Latn.MXI_Mono_16.py > data/multilingual/Latn.MXI/Mono_16/pdf_to_json_test_Latn.MXI_Mono_16.json 2>&1
Latn.MXI_Mono_8:
	-$(PYTHON) data/multilingual/Latn.MXI/Mono_8/pdf_to_json_test_Latn.MXI_Mono_8.py > data/multilingual/Latn.MXI/Mono_8/pdf_to_json_test_Latn.MXI_Mono_8.json 2>&1
Latn.MXI_Sans_12:
	-$(PYTHON) data/multilingual/Latn.MXI/Sans_12/pdf_to_json_test_Latn.MXI_Sans_12.py > data/multilingual/Latn.MXI/Sans_12/pdf_to_json_test_Latn.MXI_Sans_12.json 2>&1
Latn.MXI_Sans_16:
	-$(PYTHON) data/multilingual/Latn.MXI/Sans_16/pdf_to_json_test_Latn.MXI_Sans_16.py > data/multilingual/Latn.MXI/Sans_16/pdf_to_json_test_Latn.MXI_Sans_16.json 2>&1
Latn.MXI_Sans_8:
	-$(PYTHON) data/multilingual/Latn.MXI/Sans_8/pdf_to_json_test_Latn.MXI_Sans_8.py > data/multilingual/Latn.MXI/Sans_8/pdf_to_json_test_Latn.MXI_Sans_8.json 2>&1
Latn.MXI_Serif_12:
	-$(PYTHON) data/multilingual/Latn.MXI/Serif_12/pdf_to_json_test_Latn.MXI_Serif_12.py > data/multilingual/Latn.MXI/Serif_12/pdf_to_json_test_Latn.MXI_Serif_12.json 2>&1
Latn.MXI_Serif_16:
	-$(PYTHON) data/multilingual/Latn.MXI/Serif_16/pdf_to_json_test_Latn.MXI_Serif_16.py > data/multilingual/Latn.MXI/Serif_16/pdf_to_json_test_Latn.MXI_Serif_16.json 2>&1
Latn.MXI_Serif_8:
	-$(PYTHON) data/multilingual/Latn.MXI/Serif_8/pdf_to_json_test_Latn.MXI_Serif_8.py > data/multilingual/Latn.MXI/Serif_8/pdf_to_json_test_Latn.MXI_Serif_8.json 2>&1
Latn.MXI_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.MXI/Sun-ExtA_12/pdf_to_json_test_Latn.MXI_Sun-ExtA_12.py > data/multilingual/Latn.MXI/Sun-ExtA_12/pdf_to_json_test_Latn.MXI_Sun-ExtA_12.json 2>&1
Latn.MXI_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.MXI/Sun-ExtA_16/pdf_to_json_test_Latn.MXI_Sun-ExtA_16.py > data/multilingual/Latn.MXI/Sun-ExtA_16/pdf_to_json_test_Latn.MXI_Sun-ExtA_16.json 2>&1
Latn.MXI_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.MXI/Sun-ExtA_8/pdf_to_json_test_Latn.MXI_Sun-ExtA_8.py > data/multilingual/Latn.MXI/Sun-ExtA_8/pdf_to_json_test_Latn.MXI_Sun-ExtA_8.json 2>&1


Latn.MXI_all : Latn.MXI_Mono_12 Latn.MXI_Mono_16 Latn.MXI_Mono_8 Latn.MXI_Sans_12 Latn.MXI_Sans_16 Latn.MXI_Sans_8 Latn.MXI_Serif_12 Latn.MXI_Serif_16 Latn.MXI_Serif_8 Latn.MXI_Sun-ExtA_12 Latn.MXI_Sun-ExtA_16 Latn.MXI_Sun-ExtA_8
