PYTHON=python3


Yiii.III_Mono_12:
	-$(PYTHON) "data/multilingual/Yiii.III/Mono_12/pdf_to_json_test_Yiii.III_Mono_12.py" > "data/multilingual/Yiii.III/Mono_12/pdf_to_json_test_Yiii.III_Mono_12.json" 2>&1
Yiii.III_Mono_16:
	-$(PYTHON) "data/multilingual/Yiii.III/Mono_16/pdf_to_json_test_Yiii.III_Mono_16.py" > "data/multilingual/Yiii.III/Mono_16/pdf_to_json_test_Yiii.III_Mono_16.json" 2>&1
Yiii.III_Mono_8:
	-$(PYTHON) "data/multilingual/Yiii.III/Mono_8/pdf_to_json_test_Yiii.III_Mono_8.py" > "data/multilingual/Yiii.III/Mono_8/pdf_to_json_test_Yiii.III_Mono_8.json" 2>&1
Yiii.III_Sans_12:
	-$(PYTHON) "data/multilingual/Yiii.III/Sans_12/pdf_to_json_test_Yiii.III_Sans_12.py" > "data/multilingual/Yiii.III/Sans_12/pdf_to_json_test_Yiii.III_Sans_12.json" 2>&1
Yiii.III_Sans_16:
	-$(PYTHON) "data/multilingual/Yiii.III/Sans_16/pdf_to_json_test_Yiii.III_Sans_16.py" > "data/multilingual/Yiii.III/Sans_16/pdf_to_json_test_Yiii.III_Sans_16.json" 2>&1
Yiii.III_Sans_8:
	-$(PYTHON) "data/multilingual/Yiii.III/Sans_8/pdf_to_json_test_Yiii.III_Sans_8.py" > "data/multilingual/Yiii.III/Sans_8/pdf_to_json_test_Yiii.III_Sans_8.json" 2>&1
Yiii.III_Serif_12:
	-$(PYTHON) "data/multilingual/Yiii.III/Serif_12/pdf_to_json_test_Yiii.III_Serif_12.py" > "data/multilingual/Yiii.III/Serif_12/pdf_to_json_test_Yiii.III_Serif_12.json" 2>&1
Yiii.III_Serif_16:
	-$(PYTHON) "data/multilingual/Yiii.III/Serif_16/pdf_to_json_test_Yiii.III_Serif_16.py" > "data/multilingual/Yiii.III/Serif_16/pdf_to_json_test_Yiii.III_Serif_16.json" 2>&1
Yiii.III_Serif_8:
	-$(PYTHON) "data/multilingual/Yiii.III/Serif_8/pdf_to_json_test_Yiii.III_Serif_8.py" > "data/multilingual/Yiii.III/Serif_8/pdf_to_json_test_Yiii.III_Serif_8.json" 2>&1
Yiii.III_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Yiii.III/Sun-ExtA_12/pdf_to_json_test_Yiii.III_Sun-ExtA_12.py" > "data/multilingual/Yiii.III/Sun-ExtA_12/pdf_to_json_test_Yiii.III_Sun-ExtA_12.json" 2>&1
Yiii.III_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Yiii.III/Sun-ExtA_16/pdf_to_json_test_Yiii.III_Sun-ExtA_16.py" > "data/multilingual/Yiii.III/Sun-ExtA_16/pdf_to_json_test_Yiii.III_Sun-ExtA_16.json" 2>&1
Yiii.III_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Yiii.III/Sun-ExtA_8/pdf_to_json_test_Yiii.III_Sun-ExtA_8.py" > "data/multilingual/Yiii.III/Sun-ExtA_8/pdf_to_json_test_Yiii.III_Sun-ExtA_8.json" 2>&1


Yiii.III_all : Yiii.III_Mono_12 Yiii.III_Mono_16 Yiii.III_Mono_8 Yiii.III_Sans_12 Yiii.III_Sans_16 Yiii.III_Sans_8 Yiii.III_Serif_12 Yiii.III_Serif_16 Yiii.III_Serif_8 Yiii.III_Sun-ExtA_12 Yiii.III_Sun-ExtA_16 Yiii.III_Sun-ExtA_8
