PYTHON=python3


Cyrl.KJH_Mono_12:
	-$(PYTHON) data/multilingual/Cyrl.KJH/Mono_12/pdf_to_json_test_Cyrl.KJH_Mono_12.py > data/multilingual/Cyrl.KJH/Mono_12/pdf_to_json_test_Cyrl.KJH_Mono_12.json 2>&1
Cyrl.KJH_Mono_16:
	-$(PYTHON) data/multilingual/Cyrl.KJH/Mono_16/pdf_to_json_test_Cyrl.KJH_Mono_16.py > data/multilingual/Cyrl.KJH/Mono_16/pdf_to_json_test_Cyrl.KJH_Mono_16.json 2>&1
Cyrl.KJH_Mono_8:
	-$(PYTHON) data/multilingual/Cyrl.KJH/Mono_8/pdf_to_json_test_Cyrl.KJH_Mono_8.py > data/multilingual/Cyrl.KJH/Mono_8/pdf_to_json_test_Cyrl.KJH_Mono_8.json 2>&1
Cyrl.KJH_Sans_12:
	-$(PYTHON) data/multilingual/Cyrl.KJH/Sans_12/pdf_to_json_test_Cyrl.KJH_Sans_12.py > data/multilingual/Cyrl.KJH/Sans_12/pdf_to_json_test_Cyrl.KJH_Sans_12.json 2>&1
Cyrl.KJH_Sans_16:
	-$(PYTHON) data/multilingual/Cyrl.KJH/Sans_16/pdf_to_json_test_Cyrl.KJH_Sans_16.py > data/multilingual/Cyrl.KJH/Sans_16/pdf_to_json_test_Cyrl.KJH_Sans_16.json 2>&1
Cyrl.KJH_Sans_8:
	-$(PYTHON) data/multilingual/Cyrl.KJH/Sans_8/pdf_to_json_test_Cyrl.KJH_Sans_8.py > data/multilingual/Cyrl.KJH/Sans_8/pdf_to_json_test_Cyrl.KJH_Sans_8.json 2>&1
Cyrl.KJH_Serif_12:
	-$(PYTHON) data/multilingual/Cyrl.KJH/Serif_12/pdf_to_json_test_Cyrl.KJH_Serif_12.py > data/multilingual/Cyrl.KJH/Serif_12/pdf_to_json_test_Cyrl.KJH_Serif_12.json 2>&1
Cyrl.KJH_Serif_16:
	-$(PYTHON) data/multilingual/Cyrl.KJH/Serif_16/pdf_to_json_test_Cyrl.KJH_Serif_16.py > data/multilingual/Cyrl.KJH/Serif_16/pdf_to_json_test_Cyrl.KJH_Serif_16.json 2>&1
Cyrl.KJH_Serif_8:
	-$(PYTHON) data/multilingual/Cyrl.KJH/Serif_8/pdf_to_json_test_Cyrl.KJH_Serif_8.py > data/multilingual/Cyrl.KJH/Serif_8/pdf_to_json_test_Cyrl.KJH_Serif_8.json 2>&1
Cyrl.KJH_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Cyrl.KJH/Sun-ExtA_12/pdf_to_json_test_Cyrl.KJH_Sun-ExtA_12.py > data/multilingual/Cyrl.KJH/Sun-ExtA_12/pdf_to_json_test_Cyrl.KJH_Sun-ExtA_12.json 2>&1
Cyrl.KJH_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Cyrl.KJH/Sun-ExtA_16/pdf_to_json_test_Cyrl.KJH_Sun-ExtA_16.py > data/multilingual/Cyrl.KJH/Sun-ExtA_16/pdf_to_json_test_Cyrl.KJH_Sun-ExtA_16.json 2>&1
Cyrl.KJH_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Cyrl.KJH/Sun-ExtA_8/pdf_to_json_test_Cyrl.KJH_Sun-ExtA_8.py > data/multilingual/Cyrl.KJH/Sun-ExtA_8/pdf_to_json_test_Cyrl.KJH_Sun-ExtA_8.json 2>&1


Cyrl.KJH_all : Cyrl.KJH_Mono_12 Cyrl.KJH_Mono_16 Cyrl.KJH_Mono_8 Cyrl.KJH_Sans_12 Cyrl.KJH_Sans_16 Cyrl.KJH_Sans_8 Cyrl.KJH_Serif_12 Cyrl.KJH_Serif_16 Cyrl.KJH_Serif_8 Cyrl.KJH_Sun-ExtA_12 Cyrl.KJH_Sun-ExtA_16 Cyrl.KJH_Sun-ExtA_8
