PYTHON=python3


Latn.LOZ_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.LOZ/Mono_12/pdf_to_json_test_Latn.LOZ_Mono_12.py" > "data/multilingual/Latn.LOZ/Mono_12/pdf_to_json_test_Latn.LOZ_Mono_12.json" 2>&1
Latn.LOZ_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.LOZ/Mono_16/pdf_to_json_test_Latn.LOZ_Mono_16.py" > "data/multilingual/Latn.LOZ/Mono_16/pdf_to_json_test_Latn.LOZ_Mono_16.json" 2>&1
Latn.LOZ_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.LOZ/Mono_8/pdf_to_json_test_Latn.LOZ_Mono_8.py" > "data/multilingual/Latn.LOZ/Mono_8/pdf_to_json_test_Latn.LOZ_Mono_8.json" 2>&1
Latn.LOZ_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.LOZ/Sans_12/pdf_to_json_test_Latn.LOZ_Sans_12.py" > "data/multilingual/Latn.LOZ/Sans_12/pdf_to_json_test_Latn.LOZ_Sans_12.json" 2>&1
Latn.LOZ_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.LOZ/Sans_16/pdf_to_json_test_Latn.LOZ_Sans_16.py" > "data/multilingual/Latn.LOZ/Sans_16/pdf_to_json_test_Latn.LOZ_Sans_16.json" 2>&1
Latn.LOZ_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.LOZ/Sans_8/pdf_to_json_test_Latn.LOZ_Sans_8.py" > "data/multilingual/Latn.LOZ/Sans_8/pdf_to_json_test_Latn.LOZ_Sans_8.json" 2>&1
Latn.LOZ_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.LOZ/Serif_12/pdf_to_json_test_Latn.LOZ_Serif_12.py" > "data/multilingual/Latn.LOZ/Serif_12/pdf_to_json_test_Latn.LOZ_Serif_12.json" 2>&1
Latn.LOZ_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.LOZ/Serif_16/pdf_to_json_test_Latn.LOZ_Serif_16.py" > "data/multilingual/Latn.LOZ/Serif_16/pdf_to_json_test_Latn.LOZ_Serif_16.json" 2>&1
Latn.LOZ_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.LOZ/Serif_8/pdf_to_json_test_Latn.LOZ_Serif_8.py" > "data/multilingual/Latn.LOZ/Serif_8/pdf_to_json_test_Latn.LOZ_Serif_8.json" 2>&1
Latn.LOZ_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.LOZ/Sun-ExtA_12/pdf_to_json_test_Latn.LOZ_Sun-ExtA_12.py" > "data/multilingual/Latn.LOZ/Sun-ExtA_12/pdf_to_json_test_Latn.LOZ_Sun-ExtA_12.json" 2>&1
Latn.LOZ_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.LOZ/Sun-ExtA_16/pdf_to_json_test_Latn.LOZ_Sun-ExtA_16.py" > "data/multilingual/Latn.LOZ/Sun-ExtA_16/pdf_to_json_test_Latn.LOZ_Sun-ExtA_16.json" 2>&1
Latn.LOZ_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.LOZ/Sun-ExtA_8/pdf_to_json_test_Latn.LOZ_Sun-ExtA_8.py" > "data/multilingual/Latn.LOZ/Sun-ExtA_8/pdf_to_json_test_Latn.LOZ_Sun-ExtA_8.json" 2>&1


Latn.LOZ_all : Latn.LOZ_Mono_12 Latn.LOZ_Mono_16 Latn.LOZ_Mono_8 Latn.LOZ_Sans_12 Latn.LOZ_Sans_16 Latn.LOZ_Sans_8 Latn.LOZ_Serif_12 Latn.LOZ_Serif_16 Latn.LOZ_Serif_8 Latn.LOZ_Sun-ExtA_12 Latn.LOZ_Sun-ExtA_16 Latn.LOZ_Sun-ExtA_8
