PYTHON=python3


Cans.CSW_Mono_12:
	-$(PYTHON) "data/multilingual/Cans.CSW/Mono_12/pdf_to_json_test_Cans.CSW_Mono_12.py" > "data/multilingual/Cans.CSW/Mono_12/pdf_to_json_test_Cans.CSW_Mono_12.json" 2>&1
Cans.CSW_Mono_16:
	-$(PYTHON) "data/multilingual/Cans.CSW/Mono_16/pdf_to_json_test_Cans.CSW_Mono_16.py" > "data/multilingual/Cans.CSW/Mono_16/pdf_to_json_test_Cans.CSW_Mono_16.json" 2>&1
Cans.CSW_Mono_8:
	-$(PYTHON) "data/multilingual/Cans.CSW/Mono_8/pdf_to_json_test_Cans.CSW_Mono_8.py" > "data/multilingual/Cans.CSW/Mono_8/pdf_to_json_test_Cans.CSW_Mono_8.json" 2>&1
Cans.CSW_Sans_12:
	-$(PYTHON) "data/multilingual/Cans.CSW/Sans_12/pdf_to_json_test_Cans.CSW_Sans_12.py" > "data/multilingual/Cans.CSW/Sans_12/pdf_to_json_test_Cans.CSW_Sans_12.json" 2>&1
Cans.CSW_Sans_16:
	-$(PYTHON) "data/multilingual/Cans.CSW/Sans_16/pdf_to_json_test_Cans.CSW_Sans_16.py" > "data/multilingual/Cans.CSW/Sans_16/pdf_to_json_test_Cans.CSW_Sans_16.json" 2>&1
Cans.CSW_Sans_8:
	-$(PYTHON) "data/multilingual/Cans.CSW/Sans_8/pdf_to_json_test_Cans.CSW_Sans_8.py" > "data/multilingual/Cans.CSW/Sans_8/pdf_to_json_test_Cans.CSW_Sans_8.json" 2>&1
Cans.CSW_Serif_12:
	-$(PYTHON) "data/multilingual/Cans.CSW/Serif_12/pdf_to_json_test_Cans.CSW_Serif_12.py" > "data/multilingual/Cans.CSW/Serif_12/pdf_to_json_test_Cans.CSW_Serif_12.json" 2>&1
Cans.CSW_Serif_16:
	-$(PYTHON) "data/multilingual/Cans.CSW/Serif_16/pdf_to_json_test_Cans.CSW_Serif_16.py" > "data/multilingual/Cans.CSW/Serif_16/pdf_to_json_test_Cans.CSW_Serif_16.json" 2>&1
Cans.CSW_Serif_8:
	-$(PYTHON) "data/multilingual/Cans.CSW/Serif_8/pdf_to_json_test_Cans.CSW_Serif_8.py" > "data/multilingual/Cans.CSW/Serif_8/pdf_to_json_test_Cans.CSW_Serif_8.json" 2>&1
Cans.CSW_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Cans.CSW/Sun-ExtA_12/pdf_to_json_test_Cans.CSW_Sun-ExtA_12.py" > "data/multilingual/Cans.CSW/Sun-ExtA_12/pdf_to_json_test_Cans.CSW_Sun-ExtA_12.json" 2>&1
Cans.CSW_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Cans.CSW/Sun-ExtA_16/pdf_to_json_test_Cans.CSW_Sun-ExtA_16.py" > "data/multilingual/Cans.CSW/Sun-ExtA_16/pdf_to_json_test_Cans.CSW_Sun-ExtA_16.json" 2>&1
Cans.CSW_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Cans.CSW/Sun-ExtA_8/pdf_to_json_test_Cans.CSW_Sun-ExtA_8.py" > "data/multilingual/Cans.CSW/Sun-ExtA_8/pdf_to_json_test_Cans.CSW_Sun-ExtA_8.json" 2>&1


Cans.CSW_all : Cans.CSW_Mono_12 Cans.CSW_Mono_16 Cans.CSW_Mono_8 Cans.CSW_Sans_12 Cans.CSW_Sans_16 Cans.CSW_Sans_8 Cans.CSW_Serif_12 Cans.CSW_Serif_16 Cans.CSW_Serif_8 Cans.CSW_Sun-ExtA_12 Cans.CSW_Sun-ExtA_16 Cans.CSW_Sun-ExtA_8
