PYTHON=python3


Latn.CBU_Mono_12:
	-$(PYTHON) data/multilingual/Latn.CBU/Mono_12/pdf_to_json_test_Latn.CBU_Mono_12.py > data/multilingual/Latn.CBU/Mono_12/pdf_to_json_test_Latn.CBU_Mono_12.json 2>&1
Latn.CBU_Mono_16:
	-$(PYTHON) data/multilingual/Latn.CBU/Mono_16/pdf_to_json_test_Latn.CBU_Mono_16.py > data/multilingual/Latn.CBU/Mono_16/pdf_to_json_test_Latn.CBU_Mono_16.json 2>&1
Latn.CBU_Mono_8:
	-$(PYTHON) data/multilingual/Latn.CBU/Mono_8/pdf_to_json_test_Latn.CBU_Mono_8.py > data/multilingual/Latn.CBU/Mono_8/pdf_to_json_test_Latn.CBU_Mono_8.json 2>&1
Latn.CBU_Sans_12:
	-$(PYTHON) data/multilingual/Latn.CBU/Sans_12/pdf_to_json_test_Latn.CBU_Sans_12.py > data/multilingual/Latn.CBU/Sans_12/pdf_to_json_test_Latn.CBU_Sans_12.json 2>&1
Latn.CBU_Sans_16:
	-$(PYTHON) data/multilingual/Latn.CBU/Sans_16/pdf_to_json_test_Latn.CBU_Sans_16.py > data/multilingual/Latn.CBU/Sans_16/pdf_to_json_test_Latn.CBU_Sans_16.json 2>&1
Latn.CBU_Sans_8:
	-$(PYTHON) data/multilingual/Latn.CBU/Sans_8/pdf_to_json_test_Latn.CBU_Sans_8.py > data/multilingual/Latn.CBU/Sans_8/pdf_to_json_test_Latn.CBU_Sans_8.json 2>&1
Latn.CBU_Serif_12:
	-$(PYTHON) data/multilingual/Latn.CBU/Serif_12/pdf_to_json_test_Latn.CBU_Serif_12.py > data/multilingual/Latn.CBU/Serif_12/pdf_to_json_test_Latn.CBU_Serif_12.json 2>&1
Latn.CBU_Serif_16:
	-$(PYTHON) data/multilingual/Latn.CBU/Serif_16/pdf_to_json_test_Latn.CBU_Serif_16.py > data/multilingual/Latn.CBU/Serif_16/pdf_to_json_test_Latn.CBU_Serif_16.json 2>&1
Latn.CBU_Serif_8:
	-$(PYTHON) data/multilingual/Latn.CBU/Serif_8/pdf_to_json_test_Latn.CBU_Serif_8.py > data/multilingual/Latn.CBU/Serif_8/pdf_to_json_test_Latn.CBU_Serif_8.json 2>&1
Latn.CBU_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.CBU/Sun-ExtA_12/pdf_to_json_test_Latn.CBU_Sun-ExtA_12.py > data/multilingual/Latn.CBU/Sun-ExtA_12/pdf_to_json_test_Latn.CBU_Sun-ExtA_12.json 2>&1
Latn.CBU_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.CBU/Sun-ExtA_16/pdf_to_json_test_Latn.CBU_Sun-ExtA_16.py > data/multilingual/Latn.CBU/Sun-ExtA_16/pdf_to_json_test_Latn.CBU_Sun-ExtA_16.json 2>&1
Latn.CBU_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.CBU/Sun-ExtA_8/pdf_to_json_test_Latn.CBU_Sun-ExtA_8.py > data/multilingual/Latn.CBU/Sun-ExtA_8/pdf_to_json_test_Latn.CBU_Sun-ExtA_8.json 2>&1


Latn.CBU_all : Latn.CBU_Mono_12 Latn.CBU_Mono_16 Latn.CBU_Mono_8 Latn.CBU_Sans_12 Latn.CBU_Sans_16 Latn.CBU_Sans_8 Latn.CBU_Serif_12 Latn.CBU_Serif_16 Latn.CBU_Serif_8 Latn.CBU_Sun-ExtA_12 Latn.CBU_Sun-ExtA_16 Latn.CBU_Sun-ExtA_8
