PYTHON=python3


Latn.YAO_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.YAO/Mono_12/pdf_to_json_test_Latn.YAO_Mono_12.py" > "data/multilingual/Latn.YAO/Mono_12/pdf_to_json_test_Latn.YAO_Mono_12.json" 2>&1
Latn.YAO_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.YAO/Mono_16/pdf_to_json_test_Latn.YAO_Mono_16.py" > "data/multilingual/Latn.YAO/Mono_16/pdf_to_json_test_Latn.YAO_Mono_16.json" 2>&1
Latn.YAO_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.YAO/Mono_8/pdf_to_json_test_Latn.YAO_Mono_8.py" > "data/multilingual/Latn.YAO/Mono_8/pdf_to_json_test_Latn.YAO_Mono_8.json" 2>&1
Latn.YAO_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.YAO/Sans_12/pdf_to_json_test_Latn.YAO_Sans_12.py" > "data/multilingual/Latn.YAO/Sans_12/pdf_to_json_test_Latn.YAO_Sans_12.json" 2>&1
Latn.YAO_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.YAO/Sans_16/pdf_to_json_test_Latn.YAO_Sans_16.py" > "data/multilingual/Latn.YAO/Sans_16/pdf_to_json_test_Latn.YAO_Sans_16.json" 2>&1
Latn.YAO_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.YAO/Sans_8/pdf_to_json_test_Latn.YAO_Sans_8.py" > "data/multilingual/Latn.YAO/Sans_8/pdf_to_json_test_Latn.YAO_Sans_8.json" 2>&1
Latn.YAO_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.YAO/Serif_12/pdf_to_json_test_Latn.YAO_Serif_12.py" > "data/multilingual/Latn.YAO/Serif_12/pdf_to_json_test_Latn.YAO_Serif_12.json" 2>&1
Latn.YAO_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.YAO/Serif_16/pdf_to_json_test_Latn.YAO_Serif_16.py" > "data/multilingual/Latn.YAO/Serif_16/pdf_to_json_test_Latn.YAO_Serif_16.json" 2>&1
Latn.YAO_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.YAO/Serif_8/pdf_to_json_test_Latn.YAO_Serif_8.py" > "data/multilingual/Latn.YAO/Serif_8/pdf_to_json_test_Latn.YAO_Serif_8.json" 2>&1
Latn.YAO_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.YAO/Sun-ExtA_12/pdf_to_json_test_Latn.YAO_Sun-ExtA_12.py" > "data/multilingual/Latn.YAO/Sun-ExtA_12/pdf_to_json_test_Latn.YAO_Sun-ExtA_12.json" 2>&1
Latn.YAO_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.YAO/Sun-ExtA_16/pdf_to_json_test_Latn.YAO_Sun-ExtA_16.py" > "data/multilingual/Latn.YAO/Sun-ExtA_16/pdf_to_json_test_Latn.YAO_Sun-ExtA_16.json" 2>&1
Latn.YAO_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.YAO/Sun-ExtA_8/pdf_to_json_test_Latn.YAO_Sun-ExtA_8.py" > "data/multilingual/Latn.YAO/Sun-ExtA_8/pdf_to_json_test_Latn.YAO_Sun-ExtA_8.json" 2>&1


Latn.YAO_all : Latn.YAO_Mono_12 Latn.YAO_Mono_16 Latn.YAO_Mono_8 Latn.YAO_Sans_12 Latn.YAO_Sans_16 Latn.YAO_Sans_8 Latn.YAO_Serif_12 Latn.YAO_Serif_16 Latn.YAO_Serif_8 Latn.YAO_Sun-ExtA_12 Latn.YAO_Sun-ExtA_16 Latn.YAO_Sun-ExtA_8
