PYTHON=python3


Cyrl.KIR_Mono_12:
	-$(PYTHON) data/multilingual/Cyrl.KIR/Mono_12/pdf_to_json_test_Cyrl.KIR_Mono_12.py > data/multilingual/Cyrl.KIR/Mono_12/pdf_to_json_test_Cyrl.KIR_Mono_12.json 2>&1
Cyrl.KIR_Mono_16:
	-$(PYTHON) data/multilingual/Cyrl.KIR/Mono_16/pdf_to_json_test_Cyrl.KIR_Mono_16.py > data/multilingual/Cyrl.KIR/Mono_16/pdf_to_json_test_Cyrl.KIR_Mono_16.json 2>&1
Cyrl.KIR_Mono_8:
	-$(PYTHON) data/multilingual/Cyrl.KIR/Mono_8/pdf_to_json_test_Cyrl.KIR_Mono_8.py > data/multilingual/Cyrl.KIR/Mono_8/pdf_to_json_test_Cyrl.KIR_Mono_8.json 2>&1
Cyrl.KIR_Sans_12:
	-$(PYTHON) data/multilingual/Cyrl.KIR/Sans_12/pdf_to_json_test_Cyrl.KIR_Sans_12.py > data/multilingual/Cyrl.KIR/Sans_12/pdf_to_json_test_Cyrl.KIR_Sans_12.json 2>&1
Cyrl.KIR_Sans_16:
	-$(PYTHON) data/multilingual/Cyrl.KIR/Sans_16/pdf_to_json_test_Cyrl.KIR_Sans_16.py > data/multilingual/Cyrl.KIR/Sans_16/pdf_to_json_test_Cyrl.KIR_Sans_16.json 2>&1
Cyrl.KIR_Sans_8:
	-$(PYTHON) data/multilingual/Cyrl.KIR/Sans_8/pdf_to_json_test_Cyrl.KIR_Sans_8.py > data/multilingual/Cyrl.KIR/Sans_8/pdf_to_json_test_Cyrl.KIR_Sans_8.json 2>&1
Cyrl.KIR_Serif_12:
	-$(PYTHON) data/multilingual/Cyrl.KIR/Serif_12/pdf_to_json_test_Cyrl.KIR_Serif_12.py > data/multilingual/Cyrl.KIR/Serif_12/pdf_to_json_test_Cyrl.KIR_Serif_12.json 2>&1
Cyrl.KIR_Serif_16:
	-$(PYTHON) data/multilingual/Cyrl.KIR/Serif_16/pdf_to_json_test_Cyrl.KIR_Serif_16.py > data/multilingual/Cyrl.KIR/Serif_16/pdf_to_json_test_Cyrl.KIR_Serif_16.json 2>&1
Cyrl.KIR_Serif_8:
	-$(PYTHON) data/multilingual/Cyrl.KIR/Serif_8/pdf_to_json_test_Cyrl.KIR_Serif_8.py > data/multilingual/Cyrl.KIR/Serif_8/pdf_to_json_test_Cyrl.KIR_Serif_8.json 2>&1
Cyrl.KIR_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Cyrl.KIR/Sun-ExtA_12/pdf_to_json_test_Cyrl.KIR_Sun-ExtA_12.py > data/multilingual/Cyrl.KIR/Sun-ExtA_12/pdf_to_json_test_Cyrl.KIR_Sun-ExtA_12.json 2>&1
Cyrl.KIR_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Cyrl.KIR/Sun-ExtA_16/pdf_to_json_test_Cyrl.KIR_Sun-ExtA_16.py > data/multilingual/Cyrl.KIR/Sun-ExtA_16/pdf_to_json_test_Cyrl.KIR_Sun-ExtA_16.json 2>&1
Cyrl.KIR_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Cyrl.KIR/Sun-ExtA_8/pdf_to_json_test_Cyrl.KIR_Sun-ExtA_8.py > data/multilingual/Cyrl.KIR/Sun-ExtA_8/pdf_to_json_test_Cyrl.KIR_Sun-ExtA_8.json 2>&1


Cyrl.KIR_all : Cyrl.KIR_Mono_12 Cyrl.KIR_Mono_16 Cyrl.KIR_Mono_8 Cyrl.KIR_Sans_12 Cyrl.KIR_Sans_16 Cyrl.KIR_Sans_8 Cyrl.KIR_Serif_12 Cyrl.KIR_Serif_16 Cyrl.KIR_Serif_8 Cyrl.KIR_Sun-ExtA_12 Cyrl.KIR_Sun-ExtA_16 Cyrl.KIR_Sun-ExtA_8
