PYTHON=python3


Latn.HNI_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.HNI/Mono_12/pdf_to_json_test_Latn.HNI_Mono_12.py" > "data/multilingual/Latn.HNI/Mono_12/pdf_to_json_test_Latn.HNI_Mono_12.json" 2>&1
Latn.HNI_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.HNI/Mono_16/pdf_to_json_test_Latn.HNI_Mono_16.py" > "data/multilingual/Latn.HNI/Mono_16/pdf_to_json_test_Latn.HNI_Mono_16.json" 2>&1
Latn.HNI_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.HNI/Mono_8/pdf_to_json_test_Latn.HNI_Mono_8.py" > "data/multilingual/Latn.HNI/Mono_8/pdf_to_json_test_Latn.HNI_Mono_8.json" 2>&1
Latn.HNI_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.HNI/Sans_12/pdf_to_json_test_Latn.HNI_Sans_12.py" > "data/multilingual/Latn.HNI/Sans_12/pdf_to_json_test_Latn.HNI_Sans_12.json" 2>&1
Latn.HNI_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.HNI/Sans_16/pdf_to_json_test_Latn.HNI_Sans_16.py" > "data/multilingual/Latn.HNI/Sans_16/pdf_to_json_test_Latn.HNI_Sans_16.json" 2>&1
Latn.HNI_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.HNI/Sans_8/pdf_to_json_test_Latn.HNI_Sans_8.py" > "data/multilingual/Latn.HNI/Sans_8/pdf_to_json_test_Latn.HNI_Sans_8.json" 2>&1
Latn.HNI_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.HNI/Serif_12/pdf_to_json_test_Latn.HNI_Serif_12.py" > "data/multilingual/Latn.HNI/Serif_12/pdf_to_json_test_Latn.HNI_Serif_12.json" 2>&1
Latn.HNI_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.HNI/Serif_16/pdf_to_json_test_Latn.HNI_Serif_16.py" > "data/multilingual/Latn.HNI/Serif_16/pdf_to_json_test_Latn.HNI_Serif_16.json" 2>&1
Latn.HNI_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.HNI/Serif_8/pdf_to_json_test_Latn.HNI_Serif_8.py" > "data/multilingual/Latn.HNI/Serif_8/pdf_to_json_test_Latn.HNI_Serif_8.json" 2>&1
Latn.HNI_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.HNI/Sun-ExtA_12/pdf_to_json_test_Latn.HNI_Sun-ExtA_12.py" > "data/multilingual/Latn.HNI/Sun-ExtA_12/pdf_to_json_test_Latn.HNI_Sun-ExtA_12.json" 2>&1
Latn.HNI_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.HNI/Sun-ExtA_16/pdf_to_json_test_Latn.HNI_Sun-ExtA_16.py" > "data/multilingual/Latn.HNI/Sun-ExtA_16/pdf_to_json_test_Latn.HNI_Sun-ExtA_16.json" 2>&1
Latn.HNI_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.HNI/Sun-ExtA_8/pdf_to_json_test_Latn.HNI_Sun-ExtA_8.py" > "data/multilingual/Latn.HNI/Sun-ExtA_8/pdf_to_json_test_Latn.HNI_Sun-ExtA_8.json" 2>&1


Latn.HNI_all : Latn.HNI_Mono_12 Latn.HNI_Mono_16 Latn.HNI_Mono_8 Latn.HNI_Sans_12 Latn.HNI_Sans_16 Latn.HNI_Sans_8 Latn.HNI_Serif_12 Latn.HNI_Serif_16 Latn.HNI_Serif_8 Latn.HNI_Sun-ExtA_12 Latn.HNI_Sun-ExtA_16 Latn.HNI_Sun-ExtA_8
