PYTHON=python3


Telu.TEL_Mono_12:
	-$(PYTHON) "data/multilingual/Telu.TEL/Mono_12/pdf_to_json_test_Telu.TEL_Mono_12.py" > "data/multilingual/Telu.TEL/Mono_12/pdf_to_json_test_Telu.TEL_Mono_12.json" 2>&1
Telu.TEL_Mono_16:
	-$(PYTHON) "data/multilingual/Telu.TEL/Mono_16/pdf_to_json_test_Telu.TEL_Mono_16.py" > "data/multilingual/Telu.TEL/Mono_16/pdf_to_json_test_Telu.TEL_Mono_16.json" 2>&1
Telu.TEL_Mono_8:
	-$(PYTHON) "data/multilingual/Telu.TEL/Mono_8/pdf_to_json_test_Telu.TEL_Mono_8.py" > "data/multilingual/Telu.TEL/Mono_8/pdf_to_json_test_Telu.TEL_Mono_8.json" 2>&1
Telu.TEL_Sans_12:
	-$(PYTHON) "data/multilingual/Telu.TEL/Sans_12/pdf_to_json_test_Telu.TEL_Sans_12.py" > "data/multilingual/Telu.TEL/Sans_12/pdf_to_json_test_Telu.TEL_Sans_12.json" 2>&1
Telu.TEL_Sans_16:
	-$(PYTHON) "data/multilingual/Telu.TEL/Sans_16/pdf_to_json_test_Telu.TEL_Sans_16.py" > "data/multilingual/Telu.TEL/Sans_16/pdf_to_json_test_Telu.TEL_Sans_16.json" 2>&1
Telu.TEL_Sans_8:
	-$(PYTHON) "data/multilingual/Telu.TEL/Sans_8/pdf_to_json_test_Telu.TEL_Sans_8.py" > "data/multilingual/Telu.TEL/Sans_8/pdf_to_json_test_Telu.TEL_Sans_8.json" 2>&1
Telu.TEL_Serif_12:
	-$(PYTHON) "data/multilingual/Telu.TEL/Serif_12/pdf_to_json_test_Telu.TEL_Serif_12.py" > "data/multilingual/Telu.TEL/Serif_12/pdf_to_json_test_Telu.TEL_Serif_12.json" 2>&1
Telu.TEL_Serif_16:
	-$(PYTHON) "data/multilingual/Telu.TEL/Serif_16/pdf_to_json_test_Telu.TEL_Serif_16.py" > "data/multilingual/Telu.TEL/Serif_16/pdf_to_json_test_Telu.TEL_Serif_16.json" 2>&1
Telu.TEL_Serif_8:
	-$(PYTHON) "data/multilingual/Telu.TEL/Serif_8/pdf_to_json_test_Telu.TEL_Serif_8.py" > "data/multilingual/Telu.TEL/Serif_8/pdf_to_json_test_Telu.TEL_Serif_8.json" 2>&1
Telu.TEL_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Telu.TEL/Sun-ExtA_12/pdf_to_json_test_Telu.TEL_Sun-ExtA_12.py" > "data/multilingual/Telu.TEL/Sun-ExtA_12/pdf_to_json_test_Telu.TEL_Sun-ExtA_12.json" 2>&1
Telu.TEL_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Telu.TEL/Sun-ExtA_16/pdf_to_json_test_Telu.TEL_Sun-ExtA_16.py" > "data/multilingual/Telu.TEL/Sun-ExtA_16/pdf_to_json_test_Telu.TEL_Sun-ExtA_16.json" 2>&1
Telu.TEL_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Telu.TEL/Sun-ExtA_8/pdf_to_json_test_Telu.TEL_Sun-ExtA_8.py" > "data/multilingual/Telu.TEL/Sun-ExtA_8/pdf_to_json_test_Telu.TEL_Sun-ExtA_8.json" 2>&1


Telu.TEL_all : Telu.TEL_Mono_12 Telu.TEL_Mono_16 Telu.TEL_Mono_8 Telu.TEL_Sans_12 Telu.TEL_Sans_16 Telu.TEL_Sans_8 Telu.TEL_Serif_12 Telu.TEL_Serif_16 Telu.TEL_Serif_8 Telu.TEL_Sun-ExtA_12 Telu.TEL_Sun-ExtA_16 Telu.TEL_Sun-ExtA_8
