PYTHON=python3


Cyrl.SRP_Mono_12:
	-$(PYTHON) data/multilingual/Cyrl.SRP/Mono_12/pdf_to_json_test_Cyrl.SRP_Mono_12.py > data/multilingual/Cyrl.SRP/Mono_12/pdf_to_json_test_Cyrl.SRP_Mono_12.json 2>&1
Cyrl.SRP_Mono_16:
	-$(PYTHON) data/multilingual/Cyrl.SRP/Mono_16/pdf_to_json_test_Cyrl.SRP_Mono_16.py > data/multilingual/Cyrl.SRP/Mono_16/pdf_to_json_test_Cyrl.SRP_Mono_16.json 2>&1
Cyrl.SRP_Mono_8:
	-$(PYTHON) data/multilingual/Cyrl.SRP/Mono_8/pdf_to_json_test_Cyrl.SRP_Mono_8.py > data/multilingual/Cyrl.SRP/Mono_8/pdf_to_json_test_Cyrl.SRP_Mono_8.json 2>&1
Cyrl.SRP_Sans_12:
	-$(PYTHON) data/multilingual/Cyrl.SRP/Sans_12/pdf_to_json_test_Cyrl.SRP_Sans_12.py > data/multilingual/Cyrl.SRP/Sans_12/pdf_to_json_test_Cyrl.SRP_Sans_12.json 2>&1
Cyrl.SRP_Sans_16:
	-$(PYTHON) data/multilingual/Cyrl.SRP/Sans_16/pdf_to_json_test_Cyrl.SRP_Sans_16.py > data/multilingual/Cyrl.SRP/Sans_16/pdf_to_json_test_Cyrl.SRP_Sans_16.json 2>&1
Cyrl.SRP_Sans_8:
	-$(PYTHON) data/multilingual/Cyrl.SRP/Sans_8/pdf_to_json_test_Cyrl.SRP_Sans_8.py > data/multilingual/Cyrl.SRP/Sans_8/pdf_to_json_test_Cyrl.SRP_Sans_8.json 2>&1
Cyrl.SRP_Serif_12:
	-$(PYTHON) data/multilingual/Cyrl.SRP/Serif_12/pdf_to_json_test_Cyrl.SRP_Serif_12.py > data/multilingual/Cyrl.SRP/Serif_12/pdf_to_json_test_Cyrl.SRP_Serif_12.json 2>&1
Cyrl.SRP_Serif_16:
	-$(PYTHON) data/multilingual/Cyrl.SRP/Serif_16/pdf_to_json_test_Cyrl.SRP_Serif_16.py > data/multilingual/Cyrl.SRP/Serif_16/pdf_to_json_test_Cyrl.SRP_Serif_16.json 2>&1
Cyrl.SRP_Serif_8:
	-$(PYTHON) data/multilingual/Cyrl.SRP/Serif_8/pdf_to_json_test_Cyrl.SRP_Serif_8.py > data/multilingual/Cyrl.SRP/Serif_8/pdf_to_json_test_Cyrl.SRP_Serif_8.json 2>&1
Cyrl.SRP_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Cyrl.SRP/Sun-ExtA_12/pdf_to_json_test_Cyrl.SRP_Sun-ExtA_12.py > data/multilingual/Cyrl.SRP/Sun-ExtA_12/pdf_to_json_test_Cyrl.SRP_Sun-ExtA_12.json 2>&1
Cyrl.SRP_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Cyrl.SRP/Sun-ExtA_16/pdf_to_json_test_Cyrl.SRP_Sun-ExtA_16.py > data/multilingual/Cyrl.SRP/Sun-ExtA_16/pdf_to_json_test_Cyrl.SRP_Sun-ExtA_16.json 2>&1
Cyrl.SRP_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Cyrl.SRP/Sun-ExtA_8/pdf_to_json_test_Cyrl.SRP_Sun-ExtA_8.py > data/multilingual/Cyrl.SRP/Sun-ExtA_8/pdf_to_json_test_Cyrl.SRP_Sun-ExtA_8.json 2>&1


Cyrl.SRP_all : Cyrl.SRP_Mono_12 Cyrl.SRP_Mono_16 Cyrl.SRP_Mono_8 Cyrl.SRP_Sans_12 Cyrl.SRP_Sans_16 Cyrl.SRP_Sans_8 Cyrl.SRP_Serif_12 Cyrl.SRP_Serif_16 Cyrl.SRP_Serif_8 Cyrl.SRP_Sun-ExtA_12 Cyrl.SRP_Sun-ExtA_16 Cyrl.SRP_Sun-ExtA_8
