PYTHON=python3


Latn.HAU_Mono_12:
	-$(PYTHON) data/multilingual/Latn.HAU/Mono_12/pdf_to_json_test_Latn.HAU_Mono_12.py > data/multilingual/Latn.HAU/Mono_12/pdf_to_json_test_Latn.HAU_Mono_12.json 2>&1
Latn.HAU_Mono_16:
	-$(PYTHON) data/multilingual/Latn.HAU/Mono_16/pdf_to_json_test_Latn.HAU_Mono_16.py > data/multilingual/Latn.HAU/Mono_16/pdf_to_json_test_Latn.HAU_Mono_16.json 2>&1
Latn.HAU_Mono_8:
	-$(PYTHON) data/multilingual/Latn.HAU/Mono_8/pdf_to_json_test_Latn.HAU_Mono_8.py > data/multilingual/Latn.HAU/Mono_8/pdf_to_json_test_Latn.HAU_Mono_8.json 2>&1
Latn.HAU_Sans_12:
	-$(PYTHON) data/multilingual/Latn.HAU/Sans_12/pdf_to_json_test_Latn.HAU_Sans_12.py > data/multilingual/Latn.HAU/Sans_12/pdf_to_json_test_Latn.HAU_Sans_12.json 2>&1
Latn.HAU_Sans_16:
	-$(PYTHON) data/multilingual/Latn.HAU/Sans_16/pdf_to_json_test_Latn.HAU_Sans_16.py > data/multilingual/Latn.HAU/Sans_16/pdf_to_json_test_Latn.HAU_Sans_16.json 2>&1
Latn.HAU_Sans_8:
	-$(PYTHON) data/multilingual/Latn.HAU/Sans_8/pdf_to_json_test_Latn.HAU_Sans_8.py > data/multilingual/Latn.HAU/Sans_8/pdf_to_json_test_Latn.HAU_Sans_8.json 2>&1
Latn.HAU_Serif_12:
	-$(PYTHON) data/multilingual/Latn.HAU/Serif_12/pdf_to_json_test_Latn.HAU_Serif_12.py > data/multilingual/Latn.HAU/Serif_12/pdf_to_json_test_Latn.HAU_Serif_12.json 2>&1
Latn.HAU_Serif_16:
	-$(PYTHON) data/multilingual/Latn.HAU/Serif_16/pdf_to_json_test_Latn.HAU_Serif_16.py > data/multilingual/Latn.HAU/Serif_16/pdf_to_json_test_Latn.HAU_Serif_16.json 2>&1
Latn.HAU_Serif_8:
	-$(PYTHON) data/multilingual/Latn.HAU/Serif_8/pdf_to_json_test_Latn.HAU_Serif_8.py > data/multilingual/Latn.HAU/Serif_8/pdf_to_json_test_Latn.HAU_Serif_8.json 2>&1
Latn.HAU_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.HAU/Sun-ExtA_12/pdf_to_json_test_Latn.HAU_Sun-ExtA_12.py > data/multilingual/Latn.HAU/Sun-ExtA_12/pdf_to_json_test_Latn.HAU_Sun-ExtA_12.json 2>&1
Latn.HAU_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.HAU/Sun-ExtA_16/pdf_to_json_test_Latn.HAU_Sun-ExtA_16.py > data/multilingual/Latn.HAU/Sun-ExtA_16/pdf_to_json_test_Latn.HAU_Sun-ExtA_16.json 2>&1
Latn.HAU_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.HAU/Sun-ExtA_8/pdf_to_json_test_Latn.HAU_Sun-ExtA_8.py > data/multilingual/Latn.HAU/Sun-ExtA_8/pdf_to_json_test_Latn.HAU_Sun-ExtA_8.json 2>&1


Latn.HAU_all : Latn.HAU_Mono_12 Latn.HAU_Mono_16 Latn.HAU_Mono_8 Latn.HAU_Sans_12 Latn.HAU_Sans_16 Latn.HAU_Sans_8 Latn.HAU_Serif_12 Latn.HAU_Serif_16 Latn.HAU_Serif_8 Latn.HAU_Sun-ExtA_12 Latn.HAU_Sun-ExtA_16 Latn.HAU_Sun-ExtA_8
