PYTHON=python3


Mlym.MAL_Mono_12:
	-$(PYTHON) data/multilingual/Mlym.MAL/Mono_12/pdf_to_json_test_Mlym.MAL_Mono_12.py > data/multilingual/Mlym.MAL/Mono_12/pdf_to_json_test_Mlym.MAL_Mono_12.json 2>&1
Mlym.MAL_Mono_16:
	-$(PYTHON) data/multilingual/Mlym.MAL/Mono_16/pdf_to_json_test_Mlym.MAL_Mono_16.py > data/multilingual/Mlym.MAL/Mono_16/pdf_to_json_test_Mlym.MAL_Mono_16.json 2>&1
Mlym.MAL_Mono_8:
	-$(PYTHON) data/multilingual/Mlym.MAL/Mono_8/pdf_to_json_test_Mlym.MAL_Mono_8.py > data/multilingual/Mlym.MAL/Mono_8/pdf_to_json_test_Mlym.MAL_Mono_8.json 2>&1
Mlym.MAL_Sans_12:
	-$(PYTHON) data/multilingual/Mlym.MAL/Sans_12/pdf_to_json_test_Mlym.MAL_Sans_12.py > data/multilingual/Mlym.MAL/Sans_12/pdf_to_json_test_Mlym.MAL_Sans_12.json 2>&1
Mlym.MAL_Sans_16:
	-$(PYTHON) data/multilingual/Mlym.MAL/Sans_16/pdf_to_json_test_Mlym.MAL_Sans_16.py > data/multilingual/Mlym.MAL/Sans_16/pdf_to_json_test_Mlym.MAL_Sans_16.json 2>&1
Mlym.MAL_Sans_8:
	-$(PYTHON) data/multilingual/Mlym.MAL/Sans_8/pdf_to_json_test_Mlym.MAL_Sans_8.py > data/multilingual/Mlym.MAL/Sans_8/pdf_to_json_test_Mlym.MAL_Sans_8.json 2>&1
Mlym.MAL_Serif_12:
	-$(PYTHON) data/multilingual/Mlym.MAL/Serif_12/pdf_to_json_test_Mlym.MAL_Serif_12.py > data/multilingual/Mlym.MAL/Serif_12/pdf_to_json_test_Mlym.MAL_Serif_12.json 2>&1
Mlym.MAL_Serif_16:
	-$(PYTHON) data/multilingual/Mlym.MAL/Serif_16/pdf_to_json_test_Mlym.MAL_Serif_16.py > data/multilingual/Mlym.MAL/Serif_16/pdf_to_json_test_Mlym.MAL_Serif_16.json 2>&1
Mlym.MAL_Serif_8:
	-$(PYTHON) data/multilingual/Mlym.MAL/Serif_8/pdf_to_json_test_Mlym.MAL_Serif_8.py > data/multilingual/Mlym.MAL/Serif_8/pdf_to_json_test_Mlym.MAL_Serif_8.json 2>&1
Mlym.MAL_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Mlym.MAL/Sun-ExtA_12/pdf_to_json_test_Mlym.MAL_Sun-ExtA_12.py > data/multilingual/Mlym.MAL/Sun-ExtA_12/pdf_to_json_test_Mlym.MAL_Sun-ExtA_12.json 2>&1
Mlym.MAL_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Mlym.MAL/Sun-ExtA_16/pdf_to_json_test_Mlym.MAL_Sun-ExtA_16.py > data/multilingual/Mlym.MAL/Sun-ExtA_16/pdf_to_json_test_Mlym.MAL_Sun-ExtA_16.json 2>&1
Mlym.MAL_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Mlym.MAL/Sun-ExtA_8/pdf_to_json_test_Mlym.MAL_Sun-ExtA_8.py > data/multilingual/Mlym.MAL/Sun-ExtA_8/pdf_to_json_test_Mlym.MAL_Sun-ExtA_8.json 2>&1


Mlym.MAL_all : Mlym.MAL_Mono_12 Mlym.MAL_Mono_16 Mlym.MAL_Mono_8 Mlym.MAL_Sans_12 Mlym.MAL_Sans_16 Mlym.MAL_Sans_8 Mlym.MAL_Serif_12 Mlym.MAL_Serif_16 Mlym.MAL_Serif_8 Mlym.MAL_Sun-ExtA_12 Mlym.MAL_Sun-ExtA_16 Mlym.MAL_Sun-ExtA_8
