PYTHON=python3


Latn.EKK_Mono_12:
	-$(PYTHON) data/multilingual/Latn.EKK/Mono_12/pdf_to_json_test_Latn.EKK_Mono_12.py > data/multilingual/Latn.EKK/Mono_12/pdf_to_json_test_Latn.EKK_Mono_12.json 2>&1
Latn.EKK_Mono_16:
	-$(PYTHON) data/multilingual/Latn.EKK/Mono_16/pdf_to_json_test_Latn.EKK_Mono_16.py > data/multilingual/Latn.EKK/Mono_16/pdf_to_json_test_Latn.EKK_Mono_16.json 2>&1
Latn.EKK_Mono_8:
	-$(PYTHON) data/multilingual/Latn.EKK/Mono_8/pdf_to_json_test_Latn.EKK_Mono_8.py > data/multilingual/Latn.EKK/Mono_8/pdf_to_json_test_Latn.EKK_Mono_8.json 2>&1
Latn.EKK_Sans_12:
	-$(PYTHON) data/multilingual/Latn.EKK/Sans_12/pdf_to_json_test_Latn.EKK_Sans_12.py > data/multilingual/Latn.EKK/Sans_12/pdf_to_json_test_Latn.EKK_Sans_12.json 2>&1
Latn.EKK_Sans_16:
	-$(PYTHON) data/multilingual/Latn.EKK/Sans_16/pdf_to_json_test_Latn.EKK_Sans_16.py > data/multilingual/Latn.EKK/Sans_16/pdf_to_json_test_Latn.EKK_Sans_16.json 2>&1
Latn.EKK_Sans_8:
	-$(PYTHON) data/multilingual/Latn.EKK/Sans_8/pdf_to_json_test_Latn.EKK_Sans_8.py > data/multilingual/Latn.EKK/Sans_8/pdf_to_json_test_Latn.EKK_Sans_8.json 2>&1
Latn.EKK_Serif_12:
	-$(PYTHON) data/multilingual/Latn.EKK/Serif_12/pdf_to_json_test_Latn.EKK_Serif_12.py > data/multilingual/Latn.EKK/Serif_12/pdf_to_json_test_Latn.EKK_Serif_12.json 2>&1
Latn.EKK_Serif_16:
	-$(PYTHON) data/multilingual/Latn.EKK/Serif_16/pdf_to_json_test_Latn.EKK_Serif_16.py > data/multilingual/Latn.EKK/Serif_16/pdf_to_json_test_Latn.EKK_Serif_16.json 2>&1
Latn.EKK_Serif_8:
	-$(PYTHON) data/multilingual/Latn.EKK/Serif_8/pdf_to_json_test_Latn.EKK_Serif_8.py > data/multilingual/Latn.EKK/Serif_8/pdf_to_json_test_Latn.EKK_Serif_8.json 2>&1
Latn.EKK_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.EKK/Sun-ExtA_12/pdf_to_json_test_Latn.EKK_Sun-ExtA_12.py > data/multilingual/Latn.EKK/Sun-ExtA_12/pdf_to_json_test_Latn.EKK_Sun-ExtA_12.json 2>&1
Latn.EKK_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.EKK/Sun-ExtA_16/pdf_to_json_test_Latn.EKK_Sun-ExtA_16.py > data/multilingual/Latn.EKK/Sun-ExtA_16/pdf_to_json_test_Latn.EKK_Sun-ExtA_16.json 2>&1
Latn.EKK_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.EKK/Sun-ExtA_8/pdf_to_json_test_Latn.EKK_Sun-ExtA_8.py > data/multilingual/Latn.EKK/Sun-ExtA_8/pdf_to_json_test_Latn.EKK_Sun-ExtA_8.json 2>&1


Latn.EKK_all : Latn.EKK_Mono_12 Latn.EKK_Mono_16 Latn.EKK_Mono_8 Latn.EKK_Sans_12 Latn.EKK_Sans_16 Latn.EKK_Sans_8 Latn.EKK_Serif_12 Latn.EKK_Serif_16 Latn.EKK_Serif_8 Latn.EKK_Sun-ExtA_12 Latn.EKK_Sun-ExtA_16 Latn.EKK_Sun-ExtA_8
