PYTHON=python3


Latn.AGR_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.AGR/Mono_12/pdf_to_json_test_Latn.AGR_Mono_12.py" > "data/multilingual/Latn.AGR/Mono_12/pdf_to_json_test_Latn.AGR_Mono_12.json" 2>&1
Latn.AGR_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.AGR/Mono_16/pdf_to_json_test_Latn.AGR_Mono_16.py" > "data/multilingual/Latn.AGR/Mono_16/pdf_to_json_test_Latn.AGR_Mono_16.json" 2>&1
Latn.AGR_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.AGR/Mono_8/pdf_to_json_test_Latn.AGR_Mono_8.py" > "data/multilingual/Latn.AGR/Mono_8/pdf_to_json_test_Latn.AGR_Mono_8.json" 2>&1
Latn.AGR_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.AGR/Sans_12/pdf_to_json_test_Latn.AGR_Sans_12.py" > "data/multilingual/Latn.AGR/Sans_12/pdf_to_json_test_Latn.AGR_Sans_12.json" 2>&1
Latn.AGR_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.AGR/Sans_16/pdf_to_json_test_Latn.AGR_Sans_16.py" > "data/multilingual/Latn.AGR/Sans_16/pdf_to_json_test_Latn.AGR_Sans_16.json" 2>&1
Latn.AGR_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.AGR/Sans_8/pdf_to_json_test_Latn.AGR_Sans_8.py" > "data/multilingual/Latn.AGR/Sans_8/pdf_to_json_test_Latn.AGR_Sans_8.json" 2>&1
Latn.AGR_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.AGR/Serif_12/pdf_to_json_test_Latn.AGR_Serif_12.py" > "data/multilingual/Latn.AGR/Serif_12/pdf_to_json_test_Latn.AGR_Serif_12.json" 2>&1
Latn.AGR_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.AGR/Serif_16/pdf_to_json_test_Latn.AGR_Serif_16.py" > "data/multilingual/Latn.AGR/Serif_16/pdf_to_json_test_Latn.AGR_Serif_16.json" 2>&1
Latn.AGR_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.AGR/Serif_8/pdf_to_json_test_Latn.AGR_Serif_8.py" > "data/multilingual/Latn.AGR/Serif_8/pdf_to_json_test_Latn.AGR_Serif_8.json" 2>&1
Latn.AGR_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.AGR/Sun-ExtA_12/pdf_to_json_test_Latn.AGR_Sun-ExtA_12.py" > "data/multilingual/Latn.AGR/Sun-ExtA_12/pdf_to_json_test_Latn.AGR_Sun-ExtA_12.json" 2>&1
Latn.AGR_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.AGR/Sun-ExtA_16/pdf_to_json_test_Latn.AGR_Sun-ExtA_16.py" > "data/multilingual/Latn.AGR/Sun-ExtA_16/pdf_to_json_test_Latn.AGR_Sun-ExtA_16.json" 2>&1
Latn.AGR_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.AGR/Sun-ExtA_8/pdf_to_json_test_Latn.AGR_Sun-ExtA_8.py" > "data/multilingual/Latn.AGR/Sun-ExtA_8/pdf_to_json_test_Latn.AGR_Sun-ExtA_8.json" 2>&1


Latn.AGR_all : Latn.AGR_Mono_12 Latn.AGR_Mono_16 Latn.AGR_Mono_8 Latn.AGR_Sans_12 Latn.AGR_Sans_16 Latn.AGR_Sans_8 Latn.AGR_Serif_12 Latn.AGR_Serif_16 Latn.AGR_Serif_8 Latn.AGR_Sun-ExtA_12 Latn.AGR_Sun-ExtA_16 Latn.AGR_Sun-ExtA_8
