PYTHON=python3


Arab.PRS_Mono_12:
	-$(PYTHON) "data/multilingual/Arab.PRS/Mono_12/pdf_to_json_test_Arab.PRS_Mono_12.py" > "data/multilingual/Arab.PRS/Mono_12/pdf_to_json_test_Arab.PRS_Mono_12.json" 2>&1
Arab.PRS_Mono_16:
	-$(PYTHON) "data/multilingual/Arab.PRS/Mono_16/pdf_to_json_test_Arab.PRS_Mono_16.py" > "data/multilingual/Arab.PRS/Mono_16/pdf_to_json_test_Arab.PRS_Mono_16.json" 2>&1
Arab.PRS_Mono_8:
	-$(PYTHON) "data/multilingual/Arab.PRS/Mono_8/pdf_to_json_test_Arab.PRS_Mono_8.py" > "data/multilingual/Arab.PRS/Mono_8/pdf_to_json_test_Arab.PRS_Mono_8.json" 2>&1
Arab.PRS_Sans_12:
	-$(PYTHON) "data/multilingual/Arab.PRS/Sans_12/pdf_to_json_test_Arab.PRS_Sans_12.py" > "data/multilingual/Arab.PRS/Sans_12/pdf_to_json_test_Arab.PRS_Sans_12.json" 2>&1
Arab.PRS_Sans_16:
	-$(PYTHON) "data/multilingual/Arab.PRS/Sans_16/pdf_to_json_test_Arab.PRS_Sans_16.py" > "data/multilingual/Arab.PRS/Sans_16/pdf_to_json_test_Arab.PRS_Sans_16.json" 2>&1
Arab.PRS_Sans_8:
	-$(PYTHON) "data/multilingual/Arab.PRS/Sans_8/pdf_to_json_test_Arab.PRS_Sans_8.py" > "data/multilingual/Arab.PRS/Sans_8/pdf_to_json_test_Arab.PRS_Sans_8.json" 2>&1
Arab.PRS_Serif_12:
	-$(PYTHON) "data/multilingual/Arab.PRS/Serif_12/pdf_to_json_test_Arab.PRS_Serif_12.py" > "data/multilingual/Arab.PRS/Serif_12/pdf_to_json_test_Arab.PRS_Serif_12.json" 2>&1
Arab.PRS_Serif_16:
	-$(PYTHON) "data/multilingual/Arab.PRS/Serif_16/pdf_to_json_test_Arab.PRS_Serif_16.py" > "data/multilingual/Arab.PRS/Serif_16/pdf_to_json_test_Arab.PRS_Serif_16.json" 2>&1
Arab.PRS_Serif_8:
	-$(PYTHON) "data/multilingual/Arab.PRS/Serif_8/pdf_to_json_test_Arab.PRS_Serif_8.py" > "data/multilingual/Arab.PRS/Serif_8/pdf_to_json_test_Arab.PRS_Serif_8.json" 2>&1
Arab.PRS_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Arab.PRS/Sun-ExtA_12/pdf_to_json_test_Arab.PRS_Sun-ExtA_12.py" > "data/multilingual/Arab.PRS/Sun-ExtA_12/pdf_to_json_test_Arab.PRS_Sun-ExtA_12.json" 2>&1
Arab.PRS_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Arab.PRS/Sun-ExtA_16/pdf_to_json_test_Arab.PRS_Sun-ExtA_16.py" > "data/multilingual/Arab.PRS/Sun-ExtA_16/pdf_to_json_test_Arab.PRS_Sun-ExtA_16.json" 2>&1
Arab.PRS_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Arab.PRS/Sun-ExtA_8/pdf_to_json_test_Arab.PRS_Sun-ExtA_8.py" > "data/multilingual/Arab.PRS/Sun-ExtA_8/pdf_to_json_test_Arab.PRS_Sun-ExtA_8.json" 2>&1


Arab.PRS_all : Arab.PRS_Mono_12 Arab.PRS_Mono_16 Arab.PRS_Mono_8 Arab.PRS_Sans_12 Arab.PRS_Sans_16 Arab.PRS_Sans_8 Arab.PRS_Serif_12 Arab.PRS_Serif_16 Arab.PRS_Serif_8 Arab.PRS_Sun-ExtA_12 Arab.PRS_Sun-ExtA_16 Arab.PRS_Sun-ExtA_8
