PYTHON=python3


Latn.QUG_Mono_12:
	-$(PYTHON) data/multilingual/Latn.QUG/Mono_12/pdf_to_json_test_Latn.QUG_Mono_12.py > data/multilingual/Latn.QUG/Mono_12/pdf_to_json_test_Latn.QUG_Mono_12.json 2>&1
Latn.QUG_Mono_16:
	-$(PYTHON) data/multilingual/Latn.QUG/Mono_16/pdf_to_json_test_Latn.QUG_Mono_16.py > data/multilingual/Latn.QUG/Mono_16/pdf_to_json_test_Latn.QUG_Mono_16.json 2>&1
Latn.QUG_Mono_8:
	-$(PYTHON) data/multilingual/Latn.QUG/Mono_8/pdf_to_json_test_Latn.QUG_Mono_8.py > data/multilingual/Latn.QUG/Mono_8/pdf_to_json_test_Latn.QUG_Mono_8.json 2>&1
Latn.QUG_Sans_12:
	-$(PYTHON) data/multilingual/Latn.QUG/Sans_12/pdf_to_json_test_Latn.QUG_Sans_12.py > data/multilingual/Latn.QUG/Sans_12/pdf_to_json_test_Latn.QUG_Sans_12.json 2>&1
Latn.QUG_Sans_16:
	-$(PYTHON) data/multilingual/Latn.QUG/Sans_16/pdf_to_json_test_Latn.QUG_Sans_16.py > data/multilingual/Latn.QUG/Sans_16/pdf_to_json_test_Latn.QUG_Sans_16.json 2>&1
Latn.QUG_Sans_8:
	-$(PYTHON) data/multilingual/Latn.QUG/Sans_8/pdf_to_json_test_Latn.QUG_Sans_8.py > data/multilingual/Latn.QUG/Sans_8/pdf_to_json_test_Latn.QUG_Sans_8.json 2>&1
Latn.QUG_Serif_12:
	-$(PYTHON) data/multilingual/Latn.QUG/Serif_12/pdf_to_json_test_Latn.QUG_Serif_12.py > data/multilingual/Latn.QUG/Serif_12/pdf_to_json_test_Latn.QUG_Serif_12.json 2>&1
Latn.QUG_Serif_16:
	-$(PYTHON) data/multilingual/Latn.QUG/Serif_16/pdf_to_json_test_Latn.QUG_Serif_16.py > data/multilingual/Latn.QUG/Serif_16/pdf_to_json_test_Latn.QUG_Serif_16.json 2>&1
Latn.QUG_Serif_8:
	-$(PYTHON) data/multilingual/Latn.QUG/Serif_8/pdf_to_json_test_Latn.QUG_Serif_8.py > data/multilingual/Latn.QUG/Serif_8/pdf_to_json_test_Latn.QUG_Serif_8.json 2>&1
Latn.QUG_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.QUG/Sun-ExtA_12/pdf_to_json_test_Latn.QUG_Sun-ExtA_12.py > data/multilingual/Latn.QUG/Sun-ExtA_12/pdf_to_json_test_Latn.QUG_Sun-ExtA_12.json 2>&1
Latn.QUG_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.QUG/Sun-ExtA_16/pdf_to_json_test_Latn.QUG_Sun-ExtA_16.py > data/multilingual/Latn.QUG/Sun-ExtA_16/pdf_to_json_test_Latn.QUG_Sun-ExtA_16.json 2>&1
Latn.QUG_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.QUG/Sun-ExtA_8/pdf_to_json_test_Latn.QUG_Sun-ExtA_8.py > data/multilingual/Latn.QUG/Sun-ExtA_8/pdf_to_json_test_Latn.QUG_Sun-ExtA_8.json 2>&1


Latn.QUG_all : Latn.QUG_Mono_12 Latn.QUG_Mono_16 Latn.QUG_Mono_8 Latn.QUG_Sans_12 Latn.QUG_Sans_16 Latn.QUG_Sans_8 Latn.QUG_Serif_12 Latn.QUG_Serif_16 Latn.QUG_Serif_8 Latn.QUG_Sun-ExtA_12 Latn.QUG_Sun-ExtA_16 Latn.QUG_Sun-ExtA_8
