PYTHON=python3


Latn.UZN_Mono_12:
	-$(PYTHON) data/multilingual/Latn.UZN/Mono_12/pdf_to_json_test_Latn.UZN_Mono_12.py > data/multilingual/Latn.UZN/Mono_12/pdf_to_json_test_Latn.UZN_Mono_12.json 2>&1
Latn.UZN_Mono_16:
	-$(PYTHON) data/multilingual/Latn.UZN/Mono_16/pdf_to_json_test_Latn.UZN_Mono_16.py > data/multilingual/Latn.UZN/Mono_16/pdf_to_json_test_Latn.UZN_Mono_16.json 2>&1
Latn.UZN_Mono_8:
	-$(PYTHON) data/multilingual/Latn.UZN/Mono_8/pdf_to_json_test_Latn.UZN_Mono_8.py > data/multilingual/Latn.UZN/Mono_8/pdf_to_json_test_Latn.UZN_Mono_8.json 2>&1
Latn.UZN_Sans_12:
	-$(PYTHON) data/multilingual/Latn.UZN/Sans_12/pdf_to_json_test_Latn.UZN_Sans_12.py > data/multilingual/Latn.UZN/Sans_12/pdf_to_json_test_Latn.UZN_Sans_12.json 2>&1
Latn.UZN_Sans_16:
	-$(PYTHON) data/multilingual/Latn.UZN/Sans_16/pdf_to_json_test_Latn.UZN_Sans_16.py > data/multilingual/Latn.UZN/Sans_16/pdf_to_json_test_Latn.UZN_Sans_16.json 2>&1
Latn.UZN_Sans_8:
	-$(PYTHON) data/multilingual/Latn.UZN/Sans_8/pdf_to_json_test_Latn.UZN_Sans_8.py > data/multilingual/Latn.UZN/Sans_8/pdf_to_json_test_Latn.UZN_Sans_8.json 2>&1
Latn.UZN_Serif_12:
	-$(PYTHON) data/multilingual/Latn.UZN/Serif_12/pdf_to_json_test_Latn.UZN_Serif_12.py > data/multilingual/Latn.UZN/Serif_12/pdf_to_json_test_Latn.UZN_Serif_12.json 2>&1
Latn.UZN_Serif_16:
	-$(PYTHON) data/multilingual/Latn.UZN/Serif_16/pdf_to_json_test_Latn.UZN_Serif_16.py > data/multilingual/Latn.UZN/Serif_16/pdf_to_json_test_Latn.UZN_Serif_16.json 2>&1
Latn.UZN_Serif_8:
	-$(PYTHON) data/multilingual/Latn.UZN/Serif_8/pdf_to_json_test_Latn.UZN_Serif_8.py > data/multilingual/Latn.UZN/Serif_8/pdf_to_json_test_Latn.UZN_Serif_8.json 2>&1
Latn.UZN_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.UZN/Sun-ExtA_12/pdf_to_json_test_Latn.UZN_Sun-ExtA_12.py > data/multilingual/Latn.UZN/Sun-ExtA_12/pdf_to_json_test_Latn.UZN_Sun-ExtA_12.json 2>&1
Latn.UZN_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.UZN/Sun-ExtA_16/pdf_to_json_test_Latn.UZN_Sun-ExtA_16.py > data/multilingual/Latn.UZN/Sun-ExtA_16/pdf_to_json_test_Latn.UZN_Sun-ExtA_16.json 2>&1
Latn.UZN_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.UZN/Sun-ExtA_8/pdf_to_json_test_Latn.UZN_Sun-ExtA_8.py > data/multilingual/Latn.UZN/Sun-ExtA_8/pdf_to_json_test_Latn.UZN_Sun-ExtA_8.json 2>&1


Latn.UZN_all : Latn.UZN_Mono_12 Latn.UZN_Mono_16 Latn.UZN_Mono_8 Latn.UZN_Sans_12 Latn.UZN_Sans_16 Latn.UZN_Sans_8 Latn.UZN_Serif_12 Latn.UZN_Serif_16 Latn.UZN_Serif_8 Latn.UZN_Sun-ExtA_12 Latn.UZN_Sun-ExtA_16 Latn.UZN_Sun-ExtA_8
