PYTHON=python3


Cans.OJB_Mono_12:
	-$(PYTHON) "data/multilingual/Cans.OJB/Mono_12/pdf_to_json_test_Cans.OJB_Mono_12.py" > "data/multilingual/Cans.OJB/Mono_12/pdf_to_json_test_Cans.OJB_Mono_12.json" 2>&1
Cans.OJB_Mono_16:
	-$(PYTHON) "data/multilingual/Cans.OJB/Mono_16/pdf_to_json_test_Cans.OJB_Mono_16.py" > "data/multilingual/Cans.OJB/Mono_16/pdf_to_json_test_Cans.OJB_Mono_16.json" 2>&1
Cans.OJB_Mono_8:
	-$(PYTHON) "data/multilingual/Cans.OJB/Mono_8/pdf_to_json_test_Cans.OJB_Mono_8.py" > "data/multilingual/Cans.OJB/Mono_8/pdf_to_json_test_Cans.OJB_Mono_8.json" 2>&1
Cans.OJB_Sans_12:
	-$(PYTHON) "data/multilingual/Cans.OJB/Sans_12/pdf_to_json_test_Cans.OJB_Sans_12.py" > "data/multilingual/Cans.OJB/Sans_12/pdf_to_json_test_Cans.OJB_Sans_12.json" 2>&1
Cans.OJB_Sans_16:
	-$(PYTHON) "data/multilingual/Cans.OJB/Sans_16/pdf_to_json_test_Cans.OJB_Sans_16.py" > "data/multilingual/Cans.OJB/Sans_16/pdf_to_json_test_Cans.OJB_Sans_16.json" 2>&1
Cans.OJB_Sans_8:
	-$(PYTHON) "data/multilingual/Cans.OJB/Sans_8/pdf_to_json_test_Cans.OJB_Sans_8.py" > "data/multilingual/Cans.OJB/Sans_8/pdf_to_json_test_Cans.OJB_Sans_8.json" 2>&1
Cans.OJB_Serif_12:
	-$(PYTHON) "data/multilingual/Cans.OJB/Serif_12/pdf_to_json_test_Cans.OJB_Serif_12.py" > "data/multilingual/Cans.OJB/Serif_12/pdf_to_json_test_Cans.OJB_Serif_12.json" 2>&1
Cans.OJB_Serif_16:
	-$(PYTHON) "data/multilingual/Cans.OJB/Serif_16/pdf_to_json_test_Cans.OJB_Serif_16.py" > "data/multilingual/Cans.OJB/Serif_16/pdf_to_json_test_Cans.OJB_Serif_16.json" 2>&1
Cans.OJB_Serif_8:
	-$(PYTHON) "data/multilingual/Cans.OJB/Serif_8/pdf_to_json_test_Cans.OJB_Serif_8.py" > "data/multilingual/Cans.OJB/Serif_8/pdf_to_json_test_Cans.OJB_Serif_8.json" 2>&1
Cans.OJB_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Cans.OJB/Sun-ExtA_12/pdf_to_json_test_Cans.OJB_Sun-ExtA_12.py" > "data/multilingual/Cans.OJB/Sun-ExtA_12/pdf_to_json_test_Cans.OJB_Sun-ExtA_12.json" 2>&1
Cans.OJB_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Cans.OJB/Sun-ExtA_16/pdf_to_json_test_Cans.OJB_Sun-ExtA_16.py" > "data/multilingual/Cans.OJB/Sun-ExtA_16/pdf_to_json_test_Cans.OJB_Sun-ExtA_16.json" 2>&1
Cans.OJB_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Cans.OJB/Sun-ExtA_8/pdf_to_json_test_Cans.OJB_Sun-ExtA_8.py" > "data/multilingual/Cans.OJB/Sun-ExtA_8/pdf_to_json_test_Cans.OJB_Sun-ExtA_8.json" 2>&1


Cans.OJB_all : Cans.OJB_Mono_12 Cans.OJB_Mono_16 Cans.OJB_Mono_8 Cans.OJB_Sans_12 Cans.OJB_Sans_16 Cans.OJB_Sans_8 Cans.OJB_Serif_12 Cans.OJB_Serif_16 Cans.OJB_Serif_8 Cans.OJB_Sun-ExtA_12 Cans.OJB_Sun-ExtA_16 Cans.OJB_Sun-ExtA_8
