PYTHON=python3


Mymr.SHN_Mono_12:
	-$(PYTHON) "data/multilingual/Mymr.SHN/Mono_12/pdf_to_json_test_Mymr.SHN_Mono_12.py" > "data/multilingual/Mymr.SHN/Mono_12/pdf_to_json_test_Mymr.SHN_Mono_12.json" 2>&1
Mymr.SHN_Mono_16:
	-$(PYTHON) "data/multilingual/Mymr.SHN/Mono_16/pdf_to_json_test_Mymr.SHN_Mono_16.py" > "data/multilingual/Mymr.SHN/Mono_16/pdf_to_json_test_Mymr.SHN_Mono_16.json" 2>&1
Mymr.SHN_Mono_8:
	-$(PYTHON) "data/multilingual/Mymr.SHN/Mono_8/pdf_to_json_test_Mymr.SHN_Mono_8.py" > "data/multilingual/Mymr.SHN/Mono_8/pdf_to_json_test_Mymr.SHN_Mono_8.json" 2>&1
Mymr.SHN_Sans_12:
	-$(PYTHON) "data/multilingual/Mymr.SHN/Sans_12/pdf_to_json_test_Mymr.SHN_Sans_12.py" > "data/multilingual/Mymr.SHN/Sans_12/pdf_to_json_test_Mymr.SHN_Sans_12.json" 2>&1
Mymr.SHN_Sans_16:
	-$(PYTHON) "data/multilingual/Mymr.SHN/Sans_16/pdf_to_json_test_Mymr.SHN_Sans_16.py" > "data/multilingual/Mymr.SHN/Sans_16/pdf_to_json_test_Mymr.SHN_Sans_16.json" 2>&1
Mymr.SHN_Sans_8:
	-$(PYTHON) "data/multilingual/Mymr.SHN/Sans_8/pdf_to_json_test_Mymr.SHN_Sans_8.py" > "data/multilingual/Mymr.SHN/Sans_8/pdf_to_json_test_Mymr.SHN_Sans_8.json" 2>&1
Mymr.SHN_Serif_12:
	-$(PYTHON) "data/multilingual/Mymr.SHN/Serif_12/pdf_to_json_test_Mymr.SHN_Serif_12.py" > "data/multilingual/Mymr.SHN/Serif_12/pdf_to_json_test_Mymr.SHN_Serif_12.json" 2>&1
Mymr.SHN_Serif_16:
	-$(PYTHON) "data/multilingual/Mymr.SHN/Serif_16/pdf_to_json_test_Mymr.SHN_Serif_16.py" > "data/multilingual/Mymr.SHN/Serif_16/pdf_to_json_test_Mymr.SHN_Serif_16.json" 2>&1
Mymr.SHN_Serif_8:
	-$(PYTHON) "data/multilingual/Mymr.SHN/Serif_8/pdf_to_json_test_Mymr.SHN_Serif_8.py" > "data/multilingual/Mymr.SHN/Serif_8/pdf_to_json_test_Mymr.SHN_Serif_8.json" 2>&1
Mymr.SHN_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Mymr.SHN/Sun-ExtA_12/pdf_to_json_test_Mymr.SHN_Sun-ExtA_12.py" > "data/multilingual/Mymr.SHN/Sun-ExtA_12/pdf_to_json_test_Mymr.SHN_Sun-ExtA_12.json" 2>&1
Mymr.SHN_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Mymr.SHN/Sun-ExtA_16/pdf_to_json_test_Mymr.SHN_Sun-ExtA_16.py" > "data/multilingual/Mymr.SHN/Sun-ExtA_16/pdf_to_json_test_Mymr.SHN_Sun-ExtA_16.json" 2>&1
Mymr.SHN_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Mymr.SHN/Sun-ExtA_8/pdf_to_json_test_Mymr.SHN_Sun-ExtA_8.py" > "data/multilingual/Mymr.SHN/Sun-ExtA_8/pdf_to_json_test_Mymr.SHN_Sun-ExtA_8.json" 2>&1


Mymr.SHN_all : Mymr.SHN_Mono_12 Mymr.SHN_Mono_16 Mymr.SHN_Mono_8 Mymr.SHN_Sans_12 Mymr.SHN_Sans_16 Mymr.SHN_Sans_8 Mymr.SHN_Serif_12 Mymr.SHN_Serif_16 Mymr.SHN_Serif_8 Mymr.SHN_Sun-ExtA_12 Mymr.SHN_Sun-ExtA_16 Mymr.SHN_Sun-ExtA_8
