PYTHON=python3


Latn.BAM_Mono_12:
	-$(PYTHON) data/multilingual/Latn.BAM/Mono_12/pdf_to_json_test_Latn.BAM_Mono_12.py > data/multilingual/Latn.BAM/Mono_12/pdf_to_json_test_Latn.BAM_Mono_12.json 2>&1
Latn.BAM_Mono_16:
	-$(PYTHON) data/multilingual/Latn.BAM/Mono_16/pdf_to_json_test_Latn.BAM_Mono_16.py > data/multilingual/Latn.BAM/Mono_16/pdf_to_json_test_Latn.BAM_Mono_16.json 2>&1
Latn.BAM_Mono_8:
	-$(PYTHON) data/multilingual/Latn.BAM/Mono_8/pdf_to_json_test_Latn.BAM_Mono_8.py > data/multilingual/Latn.BAM/Mono_8/pdf_to_json_test_Latn.BAM_Mono_8.json 2>&1
Latn.BAM_Sans_12:
	-$(PYTHON) data/multilingual/Latn.BAM/Sans_12/pdf_to_json_test_Latn.BAM_Sans_12.py > data/multilingual/Latn.BAM/Sans_12/pdf_to_json_test_Latn.BAM_Sans_12.json 2>&1
Latn.BAM_Sans_16:
	-$(PYTHON) data/multilingual/Latn.BAM/Sans_16/pdf_to_json_test_Latn.BAM_Sans_16.py > data/multilingual/Latn.BAM/Sans_16/pdf_to_json_test_Latn.BAM_Sans_16.json 2>&1
Latn.BAM_Sans_8:
	-$(PYTHON) data/multilingual/Latn.BAM/Sans_8/pdf_to_json_test_Latn.BAM_Sans_8.py > data/multilingual/Latn.BAM/Sans_8/pdf_to_json_test_Latn.BAM_Sans_8.json 2>&1
Latn.BAM_Serif_12:
	-$(PYTHON) data/multilingual/Latn.BAM/Serif_12/pdf_to_json_test_Latn.BAM_Serif_12.py > data/multilingual/Latn.BAM/Serif_12/pdf_to_json_test_Latn.BAM_Serif_12.json 2>&1
Latn.BAM_Serif_16:
	-$(PYTHON) data/multilingual/Latn.BAM/Serif_16/pdf_to_json_test_Latn.BAM_Serif_16.py > data/multilingual/Latn.BAM/Serif_16/pdf_to_json_test_Latn.BAM_Serif_16.json 2>&1
Latn.BAM_Serif_8:
	-$(PYTHON) data/multilingual/Latn.BAM/Serif_8/pdf_to_json_test_Latn.BAM_Serif_8.py > data/multilingual/Latn.BAM/Serif_8/pdf_to_json_test_Latn.BAM_Serif_8.json 2>&1
Latn.BAM_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.BAM/Sun-ExtA_12/pdf_to_json_test_Latn.BAM_Sun-ExtA_12.py > data/multilingual/Latn.BAM/Sun-ExtA_12/pdf_to_json_test_Latn.BAM_Sun-ExtA_12.json 2>&1
Latn.BAM_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.BAM/Sun-ExtA_16/pdf_to_json_test_Latn.BAM_Sun-ExtA_16.py > data/multilingual/Latn.BAM/Sun-ExtA_16/pdf_to_json_test_Latn.BAM_Sun-ExtA_16.json 2>&1
Latn.BAM_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.BAM/Sun-ExtA_8/pdf_to_json_test_Latn.BAM_Sun-ExtA_8.py > data/multilingual/Latn.BAM/Sun-ExtA_8/pdf_to_json_test_Latn.BAM_Sun-ExtA_8.json 2>&1


Latn.BAM_all : Latn.BAM_Mono_12 Latn.BAM_Mono_16 Latn.BAM_Mono_8 Latn.BAM_Sans_12 Latn.BAM_Sans_16 Latn.BAM_Sans_8 Latn.BAM_Serif_12 Latn.BAM_Serif_16 Latn.BAM_Serif_8 Latn.BAM_Sun-ExtA_12 Latn.BAM_Sun-ExtA_16 Latn.BAM_Sun-ExtA_8
