PYTHON=python3


Arab.SKR_Mono_12:
	-$(PYTHON) "data/multilingual/Arab.SKR/Mono_12/pdf_to_json_test_Arab.SKR_Mono_12.py" > "data/multilingual/Arab.SKR/Mono_12/pdf_to_json_test_Arab.SKR_Mono_12.json" 2>&1
Arab.SKR_Mono_16:
	-$(PYTHON) "data/multilingual/Arab.SKR/Mono_16/pdf_to_json_test_Arab.SKR_Mono_16.py" > "data/multilingual/Arab.SKR/Mono_16/pdf_to_json_test_Arab.SKR_Mono_16.json" 2>&1
Arab.SKR_Mono_8:
	-$(PYTHON) "data/multilingual/Arab.SKR/Mono_8/pdf_to_json_test_Arab.SKR_Mono_8.py" > "data/multilingual/Arab.SKR/Mono_8/pdf_to_json_test_Arab.SKR_Mono_8.json" 2>&1
Arab.SKR_Sans_12:
	-$(PYTHON) "data/multilingual/Arab.SKR/Sans_12/pdf_to_json_test_Arab.SKR_Sans_12.py" > "data/multilingual/Arab.SKR/Sans_12/pdf_to_json_test_Arab.SKR_Sans_12.json" 2>&1
Arab.SKR_Sans_16:
	-$(PYTHON) "data/multilingual/Arab.SKR/Sans_16/pdf_to_json_test_Arab.SKR_Sans_16.py" > "data/multilingual/Arab.SKR/Sans_16/pdf_to_json_test_Arab.SKR_Sans_16.json" 2>&1
Arab.SKR_Sans_8:
	-$(PYTHON) "data/multilingual/Arab.SKR/Sans_8/pdf_to_json_test_Arab.SKR_Sans_8.py" > "data/multilingual/Arab.SKR/Sans_8/pdf_to_json_test_Arab.SKR_Sans_8.json" 2>&1
Arab.SKR_Serif_12:
	-$(PYTHON) "data/multilingual/Arab.SKR/Serif_12/pdf_to_json_test_Arab.SKR_Serif_12.py" > "data/multilingual/Arab.SKR/Serif_12/pdf_to_json_test_Arab.SKR_Serif_12.json" 2>&1
Arab.SKR_Serif_16:
	-$(PYTHON) "data/multilingual/Arab.SKR/Serif_16/pdf_to_json_test_Arab.SKR_Serif_16.py" > "data/multilingual/Arab.SKR/Serif_16/pdf_to_json_test_Arab.SKR_Serif_16.json" 2>&1
Arab.SKR_Serif_8:
	-$(PYTHON) "data/multilingual/Arab.SKR/Serif_8/pdf_to_json_test_Arab.SKR_Serif_8.py" > "data/multilingual/Arab.SKR/Serif_8/pdf_to_json_test_Arab.SKR_Serif_8.json" 2>&1
Arab.SKR_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Arab.SKR/Sun-ExtA_12/pdf_to_json_test_Arab.SKR_Sun-ExtA_12.py" > "data/multilingual/Arab.SKR/Sun-ExtA_12/pdf_to_json_test_Arab.SKR_Sun-ExtA_12.json" 2>&1
Arab.SKR_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Arab.SKR/Sun-ExtA_16/pdf_to_json_test_Arab.SKR_Sun-ExtA_16.py" > "data/multilingual/Arab.SKR/Sun-ExtA_16/pdf_to_json_test_Arab.SKR_Sun-ExtA_16.json" 2>&1
Arab.SKR_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Arab.SKR/Sun-ExtA_8/pdf_to_json_test_Arab.SKR_Sun-ExtA_8.py" > "data/multilingual/Arab.SKR/Sun-ExtA_8/pdf_to_json_test_Arab.SKR_Sun-ExtA_8.json" 2>&1


Arab.SKR_all : Arab.SKR_Mono_12 Arab.SKR_Mono_16 Arab.SKR_Mono_8 Arab.SKR_Sans_12 Arab.SKR_Sans_16 Arab.SKR_Sans_8 Arab.SKR_Serif_12 Arab.SKR_Serif_16 Arab.SKR_Serif_8 Arab.SKR_Sun-ExtA_12 Arab.SKR_Sun-ExtA_16 Arab.SKR_Sun-ExtA_8
