PYTHON=python3


Latn.CBT_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.CBT/Mono_12/pdf_to_json_test_Latn.CBT_Mono_12.py" > "data/multilingual/Latn.CBT/Mono_12/pdf_to_json_test_Latn.CBT_Mono_12.json" 2>&1
Latn.CBT_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.CBT/Mono_16/pdf_to_json_test_Latn.CBT_Mono_16.py" > "data/multilingual/Latn.CBT/Mono_16/pdf_to_json_test_Latn.CBT_Mono_16.json" 2>&1
Latn.CBT_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.CBT/Mono_8/pdf_to_json_test_Latn.CBT_Mono_8.py" > "data/multilingual/Latn.CBT/Mono_8/pdf_to_json_test_Latn.CBT_Mono_8.json" 2>&1
Latn.CBT_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.CBT/Sans_12/pdf_to_json_test_Latn.CBT_Sans_12.py" > "data/multilingual/Latn.CBT/Sans_12/pdf_to_json_test_Latn.CBT_Sans_12.json" 2>&1
Latn.CBT_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.CBT/Sans_16/pdf_to_json_test_Latn.CBT_Sans_16.py" > "data/multilingual/Latn.CBT/Sans_16/pdf_to_json_test_Latn.CBT_Sans_16.json" 2>&1
Latn.CBT_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.CBT/Sans_8/pdf_to_json_test_Latn.CBT_Sans_8.py" > "data/multilingual/Latn.CBT/Sans_8/pdf_to_json_test_Latn.CBT_Sans_8.json" 2>&1
Latn.CBT_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.CBT/Serif_12/pdf_to_json_test_Latn.CBT_Serif_12.py" > "data/multilingual/Latn.CBT/Serif_12/pdf_to_json_test_Latn.CBT_Serif_12.json" 2>&1
Latn.CBT_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.CBT/Serif_16/pdf_to_json_test_Latn.CBT_Serif_16.py" > "data/multilingual/Latn.CBT/Serif_16/pdf_to_json_test_Latn.CBT_Serif_16.json" 2>&1
Latn.CBT_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.CBT/Serif_8/pdf_to_json_test_Latn.CBT_Serif_8.py" > "data/multilingual/Latn.CBT/Serif_8/pdf_to_json_test_Latn.CBT_Serif_8.json" 2>&1
Latn.CBT_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.CBT/Sun-ExtA_12/pdf_to_json_test_Latn.CBT_Sun-ExtA_12.py" > "data/multilingual/Latn.CBT/Sun-ExtA_12/pdf_to_json_test_Latn.CBT_Sun-ExtA_12.json" 2>&1
Latn.CBT_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.CBT/Sun-ExtA_16/pdf_to_json_test_Latn.CBT_Sun-ExtA_16.py" > "data/multilingual/Latn.CBT/Sun-ExtA_16/pdf_to_json_test_Latn.CBT_Sun-ExtA_16.json" 2>&1
Latn.CBT_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.CBT/Sun-ExtA_8/pdf_to_json_test_Latn.CBT_Sun-ExtA_8.py" > "data/multilingual/Latn.CBT/Sun-ExtA_8/pdf_to_json_test_Latn.CBT_Sun-ExtA_8.json" 2>&1


Latn.CBT_all : Latn.CBT_Mono_12 Latn.CBT_Mono_16 Latn.CBT_Mono_8 Latn.CBT_Sans_12 Latn.CBT_Sans_16 Latn.CBT_Sans_8 Latn.CBT_Serif_12 Latn.CBT_Serif_16 Latn.CBT_Serif_8 Latn.CBT_Sun-ExtA_12 Latn.CBT_Sun-ExtA_16 Latn.CBT_Sun-ExtA_8
