PYTHON=python3


Latn.AMI_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.AMI/Mono_12/pdf_to_json_test_Latn.AMI_Mono_12.py" > "data/multilingual/Latn.AMI/Mono_12/pdf_to_json_test_Latn.AMI_Mono_12.json" 2>&1
Latn.AMI_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.AMI/Mono_16/pdf_to_json_test_Latn.AMI_Mono_16.py" > "data/multilingual/Latn.AMI/Mono_16/pdf_to_json_test_Latn.AMI_Mono_16.json" 2>&1
Latn.AMI_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.AMI/Mono_8/pdf_to_json_test_Latn.AMI_Mono_8.py" > "data/multilingual/Latn.AMI/Mono_8/pdf_to_json_test_Latn.AMI_Mono_8.json" 2>&1
Latn.AMI_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.AMI/Sans_12/pdf_to_json_test_Latn.AMI_Sans_12.py" > "data/multilingual/Latn.AMI/Sans_12/pdf_to_json_test_Latn.AMI_Sans_12.json" 2>&1
Latn.AMI_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.AMI/Sans_16/pdf_to_json_test_Latn.AMI_Sans_16.py" > "data/multilingual/Latn.AMI/Sans_16/pdf_to_json_test_Latn.AMI_Sans_16.json" 2>&1
Latn.AMI_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.AMI/Sans_8/pdf_to_json_test_Latn.AMI_Sans_8.py" > "data/multilingual/Latn.AMI/Sans_8/pdf_to_json_test_Latn.AMI_Sans_8.json" 2>&1
Latn.AMI_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.AMI/Serif_12/pdf_to_json_test_Latn.AMI_Serif_12.py" > "data/multilingual/Latn.AMI/Serif_12/pdf_to_json_test_Latn.AMI_Serif_12.json" 2>&1
Latn.AMI_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.AMI/Serif_16/pdf_to_json_test_Latn.AMI_Serif_16.py" > "data/multilingual/Latn.AMI/Serif_16/pdf_to_json_test_Latn.AMI_Serif_16.json" 2>&1
Latn.AMI_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.AMI/Serif_8/pdf_to_json_test_Latn.AMI_Serif_8.py" > "data/multilingual/Latn.AMI/Serif_8/pdf_to_json_test_Latn.AMI_Serif_8.json" 2>&1
Latn.AMI_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.AMI/Sun-ExtA_12/pdf_to_json_test_Latn.AMI_Sun-ExtA_12.py" > "data/multilingual/Latn.AMI/Sun-ExtA_12/pdf_to_json_test_Latn.AMI_Sun-ExtA_12.json" 2>&1
Latn.AMI_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.AMI/Sun-ExtA_16/pdf_to_json_test_Latn.AMI_Sun-ExtA_16.py" > "data/multilingual/Latn.AMI/Sun-ExtA_16/pdf_to_json_test_Latn.AMI_Sun-ExtA_16.json" 2>&1
Latn.AMI_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.AMI/Sun-ExtA_8/pdf_to_json_test_Latn.AMI_Sun-ExtA_8.py" > "data/multilingual/Latn.AMI/Sun-ExtA_8/pdf_to_json_test_Latn.AMI_Sun-ExtA_8.json" 2>&1


Latn.AMI_all : Latn.AMI_Mono_12 Latn.AMI_Mono_16 Latn.AMI_Mono_8 Latn.AMI_Sans_12 Latn.AMI_Sans_16 Latn.AMI_Sans_8 Latn.AMI_Serif_12 Latn.AMI_Serif_16 Latn.AMI_Serif_8 Latn.AMI_Sun-ExtA_12 Latn.AMI_Sun-ExtA_16 Latn.AMI_Sun-ExtA_8
