PYTHON=python3


Latn.BEM_Mono_12:
	-$(PYTHON) data/multilingual/Latn.BEM/Mono_12/pdf_to_json_test_Latn.BEM_Mono_12.py > data/multilingual/Latn.BEM/Mono_12/pdf_to_json_test_Latn.BEM_Mono_12.json 2>&1
Latn.BEM_Mono_16:
	-$(PYTHON) data/multilingual/Latn.BEM/Mono_16/pdf_to_json_test_Latn.BEM_Mono_16.py > data/multilingual/Latn.BEM/Mono_16/pdf_to_json_test_Latn.BEM_Mono_16.json 2>&1
Latn.BEM_Mono_8:
	-$(PYTHON) data/multilingual/Latn.BEM/Mono_8/pdf_to_json_test_Latn.BEM_Mono_8.py > data/multilingual/Latn.BEM/Mono_8/pdf_to_json_test_Latn.BEM_Mono_8.json 2>&1
Latn.BEM_Sans_12:
	-$(PYTHON) data/multilingual/Latn.BEM/Sans_12/pdf_to_json_test_Latn.BEM_Sans_12.py > data/multilingual/Latn.BEM/Sans_12/pdf_to_json_test_Latn.BEM_Sans_12.json 2>&1
Latn.BEM_Sans_16:
	-$(PYTHON) data/multilingual/Latn.BEM/Sans_16/pdf_to_json_test_Latn.BEM_Sans_16.py > data/multilingual/Latn.BEM/Sans_16/pdf_to_json_test_Latn.BEM_Sans_16.json 2>&1
Latn.BEM_Sans_8:
	-$(PYTHON) data/multilingual/Latn.BEM/Sans_8/pdf_to_json_test_Latn.BEM_Sans_8.py > data/multilingual/Latn.BEM/Sans_8/pdf_to_json_test_Latn.BEM_Sans_8.json 2>&1
Latn.BEM_Serif_12:
	-$(PYTHON) data/multilingual/Latn.BEM/Serif_12/pdf_to_json_test_Latn.BEM_Serif_12.py > data/multilingual/Latn.BEM/Serif_12/pdf_to_json_test_Latn.BEM_Serif_12.json 2>&1
Latn.BEM_Serif_16:
	-$(PYTHON) data/multilingual/Latn.BEM/Serif_16/pdf_to_json_test_Latn.BEM_Serif_16.py > data/multilingual/Latn.BEM/Serif_16/pdf_to_json_test_Latn.BEM_Serif_16.json 2>&1
Latn.BEM_Serif_8:
	-$(PYTHON) data/multilingual/Latn.BEM/Serif_8/pdf_to_json_test_Latn.BEM_Serif_8.py > data/multilingual/Latn.BEM/Serif_8/pdf_to_json_test_Latn.BEM_Serif_8.json 2>&1
Latn.BEM_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.BEM/Sun-ExtA_12/pdf_to_json_test_Latn.BEM_Sun-ExtA_12.py > data/multilingual/Latn.BEM/Sun-ExtA_12/pdf_to_json_test_Latn.BEM_Sun-ExtA_12.json 2>&1
Latn.BEM_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.BEM/Sun-ExtA_16/pdf_to_json_test_Latn.BEM_Sun-ExtA_16.py > data/multilingual/Latn.BEM/Sun-ExtA_16/pdf_to_json_test_Latn.BEM_Sun-ExtA_16.json 2>&1
Latn.BEM_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.BEM/Sun-ExtA_8/pdf_to_json_test_Latn.BEM_Sun-ExtA_8.py > data/multilingual/Latn.BEM/Sun-ExtA_8/pdf_to_json_test_Latn.BEM_Sun-ExtA_8.json 2>&1


Latn.BEM_all : Latn.BEM_Mono_12 Latn.BEM_Mono_16 Latn.BEM_Mono_8 Latn.BEM_Sans_12 Latn.BEM_Sans_16 Latn.BEM_Sans_8 Latn.BEM_Serif_12 Latn.BEM_Serif_16 Latn.BEM_Serif_8 Latn.BEM_Sun-ExtA_12 Latn.BEM_Sun-ExtA_16 Latn.BEM_Sun-ExtA_8
