PYTHON=python3


Latn.CTD_Mono_12:
	-$(PYTHON) data/multilingual/Latn.CTD/Mono_12/pdf_to_json_test_Latn.CTD_Mono_12.py > data/multilingual/Latn.CTD/Mono_12/pdf_to_json_test_Latn.CTD_Mono_12.json 2>&1
Latn.CTD_Mono_16:
	-$(PYTHON) data/multilingual/Latn.CTD/Mono_16/pdf_to_json_test_Latn.CTD_Mono_16.py > data/multilingual/Latn.CTD/Mono_16/pdf_to_json_test_Latn.CTD_Mono_16.json 2>&1
Latn.CTD_Mono_8:
	-$(PYTHON) data/multilingual/Latn.CTD/Mono_8/pdf_to_json_test_Latn.CTD_Mono_8.py > data/multilingual/Latn.CTD/Mono_8/pdf_to_json_test_Latn.CTD_Mono_8.json 2>&1
Latn.CTD_Sans_12:
	-$(PYTHON) data/multilingual/Latn.CTD/Sans_12/pdf_to_json_test_Latn.CTD_Sans_12.py > data/multilingual/Latn.CTD/Sans_12/pdf_to_json_test_Latn.CTD_Sans_12.json 2>&1
Latn.CTD_Sans_16:
	-$(PYTHON) data/multilingual/Latn.CTD/Sans_16/pdf_to_json_test_Latn.CTD_Sans_16.py > data/multilingual/Latn.CTD/Sans_16/pdf_to_json_test_Latn.CTD_Sans_16.json 2>&1
Latn.CTD_Sans_8:
	-$(PYTHON) data/multilingual/Latn.CTD/Sans_8/pdf_to_json_test_Latn.CTD_Sans_8.py > data/multilingual/Latn.CTD/Sans_8/pdf_to_json_test_Latn.CTD_Sans_8.json 2>&1
Latn.CTD_Serif_12:
	-$(PYTHON) data/multilingual/Latn.CTD/Serif_12/pdf_to_json_test_Latn.CTD_Serif_12.py > data/multilingual/Latn.CTD/Serif_12/pdf_to_json_test_Latn.CTD_Serif_12.json 2>&1
Latn.CTD_Serif_16:
	-$(PYTHON) data/multilingual/Latn.CTD/Serif_16/pdf_to_json_test_Latn.CTD_Serif_16.py > data/multilingual/Latn.CTD/Serif_16/pdf_to_json_test_Latn.CTD_Serif_16.json 2>&1
Latn.CTD_Serif_8:
	-$(PYTHON) data/multilingual/Latn.CTD/Serif_8/pdf_to_json_test_Latn.CTD_Serif_8.py > data/multilingual/Latn.CTD/Serif_8/pdf_to_json_test_Latn.CTD_Serif_8.json 2>&1
Latn.CTD_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.CTD/Sun-ExtA_12/pdf_to_json_test_Latn.CTD_Sun-ExtA_12.py > data/multilingual/Latn.CTD/Sun-ExtA_12/pdf_to_json_test_Latn.CTD_Sun-ExtA_12.json 2>&1
Latn.CTD_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.CTD/Sun-ExtA_16/pdf_to_json_test_Latn.CTD_Sun-ExtA_16.py > data/multilingual/Latn.CTD/Sun-ExtA_16/pdf_to_json_test_Latn.CTD_Sun-ExtA_16.json 2>&1
Latn.CTD_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.CTD/Sun-ExtA_8/pdf_to_json_test_Latn.CTD_Sun-ExtA_8.py > data/multilingual/Latn.CTD/Sun-ExtA_8/pdf_to_json_test_Latn.CTD_Sun-ExtA_8.json 2>&1


Latn.CTD_all : Latn.CTD_Mono_12 Latn.CTD_Mono_16 Latn.CTD_Mono_8 Latn.CTD_Sans_12 Latn.CTD_Sans_16 Latn.CTD_Sans_8 Latn.CTD_Serif_12 Latn.CTD_Serif_16 Latn.CTD_Serif_8 Latn.CTD_Sun-ExtA_12 Latn.CTD_Sun-ExtA_16 Latn.CTD_Sun-ExtA_8
