PYTHON=python3


Latn.XHO_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.XHO/Mono_12/pdf_to_json_test_Latn.XHO_Mono_12.py" > "data/multilingual/Latn.XHO/Mono_12/pdf_to_json_test_Latn.XHO_Mono_12.json" 2>&1
Latn.XHO_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.XHO/Mono_16/pdf_to_json_test_Latn.XHO_Mono_16.py" > "data/multilingual/Latn.XHO/Mono_16/pdf_to_json_test_Latn.XHO_Mono_16.json" 2>&1
Latn.XHO_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.XHO/Mono_8/pdf_to_json_test_Latn.XHO_Mono_8.py" > "data/multilingual/Latn.XHO/Mono_8/pdf_to_json_test_Latn.XHO_Mono_8.json" 2>&1
Latn.XHO_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.XHO/Sans_12/pdf_to_json_test_Latn.XHO_Sans_12.py" > "data/multilingual/Latn.XHO/Sans_12/pdf_to_json_test_Latn.XHO_Sans_12.json" 2>&1
Latn.XHO_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.XHO/Sans_16/pdf_to_json_test_Latn.XHO_Sans_16.py" > "data/multilingual/Latn.XHO/Sans_16/pdf_to_json_test_Latn.XHO_Sans_16.json" 2>&1
Latn.XHO_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.XHO/Sans_8/pdf_to_json_test_Latn.XHO_Sans_8.py" > "data/multilingual/Latn.XHO/Sans_8/pdf_to_json_test_Latn.XHO_Sans_8.json" 2>&1
Latn.XHO_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.XHO/Serif_12/pdf_to_json_test_Latn.XHO_Serif_12.py" > "data/multilingual/Latn.XHO/Serif_12/pdf_to_json_test_Latn.XHO_Serif_12.json" 2>&1
Latn.XHO_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.XHO/Serif_16/pdf_to_json_test_Latn.XHO_Serif_16.py" > "data/multilingual/Latn.XHO/Serif_16/pdf_to_json_test_Latn.XHO_Serif_16.json" 2>&1
Latn.XHO_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.XHO/Serif_8/pdf_to_json_test_Latn.XHO_Serif_8.py" > "data/multilingual/Latn.XHO/Serif_8/pdf_to_json_test_Latn.XHO_Serif_8.json" 2>&1
Latn.XHO_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.XHO/Sun-ExtA_12/pdf_to_json_test_Latn.XHO_Sun-ExtA_12.py" > "data/multilingual/Latn.XHO/Sun-ExtA_12/pdf_to_json_test_Latn.XHO_Sun-ExtA_12.json" 2>&1
Latn.XHO_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.XHO/Sun-ExtA_16/pdf_to_json_test_Latn.XHO_Sun-ExtA_16.py" > "data/multilingual/Latn.XHO/Sun-ExtA_16/pdf_to_json_test_Latn.XHO_Sun-ExtA_16.json" 2>&1
Latn.XHO_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.XHO/Sun-ExtA_8/pdf_to_json_test_Latn.XHO_Sun-ExtA_8.py" > "data/multilingual/Latn.XHO/Sun-ExtA_8/pdf_to_json_test_Latn.XHO_Sun-ExtA_8.json" 2>&1


Latn.XHO_all : Latn.XHO_Mono_12 Latn.XHO_Mono_16 Latn.XHO_Mono_8 Latn.XHO_Sans_12 Latn.XHO_Sans_16 Latn.XHO_Sans_8 Latn.XHO_Serif_12 Latn.XHO_Serif_16 Latn.XHO_Serif_8 Latn.XHO_Sun-ExtA_12 Latn.XHO_Sun-ExtA_16 Latn.XHO_Sun-ExtA_8
