PYTHON=python3


Latn.KNC_Mono_12:
	-$(PYTHON) data/multilingual/Latn.KNC/Mono_12/pdf_to_json_test_Latn.KNC_Mono_12.py > data/multilingual/Latn.KNC/Mono_12/pdf_to_json_test_Latn.KNC_Mono_12.json 2>&1
Latn.KNC_Mono_16:
	-$(PYTHON) data/multilingual/Latn.KNC/Mono_16/pdf_to_json_test_Latn.KNC_Mono_16.py > data/multilingual/Latn.KNC/Mono_16/pdf_to_json_test_Latn.KNC_Mono_16.json 2>&1
Latn.KNC_Mono_8:
	-$(PYTHON) data/multilingual/Latn.KNC/Mono_8/pdf_to_json_test_Latn.KNC_Mono_8.py > data/multilingual/Latn.KNC/Mono_8/pdf_to_json_test_Latn.KNC_Mono_8.json 2>&1
Latn.KNC_Sans_12:
	-$(PYTHON) data/multilingual/Latn.KNC/Sans_12/pdf_to_json_test_Latn.KNC_Sans_12.py > data/multilingual/Latn.KNC/Sans_12/pdf_to_json_test_Latn.KNC_Sans_12.json 2>&1
Latn.KNC_Sans_16:
	-$(PYTHON) data/multilingual/Latn.KNC/Sans_16/pdf_to_json_test_Latn.KNC_Sans_16.py > data/multilingual/Latn.KNC/Sans_16/pdf_to_json_test_Latn.KNC_Sans_16.json 2>&1
Latn.KNC_Sans_8:
	-$(PYTHON) data/multilingual/Latn.KNC/Sans_8/pdf_to_json_test_Latn.KNC_Sans_8.py > data/multilingual/Latn.KNC/Sans_8/pdf_to_json_test_Latn.KNC_Sans_8.json 2>&1
Latn.KNC_Serif_12:
	-$(PYTHON) data/multilingual/Latn.KNC/Serif_12/pdf_to_json_test_Latn.KNC_Serif_12.py > data/multilingual/Latn.KNC/Serif_12/pdf_to_json_test_Latn.KNC_Serif_12.json 2>&1
Latn.KNC_Serif_16:
	-$(PYTHON) data/multilingual/Latn.KNC/Serif_16/pdf_to_json_test_Latn.KNC_Serif_16.py > data/multilingual/Latn.KNC/Serif_16/pdf_to_json_test_Latn.KNC_Serif_16.json 2>&1
Latn.KNC_Serif_8:
	-$(PYTHON) data/multilingual/Latn.KNC/Serif_8/pdf_to_json_test_Latn.KNC_Serif_8.py > data/multilingual/Latn.KNC/Serif_8/pdf_to_json_test_Latn.KNC_Serif_8.json 2>&1
Latn.KNC_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.KNC/Sun-ExtA_12/pdf_to_json_test_Latn.KNC_Sun-ExtA_12.py > data/multilingual/Latn.KNC/Sun-ExtA_12/pdf_to_json_test_Latn.KNC_Sun-ExtA_12.json 2>&1
Latn.KNC_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.KNC/Sun-ExtA_16/pdf_to_json_test_Latn.KNC_Sun-ExtA_16.py > data/multilingual/Latn.KNC/Sun-ExtA_16/pdf_to_json_test_Latn.KNC_Sun-ExtA_16.json 2>&1
Latn.KNC_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.KNC/Sun-ExtA_8/pdf_to_json_test_Latn.KNC_Sun-ExtA_8.py > data/multilingual/Latn.KNC/Sun-ExtA_8/pdf_to_json_test_Latn.KNC_Sun-ExtA_8.json 2>&1


Latn.KNC_all : Latn.KNC_Mono_12 Latn.KNC_Mono_16 Latn.KNC_Mono_8 Latn.KNC_Sans_12 Latn.KNC_Sans_16 Latn.KNC_Sans_8 Latn.KNC_Serif_12 Latn.KNC_Serif_16 Latn.KNC_Serif_8 Latn.KNC_Sun-ExtA_12 Latn.KNC_Sun-ExtA_16 Latn.KNC_Sun-ExtA_8
