PYTHON=python3


Latn.NAV_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.NAV/Mono_12/pdf_to_json_test_Latn.NAV_Mono_12.py" > "data/multilingual/Latn.NAV/Mono_12/pdf_to_json_test_Latn.NAV_Mono_12.json" 2>&1
Latn.NAV_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.NAV/Mono_16/pdf_to_json_test_Latn.NAV_Mono_16.py" > "data/multilingual/Latn.NAV/Mono_16/pdf_to_json_test_Latn.NAV_Mono_16.json" 2>&1
Latn.NAV_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.NAV/Mono_8/pdf_to_json_test_Latn.NAV_Mono_8.py" > "data/multilingual/Latn.NAV/Mono_8/pdf_to_json_test_Latn.NAV_Mono_8.json" 2>&1
Latn.NAV_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.NAV/Sans_12/pdf_to_json_test_Latn.NAV_Sans_12.py" > "data/multilingual/Latn.NAV/Sans_12/pdf_to_json_test_Latn.NAV_Sans_12.json" 2>&1
Latn.NAV_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.NAV/Sans_16/pdf_to_json_test_Latn.NAV_Sans_16.py" > "data/multilingual/Latn.NAV/Sans_16/pdf_to_json_test_Latn.NAV_Sans_16.json" 2>&1
Latn.NAV_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.NAV/Sans_8/pdf_to_json_test_Latn.NAV_Sans_8.py" > "data/multilingual/Latn.NAV/Sans_8/pdf_to_json_test_Latn.NAV_Sans_8.json" 2>&1
Latn.NAV_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.NAV/Serif_12/pdf_to_json_test_Latn.NAV_Serif_12.py" > "data/multilingual/Latn.NAV/Serif_12/pdf_to_json_test_Latn.NAV_Serif_12.json" 2>&1
Latn.NAV_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.NAV/Serif_16/pdf_to_json_test_Latn.NAV_Serif_16.py" > "data/multilingual/Latn.NAV/Serif_16/pdf_to_json_test_Latn.NAV_Serif_16.json" 2>&1
Latn.NAV_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.NAV/Serif_8/pdf_to_json_test_Latn.NAV_Serif_8.py" > "data/multilingual/Latn.NAV/Serif_8/pdf_to_json_test_Latn.NAV_Serif_8.json" 2>&1
Latn.NAV_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.NAV/Sun-ExtA_12/pdf_to_json_test_Latn.NAV_Sun-ExtA_12.py" > "data/multilingual/Latn.NAV/Sun-ExtA_12/pdf_to_json_test_Latn.NAV_Sun-ExtA_12.json" 2>&1
Latn.NAV_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.NAV/Sun-ExtA_16/pdf_to_json_test_Latn.NAV_Sun-ExtA_16.py" > "data/multilingual/Latn.NAV/Sun-ExtA_16/pdf_to_json_test_Latn.NAV_Sun-ExtA_16.json" 2>&1
Latn.NAV_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.NAV/Sun-ExtA_8/pdf_to_json_test_Latn.NAV_Sun-ExtA_8.py" > "data/multilingual/Latn.NAV/Sun-ExtA_8/pdf_to_json_test_Latn.NAV_Sun-ExtA_8.json" 2>&1


Latn.NAV_all : Latn.NAV_Mono_12 Latn.NAV_Mono_16 Latn.NAV_Mono_8 Latn.NAV_Sans_12 Latn.NAV_Sans_16 Latn.NAV_Sans_8 Latn.NAV_Serif_12 Latn.NAV_Serif_16 Latn.NAV_Serif_8 Latn.NAV_Sun-ExtA_12 Latn.NAV_Sun-ExtA_16 Latn.NAV_Sun-ExtA_8
