PYTHON=python3


Latn.SRR_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.SRR/Mono_12/pdf_to_json_test_Latn.SRR_Mono_12.py" > "data/multilingual/Latn.SRR/Mono_12/pdf_to_json_test_Latn.SRR_Mono_12.json" 2>&1
Latn.SRR_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.SRR/Mono_16/pdf_to_json_test_Latn.SRR_Mono_16.py" > "data/multilingual/Latn.SRR/Mono_16/pdf_to_json_test_Latn.SRR_Mono_16.json" 2>&1
Latn.SRR_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.SRR/Mono_8/pdf_to_json_test_Latn.SRR_Mono_8.py" > "data/multilingual/Latn.SRR/Mono_8/pdf_to_json_test_Latn.SRR_Mono_8.json" 2>&1
Latn.SRR_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.SRR/Sans_12/pdf_to_json_test_Latn.SRR_Sans_12.py" > "data/multilingual/Latn.SRR/Sans_12/pdf_to_json_test_Latn.SRR_Sans_12.json" 2>&1
Latn.SRR_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.SRR/Sans_16/pdf_to_json_test_Latn.SRR_Sans_16.py" > "data/multilingual/Latn.SRR/Sans_16/pdf_to_json_test_Latn.SRR_Sans_16.json" 2>&1
Latn.SRR_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.SRR/Sans_8/pdf_to_json_test_Latn.SRR_Sans_8.py" > "data/multilingual/Latn.SRR/Sans_8/pdf_to_json_test_Latn.SRR_Sans_8.json" 2>&1
Latn.SRR_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.SRR/Serif_12/pdf_to_json_test_Latn.SRR_Serif_12.py" > "data/multilingual/Latn.SRR/Serif_12/pdf_to_json_test_Latn.SRR_Serif_12.json" 2>&1
Latn.SRR_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.SRR/Serif_16/pdf_to_json_test_Latn.SRR_Serif_16.py" > "data/multilingual/Latn.SRR/Serif_16/pdf_to_json_test_Latn.SRR_Serif_16.json" 2>&1
Latn.SRR_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.SRR/Serif_8/pdf_to_json_test_Latn.SRR_Serif_8.py" > "data/multilingual/Latn.SRR/Serif_8/pdf_to_json_test_Latn.SRR_Serif_8.json" 2>&1
Latn.SRR_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.SRR/Sun-ExtA_12/pdf_to_json_test_Latn.SRR_Sun-ExtA_12.py" > "data/multilingual/Latn.SRR/Sun-ExtA_12/pdf_to_json_test_Latn.SRR_Sun-ExtA_12.json" 2>&1
Latn.SRR_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.SRR/Sun-ExtA_16/pdf_to_json_test_Latn.SRR_Sun-ExtA_16.py" > "data/multilingual/Latn.SRR/Sun-ExtA_16/pdf_to_json_test_Latn.SRR_Sun-ExtA_16.json" 2>&1
Latn.SRR_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.SRR/Sun-ExtA_8/pdf_to_json_test_Latn.SRR_Sun-ExtA_8.py" > "data/multilingual/Latn.SRR/Sun-ExtA_8/pdf_to_json_test_Latn.SRR_Sun-ExtA_8.json" 2>&1


Latn.SRR_all : Latn.SRR_Mono_12 Latn.SRR_Mono_16 Latn.SRR_Mono_8 Latn.SRR_Sans_12 Latn.SRR_Sans_16 Latn.SRR_Sans_8 Latn.SRR_Serif_12 Latn.SRR_Serif_16 Latn.SRR_Serif_8 Latn.SRR_Sun-ExtA_12 Latn.SRR_Sun-ExtA_16 Latn.SRR_Sun-ExtA_8
