PYTHON=python3


Latn.CSA_Mono_12:
	-$(PYTHON) data/multilingual/Latn.CSA/Mono_12/pdf_to_json_test_Latn.CSA_Mono_12.py > data/multilingual/Latn.CSA/Mono_12/pdf_to_json_test_Latn.CSA_Mono_12.json 2>&1
Latn.CSA_Mono_16:
	-$(PYTHON) data/multilingual/Latn.CSA/Mono_16/pdf_to_json_test_Latn.CSA_Mono_16.py > data/multilingual/Latn.CSA/Mono_16/pdf_to_json_test_Latn.CSA_Mono_16.json 2>&1
Latn.CSA_Mono_8:
	-$(PYTHON) data/multilingual/Latn.CSA/Mono_8/pdf_to_json_test_Latn.CSA_Mono_8.py > data/multilingual/Latn.CSA/Mono_8/pdf_to_json_test_Latn.CSA_Mono_8.json 2>&1
Latn.CSA_Sans_12:
	-$(PYTHON) data/multilingual/Latn.CSA/Sans_12/pdf_to_json_test_Latn.CSA_Sans_12.py > data/multilingual/Latn.CSA/Sans_12/pdf_to_json_test_Latn.CSA_Sans_12.json 2>&1
Latn.CSA_Sans_16:
	-$(PYTHON) data/multilingual/Latn.CSA/Sans_16/pdf_to_json_test_Latn.CSA_Sans_16.py > data/multilingual/Latn.CSA/Sans_16/pdf_to_json_test_Latn.CSA_Sans_16.json 2>&1
Latn.CSA_Sans_8:
	-$(PYTHON) data/multilingual/Latn.CSA/Sans_8/pdf_to_json_test_Latn.CSA_Sans_8.py > data/multilingual/Latn.CSA/Sans_8/pdf_to_json_test_Latn.CSA_Sans_8.json 2>&1
Latn.CSA_Serif_12:
	-$(PYTHON) data/multilingual/Latn.CSA/Serif_12/pdf_to_json_test_Latn.CSA_Serif_12.py > data/multilingual/Latn.CSA/Serif_12/pdf_to_json_test_Latn.CSA_Serif_12.json 2>&1
Latn.CSA_Serif_16:
	-$(PYTHON) data/multilingual/Latn.CSA/Serif_16/pdf_to_json_test_Latn.CSA_Serif_16.py > data/multilingual/Latn.CSA/Serif_16/pdf_to_json_test_Latn.CSA_Serif_16.json 2>&1
Latn.CSA_Serif_8:
	-$(PYTHON) data/multilingual/Latn.CSA/Serif_8/pdf_to_json_test_Latn.CSA_Serif_8.py > data/multilingual/Latn.CSA/Serif_8/pdf_to_json_test_Latn.CSA_Serif_8.json 2>&1
Latn.CSA_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.CSA/Sun-ExtA_12/pdf_to_json_test_Latn.CSA_Sun-ExtA_12.py > data/multilingual/Latn.CSA/Sun-ExtA_12/pdf_to_json_test_Latn.CSA_Sun-ExtA_12.json 2>&1
Latn.CSA_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.CSA/Sun-ExtA_16/pdf_to_json_test_Latn.CSA_Sun-ExtA_16.py > data/multilingual/Latn.CSA/Sun-ExtA_16/pdf_to_json_test_Latn.CSA_Sun-ExtA_16.json 2>&1
Latn.CSA_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.CSA/Sun-ExtA_8/pdf_to_json_test_Latn.CSA_Sun-ExtA_8.py > data/multilingual/Latn.CSA/Sun-ExtA_8/pdf_to_json_test_Latn.CSA_Sun-ExtA_8.json 2>&1


Latn.CSA_all : Latn.CSA_Mono_12 Latn.CSA_Mono_16 Latn.CSA_Mono_8 Latn.CSA_Sans_12 Latn.CSA_Sans_16 Latn.CSA_Sans_8 Latn.CSA_Serif_12 Latn.CSA_Serif_16 Latn.CSA_Serif_8 Latn.CSA_Sun-ExtA_12 Latn.CSA_Sun-ExtA_16 Latn.CSA_Sun-ExtA_8
