PYTHON=python3


Syrc.AII_Mono_12:
	-$(PYTHON) data/multilingual/Syrc.AII/Mono_12/pdf_to_json_test_Syrc.AII_Mono_12.py > data/multilingual/Syrc.AII/Mono_12/pdf_to_json_test_Syrc.AII_Mono_12.json 2>&1
Syrc.AII_Mono_16:
	-$(PYTHON) data/multilingual/Syrc.AII/Mono_16/pdf_to_json_test_Syrc.AII_Mono_16.py > data/multilingual/Syrc.AII/Mono_16/pdf_to_json_test_Syrc.AII_Mono_16.json 2>&1
Syrc.AII_Mono_8:
	-$(PYTHON) data/multilingual/Syrc.AII/Mono_8/pdf_to_json_test_Syrc.AII_Mono_8.py > data/multilingual/Syrc.AII/Mono_8/pdf_to_json_test_Syrc.AII_Mono_8.json 2>&1
Syrc.AII_Sans_12:
	-$(PYTHON) data/multilingual/Syrc.AII/Sans_12/pdf_to_json_test_Syrc.AII_Sans_12.py > data/multilingual/Syrc.AII/Sans_12/pdf_to_json_test_Syrc.AII_Sans_12.json 2>&1
Syrc.AII_Sans_16:
	-$(PYTHON) data/multilingual/Syrc.AII/Sans_16/pdf_to_json_test_Syrc.AII_Sans_16.py > data/multilingual/Syrc.AII/Sans_16/pdf_to_json_test_Syrc.AII_Sans_16.json 2>&1
Syrc.AII_Sans_8:
	-$(PYTHON) data/multilingual/Syrc.AII/Sans_8/pdf_to_json_test_Syrc.AII_Sans_8.py > data/multilingual/Syrc.AII/Sans_8/pdf_to_json_test_Syrc.AII_Sans_8.json 2>&1
Syrc.AII_Serif_12:
	-$(PYTHON) data/multilingual/Syrc.AII/Serif_12/pdf_to_json_test_Syrc.AII_Serif_12.py > data/multilingual/Syrc.AII/Serif_12/pdf_to_json_test_Syrc.AII_Serif_12.json 2>&1
Syrc.AII_Serif_16:
	-$(PYTHON) data/multilingual/Syrc.AII/Serif_16/pdf_to_json_test_Syrc.AII_Serif_16.py > data/multilingual/Syrc.AII/Serif_16/pdf_to_json_test_Syrc.AII_Serif_16.json 2>&1
Syrc.AII_Serif_8:
	-$(PYTHON) data/multilingual/Syrc.AII/Serif_8/pdf_to_json_test_Syrc.AII_Serif_8.py > data/multilingual/Syrc.AII/Serif_8/pdf_to_json_test_Syrc.AII_Serif_8.json 2>&1
Syrc.AII_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Syrc.AII/Sun-ExtA_12/pdf_to_json_test_Syrc.AII_Sun-ExtA_12.py > data/multilingual/Syrc.AII/Sun-ExtA_12/pdf_to_json_test_Syrc.AII_Sun-ExtA_12.json 2>&1
Syrc.AII_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Syrc.AII/Sun-ExtA_16/pdf_to_json_test_Syrc.AII_Sun-ExtA_16.py > data/multilingual/Syrc.AII/Sun-ExtA_16/pdf_to_json_test_Syrc.AII_Sun-ExtA_16.json 2>&1
Syrc.AII_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Syrc.AII/Sun-ExtA_8/pdf_to_json_test_Syrc.AII_Sun-ExtA_8.py > data/multilingual/Syrc.AII/Sun-ExtA_8/pdf_to_json_test_Syrc.AII_Sun-ExtA_8.json 2>&1


Syrc.AII_all : Syrc.AII_Mono_12 Syrc.AII_Mono_16 Syrc.AII_Mono_8 Syrc.AII_Sans_12 Syrc.AII_Sans_16 Syrc.AII_Sans_8 Syrc.AII_Serif_12 Syrc.AII_Serif_16 Syrc.AII_Serif_8 Syrc.AII_Sun-ExtA_12 Syrc.AII_Sun-ExtA_16 Syrc.AII_Sun-ExtA_8
