PYTHON=python3


Latn.GUG_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.GUG/Mono_12/pdf_to_json_test_Latn.GUG_Mono_12.py" > "data/multilingual/Latn.GUG/Mono_12/pdf_to_json_test_Latn.GUG_Mono_12.json" 2>&1
Latn.GUG_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.GUG/Mono_16/pdf_to_json_test_Latn.GUG_Mono_16.py" > "data/multilingual/Latn.GUG/Mono_16/pdf_to_json_test_Latn.GUG_Mono_16.json" 2>&1
Latn.GUG_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.GUG/Mono_8/pdf_to_json_test_Latn.GUG_Mono_8.py" > "data/multilingual/Latn.GUG/Mono_8/pdf_to_json_test_Latn.GUG_Mono_8.json" 2>&1
Latn.GUG_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.GUG/Sans_12/pdf_to_json_test_Latn.GUG_Sans_12.py" > "data/multilingual/Latn.GUG/Sans_12/pdf_to_json_test_Latn.GUG_Sans_12.json" 2>&1
Latn.GUG_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.GUG/Sans_16/pdf_to_json_test_Latn.GUG_Sans_16.py" > "data/multilingual/Latn.GUG/Sans_16/pdf_to_json_test_Latn.GUG_Sans_16.json" 2>&1
Latn.GUG_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.GUG/Sans_8/pdf_to_json_test_Latn.GUG_Sans_8.py" > "data/multilingual/Latn.GUG/Sans_8/pdf_to_json_test_Latn.GUG_Sans_8.json" 2>&1
Latn.GUG_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.GUG/Serif_12/pdf_to_json_test_Latn.GUG_Serif_12.py" > "data/multilingual/Latn.GUG/Serif_12/pdf_to_json_test_Latn.GUG_Serif_12.json" 2>&1
Latn.GUG_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.GUG/Serif_16/pdf_to_json_test_Latn.GUG_Serif_16.py" > "data/multilingual/Latn.GUG/Serif_16/pdf_to_json_test_Latn.GUG_Serif_16.json" 2>&1
Latn.GUG_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.GUG/Serif_8/pdf_to_json_test_Latn.GUG_Serif_8.py" > "data/multilingual/Latn.GUG/Serif_8/pdf_to_json_test_Latn.GUG_Serif_8.json" 2>&1
Latn.GUG_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.GUG/Sun-ExtA_12/pdf_to_json_test_Latn.GUG_Sun-ExtA_12.py" > "data/multilingual/Latn.GUG/Sun-ExtA_12/pdf_to_json_test_Latn.GUG_Sun-ExtA_12.json" 2>&1
Latn.GUG_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.GUG/Sun-ExtA_16/pdf_to_json_test_Latn.GUG_Sun-ExtA_16.py" > "data/multilingual/Latn.GUG/Sun-ExtA_16/pdf_to_json_test_Latn.GUG_Sun-ExtA_16.json" 2>&1
Latn.GUG_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.GUG/Sun-ExtA_8/pdf_to_json_test_Latn.GUG_Sun-ExtA_8.py" > "data/multilingual/Latn.GUG/Sun-ExtA_8/pdf_to_json_test_Latn.GUG_Sun-ExtA_8.json" 2>&1


Latn.GUG_all : Latn.GUG_Mono_12 Latn.GUG_Mono_16 Latn.GUG_Mono_8 Latn.GUG_Sans_12 Latn.GUG_Sans_16 Latn.GUG_Sans_8 Latn.GUG_Serif_12 Latn.GUG_Serif_16 Latn.GUG_Serif_8 Latn.GUG_Sun-ExtA_12 Latn.GUG_Sun-ExtA_16 Latn.GUG_Sun-ExtA_8
