PYTHON=python3


Latn.SOM_Mono_12:
	-$(PYTHON) data/multilingual/Latn.SOM/Mono_12/pdf_to_json_test_Latn.SOM_Mono_12.py > data/multilingual/Latn.SOM/Mono_12/pdf_to_json_test_Latn.SOM_Mono_12.json 2>&1
Latn.SOM_Mono_16:
	-$(PYTHON) data/multilingual/Latn.SOM/Mono_16/pdf_to_json_test_Latn.SOM_Mono_16.py > data/multilingual/Latn.SOM/Mono_16/pdf_to_json_test_Latn.SOM_Mono_16.json 2>&1
Latn.SOM_Mono_8:
	-$(PYTHON) data/multilingual/Latn.SOM/Mono_8/pdf_to_json_test_Latn.SOM_Mono_8.py > data/multilingual/Latn.SOM/Mono_8/pdf_to_json_test_Latn.SOM_Mono_8.json 2>&1
Latn.SOM_Sans_12:
	-$(PYTHON) data/multilingual/Latn.SOM/Sans_12/pdf_to_json_test_Latn.SOM_Sans_12.py > data/multilingual/Latn.SOM/Sans_12/pdf_to_json_test_Latn.SOM_Sans_12.json 2>&1
Latn.SOM_Sans_16:
	-$(PYTHON) data/multilingual/Latn.SOM/Sans_16/pdf_to_json_test_Latn.SOM_Sans_16.py > data/multilingual/Latn.SOM/Sans_16/pdf_to_json_test_Latn.SOM_Sans_16.json 2>&1
Latn.SOM_Sans_8:
	-$(PYTHON) data/multilingual/Latn.SOM/Sans_8/pdf_to_json_test_Latn.SOM_Sans_8.py > data/multilingual/Latn.SOM/Sans_8/pdf_to_json_test_Latn.SOM_Sans_8.json 2>&1
Latn.SOM_Serif_12:
	-$(PYTHON) data/multilingual/Latn.SOM/Serif_12/pdf_to_json_test_Latn.SOM_Serif_12.py > data/multilingual/Latn.SOM/Serif_12/pdf_to_json_test_Latn.SOM_Serif_12.json 2>&1
Latn.SOM_Serif_16:
	-$(PYTHON) data/multilingual/Latn.SOM/Serif_16/pdf_to_json_test_Latn.SOM_Serif_16.py > data/multilingual/Latn.SOM/Serif_16/pdf_to_json_test_Latn.SOM_Serif_16.json 2>&1
Latn.SOM_Serif_8:
	-$(PYTHON) data/multilingual/Latn.SOM/Serif_8/pdf_to_json_test_Latn.SOM_Serif_8.py > data/multilingual/Latn.SOM/Serif_8/pdf_to_json_test_Latn.SOM_Serif_8.json 2>&1
Latn.SOM_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.SOM/Sun-ExtA_12/pdf_to_json_test_Latn.SOM_Sun-ExtA_12.py > data/multilingual/Latn.SOM/Sun-ExtA_12/pdf_to_json_test_Latn.SOM_Sun-ExtA_12.json 2>&1
Latn.SOM_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.SOM/Sun-ExtA_16/pdf_to_json_test_Latn.SOM_Sun-ExtA_16.py > data/multilingual/Latn.SOM/Sun-ExtA_16/pdf_to_json_test_Latn.SOM_Sun-ExtA_16.json 2>&1
Latn.SOM_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.SOM/Sun-ExtA_8/pdf_to_json_test_Latn.SOM_Sun-ExtA_8.py > data/multilingual/Latn.SOM/Sun-ExtA_8/pdf_to_json_test_Latn.SOM_Sun-ExtA_8.json 2>&1


Latn.SOM_all : Latn.SOM_Mono_12 Latn.SOM_Mono_16 Latn.SOM_Mono_8 Latn.SOM_Sans_12 Latn.SOM_Sans_16 Latn.SOM_Sans_8 Latn.SOM_Serif_12 Latn.SOM_Serif_16 Latn.SOM_Serif_8 Latn.SOM_Sun-ExtA_12 Latn.SOM_Sun-ExtA_16 Latn.SOM_Sun-ExtA_8
