PYTHON=python3


Cyrl.EVE_Mono_12:
	-$(PYTHON) "data/multilingual/Cyrl.EVE/Mono_12/pdf_to_json_test_Cyrl.EVE_Mono_12.py" > "data/multilingual/Cyrl.EVE/Mono_12/pdf_to_json_test_Cyrl.EVE_Mono_12.json" 2>&1
Cyrl.EVE_Mono_16:
	-$(PYTHON) "data/multilingual/Cyrl.EVE/Mono_16/pdf_to_json_test_Cyrl.EVE_Mono_16.py" > "data/multilingual/Cyrl.EVE/Mono_16/pdf_to_json_test_Cyrl.EVE_Mono_16.json" 2>&1
Cyrl.EVE_Mono_8:
	-$(PYTHON) "data/multilingual/Cyrl.EVE/Mono_8/pdf_to_json_test_Cyrl.EVE_Mono_8.py" > "data/multilingual/Cyrl.EVE/Mono_8/pdf_to_json_test_Cyrl.EVE_Mono_8.json" 2>&1
Cyrl.EVE_Sans_12:
	-$(PYTHON) "data/multilingual/Cyrl.EVE/Sans_12/pdf_to_json_test_Cyrl.EVE_Sans_12.py" > "data/multilingual/Cyrl.EVE/Sans_12/pdf_to_json_test_Cyrl.EVE_Sans_12.json" 2>&1
Cyrl.EVE_Sans_16:
	-$(PYTHON) "data/multilingual/Cyrl.EVE/Sans_16/pdf_to_json_test_Cyrl.EVE_Sans_16.py" > "data/multilingual/Cyrl.EVE/Sans_16/pdf_to_json_test_Cyrl.EVE_Sans_16.json" 2>&1
Cyrl.EVE_Sans_8:
	-$(PYTHON) "data/multilingual/Cyrl.EVE/Sans_8/pdf_to_json_test_Cyrl.EVE_Sans_8.py" > "data/multilingual/Cyrl.EVE/Sans_8/pdf_to_json_test_Cyrl.EVE_Sans_8.json" 2>&1
Cyrl.EVE_Serif_12:
	-$(PYTHON) "data/multilingual/Cyrl.EVE/Serif_12/pdf_to_json_test_Cyrl.EVE_Serif_12.py" > "data/multilingual/Cyrl.EVE/Serif_12/pdf_to_json_test_Cyrl.EVE_Serif_12.json" 2>&1
Cyrl.EVE_Serif_16:
	-$(PYTHON) "data/multilingual/Cyrl.EVE/Serif_16/pdf_to_json_test_Cyrl.EVE_Serif_16.py" > "data/multilingual/Cyrl.EVE/Serif_16/pdf_to_json_test_Cyrl.EVE_Serif_16.json" 2>&1
Cyrl.EVE_Serif_8:
	-$(PYTHON) "data/multilingual/Cyrl.EVE/Serif_8/pdf_to_json_test_Cyrl.EVE_Serif_8.py" > "data/multilingual/Cyrl.EVE/Serif_8/pdf_to_json_test_Cyrl.EVE_Serif_8.json" 2>&1
Cyrl.EVE_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Cyrl.EVE/Sun-ExtA_12/pdf_to_json_test_Cyrl.EVE_Sun-ExtA_12.py" > "data/multilingual/Cyrl.EVE/Sun-ExtA_12/pdf_to_json_test_Cyrl.EVE_Sun-ExtA_12.json" 2>&1
Cyrl.EVE_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Cyrl.EVE/Sun-ExtA_16/pdf_to_json_test_Cyrl.EVE_Sun-ExtA_16.py" > "data/multilingual/Cyrl.EVE/Sun-ExtA_16/pdf_to_json_test_Cyrl.EVE_Sun-ExtA_16.json" 2>&1
Cyrl.EVE_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Cyrl.EVE/Sun-ExtA_8/pdf_to_json_test_Cyrl.EVE_Sun-ExtA_8.py" > "data/multilingual/Cyrl.EVE/Sun-ExtA_8/pdf_to_json_test_Cyrl.EVE_Sun-ExtA_8.json" 2>&1


Cyrl.EVE_all : Cyrl.EVE_Mono_12 Cyrl.EVE_Mono_16 Cyrl.EVE_Mono_8 Cyrl.EVE_Sans_12 Cyrl.EVE_Sans_16 Cyrl.EVE_Sans_8 Cyrl.EVE_Serif_12 Cyrl.EVE_Serif_16 Cyrl.EVE_Serif_8 Cyrl.EVE_Sun-ExtA_12 Cyrl.EVE_Sun-ExtA_16 Cyrl.EVE_Sun-ExtA_8
