PYTHON=python3


Mymr.MNW_Mono_12:
	-$(PYTHON) "data/multilingual/Mymr.MNW/Mono_12/pdf_to_json_test_Mymr.MNW_Mono_12.py" > "data/multilingual/Mymr.MNW/Mono_12/pdf_to_json_test_Mymr.MNW_Mono_12.json" 2>&1
Mymr.MNW_Mono_16:
	-$(PYTHON) "data/multilingual/Mymr.MNW/Mono_16/pdf_to_json_test_Mymr.MNW_Mono_16.py" > "data/multilingual/Mymr.MNW/Mono_16/pdf_to_json_test_Mymr.MNW_Mono_16.json" 2>&1
Mymr.MNW_Mono_8:
	-$(PYTHON) "data/multilingual/Mymr.MNW/Mono_8/pdf_to_json_test_Mymr.MNW_Mono_8.py" > "data/multilingual/Mymr.MNW/Mono_8/pdf_to_json_test_Mymr.MNW_Mono_8.json" 2>&1
Mymr.MNW_Sans_12:
	-$(PYTHON) "data/multilingual/Mymr.MNW/Sans_12/pdf_to_json_test_Mymr.MNW_Sans_12.py" > "data/multilingual/Mymr.MNW/Sans_12/pdf_to_json_test_Mymr.MNW_Sans_12.json" 2>&1
Mymr.MNW_Sans_16:
	-$(PYTHON) "data/multilingual/Mymr.MNW/Sans_16/pdf_to_json_test_Mymr.MNW_Sans_16.py" > "data/multilingual/Mymr.MNW/Sans_16/pdf_to_json_test_Mymr.MNW_Sans_16.json" 2>&1
Mymr.MNW_Sans_8:
	-$(PYTHON) "data/multilingual/Mymr.MNW/Sans_8/pdf_to_json_test_Mymr.MNW_Sans_8.py" > "data/multilingual/Mymr.MNW/Sans_8/pdf_to_json_test_Mymr.MNW_Sans_8.json" 2>&1
Mymr.MNW_Serif_12:
	-$(PYTHON) "data/multilingual/Mymr.MNW/Serif_12/pdf_to_json_test_Mymr.MNW_Serif_12.py" > "data/multilingual/Mymr.MNW/Serif_12/pdf_to_json_test_Mymr.MNW_Serif_12.json" 2>&1
Mymr.MNW_Serif_16:
	-$(PYTHON) "data/multilingual/Mymr.MNW/Serif_16/pdf_to_json_test_Mymr.MNW_Serif_16.py" > "data/multilingual/Mymr.MNW/Serif_16/pdf_to_json_test_Mymr.MNW_Serif_16.json" 2>&1
Mymr.MNW_Serif_8:
	-$(PYTHON) "data/multilingual/Mymr.MNW/Serif_8/pdf_to_json_test_Mymr.MNW_Serif_8.py" > "data/multilingual/Mymr.MNW/Serif_8/pdf_to_json_test_Mymr.MNW_Serif_8.json" 2>&1
Mymr.MNW_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Mymr.MNW/Sun-ExtA_12/pdf_to_json_test_Mymr.MNW_Sun-ExtA_12.py" > "data/multilingual/Mymr.MNW/Sun-ExtA_12/pdf_to_json_test_Mymr.MNW_Sun-ExtA_12.json" 2>&1
Mymr.MNW_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Mymr.MNW/Sun-ExtA_16/pdf_to_json_test_Mymr.MNW_Sun-ExtA_16.py" > "data/multilingual/Mymr.MNW/Sun-ExtA_16/pdf_to_json_test_Mymr.MNW_Sun-ExtA_16.json" 2>&1
Mymr.MNW_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Mymr.MNW/Sun-ExtA_8/pdf_to_json_test_Mymr.MNW_Sun-ExtA_8.py" > "data/multilingual/Mymr.MNW/Sun-ExtA_8/pdf_to_json_test_Mymr.MNW_Sun-ExtA_8.json" 2>&1


Mymr.MNW_all : Mymr.MNW_Mono_12 Mymr.MNW_Mono_16 Mymr.MNW_Mono_8 Mymr.MNW_Sans_12 Mymr.MNW_Sans_16 Mymr.MNW_Sans_8 Mymr.MNW_Serif_12 Mymr.MNW_Serif_16 Mymr.MNW_Serif_8 Mymr.MNW_Sun-ExtA_12 Mymr.MNW_Sun-ExtA_16 Mymr.MNW_Sun-ExtA_8
