PYTHON=python3


Latn.BBA_Mono_12:
	-$(PYTHON) data/multilingual/Latn.BBA/Mono_12/pdf_to_json_test_Latn.BBA_Mono_12.py > data/multilingual/Latn.BBA/Mono_12/pdf_to_json_test_Latn.BBA_Mono_12.json 2>&1
Latn.BBA_Mono_16:
	-$(PYTHON) data/multilingual/Latn.BBA/Mono_16/pdf_to_json_test_Latn.BBA_Mono_16.py > data/multilingual/Latn.BBA/Mono_16/pdf_to_json_test_Latn.BBA_Mono_16.json 2>&1
Latn.BBA_Mono_8:
	-$(PYTHON) data/multilingual/Latn.BBA/Mono_8/pdf_to_json_test_Latn.BBA_Mono_8.py > data/multilingual/Latn.BBA/Mono_8/pdf_to_json_test_Latn.BBA_Mono_8.json 2>&1
Latn.BBA_Sans_12:
	-$(PYTHON) data/multilingual/Latn.BBA/Sans_12/pdf_to_json_test_Latn.BBA_Sans_12.py > data/multilingual/Latn.BBA/Sans_12/pdf_to_json_test_Latn.BBA_Sans_12.json 2>&1
Latn.BBA_Sans_16:
	-$(PYTHON) data/multilingual/Latn.BBA/Sans_16/pdf_to_json_test_Latn.BBA_Sans_16.py > data/multilingual/Latn.BBA/Sans_16/pdf_to_json_test_Latn.BBA_Sans_16.json 2>&1
Latn.BBA_Sans_8:
	-$(PYTHON) data/multilingual/Latn.BBA/Sans_8/pdf_to_json_test_Latn.BBA_Sans_8.py > data/multilingual/Latn.BBA/Sans_8/pdf_to_json_test_Latn.BBA_Sans_8.json 2>&1
Latn.BBA_Serif_12:
	-$(PYTHON) data/multilingual/Latn.BBA/Serif_12/pdf_to_json_test_Latn.BBA_Serif_12.py > data/multilingual/Latn.BBA/Serif_12/pdf_to_json_test_Latn.BBA_Serif_12.json 2>&1
Latn.BBA_Serif_16:
	-$(PYTHON) data/multilingual/Latn.BBA/Serif_16/pdf_to_json_test_Latn.BBA_Serif_16.py > data/multilingual/Latn.BBA/Serif_16/pdf_to_json_test_Latn.BBA_Serif_16.json 2>&1
Latn.BBA_Serif_8:
	-$(PYTHON) data/multilingual/Latn.BBA/Serif_8/pdf_to_json_test_Latn.BBA_Serif_8.py > data/multilingual/Latn.BBA/Serif_8/pdf_to_json_test_Latn.BBA_Serif_8.json 2>&1
Latn.BBA_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.BBA/Sun-ExtA_12/pdf_to_json_test_Latn.BBA_Sun-ExtA_12.py > data/multilingual/Latn.BBA/Sun-ExtA_12/pdf_to_json_test_Latn.BBA_Sun-ExtA_12.json 2>&1
Latn.BBA_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.BBA/Sun-ExtA_16/pdf_to_json_test_Latn.BBA_Sun-ExtA_16.py > data/multilingual/Latn.BBA/Sun-ExtA_16/pdf_to_json_test_Latn.BBA_Sun-ExtA_16.json 2>&1
Latn.BBA_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.BBA/Sun-ExtA_8/pdf_to_json_test_Latn.BBA_Sun-ExtA_8.py > data/multilingual/Latn.BBA/Sun-ExtA_8/pdf_to_json_test_Latn.BBA_Sun-ExtA_8.json 2>&1


Latn.BBA_all : Latn.BBA_Mono_12 Latn.BBA_Mono_16 Latn.BBA_Mono_8 Latn.BBA_Sans_12 Latn.BBA_Sans_16 Latn.BBA_Sans_8 Latn.BBA_Serif_12 Latn.BBA_Serif_16 Latn.BBA_Serif_8 Latn.BBA_Sun-ExtA_12 Latn.BBA_Sun-ExtA_16 Latn.BBA_Sun-ExtA_8
