PYTHON=python3


Latn.TOI_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.TOI/Mono_12/pdf_to_json_test_Latn.TOI_Mono_12.py" > "data/multilingual/Latn.TOI/Mono_12/pdf_to_json_test_Latn.TOI_Mono_12.json" 2>&1
Latn.TOI_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.TOI/Mono_16/pdf_to_json_test_Latn.TOI_Mono_16.py" > "data/multilingual/Latn.TOI/Mono_16/pdf_to_json_test_Latn.TOI_Mono_16.json" 2>&1
Latn.TOI_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.TOI/Mono_8/pdf_to_json_test_Latn.TOI_Mono_8.py" > "data/multilingual/Latn.TOI/Mono_8/pdf_to_json_test_Latn.TOI_Mono_8.json" 2>&1
Latn.TOI_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.TOI/Sans_12/pdf_to_json_test_Latn.TOI_Sans_12.py" > "data/multilingual/Latn.TOI/Sans_12/pdf_to_json_test_Latn.TOI_Sans_12.json" 2>&1
Latn.TOI_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.TOI/Sans_16/pdf_to_json_test_Latn.TOI_Sans_16.py" > "data/multilingual/Latn.TOI/Sans_16/pdf_to_json_test_Latn.TOI_Sans_16.json" 2>&1
Latn.TOI_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.TOI/Sans_8/pdf_to_json_test_Latn.TOI_Sans_8.py" > "data/multilingual/Latn.TOI/Sans_8/pdf_to_json_test_Latn.TOI_Sans_8.json" 2>&1
Latn.TOI_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.TOI/Serif_12/pdf_to_json_test_Latn.TOI_Serif_12.py" > "data/multilingual/Latn.TOI/Serif_12/pdf_to_json_test_Latn.TOI_Serif_12.json" 2>&1
Latn.TOI_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.TOI/Serif_16/pdf_to_json_test_Latn.TOI_Serif_16.py" > "data/multilingual/Latn.TOI/Serif_16/pdf_to_json_test_Latn.TOI_Serif_16.json" 2>&1
Latn.TOI_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.TOI/Serif_8/pdf_to_json_test_Latn.TOI_Serif_8.py" > "data/multilingual/Latn.TOI/Serif_8/pdf_to_json_test_Latn.TOI_Serif_8.json" 2>&1
Latn.TOI_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.TOI/Sun-ExtA_12/pdf_to_json_test_Latn.TOI_Sun-ExtA_12.py" > "data/multilingual/Latn.TOI/Sun-ExtA_12/pdf_to_json_test_Latn.TOI_Sun-ExtA_12.json" 2>&1
Latn.TOI_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.TOI/Sun-ExtA_16/pdf_to_json_test_Latn.TOI_Sun-ExtA_16.py" > "data/multilingual/Latn.TOI/Sun-ExtA_16/pdf_to_json_test_Latn.TOI_Sun-ExtA_16.json" 2>&1
Latn.TOI_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.TOI/Sun-ExtA_8/pdf_to_json_test_Latn.TOI_Sun-ExtA_8.py" > "data/multilingual/Latn.TOI/Sun-ExtA_8/pdf_to_json_test_Latn.TOI_Sun-ExtA_8.json" 2>&1


Latn.TOI_all : Latn.TOI_Mono_12 Latn.TOI_Mono_16 Latn.TOI_Mono_8 Latn.TOI_Sans_12 Latn.TOI_Sans_16 Latn.TOI_Sans_8 Latn.TOI_Serif_12 Latn.TOI_Serif_16 Latn.TOI_Serif_8 Latn.TOI_Sun-ExtA_12 Latn.TOI_Sun-ExtA_16 Latn.TOI_Sun-ExtA_8
