PYTHON=python3


Hebr.YDD_Mono_12:
	-$(PYTHON) data/multilingual/Hebr.YDD/Mono_12/pdf_to_json_test_Hebr.YDD_Mono_12.py > data/multilingual/Hebr.YDD/Mono_12/pdf_to_json_test_Hebr.YDD_Mono_12.json 2>&1
Hebr.YDD_Mono_16:
	-$(PYTHON) data/multilingual/Hebr.YDD/Mono_16/pdf_to_json_test_Hebr.YDD_Mono_16.py > data/multilingual/Hebr.YDD/Mono_16/pdf_to_json_test_Hebr.YDD_Mono_16.json 2>&1
Hebr.YDD_Mono_8:
	-$(PYTHON) data/multilingual/Hebr.YDD/Mono_8/pdf_to_json_test_Hebr.YDD_Mono_8.py > data/multilingual/Hebr.YDD/Mono_8/pdf_to_json_test_Hebr.YDD_Mono_8.json 2>&1
Hebr.YDD_Sans_12:
	-$(PYTHON) data/multilingual/Hebr.YDD/Sans_12/pdf_to_json_test_Hebr.YDD_Sans_12.py > data/multilingual/Hebr.YDD/Sans_12/pdf_to_json_test_Hebr.YDD_Sans_12.json 2>&1
Hebr.YDD_Sans_16:
	-$(PYTHON) data/multilingual/Hebr.YDD/Sans_16/pdf_to_json_test_Hebr.YDD_Sans_16.py > data/multilingual/Hebr.YDD/Sans_16/pdf_to_json_test_Hebr.YDD_Sans_16.json 2>&1
Hebr.YDD_Sans_8:
	-$(PYTHON) data/multilingual/Hebr.YDD/Sans_8/pdf_to_json_test_Hebr.YDD_Sans_8.py > data/multilingual/Hebr.YDD/Sans_8/pdf_to_json_test_Hebr.YDD_Sans_8.json 2>&1
Hebr.YDD_Serif_12:
	-$(PYTHON) data/multilingual/Hebr.YDD/Serif_12/pdf_to_json_test_Hebr.YDD_Serif_12.py > data/multilingual/Hebr.YDD/Serif_12/pdf_to_json_test_Hebr.YDD_Serif_12.json 2>&1
Hebr.YDD_Serif_16:
	-$(PYTHON) data/multilingual/Hebr.YDD/Serif_16/pdf_to_json_test_Hebr.YDD_Serif_16.py > data/multilingual/Hebr.YDD/Serif_16/pdf_to_json_test_Hebr.YDD_Serif_16.json 2>&1
Hebr.YDD_Serif_8:
	-$(PYTHON) data/multilingual/Hebr.YDD/Serif_8/pdf_to_json_test_Hebr.YDD_Serif_8.py > data/multilingual/Hebr.YDD/Serif_8/pdf_to_json_test_Hebr.YDD_Serif_8.json 2>&1
Hebr.YDD_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Hebr.YDD/Sun-ExtA_12/pdf_to_json_test_Hebr.YDD_Sun-ExtA_12.py > data/multilingual/Hebr.YDD/Sun-ExtA_12/pdf_to_json_test_Hebr.YDD_Sun-ExtA_12.json 2>&1
Hebr.YDD_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Hebr.YDD/Sun-ExtA_16/pdf_to_json_test_Hebr.YDD_Sun-ExtA_16.py > data/multilingual/Hebr.YDD/Sun-ExtA_16/pdf_to_json_test_Hebr.YDD_Sun-ExtA_16.json 2>&1
Hebr.YDD_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Hebr.YDD/Sun-ExtA_8/pdf_to_json_test_Hebr.YDD_Sun-ExtA_8.py > data/multilingual/Hebr.YDD/Sun-ExtA_8/pdf_to_json_test_Hebr.YDD_Sun-ExtA_8.json 2>&1


Hebr.YDD_all : Hebr.YDD_Mono_12 Hebr.YDD_Mono_16 Hebr.YDD_Mono_8 Hebr.YDD_Sans_12 Hebr.YDD_Sans_16 Hebr.YDD_Sans_8 Hebr.YDD_Serif_12 Hebr.YDD_Serif_16 Hebr.YDD_Serif_8 Hebr.YDD_Sun-ExtA_12 Hebr.YDD_Sun-ExtA_16 Hebr.YDD_Sun-ExtA_8
