PYTHON=python3


Deva.MAG_Mono_12:
	-$(PYTHON) data/multilingual/Deva.MAG/Mono_12/pdf_to_json_test_Deva.MAG_Mono_12.py > data/multilingual/Deva.MAG/Mono_12/pdf_to_json_test_Deva.MAG_Mono_12.json 2>&1
Deva.MAG_Mono_16:
	-$(PYTHON) data/multilingual/Deva.MAG/Mono_16/pdf_to_json_test_Deva.MAG_Mono_16.py > data/multilingual/Deva.MAG/Mono_16/pdf_to_json_test_Deva.MAG_Mono_16.json 2>&1
Deva.MAG_Mono_8:
	-$(PYTHON) data/multilingual/Deva.MAG/Mono_8/pdf_to_json_test_Deva.MAG_Mono_8.py > data/multilingual/Deva.MAG/Mono_8/pdf_to_json_test_Deva.MAG_Mono_8.json 2>&1
Deva.MAG_Sans_12:
	-$(PYTHON) data/multilingual/Deva.MAG/Sans_12/pdf_to_json_test_Deva.MAG_Sans_12.py > data/multilingual/Deva.MAG/Sans_12/pdf_to_json_test_Deva.MAG_Sans_12.json 2>&1
Deva.MAG_Sans_16:
	-$(PYTHON) data/multilingual/Deva.MAG/Sans_16/pdf_to_json_test_Deva.MAG_Sans_16.py > data/multilingual/Deva.MAG/Sans_16/pdf_to_json_test_Deva.MAG_Sans_16.json 2>&1
Deva.MAG_Sans_8:
	-$(PYTHON) data/multilingual/Deva.MAG/Sans_8/pdf_to_json_test_Deva.MAG_Sans_8.py > data/multilingual/Deva.MAG/Sans_8/pdf_to_json_test_Deva.MAG_Sans_8.json 2>&1
Deva.MAG_Serif_12:
	-$(PYTHON) data/multilingual/Deva.MAG/Serif_12/pdf_to_json_test_Deva.MAG_Serif_12.py > data/multilingual/Deva.MAG/Serif_12/pdf_to_json_test_Deva.MAG_Serif_12.json 2>&1
Deva.MAG_Serif_16:
	-$(PYTHON) data/multilingual/Deva.MAG/Serif_16/pdf_to_json_test_Deva.MAG_Serif_16.py > data/multilingual/Deva.MAG/Serif_16/pdf_to_json_test_Deva.MAG_Serif_16.json 2>&1
Deva.MAG_Serif_8:
	-$(PYTHON) data/multilingual/Deva.MAG/Serif_8/pdf_to_json_test_Deva.MAG_Serif_8.py > data/multilingual/Deva.MAG/Serif_8/pdf_to_json_test_Deva.MAG_Serif_8.json 2>&1
Deva.MAG_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Deva.MAG/Sun-ExtA_12/pdf_to_json_test_Deva.MAG_Sun-ExtA_12.py > data/multilingual/Deva.MAG/Sun-ExtA_12/pdf_to_json_test_Deva.MAG_Sun-ExtA_12.json 2>&1
Deva.MAG_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Deva.MAG/Sun-ExtA_16/pdf_to_json_test_Deva.MAG_Sun-ExtA_16.py > data/multilingual/Deva.MAG/Sun-ExtA_16/pdf_to_json_test_Deva.MAG_Sun-ExtA_16.json 2>&1
Deva.MAG_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Deva.MAG/Sun-ExtA_8/pdf_to_json_test_Deva.MAG_Sun-ExtA_8.py > data/multilingual/Deva.MAG/Sun-ExtA_8/pdf_to_json_test_Deva.MAG_Sun-ExtA_8.json 2>&1


Deva.MAG_all : Deva.MAG_Mono_12 Deva.MAG_Mono_16 Deva.MAG_Mono_8 Deva.MAG_Sans_12 Deva.MAG_Sans_16 Deva.MAG_Sans_8 Deva.MAG_Serif_12 Deva.MAG_Serif_16 Deva.MAG_Serif_8 Deva.MAG_Sun-ExtA_12 Deva.MAG_Sun-ExtA_16 Deva.MAG_Sun-ExtA_8
