PYTHON=python3


Latn.CBR_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.CBR/Mono_12/pdf_to_json_test_Latn.CBR_Mono_12.py" > "data/multilingual/Latn.CBR/Mono_12/pdf_to_json_test_Latn.CBR_Mono_12.json" 2>&1
Latn.CBR_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.CBR/Mono_16/pdf_to_json_test_Latn.CBR_Mono_16.py" > "data/multilingual/Latn.CBR/Mono_16/pdf_to_json_test_Latn.CBR_Mono_16.json" 2>&1
Latn.CBR_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.CBR/Mono_8/pdf_to_json_test_Latn.CBR_Mono_8.py" > "data/multilingual/Latn.CBR/Mono_8/pdf_to_json_test_Latn.CBR_Mono_8.json" 2>&1
Latn.CBR_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.CBR/Sans_12/pdf_to_json_test_Latn.CBR_Sans_12.py" > "data/multilingual/Latn.CBR/Sans_12/pdf_to_json_test_Latn.CBR_Sans_12.json" 2>&1
Latn.CBR_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.CBR/Sans_16/pdf_to_json_test_Latn.CBR_Sans_16.py" > "data/multilingual/Latn.CBR/Sans_16/pdf_to_json_test_Latn.CBR_Sans_16.json" 2>&1
Latn.CBR_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.CBR/Sans_8/pdf_to_json_test_Latn.CBR_Sans_8.py" > "data/multilingual/Latn.CBR/Sans_8/pdf_to_json_test_Latn.CBR_Sans_8.json" 2>&1
Latn.CBR_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.CBR/Serif_12/pdf_to_json_test_Latn.CBR_Serif_12.py" > "data/multilingual/Latn.CBR/Serif_12/pdf_to_json_test_Latn.CBR_Serif_12.json" 2>&1
Latn.CBR_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.CBR/Serif_16/pdf_to_json_test_Latn.CBR_Serif_16.py" > "data/multilingual/Latn.CBR/Serif_16/pdf_to_json_test_Latn.CBR_Serif_16.json" 2>&1
Latn.CBR_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.CBR/Serif_8/pdf_to_json_test_Latn.CBR_Serif_8.py" > "data/multilingual/Latn.CBR/Serif_8/pdf_to_json_test_Latn.CBR_Serif_8.json" 2>&1
Latn.CBR_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.CBR/Sun-ExtA_12/pdf_to_json_test_Latn.CBR_Sun-ExtA_12.py" > "data/multilingual/Latn.CBR/Sun-ExtA_12/pdf_to_json_test_Latn.CBR_Sun-ExtA_12.json" 2>&1
Latn.CBR_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.CBR/Sun-ExtA_16/pdf_to_json_test_Latn.CBR_Sun-ExtA_16.py" > "data/multilingual/Latn.CBR/Sun-ExtA_16/pdf_to_json_test_Latn.CBR_Sun-ExtA_16.json" 2>&1
Latn.CBR_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.CBR/Sun-ExtA_8/pdf_to_json_test_Latn.CBR_Sun-ExtA_8.py" > "data/multilingual/Latn.CBR/Sun-ExtA_8/pdf_to_json_test_Latn.CBR_Sun-ExtA_8.json" 2>&1


Latn.CBR_all : Latn.CBR_Mono_12 Latn.CBR_Mono_16 Latn.CBR_Mono_8 Latn.CBR_Sans_12 Latn.CBR_Sans_16 Latn.CBR_Sans_8 Latn.CBR_Serif_12 Latn.CBR_Serif_16 Latn.CBR_Serif_8 Latn.CBR_Sun-ExtA_12 Latn.CBR_Sun-ExtA_16 Latn.CBR_Sun-ExtA_8
