PYTHON=python3


Latn.HUU_Mono_12:
	-$(PYTHON) data/multilingual/Latn.HUU/Mono_12/pdf_to_json_test_Latn.HUU_Mono_12.py > data/multilingual/Latn.HUU/Mono_12/pdf_to_json_test_Latn.HUU_Mono_12.json 2>&1
Latn.HUU_Mono_16:
	-$(PYTHON) data/multilingual/Latn.HUU/Mono_16/pdf_to_json_test_Latn.HUU_Mono_16.py > data/multilingual/Latn.HUU/Mono_16/pdf_to_json_test_Latn.HUU_Mono_16.json 2>&1
Latn.HUU_Mono_8:
	-$(PYTHON) data/multilingual/Latn.HUU/Mono_8/pdf_to_json_test_Latn.HUU_Mono_8.py > data/multilingual/Latn.HUU/Mono_8/pdf_to_json_test_Latn.HUU_Mono_8.json 2>&1
Latn.HUU_Sans_12:
	-$(PYTHON) data/multilingual/Latn.HUU/Sans_12/pdf_to_json_test_Latn.HUU_Sans_12.py > data/multilingual/Latn.HUU/Sans_12/pdf_to_json_test_Latn.HUU_Sans_12.json 2>&1
Latn.HUU_Sans_16:
	-$(PYTHON) data/multilingual/Latn.HUU/Sans_16/pdf_to_json_test_Latn.HUU_Sans_16.py > data/multilingual/Latn.HUU/Sans_16/pdf_to_json_test_Latn.HUU_Sans_16.json 2>&1
Latn.HUU_Sans_8:
	-$(PYTHON) data/multilingual/Latn.HUU/Sans_8/pdf_to_json_test_Latn.HUU_Sans_8.py > data/multilingual/Latn.HUU/Sans_8/pdf_to_json_test_Latn.HUU_Sans_8.json 2>&1
Latn.HUU_Serif_12:
	-$(PYTHON) data/multilingual/Latn.HUU/Serif_12/pdf_to_json_test_Latn.HUU_Serif_12.py > data/multilingual/Latn.HUU/Serif_12/pdf_to_json_test_Latn.HUU_Serif_12.json 2>&1
Latn.HUU_Serif_16:
	-$(PYTHON) data/multilingual/Latn.HUU/Serif_16/pdf_to_json_test_Latn.HUU_Serif_16.py > data/multilingual/Latn.HUU/Serif_16/pdf_to_json_test_Latn.HUU_Serif_16.json 2>&1
Latn.HUU_Serif_8:
	-$(PYTHON) data/multilingual/Latn.HUU/Serif_8/pdf_to_json_test_Latn.HUU_Serif_8.py > data/multilingual/Latn.HUU/Serif_8/pdf_to_json_test_Latn.HUU_Serif_8.json 2>&1
Latn.HUU_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.HUU/Sun-ExtA_12/pdf_to_json_test_Latn.HUU_Sun-ExtA_12.py > data/multilingual/Latn.HUU/Sun-ExtA_12/pdf_to_json_test_Latn.HUU_Sun-ExtA_12.json 2>&1
Latn.HUU_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.HUU/Sun-ExtA_16/pdf_to_json_test_Latn.HUU_Sun-ExtA_16.py > data/multilingual/Latn.HUU/Sun-ExtA_16/pdf_to_json_test_Latn.HUU_Sun-ExtA_16.json 2>&1
Latn.HUU_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.HUU/Sun-ExtA_8/pdf_to_json_test_Latn.HUU_Sun-ExtA_8.py > data/multilingual/Latn.HUU/Sun-ExtA_8/pdf_to_json_test_Latn.HUU_Sun-ExtA_8.json 2>&1


Latn.HUU_all : Latn.HUU_Mono_12 Latn.HUU_Mono_16 Latn.HUU_Mono_8 Latn.HUU_Sans_12 Latn.HUU_Sans_16 Latn.HUU_Sans_8 Latn.HUU_Serif_12 Latn.HUU_Serif_16 Latn.HUU_Serif_8 Latn.HUU_Sun-ExtA_12 Latn.HUU_Sun-ExtA_16 Latn.HUU_Sun-ExtA_8
