PYTHON=python3


Latn.XSM_Mono_12:
	-$(PYTHON) data/multilingual/Latn.XSM/Mono_12/pdf_to_json_test_Latn.XSM_Mono_12.py > data/multilingual/Latn.XSM/Mono_12/pdf_to_json_test_Latn.XSM_Mono_12.json 2>&1
Latn.XSM_Mono_16:
	-$(PYTHON) data/multilingual/Latn.XSM/Mono_16/pdf_to_json_test_Latn.XSM_Mono_16.py > data/multilingual/Latn.XSM/Mono_16/pdf_to_json_test_Latn.XSM_Mono_16.json 2>&1
Latn.XSM_Mono_8:
	-$(PYTHON) data/multilingual/Latn.XSM/Mono_8/pdf_to_json_test_Latn.XSM_Mono_8.py > data/multilingual/Latn.XSM/Mono_8/pdf_to_json_test_Latn.XSM_Mono_8.json 2>&1
Latn.XSM_Sans_12:
	-$(PYTHON) data/multilingual/Latn.XSM/Sans_12/pdf_to_json_test_Latn.XSM_Sans_12.py > data/multilingual/Latn.XSM/Sans_12/pdf_to_json_test_Latn.XSM_Sans_12.json 2>&1
Latn.XSM_Sans_16:
	-$(PYTHON) data/multilingual/Latn.XSM/Sans_16/pdf_to_json_test_Latn.XSM_Sans_16.py > data/multilingual/Latn.XSM/Sans_16/pdf_to_json_test_Latn.XSM_Sans_16.json 2>&1
Latn.XSM_Sans_8:
	-$(PYTHON) data/multilingual/Latn.XSM/Sans_8/pdf_to_json_test_Latn.XSM_Sans_8.py > data/multilingual/Latn.XSM/Sans_8/pdf_to_json_test_Latn.XSM_Sans_8.json 2>&1
Latn.XSM_Serif_12:
	-$(PYTHON) data/multilingual/Latn.XSM/Serif_12/pdf_to_json_test_Latn.XSM_Serif_12.py > data/multilingual/Latn.XSM/Serif_12/pdf_to_json_test_Latn.XSM_Serif_12.json 2>&1
Latn.XSM_Serif_16:
	-$(PYTHON) data/multilingual/Latn.XSM/Serif_16/pdf_to_json_test_Latn.XSM_Serif_16.py > data/multilingual/Latn.XSM/Serif_16/pdf_to_json_test_Latn.XSM_Serif_16.json 2>&1
Latn.XSM_Serif_8:
	-$(PYTHON) data/multilingual/Latn.XSM/Serif_8/pdf_to_json_test_Latn.XSM_Serif_8.py > data/multilingual/Latn.XSM/Serif_8/pdf_to_json_test_Latn.XSM_Serif_8.json 2>&1
Latn.XSM_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.XSM/Sun-ExtA_12/pdf_to_json_test_Latn.XSM_Sun-ExtA_12.py > data/multilingual/Latn.XSM/Sun-ExtA_12/pdf_to_json_test_Latn.XSM_Sun-ExtA_12.json 2>&1
Latn.XSM_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.XSM/Sun-ExtA_16/pdf_to_json_test_Latn.XSM_Sun-ExtA_16.py > data/multilingual/Latn.XSM/Sun-ExtA_16/pdf_to_json_test_Latn.XSM_Sun-ExtA_16.json 2>&1
Latn.XSM_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.XSM/Sun-ExtA_8/pdf_to_json_test_Latn.XSM_Sun-ExtA_8.py > data/multilingual/Latn.XSM/Sun-ExtA_8/pdf_to_json_test_Latn.XSM_Sun-ExtA_8.json 2>&1


Latn.XSM_all : Latn.XSM_Mono_12 Latn.XSM_Mono_16 Latn.XSM_Mono_8 Latn.XSM_Sans_12 Latn.XSM_Sans_16 Latn.XSM_Sans_8 Latn.XSM_Serif_12 Latn.XSM_Serif_16 Latn.XSM_Serif_8 Latn.XSM_Sun-ExtA_12 Latn.XSM_Sun-ExtA_16 Latn.XSM_Sun-ExtA_8
