PYTHON=python3


Latn.VEN_Mono_12:
	-$(PYTHON) data/multilingual/Latn.VEN/Mono_12/pdf_to_json_test_Latn.VEN_Mono_12.py > data/multilingual/Latn.VEN/Mono_12/pdf_to_json_test_Latn.VEN_Mono_12.json 2>&1
Latn.VEN_Mono_16:
	-$(PYTHON) data/multilingual/Latn.VEN/Mono_16/pdf_to_json_test_Latn.VEN_Mono_16.py > data/multilingual/Latn.VEN/Mono_16/pdf_to_json_test_Latn.VEN_Mono_16.json 2>&1
Latn.VEN_Mono_8:
	-$(PYTHON) data/multilingual/Latn.VEN/Mono_8/pdf_to_json_test_Latn.VEN_Mono_8.py > data/multilingual/Latn.VEN/Mono_8/pdf_to_json_test_Latn.VEN_Mono_8.json 2>&1
Latn.VEN_Sans_12:
	-$(PYTHON) data/multilingual/Latn.VEN/Sans_12/pdf_to_json_test_Latn.VEN_Sans_12.py > data/multilingual/Latn.VEN/Sans_12/pdf_to_json_test_Latn.VEN_Sans_12.json 2>&1
Latn.VEN_Sans_16:
	-$(PYTHON) data/multilingual/Latn.VEN/Sans_16/pdf_to_json_test_Latn.VEN_Sans_16.py > data/multilingual/Latn.VEN/Sans_16/pdf_to_json_test_Latn.VEN_Sans_16.json 2>&1
Latn.VEN_Sans_8:
	-$(PYTHON) data/multilingual/Latn.VEN/Sans_8/pdf_to_json_test_Latn.VEN_Sans_8.py > data/multilingual/Latn.VEN/Sans_8/pdf_to_json_test_Latn.VEN_Sans_8.json 2>&1
Latn.VEN_Serif_12:
	-$(PYTHON) data/multilingual/Latn.VEN/Serif_12/pdf_to_json_test_Latn.VEN_Serif_12.py > data/multilingual/Latn.VEN/Serif_12/pdf_to_json_test_Latn.VEN_Serif_12.json 2>&1
Latn.VEN_Serif_16:
	-$(PYTHON) data/multilingual/Latn.VEN/Serif_16/pdf_to_json_test_Latn.VEN_Serif_16.py > data/multilingual/Latn.VEN/Serif_16/pdf_to_json_test_Latn.VEN_Serif_16.json 2>&1
Latn.VEN_Serif_8:
	-$(PYTHON) data/multilingual/Latn.VEN/Serif_8/pdf_to_json_test_Latn.VEN_Serif_8.py > data/multilingual/Latn.VEN/Serif_8/pdf_to_json_test_Latn.VEN_Serif_8.json 2>&1
Latn.VEN_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.VEN/Sun-ExtA_12/pdf_to_json_test_Latn.VEN_Sun-ExtA_12.py > data/multilingual/Latn.VEN/Sun-ExtA_12/pdf_to_json_test_Latn.VEN_Sun-ExtA_12.json 2>&1
Latn.VEN_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.VEN/Sun-ExtA_16/pdf_to_json_test_Latn.VEN_Sun-ExtA_16.py > data/multilingual/Latn.VEN/Sun-ExtA_16/pdf_to_json_test_Latn.VEN_Sun-ExtA_16.json 2>&1
Latn.VEN_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.VEN/Sun-ExtA_8/pdf_to_json_test_Latn.VEN_Sun-ExtA_8.py > data/multilingual/Latn.VEN/Sun-ExtA_8/pdf_to_json_test_Latn.VEN_Sun-ExtA_8.json 2>&1


Latn.VEN_all : Latn.VEN_Mono_12 Latn.VEN_Mono_16 Latn.VEN_Mono_8 Latn.VEN_Sans_12 Latn.VEN_Sans_16 Latn.VEN_Sans_8 Latn.VEN_Serif_12 Latn.VEN_Serif_16 Latn.VEN_Serif_8 Latn.VEN_Sun-ExtA_12 Latn.VEN_Sun-ExtA_16 Latn.VEN_Sun-ExtA_8
