PYTHON=python3


Latn.OTE_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.OTE/Mono_12/pdf_to_json_test_Latn.OTE_Mono_12.py" > "data/multilingual/Latn.OTE/Mono_12/pdf_to_json_test_Latn.OTE_Mono_12.json" 2>&1
Latn.OTE_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.OTE/Mono_16/pdf_to_json_test_Latn.OTE_Mono_16.py" > "data/multilingual/Latn.OTE/Mono_16/pdf_to_json_test_Latn.OTE_Mono_16.json" 2>&1
Latn.OTE_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.OTE/Mono_8/pdf_to_json_test_Latn.OTE_Mono_8.py" > "data/multilingual/Latn.OTE/Mono_8/pdf_to_json_test_Latn.OTE_Mono_8.json" 2>&1
Latn.OTE_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.OTE/Sans_12/pdf_to_json_test_Latn.OTE_Sans_12.py" > "data/multilingual/Latn.OTE/Sans_12/pdf_to_json_test_Latn.OTE_Sans_12.json" 2>&1
Latn.OTE_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.OTE/Sans_16/pdf_to_json_test_Latn.OTE_Sans_16.py" > "data/multilingual/Latn.OTE/Sans_16/pdf_to_json_test_Latn.OTE_Sans_16.json" 2>&1
Latn.OTE_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.OTE/Sans_8/pdf_to_json_test_Latn.OTE_Sans_8.py" > "data/multilingual/Latn.OTE/Sans_8/pdf_to_json_test_Latn.OTE_Sans_8.json" 2>&1
Latn.OTE_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.OTE/Serif_12/pdf_to_json_test_Latn.OTE_Serif_12.py" > "data/multilingual/Latn.OTE/Serif_12/pdf_to_json_test_Latn.OTE_Serif_12.json" 2>&1
Latn.OTE_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.OTE/Serif_16/pdf_to_json_test_Latn.OTE_Serif_16.py" > "data/multilingual/Latn.OTE/Serif_16/pdf_to_json_test_Latn.OTE_Serif_16.json" 2>&1
Latn.OTE_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.OTE/Serif_8/pdf_to_json_test_Latn.OTE_Serif_8.py" > "data/multilingual/Latn.OTE/Serif_8/pdf_to_json_test_Latn.OTE_Serif_8.json" 2>&1
Latn.OTE_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.OTE/Sun-ExtA_12/pdf_to_json_test_Latn.OTE_Sun-ExtA_12.py" > "data/multilingual/Latn.OTE/Sun-ExtA_12/pdf_to_json_test_Latn.OTE_Sun-ExtA_12.json" 2>&1
Latn.OTE_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.OTE/Sun-ExtA_16/pdf_to_json_test_Latn.OTE_Sun-ExtA_16.py" > "data/multilingual/Latn.OTE/Sun-ExtA_16/pdf_to_json_test_Latn.OTE_Sun-ExtA_16.json" 2>&1
Latn.OTE_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.OTE/Sun-ExtA_8/pdf_to_json_test_Latn.OTE_Sun-ExtA_8.py" > "data/multilingual/Latn.OTE/Sun-ExtA_8/pdf_to_json_test_Latn.OTE_Sun-ExtA_8.json" 2>&1


Latn.OTE_all : Latn.OTE_Mono_12 Latn.OTE_Mono_16 Latn.OTE_Mono_8 Latn.OTE_Sans_12 Latn.OTE_Sans_16 Latn.OTE_Sans_8 Latn.OTE_Serif_12 Latn.OTE_Serif_16 Latn.OTE_Serif_8 Latn.OTE_Sun-ExtA_12 Latn.OTE_Sun-ExtA_16 Latn.OTE_Sun-ExtA_8
