PYTHON=python3


Cyrl.AZJ_Mono_12:
	-$(PYTHON) data/multilingual/Cyrl.AZJ/Mono_12/pdf_to_json_test_Cyrl.AZJ_Mono_12.py > data/multilingual/Cyrl.AZJ/Mono_12/pdf_to_json_test_Cyrl.AZJ_Mono_12.json 2>&1
Cyrl.AZJ_Mono_16:
	-$(PYTHON) data/multilingual/Cyrl.AZJ/Mono_16/pdf_to_json_test_Cyrl.AZJ_Mono_16.py > data/multilingual/Cyrl.AZJ/Mono_16/pdf_to_json_test_Cyrl.AZJ_Mono_16.json 2>&1
Cyrl.AZJ_Mono_8:
	-$(PYTHON) data/multilingual/Cyrl.AZJ/Mono_8/pdf_to_json_test_Cyrl.AZJ_Mono_8.py > data/multilingual/Cyrl.AZJ/Mono_8/pdf_to_json_test_Cyrl.AZJ_Mono_8.json 2>&1
Cyrl.AZJ_Sans_12:
	-$(PYTHON) data/multilingual/Cyrl.AZJ/Sans_12/pdf_to_json_test_Cyrl.AZJ_Sans_12.py > data/multilingual/Cyrl.AZJ/Sans_12/pdf_to_json_test_Cyrl.AZJ_Sans_12.json 2>&1
Cyrl.AZJ_Sans_16:
	-$(PYTHON) data/multilingual/Cyrl.AZJ/Sans_16/pdf_to_json_test_Cyrl.AZJ_Sans_16.py > data/multilingual/Cyrl.AZJ/Sans_16/pdf_to_json_test_Cyrl.AZJ_Sans_16.json 2>&1
Cyrl.AZJ_Sans_8:
	-$(PYTHON) data/multilingual/Cyrl.AZJ/Sans_8/pdf_to_json_test_Cyrl.AZJ_Sans_8.py > data/multilingual/Cyrl.AZJ/Sans_8/pdf_to_json_test_Cyrl.AZJ_Sans_8.json 2>&1
Cyrl.AZJ_Serif_12:
	-$(PYTHON) data/multilingual/Cyrl.AZJ/Serif_12/pdf_to_json_test_Cyrl.AZJ_Serif_12.py > data/multilingual/Cyrl.AZJ/Serif_12/pdf_to_json_test_Cyrl.AZJ_Serif_12.json 2>&1
Cyrl.AZJ_Serif_16:
	-$(PYTHON) data/multilingual/Cyrl.AZJ/Serif_16/pdf_to_json_test_Cyrl.AZJ_Serif_16.py > data/multilingual/Cyrl.AZJ/Serif_16/pdf_to_json_test_Cyrl.AZJ_Serif_16.json 2>&1
Cyrl.AZJ_Serif_8:
	-$(PYTHON) data/multilingual/Cyrl.AZJ/Serif_8/pdf_to_json_test_Cyrl.AZJ_Serif_8.py > data/multilingual/Cyrl.AZJ/Serif_8/pdf_to_json_test_Cyrl.AZJ_Serif_8.json 2>&1
Cyrl.AZJ_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Cyrl.AZJ/Sun-ExtA_12/pdf_to_json_test_Cyrl.AZJ_Sun-ExtA_12.py > data/multilingual/Cyrl.AZJ/Sun-ExtA_12/pdf_to_json_test_Cyrl.AZJ_Sun-ExtA_12.json 2>&1
Cyrl.AZJ_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Cyrl.AZJ/Sun-ExtA_16/pdf_to_json_test_Cyrl.AZJ_Sun-ExtA_16.py > data/multilingual/Cyrl.AZJ/Sun-ExtA_16/pdf_to_json_test_Cyrl.AZJ_Sun-ExtA_16.json 2>&1
Cyrl.AZJ_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Cyrl.AZJ/Sun-ExtA_8/pdf_to_json_test_Cyrl.AZJ_Sun-ExtA_8.py > data/multilingual/Cyrl.AZJ/Sun-ExtA_8/pdf_to_json_test_Cyrl.AZJ_Sun-ExtA_8.json 2>&1


Cyrl.AZJ_all : Cyrl.AZJ_Mono_12 Cyrl.AZJ_Mono_16 Cyrl.AZJ_Mono_8 Cyrl.AZJ_Sans_12 Cyrl.AZJ_Sans_16 Cyrl.AZJ_Sans_8 Cyrl.AZJ_Serif_12 Cyrl.AZJ_Serif_16 Cyrl.AZJ_Serif_8 Cyrl.AZJ_Sun-ExtA_12 Cyrl.AZJ_Sun-ExtA_16 Cyrl.AZJ_Sun-ExtA_8
