PYTHON=python3


Gujr.GUJ_Mono_12:
	-$(PYTHON) data/multilingual/Gujr.GUJ/Mono_12/pdf_to_json_test_Gujr.GUJ_Mono_12.py > data/multilingual/Gujr.GUJ/Mono_12/pdf_to_json_test_Gujr.GUJ_Mono_12.json 2>&1
Gujr.GUJ_Mono_16:
	-$(PYTHON) data/multilingual/Gujr.GUJ/Mono_16/pdf_to_json_test_Gujr.GUJ_Mono_16.py > data/multilingual/Gujr.GUJ/Mono_16/pdf_to_json_test_Gujr.GUJ_Mono_16.json 2>&1
Gujr.GUJ_Mono_8:
	-$(PYTHON) data/multilingual/Gujr.GUJ/Mono_8/pdf_to_json_test_Gujr.GUJ_Mono_8.py > data/multilingual/Gujr.GUJ/Mono_8/pdf_to_json_test_Gujr.GUJ_Mono_8.json 2>&1
Gujr.GUJ_Sans_12:
	-$(PYTHON) data/multilingual/Gujr.GUJ/Sans_12/pdf_to_json_test_Gujr.GUJ_Sans_12.py > data/multilingual/Gujr.GUJ/Sans_12/pdf_to_json_test_Gujr.GUJ_Sans_12.json 2>&1
Gujr.GUJ_Sans_16:
	-$(PYTHON) data/multilingual/Gujr.GUJ/Sans_16/pdf_to_json_test_Gujr.GUJ_Sans_16.py > data/multilingual/Gujr.GUJ/Sans_16/pdf_to_json_test_Gujr.GUJ_Sans_16.json 2>&1
Gujr.GUJ_Sans_8:
	-$(PYTHON) data/multilingual/Gujr.GUJ/Sans_8/pdf_to_json_test_Gujr.GUJ_Sans_8.py > data/multilingual/Gujr.GUJ/Sans_8/pdf_to_json_test_Gujr.GUJ_Sans_8.json 2>&1
Gujr.GUJ_Serif_12:
	-$(PYTHON) data/multilingual/Gujr.GUJ/Serif_12/pdf_to_json_test_Gujr.GUJ_Serif_12.py > data/multilingual/Gujr.GUJ/Serif_12/pdf_to_json_test_Gujr.GUJ_Serif_12.json 2>&1
Gujr.GUJ_Serif_16:
	-$(PYTHON) data/multilingual/Gujr.GUJ/Serif_16/pdf_to_json_test_Gujr.GUJ_Serif_16.py > data/multilingual/Gujr.GUJ/Serif_16/pdf_to_json_test_Gujr.GUJ_Serif_16.json 2>&1
Gujr.GUJ_Serif_8:
	-$(PYTHON) data/multilingual/Gujr.GUJ/Serif_8/pdf_to_json_test_Gujr.GUJ_Serif_8.py > data/multilingual/Gujr.GUJ/Serif_8/pdf_to_json_test_Gujr.GUJ_Serif_8.json 2>&1
Gujr.GUJ_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Gujr.GUJ/Sun-ExtA_12/pdf_to_json_test_Gujr.GUJ_Sun-ExtA_12.py > data/multilingual/Gujr.GUJ/Sun-ExtA_12/pdf_to_json_test_Gujr.GUJ_Sun-ExtA_12.json 2>&1
Gujr.GUJ_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Gujr.GUJ/Sun-ExtA_16/pdf_to_json_test_Gujr.GUJ_Sun-ExtA_16.py > data/multilingual/Gujr.GUJ/Sun-ExtA_16/pdf_to_json_test_Gujr.GUJ_Sun-ExtA_16.json 2>&1
Gujr.GUJ_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Gujr.GUJ/Sun-ExtA_8/pdf_to_json_test_Gujr.GUJ_Sun-ExtA_8.py > data/multilingual/Gujr.GUJ/Sun-ExtA_8/pdf_to_json_test_Gujr.GUJ_Sun-ExtA_8.json 2>&1


Gujr.GUJ_all : Gujr.GUJ_Mono_12 Gujr.GUJ_Mono_16 Gujr.GUJ_Mono_8 Gujr.GUJ_Sans_12 Gujr.GUJ_Sans_16 Gujr.GUJ_Sans_8 Gujr.GUJ_Serif_12 Gujr.GUJ_Serif_16 Gujr.GUJ_Serif_8 Gujr.GUJ_Sun-ExtA_12 Gujr.GUJ_Sun-ExtA_16 Gujr.GUJ_Sun-ExtA_8
