PYTHON=python3


Tibt.BOD_Mono_12:
	-$(PYTHON) "data/multilingual/Tibt.BOD/Mono_12/pdf_to_json_test_Tibt.BOD_Mono_12.py" > "data/multilingual/Tibt.BOD/Mono_12/pdf_to_json_test_Tibt.BOD_Mono_12.json" 2>&1
Tibt.BOD_Mono_16:
	-$(PYTHON) "data/multilingual/Tibt.BOD/Mono_16/pdf_to_json_test_Tibt.BOD_Mono_16.py" > "data/multilingual/Tibt.BOD/Mono_16/pdf_to_json_test_Tibt.BOD_Mono_16.json" 2>&1
Tibt.BOD_Mono_8:
	-$(PYTHON) "data/multilingual/Tibt.BOD/Mono_8/pdf_to_json_test_Tibt.BOD_Mono_8.py" > "data/multilingual/Tibt.BOD/Mono_8/pdf_to_json_test_Tibt.BOD_Mono_8.json" 2>&1
Tibt.BOD_Sans_12:
	-$(PYTHON) "data/multilingual/Tibt.BOD/Sans_12/pdf_to_json_test_Tibt.BOD_Sans_12.py" > "data/multilingual/Tibt.BOD/Sans_12/pdf_to_json_test_Tibt.BOD_Sans_12.json" 2>&1
Tibt.BOD_Sans_16:
	-$(PYTHON) "data/multilingual/Tibt.BOD/Sans_16/pdf_to_json_test_Tibt.BOD_Sans_16.py" > "data/multilingual/Tibt.BOD/Sans_16/pdf_to_json_test_Tibt.BOD_Sans_16.json" 2>&1
Tibt.BOD_Sans_8:
	-$(PYTHON) "data/multilingual/Tibt.BOD/Sans_8/pdf_to_json_test_Tibt.BOD_Sans_8.py" > "data/multilingual/Tibt.BOD/Sans_8/pdf_to_json_test_Tibt.BOD_Sans_8.json" 2>&1
Tibt.BOD_Serif_12:
	-$(PYTHON) "data/multilingual/Tibt.BOD/Serif_12/pdf_to_json_test_Tibt.BOD_Serif_12.py" > "data/multilingual/Tibt.BOD/Serif_12/pdf_to_json_test_Tibt.BOD_Serif_12.json" 2>&1
Tibt.BOD_Serif_16:
	-$(PYTHON) "data/multilingual/Tibt.BOD/Serif_16/pdf_to_json_test_Tibt.BOD_Serif_16.py" > "data/multilingual/Tibt.BOD/Serif_16/pdf_to_json_test_Tibt.BOD_Serif_16.json" 2>&1
Tibt.BOD_Serif_8:
	-$(PYTHON) "data/multilingual/Tibt.BOD/Serif_8/pdf_to_json_test_Tibt.BOD_Serif_8.py" > "data/multilingual/Tibt.BOD/Serif_8/pdf_to_json_test_Tibt.BOD_Serif_8.json" 2>&1
Tibt.BOD_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Tibt.BOD/Sun-ExtA_12/pdf_to_json_test_Tibt.BOD_Sun-ExtA_12.py" > "data/multilingual/Tibt.BOD/Sun-ExtA_12/pdf_to_json_test_Tibt.BOD_Sun-ExtA_12.json" 2>&1
Tibt.BOD_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Tibt.BOD/Sun-ExtA_16/pdf_to_json_test_Tibt.BOD_Sun-ExtA_16.py" > "data/multilingual/Tibt.BOD/Sun-ExtA_16/pdf_to_json_test_Tibt.BOD_Sun-ExtA_16.json" 2>&1
Tibt.BOD_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Tibt.BOD/Sun-ExtA_8/pdf_to_json_test_Tibt.BOD_Sun-ExtA_8.py" > "data/multilingual/Tibt.BOD/Sun-ExtA_8/pdf_to_json_test_Tibt.BOD_Sun-ExtA_8.json" 2>&1


Tibt.BOD_all : Tibt.BOD_Mono_12 Tibt.BOD_Mono_16 Tibt.BOD_Mono_8 Tibt.BOD_Sans_12 Tibt.BOD_Sans_16 Tibt.BOD_Sans_8 Tibt.BOD_Serif_12 Tibt.BOD_Serif_16 Tibt.BOD_Serif_8 Tibt.BOD_Sun-ExtA_12 Tibt.BOD_Sun-ExtA_16 Tibt.BOD_Sun-ExtA_8
