PYTHON=python3


Latn.TCA_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.TCA/Mono_12/pdf_to_json_test_Latn.TCA_Mono_12.py" > "data/multilingual/Latn.TCA/Mono_12/pdf_to_json_test_Latn.TCA_Mono_12.json" 2>&1
Latn.TCA_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.TCA/Mono_16/pdf_to_json_test_Latn.TCA_Mono_16.py" > "data/multilingual/Latn.TCA/Mono_16/pdf_to_json_test_Latn.TCA_Mono_16.json" 2>&1
Latn.TCA_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.TCA/Mono_8/pdf_to_json_test_Latn.TCA_Mono_8.py" > "data/multilingual/Latn.TCA/Mono_8/pdf_to_json_test_Latn.TCA_Mono_8.json" 2>&1
Latn.TCA_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.TCA/Sans_12/pdf_to_json_test_Latn.TCA_Sans_12.py" > "data/multilingual/Latn.TCA/Sans_12/pdf_to_json_test_Latn.TCA_Sans_12.json" 2>&1
Latn.TCA_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.TCA/Sans_16/pdf_to_json_test_Latn.TCA_Sans_16.py" > "data/multilingual/Latn.TCA/Sans_16/pdf_to_json_test_Latn.TCA_Sans_16.json" 2>&1
Latn.TCA_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.TCA/Sans_8/pdf_to_json_test_Latn.TCA_Sans_8.py" > "data/multilingual/Latn.TCA/Sans_8/pdf_to_json_test_Latn.TCA_Sans_8.json" 2>&1
Latn.TCA_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.TCA/Serif_12/pdf_to_json_test_Latn.TCA_Serif_12.py" > "data/multilingual/Latn.TCA/Serif_12/pdf_to_json_test_Latn.TCA_Serif_12.json" 2>&1
Latn.TCA_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.TCA/Serif_16/pdf_to_json_test_Latn.TCA_Serif_16.py" > "data/multilingual/Latn.TCA/Serif_16/pdf_to_json_test_Latn.TCA_Serif_16.json" 2>&1
Latn.TCA_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.TCA/Serif_8/pdf_to_json_test_Latn.TCA_Serif_8.py" > "data/multilingual/Latn.TCA/Serif_8/pdf_to_json_test_Latn.TCA_Serif_8.json" 2>&1
Latn.TCA_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.TCA/Sun-ExtA_12/pdf_to_json_test_Latn.TCA_Sun-ExtA_12.py" > "data/multilingual/Latn.TCA/Sun-ExtA_12/pdf_to_json_test_Latn.TCA_Sun-ExtA_12.json" 2>&1
Latn.TCA_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.TCA/Sun-ExtA_16/pdf_to_json_test_Latn.TCA_Sun-ExtA_16.py" > "data/multilingual/Latn.TCA/Sun-ExtA_16/pdf_to_json_test_Latn.TCA_Sun-ExtA_16.json" 2>&1
Latn.TCA_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.TCA/Sun-ExtA_8/pdf_to_json_test_Latn.TCA_Sun-ExtA_8.py" > "data/multilingual/Latn.TCA/Sun-ExtA_8/pdf_to_json_test_Latn.TCA_Sun-ExtA_8.json" 2>&1


Latn.TCA_all : Latn.TCA_Mono_12 Latn.TCA_Mono_16 Latn.TCA_Mono_8 Latn.TCA_Sans_12 Latn.TCA_Sans_16 Latn.TCA_Sans_8 Latn.TCA_Serif_12 Latn.TCA_Serif_16 Latn.TCA_Serif_8 Latn.TCA_Sun-ExtA_12 Latn.TCA_Sun-ExtA_16 Latn.TCA_Sun-ExtA_8
