PYTHON=python3


Latn.NDO_Mono_12:
	-$(PYTHON) data/multilingual/Latn.NDO/Mono_12/pdf_to_json_test_Latn.NDO_Mono_12.py > data/multilingual/Latn.NDO/Mono_12/pdf_to_json_test_Latn.NDO_Mono_12.json 2>&1
Latn.NDO_Mono_16:
	-$(PYTHON) data/multilingual/Latn.NDO/Mono_16/pdf_to_json_test_Latn.NDO_Mono_16.py > data/multilingual/Latn.NDO/Mono_16/pdf_to_json_test_Latn.NDO_Mono_16.json 2>&1
Latn.NDO_Mono_8:
	-$(PYTHON) data/multilingual/Latn.NDO/Mono_8/pdf_to_json_test_Latn.NDO_Mono_8.py > data/multilingual/Latn.NDO/Mono_8/pdf_to_json_test_Latn.NDO_Mono_8.json 2>&1
Latn.NDO_Sans_12:
	-$(PYTHON) data/multilingual/Latn.NDO/Sans_12/pdf_to_json_test_Latn.NDO_Sans_12.py > data/multilingual/Latn.NDO/Sans_12/pdf_to_json_test_Latn.NDO_Sans_12.json 2>&1
Latn.NDO_Sans_16:
	-$(PYTHON) data/multilingual/Latn.NDO/Sans_16/pdf_to_json_test_Latn.NDO_Sans_16.py > data/multilingual/Latn.NDO/Sans_16/pdf_to_json_test_Latn.NDO_Sans_16.json 2>&1
Latn.NDO_Sans_8:
	-$(PYTHON) data/multilingual/Latn.NDO/Sans_8/pdf_to_json_test_Latn.NDO_Sans_8.py > data/multilingual/Latn.NDO/Sans_8/pdf_to_json_test_Latn.NDO_Sans_8.json 2>&1
Latn.NDO_Serif_12:
	-$(PYTHON) data/multilingual/Latn.NDO/Serif_12/pdf_to_json_test_Latn.NDO_Serif_12.py > data/multilingual/Latn.NDO/Serif_12/pdf_to_json_test_Latn.NDO_Serif_12.json 2>&1
Latn.NDO_Serif_16:
	-$(PYTHON) data/multilingual/Latn.NDO/Serif_16/pdf_to_json_test_Latn.NDO_Serif_16.py > data/multilingual/Latn.NDO/Serif_16/pdf_to_json_test_Latn.NDO_Serif_16.json 2>&1
Latn.NDO_Serif_8:
	-$(PYTHON) data/multilingual/Latn.NDO/Serif_8/pdf_to_json_test_Latn.NDO_Serif_8.py > data/multilingual/Latn.NDO/Serif_8/pdf_to_json_test_Latn.NDO_Serif_8.json 2>&1
Latn.NDO_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.NDO/Sun-ExtA_12/pdf_to_json_test_Latn.NDO_Sun-ExtA_12.py > data/multilingual/Latn.NDO/Sun-ExtA_12/pdf_to_json_test_Latn.NDO_Sun-ExtA_12.json 2>&1
Latn.NDO_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.NDO/Sun-ExtA_16/pdf_to_json_test_Latn.NDO_Sun-ExtA_16.py > data/multilingual/Latn.NDO/Sun-ExtA_16/pdf_to_json_test_Latn.NDO_Sun-ExtA_16.json 2>&1
Latn.NDO_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.NDO/Sun-ExtA_8/pdf_to_json_test_Latn.NDO_Sun-ExtA_8.py > data/multilingual/Latn.NDO/Sun-ExtA_8/pdf_to_json_test_Latn.NDO_Sun-ExtA_8.json 2>&1


Latn.NDO_all : Latn.NDO_Mono_12 Latn.NDO_Mono_16 Latn.NDO_Mono_8 Latn.NDO_Sans_12 Latn.NDO_Sans_16 Latn.NDO_Sans_8 Latn.NDO_Serif_12 Latn.NDO_Serif_16 Latn.NDO_Serif_8 Latn.NDO_Sun-ExtA_12 Latn.NDO_Sun-ExtA_16 Latn.NDO_Sun-ExtA_8
