PYTHON=python3


Latn.OKI_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.OKI/Mono_12/pdf_to_json_test_Latn.OKI_Mono_12.py" > "data/multilingual/Latn.OKI/Mono_12/pdf_to_json_test_Latn.OKI_Mono_12.json" 2>&1
Latn.OKI_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.OKI/Mono_16/pdf_to_json_test_Latn.OKI_Mono_16.py" > "data/multilingual/Latn.OKI/Mono_16/pdf_to_json_test_Latn.OKI_Mono_16.json" 2>&1
Latn.OKI_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.OKI/Mono_8/pdf_to_json_test_Latn.OKI_Mono_8.py" > "data/multilingual/Latn.OKI/Mono_8/pdf_to_json_test_Latn.OKI_Mono_8.json" 2>&1
Latn.OKI_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.OKI/Sans_12/pdf_to_json_test_Latn.OKI_Sans_12.py" > "data/multilingual/Latn.OKI/Sans_12/pdf_to_json_test_Latn.OKI_Sans_12.json" 2>&1
Latn.OKI_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.OKI/Sans_16/pdf_to_json_test_Latn.OKI_Sans_16.py" > "data/multilingual/Latn.OKI/Sans_16/pdf_to_json_test_Latn.OKI_Sans_16.json" 2>&1
Latn.OKI_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.OKI/Sans_8/pdf_to_json_test_Latn.OKI_Sans_8.py" > "data/multilingual/Latn.OKI/Sans_8/pdf_to_json_test_Latn.OKI_Sans_8.json" 2>&1
Latn.OKI_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.OKI/Serif_12/pdf_to_json_test_Latn.OKI_Serif_12.py" > "data/multilingual/Latn.OKI/Serif_12/pdf_to_json_test_Latn.OKI_Serif_12.json" 2>&1
Latn.OKI_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.OKI/Serif_16/pdf_to_json_test_Latn.OKI_Serif_16.py" > "data/multilingual/Latn.OKI/Serif_16/pdf_to_json_test_Latn.OKI_Serif_16.json" 2>&1
Latn.OKI_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.OKI/Serif_8/pdf_to_json_test_Latn.OKI_Serif_8.py" > "data/multilingual/Latn.OKI/Serif_8/pdf_to_json_test_Latn.OKI_Serif_8.json" 2>&1
Latn.OKI_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.OKI/Sun-ExtA_12/pdf_to_json_test_Latn.OKI_Sun-ExtA_12.py" > "data/multilingual/Latn.OKI/Sun-ExtA_12/pdf_to_json_test_Latn.OKI_Sun-ExtA_12.json" 2>&1
Latn.OKI_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.OKI/Sun-ExtA_16/pdf_to_json_test_Latn.OKI_Sun-ExtA_16.py" > "data/multilingual/Latn.OKI/Sun-ExtA_16/pdf_to_json_test_Latn.OKI_Sun-ExtA_16.json" 2>&1
Latn.OKI_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.OKI/Sun-ExtA_8/pdf_to_json_test_Latn.OKI_Sun-ExtA_8.py" > "data/multilingual/Latn.OKI/Sun-ExtA_8/pdf_to_json_test_Latn.OKI_Sun-ExtA_8.json" 2>&1


Latn.OKI_all : Latn.OKI_Mono_12 Latn.OKI_Mono_16 Latn.OKI_Mono_8 Latn.OKI_Sans_12 Latn.OKI_Sans_16 Latn.OKI_Sans_8 Latn.OKI_Serif_12 Latn.OKI_Serif_16 Latn.OKI_Serif_8 Latn.OKI_Sun-ExtA_12 Latn.OKI_Sun-ExtA_16 Latn.OKI_Sun-ExtA_8
