PYTHON=python3


Latn.NLD_Mono_12:
	-$(PYTHON) data/multilingual/Latn.NLD/Mono_12/pdf_to_json_test_Latn.NLD_Mono_12.py > data/multilingual/Latn.NLD/Mono_12/pdf_to_json_test_Latn.NLD_Mono_12.json 2>&1
Latn.NLD_Mono_16:
	-$(PYTHON) data/multilingual/Latn.NLD/Mono_16/pdf_to_json_test_Latn.NLD_Mono_16.py > data/multilingual/Latn.NLD/Mono_16/pdf_to_json_test_Latn.NLD_Mono_16.json 2>&1
Latn.NLD_Mono_8:
	-$(PYTHON) data/multilingual/Latn.NLD/Mono_8/pdf_to_json_test_Latn.NLD_Mono_8.py > data/multilingual/Latn.NLD/Mono_8/pdf_to_json_test_Latn.NLD_Mono_8.json 2>&1
Latn.NLD_Sans_12:
	-$(PYTHON) data/multilingual/Latn.NLD/Sans_12/pdf_to_json_test_Latn.NLD_Sans_12.py > data/multilingual/Latn.NLD/Sans_12/pdf_to_json_test_Latn.NLD_Sans_12.json 2>&1
Latn.NLD_Sans_16:
	-$(PYTHON) data/multilingual/Latn.NLD/Sans_16/pdf_to_json_test_Latn.NLD_Sans_16.py > data/multilingual/Latn.NLD/Sans_16/pdf_to_json_test_Latn.NLD_Sans_16.json 2>&1
Latn.NLD_Sans_8:
	-$(PYTHON) data/multilingual/Latn.NLD/Sans_8/pdf_to_json_test_Latn.NLD_Sans_8.py > data/multilingual/Latn.NLD/Sans_8/pdf_to_json_test_Latn.NLD_Sans_8.json 2>&1
Latn.NLD_Serif_12:
	-$(PYTHON) data/multilingual/Latn.NLD/Serif_12/pdf_to_json_test_Latn.NLD_Serif_12.py > data/multilingual/Latn.NLD/Serif_12/pdf_to_json_test_Latn.NLD_Serif_12.json 2>&1
Latn.NLD_Serif_16:
	-$(PYTHON) data/multilingual/Latn.NLD/Serif_16/pdf_to_json_test_Latn.NLD_Serif_16.py > data/multilingual/Latn.NLD/Serif_16/pdf_to_json_test_Latn.NLD_Serif_16.json 2>&1
Latn.NLD_Serif_8:
	-$(PYTHON) data/multilingual/Latn.NLD/Serif_8/pdf_to_json_test_Latn.NLD_Serif_8.py > data/multilingual/Latn.NLD/Serif_8/pdf_to_json_test_Latn.NLD_Serif_8.json 2>&1
Latn.NLD_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.NLD/Sun-ExtA_12/pdf_to_json_test_Latn.NLD_Sun-ExtA_12.py > data/multilingual/Latn.NLD/Sun-ExtA_12/pdf_to_json_test_Latn.NLD_Sun-ExtA_12.json 2>&1
Latn.NLD_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.NLD/Sun-ExtA_16/pdf_to_json_test_Latn.NLD_Sun-ExtA_16.py > data/multilingual/Latn.NLD/Sun-ExtA_16/pdf_to_json_test_Latn.NLD_Sun-ExtA_16.json 2>&1
Latn.NLD_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.NLD/Sun-ExtA_8/pdf_to_json_test_Latn.NLD_Sun-ExtA_8.py > data/multilingual/Latn.NLD/Sun-ExtA_8/pdf_to_json_test_Latn.NLD_Sun-ExtA_8.json 2>&1


Latn.NLD_all : Latn.NLD_Mono_12 Latn.NLD_Mono_16 Latn.NLD_Mono_8 Latn.NLD_Sans_12 Latn.NLD_Sans_16 Latn.NLD_Sans_8 Latn.NLD_Serif_12 Latn.NLD_Serif_16 Latn.NLD_Serif_8 Latn.NLD_Sun-ExtA_12 Latn.NLD_Sun-ExtA_16 Latn.NLD_Sun-ExtA_8
