PYTHON=python3


Latn.YOR_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.YOR/Mono_12/pdf_to_json_test_Latn.YOR_Mono_12.py" > "data/multilingual/Latn.YOR/Mono_12/pdf_to_json_test_Latn.YOR_Mono_12.json" 2>&1
Latn.YOR_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.YOR/Mono_16/pdf_to_json_test_Latn.YOR_Mono_16.py" > "data/multilingual/Latn.YOR/Mono_16/pdf_to_json_test_Latn.YOR_Mono_16.json" 2>&1
Latn.YOR_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.YOR/Mono_8/pdf_to_json_test_Latn.YOR_Mono_8.py" > "data/multilingual/Latn.YOR/Mono_8/pdf_to_json_test_Latn.YOR_Mono_8.json" 2>&1
Latn.YOR_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.YOR/Sans_12/pdf_to_json_test_Latn.YOR_Sans_12.py" > "data/multilingual/Latn.YOR/Sans_12/pdf_to_json_test_Latn.YOR_Sans_12.json" 2>&1
Latn.YOR_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.YOR/Sans_16/pdf_to_json_test_Latn.YOR_Sans_16.py" > "data/multilingual/Latn.YOR/Sans_16/pdf_to_json_test_Latn.YOR_Sans_16.json" 2>&1
Latn.YOR_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.YOR/Sans_8/pdf_to_json_test_Latn.YOR_Sans_8.py" > "data/multilingual/Latn.YOR/Sans_8/pdf_to_json_test_Latn.YOR_Sans_8.json" 2>&1
Latn.YOR_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.YOR/Serif_12/pdf_to_json_test_Latn.YOR_Serif_12.py" > "data/multilingual/Latn.YOR/Serif_12/pdf_to_json_test_Latn.YOR_Serif_12.json" 2>&1
Latn.YOR_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.YOR/Serif_16/pdf_to_json_test_Latn.YOR_Serif_16.py" > "data/multilingual/Latn.YOR/Serif_16/pdf_to_json_test_Latn.YOR_Serif_16.json" 2>&1
Latn.YOR_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.YOR/Serif_8/pdf_to_json_test_Latn.YOR_Serif_8.py" > "data/multilingual/Latn.YOR/Serif_8/pdf_to_json_test_Latn.YOR_Serif_8.json" 2>&1
Latn.YOR_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.YOR/Sun-ExtA_12/pdf_to_json_test_Latn.YOR_Sun-ExtA_12.py" > "data/multilingual/Latn.YOR/Sun-ExtA_12/pdf_to_json_test_Latn.YOR_Sun-ExtA_12.json" 2>&1
Latn.YOR_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.YOR/Sun-ExtA_16/pdf_to_json_test_Latn.YOR_Sun-ExtA_16.py" > "data/multilingual/Latn.YOR/Sun-ExtA_16/pdf_to_json_test_Latn.YOR_Sun-ExtA_16.json" 2>&1
Latn.YOR_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.YOR/Sun-ExtA_8/pdf_to_json_test_Latn.YOR_Sun-ExtA_8.py" > "data/multilingual/Latn.YOR/Sun-ExtA_8/pdf_to_json_test_Latn.YOR_Sun-ExtA_8.json" 2>&1


Latn.YOR_all : Latn.YOR_Mono_12 Latn.YOR_Mono_16 Latn.YOR_Mono_8 Latn.YOR_Sans_12 Latn.YOR_Sans_16 Latn.YOR_Sans_8 Latn.YOR_Serif_12 Latn.YOR_Serif_16 Latn.YOR_Serif_8 Latn.YOR_Sun-ExtA_12 Latn.YOR_Sun-ExtA_16 Latn.YOR_Sun-ExtA_8
