PYTHON=python3


Latn.GKP_Mono_12:
	-$(PYTHON) data/multilingual/Latn.GKP/Mono_12/pdf_to_json_test_Latn.GKP_Mono_12.py > data/multilingual/Latn.GKP/Mono_12/pdf_to_json_test_Latn.GKP_Mono_12.json 2>&1
Latn.GKP_Mono_16:
	-$(PYTHON) data/multilingual/Latn.GKP/Mono_16/pdf_to_json_test_Latn.GKP_Mono_16.py > data/multilingual/Latn.GKP/Mono_16/pdf_to_json_test_Latn.GKP_Mono_16.json 2>&1
Latn.GKP_Mono_8:
	-$(PYTHON) data/multilingual/Latn.GKP/Mono_8/pdf_to_json_test_Latn.GKP_Mono_8.py > data/multilingual/Latn.GKP/Mono_8/pdf_to_json_test_Latn.GKP_Mono_8.json 2>&1
Latn.GKP_Sans_12:
	-$(PYTHON) data/multilingual/Latn.GKP/Sans_12/pdf_to_json_test_Latn.GKP_Sans_12.py > data/multilingual/Latn.GKP/Sans_12/pdf_to_json_test_Latn.GKP_Sans_12.json 2>&1
Latn.GKP_Sans_16:
	-$(PYTHON) data/multilingual/Latn.GKP/Sans_16/pdf_to_json_test_Latn.GKP_Sans_16.py > data/multilingual/Latn.GKP/Sans_16/pdf_to_json_test_Latn.GKP_Sans_16.json 2>&1
Latn.GKP_Sans_8:
	-$(PYTHON) data/multilingual/Latn.GKP/Sans_8/pdf_to_json_test_Latn.GKP_Sans_8.py > data/multilingual/Latn.GKP/Sans_8/pdf_to_json_test_Latn.GKP_Sans_8.json 2>&1
Latn.GKP_Serif_12:
	-$(PYTHON) data/multilingual/Latn.GKP/Serif_12/pdf_to_json_test_Latn.GKP_Serif_12.py > data/multilingual/Latn.GKP/Serif_12/pdf_to_json_test_Latn.GKP_Serif_12.json 2>&1
Latn.GKP_Serif_16:
	-$(PYTHON) data/multilingual/Latn.GKP/Serif_16/pdf_to_json_test_Latn.GKP_Serif_16.py > data/multilingual/Latn.GKP/Serif_16/pdf_to_json_test_Latn.GKP_Serif_16.json 2>&1
Latn.GKP_Serif_8:
	-$(PYTHON) data/multilingual/Latn.GKP/Serif_8/pdf_to_json_test_Latn.GKP_Serif_8.py > data/multilingual/Latn.GKP/Serif_8/pdf_to_json_test_Latn.GKP_Serif_8.json 2>&1
Latn.GKP_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.GKP/Sun-ExtA_12/pdf_to_json_test_Latn.GKP_Sun-ExtA_12.py > data/multilingual/Latn.GKP/Sun-ExtA_12/pdf_to_json_test_Latn.GKP_Sun-ExtA_12.json 2>&1
Latn.GKP_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.GKP/Sun-ExtA_16/pdf_to_json_test_Latn.GKP_Sun-ExtA_16.py > data/multilingual/Latn.GKP/Sun-ExtA_16/pdf_to_json_test_Latn.GKP_Sun-ExtA_16.json 2>&1
Latn.GKP_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.GKP/Sun-ExtA_8/pdf_to_json_test_Latn.GKP_Sun-ExtA_8.py > data/multilingual/Latn.GKP/Sun-ExtA_8/pdf_to_json_test_Latn.GKP_Sun-ExtA_8.json 2>&1


Latn.GKP_all : Latn.GKP_Mono_12 Latn.GKP_Mono_16 Latn.GKP_Mono_8 Latn.GKP_Sans_12 Latn.GKP_Sans_16 Latn.GKP_Sans_8 Latn.GKP_Serif_12 Latn.GKP_Serif_16 Latn.GKP_Serif_8 Latn.GKP_Sun-ExtA_12 Latn.GKP_Sun-ExtA_16 Latn.GKP_Sun-ExtA_8
