PYTHON=python3


Grek.ELL_Mono_12:
	-$(PYTHON) data/multilingual/Grek.ELL/Mono_12/pdf_to_json_test_Grek.ELL_Mono_12.py > data/multilingual/Grek.ELL/Mono_12/pdf_to_json_test_Grek.ELL_Mono_12.json 2>&1
Grek.ELL_Mono_16:
	-$(PYTHON) data/multilingual/Grek.ELL/Mono_16/pdf_to_json_test_Grek.ELL_Mono_16.py > data/multilingual/Grek.ELL/Mono_16/pdf_to_json_test_Grek.ELL_Mono_16.json 2>&1
Grek.ELL_Mono_8:
	-$(PYTHON) data/multilingual/Grek.ELL/Mono_8/pdf_to_json_test_Grek.ELL_Mono_8.py > data/multilingual/Grek.ELL/Mono_8/pdf_to_json_test_Grek.ELL_Mono_8.json 2>&1
Grek.ELL_Sans_12:
	-$(PYTHON) data/multilingual/Grek.ELL/Sans_12/pdf_to_json_test_Grek.ELL_Sans_12.py > data/multilingual/Grek.ELL/Sans_12/pdf_to_json_test_Grek.ELL_Sans_12.json 2>&1
Grek.ELL_Sans_16:
	-$(PYTHON) data/multilingual/Grek.ELL/Sans_16/pdf_to_json_test_Grek.ELL_Sans_16.py > data/multilingual/Grek.ELL/Sans_16/pdf_to_json_test_Grek.ELL_Sans_16.json 2>&1
Grek.ELL_Sans_8:
	-$(PYTHON) data/multilingual/Grek.ELL/Sans_8/pdf_to_json_test_Grek.ELL_Sans_8.py > data/multilingual/Grek.ELL/Sans_8/pdf_to_json_test_Grek.ELL_Sans_8.json 2>&1
Grek.ELL_Serif_12:
	-$(PYTHON) data/multilingual/Grek.ELL/Serif_12/pdf_to_json_test_Grek.ELL_Serif_12.py > data/multilingual/Grek.ELL/Serif_12/pdf_to_json_test_Grek.ELL_Serif_12.json 2>&1
Grek.ELL_Serif_16:
	-$(PYTHON) data/multilingual/Grek.ELL/Serif_16/pdf_to_json_test_Grek.ELL_Serif_16.py > data/multilingual/Grek.ELL/Serif_16/pdf_to_json_test_Grek.ELL_Serif_16.json 2>&1
Grek.ELL_Serif_8:
	-$(PYTHON) data/multilingual/Grek.ELL/Serif_8/pdf_to_json_test_Grek.ELL_Serif_8.py > data/multilingual/Grek.ELL/Serif_8/pdf_to_json_test_Grek.ELL_Serif_8.json 2>&1
Grek.ELL_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Grek.ELL/Sun-ExtA_12/pdf_to_json_test_Grek.ELL_Sun-ExtA_12.py > data/multilingual/Grek.ELL/Sun-ExtA_12/pdf_to_json_test_Grek.ELL_Sun-ExtA_12.json 2>&1
Grek.ELL_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Grek.ELL/Sun-ExtA_16/pdf_to_json_test_Grek.ELL_Sun-ExtA_16.py > data/multilingual/Grek.ELL/Sun-ExtA_16/pdf_to_json_test_Grek.ELL_Sun-ExtA_16.json 2>&1
Grek.ELL_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Grek.ELL/Sun-ExtA_8/pdf_to_json_test_Grek.ELL_Sun-ExtA_8.py > data/multilingual/Grek.ELL/Sun-ExtA_8/pdf_to_json_test_Grek.ELL_Sun-ExtA_8.json 2>&1


Grek.ELL_all : Grek.ELL_Mono_12 Grek.ELL_Mono_16 Grek.ELL_Mono_8 Grek.ELL_Sans_12 Grek.ELL_Sans_16 Grek.ELL_Sans_8 Grek.ELL_Serif_12 Grek.ELL_Serif_16 Grek.ELL_Serif_8 Grek.ELL_Sun-ExtA_12 Grek.ELL_Sun-ExtA_16 Grek.ELL_Sun-ExtA_8
