PYTHON=python3


Latn.DIP_Mono_12:
	-$(PYTHON) data/multilingual/Latn.DIP/Mono_12/pdf_to_json_test_Latn.DIP_Mono_12.py > data/multilingual/Latn.DIP/Mono_12/pdf_to_json_test_Latn.DIP_Mono_12.json 2>&1
Latn.DIP_Mono_16:
	-$(PYTHON) data/multilingual/Latn.DIP/Mono_16/pdf_to_json_test_Latn.DIP_Mono_16.py > data/multilingual/Latn.DIP/Mono_16/pdf_to_json_test_Latn.DIP_Mono_16.json 2>&1
Latn.DIP_Mono_8:
	-$(PYTHON) data/multilingual/Latn.DIP/Mono_8/pdf_to_json_test_Latn.DIP_Mono_8.py > data/multilingual/Latn.DIP/Mono_8/pdf_to_json_test_Latn.DIP_Mono_8.json 2>&1
Latn.DIP_Sans_12:
	-$(PYTHON) data/multilingual/Latn.DIP/Sans_12/pdf_to_json_test_Latn.DIP_Sans_12.py > data/multilingual/Latn.DIP/Sans_12/pdf_to_json_test_Latn.DIP_Sans_12.json 2>&1
Latn.DIP_Sans_16:
	-$(PYTHON) data/multilingual/Latn.DIP/Sans_16/pdf_to_json_test_Latn.DIP_Sans_16.py > data/multilingual/Latn.DIP/Sans_16/pdf_to_json_test_Latn.DIP_Sans_16.json 2>&1
Latn.DIP_Sans_8:
	-$(PYTHON) data/multilingual/Latn.DIP/Sans_8/pdf_to_json_test_Latn.DIP_Sans_8.py > data/multilingual/Latn.DIP/Sans_8/pdf_to_json_test_Latn.DIP_Sans_8.json 2>&1
Latn.DIP_Serif_12:
	-$(PYTHON) data/multilingual/Latn.DIP/Serif_12/pdf_to_json_test_Latn.DIP_Serif_12.py > data/multilingual/Latn.DIP/Serif_12/pdf_to_json_test_Latn.DIP_Serif_12.json 2>&1
Latn.DIP_Serif_16:
	-$(PYTHON) data/multilingual/Latn.DIP/Serif_16/pdf_to_json_test_Latn.DIP_Serif_16.py > data/multilingual/Latn.DIP/Serif_16/pdf_to_json_test_Latn.DIP_Serif_16.json 2>&1
Latn.DIP_Serif_8:
	-$(PYTHON) data/multilingual/Latn.DIP/Serif_8/pdf_to_json_test_Latn.DIP_Serif_8.py > data/multilingual/Latn.DIP/Serif_8/pdf_to_json_test_Latn.DIP_Serif_8.json 2>&1
Latn.DIP_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.DIP/Sun-ExtA_12/pdf_to_json_test_Latn.DIP_Sun-ExtA_12.py > data/multilingual/Latn.DIP/Sun-ExtA_12/pdf_to_json_test_Latn.DIP_Sun-ExtA_12.json 2>&1
Latn.DIP_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.DIP/Sun-ExtA_16/pdf_to_json_test_Latn.DIP_Sun-ExtA_16.py > data/multilingual/Latn.DIP/Sun-ExtA_16/pdf_to_json_test_Latn.DIP_Sun-ExtA_16.json 2>&1
Latn.DIP_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.DIP/Sun-ExtA_8/pdf_to_json_test_Latn.DIP_Sun-ExtA_8.py > data/multilingual/Latn.DIP/Sun-ExtA_8/pdf_to_json_test_Latn.DIP_Sun-ExtA_8.json 2>&1


Latn.DIP_all : Latn.DIP_Mono_12 Latn.DIP_Mono_16 Latn.DIP_Mono_8 Latn.DIP_Sans_12 Latn.DIP_Sans_16 Latn.DIP_Sans_8 Latn.DIP_Serif_12 Latn.DIP_Serif_16 Latn.DIP_Serif_8 Latn.DIP_Sun-ExtA_12 Latn.DIP_Sun-ExtA_16 Latn.DIP_Sun-ExtA_8
