PYTHON=python3


Latn.CRI_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.CRI/Mono_12/pdf_to_json_test_Latn.CRI_Mono_12.py" > "data/multilingual/Latn.CRI/Mono_12/pdf_to_json_test_Latn.CRI_Mono_12.json" 2>&1
Latn.CRI_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.CRI/Mono_16/pdf_to_json_test_Latn.CRI_Mono_16.py" > "data/multilingual/Latn.CRI/Mono_16/pdf_to_json_test_Latn.CRI_Mono_16.json" 2>&1
Latn.CRI_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.CRI/Mono_8/pdf_to_json_test_Latn.CRI_Mono_8.py" > "data/multilingual/Latn.CRI/Mono_8/pdf_to_json_test_Latn.CRI_Mono_8.json" 2>&1
Latn.CRI_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.CRI/Sans_12/pdf_to_json_test_Latn.CRI_Sans_12.py" > "data/multilingual/Latn.CRI/Sans_12/pdf_to_json_test_Latn.CRI_Sans_12.json" 2>&1
Latn.CRI_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.CRI/Sans_16/pdf_to_json_test_Latn.CRI_Sans_16.py" > "data/multilingual/Latn.CRI/Sans_16/pdf_to_json_test_Latn.CRI_Sans_16.json" 2>&1
Latn.CRI_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.CRI/Sans_8/pdf_to_json_test_Latn.CRI_Sans_8.py" > "data/multilingual/Latn.CRI/Sans_8/pdf_to_json_test_Latn.CRI_Sans_8.json" 2>&1
Latn.CRI_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.CRI/Serif_12/pdf_to_json_test_Latn.CRI_Serif_12.py" > "data/multilingual/Latn.CRI/Serif_12/pdf_to_json_test_Latn.CRI_Serif_12.json" 2>&1
Latn.CRI_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.CRI/Serif_16/pdf_to_json_test_Latn.CRI_Serif_16.py" > "data/multilingual/Latn.CRI/Serif_16/pdf_to_json_test_Latn.CRI_Serif_16.json" 2>&1
Latn.CRI_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.CRI/Serif_8/pdf_to_json_test_Latn.CRI_Serif_8.py" > "data/multilingual/Latn.CRI/Serif_8/pdf_to_json_test_Latn.CRI_Serif_8.json" 2>&1
Latn.CRI_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.CRI/Sun-ExtA_12/pdf_to_json_test_Latn.CRI_Sun-ExtA_12.py" > "data/multilingual/Latn.CRI/Sun-ExtA_12/pdf_to_json_test_Latn.CRI_Sun-ExtA_12.json" 2>&1
Latn.CRI_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.CRI/Sun-ExtA_16/pdf_to_json_test_Latn.CRI_Sun-ExtA_16.py" > "data/multilingual/Latn.CRI/Sun-ExtA_16/pdf_to_json_test_Latn.CRI_Sun-ExtA_16.json" 2>&1
Latn.CRI_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.CRI/Sun-ExtA_8/pdf_to_json_test_Latn.CRI_Sun-ExtA_8.py" > "data/multilingual/Latn.CRI/Sun-ExtA_8/pdf_to_json_test_Latn.CRI_Sun-ExtA_8.json" 2>&1


Latn.CRI_all : Latn.CRI_Mono_12 Latn.CRI_Mono_16 Latn.CRI_Mono_8 Latn.CRI_Sans_12 Latn.CRI_Sans_16 Latn.CRI_Sans_8 Latn.CRI_Serif_12 Latn.CRI_Serif_16 Latn.CRI_Serif_8 Latn.CRI_Sun-ExtA_12 Latn.CRI_Sun-ExtA_16 Latn.CRI_Sun-ExtA_8
