PYTHON=python3


Latn.MZI_Mono_12:
	-$(PYTHON) data/multilingual/Latn.MZI/Mono_12/pdf_to_json_test_Latn.MZI_Mono_12.py > data/multilingual/Latn.MZI/Mono_12/pdf_to_json_test_Latn.MZI_Mono_12.json 2>&1
Latn.MZI_Mono_16:
	-$(PYTHON) data/multilingual/Latn.MZI/Mono_16/pdf_to_json_test_Latn.MZI_Mono_16.py > data/multilingual/Latn.MZI/Mono_16/pdf_to_json_test_Latn.MZI_Mono_16.json 2>&1
Latn.MZI_Mono_8:
	-$(PYTHON) data/multilingual/Latn.MZI/Mono_8/pdf_to_json_test_Latn.MZI_Mono_8.py > data/multilingual/Latn.MZI/Mono_8/pdf_to_json_test_Latn.MZI_Mono_8.json 2>&1
Latn.MZI_Sans_12:
	-$(PYTHON) data/multilingual/Latn.MZI/Sans_12/pdf_to_json_test_Latn.MZI_Sans_12.py > data/multilingual/Latn.MZI/Sans_12/pdf_to_json_test_Latn.MZI_Sans_12.json 2>&1
Latn.MZI_Sans_16:
	-$(PYTHON) data/multilingual/Latn.MZI/Sans_16/pdf_to_json_test_Latn.MZI_Sans_16.py > data/multilingual/Latn.MZI/Sans_16/pdf_to_json_test_Latn.MZI_Sans_16.json 2>&1
Latn.MZI_Sans_8:
	-$(PYTHON) data/multilingual/Latn.MZI/Sans_8/pdf_to_json_test_Latn.MZI_Sans_8.py > data/multilingual/Latn.MZI/Sans_8/pdf_to_json_test_Latn.MZI_Sans_8.json 2>&1
Latn.MZI_Serif_12:
	-$(PYTHON) data/multilingual/Latn.MZI/Serif_12/pdf_to_json_test_Latn.MZI_Serif_12.py > data/multilingual/Latn.MZI/Serif_12/pdf_to_json_test_Latn.MZI_Serif_12.json 2>&1
Latn.MZI_Serif_16:
	-$(PYTHON) data/multilingual/Latn.MZI/Serif_16/pdf_to_json_test_Latn.MZI_Serif_16.py > data/multilingual/Latn.MZI/Serif_16/pdf_to_json_test_Latn.MZI_Serif_16.json 2>&1
Latn.MZI_Serif_8:
	-$(PYTHON) data/multilingual/Latn.MZI/Serif_8/pdf_to_json_test_Latn.MZI_Serif_8.py > data/multilingual/Latn.MZI/Serif_8/pdf_to_json_test_Latn.MZI_Serif_8.json 2>&1
Latn.MZI_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.MZI/Sun-ExtA_12/pdf_to_json_test_Latn.MZI_Sun-ExtA_12.py > data/multilingual/Latn.MZI/Sun-ExtA_12/pdf_to_json_test_Latn.MZI_Sun-ExtA_12.json 2>&1
Latn.MZI_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.MZI/Sun-ExtA_16/pdf_to_json_test_Latn.MZI_Sun-ExtA_16.py > data/multilingual/Latn.MZI/Sun-ExtA_16/pdf_to_json_test_Latn.MZI_Sun-ExtA_16.json 2>&1
Latn.MZI_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.MZI/Sun-ExtA_8/pdf_to_json_test_Latn.MZI_Sun-ExtA_8.py > data/multilingual/Latn.MZI/Sun-ExtA_8/pdf_to_json_test_Latn.MZI_Sun-ExtA_8.json 2>&1


Latn.MZI_all : Latn.MZI_Mono_12 Latn.MZI_Mono_16 Latn.MZI_Mono_8 Latn.MZI_Sans_12 Latn.MZI_Sans_16 Latn.MZI_Sans_8 Latn.MZI_Serif_12 Latn.MZI_Serif_16 Latn.MZI_Serif_8 Latn.MZI_Sun-ExtA_12 Latn.MZI_Sun-ExtA_16 Latn.MZI_Sun-ExtA_8
