PYTHON=python3


Latn.EUS_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.EUS/Mono_12/pdf_to_json_test_Latn.EUS_Mono_12.py" > "data/multilingual/Latn.EUS/Mono_12/pdf_to_json_test_Latn.EUS_Mono_12.json" 2>&1
Latn.EUS_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.EUS/Mono_16/pdf_to_json_test_Latn.EUS_Mono_16.py" > "data/multilingual/Latn.EUS/Mono_16/pdf_to_json_test_Latn.EUS_Mono_16.json" 2>&1
Latn.EUS_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.EUS/Mono_8/pdf_to_json_test_Latn.EUS_Mono_8.py" > "data/multilingual/Latn.EUS/Mono_8/pdf_to_json_test_Latn.EUS_Mono_8.json" 2>&1
Latn.EUS_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.EUS/Sans_12/pdf_to_json_test_Latn.EUS_Sans_12.py" > "data/multilingual/Latn.EUS/Sans_12/pdf_to_json_test_Latn.EUS_Sans_12.json" 2>&1
Latn.EUS_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.EUS/Sans_16/pdf_to_json_test_Latn.EUS_Sans_16.py" > "data/multilingual/Latn.EUS/Sans_16/pdf_to_json_test_Latn.EUS_Sans_16.json" 2>&1
Latn.EUS_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.EUS/Sans_8/pdf_to_json_test_Latn.EUS_Sans_8.py" > "data/multilingual/Latn.EUS/Sans_8/pdf_to_json_test_Latn.EUS_Sans_8.json" 2>&1
Latn.EUS_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.EUS/Serif_12/pdf_to_json_test_Latn.EUS_Serif_12.py" > "data/multilingual/Latn.EUS/Serif_12/pdf_to_json_test_Latn.EUS_Serif_12.json" 2>&1
Latn.EUS_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.EUS/Serif_16/pdf_to_json_test_Latn.EUS_Serif_16.py" > "data/multilingual/Latn.EUS/Serif_16/pdf_to_json_test_Latn.EUS_Serif_16.json" 2>&1
Latn.EUS_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.EUS/Serif_8/pdf_to_json_test_Latn.EUS_Serif_8.py" > "data/multilingual/Latn.EUS/Serif_8/pdf_to_json_test_Latn.EUS_Serif_8.json" 2>&1
Latn.EUS_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.EUS/Sun-ExtA_12/pdf_to_json_test_Latn.EUS_Sun-ExtA_12.py" > "data/multilingual/Latn.EUS/Sun-ExtA_12/pdf_to_json_test_Latn.EUS_Sun-ExtA_12.json" 2>&1
Latn.EUS_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.EUS/Sun-ExtA_16/pdf_to_json_test_Latn.EUS_Sun-ExtA_16.py" > "data/multilingual/Latn.EUS/Sun-ExtA_16/pdf_to_json_test_Latn.EUS_Sun-ExtA_16.json" 2>&1
Latn.EUS_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.EUS/Sun-ExtA_8/pdf_to_json_test_Latn.EUS_Sun-ExtA_8.py" > "data/multilingual/Latn.EUS/Sun-ExtA_8/pdf_to_json_test_Latn.EUS_Sun-ExtA_8.json" 2>&1


Latn.EUS_all : Latn.EUS_Mono_12 Latn.EUS_Mono_16 Latn.EUS_Mono_8 Latn.EUS_Sans_12 Latn.EUS_Sans_16 Latn.EUS_Sans_8 Latn.EUS_Serif_12 Latn.EUS_Serif_16 Latn.EUS_Serif_8 Latn.EUS_Sun-ExtA_12 Latn.EUS_Sun-ExtA_16 Latn.EUS_Sun-ExtA_8
