PYTHON=python3


Latn.QUE_Mono_12:
	-$(PYTHON) data/multilingual/Latn.QUE/Mono_12/pdf_to_json_test_Latn.QUE_Mono_12.py > data/multilingual/Latn.QUE/Mono_12/pdf_to_json_test_Latn.QUE_Mono_12.json 2>&1
Latn.QUE_Mono_16:
	-$(PYTHON) data/multilingual/Latn.QUE/Mono_16/pdf_to_json_test_Latn.QUE_Mono_16.py > data/multilingual/Latn.QUE/Mono_16/pdf_to_json_test_Latn.QUE_Mono_16.json 2>&1
Latn.QUE_Mono_8:
	-$(PYTHON) data/multilingual/Latn.QUE/Mono_8/pdf_to_json_test_Latn.QUE_Mono_8.py > data/multilingual/Latn.QUE/Mono_8/pdf_to_json_test_Latn.QUE_Mono_8.json 2>&1
Latn.QUE_Sans_12:
	-$(PYTHON) data/multilingual/Latn.QUE/Sans_12/pdf_to_json_test_Latn.QUE_Sans_12.py > data/multilingual/Latn.QUE/Sans_12/pdf_to_json_test_Latn.QUE_Sans_12.json 2>&1
Latn.QUE_Sans_16:
	-$(PYTHON) data/multilingual/Latn.QUE/Sans_16/pdf_to_json_test_Latn.QUE_Sans_16.py > data/multilingual/Latn.QUE/Sans_16/pdf_to_json_test_Latn.QUE_Sans_16.json 2>&1
Latn.QUE_Sans_8:
	-$(PYTHON) data/multilingual/Latn.QUE/Sans_8/pdf_to_json_test_Latn.QUE_Sans_8.py > data/multilingual/Latn.QUE/Sans_8/pdf_to_json_test_Latn.QUE_Sans_8.json 2>&1
Latn.QUE_Serif_12:
	-$(PYTHON) data/multilingual/Latn.QUE/Serif_12/pdf_to_json_test_Latn.QUE_Serif_12.py > data/multilingual/Latn.QUE/Serif_12/pdf_to_json_test_Latn.QUE_Serif_12.json 2>&1
Latn.QUE_Serif_16:
	-$(PYTHON) data/multilingual/Latn.QUE/Serif_16/pdf_to_json_test_Latn.QUE_Serif_16.py > data/multilingual/Latn.QUE/Serif_16/pdf_to_json_test_Latn.QUE_Serif_16.json 2>&1
Latn.QUE_Serif_8:
	-$(PYTHON) data/multilingual/Latn.QUE/Serif_8/pdf_to_json_test_Latn.QUE_Serif_8.py > data/multilingual/Latn.QUE/Serif_8/pdf_to_json_test_Latn.QUE_Serif_8.json 2>&1
Latn.QUE_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.QUE/Sun-ExtA_12/pdf_to_json_test_Latn.QUE_Sun-ExtA_12.py > data/multilingual/Latn.QUE/Sun-ExtA_12/pdf_to_json_test_Latn.QUE_Sun-ExtA_12.json 2>&1
Latn.QUE_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.QUE/Sun-ExtA_16/pdf_to_json_test_Latn.QUE_Sun-ExtA_16.py > data/multilingual/Latn.QUE/Sun-ExtA_16/pdf_to_json_test_Latn.QUE_Sun-ExtA_16.json 2>&1
Latn.QUE_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.QUE/Sun-ExtA_8/pdf_to_json_test_Latn.QUE_Sun-ExtA_8.py > data/multilingual/Latn.QUE/Sun-ExtA_8/pdf_to_json_test_Latn.QUE_Sun-ExtA_8.json 2>&1


Latn.QUE_all : Latn.QUE_Mono_12 Latn.QUE_Mono_16 Latn.QUE_Mono_8 Latn.QUE_Sans_12 Latn.QUE_Sans_16 Latn.QUE_Sans_8 Latn.QUE_Serif_12 Latn.QUE_Serif_16 Latn.QUE_Serif_8 Latn.QUE_Sun-ExtA_12 Latn.QUE_Sun-ExtA_16 Latn.QUE_Sun-ExtA_8
