PYTHON=python3


Latn.SPA_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.SPA/Mono_12/pdf_to_json_test_Latn.SPA_Mono_12.py" > "data/multilingual/Latn.SPA/Mono_12/pdf_to_json_test_Latn.SPA_Mono_12.json" 2>&1
Latn.SPA_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.SPA/Mono_16/pdf_to_json_test_Latn.SPA_Mono_16.py" > "data/multilingual/Latn.SPA/Mono_16/pdf_to_json_test_Latn.SPA_Mono_16.json" 2>&1
Latn.SPA_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.SPA/Mono_8/pdf_to_json_test_Latn.SPA_Mono_8.py" > "data/multilingual/Latn.SPA/Mono_8/pdf_to_json_test_Latn.SPA_Mono_8.json" 2>&1
Latn.SPA_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.SPA/Sans_12/pdf_to_json_test_Latn.SPA_Sans_12.py" > "data/multilingual/Latn.SPA/Sans_12/pdf_to_json_test_Latn.SPA_Sans_12.json" 2>&1
Latn.SPA_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.SPA/Sans_16/pdf_to_json_test_Latn.SPA_Sans_16.py" > "data/multilingual/Latn.SPA/Sans_16/pdf_to_json_test_Latn.SPA_Sans_16.json" 2>&1
Latn.SPA_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.SPA/Sans_8/pdf_to_json_test_Latn.SPA_Sans_8.py" > "data/multilingual/Latn.SPA/Sans_8/pdf_to_json_test_Latn.SPA_Sans_8.json" 2>&1
Latn.SPA_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.SPA/Serif_12/pdf_to_json_test_Latn.SPA_Serif_12.py" > "data/multilingual/Latn.SPA/Serif_12/pdf_to_json_test_Latn.SPA_Serif_12.json" 2>&1
Latn.SPA_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.SPA/Serif_16/pdf_to_json_test_Latn.SPA_Serif_16.py" > "data/multilingual/Latn.SPA/Serif_16/pdf_to_json_test_Latn.SPA_Serif_16.json" 2>&1
Latn.SPA_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.SPA/Serif_8/pdf_to_json_test_Latn.SPA_Serif_8.py" > "data/multilingual/Latn.SPA/Serif_8/pdf_to_json_test_Latn.SPA_Serif_8.json" 2>&1
Latn.SPA_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.SPA/Sun-ExtA_12/pdf_to_json_test_Latn.SPA_Sun-ExtA_12.py" > "data/multilingual/Latn.SPA/Sun-ExtA_12/pdf_to_json_test_Latn.SPA_Sun-ExtA_12.json" 2>&1
Latn.SPA_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.SPA/Sun-ExtA_16/pdf_to_json_test_Latn.SPA_Sun-ExtA_16.py" > "data/multilingual/Latn.SPA/Sun-ExtA_16/pdf_to_json_test_Latn.SPA_Sun-ExtA_16.json" 2>&1
Latn.SPA_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.SPA/Sun-ExtA_8/pdf_to_json_test_Latn.SPA_Sun-ExtA_8.py" > "data/multilingual/Latn.SPA/Sun-ExtA_8/pdf_to_json_test_Latn.SPA_Sun-ExtA_8.json" 2>&1


Latn.SPA_all : Latn.SPA_Mono_12 Latn.SPA_Mono_16 Latn.SPA_Mono_8 Latn.SPA_Sans_12 Latn.SPA_Sans_16 Latn.SPA_Sans_8 Latn.SPA_Serif_12 Latn.SPA_Serif_16 Latn.SPA_Serif_8 Latn.SPA_Sun-ExtA_12 Latn.SPA_Sun-ExtA_16 Latn.SPA_Sun-ExtA_8
