PYTHON=python3


Latn.IDO_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.IDO/Mono_12/pdf_to_json_test_Latn.IDO_Mono_12.py" > "data/multilingual/Latn.IDO/Mono_12/pdf_to_json_test_Latn.IDO_Mono_12.json" 2>&1
Latn.IDO_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.IDO/Mono_16/pdf_to_json_test_Latn.IDO_Mono_16.py" > "data/multilingual/Latn.IDO/Mono_16/pdf_to_json_test_Latn.IDO_Mono_16.json" 2>&1
Latn.IDO_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.IDO/Mono_8/pdf_to_json_test_Latn.IDO_Mono_8.py" > "data/multilingual/Latn.IDO/Mono_8/pdf_to_json_test_Latn.IDO_Mono_8.json" 2>&1
Latn.IDO_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.IDO/Sans_12/pdf_to_json_test_Latn.IDO_Sans_12.py" > "data/multilingual/Latn.IDO/Sans_12/pdf_to_json_test_Latn.IDO_Sans_12.json" 2>&1
Latn.IDO_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.IDO/Sans_16/pdf_to_json_test_Latn.IDO_Sans_16.py" > "data/multilingual/Latn.IDO/Sans_16/pdf_to_json_test_Latn.IDO_Sans_16.json" 2>&1
Latn.IDO_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.IDO/Sans_8/pdf_to_json_test_Latn.IDO_Sans_8.py" > "data/multilingual/Latn.IDO/Sans_8/pdf_to_json_test_Latn.IDO_Sans_8.json" 2>&1
Latn.IDO_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.IDO/Serif_12/pdf_to_json_test_Latn.IDO_Serif_12.py" > "data/multilingual/Latn.IDO/Serif_12/pdf_to_json_test_Latn.IDO_Serif_12.json" 2>&1
Latn.IDO_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.IDO/Serif_16/pdf_to_json_test_Latn.IDO_Serif_16.py" > "data/multilingual/Latn.IDO/Serif_16/pdf_to_json_test_Latn.IDO_Serif_16.json" 2>&1
Latn.IDO_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.IDO/Serif_8/pdf_to_json_test_Latn.IDO_Serif_8.py" > "data/multilingual/Latn.IDO/Serif_8/pdf_to_json_test_Latn.IDO_Serif_8.json" 2>&1
Latn.IDO_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.IDO/Sun-ExtA_12/pdf_to_json_test_Latn.IDO_Sun-ExtA_12.py" > "data/multilingual/Latn.IDO/Sun-ExtA_12/pdf_to_json_test_Latn.IDO_Sun-ExtA_12.json" 2>&1
Latn.IDO_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.IDO/Sun-ExtA_16/pdf_to_json_test_Latn.IDO_Sun-ExtA_16.py" > "data/multilingual/Latn.IDO/Sun-ExtA_16/pdf_to_json_test_Latn.IDO_Sun-ExtA_16.json" 2>&1
Latn.IDO_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.IDO/Sun-ExtA_8/pdf_to_json_test_Latn.IDO_Sun-ExtA_8.py" > "data/multilingual/Latn.IDO/Sun-ExtA_8/pdf_to_json_test_Latn.IDO_Sun-ExtA_8.json" 2>&1


Latn.IDO_all : Latn.IDO_Mono_12 Latn.IDO_Mono_16 Latn.IDO_Mono_8 Latn.IDO_Sans_12 Latn.IDO_Sans_16 Latn.IDO_Sans_8 Latn.IDO_Serif_12 Latn.IDO_Serif_16 Latn.IDO_Serif_8 Latn.IDO_Sun-ExtA_12 Latn.IDO_Sun-ExtA_16 Latn.IDO_Sun-ExtA_8
