PYTHON=python3


Latn.POL_Mono_12:
	-$(PYTHON) data/multilingual/Latn.POL/Mono_12/pdf_to_json_test_Latn.POL_Mono_12.py > data/multilingual/Latn.POL/Mono_12/pdf_to_json_test_Latn.POL_Mono_12.json 2>&1
Latn.POL_Mono_16:
	-$(PYTHON) data/multilingual/Latn.POL/Mono_16/pdf_to_json_test_Latn.POL_Mono_16.py > data/multilingual/Latn.POL/Mono_16/pdf_to_json_test_Latn.POL_Mono_16.json 2>&1
Latn.POL_Mono_8:
	-$(PYTHON) data/multilingual/Latn.POL/Mono_8/pdf_to_json_test_Latn.POL_Mono_8.py > data/multilingual/Latn.POL/Mono_8/pdf_to_json_test_Latn.POL_Mono_8.json 2>&1
Latn.POL_Sans_12:
	-$(PYTHON) data/multilingual/Latn.POL/Sans_12/pdf_to_json_test_Latn.POL_Sans_12.py > data/multilingual/Latn.POL/Sans_12/pdf_to_json_test_Latn.POL_Sans_12.json 2>&1
Latn.POL_Sans_16:
	-$(PYTHON) data/multilingual/Latn.POL/Sans_16/pdf_to_json_test_Latn.POL_Sans_16.py > data/multilingual/Latn.POL/Sans_16/pdf_to_json_test_Latn.POL_Sans_16.json 2>&1
Latn.POL_Sans_8:
	-$(PYTHON) data/multilingual/Latn.POL/Sans_8/pdf_to_json_test_Latn.POL_Sans_8.py > data/multilingual/Latn.POL/Sans_8/pdf_to_json_test_Latn.POL_Sans_8.json 2>&1
Latn.POL_Serif_12:
	-$(PYTHON) data/multilingual/Latn.POL/Serif_12/pdf_to_json_test_Latn.POL_Serif_12.py > data/multilingual/Latn.POL/Serif_12/pdf_to_json_test_Latn.POL_Serif_12.json 2>&1
Latn.POL_Serif_16:
	-$(PYTHON) data/multilingual/Latn.POL/Serif_16/pdf_to_json_test_Latn.POL_Serif_16.py > data/multilingual/Latn.POL/Serif_16/pdf_to_json_test_Latn.POL_Serif_16.json 2>&1
Latn.POL_Serif_8:
	-$(PYTHON) data/multilingual/Latn.POL/Serif_8/pdf_to_json_test_Latn.POL_Serif_8.py > data/multilingual/Latn.POL/Serif_8/pdf_to_json_test_Latn.POL_Serif_8.json 2>&1
Latn.POL_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.POL/Sun-ExtA_12/pdf_to_json_test_Latn.POL_Sun-ExtA_12.py > data/multilingual/Latn.POL/Sun-ExtA_12/pdf_to_json_test_Latn.POL_Sun-ExtA_12.json 2>&1
Latn.POL_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.POL/Sun-ExtA_16/pdf_to_json_test_Latn.POL_Sun-ExtA_16.py > data/multilingual/Latn.POL/Sun-ExtA_16/pdf_to_json_test_Latn.POL_Sun-ExtA_16.json 2>&1
Latn.POL_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.POL/Sun-ExtA_8/pdf_to_json_test_Latn.POL_Sun-ExtA_8.py > data/multilingual/Latn.POL/Sun-ExtA_8/pdf_to_json_test_Latn.POL_Sun-ExtA_8.json 2>&1


Latn.POL_all : Latn.POL_Mono_12 Latn.POL_Mono_16 Latn.POL_Mono_8 Latn.POL_Sans_12 Latn.POL_Sans_16 Latn.POL_Sans_8 Latn.POL_Serif_12 Latn.POL_Serif_16 Latn.POL_Serif_8 Latn.POL_Sun-ExtA_12 Latn.POL_Sun-ExtA_16 Latn.POL_Sun-ExtA_8
