PYTHON=python3


Latn.ENG_Mono_12:
	-$(PYTHON) data/multilingual/Latn.ENG/Mono_12/pdf_to_json_test_Latn.ENG_Mono_12.py > data/multilingual/Latn.ENG/Mono_12/pdf_to_json_test_Latn.ENG_Mono_12.json 2>&1
Latn.ENG_Mono_16:
	-$(PYTHON) data/multilingual/Latn.ENG/Mono_16/pdf_to_json_test_Latn.ENG_Mono_16.py > data/multilingual/Latn.ENG/Mono_16/pdf_to_json_test_Latn.ENG_Mono_16.json 2>&1
Latn.ENG_Mono_8:
	-$(PYTHON) data/multilingual/Latn.ENG/Mono_8/pdf_to_json_test_Latn.ENG_Mono_8.py > data/multilingual/Latn.ENG/Mono_8/pdf_to_json_test_Latn.ENG_Mono_8.json 2>&1
Latn.ENG_Sans_12:
	-$(PYTHON) data/multilingual/Latn.ENG/Sans_12/pdf_to_json_test_Latn.ENG_Sans_12.py > data/multilingual/Latn.ENG/Sans_12/pdf_to_json_test_Latn.ENG_Sans_12.json 2>&1
Latn.ENG_Sans_16:
	-$(PYTHON) data/multilingual/Latn.ENG/Sans_16/pdf_to_json_test_Latn.ENG_Sans_16.py > data/multilingual/Latn.ENG/Sans_16/pdf_to_json_test_Latn.ENG_Sans_16.json 2>&1
Latn.ENG_Sans_8:
	-$(PYTHON) data/multilingual/Latn.ENG/Sans_8/pdf_to_json_test_Latn.ENG_Sans_8.py > data/multilingual/Latn.ENG/Sans_8/pdf_to_json_test_Latn.ENG_Sans_8.json 2>&1
Latn.ENG_Serif_12:
	-$(PYTHON) data/multilingual/Latn.ENG/Serif_12/pdf_to_json_test_Latn.ENG_Serif_12.py > data/multilingual/Latn.ENG/Serif_12/pdf_to_json_test_Latn.ENG_Serif_12.json 2>&1
Latn.ENG_Serif_16:
	-$(PYTHON) data/multilingual/Latn.ENG/Serif_16/pdf_to_json_test_Latn.ENG_Serif_16.py > data/multilingual/Latn.ENG/Serif_16/pdf_to_json_test_Latn.ENG_Serif_16.json 2>&1
Latn.ENG_Serif_8:
	-$(PYTHON) data/multilingual/Latn.ENG/Serif_8/pdf_to_json_test_Latn.ENG_Serif_8.py > data/multilingual/Latn.ENG/Serif_8/pdf_to_json_test_Latn.ENG_Serif_8.json 2>&1
Latn.ENG_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.ENG/Sun-ExtA_12/pdf_to_json_test_Latn.ENG_Sun-ExtA_12.py > data/multilingual/Latn.ENG/Sun-ExtA_12/pdf_to_json_test_Latn.ENG_Sun-ExtA_12.json 2>&1
Latn.ENG_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.ENG/Sun-ExtA_16/pdf_to_json_test_Latn.ENG_Sun-ExtA_16.py > data/multilingual/Latn.ENG/Sun-ExtA_16/pdf_to_json_test_Latn.ENG_Sun-ExtA_16.json 2>&1
Latn.ENG_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.ENG/Sun-ExtA_8/pdf_to_json_test_Latn.ENG_Sun-ExtA_8.py > data/multilingual/Latn.ENG/Sun-ExtA_8/pdf_to_json_test_Latn.ENG_Sun-ExtA_8.json 2>&1


Latn.ENG_all : Latn.ENG_Mono_12 Latn.ENG_Mono_16 Latn.ENG_Mono_8 Latn.ENG_Sans_12 Latn.ENG_Sans_16 Latn.ENG_Sans_8 Latn.ENG_Serif_12 Latn.ENG_Serif_16 Latn.ENG_Serif_8 Latn.ENG_Sun-ExtA_12 Latn.ENG_Sun-ExtA_16 Latn.ENG_Sun-ExtA_8
