PYTHON=python3


Latn.MAM_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.MAM/Mono_12/pdf_to_json_test_Latn.MAM_Mono_12.py" > "data/multilingual/Latn.MAM/Mono_12/pdf_to_json_test_Latn.MAM_Mono_12.json" 2>&1
Latn.MAM_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.MAM/Mono_16/pdf_to_json_test_Latn.MAM_Mono_16.py" > "data/multilingual/Latn.MAM/Mono_16/pdf_to_json_test_Latn.MAM_Mono_16.json" 2>&1
Latn.MAM_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.MAM/Mono_8/pdf_to_json_test_Latn.MAM_Mono_8.py" > "data/multilingual/Latn.MAM/Mono_8/pdf_to_json_test_Latn.MAM_Mono_8.json" 2>&1
Latn.MAM_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.MAM/Sans_12/pdf_to_json_test_Latn.MAM_Sans_12.py" > "data/multilingual/Latn.MAM/Sans_12/pdf_to_json_test_Latn.MAM_Sans_12.json" 2>&1
Latn.MAM_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.MAM/Sans_16/pdf_to_json_test_Latn.MAM_Sans_16.py" > "data/multilingual/Latn.MAM/Sans_16/pdf_to_json_test_Latn.MAM_Sans_16.json" 2>&1
Latn.MAM_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.MAM/Sans_8/pdf_to_json_test_Latn.MAM_Sans_8.py" > "data/multilingual/Latn.MAM/Sans_8/pdf_to_json_test_Latn.MAM_Sans_8.json" 2>&1
Latn.MAM_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.MAM/Serif_12/pdf_to_json_test_Latn.MAM_Serif_12.py" > "data/multilingual/Latn.MAM/Serif_12/pdf_to_json_test_Latn.MAM_Serif_12.json" 2>&1
Latn.MAM_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.MAM/Serif_16/pdf_to_json_test_Latn.MAM_Serif_16.py" > "data/multilingual/Latn.MAM/Serif_16/pdf_to_json_test_Latn.MAM_Serif_16.json" 2>&1
Latn.MAM_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.MAM/Serif_8/pdf_to_json_test_Latn.MAM_Serif_8.py" > "data/multilingual/Latn.MAM/Serif_8/pdf_to_json_test_Latn.MAM_Serif_8.json" 2>&1
Latn.MAM_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.MAM/Sun-ExtA_12/pdf_to_json_test_Latn.MAM_Sun-ExtA_12.py" > "data/multilingual/Latn.MAM/Sun-ExtA_12/pdf_to_json_test_Latn.MAM_Sun-ExtA_12.json" 2>&1
Latn.MAM_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.MAM/Sun-ExtA_16/pdf_to_json_test_Latn.MAM_Sun-ExtA_16.py" > "data/multilingual/Latn.MAM/Sun-ExtA_16/pdf_to_json_test_Latn.MAM_Sun-ExtA_16.json" 2>&1
Latn.MAM_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.MAM/Sun-ExtA_8/pdf_to_json_test_Latn.MAM_Sun-ExtA_8.py" > "data/multilingual/Latn.MAM/Sun-ExtA_8/pdf_to_json_test_Latn.MAM_Sun-ExtA_8.json" 2>&1


Latn.MAM_all : Latn.MAM_Mono_12 Latn.MAM_Mono_16 Latn.MAM_Mono_8 Latn.MAM_Sans_12 Latn.MAM_Sans_16 Latn.MAM_Sans_8 Latn.MAM_Serif_12 Latn.MAM_Serif_16 Latn.MAM_Serif_8 Latn.MAM_Sun-ExtA_12 Latn.MAM_Sun-ExtA_16 Latn.MAM_Sun-ExtA_8
