PYTHON=python3


Latn.ARL_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.ARL/Mono_12/pdf_to_json_test_Latn.ARL_Mono_12.py" > "data/multilingual/Latn.ARL/Mono_12/pdf_to_json_test_Latn.ARL_Mono_12.json" 2>&1
Latn.ARL_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.ARL/Mono_16/pdf_to_json_test_Latn.ARL_Mono_16.py" > "data/multilingual/Latn.ARL/Mono_16/pdf_to_json_test_Latn.ARL_Mono_16.json" 2>&1
Latn.ARL_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.ARL/Mono_8/pdf_to_json_test_Latn.ARL_Mono_8.py" > "data/multilingual/Latn.ARL/Mono_8/pdf_to_json_test_Latn.ARL_Mono_8.json" 2>&1
Latn.ARL_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.ARL/Sans_12/pdf_to_json_test_Latn.ARL_Sans_12.py" > "data/multilingual/Latn.ARL/Sans_12/pdf_to_json_test_Latn.ARL_Sans_12.json" 2>&1
Latn.ARL_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.ARL/Sans_16/pdf_to_json_test_Latn.ARL_Sans_16.py" > "data/multilingual/Latn.ARL/Sans_16/pdf_to_json_test_Latn.ARL_Sans_16.json" 2>&1
Latn.ARL_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.ARL/Sans_8/pdf_to_json_test_Latn.ARL_Sans_8.py" > "data/multilingual/Latn.ARL/Sans_8/pdf_to_json_test_Latn.ARL_Sans_8.json" 2>&1
Latn.ARL_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.ARL/Serif_12/pdf_to_json_test_Latn.ARL_Serif_12.py" > "data/multilingual/Latn.ARL/Serif_12/pdf_to_json_test_Latn.ARL_Serif_12.json" 2>&1
Latn.ARL_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.ARL/Serif_16/pdf_to_json_test_Latn.ARL_Serif_16.py" > "data/multilingual/Latn.ARL/Serif_16/pdf_to_json_test_Latn.ARL_Serif_16.json" 2>&1
Latn.ARL_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.ARL/Serif_8/pdf_to_json_test_Latn.ARL_Serif_8.py" > "data/multilingual/Latn.ARL/Serif_8/pdf_to_json_test_Latn.ARL_Serif_8.json" 2>&1
Latn.ARL_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.ARL/Sun-ExtA_12/pdf_to_json_test_Latn.ARL_Sun-ExtA_12.py" > "data/multilingual/Latn.ARL/Sun-ExtA_12/pdf_to_json_test_Latn.ARL_Sun-ExtA_12.json" 2>&1
Latn.ARL_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.ARL/Sun-ExtA_16/pdf_to_json_test_Latn.ARL_Sun-ExtA_16.py" > "data/multilingual/Latn.ARL/Sun-ExtA_16/pdf_to_json_test_Latn.ARL_Sun-ExtA_16.json" 2>&1
Latn.ARL_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.ARL/Sun-ExtA_8/pdf_to_json_test_Latn.ARL_Sun-ExtA_8.py" > "data/multilingual/Latn.ARL/Sun-ExtA_8/pdf_to_json_test_Latn.ARL_Sun-ExtA_8.json" 2>&1


Latn.ARL_all : Latn.ARL_Mono_12 Latn.ARL_Mono_16 Latn.ARL_Mono_8 Latn.ARL_Sans_12 Latn.ARL_Sans_16 Latn.ARL_Sans_8 Latn.ARL_Serif_12 Latn.ARL_Serif_16 Latn.ARL_Serif_8 Latn.ARL_Sun-ExtA_12 Latn.ARL_Sun-ExtA_16 Latn.ARL_Sun-ExtA_8
