PYTHON=python3


Latn.SRP_Mono_12:
	-$(PYTHON) data/multilingual/Latn.SRP/Mono_12/pdf_to_json_test_Latn.SRP_Mono_12.py > data/multilingual/Latn.SRP/Mono_12/pdf_to_json_test_Latn.SRP_Mono_12.json 2>&1
Latn.SRP_Mono_16:
	-$(PYTHON) data/multilingual/Latn.SRP/Mono_16/pdf_to_json_test_Latn.SRP_Mono_16.py > data/multilingual/Latn.SRP/Mono_16/pdf_to_json_test_Latn.SRP_Mono_16.json 2>&1
Latn.SRP_Mono_8:
	-$(PYTHON) data/multilingual/Latn.SRP/Mono_8/pdf_to_json_test_Latn.SRP_Mono_8.py > data/multilingual/Latn.SRP/Mono_8/pdf_to_json_test_Latn.SRP_Mono_8.json 2>&1
Latn.SRP_Sans_12:
	-$(PYTHON) data/multilingual/Latn.SRP/Sans_12/pdf_to_json_test_Latn.SRP_Sans_12.py > data/multilingual/Latn.SRP/Sans_12/pdf_to_json_test_Latn.SRP_Sans_12.json 2>&1
Latn.SRP_Sans_16:
	-$(PYTHON) data/multilingual/Latn.SRP/Sans_16/pdf_to_json_test_Latn.SRP_Sans_16.py > data/multilingual/Latn.SRP/Sans_16/pdf_to_json_test_Latn.SRP_Sans_16.json 2>&1
Latn.SRP_Sans_8:
	-$(PYTHON) data/multilingual/Latn.SRP/Sans_8/pdf_to_json_test_Latn.SRP_Sans_8.py > data/multilingual/Latn.SRP/Sans_8/pdf_to_json_test_Latn.SRP_Sans_8.json 2>&1
Latn.SRP_Serif_12:
	-$(PYTHON) data/multilingual/Latn.SRP/Serif_12/pdf_to_json_test_Latn.SRP_Serif_12.py > data/multilingual/Latn.SRP/Serif_12/pdf_to_json_test_Latn.SRP_Serif_12.json 2>&1
Latn.SRP_Serif_16:
	-$(PYTHON) data/multilingual/Latn.SRP/Serif_16/pdf_to_json_test_Latn.SRP_Serif_16.py > data/multilingual/Latn.SRP/Serif_16/pdf_to_json_test_Latn.SRP_Serif_16.json 2>&1
Latn.SRP_Serif_8:
	-$(PYTHON) data/multilingual/Latn.SRP/Serif_8/pdf_to_json_test_Latn.SRP_Serif_8.py > data/multilingual/Latn.SRP/Serif_8/pdf_to_json_test_Latn.SRP_Serif_8.json 2>&1
Latn.SRP_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.SRP/Sun-ExtA_12/pdf_to_json_test_Latn.SRP_Sun-ExtA_12.py > data/multilingual/Latn.SRP/Sun-ExtA_12/pdf_to_json_test_Latn.SRP_Sun-ExtA_12.json 2>&1
Latn.SRP_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.SRP/Sun-ExtA_16/pdf_to_json_test_Latn.SRP_Sun-ExtA_16.py > data/multilingual/Latn.SRP/Sun-ExtA_16/pdf_to_json_test_Latn.SRP_Sun-ExtA_16.json 2>&1
Latn.SRP_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.SRP/Sun-ExtA_8/pdf_to_json_test_Latn.SRP_Sun-ExtA_8.py > data/multilingual/Latn.SRP/Sun-ExtA_8/pdf_to_json_test_Latn.SRP_Sun-ExtA_8.json 2>&1


Latn.SRP_all : Latn.SRP_Mono_12 Latn.SRP_Mono_16 Latn.SRP_Mono_8 Latn.SRP_Sans_12 Latn.SRP_Sans_16 Latn.SRP_Sans_8 Latn.SRP_Serif_12 Latn.SRP_Serif_16 Latn.SRP_Serif_8 Latn.SRP_Sun-ExtA_12 Latn.SRP_Sun-ExtA_16 Latn.SRP_Sun-ExtA_8
