PYTHON=python3


Latn.ZAM_Mono_12:
	-$(PYTHON) data/multilingual/Latn.ZAM/Mono_12/pdf_to_json_test_Latn.ZAM_Mono_12.py > data/multilingual/Latn.ZAM/Mono_12/pdf_to_json_test_Latn.ZAM_Mono_12.json 2>&1
Latn.ZAM_Mono_16:
	-$(PYTHON) data/multilingual/Latn.ZAM/Mono_16/pdf_to_json_test_Latn.ZAM_Mono_16.py > data/multilingual/Latn.ZAM/Mono_16/pdf_to_json_test_Latn.ZAM_Mono_16.json 2>&1
Latn.ZAM_Mono_8:
	-$(PYTHON) data/multilingual/Latn.ZAM/Mono_8/pdf_to_json_test_Latn.ZAM_Mono_8.py > data/multilingual/Latn.ZAM/Mono_8/pdf_to_json_test_Latn.ZAM_Mono_8.json 2>&1
Latn.ZAM_Sans_12:
	-$(PYTHON) data/multilingual/Latn.ZAM/Sans_12/pdf_to_json_test_Latn.ZAM_Sans_12.py > data/multilingual/Latn.ZAM/Sans_12/pdf_to_json_test_Latn.ZAM_Sans_12.json 2>&1
Latn.ZAM_Sans_16:
	-$(PYTHON) data/multilingual/Latn.ZAM/Sans_16/pdf_to_json_test_Latn.ZAM_Sans_16.py > data/multilingual/Latn.ZAM/Sans_16/pdf_to_json_test_Latn.ZAM_Sans_16.json 2>&1
Latn.ZAM_Sans_8:
	-$(PYTHON) data/multilingual/Latn.ZAM/Sans_8/pdf_to_json_test_Latn.ZAM_Sans_8.py > data/multilingual/Latn.ZAM/Sans_8/pdf_to_json_test_Latn.ZAM_Sans_8.json 2>&1
Latn.ZAM_Serif_12:
	-$(PYTHON) data/multilingual/Latn.ZAM/Serif_12/pdf_to_json_test_Latn.ZAM_Serif_12.py > data/multilingual/Latn.ZAM/Serif_12/pdf_to_json_test_Latn.ZAM_Serif_12.json 2>&1
Latn.ZAM_Serif_16:
	-$(PYTHON) data/multilingual/Latn.ZAM/Serif_16/pdf_to_json_test_Latn.ZAM_Serif_16.py > data/multilingual/Latn.ZAM/Serif_16/pdf_to_json_test_Latn.ZAM_Serif_16.json 2>&1
Latn.ZAM_Serif_8:
	-$(PYTHON) data/multilingual/Latn.ZAM/Serif_8/pdf_to_json_test_Latn.ZAM_Serif_8.py > data/multilingual/Latn.ZAM/Serif_8/pdf_to_json_test_Latn.ZAM_Serif_8.json 2>&1
Latn.ZAM_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.ZAM/Sun-ExtA_12/pdf_to_json_test_Latn.ZAM_Sun-ExtA_12.py > data/multilingual/Latn.ZAM/Sun-ExtA_12/pdf_to_json_test_Latn.ZAM_Sun-ExtA_12.json 2>&1
Latn.ZAM_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.ZAM/Sun-ExtA_16/pdf_to_json_test_Latn.ZAM_Sun-ExtA_16.py > data/multilingual/Latn.ZAM/Sun-ExtA_16/pdf_to_json_test_Latn.ZAM_Sun-ExtA_16.json 2>&1
Latn.ZAM_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.ZAM/Sun-ExtA_8/pdf_to_json_test_Latn.ZAM_Sun-ExtA_8.py > data/multilingual/Latn.ZAM/Sun-ExtA_8/pdf_to_json_test_Latn.ZAM_Sun-ExtA_8.json 2>&1


Latn.ZAM_all : Latn.ZAM_Mono_12 Latn.ZAM_Mono_16 Latn.ZAM_Mono_8 Latn.ZAM_Sans_12 Latn.ZAM_Sans_16 Latn.ZAM_Sans_8 Latn.ZAM_Serif_12 Latn.ZAM_Serif_16 Latn.ZAM_Serif_8 Latn.ZAM_Sun-ExtA_12 Latn.ZAM_Sun-ExtA_16 Latn.ZAM_Sun-ExtA_8
