PYTHON=python3


Cyrl.MKD_Mono_12:
	-$(PYTHON) "data/multilingual/Cyrl.MKD/Mono_12/pdf_to_json_test_Cyrl.MKD_Mono_12.py" > "data/multilingual/Cyrl.MKD/Mono_12/pdf_to_json_test_Cyrl.MKD_Mono_12.json" 2>&1
Cyrl.MKD_Mono_16:
	-$(PYTHON) "data/multilingual/Cyrl.MKD/Mono_16/pdf_to_json_test_Cyrl.MKD_Mono_16.py" > "data/multilingual/Cyrl.MKD/Mono_16/pdf_to_json_test_Cyrl.MKD_Mono_16.json" 2>&1
Cyrl.MKD_Mono_8:
	-$(PYTHON) "data/multilingual/Cyrl.MKD/Mono_8/pdf_to_json_test_Cyrl.MKD_Mono_8.py" > "data/multilingual/Cyrl.MKD/Mono_8/pdf_to_json_test_Cyrl.MKD_Mono_8.json" 2>&1
Cyrl.MKD_Sans_12:
	-$(PYTHON) "data/multilingual/Cyrl.MKD/Sans_12/pdf_to_json_test_Cyrl.MKD_Sans_12.py" > "data/multilingual/Cyrl.MKD/Sans_12/pdf_to_json_test_Cyrl.MKD_Sans_12.json" 2>&1
Cyrl.MKD_Sans_16:
	-$(PYTHON) "data/multilingual/Cyrl.MKD/Sans_16/pdf_to_json_test_Cyrl.MKD_Sans_16.py" > "data/multilingual/Cyrl.MKD/Sans_16/pdf_to_json_test_Cyrl.MKD_Sans_16.json" 2>&1
Cyrl.MKD_Sans_8:
	-$(PYTHON) "data/multilingual/Cyrl.MKD/Sans_8/pdf_to_json_test_Cyrl.MKD_Sans_8.py" > "data/multilingual/Cyrl.MKD/Sans_8/pdf_to_json_test_Cyrl.MKD_Sans_8.json" 2>&1
Cyrl.MKD_Serif_12:
	-$(PYTHON) "data/multilingual/Cyrl.MKD/Serif_12/pdf_to_json_test_Cyrl.MKD_Serif_12.py" > "data/multilingual/Cyrl.MKD/Serif_12/pdf_to_json_test_Cyrl.MKD_Serif_12.json" 2>&1
Cyrl.MKD_Serif_16:
	-$(PYTHON) "data/multilingual/Cyrl.MKD/Serif_16/pdf_to_json_test_Cyrl.MKD_Serif_16.py" > "data/multilingual/Cyrl.MKD/Serif_16/pdf_to_json_test_Cyrl.MKD_Serif_16.json" 2>&1
Cyrl.MKD_Serif_8:
	-$(PYTHON) "data/multilingual/Cyrl.MKD/Serif_8/pdf_to_json_test_Cyrl.MKD_Serif_8.py" > "data/multilingual/Cyrl.MKD/Serif_8/pdf_to_json_test_Cyrl.MKD_Serif_8.json" 2>&1
Cyrl.MKD_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Cyrl.MKD/Sun-ExtA_12/pdf_to_json_test_Cyrl.MKD_Sun-ExtA_12.py" > "data/multilingual/Cyrl.MKD/Sun-ExtA_12/pdf_to_json_test_Cyrl.MKD_Sun-ExtA_12.json" 2>&1
Cyrl.MKD_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Cyrl.MKD/Sun-ExtA_16/pdf_to_json_test_Cyrl.MKD_Sun-ExtA_16.py" > "data/multilingual/Cyrl.MKD/Sun-ExtA_16/pdf_to_json_test_Cyrl.MKD_Sun-ExtA_16.json" 2>&1
Cyrl.MKD_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Cyrl.MKD/Sun-ExtA_8/pdf_to_json_test_Cyrl.MKD_Sun-ExtA_8.py" > "data/multilingual/Cyrl.MKD/Sun-ExtA_8/pdf_to_json_test_Cyrl.MKD_Sun-ExtA_8.json" 2>&1


Cyrl.MKD_all : Cyrl.MKD_Mono_12 Cyrl.MKD_Mono_16 Cyrl.MKD_Mono_8 Cyrl.MKD_Sans_12 Cyrl.MKD_Sans_16 Cyrl.MKD_Sans_8 Cyrl.MKD_Serif_12 Cyrl.MKD_Serif_16 Cyrl.MKD_Serif_8 Cyrl.MKD_Sun-ExtA_12 Cyrl.MKD_Sun-ExtA_16 Cyrl.MKD_Sun-ExtA_8
