PYTHON=python3


Latn.URA_Mono_12:
	-$(PYTHON) data/multilingual/Latn.URA/Mono_12/pdf_to_json_test_Latn.URA_Mono_12.py > data/multilingual/Latn.URA/Mono_12/pdf_to_json_test_Latn.URA_Mono_12.json 2>&1
Latn.URA_Mono_16:
	-$(PYTHON) data/multilingual/Latn.URA/Mono_16/pdf_to_json_test_Latn.URA_Mono_16.py > data/multilingual/Latn.URA/Mono_16/pdf_to_json_test_Latn.URA_Mono_16.json 2>&1
Latn.URA_Mono_8:
	-$(PYTHON) data/multilingual/Latn.URA/Mono_8/pdf_to_json_test_Latn.URA_Mono_8.py > data/multilingual/Latn.URA/Mono_8/pdf_to_json_test_Latn.URA_Mono_8.json 2>&1
Latn.URA_Sans_12:
	-$(PYTHON) data/multilingual/Latn.URA/Sans_12/pdf_to_json_test_Latn.URA_Sans_12.py > data/multilingual/Latn.URA/Sans_12/pdf_to_json_test_Latn.URA_Sans_12.json 2>&1
Latn.URA_Sans_16:
	-$(PYTHON) data/multilingual/Latn.URA/Sans_16/pdf_to_json_test_Latn.URA_Sans_16.py > data/multilingual/Latn.URA/Sans_16/pdf_to_json_test_Latn.URA_Sans_16.json 2>&1
Latn.URA_Sans_8:
	-$(PYTHON) data/multilingual/Latn.URA/Sans_8/pdf_to_json_test_Latn.URA_Sans_8.py > data/multilingual/Latn.URA/Sans_8/pdf_to_json_test_Latn.URA_Sans_8.json 2>&1
Latn.URA_Serif_12:
	-$(PYTHON) data/multilingual/Latn.URA/Serif_12/pdf_to_json_test_Latn.URA_Serif_12.py > data/multilingual/Latn.URA/Serif_12/pdf_to_json_test_Latn.URA_Serif_12.json 2>&1
Latn.URA_Serif_16:
	-$(PYTHON) data/multilingual/Latn.URA/Serif_16/pdf_to_json_test_Latn.URA_Serif_16.py > data/multilingual/Latn.URA/Serif_16/pdf_to_json_test_Latn.URA_Serif_16.json 2>&1
Latn.URA_Serif_8:
	-$(PYTHON) data/multilingual/Latn.URA/Serif_8/pdf_to_json_test_Latn.URA_Serif_8.py > data/multilingual/Latn.URA/Serif_8/pdf_to_json_test_Latn.URA_Serif_8.json 2>&1
Latn.URA_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.URA/Sun-ExtA_12/pdf_to_json_test_Latn.URA_Sun-ExtA_12.py > data/multilingual/Latn.URA/Sun-ExtA_12/pdf_to_json_test_Latn.URA_Sun-ExtA_12.json 2>&1
Latn.URA_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.URA/Sun-ExtA_16/pdf_to_json_test_Latn.URA_Sun-ExtA_16.py > data/multilingual/Latn.URA/Sun-ExtA_16/pdf_to_json_test_Latn.URA_Sun-ExtA_16.json 2>&1
Latn.URA_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.URA/Sun-ExtA_8/pdf_to_json_test_Latn.URA_Sun-ExtA_8.py > data/multilingual/Latn.URA/Sun-ExtA_8/pdf_to_json_test_Latn.URA_Sun-ExtA_8.json 2>&1


Latn.URA_all : Latn.URA_Mono_12 Latn.URA_Mono_16 Latn.URA_Mono_8 Latn.URA_Sans_12 Latn.URA_Sans_16 Latn.URA_Sans_8 Latn.URA_Serif_12 Latn.URA_Serif_16 Latn.URA_Serif_8 Latn.URA_Sun-ExtA_12 Latn.URA_Sun-ExtA_16 Latn.URA_Sun-ExtA_8
