PYTHON=python3


Latn.RUN_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.RUN/Mono_12/pdf_to_json_test_Latn.RUN_Mono_12.py" > "data/multilingual/Latn.RUN/Mono_12/pdf_to_json_test_Latn.RUN_Mono_12.json" 2>&1
Latn.RUN_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.RUN/Mono_16/pdf_to_json_test_Latn.RUN_Mono_16.py" > "data/multilingual/Latn.RUN/Mono_16/pdf_to_json_test_Latn.RUN_Mono_16.json" 2>&1
Latn.RUN_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.RUN/Mono_8/pdf_to_json_test_Latn.RUN_Mono_8.py" > "data/multilingual/Latn.RUN/Mono_8/pdf_to_json_test_Latn.RUN_Mono_8.json" 2>&1
Latn.RUN_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.RUN/Sans_12/pdf_to_json_test_Latn.RUN_Sans_12.py" > "data/multilingual/Latn.RUN/Sans_12/pdf_to_json_test_Latn.RUN_Sans_12.json" 2>&1
Latn.RUN_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.RUN/Sans_16/pdf_to_json_test_Latn.RUN_Sans_16.py" > "data/multilingual/Latn.RUN/Sans_16/pdf_to_json_test_Latn.RUN_Sans_16.json" 2>&1
Latn.RUN_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.RUN/Sans_8/pdf_to_json_test_Latn.RUN_Sans_8.py" > "data/multilingual/Latn.RUN/Sans_8/pdf_to_json_test_Latn.RUN_Sans_8.json" 2>&1
Latn.RUN_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.RUN/Serif_12/pdf_to_json_test_Latn.RUN_Serif_12.py" > "data/multilingual/Latn.RUN/Serif_12/pdf_to_json_test_Latn.RUN_Serif_12.json" 2>&1
Latn.RUN_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.RUN/Serif_16/pdf_to_json_test_Latn.RUN_Serif_16.py" > "data/multilingual/Latn.RUN/Serif_16/pdf_to_json_test_Latn.RUN_Serif_16.json" 2>&1
Latn.RUN_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.RUN/Serif_8/pdf_to_json_test_Latn.RUN_Serif_8.py" > "data/multilingual/Latn.RUN/Serif_8/pdf_to_json_test_Latn.RUN_Serif_8.json" 2>&1
Latn.RUN_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.RUN/Sun-ExtA_12/pdf_to_json_test_Latn.RUN_Sun-ExtA_12.py" > "data/multilingual/Latn.RUN/Sun-ExtA_12/pdf_to_json_test_Latn.RUN_Sun-ExtA_12.json" 2>&1
Latn.RUN_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.RUN/Sun-ExtA_16/pdf_to_json_test_Latn.RUN_Sun-ExtA_16.py" > "data/multilingual/Latn.RUN/Sun-ExtA_16/pdf_to_json_test_Latn.RUN_Sun-ExtA_16.json" 2>&1
Latn.RUN_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.RUN/Sun-ExtA_8/pdf_to_json_test_Latn.RUN_Sun-ExtA_8.py" > "data/multilingual/Latn.RUN/Sun-ExtA_8/pdf_to_json_test_Latn.RUN_Sun-ExtA_8.json" 2>&1


Latn.RUN_all : Latn.RUN_Mono_12 Latn.RUN_Mono_16 Latn.RUN_Mono_8 Latn.RUN_Sans_12 Latn.RUN_Sans_16 Latn.RUN_Sans_8 Latn.RUN_Serif_12 Latn.RUN_Serif_16 Latn.RUN_Serif_8 Latn.RUN_Sun-ExtA_12 Latn.RUN_Sun-ExtA_16 Latn.RUN_Sun-ExtA_8
