PYTHON=python3


Latn.KDH_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.KDH/Mono_12/pdf_to_json_test_Latn.KDH_Mono_12.py" > "data/multilingual/Latn.KDH/Mono_12/pdf_to_json_test_Latn.KDH_Mono_12.json" 2>&1
Latn.KDH_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.KDH/Mono_16/pdf_to_json_test_Latn.KDH_Mono_16.py" > "data/multilingual/Latn.KDH/Mono_16/pdf_to_json_test_Latn.KDH_Mono_16.json" 2>&1
Latn.KDH_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.KDH/Mono_8/pdf_to_json_test_Latn.KDH_Mono_8.py" > "data/multilingual/Latn.KDH/Mono_8/pdf_to_json_test_Latn.KDH_Mono_8.json" 2>&1
Latn.KDH_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.KDH/Sans_12/pdf_to_json_test_Latn.KDH_Sans_12.py" > "data/multilingual/Latn.KDH/Sans_12/pdf_to_json_test_Latn.KDH_Sans_12.json" 2>&1
Latn.KDH_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.KDH/Sans_16/pdf_to_json_test_Latn.KDH_Sans_16.py" > "data/multilingual/Latn.KDH/Sans_16/pdf_to_json_test_Latn.KDH_Sans_16.json" 2>&1
Latn.KDH_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.KDH/Sans_8/pdf_to_json_test_Latn.KDH_Sans_8.py" > "data/multilingual/Latn.KDH/Sans_8/pdf_to_json_test_Latn.KDH_Sans_8.json" 2>&1
Latn.KDH_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.KDH/Serif_12/pdf_to_json_test_Latn.KDH_Serif_12.py" > "data/multilingual/Latn.KDH/Serif_12/pdf_to_json_test_Latn.KDH_Serif_12.json" 2>&1
Latn.KDH_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.KDH/Serif_16/pdf_to_json_test_Latn.KDH_Serif_16.py" > "data/multilingual/Latn.KDH/Serif_16/pdf_to_json_test_Latn.KDH_Serif_16.json" 2>&1
Latn.KDH_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.KDH/Serif_8/pdf_to_json_test_Latn.KDH_Serif_8.py" > "data/multilingual/Latn.KDH/Serif_8/pdf_to_json_test_Latn.KDH_Serif_8.json" 2>&1
Latn.KDH_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.KDH/Sun-ExtA_12/pdf_to_json_test_Latn.KDH_Sun-ExtA_12.py" > "data/multilingual/Latn.KDH/Sun-ExtA_12/pdf_to_json_test_Latn.KDH_Sun-ExtA_12.json" 2>&1
Latn.KDH_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.KDH/Sun-ExtA_16/pdf_to_json_test_Latn.KDH_Sun-ExtA_16.py" > "data/multilingual/Latn.KDH/Sun-ExtA_16/pdf_to_json_test_Latn.KDH_Sun-ExtA_16.json" 2>&1
Latn.KDH_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.KDH/Sun-ExtA_8/pdf_to_json_test_Latn.KDH_Sun-ExtA_8.py" > "data/multilingual/Latn.KDH/Sun-ExtA_8/pdf_to_json_test_Latn.KDH_Sun-ExtA_8.json" 2>&1


Latn.KDH_all : Latn.KDH_Mono_12 Latn.KDH_Mono_16 Latn.KDH_Mono_8 Latn.KDH_Sans_12 Latn.KDH_Sans_16 Latn.KDH_Sans_8 Latn.KDH_Serif_12 Latn.KDH_Serif_16 Latn.KDH_Serif_8 Latn.KDH_Sun-ExtA_12 Latn.KDH_Sun-ExtA_16 Latn.KDH_Sun-ExtA_8
