PYTHON=python3


Latn.CBS_Mono_12:
	-$(PYTHON) data/multilingual/Latn.CBS/Mono_12/pdf_to_json_test_Latn.CBS_Mono_12.py > data/multilingual/Latn.CBS/Mono_12/pdf_to_json_test_Latn.CBS_Mono_12.json 2>&1
Latn.CBS_Mono_16:
	-$(PYTHON) data/multilingual/Latn.CBS/Mono_16/pdf_to_json_test_Latn.CBS_Mono_16.py > data/multilingual/Latn.CBS/Mono_16/pdf_to_json_test_Latn.CBS_Mono_16.json 2>&1
Latn.CBS_Mono_8:
	-$(PYTHON) data/multilingual/Latn.CBS/Mono_8/pdf_to_json_test_Latn.CBS_Mono_8.py > data/multilingual/Latn.CBS/Mono_8/pdf_to_json_test_Latn.CBS_Mono_8.json 2>&1
Latn.CBS_Sans_12:
	-$(PYTHON) data/multilingual/Latn.CBS/Sans_12/pdf_to_json_test_Latn.CBS_Sans_12.py > data/multilingual/Latn.CBS/Sans_12/pdf_to_json_test_Latn.CBS_Sans_12.json 2>&1
Latn.CBS_Sans_16:
	-$(PYTHON) data/multilingual/Latn.CBS/Sans_16/pdf_to_json_test_Latn.CBS_Sans_16.py > data/multilingual/Latn.CBS/Sans_16/pdf_to_json_test_Latn.CBS_Sans_16.json 2>&1
Latn.CBS_Sans_8:
	-$(PYTHON) data/multilingual/Latn.CBS/Sans_8/pdf_to_json_test_Latn.CBS_Sans_8.py > data/multilingual/Latn.CBS/Sans_8/pdf_to_json_test_Latn.CBS_Sans_8.json 2>&1
Latn.CBS_Serif_12:
	-$(PYTHON) data/multilingual/Latn.CBS/Serif_12/pdf_to_json_test_Latn.CBS_Serif_12.py > data/multilingual/Latn.CBS/Serif_12/pdf_to_json_test_Latn.CBS_Serif_12.json 2>&1
Latn.CBS_Serif_16:
	-$(PYTHON) data/multilingual/Latn.CBS/Serif_16/pdf_to_json_test_Latn.CBS_Serif_16.py > data/multilingual/Latn.CBS/Serif_16/pdf_to_json_test_Latn.CBS_Serif_16.json 2>&1
Latn.CBS_Serif_8:
	-$(PYTHON) data/multilingual/Latn.CBS/Serif_8/pdf_to_json_test_Latn.CBS_Serif_8.py > data/multilingual/Latn.CBS/Serif_8/pdf_to_json_test_Latn.CBS_Serif_8.json 2>&1
Latn.CBS_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.CBS/Sun-ExtA_12/pdf_to_json_test_Latn.CBS_Sun-ExtA_12.py > data/multilingual/Latn.CBS/Sun-ExtA_12/pdf_to_json_test_Latn.CBS_Sun-ExtA_12.json 2>&1
Latn.CBS_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.CBS/Sun-ExtA_16/pdf_to_json_test_Latn.CBS_Sun-ExtA_16.py > data/multilingual/Latn.CBS/Sun-ExtA_16/pdf_to_json_test_Latn.CBS_Sun-ExtA_16.json 2>&1
Latn.CBS_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.CBS/Sun-ExtA_8/pdf_to_json_test_Latn.CBS_Sun-ExtA_8.py > data/multilingual/Latn.CBS/Sun-ExtA_8/pdf_to_json_test_Latn.CBS_Sun-ExtA_8.json 2>&1


Latn.CBS_all : Latn.CBS_Mono_12 Latn.CBS_Mono_16 Latn.CBS_Mono_8 Latn.CBS_Sans_12 Latn.CBS_Sans_16 Latn.CBS_Sans_8 Latn.CBS_Serif_12 Latn.CBS_Serif_16 Latn.CBS_Serif_8 Latn.CBS_Sun-ExtA_12 Latn.CBS_Sun-ExtA_16 Latn.CBS_Sun-ExtA_8
