PYTHON=python3


Cyrl.GLD_Mono_12:
	-$(PYTHON) data/multilingual/Cyrl.GLD/Mono_12/pdf_to_json_test_Cyrl.GLD_Mono_12.py > data/multilingual/Cyrl.GLD/Mono_12/pdf_to_json_test_Cyrl.GLD_Mono_12.json 2>&1
Cyrl.GLD_Mono_16:
	-$(PYTHON) data/multilingual/Cyrl.GLD/Mono_16/pdf_to_json_test_Cyrl.GLD_Mono_16.py > data/multilingual/Cyrl.GLD/Mono_16/pdf_to_json_test_Cyrl.GLD_Mono_16.json 2>&1
Cyrl.GLD_Mono_8:
	-$(PYTHON) data/multilingual/Cyrl.GLD/Mono_8/pdf_to_json_test_Cyrl.GLD_Mono_8.py > data/multilingual/Cyrl.GLD/Mono_8/pdf_to_json_test_Cyrl.GLD_Mono_8.json 2>&1
Cyrl.GLD_Sans_12:
	-$(PYTHON) data/multilingual/Cyrl.GLD/Sans_12/pdf_to_json_test_Cyrl.GLD_Sans_12.py > data/multilingual/Cyrl.GLD/Sans_12/pdf_to_json_test_Cyrl.GLD_Sans_12.json 2>&1
Cyrl.GLD_Sans_16:
	-$(PYTHON) data/multilingual/Cyrl.GLD/Sans_16/pdf_to_json_test_Cyrl.GLD_Sans_16.py > data/multilingual/Cyrl.GLD/Sans_16/pdf_to_json_test_Cyrl.GLD_Sans_16.json 2>&1
Cyrl.GLD_Sans_8:
	-$(PYTHON) data/multilingual/Cyrl.GLD/Sans_8/pdf_to_json_test_Cyrl.GLD_Sans_8.py > data/multilingual/Cyrl.GLD/Sans_8/pdf_to_json_test_Cyrl.GLD_Sans_8.json 2>&1
Cyrl.GLD_Serif_12:
	-$(PYTHON) data/multilingual/Cyrl.GLD/Serif_12/pdf_to_json_test_Cyrl.GLD_Serif_12.py > data/multilingual/Cyrl.GLD/Serif_12/pdf_to_json_test_Cyrl.GLD_Serif_12.json 2>&1
Cyrl.GLD_Serif_16:
	-$(PYTHON) data/multilingual/Cyrl.GLD/Serif_16/pdf_to_json_test_Cyrl.GLD_Serif_16.py > data/multilingual/Cyrl.GLD/Serif_16/pdf_to_json_test_Cyrl.GLD_Serif_16.json 2>&1
Cyrl.GLD_Serif_8:
	-$(PYTHON) data/multilingual/Cyrl.GLD/Serif_8/pdf_to_json_test_Cyrl.GLD_Serif_8.py > data/multilingual/Cyrl.GLD/Serif_8/pdf_to_json_test_Cyrl.GLD_Serif_8.json 2>&1
Cyrl.GLD_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Cyrl.GLD/Sun-ExtA_12/pdf_to_json_test_Cyrl.GLD_Sun-ExtA_12.py > data/multilingual/Cyrl.GLD/Sun-ExtA_12/pdf_to_json_test_Cyrl.GLD_Sun-ExtA_12.json 2>&1
Cyrl.GLD_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Cyrl.GLD/Sun-ExtA_16/pdf_to_json_test_Cyrl.GLD_Sun-ExtA_16.py > data/multilingual/Cyrl.GLD/Sun-ExtA_16/pdf_to_json_test_Cyrl.GLD_Sun-ExtA_16.json 2>&1
Cyrl.GLD_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Cyrl.GLD/Sun-ExtA_8/pdf_to_json_test_Cyrl.GLD_Sun-ExtA_8.py > data/multilingual/Cyrl.GLD/Sun-ExtA_8/pdf_to_json_test_Cyrl.GLD_Sun-ExtA_8.json 2>&1


Cyrl.GLD_all : Cyrl.GLD_Mono_12 Cyrl.GLD_Mono_16 Cyrl.GLD_Mono_8 Cyrl.GLD_Sans_12 Cyrl.GLD_Sans_16 Cyrl.GLD_Sans_8 Cyrl.GLD_Serif_12 Cyrl.GLD_Serif_16 Cyrl.GLD_Serif_8 Cyrl.GLD_Sun-ExtA_12 Cyrl.GLD_Sun-ExtA_16 Cyrl.GLD_Sun-ExtA_8
