PYTHON=python3


Hebr.HEB_Mono_12:
	-$(PYTHON) data/multilingual/Hebr.HEB/Mono_12/pdf_to_json_test_Hebr.HEB_Mono_12.py > data/multilingual/Hebr.HEB/Mono_12/pdf_to_json_test_Hebr.HEB_Mono_12.json 2>&1
Hebr.HEB_Mono_16:
	-$(PYTHON) data/multilingual/Hebr.HEB/Mono_16/pdf_to_json_test_Hebr.HEB_Mono_16.py > data/multilingual/Hebr.HEB/Mono_16/pdf_to_json_test_Hebr.HEB_Mono_16.json 2>&1
Hebr.HEB_Mono_8:
	-$(PYTHON) data/multilingual/Hebr.HEB/Mono_8/pdf_to_json_test_Hebr.HEB_Mono_8.py > data/multilingual/Hebr.HEB/Mono_8/pdf_to_json_test_Hebr.HEB_Mono_8.json 2>&1
Hebr.HEB_Sans_12:
	-$(PYTHON) data/multilingual/Hebr.HEB/Sans_12/pdf_to_json_test_Hebr.HEB_Sans_12.py > data/multilingual/Hebr.HEB/Sans_12/pdf_to_json_test_Hebr.HEB_Sans_12.json 2>&1
Hebr.HEB_Sans_16:
	-$(PYTHON) data/multilingual/Hebr.HEB/Sans_16/pdf_to_json_test_Hebr.HEB_Sans_16.py > data/multilingual/Hebr.HEB/Sans_16/pdf_to_json_test_Hebr.HEB_Sans_16.json 2>&1
Hebr.HEB_Sans_8:
	-$(PYTHON) data/multilingual/Hebr.HEB/Sans_8/pdf_to_json_test_Hebr.HEB_Sans_8.py > data/multilingual/Hebr.HEB/Sans_8/pdf_to_json_test_Hebr.HEB_Sans_8.json 2>&1
Hebr.HEB_Serif_12:
	-$(PYTHON) data/multilingual/Hebr.HEB/Serif_12/pdf_to_json_test_Hebr.HEB_Serif_12.py > data/multilingual/Hebr.HEB/Serif_12/pdf_to_json_test_Hebr.HEB_Serif_12.json 2>&1
Hebr.HEB_Serif_16:
	-$(PYTHON) data/multilingual/Hebr.HEB/Serif_16/pdf_to_json_test_Hebr.HEB_Serif_16.py > data/multilingual/Hebr.HEB/Serif_16/pdf_to_json_test_Hebr.HEB_Serif_16.json 2>&1
Hebr.HEB_Serif_8:
	-$(PYTHON) data/multilingual/Hebr.HEB/Serif_8/pdf_to_json_test_Hebr.HEB_Serif_8.py > data/multilingual/Hebr.HEB/Serif_8/pdf_to_json_test_Hebr.HEB_Serif_8.json 2>&1
Hebr.HEB_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Hebr.HEB/Sun-ExtA_12/pdf_to_json_test_Hebr.HEB_Sun-ExtA_12.py > data/multilingual/Hebr.HEB/Sun-ExtA_12/pdf_to_json_test_Hebr.HEB_Sun-ExtA_12.json 2>&1
Hebr.HEB_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Hebr.HEB/Sun-ExtA_16/pdf_to_json_test_Hebr.HEB_Sun-ExtA_16.py > data/multilingual/Hebr.HEB/Sun-ExtA_16/pdf_to_json_test_Hebr.HEB_Sun-ExtA_16.json 2>&1
Hebr.HEB_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Hebr.HEB/Sun-ExtA_8/pdf_to_json_test_Hebr.HEB_Sun-ExtA_8.py > data/multilingual/Hebr.HEB/Sun-ExtA_8/pdf_to_json_test_Hebr.HEB_Sun-ExtA_8.json 2>&1


Hebr.HEB_all : Hebr.HEB_Mono_12 Hebr.HEB_Mono_16 Hebr.HEB_Mono_8 Hebr.HEB_Sans_12 Hebr.HEB_Sans_16 Hebr.HEB_Sans_8 Hebr.HEB_Serif_12 Hebr.HEB_Serif_16 Hebr.HEB_Serif_8 Hebr.HEB_Sun-ExtA_12 Hebr.HEB_Sun-ExtA_16 Hebr.HEB_Sun-ExtA_8
