PYTHON=python3


Latn.TSN_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.TSN/Mono_12/pdf_to_json_test_Latn.TSN_Mono_12.py" > "data/multilingual/Latn.TSN/Mono_12/pdf_to_json_test_Latn.TSN_Mono_12.json" 2>&1
Latn.TSN_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.TSN/Mono_16/pdf_to_json_test_Latn.TSN_Mono_16.py" > "data/multilingual/Latn.TSN/Mono_16/pdf_to_json_test_Latn.TSN_Mono_16.json" 2>&1
Latn.TSN_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.TSN/Mono_8/pdf_to_json_test_Latn.TSN_Mono_8.py" > "data/multilingual/Latn.TSN/Mono_8/pdf_to_json_test_Latn.TSN_Mono_8.json" 2>&1
Latn.TSN_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.TSN/Sans_12/pdf_to_json_test_Latn.TSN_Sans_12.py" > "data/multilingual/Latn.TSN/Sans_12/pdf_to_json_test_Latn.TSN_Sans_12.json" 2>&1
Latn.TSN_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.TSN/Sans_16/pdf_to_json_test_Latn.TSN_Sans_16.py" > "data/multilingual/Latn.TSN/Sans_16/pdf_to_json_test_Latn.TSN_Sans_16.json" 2>&1
Latn.TSN_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.TSN/Sans_8/pdf_to_json_test_Latn.TSN_Sans_8.py" > "data/multilingual/Latn.TSN/Sans_8/pdf_to_json_test_Latn.TSN_Sans_8.json" 2>&1
Latn.TSN_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.TSN/Serif_12/pdf_to_json_test_Latn.TSN_Serif_12.py" > "data/multilingual/Latn.TSN/Serif_12/pdf_to_json_test_Latn.TSN_Serif_12.json" 2>&1
Latn.TSN_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.TSN/Serif_16/pdf_to_json_test_Latn.TSN_Serif_16.py" > "data/multilingual/Latn.TSN/Serif_16/pdf_to_json_test_Latn.TSN_Serif_16.json" 2>&1
Latn.TSN_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.TSN/Serif_8/pdf_to_json_test_Latn.TSN_Serif_8.py" > "data/multilingual/Latn.TSN/Serif_8/pdf_to_json_test_Latn.TSN_Serif_8.json" 2>&1
Latn.TSN_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.TSN/Sun-ExtA_12/pdf_to_json_test_Latn.TSN_Sun-ExtA_12.py" > "data/multilingual/Latn.TSN/Sun-ExtA_12/pdf_to_json_test_Latn.TSN_Sun-ExtA_12.json" 2>&1
Latn.TSN_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.TSN/Sun-ExtA_16/pdf_to_json_test_Latn.TSN_Sun-ExtA_16.py" > "data/multilingual/Latn.TSN/Sun-ExtA_16/pdf_to_json_test_Latn.TSN_Sun-ExtA_16.json" 2>&1
Latn.TSN_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.TSN/Sun-ExtA_8/pdf_to_json_test_Latn.TSN_Sun-ExtA_8.py" > "data/multilingual/Latn.TSN/Sun-ExtA_8/pdf_to_json_test_Latn.TSN_Sun-ExtA_8.json" 2>&1


Latn.TSN_all : Latn.TSN_Mono_12 Latn.TSN_Mono_16 Latn.TSN_Mono_8 Latn.TSN_Sans_12 Latn.TSN_Sans_16 Latn.TSN_Sans_8 Latn.TSN_Serif_12 Latn.TSN_Serif_16 Latn.TSN_Serif_8 Latn.TSN_Sun-ExtA_12 Latn.TSN_Sun-ExtA_16 Latn.TSN_Sun-ExtA_8
