PYTHON=python3


Latn.ZTU_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.ZTU/Mono_12/pdf_to_json_test_Latn.ZTU_Mono_12.py" > "data/multilingual/Latn.ZTU/Mono_12/pdf_to_json_test_Latn.ZTU_Mono_12.json" 2>&1
Latn.ZTU_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.ZTU/Mono_16/pdf_to_json_test_Latn.ZTU_Mono_16.py" > "data/multilingual/Latn.ZTU/Mono_16/pdf_to_json_test_Latn.ZTU_Mono_16.json" 2>&1
Latn.ZTU_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.ZTU/Mono_8/pdf_to_json_test_Latn.ZTU_Mono_8.py" > "data/multilingual/Latn.ZTU/Mono_8/pdf_to_json_test_Latn.ZTU_Mono_8.json" 2>&1
Latn.ZTU_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.ZTU/Sans_12/pdf_to_json_test_Latn.ZTU_Sans_12.py" > "data/multilingual/Latn.ZTU/Sans_12/pdf_to_json_test_Latn.ZTU_Sans_12.json" 2>&1
Latn.ZTU_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.ZTU/Sans_16/pdf_to_json_test_Latn.ZTU_Sans_16.py" > "data/multilingual/Latn.ZTU/Sans_16/pdf_to_json_test_Latn.ZTU_Sans_16.json" 2>&1
Latn.ZTU_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.ZTU/Sans_8/pdf_to_json_test_Latn.ZTU_Sans_8.py" > "data/multilingual/Latn.ZTU/Sans_8/pdf_to_json_test_Latn.ZTU_Sans_8.json" 2>&1
Latn.ZTU_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.ZTU/Serif_12/pdf_to_json_test_Latn.ZTU_Serif_12.py" > "data/multilingual/Latn.ZTU/Serif_12/pdf_to_json_test_Latn.ZTU_Serif_12.json" 2>&1
Latn.ZTU_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.ZTU/Serif_16/pdf_to_json_test_Latn.ZTU_Serif_16.py" > "data/multilingual/Latn.ZTU/Serif_16/pdf_to_json_test_Latn.ZTU_Serif_16.json" 2>&1
Latn.ZTU_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.ZTU/Serif_8/pdf_to_json_test_Latn.ZTU_Serif_8.py" > "data/multilingual/Latn.ZTU/Serif_8/pdf_to_json_test_Latn.ZTU_Serif_8.json" 2>&1
Latn.ZTU_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.ZTU/Sun-ExtA_12/pdf_to_json_test_Latn.ZTU_Sun-ExtA_12.py" > "data/multilingual/Latn.ZTU/Sun-ExtA_12/pdf_to_json_test_Latn.ZTU_Sun-ExtA_12.json" 2>&1
Latn.ZTU_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.ZTU/Sun-ExtA_16/pdf_to_json_test_Latn.ZTU_Sun-ExtA_16.py" > "data/multilingual/Latn.ZTU/Sun-ExtA_16/pdf_to_json_test_Latn.ZTU_Sun-ExtA_16.json" 2>&1
Latn.ZTU_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.ZTU/Sun-ExtA_8/pdf_to_json_test_Latn.ZTU_Sun-ExtA_8.py" > "data/multilingual/Latn.ZTU/Sun-ExtA_8/pdf_to_json_test_Latn.ZTU_Sun-ExtA_8.json" 2>&1


Latn.ZTU_all : Latn.ZTU_Mono_12 Latn.ZTU_Mono_16 Latn.ZTU_Mono_8 Latn.ZTU_Sans_12 Latn.ZTU_Sans_16 Latn.ZTU_Sans_8 Latn.ZTU_Serif_12 Latn.ZTU_Serif_16 Latn.ZTU_Serif_8 Latn.ZTU_Sun-ExtA_12 Latn.ZTU_Sun-ExtA_16 Latn.ZTU_Sun-ExtA_8
