PYTHON=python3


Latn.RAR_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.RAR/Mono_12/pdf_to_json_test_Latn.RAR_Mono_12.py" > "data/multilingual/Latn.RAR/Mono_12/pdf_to_json_test_Latn.RAR_Mono_12.json" 2>&1
Latn.RAR_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.RAR/Mono_16/pdf_to_json_test_Latn.RAR_Mono_16.py" > "data/multilingual/Latn.RAR/Mono_16/pdf_to_json_test_Latn.RAR_Mono_16.json" 2>&1
Latn.RAR_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.RAR/Mono_8/pdf_to_json_test_Latn.RAR_Mono_8.py" > "data/multilingual/Latn.RAR/Mono_8/pdf_to_json_test_Latn.RAR_Mono_8.json" 2>&1
Latn.RAR_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.RAR/Sans_12/pdf_to_json_test_Latn.RAR_Sans_12.py" > "data/multilingual/Latn.RAR/Sans_12/pdf_to_json_test_Latn.RAR_Sans_12.json" 2>&1
Latn.RAR_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.RAR/Sans_16/pdf_to_json_test_Latn.RAR_Sans_16.py" > "data/multilingual/Latn.RAR/Sans_16/pdf_to_json_test_Latn.RAR_Sans_16.json" 2>&1
Latn.RAR_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.RAR/Sans_8/pdf_to_json_test_Latn.RAR_Sans_8.py" > "data/multilingual/Latn.RAR/Sans_8/pdf_to_json_test_Latn.RAR_Sans_8.json" 2>&1
Latn.RAR_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.RAR/Serif_12/pdf_to_json_test_Latn.RAR_Serif_12.py" > "data/multilingual/Latn.RAR/Serif_12/pdf_to_json_test_Latn.RAR_Serif_12.json" 2>&1
Latn.RAR_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.RAR/Serif_16/pdf_to_json_test_Latn.RAR_Serif_16.py" > "data/multilingual/Latn.RAR/Serif_16/pdf_to_json_test_Latn.RAR_Serif_16.json" 2>&1
Latn.RAR_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.RAR/Serif_8/pdf_to_json_test_Latn.RAR_Serif_8.py" > "data/multilingual/Latn.RAR/Serif_8/pdf_to_json_test_Latn.RAR_Serif_8.json" 2>&1
Latn.RAR_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.RAR/Sun-ExtA_12/pdf_to_json_test_Latn.RAR_Sun-ExtA_12.py" > "data/multilingual/Latn.RAR/Sun-ExtA_12/pdf_to_json_test_Latn.RAR_Sun-ExtA_12.json" 2>&1
Latn.RAR_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.RAR/Sun-ExtA_16/pdf_to_json_test_Latn.RAR_Sun-ExtA_16.py" > "data/multilingual/Latn.RAR/Sun-ExtA_16/pdf_to_json_test_Latn.RAR_Sun-ExtA_16.json" 2>&1
Latn.RAR_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.RAR/Sun-ExtA_8/pdf_to_json_test_Latn.RAR_Sun-ExtA_8.py" > "data/multilingual/Latn.RAR/Sun-ExtA_8/pdf_to_json_test_Latn.RAR_Sun-ExtA_8.json" 2>&1


Latn.RAR_all : Latn.RAR_Mono_12 Latn.RAR_Mono_16 Latn.RAR_Mono_8 Latn.RAR_Sans_12 Latn.RAR_Sans_16 Latn.RAR_Sans_8 Latn.RAR_Serif_12 Latn.RAR_Serif_16 Latn.RAR_Serif_8 Latn.RAR_Sun-ExtA_12 Latn.RAR_Sun-ExtA_16 Latn.RAR_Sun-ExtA_8
