PYTHON=python3


Latn.CFM_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.CFM/Mono_12/pdf_to_json_test_Latn.CFM_Mono_12.py" > "data/multilingual/Latn.CFM/Mono_12/pdf_to_json_test_Latn.CFM_Mono_12.json" 2>&1
Latn.CFM_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.CFM/Mono_16/pdf_to_json_test_Latn.CFM_Mono_16.py" > "data/multilingual/Latn.CFM/Mono_16/pdf_to_json_test_Latn.CFM_Mono_16.json" 2>&1
Latn.CFM_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.CFM/Mono_8/pdf_to_json_test_Latn.CFM_Mono_8.py" > "data/multilingual/Latn.CFM/Mono_8/pdf_to_json_test_Latn.CFM_Mono_8.json" 2>&1
Latn.CFM_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.CFM/Sans_12/pdf_to_json_test_Latn.CFM_Sans_12.py" > "data/multilingual/Latn.CFM/Sans_12/pdf_to_json_test_Latn.CFM_Sans_12.json" 2>&1
Latn.CFM_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.CFM/Sans_16/pdf_to_json_test_Latn.CFM_Sans_16.py" > "data/multilingual/Latn.CFM/Sans_16/pdf_to_json_test_Latn.CFM_Sans_16.json" 2>&1
Latn.CFM_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.CFM/Sans_8/pdf_to_json_test_Latn.CFM_Sans_8.py" > "data/multilingual/Latn.CFM/Sans_8/pdf_to_json_test_Latn.CFM_Sans_8.json" 2>&1
Latn.CFM_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.CFM/Serif_12/pdf_to_json_test_Latn.CFM_Serif_12.py" > "data/multilingual/Latn.CFM/Serif_12/pdf_to_json_test_Latn.CFM_Serif_12.json" 2>&1
Latn.CFM_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.CFM/Serif_16/pdf_to_json_test_Latn.CFM_Serif_16.py" > "data/multilingual/Latn.CFM/Serif_16/pdf_to_json_test_Latn.CFM_Serif_16.json" 2>&1
Latn.CFM_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.CFM/Serif_8/pdf_to_json_test_Latn.CFM_Serif_8.py" > "data/multilingual/Latn.CFM/Serif_8/pdf_to_json_test_Latn.CFM_Serif_8.json" 2>&1
Latn.CFM_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.CFM/Sun-ExtA_12/pdf_to_json_test_Latn.CFM_Sun-ExtA_12.py" > "data/multilingual/Latn.CFM/Sun-ExtA_12/pdf_to_json_test_Latn.CFM_Sun-ExtA_12.json" 2>&1
Latn.CFM_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.CFM/Sun-ExtA_16/pdf_to_json_test_Latn.CFM_Sun-ExtA_16.py" > "data/multilingual/Latn.CFM/Sun-ExtA_16/pdf_to_json_test_Latn.CFM_Sun-ExtA_16.json" 2>&1
Latn.CFM_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.CFM/Sun-ExtA_8/pdf_to_json_test_Latn.CFM_Sun-ExtA_8.py" > "data/multilingual/Latn.CFM/Sun-ExtA_8/pdf_to_json_test_Latn.CFM_Sun-ExtA_8.json" 2>&1


Latn.CFM_all : Latn.CFM_Mono_12 Latn.CFM_Mono_16 Latn.CFM_Mono_8 Latn.CFM_Sans_12 Latn.CFM_Sans_16 Latn.CFM_Sans_8 Latn.CFM_Serif_12 Latn.CFM_Serif_16 Latn.CFM_Serif_8 Latn.CFM_Sun-ExtA_12 Latn.CFM_Sun-ExtA_16 Latn.CFM_Sun-ExtA_8
