PYTHON=python3


Cyrl.UKR_Mono_12:
	-$(PYTHON) "data/multilingual/Cyrl.UKR/Mono_12/pdf_to_json_test_Cyrl.UKR_Mono_12.py" > "data/multilingual/Cyrl.UKR/Mono_12/pdf_to_json_test_Cyrl.UKR_Mono_12.json" 2>&1
Cyrl.UKR_Mono_16:
	-$(PYTHON) "data/multilingual/Cyrl.UKR/Mono_16/pdf_to_json_test_Cyrl.UKR_Mono_16.py" > "data/multilingual/Cyrl.UKR/Mono_16/pdf_to_json_test_Cyrl.UKR_Mono_16.json" 2>&1
Cyrl.UKR_Mono_8:
	-$(PYTHON) "data/multilingual/Cyrl.UKR/Mono_8/pdf_to_json_test_Cyrl.UKR_Mono_8.py" > "data/multilingual/Cyrl.UKR/Mono_8/pdf_to_json_test_Cyrl.UKR_Mono_8.json" 2>&1
Cyrl.UKR_Sans_12:
	-$(PYTHON) "data/multilingual/Cyrl.UKR/Sans_12/pdf_to_json_test_Cyrl.UKR_Sans_12.py" > "data/multilingual/Cyrl.UKR/Sans_12/pdf_to_json_test_Cyrl.UKR_Sans_12.json" 2>&1
Cyrl.UKR_Sans_16:
	-$(PYTHON) "data/multilingual/Cyrl.UKR/Sans_16/pdf_to_json_test_Cyrl.UKR_Sans_16.py" > "data/multilingual/Cyrl.UKR/Sans_16/pdf_to_json_test_Cyrl.UKR_Sans_16.json" 2>&1
Cyrl.UKR_Sans_8:
	-$(PYTHON) "data/multilingual/Cyrl.UKR/Sans_8/pdf_to_json_test_Cyrl.UKR_Sans_8.py" > "data/multilingual/Cyrl.UKR/Sans_8/pdf_to_json_test_Cyrl.UKR_Sans_8.json" 2>&1
Cyrl.UKR_Serif_12:
	-$(PYTHON) "data/multilingual/Cyrl.UKR/Serif_12/pdf_to_json_test_Cyrl.UKR_Serif_12.py" > "data/multilingual/Cyrl.UKR/Serif_12/pdf_to_json_test_Cyrl.UKR_Serif_12.json" 2>&1
Cyrl.UKR_Serif_16:
	-$(PYTHON) "data/multilingual/Cyrl.UKR/Serif_16/pdf_to_json_test_Cyrl.UKR_Serif_16.py" > "data/multilingual/Cyrl.UKR/Serif_16/pdf_to_json_test_Cyrl.UKR_Serif_16.json" 2>&1
Cyrl.UKR_Serif_8:
	-$(PYTHON) "data/multilingual/Cyrl.UKR/Serif_8/pdf_to_json_test_Cyrl.UKR_Serif_8.py" > "data/multilingual/Cyrl.UKR/Serif_8/pdf_to_json_test_Cyrl.UKR_Serif_8.json" 2>&1
Cyrl.UKR_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Cyrl.UKR/Sun-ExtA_12/pdf_to_json_test_Cyrl.UKR_Sun-ExtA_12.py" > "data/multilingual/Cyrl.UKR/Sun-ExtA_12/pdf_to_json_test_Cyrl.UKR_Sun-ExtA_12.json" 2>&1
Cyrl.UKR_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Cyrl.UKR/Sun-ExtA_16/pdf_to_json_test_Cyrl.UKR_Sun-ExtA_16.py" > "data/multilingual/Cyrl.UKR/Sun-ExtA_16/pdf_to_json_test_Cyrl.UKR_Sun-ExtA_16.json" 2>&1
Cyrl.UKR_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Cyrl.UKR/Sun-ExtA_8/pdf_to_json_test_Cyrl.UKR_Sun-ExtA_8.py" > "data/multilingual/Cyrl.UKR/Sun-ExtA_8/pdf_to_json_test_Cyrl.UKR_Sun-ExtA_8.json" 2>&1


Cyrl.UKR_all : Cyrl.UKR_Mono_12 Cyrl.UKR_Mono_16 Cyrl.UKR_Mono_8 Cyrl.UKR_Sans_12 Cyrl.UKR_Sans_16 Cyrl.UKR_Sans_8 Cyrl.UKR_Serif_12 Cyrl.UKR_Serif_16 Cyrl.UKR_Serif_8 Cyrl.UKR_Sun-ExtA_12 Cyrl.UKR_Sun-ExtA_16 Cyrl.UKR_Sun-ExtA_8
