PYTHON=python3


Cyrl.TGK_Mono_12:
	-$(PYTHON) data/multilingual/Cyrl.TGK/Mono_12/pdf_to_json_test_Cyrl.TGK_Mono_12.py > data/multilingual/Cyrl.TGK/Mono_12/pdf_to_json_test_Cyrl.TGK_Mono_12.json 2>&1
Cyrl.TGK_Mono_16:
	-$(PYTHON) data/multilingual/Cyrl.TGK/Mono_16/pdf_to_json_test_Cyrl.TGK_Mono_16.py > data/multilingual/Cyrl.TGK/Mono_16/pdf_to_json_test_Cyrl.TGK_Mono_16.json 2>&1
Cyrl.TGK_Mono_8:
	-$(PYTHON) data/multilingual/Cyrl.TGK/Mono_8/pdf_to_json_test_Cyrl.TGK_Mono_8.py > data/multilingual/Cyrl.TGK/Mono_8/pdf_to_json_test_Cyrl.TGK_Mono_8.json 2>&1
Cyrl.TGK_Sans_12:
	-$(PYTHON) data/multilingual/Cyrl.TGK/Sans_12/pdf_to_json_test_Cyrl.TGK_Sans_12.py > data/multilingual/Cyrl.TGK/Sans_12/pdf_to_json_test_Cyrl.TGK_Sans_12.json 2>&1
Cyrl.TGK_Sans_16:
	-$(PYTHON) data/multilingual/Cyrl.TGK/Sans_16/pdf_to_json_test_Cyrl.TGK_Sans_16.py > data/multilingual/Cyrl.TGK/Sans_16/pdf_to_json_test_Cyrl.TGK_Sans_16.json 2>&1
Cyrl.TGK_Sans_8:
	-$(PYTHON) data/multilingual/Cyrl.TGK/Sans_8/pdf_to_json_test_Cyrl.TGK_Sans_8.py > data/multilingual/Cyrl.TGK/Sans_8/pdf_to_json_test_Cyrl.TGK_Sans_8.json 2>&1
Cyrl.TGK_Serif_12:
	-$(PYTHON) data/multilingual/Cyrl.TGK/Serif_12/pdf_to_json_test_Cyrl.TGK_Serif_12.py > data/multilingual/Cyrl.TGK/Serif_12/pdf_to_json_test_Cyrl.TGK_Serif_12.json 2>&1
Cyrl.TGK_Serif_16:
	-$(PYTHON) data/multilingual/Cyrl.TGK/Serif_16/pdf_to_json_test_Cyrl.TGK_Serif_16.py > data/multilingual/Cyrl.TGK/Serif_16/pdf_to_json_test_Cyrl.TGK_Serif_16.json 2>&1
Cyrl.TGK_Serif_8:
	-$(PYTHON) data/multilingual/Cyrl.TGK/Serif_8/pdf_to_json_test_Cyrl.TGK_Serif_8.py > data/multilingual/Cyrl.TGK/Serif_8/pdf_to_json_test_Cyrl.TGK_Serif_8.json 2>&1
Cyrl.TGK_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Cyrl.TGK/Sun-ExtA_12/pdf_to_json_test_Cyrl.TGK_Sun-ExtA_12.py > data/multilingual/Cyrl.TGK/Sun-ExtA_12/pdf_to_json_test_Cyrl.TGK_Sun-ExtA_12.json 2>&1
Cyrl.TGK_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Cyrl.TGK/Sun-ExtA_16/pdf_to_json_test_Cyrl.TGK_Sun-ExtA_16.py > data/multilingual/Cyrl.TGK/Sun-ExtA_16/pdf_to_json_test_Cyrl.TGK_Sun-ExtA_16.json 2>&1
Cyrl.TGK_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Cyrl.TGK/Sun-ExtA_8/pdf_to_json_test_Cyrl.TGK_Sun-ExtA_8.py > data/multilingual/Cyrl.TGK/Sun-ExtA_8/pdf_to_json_test_Cyrl.TGK_Sun-ExtA_8.json 2>&1


Cyrl.TGK_all : Cyrl.TGK_Mono_12 Cyrl.TGK_Mono_16 Cyrl.TGK_Mono_8 Cyrl.TGK_Sans_12 Cyrl.TGK_Sans_16 Cyrl.TGK_Sans_8 Cyrl.TGK_Serif_12 Cyrl.TGK_Serif_16 Cyrl.TGK_Serif_8 Cyrl.TGK_Sun-ExtA_12 Cyrl.TGK_Sun-ExtA_16 Cyrl.TGK_Sun-ExtA_8
