PYTHON=python3


Khmr.KHM_Mono_12:
	-$(PYTHON) "data/multilingual/Khmr.KHM/Mono_12/pdf_to_json_test_Khmr.KHM_Mono_12.py" > "data/multilingual/Khmr.KHM/Mono_12/pdf_to_json_test_Khmr.KHM_Mono_12.json" 2>&1
Khmr.KHM_Mono_16:
	-$(PYTHON) "data/multilingual/Khmr.KHM/Mono_16/pdf_to_json_test_Khmr.KHM_Mono_16.py" > "data/multilingual/Khmr.KHM/Mono_16/pdf_to_json_test_Khmr.KHM_Mono_16.json" 2>&1
Khmr.KHM_Mono_8:
	-$(PYTHON) "data/multilingual/Khmr.KHM/Mono_8/pdf_to_json_test_Khmr.KHM_Mono_8.py" > "data/multilingual/Khmr.KHM/Mono_8/pdf_to_json_test_Khmr.KHM_Mono_8.json" 2>&1
Khmr.KHM_Sans_12:
	-$(PYTHON) "data/multilingual/Khmr.KHM/Sans_12/pdf_to_json_test_Khmr.KHM_Sans_12.py" > "data/multilingual/Khmr.KHM/Sans_12/pdf_to_json_test_Khmr.KHM_Sans_12.json" 2>&1
Khmr.KHM_Sans_16:
	-$(PYTHON) "data/multilingual/Khmr.KHM/Sans_16/pdf_to_json_test_Khmr.KHM_Sans_16.py" > "data/multilingual/Khmr.KHM/Sans_16/pdf_to_json_test_Khmr.KHM_Sans_16.json" 2>&1
Khmr.KHM_Sans_8:
	-$(PYTHON) "data/multilingual/Khmr.KHM/Sans_8/pdf_to_json_test_Khmr.KHM_Sans_8.py" > "data/multilingual/Khmr.KHM/Sans_8/pdf_to_json_test_Khmr.KHM_Sans_8.json" 2>&1
Khmr.KHM_Serif_12:
	-$(PYTHON) "data/multilingual/Khmr.KHM/Serif_12/pdf_to_json_test_Khmr.KHM_Serif_12.py" > "data/multilingual/Khmr.KHM/Serif_12/pdf_to_json_test_Khmr.KHM_Serif_12.json" 2>&1
Khmr.KHM_Serif_16:
	-$(PYTHON) "data/multilingual/Khmr.KHM/Serif_16/pdf_to_json_test_Khmr.KHM_Serif_16.py" > "data/multilingual/Khmr.KHM/Serif_16/pdf_to_json_test_Khmr.KHM_Serif_16.json" 2>&1
Khmr.KHM_Serif_8:
	-$(PYTHON) "data/multilingual/Khmr.KHM/Serif_8/pdf_to_json_test_Khmr.KHM_Serif_8.py" > "data/multilingual/Khmr.KHM/Serif_8/pdf_to_json_test_Khmr.KHM_Serif_8.json" 2>&1
Khmr.KHM_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Khmr.KHM/Sun-ExtA_12/pdf_to_json_test_Khmr.KHM_Sun-ExtA_12.py" > "data/multilingual/Khmr.KHM/Sun-ExtA_12/pdf_to_json_test_Khmr.KHM_Sun-ExtA_12.json" 2>&1
Khmr.KHM_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Khmr.KHM/Sun-ExtA_16/pdf_to_json_test_Khmr.KHM_Sun-ExtA_16.py" > "data/multilingual/Khmr.KHM/Sun-ExtA_16/pdf_to_json_test_Khmr.KHM_Sun-ExtA_16.json" 2>&1
Khmr.KHM_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Khmr.KHM/Sun-ExtA_8/pdf_to_json_test_Khmr.KHM_Sun-ExtA_8.py" > "data/multilingual/Khmr.KHM/Sun-ExtA_8/pdf_to_json_test_Khmr.KHM_Sun-ExtA_8.json" 2>&1


Khmr.KHM_all : Khmr.KHM_Mono_12 Khmr.KHM_Mono_16 Khmr.KHM_Mono_8 Khmr.KHM_Sans_12 Khmr.KHM_Sans_16 Khmr.KHM_Sans_8 Khmr.KHM_Serif_12 Khmr.KHM_Serif_16 Khmr.KHM_Serif_8 Khmr.KHM_Sun-ExtA_12 Khmr.KHM_Sun-ExtA_16 Khmr.KHM_Sun-ExtA_8
