PYTHON=python3


Latn.GUU_Mono_12:
	-$(PYTHON) data/multilingual/Latn.GUU/Mono_12/pdf_to_json_test_Latn.GUU_Mono_12.py > data/multilingual/Latn.GUU/Mono_12/pdf_to_json_test_Latn.GUU_Mono_12.json 2>&1
Latn.GUU_Mono_16:
	-$(PYTHON) data/multilingual/Latn.GUU/Mono_16/pdf_to_json_test_Latn.GUU_Mono_16.py > data/multilingual/Latn.GUU/Mono_16/pdf_to_json_test_Latn.GUU_Mono_16.json 2>&1
Latn.GUU_Mono_8:
	-$(PYTHON) data/multilingual/Latn.GUU/Mono_8/pdf_to_json_test_Latn.GUU_Mono_8.py > data/multilingual/Latn.GUU/Mono_8/pdf_to_json_test_Latn.GUU_Mono_8.json 2>&1
Latn.GUU_Sans_12:
	-$(PYTHON) data/multilingual/Latn.GUU/Sans_12/pdf_to_json_test_Latn.GUU_Sans_12.py > data/multilingual/Latn.GUU/Sans_12/pdf_to_json_test_Latn.GUU_Sans_12.json 2>&1
Latn.GUU_Sans_16:
	-$(PYTHON) data/multilingual/Latn.GUU/Sans_16/pdf_to_json_test_Latn.GUU_Sans_16.py > data/multilingual/Latn.GUU/Sans_16/pdf_to_json_test_Latn.GUU_Sans_16.json 2>&1
Latn.GUU_Sans_8:
	-$(PYTHON) data/multilingual/Latn.GUU/Sans_8/pdf_to_json_test_Latn.GUU_Sans_8.py > data/multilingual/Latn.GUU/Sans_8/pdf_to_json_test_Latn.GUU_Sans_8.json 2>&1
Latn.GUU_Serif_12:
	-$(PYTHON) data/multilingual/Latn.GUU/Serif_12/pdf_to_json_test_Latn.GUU_Serif_12.py > data/multilingual/Latn.GUU/Serif_12/pdf_to_json_test_Latn.GUU_Serif_12.json 2>&1
Latn.GUU_Serif_16:
	-$(PYTHON) data/multilingual/Latn.GUU/Serif_16/pdf_to_json_test_Latn.GUU_Serif_16.py > data/multilingual/Latn.GUU/Serif_16/pdf_to_json_test_Latn.GUU_Serif_16.json 2>&1
Latn.GUU_Serif_8:
	-$(PYTHON) data/multilingual/Latn.GUU/Serif_8/pdf_to_json_test_Latn.GUU_Serif_8.py > data/multilingual/Latn.GUU/Serif_8/pdf_to_json_test_Latn.GUU_Serif_8.json 2>&1
Latn.GUU_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.GUU/Sun-ExtA_12/pdf_to_json_test_Latn.GUU_Sun-ExtA_12.py > data/multilingual/Latn.GUU/Sun-ExtA_12/pdf_to_json_test_Latn.GUU_Sun-ExtA_12.json 2>&1
Latn.GUU_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.GUU/Sun-ExtA_16/pdf_to_json_test_Latn.GUU_Sun-ExtA_16.py > data/multilingual/Latn.GUU/Sun-ExtA_16/pdf_to_json_test_Latn.GUU_Sun-ExtA_16.json 2>&1
Latn.GUU_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.GUU/Sun-ExtA_8/pdf_to_json_test_Latn.GUU_Sun-ExtA_8.py > data/multilingual/Latn.GUU/Sun-ExtA_8/pdf_to_json_test_Latn.GUU_Sun-ExtA_8.json 2>&1


Latn.GUU_all : Latn.GUU_Mono_12 Latn.GUU_Mono_16 Latn.GUU_Mono_8 Latn.GUU_Sans_12 Latn.GUU_Sans_16 Latn.GUU_Sans_8 Latn.GUU_Serif_12 Latn.GUU_Serif_16 Latn.GUU_Serif_8 Latn.GUU_Sun-ExtA_12 Latn.GUU_Sun-ExtA_16 Latn.GUU_Sun-ExtA_8
