PYTHON=python3


Latn.CYM_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.CYM/Mono_12/pdf_to_json_test_Latn.CYM_Mono_12.py" > "data/multilingual/Latn.CYM/Mono_12/pdf_to_json_test_Latn.CYM_Mono_12.json" 2>&1
Latn.CYM_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.CYM/Mono_16/pdf_to_json_test_Latn.CYM_Mono_16.py" > "data/multilingual/Latn.CYM/Mono_16/pdf_to_json_test_Latn.CYM_Mono_16.json" 2>&1
Latn.CYM_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.CYM/Mono_8/pdf_to_json_test_Latn.CYM_Mono_8.py" > "data/multilingual/Latn.CYM/Mono_8/pdf_to_json_test_Latn.CYM_Mono_8.json" 2>&1
Latn.CYM_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.CYM/Sans_12/pdf_to_json_test_Latn.CYM_Sans_12.py" > "data/multilingual/Latn.CYM/Sans_12/pdf_to_json_test_Latn.CYM_Sans_12.json" 2>&1
Latn.CYM_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.CYM/Sans_16/pdf_to_json_test_Latn.CYM_Sans_16.py" > "data/multilingual/Latn.CYM/Sans_16/pdf_to_json_test_Latn.CYM_Sans_16.json" 2>&1
Latn.CYM_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.CYM/Sans_8/pdf_to_json_test_Latn.CYM_Sans_8.py" > "data/multilingual/Latn.CYM/Sans_8/pdf_to_json_test_Latn.CYM_Sans_8.json" 2>&1
Latn.CYM_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.CYM/Serif_12/pdf_to_json_test_Latn.CYM_Serif_12.py" > "data/multilingual/Latn.CYM/Serif_12/pdf_to_json_test_Latn.CYM_Serif_12.json" 2>&1
Latn.CYM_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.CYM/Serif_16/pdf_to_json_test_Latn.CYM_Serif_16.py" > "data/multilingual/Latn.CYM/Serif_16/pdf_to_json_test_Latn.CYM_Serif_16.json" 2>&1
Latn.CYM_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.CYM/Serif_8/pdf_to_json_test_Latn.CYM_Serif_8.py" > "data/multilingual/Latn.CYM/Serif_8/pdf_to_json_test_Latn.CYM_Serif_8.json" 2>&1
Latn.CYM_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.CYM/Sun-ExtA_12/pdf_to_json_test_Latn.CYM_Sun-ExtA_12.py" > "data/multilingual/Latn.CYM/Sun-ExtA_12/pdf_to_json_test_Latn.CYM_Sun-ExtA_12.json" 2>&1
Latn.CYM_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.CYM/Sun-ExtA_16/pdf_to_json_test_Latn.CYM_Sun-ExtA_16.py" > "data/multilingual/Latn.CYM/Sun-ExtA_16/pdf_to_json_test_Latn.CYM_Sun-ExtA_16.json" 2>&1
Latn.CYM_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.CYM/Sun-ExtA_8/pdf_to_json_test_Latn.CYM_Sun-ExtA_8.py" > "data/multilingual/Latn.CYM/Sun-ExtA_8/pdf_to_json_test_Latn.CYM_Sun-ExtA_8.json" 2>&1


Latn.CYM_all : Latn.CYM_Mono_12 Latn.CYM_Mono_16 Latn.CYM_Mono_8 Latn.CYM_Sans_12 Latn.CYM_Sans_16 Latn.CYM_Sans_8 Latn.CYM_Serif_12 Latn.CYM_Serif_16 Latn.CYM_Serif_8 Latn.CYM_Sun-ExtA_12 Latn.CYM_Sun-ExtA_16 Latn.CYM_Sun-ExtA_8
