PYTHON=python3


Latn.NJO_Mono_12:
	-$(PYTHON) data/multilingual/Latn.NJO/Mono_12/pdf_to_json_test_Latn.NJO_Mono_12.py > data/multilingual/Latn.NJO/Mono_12/pdf_to_json_test_Latn.NJO_Mono_12.json 2>&1
Latn.NJO_Mono_16:
	-$(PYTHON) data/multilingual/Latn.NJO/Mono_16/pdf_to_json_test_Latn.NJO_Mono_16.py > data/multilingual/Latn.NJO/Mono_16/pdf_to_json_test_Latn.NJO_Mono_16.json 2>&1
Latn.NJO_Mono_8:
	-$(PYTHON) data/multilingual/Latn.NJO/Mono_8/pdf_to_json_test_Latn.NJO_Mono_8.py > data/multilingual/Latn.NJO/Mono_8/pdf_to_json_test_Latn.NJO_Mono_8.json 2>&1
Latn.NJO_Sans_12:
	-$(PYTHON) data/multilingual/Latn.NJO/Sans_12/pdf_to_json_test_Latn.NJO_Sans_12.py > data/multilingual/Latn.NJO/Sans_12/pdf_to_json_test_Latn.NJO_Sans_12.json 2>&1
Latn.NJO_Sans_16:
	-$(PYTHON) data/multilingual/Latn.NJO/Sans_16/pdf_to_json_test_Latn.NJO_Sans_16.py > data/multilingual/Latn.NJO/Sans_16/pdf_to_json_test_Latn.NJO_Sans_16.json 2>&1
Latn.NJO_Sans_8:
	-$(PYTHON) data/multilingual/Latn.NJO/Sans_8/pdf_to_json_test_Latn.NJO_Sans_8.py > data/multilingual/Latn.NJO/Sans_8/pdf_to_json_test_Latn.NJO_Sans_8.json 2>&1
Latn.NJO_Serif_12:
	-$(PYTHON) data/multilingual/Latn.NJO/Serif_12/pdf_to_json_test_Latn.NJO_Serif_12.py > data/multilingual/Latn.NJO/Serif_12/pdf_to_json_test_Latn.NJO_Serif_12.json 2>&1
Latn.NJO_Serif_16:
	-$(PYTHON) data/multilingual/Latn.NJO/Serif_16/pdf_to_json_test_Latn.NJO_Serif_16.py > data/multilingual/Latn.NJO/Serif_16/pdf_to_json_test_Latn.NJO_Serif_16.json 2>&1
Latn.NJO_Serif_8:
	-$(PYTHON) data/multilingual/Latn.NJO/Serif_8/pdf_to_json_test_Latn.NJO_Serif_8.py > data/multilingual/Latn.NJO/Serif_8/pdf_to_json_test_Latn.NJO_Serif_8.json 2>&1
Latn.NJO_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.NJO/Sun-ExtA_12/pdf_to_json_test_Latn.NJO_Sun-ExtA_12.py > data/multilingual/Latn.NJO/Sun-ExtA_12/pdf_to_json_test_Latn.NJO_Sun-ExtA_12.json 2>&1
Latn.NJO_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.NJO/Sun-ExtA_16/pdf_to_json_test_Latn.NJO_Sun-ExtA_16.py > data/multilingual/Latn.NJO/Sun-ExtA_16/pdf_to_json_test_Latn.NJO_Sun-ExtA_16.json 2>&1
Latn.NJO_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.NJO/Sun-ExtA_8/pdf_to_json_test_Latn.NJO_Sun-ExtA_8.py > data/multilingual/Latn.NJO/Sun-ExtA_8/pdf_to_json_test_Latn.NJO_Sun-ExtA_8.json 2>&1


Latn.NJO_all : Latn.NJO_Mono_12 Latn.NJO_Mono_16 Latn.NJO_Mono_8 Latn.NJO_Sans_12 Latn.NJO_Sans_16 Latn.NJO_Sans_8 Latn.NJO_Serif_12 Latn.NJO_Serif_16 Latn.NJO_Serif_8 Latn.NJO_Sun-ExtA_12 Latn.NJO_Sun-ExtA_16 Latn.NJO_Sun-ExtA_8
