PYTHON=python3


Latn.KRL_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.KRL/Mono_12/pdf_to_json_test_Latn.KRL_Mono_12.py" > "data/multilingual/Latn.KRL/Mono_12/pdf_to_json_test_Latn.KRL_Mono_12.json" 2>&1
Latn.KRL_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.KRL/Mono_16/pdf_to_json_test_Latn.KRL_Mono_16.py" > "data/multilingual/Latn.KRL/Mono_16/pdf_to_json_test_Latn.KRL_Mono_16.json" 2>&1
Latn.KRL_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.KRL/Mono_8/pdf_to_json_test_Latn.KRL_Mono_8.py" > "data/multilingual/Latn.KRL/Mono_8/pdf_to_json_test_Latn.KRL_Mono_8.json" 2>&1
Latn.KRL_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.KRL/Sans_12/pdf_to_json_test_Latn.KRL_Sans_12.py" > "data/multilingual/Latn.KRL/Sans_12/pdf_to_json_test_Latn.KRL_Sans_12.json" 2>&1
Latn.KRL_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.KRL/Sans_16/pdf_to_json_test_Latn.KRL_Sans_16.py" > "data/multilingual/Latn.KRL/Sans_16/pdf_to_json_test_Latn.KRL_Sans_16.json" 2>&1
Latn.KRL_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.KRL/Sans_8/pdf_to_json_test_Latn.KRL_Sans_8.py" > "data/multilingual/Latn.KRL/Sans_8/pdf_to_json_test_Latn.KRL_Sans_8.json" 2>&1
Latn.KRL_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.KRL/Serif_12/pdf_to_json_test_Latn.KRL_Serif_12.py" > "data/multilingual/Latn.KRL/Serif_12/pdf_to_json_test_Latn.KRL_Serif_12.json" 2>&1
Latn.KRL_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.KRL/Serif_16/pdf_to_json_test_Latn.KRL_Serif_16.py" > "data/multilingual/Latn.KRL/Serif_16/pdf_to_json_test_Latn.KRL_Serif_16.json" 2>&1
Latn.KRL_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.KRL/Serif_8/pdf_to_json_test_Latn.KRL_Serif_8.py" > "data/multilingual/Latn.KRL/Serif_8/pdf_to_json_test_Latn.KRL_Serif_8.json" 2>&1
Latn.KRL_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.KRL/Sun-ExtA_12/pdf_to_json_test_Latn.KRL_Sun-ExtA_12.py" > "data/multilingual/Latn.KRL/Sun-ExtA_12/pdf_to_json_test_Latn.KRL_Sun-ExtA_12.json" 2>&1
Latn.KRL_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.KRL/Sun-ExtA_16/pdf_to_json_test_Latn.KRL_Sun-ExtA_16.py" > "data/multilingual/Latn.KRL/Sun-ExtA_16/pdf_to_json_test_Latn.KRL_Sun-ExtA_16.json" 2>&1
Latn.KRL_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.KRL/Sun-ExtA_8/pdf_to_json_test_Latn.KRL_Sun-ExtA_8.py" > "data/multilingual/Latn.KRL/Sun-ExtA_8/pdf_to_json_test_Latn.KRL_Sun-ExtA_8.json" 2>&1


Latn.KRL_all : Latn.KRL_Mono_12 Latn.KRL_Mono_16 Latn.KRL_Mono_8 Latn.KRL_Sans_12 Latn.KRL_Sans_16 Latn.KRL_Sans_8 Latn.KRL_Serif_12 Latn.KRL_Serif_16 Latn.KRL_Serif_8 Latn.KRL_Sun-ExtA_12 Latn.KRL_Sun-ExtA_16 Latn.KRL_Sun-ExtA_8
