PYTHON=python3


Latn.MTO_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.MTO/Mono_12/pdf_to_json_test_Latn.MTO_Mono_12.py" > "data/multilingual/Latn.MTO/Mono_12/pdf_to_json_test_Latn.MTO_Mono_12.json" 2>&1
Latn.MTO_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.MTO/Mono_16/pdf_to_json_test_Latn.MTO_Mono_16.py" > "data/multilingual/Latn.MTO/Mono_16/pdf_to_json_test_Latn.MTO_Mono_16.json" 2>&1
Latn.MTO_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.MTO/Mono_8/pdf_to_json_test_Latn.MTO_Mono_8.py" > "data/multilingual/Latn.MTO/Mono_8/pdf_to_json_test_Latn.MTO_Mono_8.json" 2>&1
Latn.MTO_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.MTO/Sans_12/pdf_to_json_test_Latn.MTO_Sans_12.py" > "data/multilingual/Latn.MTO/Sans_12/pdf_to_json_test_Latn.MTO_Sans_12.json" 2>&1
Latn.MTO_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.MTO/Sans_16/pdf_to_json_test_Latn.MTO_Sans_16.py" > "data/multilingual/Latn.MTO/Sans_16/pdf_to_json_test_Latn.MTO_Sans_16.json" 2>&1
Latn.MTO_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.MTO/Sans_8/pdf_to_json_test_Latn.MTO_Sans_8.py" > "data/multilingual/Latn.MTO/Sans_8/pdf_to_json_test_Latn.MTO_Sans_8.json" 2>&1
Latn.MTO_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.MTO/Serif_12/pdf_to_json_test_Latn.MTO_Serif_12.py" > "data/multilingual/Latn.MTO/Serif_12/pdf_to_json_test_Latn.MTO_Serif_12.json" 2>&1
Latn.MTO_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.MTO/Serif_16/pdf_to_json_test_Latn.MTO_Serif_16.py" > "data/multilingual/Latn.MTO/Serif_16/pdf_to_json_test_Latn.MTO_Serif_16.json" 2>&1
Latn.MTO_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.MTO/Serif_8/pdf_to_json_test_Latn.MTO_Serif_8.py" > "data/multilingual/Latn.MTO/Serif_8/pdf_to_json_test_Latn.MTO_Serif_8.json" 2>&1
Latn.MTO_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.MTO/Sun-ExtA_12/pdf_to_json_test_Latn.MTO_Sun-ExtA_12.py" > "data/multilingual/Latn.MTO/Sun-ExtA_12/pdf_to_json_test_Latn.MTO_Sun-ExtA_12.json" 2>&1
Latn.MTO_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.MTO/Sun-ExtA_16/pdf_to_json_test_Latn.MTO_Sun-ExtA_16.py" > "data/multilingual/Latn.MTO/Sun-ExtA_16/pdf_to_json_test_Latn.MTO_Sun-ExtA_16.json" 2>&1
Latn.MTO_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.MTO/Sun-ExtA_8/pdf_to_json_test_Latn.MTO_Sun-ExtA_8.py" > "data/multilingual/Latn.MTO/Sun-ExtA_8/pdf_to_json_test_Latn.MTO_Sun-ExtA_8.json" 2>&1


Latn.MTO_all : Latn.MTO_Mono_12 Latn.MTO_Mono_16 Latn.MTO_Mono_8 Latn.MTO_Sans_12 Latn.MTO_Sans_16 Latn.MTO_Sans_8 Latn.MTO_Serif_12 Latn.MTO_Serif_16 Latn.MTO_Serif_8 Latn.MTO_Sun-ExtA_12 Latn.MTO_Sun-ExtA_16 Latn.MTO_Sun-ExtA_8
