PYTHON=python3


Latn.SME_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.SME/Mono_12/pdf_to_json_test_Latn.SME_Mono_12.py" > "data/multilingual/Latn.SME/Mono_12/pdf_to_json_test_Latn.SME_Mono_12.json" 2>&1
Latn.SME_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.SME/Mono_16/pdf_to_json_test_Latn.SME_Mono_16.py" > "data/multilingual/Latn.SME/Mono_16/pdf_to_json_test_Latn.SME_Mono_16.json" 2>&1
Latn.SME_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.SME/Mono_8/pdf_to_json_test_Latn.SME_Mono_8.py" > "data/multilingual/Latn.SME/Mono_8/pdf_to_json_test_Latn.SME_Mono_8.json" 2>&1
Latn.SME_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.SME/Sans_12/pdf_to_json_test_Latn.SME_Sans_12.py" > "data/multilingual/Latn.SME/Sans_12/pdf_to_json_test_Latn.SME_Sans_12.json" 2>&1
Latn.SME_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.SME/Sans_16/pdf_to_json_test_Latn.SME_Sans_16.py" > "data/multilingual/Latn.SME/Sans_16/pdf_to_json_test_Latn.SME_Sans_16.json" 2>&1
Latn.SME_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.SME/Sans_8/pdf_to_json_test_Latn.SME_Sans_8.py" > "data/multilingual/Latn.SME/Sans_8/pdf_to_json_test_Latn.SME_Sans_8.json" 2>&1
Latn.SME_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.SME/Serif_12/pdf_to_json_test_Latn.SME_Serif_12.py" > "data/multilingual/Latn.SME/Serif_12/pdf_to_json_test_Latn.SME_Serif_12.json" 2>&1
Latn.SME_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.SME/Serif_16/pdf_to_json_test_Latn.SME_Serif_16.py" > "data/multilingual/Latn.SME/Serif_16/pdf_to_json_test_Latn.SME_Serif_16.json" 2>&1
Latn.SME_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.SME/Serif_8/pdf_to_json_test_Latn.SME_Serif_8.py" > "data/multilingual/Latn.SME/Serif_8/pdf_to_json_test_Latn.SME_Serif_8.json" 2>&1
Latn.SME_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.SME/Sun-ExtA_12/pdf_to_json_test_Latn.SME_Sun-ExtA_12.py" > "data/multilingual/Latn.SME/Sun-ExtA_12/pdf_to_json_test_Latn.SME_Sun-ExtA_12.json" 2>&1
Latn.SME_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.SME/Sun-ExtA_16/pdf_to_json_test_Latn.SME_Sun-ExtA_16.py" > "data/multilingual/Latn.SME/Sun-ExtA_16/pdf_to_json_test_Latn.SME_Sun-ExtA_16.json" 2>&1
Latn.SME_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.SME/Sun-ExtA_8/pdf_to_json_test_Latn.SME_Sun-ExtA_8.py" > "data/multilingual/Latn.SME/Sun-ExtA_8/pdf_to_json_test_Latn.SME_Sun-ExtA_8.json" 2>&1


Latn.SME_all : Latn.SME_Mono_12 Latn.SME_Mono_16 Latn.SME_Mono_8 Latn.SME_Sans_12 Latn.SME_Sans_16 Latn.SME_Sans_8 Latn.SME_Serif_12 Latn.SME_Serif_16 Latn.SME_Serif_8 Latn.SME_Sun-ExtA_12 Latn.SME_Sun-ExtA_16 Latn.SME_Sun-ExtA_8
