PYTHON=python3


Latn.GJN_Mono_12:
	-$(PYTHON) data/multilingual/Latn.GJN/Mono_12/pdf_to_json_test_Latn.GJN_Mono_12.py > data/multilingual/Latn.GJN/Mono_12/pdf_to_json_test_Latn.GJN_Mono_12.json 2>&1
Latn.GJN_Mono_16:
	-$(PYTHON) data/multilingual/Latn.GJN/Mono_16/pdf_to_json_test_Latn.GJN_Mono_16.py > data/multilingual/Latn.GJN/Mono_16/pdf_to_json_test_Latn.GJN_Mono_16.json 2>&1
Latn.GJN_Mono_8:
	-$(PYTHON) data/multilingual/Latn.GJN/Mono_8/pdf_to_json_test_Latn.GJN_Mono_8.py > data/multilingual/Latn.GJN/Mono_8/pdf_to_json_test_Latn.GJN_Mono_8.json 2>&1
Latn.GJN_Sans_12:
	-$(PYTHON) data/multilingual/Latn.GJN/Sans_12/pdf_to_json_test_Latn.GJN_Sans_12.py > data/multilingual/Latn.GJN/Sans_12/pdf_to_json_test_Latn.GJN_Sans_12.json 2>&1
Latn.GJN_Sans_16:
	-$(PYTHON) data/multilingual/Latn.GJN/Sans_16/pdf_to_json_test_Latn.GJN_Sans_16.py > data/multilingual/Latn.GJN/Sans_16/pdf_to_json_test_Latn.GJN_Sans_16.json 2>&1
Latn.GJN_Sans_8:
	-$(PYTHON) data/multilingual/Latn.GJN/Sans_8/pdf_to_json_test_Latn.GJN_Sans_8.py > data/multilingual/Latn.GJN/Sans_8/pdf_to_json_test_Latn.GJN_Sans_8.json 2>&1
Latn.GJN_Serif_12:
	-$(PYTHON) data/multilingual/Latn.GJN/Serif_12/pdf_to_json_test_Latn.GJN_Serif_12.py > data/multilingual/Latn.GJN/Serif_12/pdf_to_json_test_Latn.GJN_Serif_12.json 2>&1
Latn.GJN_Serif_16:
	-$(PYTHON) data/multilingual/Latn.GJN/Serif_16/pdf_to_json_test_Latn.GJN_Serif_16.py > data/multilingual/Latn.GJN/Serif_16/pdf_to_json_test_Latn.GJN_Serif_16.json 2>&1
Latn.GJN_Serif_8:
	-$(PYTHON) data/multilingual/Latn.GJN/Serif_8/pdf_to_json_test_Latn.GJN_Serif_8.py > data/multilingual/Latn.GJN/Serif_8/pdf_to_json_test_Latn.GJN_Serif_8.json 2>&1
Latn.GJN_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.GJN/Sun-ExtA_12/pdf_to_json_test_Latn.GJN_Sun-ExtA_12.py > data/multilingual/Latn.GJN/Sun-ExtA_12/pdf_to_json_test_Latn.GJN_Sun-ExtA_12.json 2>&1
Latn.GJN_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.GJN/Sun-ExtA_16/pdf_to_json_test_Latn.GJN_Sun-ExtA_16.py > data/multilingual/Latn.GJN/Sun-ExtA_16/pdf_to_json_test_Latn.GJN_Sun-ExtA_16.json 2>&1
Latn.GJN_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.GJN/Sun-ExtA_8/pdf_to_json_test_Latn.GJN_Sun-ExtA_8.py > data/multilingual/Latn.GJN/Sun-ExtA_8/pdf_to_json_test_Latn.GJN_Sun-ExtA_8.json 2>&1


Latn.GJN_all : Latn.GJN_Mono_12 Latn.GJN_Mono_16 Latn.GJN_Mono_8 Latn.GJN_Sans_12 Latn.GJN_Sans_16 Latn.GJN_Sans_8 Latn.GJN_Serif_12 Latn.GJN_Serif_16 Latn.GJN_Serif_8 Latn.GJN_Sun-ExtA_12 Latn.GJN_Sun-ExtA_16 Latn.GJN_Sun-ExtA_8
