PYTHON=python3


Latn.NOB_Mono_12:
	-$(PYTHON) data/multilingual/Latn.NOB/Mono_12/pdf_to_json_test_Latn.NOB_Mono_12.py > data/multilingual/Latn.NOB/Mono_12/pdf_to_json_test_Latn.NOB_Mono_12.json 2>&1
Latn.NOB_Mono_16:
	-$(PYTHON) data/multilingual/Latn.NOB/Mono_16/pdf_to_json_test_Latn.NOB_Mono_16.py > data/multilingual/Latn.NOB/Mono_16/pdf_to_json_test_Latn.NOB_Mono_16.json 2>&1
Latn.NOB_Mono_8:
	-$(PYTHON) data/multilingual/Latn.NOB/Mono_8/pdf_to_json_test_Latn.NOB_Mono_8.py > data/multilingual/Latn.NOB/Mono_8/pdf_to_json_test_Latn.NOB_Mono_8.json 2>&1
Latn.NOB_Sans_12:
	-$(PYTHON) data/multilingual/Latn.NOB/Sans_12/pdf_to_json_test_Latn.NOB_Sans_12.py > data/multilingual/Latn.NOB/Sans_12/pdf_to_json_test_Latn.NOB_Sans_12.json 2>&1
Latn.NOB_Sans_16:
	-$(PYTHON) data/multilingual/Latn.NOB/Sans_16/pdf_to_json_test_Latn.NOB_Sans_16.py > data/multilingual/Latn.NOB/Sans_16/pdf_to_json_test_Latn.NOB_Sans_16.json 2>&1
Latn.NOB_Sans_8:
	-$(PYTHON) data/multilingual/Latn.NOB/Sans_8/pdf_to_json_test_Latn.NOB_Sans_8.py > data/multilingual/Latn.NOB/Sans_8/pdf_to_json_test_Latn.NOB_Sans_8.json 2>&1
Latn.NOB_Serif_12:
	-$(PYTHON) data/multilingual/Latn.NOB/Serif_12/pdf_to_json_test_Latn.NOB_Serif_12.py > data/multilingual/Latn.NOB/Serif_12/pdf_to_json_test_Latn.NOB_Serif_12.json 2>&1
Latn.NOB_Serif_16:
	-$(PYTHON) data/multilingual/Latn.NOB/Serif_16/pdf_to_json_test_Latn.NOB_Serif_16.py > data/multilingual/Latn.NOB/Serif_16/pdf_to_json_test_Latn.NOB_Serif_16.json 2>&1
Latn.NOB_Serif_8:
	-$(PYTHON) data/multilingual/Latn.NOB/Serif_8/pdf_to_json_test_Latn.NOB_Serif_8.py > data/multilingual/Latn.NOB/Serif_8/pdf_to_json_test_Latn.NOB_Serif_8.json 2>&1
Latn.NOB_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.NOB/Sun-ExtA_12/pdf_to_json_test_Latn.NOB_Sun-ExtA_12.py > data/multilingual/Latn.NOB/Sun-ExtA_12/pdf_to_json_test_Latn.NOB_Sun-ExtA_12.json 2>&1
Latn.NOB_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.NOB/Sun-ExtA_16/pdf_to_json_test_Latn.NOB_Sun-ExtA_16.py > data/multilingual/Latn.NOB/Sun-ExtA_16/pdf_to_json_test_Latn.NOB_Sun-ExtA_16.json 2>&1
Latn.NOB_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.NOB/Sun-ExtA_8/pdf_to_json_test_Latn.NOB_Sun-ExtA_8.py > data/multilingual/Latn.NOB/Sun-ExtA_8/pdf_to_json_test_Latn.NOB_Sun-ExtA_8.json 2>&1


Latn.NOB_all : Latn.NOB_Mono_12 Latn.NOB_Mono_16 Latn.NOB_Mono_8 Latn.NOB_Sans_12 Latn.NOB_Sans_16 Latn.NOB_Sans_8 Latn.NOB_Serif_12 Latn.NOB_Serif_16 Latn.NOB_Serif_8 Latn.NOB_Sun-ExtA_12 Latn.NOB_Sun-ExtA_16 Latn.NOB_Sun-ExtA_8
