PYTHON=python3


Latn.ACU_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.ACU/Mono_12/pdf_to_json_test_Latn.ACU_Mono_12.py" > "data/multilingual/Latn.ACU/Mono_12/pdf_to_json_test_Latn.ACU_Mono_12.json" 2>&1
Latn.ACU_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.ACU/Mono_16/pdf_to_json_test_Latn.ACU_Mono_16.py" > "data/multilingual/Latn.ACU/Mono_16/pdf_to_json_test_Latn.ACU_Mono_16.json" 2>&1
Latn.ACU_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.ACU/Mono_8/pdf_to_json_test_Latn.ACU_Mono_8.py" > "data/multilingual/Latn.ACU/Mono_8/pdf_to_json_test_Latn.ACU_Mono_8.json" 2>&1
Latn.ACU_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.ACU/Sans_12/pdf_to_json_test_Latn.ACU_Sans_12.py" > "data/multilingual/Latn.ACU/Sans_12/pdf_to_json_test_Latn.ACU_Sans_12.json" 2>&1
Latn.ACU_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.ACU/Sans_16/pdf_to_json_test_Latn.ACU_Sans_16.py" > "data/multilingual/Latn.ACU/Sans_16/pdf_to_json_test_Latn.ACU_Sans_16.json" 2>&1
Latn.ACU_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.ACU/Sans_8/pdf_to_json_test_Latn.ACU_Sans_8.py" > "data/multilingual/Latn.ACU/Sans_8/pdf_to_json_test_Latn.ACU_Sans_8.json" 2>&1
Latn.ACU_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.ACU/Serif_12/pdf_to_json_test_Latn.ACU_Serif_12.py" > "data/multilingual/Latn.ACU/Serif_12/pdf_to_json_test_Latn.ACU_Serif_12.json" 2>&1
Latn.ACU_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.ACU/Serif_16/pdf_to_json_test_Latn.ACU_Serif_16.py" > "data/multilingual/Latn.ACU/Serif_16/pdf_to_json_test_Latn.ACU_Serif_16.json" 2>&1
Latn.ACU_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.ACU/Serif_8/pdf_to_json_test_Latn.ACU_Serif_8.py" > "data/multilingual/Latn.ACU/Serif_8/pdf_to_json_test_Latn.ACU_Serif_8.json" 2>&1
Latn.ACU_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.ACU/Sun-ExtA_12/pdf_to_json_test_Latn.ACU_Sun-ExtA_12.py" > "data/multilingual/Latn.ACU/Sun-ExtA_12/pdf_to_json_test_Latn.ACU_Sun-ExtA_12.json" 2>&1
Latn.ACU_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.ACU/Sun-ExtA_16/pdf_to_json_test_Latn.ACU_Sun-ExtA_16.py" > "data/multilingual/Latn.ACU/Sun-ExtA_16/pdf_to_json_test_Latn.ACU_Sun-ExtA_16.json" 2>&1
Latn.ACU_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.ACU/Sun-ExtA_8/pdf_to_json_test_Latn.ACU_Sun-ExtA_8.py" > "data/multilingual/Latn.ACU/Sun-ExtA_8/pdf_to_json_test_Latn.ACU_Sun-ExtA_8.json" 2>&1


Latn.ACU_all : Latn.ACU_Mono_12 Latn.ACU_Mono_16 Latn.ACU_Mono_8 Latn.ACU_Sans_12 Latn.ACU_Sans_16 Latn.ACU_Sans_8 Latn.ACU_Serif_12 Latn.ACU_Serif_16 Latn.ACU_Serif_8 Latn.ACU_Sun-ExtA_12 Latn.ACU_Sun-ExtA_16 Latn.ACU_Sun-ExtA_8
