PYTHON=python3


Latn.FUV_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.FUV/Mono_12/pdf_to_json_test_Latn.FUV_Mono_12.py" > "data/multilingual/Latn.FUV/Mono_12/pdf_to_json_test_Latn.FUV_Mono_12.json" 2>&1
Latn.FUV_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.FUV/Mono_16/pdf_to_json_test_Latn.FUV_Mono_16.py" > "data/multilingual/Latn.FUV/Mono_16/pdf_to_json_test_Latn.FUV_Mono_16.json" 2>&1
Latn.FUV_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.FUV/Mono_8/pdf_to_json_test_Latn.FUV_Mono_8.py" > "data/multilingual/Latn.FUV/Mono_8/pdf_to_json_test_Latn.FUV_Mono_8.json" 2>&1
Latn.FUV_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.FUV/Sans_12/pdf_to_json_test_Latn.FUV_Sans_12.py" > "data/multilingual/Latn.FUV/Sans_12/pdf_to_json_test_Latn.FUV_Sans_12.json" 2>&1
Latn.FUV_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.FUV/Sans_16/pdf_to_json_test_Latn.FUV_Sans_16.py" > "data/multilingual/Latn.FUV/Sans_16/pdf_to_json_test_Latn.FUV_Sans_16.json" 2>&1
Latn.FUV_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.FUV/Sans_8/pdf_to_json_test_Latn.FUV_Sans_8.py" > "data/multilingual/Latn.FUV/Sans_8/pdf_to_json_test_Latn.FUV_Sans_8.json" 2>&1
Latn.FUV_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.FUV/Serif_12/pdf_to_json_test_Latn.FUV_Serif_12.py" > "data/multilingual/Latn.FUV/Serif_12/pdf_to_json_test_Latn.FUV_Serif_12.json" 2>&1
Latn.FUV_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.FUV/Serif_16/pdf_to_json_test_Latn.FUV_Serif_16.py" > "data/multilingual/Latn.FUV/Serif_16/pdf_to_json_test_Latn.FUV_Serif_16.json" 2>&1
Latn.FUV_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.FUV/Serif_8/pdf_to_json_test_Latn.FUV_Serif_8.py" > "data/multilingual/Latn.FUV/Serif_8/pdf_to_json_test_Latn.FUV_Serif_8.json" 2>&1
Latn.FUV_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.FUV/Sun-ExtA_12/pdf_to_json_test_Latn.FUV_Sun-ExtA_12.py" > "data/multilingual/Latn.FUV/Sun-ExtA_12/pdf_to_json_test_Latn.FUV_Sun-ExtA_12.json" 2>&1
Latn.FUV_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.FUV/Sun-ExtA_16/pdf_to_json_test_Latn.FUV_Sun-ExtA_16.py" > "data/multilingual/Latn.FUV/Sun-ExtA_16/pdf_to_json_test_Latn.FUV_Sun-ExtA_16.json" 2>&1
Latn.FUV_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.FUV/Sun-ExtA_8/pdf_to_json_test_Latn.FUV_Sun-ExtA_8.py" > "data/multilingual/Latn.FUV/Sun-ExtA_8/pdf_to_json_test_Latn.FUV_Sun-ExtA_8.json" 2>&1


Latn.FUV_all : Latn.FUV_Mono_12 Latn.FUV_Mono_16 Latn.FUV_Mono_8 Latn.FUV_Sans_12 Latn.FUV_Sans_16 Latn.FUV_Sans_8 Latn.FUV_Serif_12 Latn.FUV_Serif_16 Latn.FUV_Serif_8 Latn.FUV_Sun-ExtA_12 Latn.FUV_Sun-ExtA_16 Latn.FUV_Sun-ExtA_8
