PYTHON=python3


Cyrl.CJS_Mono_12:
	-$(PYTHON) data/multilingual/Cyrl.CJS/Mono_12/pdf_to_json_test_Cyrl.CJS_Mono_12.py > data/multilingual/Cyrl.CJS/Mono_12/pdf_to_json_test_Cyrl.CJS_Mono_12.json 2>&1
Cyrl.CJS_Mono_16:
	-$(PYTHON) data/multilingual/Cyrl.CJS/Mono_16/pdf_to_json_test_Cyrl.CJS_Mono_16.py > data/multilingual/Cyrl.CJS/Mono_16/pdf_to_json_test_Cyrl.CJS_Mono_16.json 2>&1
Cyrl.CJS_Mono_8:
	-$(PYTHON) data/multilingual/Cyrl.CJS/Mono_8/pdf_to_json_test_Cyrl.CJS_Mono_8.py > data/multilingual/Cyrl.CJS/Mono_8/pdf_to_json_test_Cyrl.CJS_Mono_8.json 2>&1
Cyrl.CJS_Sans_12:
	-$(PYTHON) data/multilingual/Cyrl.CJS/Sans_12/pdf_to_json_test_Cyrl.CJS_Sans_12.py > data/multilingual/Cyrl.CJS/Sans_12/pdf_to_json_test_Cyrl.CJS_Sans_12.json 2>&1
Cyrl.CJS_Sans_16:
	-$(PYTHON) data/multilingual/Cyrl.CJS/Sans_16/pdf_to_json_test_Cyrl.CJS_Sans_16.py > data/multilingual/Cyrl.CJS/Sans_16/pdf_to_json_test_Cyrl.CJS_Sans_16.json 2>&1
Cyrl.CJS_Sans_8:
	-$(PYTHON) data/multilingual/Cyrl.CJS/Sans_8/pdf_to_json_test_Cyrl.CJS_Sans_8.py > data/multilingual/Cyrl.CJS/Sans_8/pdf_to_json_test_Cyrl.CJS_Sans_8.json 2>&1
Cyrl.CJS_Serif_12:
	-$(PYTHON) data/multilingual/Cyrl.CJS/Serif_12/pdf_to_json_test_Cyrl.CJS_Serif_12.py > data/multilingual/Cyrl.CJS/Serif_12/pdf_to_json_test_Cyrl.CJS_Serif_12.json 2>&1
Cyrl.CJS_Serif_16:
	-$(PYTHON) data/multilingual/Cyrl.CJS/Serif_16/pdf_to_json_test_Cyrl.CJS_Serif_16.py > data/multilingual/Cyrl.CJS/Serif_16/pdf_to_json_test_Cyrl.CJS_Serif_16.json 2>&1
Cyrl.CJS_Serif_8:
	-$(PYTHON) data/multilingual/Cyrl.CJS/Serif_8/pdf_to_json_test_Cyrl.CJS_Serif_8.py > data/multilingual/Cyrl.CJS/Serif_8/pdf_to_json_test_Cyrl.CJS_Serif_8.json 2>&1
Cyrl.CJS_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Cyrl.CJS/Sun-ExtA_12/pdf_to_json_test_Cyrl.CJS_Sun-ExtA_12.py > data/multilingual/Cyrl.CJS/Sun-ExtA_12/pdf_to_json_test_Cyrl.CJS_Sun-ExtA_12.json 2>&1
Cyrl.CJS_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Cyrl.CJS/Sun-ExtA_16/pdf_to_json_test_Cyrl.CJS_Sun-ExtA_16.py > data/multilingual/Cyrl.CJS/Sun-ExtA_16/pdf_to_json_test_Cyrl.CJS_Sun-ExtA_16.json 2>&1
Cyrl.CJS_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Cyrl.CJS/Sun-ExtA_8/pdf_to_json_test_Cyrl.CJS_Sun-ExtA_8.py > data/multilingual/Cyrl.CJS/Sun-ExtA_8/pdf_to_json_test_Cyrl.CJS_Sun-ExtA_8.json 2>&1


Cyrl.CJS_all : Cyrl.CJS_Mono_12 Cyrl.CJS_Mono_16 Cyrl.CJS_Mono_8 Cyrl.CJS_Sans_12 Cyrl.CJS_Sans_16 Cyrl.CJS_Sans_8 Cyrl.CJS_Serif_12 Cyrl.CJS_Serif_16 Cyrl.CJS_Serif_8 Cyrl.CJS_Sun-ExtA_12 Cyrl.CJS_Sun-ExtA_16 Cyrl.CJS_Sun-ExtA_8
