PYTHON=python3


Latn.BUG_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.BUG/Mono_12/pdf_to_json_test_Latn.BUG_Mono_12.py" > "data/multilingual/Latn.BUG/Mono_12/pdf_to_json_test_Latn.BUG_Mono_12.json" 2>&1
Latn.BUG_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.BUG/Mono_16/pdf_to_json_test_Latn.BUG_Mono_16.py" > "data/multilingual/Latn.BUG/Mono_16/pdf_to_json_test_Latn.BUG_Mono_16.json" 2>&1
Latn.BUG_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.BUG/Mono_8/pdf_to_json_test_Latn.BUG_Mono_8.py" > "data/multilingual/Latn.BUG/Mono_8/pdf_to_json_test_Latn.BUG_Mono_8.json" 2>&1
Latn.BUG_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.BUG/Sans_12/pdf_to_json_test_Latn.BUG_Sans_12.py" > "data/multilingual/Latn.BUG/Sans_12/pdf_to_json_test_Latn.BUG_Sans_12.json" 2>&1
Latn.BUG_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.BUG/Sans_16/pdf_to_json_test_Latn.BUG_Sans_16.py" > "data/multilingual/Latn.BUG/Sans_16/pdf_to_json_test_Latn.BUG_Sans_16.json" 2>&1
Latn.BUG_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.BUG/Sans_8/pdf_to_json_test_Latn.BUG_Sans_8.py" > "data/multilingual/Latn.BUG/Sans_8/pdf_to_json_test_Latn.BUG_Sans_8.json" 2>&1
Latn.BUG_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.BUG/Serif_12/pdf_to_json_test_Latn.BUG_Serif_12.py" > "data/multilingual/Latn.BUG/Serif_12/pdf_to_json_test_Latn.BUG_Serif_12.json" 2>&1
Latn.BUG_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.BUG/Serif_16/pdf_to_json_test_Latn.BUG_Serif_16.py" > "data/multilingual/Latn.BUG/Serif_16/pdf_to_json_test_Latn.BUG_Serif_16.json" 2>&1
Latn.BUG_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.BUG/Serif_8/pdf_to_json_test_Latn.BUG_Serif_8.py" > "data/multilingual/Latn.BUG/Serif_8/pdf_to_json_test_Latn.BUG_Serif_8.json" 2>&1
Latn.BUG_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.BUG/Sun-ExtA_12/pdf_to_json_test_Latn.BUG_Sun-ExtA_12.py" > "data/multilingual/Latn.BUG/Sun-ExtA_12/pdf_to_json_test_Latn.BUG_Sun-ExtA_12.json" 2>&1
Latn.BUG_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.BUG/Sun-ExtA_16/pdf_to_json_test_Latn.BUG_Sun-ExtA_16.py" > "data/multilingual/Latn.BUG/Sun-ExtA_16/pdf_to_json_test_Latn.BUG_Sun-ExtA_16.json" 2>&1
Latn.BUG_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.BUG/Sun-ExtA_8/pdf_to_json_test_Latn.BUG_Sun-ExtA_8.py" > "data/multilingual/Latn.BUG/Sun-ExtA_8/pdf_to_json_test_Latn.BUG_Sun-ExtA_8.json" 2>&1


Latn.BUG_all : Latn.BUG_Mono_12 Latn.BUG_Mono_16 Latn.BUG_Mono_8 Latn.BUG_Sans_12 Latn.BUG_Sans_16 Latn.BUG_Sans_8 Latn.BUG_Serif_12 Latn.BUG_Serif_16 Latn.BUG_Serif_8 Latn.BUG_Sun-ExtA_12 Latn.BUG_Sun-ExtA_16 Latn.BUG_Sun-ExtA_8
