PYTHON=python3


Latn.FRA_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.FRA/Mono_12/pdf_to_json_test_Latn.FRA_Mono_12.py" > "data/multilingual/Latn.FRA/Mono_12/pdf_to_json_test_Latn.FRA_Mono_12.json" 2>&1
Latn.FRA_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.FRA/Mono_16/pdf_to_json_test_Latn.FRA_Mono_16.py" > "data/multilingual/Latn.FRA/Mono_16/pdf_to_json_test_Latn.FRA_Mono_16.json" 2>&1
Latn.FRA_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.FRA/Mono_8/pdf_to_json_test_Latn.FRA_Mono_8.py" > "data/multilingual/Latn.FRA/Mono_8/pdf_to_json_test_Latn.FRA_Mono_8.json" 2>&1
Latn.FRA_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.FRA/Sans_12/pdf_to_json_test_Latn.FRA_Sans_12.py" > "data/multilingual/Latn.FRA/Sans_12/pdf_to_json_test_Latn.FRA_Sans_12.json" 2>&1
Latn.FRA_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.FRA/Sans_16/pdf_to_json_test_Latn.FRA_Sans_16.py" > "data/multilingual/Latn.FRA/Sans_16/pdf_to_json_test_Latn.FRA_Sans_16.json" 2>&1
Latn.FRA_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.FRA/Sans_8/pdf_to_json_test_Latn.FRA_Sans_8.py" > "data/multilingual/Latn.FRA/Sans_8/pdf_to_json_test_Latn.FRA_Sans_8.json" 2>&1
Latn.FRA_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.FRA/Serif_12/pdf_to_json_test_Latn.FRA_Serif_12.py" > "data/multilingual/Latn.FRA/Serif_12/pdf_to_json_test_Latn.FRA_Serif_12.json" 2>&1
Latn.FRA_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.FRA/Serif_16/pdf_to_json_test_Latn.FRA_Serif_16.py" > "data/multilingual/Latn.FRA/Serif_16/pdf_to_json_test_Latn.FRA_Serif_16.json" 2>&1
Latn.FRA_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.FRA/Serif_8/pdf_to_json_test_Latn.FRA_Serif_8.py" > "data/multilingual/Latn.FRA/Serif_8/pdf_to_json_test_Latn.FRA_Serif_8.json" 2>&1
Latn.FRA_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.FRA/Sun-ExtA_12/pdf_to_json_test_Latn.FRA_Sun-ExtA_12.py" > "data/multilingual/Latn.FRA/Sun-ExtA_12/pdf_to_json_test_Latn.FRA_Sun-ExtA_12.json" 2>&1
Latn.FRA_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.FRA/Sun-ExtA_16/pdf_to_json_test_Latn.FRA_Sun-ExtA_16.py" > "data/multilingual/Latn.FRA/Sun-ExtA_16/pdf_to_json_test_Latn.FRA_Sun-ExtA_16.json" 2>&1
Latn.FRA_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.FRA/Sun-ExtA_8/pdf_to_json_test_Latn.FRA_Sun-ExtA_8.py" > "data/multilingual/Latn.FRA/Sun-ExtA_8/pdf_to_json_test_Latn.FRA_Sun-ExtA_8.json" 2>&1


Latn.FRA_all : Latn.FRA_Mono_12 Latn.FRA_Mono_16 Latn.FRA_Mono_8 Latn.FRA_Sans_12 Latn.FRA_Sans_16 Latn.FRA_Sans_8 Latn.FRA_Serif_12 Latn.FRA_Serif_16 Latn.FRA_Serif_8 Latn.FRA_Sun-ExtA_12 Latn.FRA_Sun-ExtA_16 Latn.FRA_Sun-ExtA_8
