PYTHON=python3


Latn.ORH_Mono_12:
	-$(PYTHON) data/multilingual/Latn.ORH/Mono_12/pdf_to_json_test_Latn.ORH_Mono_12.py > data/multilingual/Latn.ORH/Mono_12/pdf_to_json_test_Latn.ORH_Mono_12.json 2>&1
Latn.ORH_Mono_16:
	-$(PYTHON) data/multilingual/Latn.ORH/Mono_16/pdf_to_json_test_Latn.ORH_Mono_16.py > data/multilingual/Latn.ORH/Mono_16/pdf_to_json_test_Latn.ORH_Mono_16.json 2>&1
Latn.ORH_Mono_8:
	-$(PYTHON) data/multilingual/Latn.ORH/Mono_8/pdf_to_json_test_Latn.ORH_Mono_8.py > data/multilingual/Latn.ORH/Mono_8/pdf_to_json_test_Latn.ORH_Mono_8.json 2>&1
Latn.ORH_Sans_12:
	-$(PYTHON) data/multilingual/Latn.ORH/Sans_12/pdf_to_json_test_Latn.ORH_Sans_12.py > data/multilingual/Latn.ORH/Sans_12/pdf_to_json_test_Latn.ORH_Sans_12.json 2>&1
Latn.ORH_Sans_16:
	-$(PYTHON) data/multilingual/Latn.ORH/Sans_16/pdf_to_json_test_Latn.ORH_Sans_16.py > data/multilingual/Latn.ORH/Sans_16/pdf_to_json_test_Latn.ORH_Sans_16.json 2>&1
Latn.ORH_Sans_8:
	-$(PYTHON) data/multilingual/Latn.ORH/Sans_8/pdf_to_json_test_Latn.ORH_Sans_8.py > data/multilingual/Latn.ORH/Sans_8/pdf_to_json_test_Latn.ORH_Sans_8.json 2>&1
Latn.ORH_Serif_12:
	-$(PYTHON) data/multilingual/Latn.ORH/Serif_12/pdf_to_json_test_Latn.ORH_Serif_12.py > data/multilingual/Latn.ORH/Serif_12/pdf_to_json_test_Latn.ORH_Serif_12.json 2>&1
Latn.ORH_Serif_16:
	-$(PYTHON) data/multilingual/Latn.ORH/Serif_16/pdf_to_json_test_Latn.ORH_Serif_16.py > data/multilingual/Latn.ORH/Serif_16/pdf_to_json_test_Latn.ORH_Serif_16.json 2>&1
Latn.ORH_Serif_8:
	-$(PYTHON) data/multilingual/Latn.ORH/Serif_8/pdf_to_json_test_Latn.ORH_Serif_8.py > data/multilingual/Latn.ORH/Serif_8/pdf_to_json_test_Latn.ORH_Serif_8.json 2>&1
Latn.ORH_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.ORH/Sun-ExtA_12/pdf_to_json_test_Latn.ORH_Sun-ExtA_12.py > data/multilingual/Latn.ORH/Sun-ExtA_12/pdf_to_json_test_Latn.ORH_Sun-ExtA_12.json 2>&1
Latn.ORH_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.ORH/Sun-ExtA_16/pdf_to_json_test_Latn.ORH_Sun-ExtA_16.py > data/multilingual/Latn.ORH/Sun-ExtA_16/pdf_to_json_test_Latn.ORH_Sun-ExtA_16.json 2>&1
Latn.ORH_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.ORH/Sun-ExtA_8/pdf_to_json_test_Latn.ORH_Sun-ExtA_8.py > data/multilingual/Latn.ORH/Sun-ExtA_8/pdf_to_json_test_Latn.ORH_Sun-ExtA_8.json 2>&1


Latn.ORH_all : Latn.ORH_Mono_12 Latn.ORH_Mono_16 Latn.ORH_Mono_8 Latn.ORH_Sans_12 Latn.ORH_Sans_16 Latn.ORH_Sans_8 Latn.ORH_Serif_12 Latn.ORH_Serif_16 Latn.ORH_Serif_8 Latn.ORH_Sun-ExtA_12 Latn.ORH_Sun-ExtA_16 Latn.ORH_Sun-ExtA_8
