PYTHON=python3


Latn.DAN_Mono_12:
	-$(PYTHON) data/multilingual/Latn.DAN/Mono_12/pdf_to_json_test_Latn.DAN_Mono_12.py > data/multilingual/Latn.DAN/Mono_12/pdf_to_json_test_Latn.DAN_Mono_12.json 2>&1
Latn.DAN_Mono_16:
	-$(PYTHON) data/multilingual/Latn.DAN/Mono_16/pdf_to_json_test_Latn.DAN_Mono_16.py > data/multilingual/Latn.DAN/Mono_16/pdf_to_json_test_Latn.DAN_Mono_16.json 2>&1
Latn.DAN_Mono_8:
	-$(PYTHON) data/multilingual/Latn.DAN/Mono_8/pdf_to_json_test_Latn.DAN_Mono_8.py > data/multilingual/Latn.DAN/Mono_8/pdf_to_json_test_Latn.DAN_Mono_8.json 2>&1
Latn.DAN_Sans_12:
	-$(PYTHON) data/multilingual/Latn.DAN/Sans_12/pdf_to_json_test_Latn.DAN_Sans_12.py > data/multilingual/Latn.DAN/Sans_12/pdf_to_json_test_Latn.DAN_Sans_12.json 2>&1
Latn.DAN_Sans_16:
	-$(PYTHON) data/multilingual/Latn.DAN/Sans_16/pdf_to_json_test_Latn.DAN_Sans_16.py > data/multilingual/Latn.DAN/Sans_16/pdf_to_json_test_Latn.DAN_Sans_16.json 2>&1
Latn.DAN_Sans_8:
	-$(PYTHON) data/multilingual/Latn.DAN/Sans_8/pdf_to_json_test_Latn.DAN_Sans_8.py > data/multilingual/Latn.DAN/Sans_8/pdf_to_json_test_Latn.DAN_Sans_8.json 2>&1
Latn.DAN_Serif_12:
	-$(PYTHON) data/multilingual/Latn.DAN/Serif_12/pdf_to_json_test_Latn.DAN_Serif_12.py > data/multilingual/Latn.DAN/Serif_12/pdf_to_json_test_Latn.DAN_Serif_12.json 2>&1
Latn.DAN_Serif_16:
	-$(PYTHON) data/multilingual/Latn.DAN/Serif_16/pdf_to_json_test_Latn.DAN_Serif_16.py > data/multilingual/Latn.DAN/Serif_16/pdf_to_json_test_Latn.DAN_Serif_16.json 2>&1
Latn.DAN_Serif_8:
	-$(PYTHON) data/multilingual/Latn.DAN/Serif_8/pdf_to_json_test_Latn.DAN_Serif_8.py > data/multilingual/Latn.DAN/Serif_8/pdf_to_json_test_Latn.DAN_Serif_8.json 2>&1
Latn.DAN_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.DAN/Sun-ExtA_12/pdf_to_json_test_Latn.DAN_Sun-ExtA_12.py > data/multilingual/Latn.DAN/Sun-ExtA_12/pdf_to_json_test_Latn.DAN_Sun-ExtA_12.json 2>&1
Latn.DAN_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.DAN/Sun-ExtA_16/pdf_to_json_test_Latn.DAN_Sun-ExtA_16.py > data/multilingual/Latn.DAN/Sun-ExtA_16/pdf_to_json_test_Latn.DAN_Sun-ExtA_16.json 2>&1
Latn.DAN_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.DAN/Sun-ExtA_8/pdf_to_json_test_Latn.DAN_Sun-ExtA_8.py > data/multilingual/Latn.DAN/Sun-ExtA_8/pdf_to_json_test_Latn.DAN_Sun-ExtA_8.json 2>&1


Latn.DAN_all : Latn.DAN_Mono_12 Latn.DAN_Mono_16 Latn.DAN_Mono_8 Latn.DAN_Sans_12 Latn.DAN_Sans_16 Latn.DAN_Sans_8 Latn.DAN_Serif_12 Latn.DAN_Serif_16 Latn.DAN_Serif_8 Latn.DAN_Sun-ExtA_12 Latn.DAN_Sun-ExtA_16 Latn.DAN_Sun-ExtA_8
