PYTHON=python3


Cyrl.BOS_Mono_12:
	-$(PYTHON) data/multilingual/Cyrl.BOS/Mono_12/pdf_to_json_test_Cyrl.BOS_Mono_12.py > data/multilingual/Cyrl.BOS/Mono_12/pdf_to_json_test_Cyrl.BOS_Mono_12.json 2>&1
Cyrl.BOS_Mono_16:
	-$(PYTHON) data/multilingual/Cyrl.BOS/Mono_16/pdf_to_json_test_Cyrl.BOS_Mono_16.py > data/multilingual/Cyrl.BOS/Mono_16/pdf_to_json_test_Cyrl.BOS_Mono_16.json 2>&1
Cyrl.BOS_Mono_8:
	-$(PYTHON) data/multilingual/Cyrl.BOS/Mono_8/pdf_to_json_test_Cyrl.BOS_Mono_8.py > data/multilingual/Cyrl.BOS/Mono_8/pdf_to_json_test_Cyrl.BOS_Mono_8.json 2>&1
Cyrl.BOS_Sans_12:
	-$(PYTHON) data/multilingual/Cyrl.BOS/Sans_12/pdf_to_json_test_Cyrl.BOS_Sans_12.py > data/multilingual/Cyrl.BOS/Sans_12/pdf_to_json_test_Cyrl.BOS_Sans_12.json 2>&1
Cyrl.BOS_Sans_16:
	-$(PYTHON) data/multilingual/Cyrl.BOS/Sans_16/pdf_to_json_test_Cyrl.BOS_Sans_16.py > data/multilingual/Cyrl.BOS/Sans_16/pdf_to_json_test_Cyrl.BOS_Sans_16.json 2>&1
Cyrl.BOS_Sans_8:
	-$(PYTHON) data/multilingual/Cyrl.BOS/Sans_8/pdf_to_json_test_Cyrl.BOS_Sans_8.py > data/multilingual/Cyrl.BOS/Sans_8/pdf_to_json_test_Cyrl.BOS_Sans_8.json 2>&1
Cyrl.BOS_Serif_12:
	-$(PYTHON) data/multilingual/Cyrl.BOS/Serif_12/pdf_to_json_test_Cyrl.BOS_Serif_12.py > data/multilingual/Cyrl.BOS/Serif_12/pdf_to_json_test_Cyrl.BOS_Serif_12.json 2>&1
Cyrl.BOS_Serif_16:
	-$(PYTHON) data/multilingual/Cyrl.BOS/Serif_16/pdf_to_json_test_Cyrl.BOS_Serif_16.py > data/multilingual/Cyrl.BOS/Serif_16/pdf_to_json_test_Cyrl.BOS_Serif_16.json 2>&1
Cyrl.BOS_Serif_8:
	-$(PYTHON) data/multilingual/Cyrl.BOS/Serif_8/pdf_to_json_test_Cyrl.BOS_Serif_8.py > data/multilingual/Cyrl.BOS/Serif_8/pdf_to_json_test_Cyrl.BOS_Serif_8.json 2>&1
Cyrl.BOS_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Cyrl.BOS/Sun-ExtA_12/pdf_to_json_test_Cyrl.BOS_Sun-ExtA_12.py > data/multilingual/Cyrl.BOS/Sun-ExtA_12/pdf_to_json_test_Cyrl.BOS_Sun-ExtA_12.json 2>&1
Cyrl.BOS_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Cyrl.BOS/Sun-ExtA_16/pdf_to_json_test_Cyrl.BOS_Sun-ExtA_16.py > data/multilingual/Cyrl.BOS/Sun-ExtA_16/pdf_to_json_test_Cyrl.BOS_Sun-ExtA_16.json 2>&1
Cyrl.BOS_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Cyrl.BOS/Sun-ExtA_8/pdf_to_json_test_Cyrl.BOS_Sun-ExtA_8.py > data/multilingual/Cyrl.BOS/Sun-ExtA_8/pdf_to_json_test_Cyrl.BOS_Sun-ExtA_8.json 2>&1


Cyrl.BOS_all : Cyrl.BOS_Mono_12 Cyrl.BOS_Mono_16 Cyrl.BOS_Mono_8 Cyrl.BOS_Sans_12 Cyrl.BOS_Sans_16 Cyrl.BOS_Sans_8 Cyrl.BOS_Serif_12 Cyrl.BOS_Serif_16 Cyrl.BOS_Serif_8 Cyrl.BOS_Sun-ExtA_12 Cyrl.BOS_Sun-ExtA_16 Cyrl.BOS_Sun-ExtA_8
