PYTHON=python3


Cyrl.RUS_Mono_12:
	-$(PYTHON) data/multilingual/Cyrl.RUS/Mono_12/pdf_to_json_test_Cyrl.RUS_Mono_12.py > data/multilingual/Cyrl.RUS/Mono_12/pdf_to_json_test_Cyrl.RUS_Mono_12.json 2>&1
Cyrl.RUS_Mono_16:
	-$(PYTHON) data/multilingual/Cyrl.RUS/Mono_16/pdf_to_json_test_Cyrl.RUS_Mono_16.py > data/multilingual/Cyrl.RUS/Mono_16/pdf_to_json_test_Cyrl.RUS_Mono_16.json 2>&1
Cyrl.RUS_Mono_8:
	-$(PYTHON) data/multilingual/Cyrl.RUS/Mono_8/pdf_to_json_test_Cyrl.RUS_Mono_8.py > data/multilingual/Cyrl.RUS/Mono_8/pdf_to_json_test_Cyrl.RUS_Mono_8.json 2>&1
Cyrl.RUS_Sans_12:
	-$(PYTHON) data/multilingual/Cyrl.RUS/Sans_12/pdf_to_json_test_Cyrl.RUS_Sans_12.py > data/multilingual/Cyrl.RUS/Sans_12/pdf_to_json_test_Cyrl.RUS_Sans_12.json 2>&1
Cyrl.RUS_Sans_16:
	-$(PYTHON) data/multilingual/Cyrl.RUS/Sans_16/pdf_to_json_test_Cyrl.RUS_Sans_16.py > data/multilingual/Cyrl.RUS/Sans_16/pdf_to_json_test_Cyrl.RUS_Sans_16.json 2>&1
Cyrl.RUS_Sans_8:
	-$(PYTHON) data/multilingual/Cyrl.RUS/Sans_8/pdf_to_json_test_Cyrl.RUS_Sans_8.py > data/multilingual/Cyrl.RUS/Sans_8/pdf_to_json_test_Cyrl.RUS_Sans_8.json 2>&1
Cyrl.RUS_Serif_12:
	-$(PYTHON) data/multilingual/Cyrl.RUS/Serif_12/pdf_to_json_test_Cyrl.RUS_Serif_12.py > data/multilingual/Cyrl.RUS/Serif_12/pdf_to_json_test_Cyrl.RUS_Serif_12.json 2>&1
Cyrl.RUS_Serif_16:
	-$(PYTHON) data/multilingual/Cyrl.RUS/Serif_16/pdf_to_json_test_Cyrl.RUS_Serif_16.py > data/multilingual/Cyrl.RUS/Serif_16/pdf_to_json_test_Cyrl.RUS_Serif_16.json 2>&1
Cyrl.RUS_Serif_8:
	-$(PYTHON) data/multilingual/Cyrl.RUS/Serif_8/pdf_to_json_test_Cyrl.RUS_Serif_8.py > data/multilingual/Cyrl.RUS/Serif_8/pdf_to_json_test_Cyrl.RUS_Serif_8.json 2>&1
Cyrl.RUS_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Cyrl.RUS/Sun-ExtA_12/pdf_to_json_test_Cyrl.RUS_Sun-ExtA_12.py > data/multilingual/Cyrl.RUS/Sun-ExtA_12/pdf_to_json_test_Cyrl.RUS_Sun-ExtA_12.json 2>&1
Cyrl.RUS_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Cyrl.RUS/Sun-ExtA_16/pdf_to_json_test_Cyrl.RUS_Sun-ExtA_16.py > data/multilingual/Cyrl.RUS/Sun-ExtA_16/pdf_to_json_test_Cyrl.RUS_Sun-ExtA_16.json 2>&1
Cyrl.RUS_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Cyrl.RUS/Sun-ExtA_8/pdf_to_json_test_Cyrl.RUS_Sun-ExtA_8.py > data/multilingual/Cyrl.RUS/Sun-ExtA_8/pdf_to_json_test_Cyrl.RUS_Sun-ExtA_8.json 2>&1


Cyrl.RUS_all : Cyrl.RUS_Mono_12 Cyrl.RUS_Mono_16 Cyrl.RUS_Mono_8 Cyrl.RUS_Sans_12 Cyrl.RUS_Sans_16 Cyrl.RUS_Sans_8 Cyrl.RUS_Serif_12 Cyrl.RUS_Serif_16 Cyrl.RUS_Serif_8 Cyrl.RUS_Sun-ExtA_12 Cyrl.RUS_Sun-ExtA_16 Cyrl.RUS_Sun-ExtA_8
