PYTHON=python3


Latn.RON_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.RON/Mono_12/pdf_to_json_test_Latn.RON_Mono_12.py" > "data/multilingual/Latn.RON/Mono_12/pdf_to_json_test_Latn.RON_Mono_12.json" 2>&1
Latn.RON_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.RON/Mono_16/pdf_to_json_test_Latn.RON_Mono_16.py" > "data/multilingual/Latn.RON/Mono_16/pdf_to_json_test_Latn.RON_Mono_16.json" 2>&1
Latn.RON_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.RON/Mono_8/pdf_to_json_test_Latn.RON_Mono_8.py" > "data/multilingual/Latn.RON/Mono_8/pdf_to_json_test_Latn.RON_Mono_8.json" 2>&1
Latn.RON_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.RON/Sans_12/pdf_to_json_test_Latn.RON_Sans_12.py" > "data/multilingual/Latn.RON/Sans_12/pdf_to_json_test_Latn.RON_Sans_12.json" 2>&1
Latn.RON_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.RON/Sans_16/pdf_to_json_test_Latn.RON_Sans_16.py" > "data/multilingual/Latn.RON/Sans_16/pdf_to_json_test_Latn.RON_Sans_16.json" 2>&1
Latn.RON_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.RON/Sans_8/pdf_to_json_test_Latn.RON_Sans_8.py" > "data/multilingual/Latn.RON/Sans_8/pdf_to_json_test_Latn.RON_Sans_8.json" 2>&1
Latn.RON_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.RON/Serif_12/pdf_to_json_test_Latn.RON_Serif_12.py" > "data/multilingual/Latn.RON/Serif_12/pdf_to_json_test_Latn.RON_Serif_12.json" 2>&1
Latn.RON_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.RON/Serif_16/pdf_to_json_test_Latn.RON_Serif_16.py" > "data/multilingual/Latn.RON/Serif_16/pdf_to_json_test_Latn.RON_Serif_16.json" 2>&1
Latn.RON_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.RON/Serif_8/pdf_to_json_test_Latn.RON_Serif_8.py" > "data/multilingual/Latn.RON/Serif_8/pdf_to_json_test_Latn.RON_Serif_8.json" 2>&1
Latn.RON_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.RON/Sun-ExtA_12/pdf_to_json_test_Latn.RON_Sun-ExtA_12.py" > "data/multilingual/Latn.RON/Sun-ExtA_12/pdf_to_json_test_Latn.RON_Sun-ExtA_12.json" 2>&1
Latn.RON_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.RON/Sun-ExtA_16/pdf_to_json_test_Latn.RON_Sun-ExtA_16.py" > "data/multilingual/Latn.RON/Sun-ExtA_16/pdf_to_json_test_Latn.RON_Sun-ExtA_16.json" 2>&1
Latn.RON_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.RON/Sun-ExtA_8/pdf_to_json_test_Latn.RON_Sun-ExtA_8.py" > "data/multilingual/Latn.RON/Sun-ExtA_8/pdf_to_json_test_Latn.RON_Sun-ExtA_8.json" 2>&1


Latn.RON_all : Latn.RON_Mono_12 Latn.RON_Mono_16 Latn.RON_Mono_8 Latn.RON_Sans_12 Latn.RON_Sans_16 Latn.RON_Sans_8 Latn.RON_Serif_12 Latn.RON_Serif_16 Latn.RON_Serif_8 Latn.RON_Sun-ExtA_12 Latn.RON_Sun-ExtA_16 Latn.RON_Sun-ExtA_8
