PYTHON=python3


Latn.LVS_Mono_12:
	-$(PYTHON) data/multilingual/Latn.LVS/Mono_12/pdf_to_json_test_Latn.LVS_Mono_12.py > data/multilingual/Latn.LVS/Mono_12/pdf_to_json_test_Latn.LVS_Mono_12.json 2>&1
Latn.LVS_Mono_16:
	-$(PYTHON) data/multilingual/Latn.LVS/Mono_16/pdf_to_json_test_Latn.LVS_Mono_16.py > data/multilingual/Latn.LVS/Mono_16/pdf_to_json_test_Latn.LVS_Mono_16.json 2>&1
Latn.LVS_Mono_8:
	-$(PYTHON) data/multilingual/Latn.LVS/Mono_8/pdf_to_json_test_Latn.LVS_Mono_8.py > data/multilingual/Latn.LVS/Mono_8/pdf_to_json_test_Latn.LVS_Mono_8.json 2>&1
Latn.LVS_Sans_12:
	-$(PYTHON) data/multilingual/Latn.LVS/Sans_12/pdf_to_json_test_Latn.LVS_Sans_12.py > data/multilingual/Latn.LVS/Sans_12/pdf_to_json_test_Latn.LVS_Sans_12.json 2>&1
Latn.LVS_Sans_16:
	-$(PYTHON) data/multilingual/Latn.LVS/Sans_16/pdf_to_json_test_Latn.LVS_Sans_16.py > data/multilingual/Latn.LVS/Sans_16/pdf_to_json_test_Latn.LVS_Sans_16.json 2>&1
Latn.LVS_Sans_8:
	-$(PYTHON) data/multilingual/Latn.LVS/Sans_8/pdf_to_json_test_Latn.LVS_Sans_8.py > data/multilingual/Latn.LVS/Sans_8/pdf_to_json_test_Latn.LVS_Sans_8.json 2>&1
Latn.LVS_Serif_12:
	-$(PYTHON) data/multilingual/Latn.LVS/Serif_12/pdf_to_json_test_Latn.LVS_Serif_12.py > data/multilingual/Latn.LVS/Serif_12/pdf_to_json_test_Latn.LVS_Serif_12.json 2>&1
Latn.LVS_Serif_16:
	-$(PYTHON) data/multilingual/Latn.LVS/Serif_16/pdf_to_json_test_Latn.LVS_Serif_16.py > data/multilingual/Latn.LVS/Serif_16/pdf_to_json_test_Latn.LVS_Serif_16.json 2>&1
Latn.LVS_Serif_8:
	-$(PYTHON) data/multilingual/Latn.LVS/Serif_8/pdf_to_json_test_Latn.LVS_Serif_8.py > data/multilingual/Latn.LVS/Serif_8/pdf_to_json_test_Latn.LVS_Serif_8.json 2>&1
Latn.LVS_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.LVS/Sun-ExtA_12/pdf_to_json_test_Latn.LVS_Sun-ExtA_12.py > data/multilingual/Latn.LVS/Sun-ExtA_12/pdf_to_json_test_Latn.LVS_Sun-ExtA_12.json 2>&1
Latn.LVS_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.LVS/Sun-ExtA_16/pdf_to_json_test_Latn.LVS_Sun-ExtA_16.py > data/multilingual/Latn.LVS/Sun-ExtA_16/pdf_to_json_test_Latn.LVS_Sun-ExtA_16.json 2>&1
Latn.LVS_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.LVS/Sun-ExtA_8/pdf_to_json_test_Latn.LVS_Sun-ExtA_8.py > data/multilingual/Latn.LVS/Sun-ExtA_8/pdf_to_json_test_Latn.LVS_Sun-ExtA_8.json 2>&1


Latn.LVS_all : Latn.LVS_Mono_12 Latn.LVS_Mono_16 Latn.LVS_Mono_8 Latn.LVS_Sans_12 Latn.LVS_Sans_16 Latn.LVS_Sans_8 Latn.LVS_Serif_12 Latn.LVS_Serif_16 Latn.LVS_Serif_8 Latn.LVS_Sun-ExtA_12 Latn.LVS_Sun-ExtA_16 Latn.LVS_Sun-ExtA_8
