PYTHON=python3


Hang.KOR_Mono_12:
	-$(PYTHON) "data/multilingual/Hang.KOR/Mono_12/pdf_to_json_test_Hang.KOR_Mono_12.py" > "data/multilingual/Hang.KOR/Mono_12/pdf_to_json_test_Hang.KOR_Mono_12.json" 2>&1
Hang.KOR_Mono_16:
	-$(PYTHON) "data/multilingual/Hang.KOR/Mono_16/pdf_to_json_test_Hang.KOR_Mono_16.py" > "data/multilingual/Hang.KOR/Mono_16/pdf_to_json_test_Hang.KOR_Mono_16.json" 2>&1
Hang.KOR_Mono_8:
	-$(PYTHON) "data/multilingual/Hang.KOR/Mono_8/pdf_to_json_test_Hang.KOR_Mono_8.py" > "data/multilingual/Hang.KOR/Mono_8/pdf_to_json_test_Hang.KOR_Mono_8.json" 2>&1
Hang.KOR_Sans_12:
	-$(PYTHON) "data/multilingual/Hang.KOR/Sans_12/pdf_to_json_test_Hang.KOR_Sans_12.py" > "data/multilingual/Hang.KOR/Sans_12/pdf_to_json_test_Hang.KOR_Sans_12.json" 2>&1
Hang.KOR_Sans_16:
	-$(PYTHON) "data/multilingual/Hang.KOR/Sans_16/pdf_to_json_test_Hang.KOR_Sans_16.py" > "data/multilingual/Hang.KOR/Sans_16/pdf_to_json_test_Hang.KOR_Sans_16.json" 2>&1
Hang.KOR_Sans_8:
	-$(PYTHON) "data/multilingual/Hang.KOR/Sans_8/pdf_to_json_test_Hang.KOR_Sans_8.py" > "data/multilingual/Hang.KOR/Sans_8/pdf_to_json_test_Hang.KOR_Sans_8.json" 2>&1
Hang.KOR_Serif_12:
	-$(PYTHON) "data/multilingual/Hang.KOR/Serif_12/pdf_to_json_test_Hang.KOR_Serif_12.py" > "data/multilingual/Hang.KOR/Serif_12/pdf_to_json_test_Hang.KOR_Serif_12.json" 2>&1
Hang.KOR_Serif_16:
	-$(PYTHON) "data/multilingual/Hang.KOR/Serif_16/pdf_to_json_test_Hang.KOR_Serif_16.py" > "data/multilingual/Hang.KOR/Serif_16/pdf_to_json_test_Hang.KOR_Serif_16.json" 2>&1
Hang.KOR_Serif_8:
	-$(PYTHON) "data/multilingual/Hang.KOR/Serif_8/pdf_to_json_test_Hang.KOR_Serif_8.py" > "data/multilingual/Hang.KOR/Serif_8/pdf_to_json_test_Hang.KOR_Serif_8.json" 2>&1
Hang.KOR_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Hang.KOR/Sun-ExtA_12/pdf_to_json_test_Hang.KOR_Sun-ExtA_12.py" > "data/multilingual/Hang.KOR/Sun-ExtA_12/pdf_to_json_test_Hang.KOR_Sun-ExtA_12.json" 2>&1
Hang.KOR_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Hang.KOR/Sun-ExtA_16/pdf_to_json_test_Hang.KOR_Sun-ExtA_16.py" > "data/multilingual/Hang.KOR/Sun-ExtA_16/pdf_to_json_test_Hang.KOR_Sun-ExtA_16.json" 2>&1
Hang.KOR_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Hang.KOR/Sun-ExtA_8/pdf_to_json_test_Hang.KOR_Sun-ExtA_8.py" > "data/multilingual/Hang.KOR/Sun-ExtA_8/pdf_to_json_test_Hang.KOR_Sun-ExtA_8.json" 2>&1


Hang.KOR_all : Hang.KOR_Mono_12 Hang.KOR_Mono_16 Hang.KOR_Mono_8 Hang.KOR_Sans_12 Hang.KOR_Sans_16 Hang.KOR_Sans_8 Hang.KOR_Serif_12 Hang.KOR_Serif_16 Hang.KOR_Serif_8 Hang.KOR_Sun-ExtA_12 Hang.KOR_Sun-ExtA_16 Hang.KOR_Sun-ExtA_8
