PYTHON=python3


Latn.IND_Mono_12:
	-$(PYTHON) data/multilingual/Latn.IND/Mono_12/pdf_to_json_test_Latn.IND_Mono_12.py > data/multilingual/Latn.IND/Mono_12/pdf_to_json_test_Latn.IND_Mono_12.json 2>&1
Latn.IND_Mono_16:
	-$(PYTHON) data/multilingual/Latn.IND/Mono_16/pdf_to_json_test_Latn.IND_Mono_16.py > data/multilingual/Latn.IND/Mono_16/pdf_to_json_test_Latn.IND_Mono_16.json 2>&1
Latn.IND_Mono_8:
	-$(PYTHON) data/multilingual/Latn.IND/Mono_8/pdf_to_json_test_Latn.IND_Mono_8.py > data/multilingual/Latn.IND/Mono_8/pdf_to_json_test_Latn.IND_Mono_8.json 2>&1
Latn.IND_Sans_12:
	-$(PYTHON) data/multilingual/Latn.IND/Sans_12/pdf_to_json_test_Latn.IND_Sans_12.py > data/multilingual/Latn.IND/Sans_12/pdf_to_json_test_Latn.IND_Sans_12.json 2>&1
Latn.IND_Sans_16:
	-$(PYTHON) data/multilingual/Latn.IND/Sans_16/pdf_to_json_test_Latn.IND_Sans_16.py > data/multilingual/Latn.IND/Sans_16/pdf_to_json_test_Latn.IND_Sans_16.json 2>&1
Latn.IND_Sans_8:
	-$(PYTHON) data/multilingual/Latn.IND/Sans_8/pdf_to_json_test_Latn.IND_Sans_8.py > data/multilingual/Latn.IND/Sans_8/pdf_to_json_test_Latn.IND_Sans_8.json 2>&1
Latn.IND_Serif_12:
	-$(PYTHON) data/multilingual/Latn.IND/Serif_12/pdf_to_json_test_Latn.IND_Serif_12.py > data/multilingual/Latn.IND/Serif_12/pdf_to_json_test_Latn.IND_Serif_12.json 2>&1
Latn.IND_Serif_16:
	-$(PYTHON) data/multilingual/Latn.IND/Serif_16/pdf_to_json_test_Latn.IND_Serif_16.py > data/multilingual/Latn.IND/Serif_16/pdf_to_json_test_Latn.IND_Serif_16.json 2>&1
Latn.IND_Serif_8:
	-$(PYTHON) data/multilingual/Latn.IND/Serif_8/pdf_to_json_test_Latn.IND_Serif_8.py > data/multilingual/Latn.IND/Serif_8/pdf_to_json_test_Latn.IND_Serif_8.json 2>&1
Latn.IND_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.IND/Sun-ExtA_12/pdf_to_json_test_Latn.IND_Sun-ExtA_12.py > data/multilingual/Latn.IND/Sun-ExtA_12/pdf_to_json_test_Latn.IND_Sun-ExtA_12.json 2>&1
Latn.IND_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.IND/Sun-ExtA_16/pdf_to_json_test_Latn.IND_Sun-ExtA_16.py > data/multilingual/Latn.IND/Sun-ExtA_16/pdf_to_json_test_Latn.IND_Sun-ExtA_16.json 2>&1
Latn.IND_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.IND/Sun-ExtA_8/pdf_to_json_test_Latn.IND_Sun-ExtA_8.py > data/multilingual/Latn.IND/Sun-ExtA_8/pdf_to_json_test_Latn.IND_Sun-ExtA_8.json 2>&1


Latn.IND_all : Latn.IND_Mono_12 Latn.IND_Mono_16 Latn.IND_Mono_8 Latn.IND_Sans_12 Latn.IND_Sans_16 Latn.IND_Sans_8 Latn.IND_Serif_12 Latn.IND_Serif_16 Latn.IND_Serif_8 Latn.IND_Sun-ExtA_12 Latn.IND_Sun-ExtA_16 Latn.IND_Sun-ExtA_8
