PYTHON=python3


Tibt.DZO_Mono_12:
	-$(PYTHON) data/multilingual/Tibt.DZO/Mono_12/pdf_to_json_test_Tibt.DZO_Mono_12.py > data/multilingual/Tibt.DZO/Mono_12/pdf_to_json_test_Tibt.DZO_Mono_12.json 2>&1
Tibt.DZO_Mono_16:
	-$(PYTHON) data/multilingual/Tibt.DZO/Mono_16/pdf_to_json_test_Tibt.DZO_Mono_16.py > data/multilingual/Tibt.DZO/Mono_16/pdf_to_json_test_Tibt.DZO_Mono_16.json 2>&1
Tibt.DZO_Mono_8:
	-$(PYTHON) data/multilingual/Tibt.DZO/Mono_8/pdf_to_json_test_Tibt.DZO_Mono_8.py > data/multilingual/Tibt.DZO/Mono_8/pdf_to_json_test_Tibt.DZO_Mono_8.json 2>&1
Tibt.DZO_Sans_12:
	-$(PYTHON) data/multilingual/Tibt.DZO/Sans_12/pdf_to_json_test_Tibt.DZO_Sans_12.py > data/multilingual/Tibt.DZO/Sans_12/pdf_to_json_test_Tibt.DZO_Sans_12.json 2>&1
Tibt.DZO_Sans_16:
	-$(PYTHON) data/multilingual/Tibt.DZO/Sans_16/pdf_to_json_test_Tibt.DZO_Sans_16.py > data/multilingual/Tibt.DZO/Sans_16/pdf_to_json_test_Tibt.DZO_Sans_16.json 2>&1
Tibt.DZO_Sans_8:
	-$(PYTHON) data/multilingual/Tibt.DZO/Sans_8/pdf_to_json_test_Tibt.DZO_Sans_8.py > data/multilingual/Tibt.DZO/Sans_8/pdf_to_json_test_Tibt.DZO_Sans_8.json 2>&1
Tibt.DZO_Serif_12:
	-$(PYTHON) data/multilingual/Tibt.DZO/Serif_12/pdf_to_json_test_Tibt.DZO_Serif_12.py > data/multilingual/Tibt.DZO/Serif_12/pdf_to_json_test_Tibt.DZO_Serif_12.json 2>&1
Tibt.DZO_Serif_16:
	-$(PYTHON) data/multilingual/Tibt.DZO/Serif_16/pdf_to_json_test_Tibt.DZO_Serif_16.py > data/multilingual/Tibt.DZO/Serif_16/pdf_to_json_test_Tibt.DZO_Serif_16.json 2>&1
Tibt.DZO_Serif_8:
	-$(PYTHON) data/multilingual/Tibt.DZO/Serif_8/pdf_to_json_test_Tibt.DZO_Serif_8.py > data/multilingual/Tibt.DZO/Serif_8/pdf_to_json_test_Tibt.DZO_Serif_8.json 2>&1
Tibt.DZO_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Tibt.DZO/Sun-ExtA_12/pdf_to_json_test_Tibt.DZO_Sun-ExtA_12.py > data/multilingual/Tibt.DZO/Sun-ExtA_12/pdf_to_json_test_Tibt.DZO_Sun-ExtA_12.json 2>&1
Tibt.DZO_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Tibt.DZO/Sun-ExtA_16/pdf_to_json_test_Tibt.DZO_Sun-ExtA_16.py > data/multilingual/Tibt.DZO/Sun-ExtA_16/pdf_to_json_test_Tibt.DZO_Sun-ExtA_16.json 2>&1
Tibt.DZO_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Tibt.DZO/Sun-ExtA_8/pdf_to_json_test_Tibt.DZO_Sun-ExtA_8.py > data/multilingual/Tibt.DZO/Sun-ExtA_8/pdf_to_json_test_Tibt.DZO_Sun-ExtA_8.json 2>&1


Tibt.DZO_all : Tibt.DZO_Mono_12 Tibt.DZO_Mono_16 Tibt.DZO_Mono_8 Tibt.DZO_Sans_12 Tibt.DZO_Sans_16 Tibt.DZO_Sans_8 Tibt.DZO_Serif_12 Tibt.DZO_Serif_16 Tibt.DZO_Serif_8 Tibt.DZO_Sun-ExtA_12 Tibt.DZO_Sun-ExtA_16 Tibt.DZO_Sun-ExtA_8
