PYTHON=python3


Latn.NKU_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.NKU/Mono_12/pdf_to_json_test_Latn.NKU_Mono_12.py" > "data/multilingual/Latn.NKU/Mono_12/pdf_to_json_test_Latn.NKU_Mono_12.json" 2>&1
Latn.NKU_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.NKU/Mono_16/pdf_to_json_test_Latn.NKU_Mono_16.py" > "data/multilingual/Latn.NKU/Mono_16/pdf_to_json_test_Latn.NKU_Mono_16.json" 2>&1
Latn.NKU_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.NKU/Mono_8/pdf_to_json_test_Latn.NKU_Mono_8.py" > "data/multilingual/Latn.NKU/Mono_8/pdf_to_json_test_Latn.NKU_Mono_8.json" 2>&1
Latn.NKU_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.NKU/Sans_12/pdf_to_json_test_Latn.NKU_Sans_12.py" > "data/multilingual/Latn.NKU/Sans_12/pdf_to_json_test_Latn.NKU_Sans_12.json" 2>&1
Latn.NKU_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.NKU/Sans_16/pdf_to_json_test_Latn.NKU_Sans_16.py" > "data/multilingual/Latn.NKU/Sans_16/pdf_to_json_test_Latn.NKU_Sans_16.json" 2>&1
Latn.NKU_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.NKU/Sans_8/pdf_to_json_test_Latn.NKU_Sans_8.py" > "data/multilingual/Latn.NKU/Sans_8/pdf_to_json_test_Latn.NKU_Sans_8.json" 2>&1
Latn.NKU_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.NKU/Serif_12/pdf_to_json_test_Latn.NKU_Serif_12.py" > "data/multilingual/Latn.NKU/Serif_12/pdf_to_json_test_Latn.NKU_Serif_12.json" 2>&1
Latn.NKU_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.NKU/Serif_16/pdf_to_json_test_Latn.NKU_Serif_16.py" > "data/multilingual/Latn.NKU/Serif_16/pdf_to_json_test_Latn.NKU_Serif_16.json" 2>&1
Latn.NKU_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.NKU/Serif_8/pdf_to_json_test_Latn.NKU_Serif_8.py" > "data/multilingual/Latn.NKU/Serif_8/pdf_to_json_test_Latn.NKU_Serif_8.json" 2>&1
Latn.NKU_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.NKU/Sun-ExtA_12/pdf_to_json_test_Latn.NKU_Sun-ExtA_12.py" > "data/multilingual/Latn.NKU/Sun-ExtA_12/pdf_to_json_test_Latn.NKU_Sun-ExtA_12.json" 2>&1
Latn.NKU_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.NKU/Sun-ExtA_16/pdf_to_json_test_Latn.NKU_Sun-ExtA_16.py" > "data/multilingual/Latn.NKU/Sun-ExtA_16/pdf_to_json_test_Latn.NKU_Sun-ExtA_16.json" 2>&1
Latn.NKU_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.NKU/Sun-ExtA_8/pdf_to_json_test_Latn.NKU_Sun-ExtA_8.py" > "data/multilingual/Latn.NKU/Sun-ExtA_8/pdf_to_json_test_Latn.NKU_Sun-ExtA_8.json" 2>&1


Latn.NKU_all : Latn.NKU_Mono_12 Latn.NKU_Mono_16 Latn.NKU_Mono_8 Latn.NKU_Sans_12 Latn.NKU_Sans_16 Latn.NKU_Sans_8 Latn.NKU_Serif_12 Latn.NKU_Serif_16 Latn.NKU_Serif_8 Latn.NKU_Sun-ExtA_12 Latn.NKU_Sun-ExtA_16 Latn.NKU_Sun-ExtA_8
