PYTHON=python3


Latn.ZUL_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.ZUL/Mono_12/pdf_to_json_test_Latn.ZUL_Mono_12.py" > "data/multilingual/Latn.ZUL/Mono_12/pdf_to_json_test_Latn.ZUL_Mono_12.json" 2>&1
Latn.ZUL_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.ZUL/Mono_16/pdf_to_json_test_Latn.ZUL_Mono_16.py" > "data/multilingual/Latn.ZUL/Mono_16/pdf_to_json_test_Latn.ZUL_Mono_16.json" 2>&1
Latn.ZUL_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.ZUL/Mono_8/pdf_to_json_test_Latn.ZUL_Mono_8.py" > "data/multilingual/Latn.ZUL/Mono_8/pdf_to_json_test_Latn.ZUL_Mono_8.json" 2>&1
Latn.ZUL_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.ZUL/Sans_12/pdf_to_json_test_Latn.ZUL_Sans_12.py" > "data/multilingual/Latn.ZUL/Sans_12/pdf_to_json_test_Latn.ZUL_Sans_12.json" 2>&1
Latn.ZUL_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.ZUL/Sans_16/pdf_to_json_test_Latn.ZUL_Sans_16.py" > "data/multilingual/Latn.ZUL/Sans_16/pdf_to_json_test_Latn.ZUL_Sans_16.json" 2>&1
Latn.ZUL_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.ZUL/Sans_8/pdf_to_json_test_Latn.ZUL_Sans_8.py" > "data/multilingual/Latn.ZUL/Sans_8/pdf_to_json_test_Latn.ZUL_Sans_8.json" 2>&1
Latn.ZUL_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.ZUL/Serif_12/pdf_to_json_test_Latn.ZUL_Serif_12.py" > "data/multilingual/Latn.ZUL/Serif_12/pdf_to_json_test_Latn.ZUL_Serif_12.json" 2>&1
Latn.ZUL_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.ZUL/Serif_16/pdf_to_json_test_Latn.ZUL_Serif_16.py" > "data/multilingual/Latn.ZUL/Serif_16/pdf_to_json_test_Latn.ZUL_Serif_16.json" 2>&1
Latn.ZUL_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.ZUL/Serif_8/pdf_to_json_test_Latn.ZUL_Serif_8.py" > "data/multilingual/Latn.ZUL/Serif_8/pdf_to_json_test_Latn.ZUL_Serif_8.json" 2>&1
Latn.ZUL_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.ZUL/Sun-ExtA_12/pdf_to_json_test_Latn.ZUL_Sun-ExtA_12.py" > "data/multilingual/Latn.ZUL/Sun-ExtA_12/pdf_to_json_test_Latn.ZUL_Sun-ExtA_12.json" 2>&1
Latn.ZUL_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.ZUL/Sun-ExtA_16/pdf_to_json_test_Latn.ZUL_Sun-ExtA_16.py" > "data/multilingual/Latn.ZUL/Sun-ExtA_16/pdf_to_json_test_Latn.ZUL_Sun-ExtA_16.json" 2>&1
Latn.ZUL_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.ZUL/Sun-ExtA_8/pdf_to_json_test_Latn.ZUL_Sun-ExtA_8.py" > "data/multilingual/Latn.ZUL/Sun-ExtA_8/pdf_to_json_test_Latn.ZUL_Sun-ExtA_8.json" 2>&1


Latn.ZUL_all : Latn.ZUL_Mono_12 Latn.ZUL_Mono_16 Latn.ZUL_Mono_8 Latn.ZUL_Sans_12 Latn.ZUL_Sans_16 Latn.ZUL_Sans_8 Latn.ZUL_Serif_12 Latn.ZUL_Serif_16 Latn.ZUL_Serif_8 Latn.ZUL_Sun-ExtA_12 Latn.ZUL_Sun-ExtA_16 Latn.ZUL_Sun-ExtA_8
