PYTHON=python3


Deva.MAI_Mono_12:
	-$(PYTHON) "data/multilingual/Deva.MAI/Mono_12/pdf_to_json_test_Deva.MAI_Mono_12.py" > "data/multilingual/Deva.MAI/Mono_12/pdf_to_json_test_Deva.MAI_Mono_12.json" 2>&1
Deva.MAI_Mono_16:
	-$(PYTHON) "data/multilingual/Deva.MAI/Mono_16/pdf_to_json_test_Deva.MAI_Mono_16.py" > "data/multilingual/Deva.MAI/Mono_16/pdf_to_json_test_Deva.MAI_Mono_16.json" 2>&1
Deva.MAI_Mono_8:
	-$(PYTHON) "data/multilingual/Deva.MAI/Mono_8/pdf_to_json_test_Deva.MAI_Mono_8.py" > "data/multilingual/Deva.MAI/Mono_8/pdf_to_json_test_Deva.MAI_Mono_8.json" 2>&1
Deva.MAI_Sans_12:
	-$(PYTHON) "data/multilingual/Deva.MAI/Sans_12/pdf_to_json_test_Deva.MAI_Sans_12.py" > "data/multilingual/Deva.MAI/Sans_12/pdf_to_json_test_Deva.MAI_Sans_12.json" 2>&1
Deva.MAI_Sans_16:
	-$(PYTHON) "data/multilingual/Deva.MAI/Sans_16/pdf_to_json_test_Deva.MAI_Sans_16.py" > "data/multilingual/Deva.MAI/Sans_16/pdf_to_json_test_Deva.MAI_Sans_16.json" 2>&1
Deva.MAI_Sans_8:
	-$(PYTHON) "data/multilingual/Deva.MAI/Sans_8/pdf_to_json_test_Deva.MAI_Sans_8.py" > "data/multilingual/Deva.MAI/Sans_8/pdf_to_json_test_Deva.MAI_Sans_8.json" 2>&1
Deva.MAI_Serif_12:
	-$(PYTHON) "data/multilingual/Deva.MAI/Serif_12/pdf_to_json_test_Deva.MAI_Serif_12.py" > "data/multilingual/Deva.MAI/Serif_12/pdf_to_json_test_Deva.MAI_Serif_12.json" 2>&1
Deva.MAI_Serif_16:
	-$(PYTHON) "data/multilingual/Deva.MAI/Serif_16/pdf_to_json_test_Deva.MAI_Serif_16.py" > "data/multilingual/Deva.MAI/Serif_16/pdf_to_json_test_Deva.MAI_Serif_16.json" 2>&1
Deva.MAI_Serif_8:
	-$(PYTHON) "data/multilingual/Deva.MAI/Serif_8/pdf_to_json_test_Deva.MAI_Serif_8.py" > "data/multilingual/Deva.MAI/Serif_8/pdf_to_json_test_Deva.MAI_Serif_8.json" 2>&1
Deva.MAI_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Deva.MAI/Sun-ExtA_12/pdf_to_json_test_Deva.MAI_Sun-ExtA_12.py" > "data/multilingual/Deva.MAI/Sun-ExtA_12/pdf_to_json_test_Deva.MAI_Sun-ExtA_12.json" 2>&1
Deva.MAI_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Deva.MAI/Sun-ExtA_16/pdf_to_json_test_Deva.MAI_Sun-ExtA_16.py" > "data/multilingual/Deva.MAI/Sun-ExtA_16/pdf_to_json_test_Deva.MAI_Sun-ExtA_16.json" 2>&1
Deva.MAI_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Deva.MAI/Sun-ExtA_8/pdf_to_json_test_Deva.MAI_Sun-ExtA_8.py" > "data/multilingual/Deva.MAI/Sun-ExtA_8/pdf_to_json_test_Deva.MAI_Sun-ExtA_8.json" 2>&1


Deva.MAI_all : Deva.MAI_Mono_12 Deva.MAI_Mono_16 Deva.MAI_Mono_8 Deva.MAI_Sans_12 Deva.MAI_Sans_16 Deva.MAI_Sans_8 Deva.MAI_Serif_12 Deva.MAI_Serif_16 Deva.MAI_Serif_8 Deva.MAI_Sun-ExtA_12 Deva.MAI_Sun-ExtA_16 Deva.MAI_Sun-ExtA_8
