PYTHON=python3


Latn.EMK_Mono_12:
	-$(PYTHON) data/multilingual/Latn.EMK/Mono_12/pdf_to_json_test_Latn.EMK_Mono_12.py > data/multilingual/Latn.EMK/Mono_12/pdf_to_json_test_Latn.EMK_Mono_12.json 2>&1
Latn.EMK_Mono_16:
	-$(PYTHON) data/multilingual/Latn.EMK/Mono_16/pdf_to_json_test_Latn.EMK_Mono_16.py > data/multilingual/Latn.EMK/Mono_16/pdf_to_json_test_Latn.EMK_Mono_16.json 2>&1
Latn.EMK_Mono_8:
	-$(PYTHON) data/multilingual/Latn.EMK/Mono_8/pdf_to_json_test_Latn.EMK_Mono_8.py > data/multilingual/Latn.EMK/Mono_8/pdf_to_json_test_Latn.EMK_Mono_8.json 2>&1
Latn.EMK_Sans_12:
	-$(PYTHON) data/multilingual/Latn.EMK/Sans_12/pdf_to_json_test_Latn.EMK_Sans_12.py > data/multilingual/Latn.EMK/Sans_12/pdf_to_json_test_Latn.EMK_Sans_12.json 2>&1
Latn.EMK_Sans_16:
	-$(PYTHON) data/multilingual/Latn.EMK/Sans_16/pdf_to_json_test_Latn.EMK_Sans_16.py > data/multilingual/Latn.EMK/Sans_16/pdf_to_json_test_Latn.EMK_Sans_16.json 2>&1
Latn.EMK_Sans_8:
	-$(PYTHON) data/multilingual/Latn.EMK/Sans_8/pdf_to_json_test_Latn.EMK_Sans_8.py > data/multilingual/Latn.EMK/Sans_8/pdf_to_json_test_Latn.EMK_Sans_8.json 2>&1
Latn.EMK_Serif_12:
	-$(PYTHON) data/multilingual/Latn.EMK/Serif_12/pdf_to_json_test_Latn.EMK_Serif_12.py > data/multilingual/Latn.EMK/Serif_12/pdf_to_json_test_Latn.EMK_Serif_12.json 2>&1
Latn.EMK_Serif_16:
	-$(PYTHON) data/multilingual/Latn.EMK/Serif_16/pdf_to_json_test_Latn.EMK_Serif_16.py > data/multilingual/Latn.EMK/Serif_16/pdf_to_json_test_Latn.EMK_Serif_16.json 2>&1
Latn.EMK_Serif_8:
	-$(PYTHON) data/multilingual/Latn.EMK/Serif_8/pdf_to_json_test_Latn.EMK_Serif_8.py > data/multilingual/Latn.EMK/Serif_8/pdf_to_json_test_Latn.EMK_Serif_8.json 2>&1
Latn.EMK_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.EMK/Sun-ExtA_12/pdf_to_json_test_Latn.EMK_Sun-ExtA_12.py > data/multilingual/Latn.EMK/Sun-ExtA_12/pdf_to_json_test_Latn.EMK_Sun-ExtA_12.json 2>&1
Latn.EMK_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.EMK/Sun-ExtA_16/pdf_to_json_test_Latn.EMK_Sun-ExtA_16.py > data/multilingual/Latn.EMK/Sun-ExtA_16/pdf_to_json_test_Latn.EMK_Sun-ExtA_16.json 2>&1
Latn.EMK_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.EMK/Sun-ExtA_8/pdf_to_json_test_Latn.EMK_Sun-ExtA_8.py > data/multilingual/Latn.EMK/Sun-ExtA_8/pdf_to_json_test_Latn.EMK_Sun-ExtA_8.json 2>&1


Latn.EMK_all : Latn.EMK_Mono_12 Latn.EMK_Mono_16 Latn.EMK_Mono_8 Latn.EMK_Sans_12 Latn.EMK_Sans_16 Latn.EMK_Sans_8 Latn.EMK_Serif_12 Latn.EMK_Serif_16 Latn.EMK_Serif_8 Latn.EMK_Sun-ExtA_12 Latn.EMK_Sun-ExtA_16 Latn.EMK_Sun-ExtA_8
