PYTHON=python3


Tfng.ZGH_Mono_12:
	-$(PYTHON) data/multilingual/Tfng.ZGH/Mono_12/pdf_to_json_test_Tfng.ZGH_Mono_12.py > data/multilingual/Tfng.ZGH/Mono_12/pdf_to_json_test_Tfng.ZGH_Mono_12.json 2>&1
Tfng.ZGH_Mono_16:
	-$(PYTHON) data/multilingual/Tfng.ZGH/Mono_16/pdf_to_json_test_Tfng.ZGH_Mono_16.py > data/multilingual/Tfng.ZGH/Mono_16/pdf_to_json_test_Tfng.ZGH_Mono_16.json 2>&1
Tfng.ZGH_Mono_8:
	-$(PYTHON) data/multilingual/Tfng.ZGH/Mono_8/pdf_to_json_test_Tfng.ZGH_Mono_8.py > data/multilingual/Tfng.ZGH/Mono_8/pdf_to_json_test_Tfng.ZGH_Mono_8.json 2>&1
Tfng.ZGH_Sans_12:
	-$(PYTHON) data/multilingual/Tfng.ZGH/Sans_12/pdf_to_json_test_Tfng.ZGH_Sans_12.py > data/multilingual/Tfng.ZGH/Sans_12/pdf_to_json_test_Tfng.ZGH_Sans_12.json 2>&1
Tfng.ZGH_Sans_16:
	-$(PYTHON) data/multilingual/Tfng.ZGH/Sans_16/pdf_to_json_test_Tfng.ZGH_Sans_16.py > data/multilingual/Tfng.ZGH/Sans_16/pdf_to_json_test_Tfng.ZGH_Sans_16.json 2>&1
Tfng.ZGH_Sans_8:
	-$(PYTHON) data/multilingual/Tfng.ZGH/Sans_8/pdf_to_json_test_Tfng.ZGH_Sans_8.py > data/multilingual/Tfng.ZGH/Sans_8/pdf_to_json_test_Tfng.ZGH_Sans_8.json 2>&1
Tfng.ZGH_Serif_12:
	-$(PYTHON) data/multilingual/Tfng.ZGH/Serif_12/pdf_to_json_test_Tfng.ZGH_Serif_12.py > data/multilingual/Tfng.ZGH/Serif_12/pdf_to_json_test_Tfng.ZGH_Serif_12.json 2>&1
Tfng.ZGH_Serif_16:
	-$(PYTHON) data/multilingual/Tfng.ZGH/Serif_16/pdf_to_json_test_Tfng.ZGH_Serif_16.py > data/multilingual/Tfng.ZGH/Serif_16/pdf_to_json_test_Tfng.ZGH_Serif_16.json 2>&1
Tfng.ZGH_Serif_8:
	-$(PYTHON) data/multilingual/Tfng.ZGH/Serif_8/pdf_to_json_test_Tfng.ZGH_Serif_8.py > data/multilingual/Tfng.ZGH/Serif_8/pdf_to_json_test_Tfng.ZGH_Serif_8.json 2>&1
Tfng.ZGH_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Tfng.ZGH/Sun-ExtA_12/pdf_to_json_test_Tfng.ZGH_Sun-ExtA_12.py > data/multilingual/Tfng.ZGH/Sun-ExtA_12/pdf_to_json_test_Tfng.ZGH_Sun-ExtA_12.json 2>&1
Tfng.ZGH_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Tfng.ZGH/Sun-ExtA_16/pdf_to_json_test_Tfng.ZGH_Sun-ExtA_16.py > data/multilingual/Tfng.ZGH/Sun-ExtA_16/pdf_to_json_test_Tfng.ZGH_Sun-ExtA_16.json 2>&1
Tfng.ZGH_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Tfng.ZGH/Sun-ExtA_8/pdf_to_json_test_Tfng.ZGH_Sun-ExtA_8.py > data/multilingual/Tfng.ZGH/Sun-ExtA_8/pdf_to_json_test_Tfng.ZGH_Sun-ExtA_8.json 2>&1


Tfng.ZGH_all : Tfng.ZGH_Mono_12 Tfng.ZGH_Mono_16 Tfng.ZGH_Mono_8 Tfng.ZGH_Sans_12 Tfng.ZGH_Sans_16 Tfng.ZGH_Sans_8 Tfng.ZGH_Serif_12 Tfng.ZGH_Serif_16 Tfng.ZGH_Serif_8 Tfng.ZGH_Sun-ExtA_12 Tfng.ZGH_Sun-ExtA_16 Tfng.ZGH_Sun-ExtA_8
