PYTHON=python3


Latn.PIU_Mono_12:
	-$(PYTHON) data/multilingual/Latn.PIU/Mono_12/pdf_to_json_test_Latn.PIU_Mono_12.py > data/multilingual/Latn.PIU/Mono_12/pdf_to_json_test_Latn.PIU_Mono_12.json 2>&1
Latn.PIU_Mono_16:
	-$(PYTHON) data/multilingual/Latn.PIU/Mono_16/pdf_to_json_test_Latn.PIU_Mono_16.py > data/multilingual/Latn.PIU/Mono_16/pdf_to_json_test_Latn.PIU_Mono_16.json 2>&1
Latn.PIU_Mono_8:
	-$(PYTHON) data/multilingual/Latn.PIU/Mono_8/pdf_to_json_test_Latn.PIU_Mono_8.py > data/multilingual/Latn.PIU/Mono_8/pdf_to_json_test_Latn.PIU_Mono_8.json 2>&1
Latn.PIU_Sans_12:
	-$(PYTHON) data/multilingual/Latn.PIU/Sans_12/pdf_to_json_test_Latn.PIU_Sans_12.py > data/multilingual/Latn.PIU/Sans_12/pdf_to_json_test_Latn.PIU_Sans_12.json 2>&1
Latn.PIU_Sans_16:
	-$(PYTHON) data/multilingual/Latn.PIU/Sans_16/pdf_to_json_test_Latn.PIU_Sans_16.py > data/multilingual/Latn.PIU/Sans_16/pdf_to_json_test_Latn.PIU_Sans_16.json 2>&1
Latn.PIU_Sans_8:
	-$(PYTHON) data/multilingual/Latn.PIU/Sans_8/pdf_to_json_test_Latn.PIU_Sans_8.py > data/multilingual/Latn.PIU/Sans_8/pdf_to_json_test_Latn.PIU_Sans_8.json 2>&1
Latn.PIU_Serif_12:
	-$(PYTHON) data/multilingual/Latn.PIU/Serif_12/pdf_to_json_test_Latn.PIU_Serif_12.py > data/multilingual/Latn.PIU/Serif_12/pdf_to_json_test_Latn.PIU_Serif_12.json 2>&1
Latn.PIU_Serif_16:
	-$(PYTHON) data/multilingual/Latn.PIU/Serif_16/pdf_to_json_test_Latn.PIU_Serif_16.py > data/multilingual/Latn.PIU/Serif_16/pdf_to_json_test_Latn.PIU_Serif_16.json 2>&1
Latn.PIU_Serif_8:
	-$(PYTHON) data/multilingual/Latn.PIU/Serif_8/pdf_to_json_test_Latn.PIU_Serif_8.py > data/multilingual/Latn.PIU/Serif_8/pdf_to_json_test_Latn.PIU_Serif_8.json 2>&1
Latn.PIU_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.PIU/Sun-ExtA_12/pdf_to_json_test_Latn.PIU_Sun-ExtA_12.py > data/multilingual/Latn.PIU/Sun-ExtA_12/pdf_to_json_test_Latn.PIU_Sun-ExtA_12.json 2>&1
Latn.PIU_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.PIU/Sun-ExtA_16/pdf_to_json_test_Latn.PIU_Sun-ExtA_16.py > data/multilingual/Latn.PIU/Sun-ExtA_16/pdf_to_json_test_Latn.PIU_Sun-ExtA_16.json 2>&1
Latn.PIU_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.PIU/Sun-ExtA_8/pdf_to_json_test_Latn.PIU_Sun-ExtA_8.py > data/multilingual/Latn.PIU/Sun-ExtA_8/pdf_to_json_test_Latn.PIU_Sun-ExtA_8.json 2>&1


Latn.PIU_all : Latn.PIU_Mono_12 Latn.PIU_Mono_16 Latn.PIU_Mono_8 Latn.PIU_Sans_12 Latn.PIU_Sans_16 Latn.PIU_Sans_8 Latn.PIU_Serif_12 Latn.PIU_Serif_16 Latn.PIU_Serif_8 Latn.PIU_Sun-ExtA_12 Latn.PIU_Sun-ExtA_16 Latn.PIU_Sun-ExtA_8
