PYTHON=python3


Jpan.JPN_Mono_12:
	-$(PYTHON) "data/multilingual/Jpan.JPN/Mono_12/pdf_to_json_test_Jpan.JPN_Mono_12.py" > "data/multilingual/Jpan.JPN/Mono_12/pdf_to_json_test_Jpan.JPN_Mono_12.json" 2>&1
Jpan.JPN_Mono_16:
	-$(PYTHON) "data/multilingual/Jpan.JPN/Mono_16/pdf_to_json_test_Jpan.JPN_Mono_16.py" > "data/multilingual/Jpan.JPN/Mono_16/pdf_to_json_test_Jpan.JPN_Mono_16.json" 2>&1
Jpan.JPN_Mono_8:
	-$(PYTHON) "data/multilingual/Jpan.JPN/Mono_8/pdf_to_json_test_Jpan.JPN_Mono_8.py" > "data/multilingual/Jpan.JPN/Mono_8/pdf_to_json_test_Jpan.JPN_Mono_8.json" 2>&1
Jpan.JPN_Sans_12:
	-$(PYTHON) "data/multilingual/Jpan.JPN/Sans_12/pdf_to_json_test_Jpan.JPN_Sans_12.py" > "data/multilingual/Jpan.JPN/Sans_12/pdf_to_json_test_Jpan.JPN_Sans_12.json" 2>&1
Jpan.JPN_Sans_16:
	-$(PYTHON) "data/multilingual/Jpan.JPN/Sans_16/pdf_to_json_test_Jpan.JPN_Sans_16.py" > "data/multilingual/Jpan.JPN/Sans_16/pdf_to_json_test_Jpan.JPN_Sans_16.json" 2>&1
Jpan.JPN_Sans_8:
	-$(PYTHON) "data/multilingual/Jpan.JPN/Sans_8/pdf_to_json_test_Jpan.JPN_Sans_8.py" > "data/multilingual/Jpan.JPN/Sans_8/pdf_to_json_test_Jpan.JPN_Sans_8.json" 2>&1
Jpan.JPN_Serif_12:
	-$(PYTHON) "data/multilingual/Jpan.JPN/Serif_12/pdf_to_json_test_Jpan.JPN_Serif_12.py" > "data/multilingual/Jpan.JPN/Serif_12/pdf_to_json_test_Jpan.JPN_Serif_12.json" 2>&1
Jpan.JPN_Serif_16:
	-$(PYTHON) "data/multilingual/Jpan.JPN/Serif_16/pdf_to_json_test_Jpan.JPN_Serif_16.py" > "data/multilingual/Jpan.JPN/Serif_16/pdf_to_json_test_Jpan.JPN_Serif_16.json" 2>&1
Jpan.JPN_Serif_8:
	-$(PYTHON) "data/multilingual/Jpan.JPN/Serif_8/pdf_to_json_test_Jpan.JPN_Serif_8.py" > "data/multilingual/Jpan.JPN/Serif_8/pdf_to_json_test_Jpan.JPN_Serif_8.json" 2>&1
Jpan.JPN_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Jpan.JPN/Sun-ExtA_12/pdf_to_json_test_Jpan.JPN_Sun-ExtA_12.py" > "data/multilingual/Jpan.JPN/Sun-ExtA_12/pdf_to_json_test_Jpan.JPN_Sun-ExtA_12.json" 2>&1
Jpan.JPN_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Jpan.JPN/Sun-ExtA_16/pdf_to_json_test_Jpan.JPN_Sun-ExtA_16.py" > "data/multilingual/Jpan.JPN/Sun-ExtA_16/pdf_to_json_test_Jpan.JPN_Sun-ExtA_16.json" 2>&1
Jpan.JPN_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Jpan.JPN/Sun-ExtA_8/pdf_to_json_test_Jpan.JPN_Sun-ExtA_8.py" > "data/multilingual/Jpan.JPN/Sun-ExtA_8/pdf_to_json_test_Jpan.JPN_Sun-ExtA_8.json" 2>&1


Jpan.JPN_all : Jpan.JPN_Mono_12 Jpan.JPN_Mono_16 Jpan.JPN_Mono_8 Jpan.JPN_Sans_12 Jpan.JPN_Sans_16 Jpan.JPN_Sans_8 Jpan.JPN_Serif_12 Jpan.JPN_Serif_16 Jpan.JPN_Serif_8 Jpan.JPN_Sun-ExtA_12 Jpan.JPN_Sun-ExtA_16 Jpan.JPN_Sun-ExtA_8
