PYTHON=python3


Arab.PBU_Mono_12:
	-$(PYTHON) "data/multilingual/Arab.PBU/Mono_12/pdf_to_json_test_Arab.PBU_Mono_12.py" > "data/multilingual/Arab.PBU/Mono_12/pdf_to_json_test_Arab.PBU_Mono_12.json" 2>&1
Arab.PBU_Mono_16:
	-$(PYTHON) "data/multilingual/Arab.PBU/Mono_16/pdf_to_json_test_Arab.PBU_Mono_16.py" > "data/multilingual/Arab.PBU/Mono_16/pdf_to_json_test_Arab.PBU_Mono_16.json" 2>&1
Arab.PBU_Mono_8:
	-$(PYTHON) "data/multilingual/Arab.PBU/Mono_8/pdf_to_json_test_Arab.PBU_Mono_8.py" > "data/multilingual/Arab.PBU/Mono_8/pdf_to_json_test_Arab.PBU_Mono_8.json" 2>&1
Arab.PBU_Sans_12:
	-$(PYTHON) "data/multilingual/Arab.PBU/Sans_12/pdf_to_json_test_Arab.PBU_Sans_12.py" > "data/multilingual/Arab.PBU/Sans_12/pdf_to_json_test_Arab.PBU_Sans_12.json" 2>&1
Arab.PBU_Sans_16:
	-$(PYTHON) "data/multilingual/Arab.PBU/Sans_16/pdf_to_json_test_Arab.PBU_Sans_16.py" > "data/multilingual/Arab.PBU/Sans_16/pdf_to_json_test_Arab.PBU_Sans_16.json" 2>&1
Arab.PBU_Sans_8:
	-$(PYTHON) "data/multilingual/Arab.PBU/Sans_8/pdf_to_json_test_Arab.PBU_Sans_8.py" > "data/multilingual/Arab.PBU/Sans_8/pdf_to_json_test_Arab.PBU_Sans_8.json" 2>&1
Arab.PBU_Serif_12:
	-$(PYTHON) "data/multilingual/Arab.PBU/Serif_12/pdf_to_json_test_Arab.PBU_Serif_12.py" > "data/multilingual/Arab.PBU/Serif_12/pdf_to_json_test_Arab.PBU_Serif_12.json" 2>&1
Arab.PBU_Serif_16:
	-$(PYTHON) "data/multilingual/Arab.PBU/Serif_16/pdf_to_json_test_Arab.PBU_Serif_16.py" > "data/multilingual/Arab.PBU/Serif_16/pdf_to_json_test_Arab.PBU_Serif_16.json" 2>&1
Arab.PBU_Serif_8:
	-$(PYTHON) "data/multilingual/Arab.PBU/Serif_8/pdf_to_json_test_Arab.PBU_Serif_8.py" > "data/multilingual/Arab.PBU/Serif_8/pdf_to_json_test_Arab.PBU_Serif_8.json" 2>&1
Arab.PBU_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Arab.PBU/Sun-ExtA_12/pdf_to_json_test_Arab.PBU_Sun-ExtA_12.py" > "data/multilingual/Arab.PBU/Sun-ExtA_12/pdf_to_json_test_Arab.PBU_Sun-ExtA_12.json" 2>&1
Arab.PBU_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Arab.PBU/Sun-ExtA_16/pdf_to_json_test_Arab.PBU_Sun-ExtA_16.py" > "data/multilingual/Arab.PBU/Sun-ExtA_16/pdf_to_json_test_Arab.PBU_Sun-ExtA_16.json" 2>&1
Arab.PBU_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Arab.PBU/Sun-ExtA_8/pdf_to_json_test_Arab.PBU_Sun-ExtA_8.py" > "data/multilingual/Arab.PBU/Sun-ExtA_8/pdf_to_json_test_Arab.PBU_Sun-ExtA_8.json" 2>&1


Arab.PBU_all : Arab.PBU_Mono_12 Arab.PBU_Mono_16 Arab.PBU_Mono_8 Arab.PBU_Sans_12 Arab.PBU_Sans_16 Arab.PBU_Sans_8 Arab.PBU_Serif_12 Arab.PBU_Serif_16 Arab.PBU_Serif_8 Arab.PBU_Sun-ExtA_12 Arab.PBU_Sun-ExtA_16 Arab.PBU_Sun-ExtA_8
