PYTHON=python3


Latn.BOA_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.BOA/Mono_12/pdf_to_json_test_Latn.BOA_Mono_12.py" > "data/multilingual/Latn.BOA/Mono_12/pdf_to_json_test_Latn.BOA_Mono_12.json" 2>&1
Latn.BOA_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.BOA/Mono_16/pdf_to_json_test_Latn.BOA_Mono_16.py" > "data/multilingual/Latn.BOA/Mono_16/pdf_to_json_test_Latn.BOA_Mono_16.json" 2>&1
Latn.BOA_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.BOA/Mono_8/pdf_to_json_test_Latn.BOA_Mono_8.py" > "data/multilingual/Latn.BOA/Mono_8/pdf_to_json_test_Latn.BOA_Mono_8.json" 2>&1
Latn.BOA_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.BOA/Sans_12/pdf_to_json_test_Latn.BOA_Sans_12.py" > "data/multilingual/Latn.BOA/Sans_12/pdf_to_json_test_Latn.BOA_Sans_12.json" 2>&1
Latn.BOA_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.BOA/Sans_16/pdf_to_json_test_Latn.BOA_Sans_16.py" > "data/multilingual/Latn.BOA/Sans_16/pdf_to_json_test_Latn.BOA_Sans_16.json" 2>&1
Latn.BOA_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.BOA/Sans_8/pdf_to_json_test_Latn.BOA_Sans_8.py" > "data/multilingual/Latn.BOA/Sans_8/pdf_to_json_test_Latn.BOA_Sans_8.json" 2>&1
Latn.BOA_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.BOA/Serif_12/pdf_to_json_test_Latn.BOA_Serif_12.py" > "data/multilingual/Latn.BOA/Serif_12/pdf_to_json_test_Latn.BOA_Serif_12.json" 2>&1
Latn.BOA_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.BOA/Serif_16/pdf_to_json_test_Latn.BOA_Serif_16.py" > "data/multilingual/Latn.BOA/Serif_16/pdf_to_json_test_Latn.BOA_Serif_16.json" 2>&1
Latn.BOA_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.BOA/Serif_8/pdf_to_json_test_Latn.BOA_Serif_8.py" > "data/multilingual/Latn.BOA/Serif_8/pdf_to_json_test_Latn.BOA_Serif_8.json" 2>&1
Latn.BOA_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.BOA/Sun-ExtA_12/pdf_to_json_test_Latn.BOA_Sun-ExtA_12.py" > "data/multilingual/Latn.BOA/Sun-ExtA_12/pdf_to_json_test_Latn.BOA_Sun-ExtA_12.json" 2>&1
Latn.BOA_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.BOA/Sun-ExtA_16/pdf_to_json_test_Latn.BOA_Sun-ExtA_16.py" > "data/multilingual/Latn.BOA/Sun-ExtA_16/pdf_to_json_test_Latn.BOA_Sun-ExtA_16.json" 2>&1
Latn.BOA_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.BOA/Sun-ExtA_8/pdf_to_json_test_Latn.BOA_Sun-ExtA_8.py" > "data/multilingual/Latn.BOA/Sun-ExtA_8/pdf_to_json_test_Latn.BOA_Sun-ExtA_8.json" 2>&1


Latn.BOA_all : Latn.BOA_Mono_12 Latn.BOA_Mono_16 Latn.BOA_Mono_8 Latn.BOA_Sans_12 Latn.BOA_Sans_16 Latn.BOA_Sans_8 Latn.BOA_Serif_12 Latn.BOA_Serif_16 Latn.BOA_Serif_8 Latn.BOA_Sun-ExtA_12 Latn.BOA_Sun-ExtA_16 Latn.BOA_Sun-ExtA_8
