PYTHON=python3


Latn.GLE_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.GLE/Mono_12/pdf_to_json_test_Latn.GLE_Mono_12.py" > "data/multilingual/Latn.GLE/Mono_12/pdf_to_json_test_Latn.GLE_Mono_12.json" 2>&1
Latn.GLE_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.GLE/Mono_16/pdf_to_json_test_Latn.GLE_Mono_16.py" > "data/multilingual/Latn.GLE/Mono_16/pdf_to_json_test_Latn.GLE_Mono_16.json" 2>&1
Latn.GLE_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.GLE/Mono_8/pdf_to_json_test_Latn.GLE_Mono_8.py" > "data/multilingual/Latn.GLE/Mono_8/pdf_to_json_test_Latn.GLE_Mono_8.json" 2>&1
Latn.GLE_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.GLE/Sans_12/pdf_to_json_test_Latn.GLE_Sans_12.py" > "data/multilingual/Latn.GLE/Sans_12/pdf_to_json_test_Latn.GLE_Sans_12.json" 2>&1
Latn.GLE_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.GLE/Sans_16/pdf_to_json_test_Latn.GLE_Sans_16.py" > "data/multilingual/Latn.GLE/Sans_16/pdf_to_json_test_Latn.GLE_Sans_16.json" 2>&1
Latn.GLE_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.GLE/Sans_8/pdf_to_json_test_Latn.GLE_Sans_8.py" > "data/multilingual/Latn.GLE/Sans_8/pdf_to_json_test_Latn.GLE_Sans_8.json" 2>&1
Latn.GLE_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.GLE/Serif_12/pdf_to_json_test_Latn.GLE_Serif_12.py" > "data/multilingual/Latn.GLE/Serif_12/pdf_to_json_test_Latn.GLE_Serif_12.json" 2>&1
Latn.GLE_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.GLE/Serif_16/pdf_to_json_test_Latn.GLE_Serif_16.py" > "data/multilingual/Latn.GLE/Serif_16/pdf_to_json_test_Latn.GLE_Serif_16.json" 2>&1
Latn.GLE_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.GLE/Serif_8/pdf_to_json_test_Latn.GLE_Serif_8.py" > "data/multilingual/Latn.GLE/Serif_8/pdf_to_json_test_Latn.GLE_Serif_8.json" 2>&1
Latn.GLE_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.GLE/Sun-ExtA_12/pdf_to_json_test_Latn.GLE_Sun-ExtA_12.py" > "data/multilingual/Latn.GLE/Sun-ExtA_12/pdf_to_json_test_Latn.GLE_Sun-ExtA_12.json" 2>&1
Latn.GLE_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.GLE/Sun-ExtA_16/pdf_to_json_test_Latn.GLE_Sun-ExtA_16.py" > "data/multilingual/Latn.GLE/Sun-ExtA_16/pdf_to_json_test_Latn.GLE_Sun-ExtA_16.json" 2>&1
Latn.GLE_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.GLE/Sun-ExtA_8/pdf_to_json_test_Latn.GLE_Sun-ExtA_8.py" > "data/multilingual/Latn.GLE/Sun-ExtA_8/pdf_to_json_test_Latn.GLE_Sun-ExtA_8.json" 2>&1


Latn.GLE_all : Latn.GLE_Mono_12 Latn.GLE_Mono_16 Latn.GLE_Mono_8 Latn.GLE_Sans_12 Latn.GLE_Sans_16 Latn.GLE_Sans_8 Latn.GLE_Serif_12 Latn.GLE_Serif_16 Latn.GLE_Serif_8 Latn.GLE_Sun-ExtA_12 Latn.GLE_Sun-ExtA_16 Latn.GLE_Sun-ExtA_8
