PYTHON=python3


Latn.FRY_Mono_12:
	-$(PYTHON) data/multilingual/Latn.FRY/Mono_12/pdf_to_json_test_Latn.FRY_Mono_12.py > data/multilingual/Latn.FRY/Mono_12/pdf_to_json_test_Latn.FRY_Mono_12.json 2>&1
Latn.FRY_Mono_16:
	-$(PYTHON) data/multilingual/Latn.FRY/Mono_16/pdf_to_json_test_Latn.FRY_Mono_16.py > data/multilingual/Latn.FRY/Mono_16/pdf_to_json_test_Latn.FRY_Mono_16.json 2>&1
Latn.FRY_Mono_8:
	-$(PYTHON) data/multilingual/Latn.FRY/Mono_8/pdf_to_json_test_Latn.FRY_Mono_8.py > data/multilingual/Latn.FRY/Mono_8/pdf_to_json_test_Latn.FRY_Mono_8.json 2>&1
Latn.FRY_Sans_12:
	-$(PYTHON) data/multilingual/Latn.FRY/Sans_12/pdf_to_json_test_Latn.FRY_Sans_12.py > data/multilingual/Latn.FRY/Sans_12/pdf_to_json_test_Latn.FRY_Sans_12.json 2>&1
Latn.FRY_Sans_16:
	-$(PYTHON) data/multilingual/Latn.FRY/Sans_16/pdf_to_json_test_Latn.FRY_Sans_16.py > data/multilingual/Latn.FRY/Sans_16/pdf_to_json_test_Latn.FRY_Sans_16.json 2>&1
Latn.FRY_Sans_8:
	-$(PYTHON) data/multilingual/Latn.FRY/Sans_8/pdf_to_json_test_Latn.FRY_Sans_8.py > data/multilingual/Latn.FRY/Sans_8/pdf_to_json_test_Latn.FRY_Sans_8.json 2>&1
Latn.FRY_Serif_12:
	-$(PYTHON) data/multilingual/Latn.FRY/Serif_12/pdf_to_json_test_Latn.FRY_Serif_12.py > data/multilingual/Latn.FRY/Serif_12/pdf_to_json_test_Latn.FRY_Serif_12.json 2>&1
Latn.FRY_Serif_16:
	-$(PYTHON) data/multilingual/Latn.FRY/Serif_16/pdf_to_json_test_Latn.FRY_Serif_16.py > data/multilingual/Latn.FRY/Serif_16/pdf_to_json_test_Latn.FRY_Serif_16.json 2>&1
Latn.FRY_Serif_8:
	-$(PYTHON) data/multilingual/Latn.FRY/Serif_8/pdf_to_json_test_Latn.FRY_Serif_8.py > data/multilingual/Latn.FRY/Serif_8/pdf_to_json_test_Latn.FRY_Serif_8.json 2>&1
Latn.FRY_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.FRY/Sun-ExtA_12/pdf_to_json_test_Latn.FRY_Sun-ExtA_12.py > data/multilingual/Latn.FRY/Sun-ExtA_12/pdf_to_json_test_Latn.FRY_Sun-ExtA_12.json 2>&1
Latn.FRY_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.FRY/Sun-ExtA_16/pdf_to_json_test_Latn.FRY_Sun-ExtA_16.py > data/multilingual/Latn.FRY/Sun-ExtA_16/pdf_to_json_test_Latn.FRY_Sun-ExtA_16.json 2>&1
Latn.FRY_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.FRY/Sun-ExtA_8/pdf_to_json_test_Latn.FRY_Sun-ExtA_8.py > data/multilingual/Latn.FRY/Sun-ExtA_8/pdf_to_json_test_Latn.FRY_Sun-ExtA_8.json 2>&1


Latn.FRY_all : Latn.FRY_Mono_12 Latn.FRY_Mono_16 Latn.FRY_Mono_8 Latn.FRY_Sans_12 Latn.FRY_Sans_16 Latn.FRY_Sans_8 Latn.FRY_Serif_12 Latn.FRY_Serif_16 Latn.FRY_Serif_8 Latn.FRY_Sun-ExtA_12 Latn.FRY_Sun-ExtA_16 Latn.FRY_Sun-ExtA_8
