PYTHON=python3


Hans.HAK_Mono_12:
	-$(PYTHON) data/multilingual/Hans.HAK/Mono_12/pdf_to_json_test_Hans.HAK_Mono_12.py > data/multilingual/Hans.HAK/Mono_12/pdf_to_json_test_Hans.HAK_Mono_12.json 2>&1
Hans.HAK_Mono_16:
	-$(PYTHON) data/multilingual/Hans.HAK/Mono_16/pdf_to_json_test_Hans.HAK_Mono_16.py > data/multilingual/Hans.HAK/Mono_16/pdf_to_json_test_Hans.HAK_Mono_16.json 2>&1
Hans.HAK_Mono_8:
	-$(PYTHON) data/multilingual/Hans.HAK/Mono_8/pdf_to_json_test_Hans.HAK_Mono_8.py > data/multilingual/Hans.HAK/Mono_8/pdf_to_json_test_Hans.HAK_Mono_8.json 2>&1
Hans.HAK_Sans_12:
	-$(PYTHON) data/multilingual/Hans.HAK/Sans_12/pdf_to_json_test_Hans.HAK_Sans_12.py > data/multilingual/Hans.HAK/Sans_12/pdf_to_json_test_Hans.HAK_Sans_12.json 2>&1
Hans.HAK_Sans_16:
	-$(PYTHON) data/multilingual/Hans.HAK/Sans_16/pdf_to_json_test_Hans.HAK_Sans_16.py > data/multilingual/Hans.HAK/Sans_16/pdf_to_json_test_Hans.HAK_Sans_16.json 2>&1
Hans.HAK_Sans_8:
	-$(PYTHON) data/multilingual/Hans.HAK/Sans_8/pdf_to_json_test_Hans.HAK_Sans_8.py > data/multilingual/Hans.HAK/Sans_8/pdf_to_json_test_Hans.HAK_Sans_8.json 2>&1
Hans.HAK_Serif_12:
	-$(PYTHON) data/multilingual/Hans.HAK/Serif_12/pdf_to_json_test_Hans.HAK_Serif_12.py > data/multilingual/Hans.HAK/Serif_12/pdf_to_json_test_Hans.HAK_Serif_12.json 2>&1
Hans.HAK_Serif_16:
	-$(PYTHON) data/multilingual/Hans.HAK/Serif_16/pdf_to_json_test_Hans.HAK_Serif_16.py > data/multilingual/Hans.HAK/Serif_16/pdf_to_json_test_Hans.HAK_Serif_16.json 2>&1
Hans.HAK_Serif_8:
	-$(PYTHON) data/multilingual/Hans.HAK/Serif_8/pdf_to_json_test_Hans.HAK_Serif_8.py > data/multilingual/Hans.HAK/Serif_8/pdf_to_json_test_Hans.HAK_Serif_8.json 2>&1
Hans.HAK_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Hans.HAK/Sun-ExtA_12/pdf_to_json_test_Hans.HAK_Sun-ExtA_12.py > data/multilingual/Hans.HAK/Sun-ExtA_12/pdf_to_json_test_Hans.HAK_Sun-ExtA_12.json 2>&1
Hans.HAK_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Hans.HAK/Sun-ExtA_16/pdf_to_json_test_Hans.HAK_Sun-ExtA_16.py > data/multilingual/Hans.HAK/Sun-ExtA_16/pdf_to_json_test_Hans.HAK_Sun-ExtA_16.json 2>&1
Hans.HAK_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Hans.HAK/Sun-ExtA_8/pdf_to_json_test_Hans.HAK_Sun-ExtA_8.py > data/multilingual/Hans.HAK/Sun-ExtA_8/pdf_to_json_test_Hans.HAK_Sun-ExtA_8.json 2>&1


Hans.HAK_all : Hans.HAK_Mono_12 Hans.HAK_Mono_16 Hans.HAK_Mono_8 Hans.HAK_Sans_12 Hans.HAK_Sans_16 Hans.HAK_Sans_8 Hans.HAK_Serif_12 Hans.HAK_Serif_16 Hans.HAK_Serif_8 Hans.HAK_Sun-ExtA_12 Hans.HAK_Sun-ExtA_16 Hans.HAK_Sun-ExtA_8
