PYTHON=python3


Latn.TAH_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.TAH/Mono_12/pdf_to_json_test_Latn.TAH_Mono_12.py" > "data/multilingual/Latn.TAH/Mono_12/pdf_to_json_test_Latn.TAH_Mono_12.json" 2>&1
Latn.TAH_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.TAH/Mono_16/pdf_to_json_test_Latn.TAH_Mono_16.py" > "data/multilingual/Latn.TAH/Mono_16/pdf_to_json_test_Latn.TAH_Mono_16.json" 2>&1
Latn.TAH_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.TAH/Mono_8/pdf_to_json_test_Latn.TAH_Mono_8.py" > "data/multilingual/Latn.TAH/Mono_8/pdf_to_json_test_Latn.TAH_Mono_8.json" 2>&1
Latn.TAH_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.TAH/Sans_12/pdf_to_json_test_Latn.TAH_Sans_12.py" > "data/multilingual/Latn.TAH/Sans_12/pdf_to_json_test_Latn.TAH_Sans_12.json" 2>&1
Latn.TAH_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.TAH/Sans_16/pdf_to_json_test_Latn.TAH_Sans_16.py" > "data/multilingual/Latn.TAH/Sans_16/pdf_to_json_test_Latn.TAH_Sans_16.json" 2>&1
Latn.TAH_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.TAH/Sans_8/pdf_to_json_test_Latn.TAH_Sans_8.py" > "data/multilingual/Latn.TAH/Sans_8/pdf_to_json_test_Latn.TAH_Sans_8.json" 2>&1
Latn.TAH_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.TAH/Serif_12/pdf_to_json_test_Latn.TAH_Serif_12.py" > "data/multilingual/Latn.TAH/Serif_12/pdf_to_json_test_Latn.TAH_Serif_12.json" 2>&1
Latn.TAH_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.TAH/Serif_16/pdf_to_json_test_Latn.TAH_Serif_16.py" > "data/multilingual/Latn.TAH/Serif_16/pdf_to_json_test_Latn.TAH_Serif_16.json" 2>&1
Latn.TAH_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.TAH/Serif_8/pdf_to_json_test_Latn.TAH_Serif_8.py" > "data/multilingual/Latn.TAH/Serif_8/pdf_to_json_test_Latn.TAH_Serif_8.json" 2>&1
Latn.TAH_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.TAH/Sun-ExtA_12/pdf_to_json_test_Latn.TAH_Sun-ExtA_12.py" > "data/multilingual/Latn.TAH/Sun-ExtA_12/pdf_to_json_test_Latn.TAH_Sun-ExtA_12.json" 2>&1
Latn.TAH_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.TAH/Sun-ExtA_16/pdf_to_json_test_Latn.TAH_Sun-ExtA_16.py" > "data/multilingual/Latn.TAH/Sun-ExtA_16/pdf_to_json_test_Latn.TAH_Sun-ExtA_16.json" 2>&1
Latn.TAH_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.TAH/Sun-ExtA_8/pdf_to_json_test_Latn.TAH_Sun-ExtA_8.py" > "data/multilingual/Latn.TAH/Sun-ExtA_8/pdf_to_json_test_Latn.TAH_Sun-ExtA_8.json" 2>&1


Latn.TAH_all : Latn.TAH_Mono_12 Latn.TAH_Mono_16 Latn.TAH_Mono_8 Latn.TAH_Sans_12 Latn.TAH_Sans_16 Latn.TAH_Sans_8 Latn.TAH_Serif_12 Latn.TAH_Serif_16 Latn.TAH_Serif_8 Latn.TAH_Sun-ExtA_12 Latn.TAH_Sun-ExtA_16 Latn.TAH_Sun-ExtA_8
