PYTHON=python3


Latn.CHJ_Mono_12:
	-$(PYTHON) data/multilingual/Latn.CHJ/Mono_12/pdf_to_json_test_Latn.CHJ_Mono_12.py > data/multilingual/Latn.CHJ/Mono_12/pdf_to_json_test_Latn.CHJ_Mono_12.json 2>&1
Latn.CHJ_Mono_16:
	-$(PYTHON) data/multilingual/Latn.CHJ/Mono_16/pdf_to_json_test_Latn.CHJ_Mono_16.py > data/multilingual/Latn.CHJ/Mono_16/pdf_to_json_test_Latn.CHJ_Mono_16.json 2>&1
Latn.CHJ_Mono_8:
	-$(PYTHON) data/multilingual/Latn.CHJ/Mono_8/pdf_to_json_test_Latn.CHJ_Mono_8.py > data/multilingual/Latn.CHJ/Mono_8/pdf_to_json_test_Latn.CHJ_Mono_8.json 2>&1
Latn.CHJ_Sans_12:
	-$(PYTHON) data/multilingual/Latn.CHJ/Sans_12/pdf_to_json_test_Latn.CHJ_Sans_12.py > data/multilingual/Latn.CHJ/Sans_12/pdf_to_json_test_Latn.CHJ_Sans_12.json 2>&1
Latn.CHJ_Sans_16:
	-$(PYTHON) data/multilingual/Latn.CHJ/Sans_16/pdf_to_json_test_Latn.CHJ_Sans_16.py > data/multilingual/Latn.CHJ/Sans_16/pdf_to_json_test_Latn.CHJ_Sans_16.json 2>&1
Latn.CHJ_Sans_8:
	-$(PYTHON) data/multilingual/Latn.CHJ/Sans_8/pdf_to_json_test_Latn.CHJ_Sans_8.py > data/multilingual/Latn.CHJ/Sans_8/pdf_to_json_test_Latn.CHJ_Sans_8.json 2>&1
Latn.CHJ_Serif_12:
	-$(PYTHON) data/multilingual/Latn.CHJ/Serif_12/pdf_to_json_test_Latn.CHJ_Serif_12.py > data/multilingual/Latn.CHJ/Serif_12/pdf_to_json_test_Latn.CHJ_Serif_12.json 2>&1
Latn.CHJ_Serif_16:
	-$(PYTHON) data/multilingual/Latn.CHJ/Serif_16/pdf_to_json_test_Latn.CHJ_Serif_16.py > data/multilingual/Latn.CHJ/Serif_16/pdf_to_json_test_Latn.CHJ_Serif_16.json 2>&1
Latn.CHJ_Serif_8:
	-$(PYTHON) data/multilingual/Latn.CHJ/Serif_8/pdf_to_json_test_Latn.CHJ_Serif_8.py > data/multilingual/Latn.CHJ/Serif_8/pdf_to_json_test_Latn.CHJ_Serif_8.json 2>&1
Latn.CHJ_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.CHJ/Sun-ExtA_12/pdf_to_json_test_Latn.CHJ_Sun-ExtA_12.py > data/multilingual/Latn.CHJ/Sun-ExtA_12/pdf_to_json_test_Latn.CHJ_Sun-ExtA_12.json 2>&1
Latn.CHJ_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.CHJ/Sun-ExtA_16/pdf_to_json_test_Latn.CHJ_Sun-ExtA_16.py > data/multilingual/Latn.CHJ/Sun-ExtA_16/pdf_to_json_test_Latn.CHJ_Sun-ExtA_16.json 2>&1
Latn.CHJ_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.CHJ/Sun-ExtA_8/pdf_to_json_test_Latn.CHJ_Sun-ExtA_8.py > data/multilingual/Latn.CHJ/Sun-ExtA_8/pdf_to_json_test_Latn.CHJ_Sun-ExtA_8.json 2>&1


Latn.CHJ_all : Latn.CHJ_Mono_12 Latn.CHJ_Mono_16 Latn.CHJ_Mono_8 Latn.CHJ_Sans_12 Latn.CHJ_Sans_16 Latn.CHJ_Sans_8 Latn.CHJ_Serif_12 Latn.CHJ_Serif_16 Latn.CHJ_Serif_8 Latn.CHJ_Sun-ExtA_12 Latn.CHJ_Sun-ExtA_16 Latn.CHJ_Sun-ExtA_8
