PYTHON=python3


Cans.IKE_Mono_12:
	-$(PYTHON) "data/multilingual/Cans.IKE/Mono_12/pdf_to_json_test_Cans.IKE_Mono_12.py" > "data/multilingual/Cans.IKE/Mono_12/pdf_to_json_test_Cans.IKE_Mono_12.json" 2>&1
Cans.IKE_Mono_16:
	-$(PYTHON) "data/multilingual/Cans.IKE/Mono_16/pdf_to_json_test_Cans.IKE_Mono_16.py" > "data/multilingual/Cans.IKE/Mono_16/pdf_to_json_test_Cans.IKE_Mono_16.json" 2>&1
Cans.IKE_Mono_8:
	-$(PYTHON) "data/multilingual/Cans.IKE/Mono_8/pdf_to_json_test_Cans.IKE_Mono_8.py" > "data/multilingual/Cans.IKE/Mono_8/pdf_to_json_test_Cans.IKE_Mono_8.json" 2>&1
Cans.IKE_Sans_12:
	-$(PYTHON) "data/multilingual/Cans.IKE/Sans_12/pdf_to_json_test_Cans.IKE_Sans_12.py" > "data/multilingual/Cans.IKE/Sans_12/pdf_to_json_test_Cans.IKE_Sans_12.json" 2>&1
Cans.IKE_Sans_16:
	-$(PYTHON) "data/multilingual/Cans.IKE/Sans_16/pdf_to_json_test_Cans.IKE_Sans_16.py" > "data/multilingual/Cans.IKE/Sans_16/pdf_to_json_test_Cans.IKE_Sans_16.json" 2>&1
Cans.IKE_Sans_8:
	-$(PYTHON) "data/multilingual/Cans.IKE/Sans_8/pdf_to_json_test_Cans.IKE_Sans_8.py" > "data/multilingual/Cans.IKE/Sans_8/pdf_to_json_test_Cans.IKE_Sans_8.json" 2>&1
Cans.IKE_Serif_12:
	-$(PYTHON) "data/multilingual/Cans.IKE/Serif_12/pdf_to_json_test_Cans.IKE_Serif_12.py" > "data/multilingual/Cans.IKE/Serif_12/pdf_to_json_test_Cans.IKE_Serif_12.json" 2>&1
Cans.IKE_Serif_16:
	-$(PYTHON) "data/multilingual/Cans.IKE/Serif_16/pdf_to_json_test_Cans.IKE_Serif_16.py" > "data/multilingual/Cans.IKE/Serif_16/pdf_to_json_test_Cans.IKE_Serif_16.json" 2>&1
Cans.IKE_Serif_8:
	-$(PYTHON) "data/multilingual/Cans.IKE/Serif_8/pdf_to_json_test_Cans.IKE_Serif_8.py" > "data/multilingual/Cans.IKE/Serif_8/pdf_to_json_test_Cans.IKE_Serif_8.json" 2>&1
Cans.IKE_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Cans.IKE/Sun-ExtA_12/pdf_to_json_test_Cans.IKE_Sun-ExtA_12.py" > "data/multilingual/Cans.IKE/Sun-ExtA_12/pdf_to_json_test_Cans.IKE_Sun-ExtA_12.json" 2>&1
Cans.IKE_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Cans.IKE/Sun-ExtA_16/pdf_to_json_test_Cans.IKE_Sun-ExtA_16.py" > "data/multilingual/Cans.IKE/Sun-ExtA_16/pdf_to_json_test_Cans.IKE_Sun-ExtA_16.json" 2>&1
Cans.IKE_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Cans.IKE/Sun-ExtA_8/pdf_to_json_test_Cans.IKE_Sun-ExtA_8.py" > "data/multilingual/Cans.IKE/Sun-ExtA_8/pdf_to_json_test_Cans.IKE_Sun-ExtA_8.json" 2>&1


Cans.IKE_all : Cans.IKE_Mono_12 Cans.IKE_Mono_16 Cans.IKE_Mono_8 Cans.IKE_Sans_12 Cans.IKE_Sans_16 Cans.IKE_Sans_8 Cans.IKE_Serif_12 Cans.IKE_Serif_16 Cans.IKE_Serif_8 Cans.IKE_Sun-ExtA_12 Cans.IKE_Sun-ExtA_16 Cans.IKE_Sun-ExtA_8
