PYTHON=python3


Arab.ARB_Mono_12:
	-$(PYTHON) data/multilingual/Arab.ARB/Mono_12/pdf_to_json_test_Arab.ARB_Mono_12.py > data/multilingual/Arab.ARB/Mono_12/pdf_to_json_test_Arab.ARB_Mono_12.json 2>&1
Arab.ARB_Mono_16:
	-$(PYTHON) data/multilingual/Arab.ARB/Mono_16/pdf_to_json_test_Arab.ARB_Mono_16.py > data/multilingual/Arab.ARB/Mono_16/pdf_to_json_test_Arab.ARB_Mono_16.json 2>&1
Arab.ARB_Mono_8:
	-$(PYTHON) data/multilingual/Arab.ARB/Mono_8/pdf_to_json_test_Arab.ARB_Mono_8.py > data/multilingual/Arab.ARB/Mono_8/pdf_to_json_test_Arab.ARB_Mono_8.json 2>&1
Arab.ARB_Sans_12:
	-$(PYTHON) data/multilingual/Arab.ARB/Sans_12/pdf_to_json_test_Arab.ARB_Sans_12.py > data/multilingual/Arab.ARB/Sans_12/pdf_to_json_test_Arab.ARB_Sans_12.json 2>&1
Arab.ARB_Sans_16:
	-$(PYTHON) data/multilingual/Arab.ARB/Sans_16/pdf_to_json_test_Arab.ARB_Sans_16.py > data/multilingual/Arab.ARB/Sans_16/pdf_to_json_test_Arab.ARB_Sans_16.json 2>&1
Arab.ARB_Sans_8:
	-$(PYTHON) data/multilingual/Arab.ARB/Sans_8/pdf_to_json_test_Arab.ARB_Sans_8.py > data/multilingual/Arab.ARB/Sans_8/pdf_to_json_test_Arab.ARB_Sans_8.json 2>&1
Arab.ARB_Serif_12:
	-$(PYTHON) data/multilingual/Arab.ARB/Serif_12/pdf_to_json_test_Arab.ARB_Serif_12.py > data/multilingual/Arab.ARB/Serif_12/pdf_to_json_test_Arab.ARB_Serif_12.json 2>&1
Arab.ARB_Serif_16:
	-$(PYTHON) data/multilingual/Arab.ARB/Serif_16/pdf_to_json_test_Arab.ARB_Serif_16.py > data/multilingual/Arab.ARB/Serif_16/pdf_to_json_test_Arab.ARB_Serif_16.json 2>&1
Arab.ARB_Serif_8:
	-$(PYTHON) data/multilingual/Arab.ARB/Serif_8/pdf_to_json_test_Arab.ARB_Serif_8.py > data/multilingual/Arab.ARB/Serif_8/pdf_to_json_test_Arab.ARB_Serif_8.json 2>&1
Arab.ARB_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Arab.ARB/Sun-ExtA_12/pdf_to_json_test_Arab.ARB_Sun-ExtA_12.py > data/multilingual/Arab.ARB/Sun-ExtA_12/pdf_to_json_test_Arab.ARB_Sun-ExtA_12.json 2>&1
Arab.ARB_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Arab.ARB/Sun-ExtA_16/pdf_to_json_test_Arab.ARB_Sun-ExtA_16.py > data/multilingual/Arab.ARB/Sun-ExtA_16/pdf_to_json_test_Arab.ARB_Sun-ExtA_16.json 2>&1
Arab.ARB_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Arab.ARB/Sun-ExtA_8/pdf_to_json_test_Arab.ARB_Sun-ExtA_8.py > data/multilingual/Arab.ARB/Sun-ExtA_8/pdf_to_json_test_Arab.ARB_Sun-ExtA_8.json 2>&1


Arab.ARB_all : Arab.ARB_Mono_12 Arab.ARB_Mono_16 Arab.ARB_Mono_8 Arab.ARB_Sans_12 Arab.ARB_Sans_16 Arab.ARB_Sans_8 Arab.ARB_Serif_12 Arab.ARB_Serif_16 Arab.ARB_Serif_8 Arab.ARB_Sun-ExtA_12 Arab.ARB_Sun-ExtA_16 Arab.ARB_Sun-ExtA_8
