PYTHON=python3


Latn.UIG_Mono_12:
	-$(PYTHON) data/multilingual/Latn.UIG/Mono_12/pdf_to_json_test_Latn.UIG_Mono_12.py > data/multilingual/Latn.UIG/Mono_12/pdf_to_json_test_Latn.UIG_Mono_12.json 2>&1
Latn.UIG_Mono_16:
	-$(PYTHON) data/multilingual/Latn.UIG/Mono_16/pdf_to_json_test_Latn.UIG_Mono_16.py > data/multilingual/Latn.UIG/Mono_16/pdf_to_json_test_Latn.UIG_Mono_16.json 2>&1
Latn.UIG_Mono_8:
	-$(PYTHON) data/multilingual/Latn.UIG/Mono_8/pdf_to_json_test_Latn.UIG_Mono_8.py > data/multilingual/Latn.UIG/Mono_8/pdf_to_json_test_Latn.UIG_Mono_8.json 2>&1
Latn.UIG_Sans_12:
	-$(PYTHON) data/multilingual/Latn.UIG/Sans_12/pdf_to_json_test_Latn.UIG_Sans_12.py > data/multilingual/Latn.UIG/Sans_12/pdf_to_json_test_Latn.UIG_Sans_12.json 2>&1
Latn.UIG_Sans_16:
	-$(PYTHON) data/multilingual/Latn.UIG/Sans_16/pdf_to_json_test_Latn.UIG_Sans_16.py > data/multilingual/Latn.UIG/Sans_16/pdf_to_json_test_Latn.UIG_Sans_16.json 2>&1
Latn.UIG_Sans_8:
	-$(PYTHON) data/multilingual/Latn.UIG/Sans_8/pdf_to_json_test_Latn.UIG_Sans_8.py > data/multilingual/Latn.UIG/Sans_8/pdf_to_json_test_Latn.UIG_Sans_8.json 2>&1
Latn.UIG_Serif_12:
	-$(PYTHON) data/multilingual/Latn.UIG/Serif_12/pdf_to_json_test_Latn.UIG_Serif_12.py > data/multilingual/Latn.UIG/Serif_12/pdf_to_json_test_Latn.UIG_Serif_12.json 2>&1
Latn.UIG_Serif_16:
	-$(PYTHON) data/multilingual/Latn.UIG/Serif_16/pdf_to_json_test_Latn.UIG_Serif_16.py > data/multilingual/Latn.UIG/Serif_16/pdf_to_json_test_Latn.UIG_Serif_16.json 2>&1
Latn.UIG_Serif_8:
	-$(PYTHON) data/multilingual/Latn.UIG/Serif_8/pdf_to_json_test_Latn.UIG_Serif_8.py > data/multilingual/Latn.UIG/Serif_8/pdf_to_json_test_Latn.UIG_Serif_8.json 2>&1
Latn.UIG_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.UIG/Sun-ExtA_12/pdf_to_json_test_Latn.UIG_Sun-ExtA_12.py > data/multilingual/Latn.UIG/Sun-ExtA_12/pdf_to_json_test_Latn.UIG_Sun-ExtA_12.json 2>&1
Latn.UIG_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.UIG/Sun-ExtA_16/pdf_to_json_test_Latn.UIG_Sun-ExtA_16.py > data/multilingual/Latn.UIG/Sun-ExtA_16/pdf_to_json_test_Latn.UIG_Sun-ExtA_16.json 2>&1
Latn.UIG_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.UIG/Sun-ExtA_8/pdf_to_json_test_Latn.UIG_Sun-ExtA_8.py > data/multilingual/Latn.UIG/Sun-ExtA_8/pdf_to_json_test_Latn.UIG_Sun-ExtA_8.json 2>&1


Latn.UIG_all : Latn.UIG_Mono_12 Latn.UIG_Mono_16 Latn.UIG_Mono_8 Latn.UIG_Sans_12 Latn.UIG_Sans_16 Latn.UIG_Sans_8 Latn.UIG_Serif_12 Latn.UIG_Serif_16 Latn.UIG_Serif_8 Latn.UIG_Sun-ExtA_12 Latn.UIG_Sun-ExtA_16 Latn.UIG_Sun-ExtA_8
