PYTHON=python3


Hans.NAN_Mono_12:
	-$(PYTHON) data/multilingual/Hans.NAN/Mono_12/pdf_to_json_test_Hans.NAN_Mono_12.py > data/multilingual/Hans.NAN/Mono_12/pdf_to_json_test_Hans.NAN_Mono_12.json 2>&1
Hans.NAN_Mono_16:
	-$(PYTHON) data/multilingual/Hans.NAN/Mono_16/pdf_to_json_test_Hans.NAN_Mono_16.py > data/multilingual/Hans.NAN/Mono_16/pdf_to_json_test_Hans.NAN_Mono_16.json 2>&1
Hans.NAN_Mono_8:
	-$(PYTHON) data/multilingual/Hans.NAN/Mono_8/pdf_to_json_test_Hans.NAN_Mono_8.py > data/multilingual/Hans.NAN/Mono_8/pdf_to_json_test_Hans.NAN_Mono_8.json 2>&1
Hans.NAN_Sans_12:
	-$(PYTHON) data/multilingual/Hans.NAN/Sans_12/pdf_to_json_test_Hans.NAN_Sans_12.py > data/multilingual/Hans.NAN/Sans_12/pdf_to_json_test_Hans.NAN_Sans_12.json 2>&1
Hans.NAN_Sans_16:
	-$(PYTHON) data/multilingual/Hans.NAN/Sans_16/pdf_to_json_test_Hans.NAN_Sans_16.py > data/multilingual/Hans.NAN/Sans_16/pdf_to_json_test_Hans.NAN_Sans_16.json 2>&1
Hans.NAN_Sans_8:
	-$(PYTHON) data/multilingual/Hans.NAN/Sans_8/pdf_to_json_test_Hans.NAN_Sans_8.py > data/multilingual/Hans.NAN/Sans_8/pdf_to_json_test_Hans.NAN_Sans_8.json 2>&1
Hans.NAN_Serif_12:
	-$(PYTHON) data/multilingual/Hans.NAN/Serif_12/pdf_to_json_test_Hans.NAN_Serif_12.py > data/multilingual/Hans.NAN/Serif_12/pdf_to_json_test_Hans.NAN_Serif_12.json 2>&1
Hans.NAN_Serif_16:
	-$(PYTHON) data/multilingual/Hans.NAN/Serif_16/pdf_to_json_test_Hans.NAN_Serif_16.py > data/multilingual/Hans.NAN/Serif_16/pdf_to_json_test_Hans.NAN_Serif_16.json 2>&1
Hans.NAN_Serif_8:
	-$(PYTHON) data/multilingual/Hans.NAN/Serif_8/pdf_to_json_test_Hans.NAN_Serif_8.py > data/multilingual/Hans.NAN/Serif_8/pdf_to_json_test_Hans.NAN_Serif_8.json 2>&1
Hans.NAN_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Hans.NAN/Sun-ExtA_12/pdf_to_json_test_Hans.NAN_Sun-ExtA_12.py > data/multilingual/Hans.NAN/Sun-ExtA_12/pdf_to_json_test_Hans.NAN_Sun-ExtA_12.json 2>&1
Hans.NAN_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Hans.NAN/Sun-ExtA_16/pdf_to_json_test_Hans.NAN_Sun-ExtA_16.py > data/multilingual/Hans.NAN/Sun-ExtA_16/pdf_to_json_test_Hans.NAN_Sun-ExtA_16.json 2>&1
Hans.NAN_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Hans.NAN/Sun-ExtA_8/pdf_to_json_test_Hans.NAN_Sun-ExtA_8.py > data/multilingual/Hans.NAN/Sun-ExtA_8/pdf_to_json_test_Hans.NAN_Sun-ExtA_8.json 2>&1


Hans.NAN_all : Hans.NAN_Mono_12 Hans.NAN_Mono_16 Hans.NAN_Mono_8 Hans.NAN_Sans_12 Hans.NAN_Sans_16 Hans.NAN_Sans_8 Hans.NAN_Serif_12 Hans.NAN_Serif_16 Hans.NAN_Serif_8 Hans.NAN_Sun-ExtA_12 Hans.NAN_Sun-ExtA_16 Hans.NAN_Sun-ExtA_8
