PYTHON=python3


Latn.FON_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.FON/Mono_12/pdf_to_json_test_Latn.FON_Mono_12.py" > "data/multilingual/Latn.FON/Mono_12/pdf_to_json_test_Latn.FON_Mono_12.json" 2>&1
Latn.FON_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.FON/Mono_16/pdf_to_json_test_Latn.FON_Mono_16.py" > "data/multilingual/Latn.FON/Mono_16/pdf_to_json_test_Latn.FON_Mono_16.json" 2>&1
Latn.FON_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.FON/Mono_8/pdf_to_json_test_Latn.FON_Mono_8.py" > "data/multilingual/Latn.FON/Mono_8/pdf_to_json_test_Latn.FON_Mono_8.json" 2>&1
Latn.FON_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.FON/Sans_12/pdf_to_json_test_Latn.FON_Sans_12.py" > "data/multilingual/Latn.FON/Sans_12/pdf_to_json_test_Latn.FON_Sans_12.json" 2>&1
Latn.FON_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.FON/Sans_16/pdf_to_json_test_Latn.FON_Sans_16.py" > "data/multilingual/Latn.FON/Sans_16/pdf_to_json_test_Latn.FON_Sans_16.json" 2>&1
Latn.FON_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.FON/Sans_8/pdf_to_json_test_Latn.FON_Sans_8.py" > "data/multilingual/Latn.FON/Sans_8/pdf_to_json_test_Latn.FON_Sans_8.json" 2>&1
Latn.FON_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.FON/Serif_12/pdf_to_json_test_Latn.FON_Serif_12.py" > "data/multilingual/Latn.FON/Serif_12/pdf_to_json_test_Latn.FON_Serif_12.json" 2>&1
Latn.FON_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.FON/Serif_16/pdf_to_json_test_Latn.FON_Serif_16.py" > "data/multilingual/Latn.FON/Serif_16/pdf_to_json_test_Latn.FON_Serif_16.json" 2>&1
Latn.FON_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.FON/Serif_8/pdf_to_json_test_Latn.FON_Serif_8.py" > "data/multilingual/Latn.FON/Serif_8/pdf_to_json_test_Latn.FON_Serif_8.json" 2>&1
Latn.FON_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.FON/Sun-ExtA_12/pdf_to_json_test_Latn.FON_Sun-ExtA_12.py" > "data/multilingual/Latn.FON/Sun-ExtA_12/pdf_to_json_test_Latn.FON_Sun-ExtA_12.json" 2>&1
Latn.FON_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.FON/Sun-ExtA_16/pdf_to_json_test_Latn.FON_Sun-ExtA_16.py" > "data/multilingual/Latn.FON/Sun-ExtA_16/pdf_to_json_test_Latn.FON_Sun-ExtA_16.json" 2>&1
Latn.FON_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.FON/Sun-ExtA_8/pdf_to_json_test_Latn.FON_Sun-ExtA_8.py" > "data/multilingual/Latn.FON/Sun-ExtA_8/pdf_to_json_test_Latn.FON_Sun-ExtA_8.json" 2>&1


Latn.FON_all : Latn.FON_Mono_12 Latn.FON_Mono_16 Latn.FON_Mono_8 Latn.FON_Sans_12 Latn.FON_Sans_16 Latn.FON_Sans_8 Latn.FON_Serif_12 Latn.FON_Serif_16 Latn.FON_Serif_8 Latn.FON_Sun-ExtA_12 Latn.FON_Sun-ExtA_16 Latn.FON_Sun-ExtA_8
