PYTHON=python3


Latn.PIS_Mono_12:
	-$(PYTHON) data/multilingual/Latn.PIS/Mono_12/pdf_to_json_test_Latn.PIS_Mono_12.py > data/multilingual/Latn.PIS/Mono_12/pdf_to_json_test_Latn.PIS_Mono_12.json 2>&1
Latn.PIS_Mono_16:
	-$(PYTHON) data/multilingual/Latn.PIS/Mono_16/pdf_to_json_test_Latn.PIS_Mono_16.py > data/multilingual/Latn.PIS/Mono_16/pdf_to_json_test_Latn.PIS_Mono_16.json 2>&1
Latn.PIS_Mono_8:
	-$(PYTHON) data/multilingual/Latn.PIS/Mono_8/pdf_to_json_test_Latn.PIS_Mono_8.py > data/multilingual/Latn.PIS/Mono_8/pdf_to_json_test_Latn.PIS_Mono_8.json 2>&1
Latn.PIS_Sans_12:
	-$(PYTHON) data/multilingual/Latn.PIS/Sans_12/pdf_to_json_test_Latn.PIS_Sans_12.py > data/multilingual/Latn.PIS/Sans_12/pdf_to_json_test_Latn.PIS_Sans_12.json 2>&1
Latn.PIS_Sans_16:
	-$(PYTHON) data/multilingual/Latn.PIS/Sans_16/pdf_to_json_test_Latn.PIS_Sans_16.py > data/multilingual/Latn.PIS/Sans_16/pdf_to_json_test_Latn.PIS_Sans_16.json 2>&1
Latn.PIS_Sans_8:
	-$(PYTHON) data/multilingual/Latn.PIS/Sans_8/pdf_to_json_test_Latn.PIS_Sans_8.py > data/multilingual/Latn.PIS/Sans_8/pdf_to_json_test_Latn.PIS_Sans_8.json 2>&1
Latn.PIS_Serif_12:
	-$(PYTHON) data/multilingual/Latn.PIS/Serif_12/pdf_to_json_test_Latn.PIS_Serif_12.py > data/multilingual/Latn.PIS/Serif_12/pdf_to_json_test_Latn.PIS_Serif_12.json 2>&1
Latn.PIS_Serif_16:
	-$(PYTHON) data/multilingual/Latn.PIS/Serif_16/pdf_to_json_test_Latn.PIS_Serif_16.py > data/multilingual/Latn.PIS/Serif_16/pdf_to_json_test_Latn.PIS_Serif_16.json 2>&1
Latn.PIS_Serif_8:
	-$(PYTHON) data/multilingual/Latn.PIS/Serif_8/pdf_to_json_test_Latn.PIS_Serif_8.py > data/multilingual/Latn.PIS/Serif_8/pdf_to_json_test_Latn.PIS_Serif_8.json 2>&1
Latn.PIS_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.PIS/Sun-ExtA_12/pdf_to_json_test_Latn.PIS_Sun-ExtA_12.py > data/multilingual/Latn.PIS/Sun-ExtA_12/pdf_to_json_test_Latn.PIS_Sun-ExtA_12.json 2>&1
Latn.PIS_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.PIS/Sun-ExtA_16/pdf_to_json_test_Latn.PIS_Sun-ExtA_16.py > data/multilingual/Latn.PIS/Sun-ExtA_16/pdf_to_json_test_Latn.PIS_Sun-ExtA_16.json 2>&1
Latn.PIS_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.PIS/Sun-ExtA_8/pdf_to_json_test_Latn.PIS_Sun-ExtA_8.py > data/multilingual/Latn.PIS/Sun-ExtA_8/pdf_to_json_test_Latn.PIS_Sun-ExtA_8.json 2>&1


Latn.PIS_all : Latn.PIS_Mono_12 Latn.PIS_Mono_16 Latn.PIS_Mono_8 Latn.PIS_Sans_12 Latn.PIS_Sans_16 Latn.PIS_Sans_8 Latn.PIS_Serif_12 Latn.PIS_Serif_16 Latn.PIS_Serif_8 Latn.PIS_Sun-ExtA_12 Latn.PIS_Sun-ExtA_16 Latn.PIS_Sun-ExtA_8
