PYTHON=python3


Latn.BIS_Mono_12:
	-$(PYTHON) data/multilingual/Latn.BIS/Mono_12/pdf_to_json_test_Latn.BIS_Mono_12.py > data/multilingual/Latn.BIS/Mono_12/pdf_to_json_test_Latn.BIS_Mono_12.json 2>&1
Latn.BIS_Mono_16:
	-$(PYTHON) data/multilingual/Latn.BIS/Mono_16/pdf_to_json_test_Latn.BIS_Mono_16.py > data/multilingual/Latn.BIS/Mono_16/pdf_to_json_test_Latn.BIS_Mono_16.json 2>&1
Latn.BIS_Mono_8:
	-$(PYTHON) data/multilingual/Latn.BIS/Mono_8/pdf_to_json_test_Latn.BIS_Mono_8.py > data/multilingual/Latn.BIS/Mono_8/pdf_to_json_test_Latn.BIS_Mono_8.json 2>&1
Latn.BIS_Sans_12:
	-$(PYTHON) data/multilingual/Latn.BIS/Sans_12/pdf_to_json_test_Latn.BIS_Sans_12.py > data/multilingual/Latn.BIS/Sans_12/pdf_to_json_test_Latn.BIS_Sans_12.json 2>&1
Latn.BIS_Sans_16:
	-$(PYTHON) data/multilingual/Latn.BIS/Sans_16/pdf_to_json_test_Latn.BIS_Sans_16.py > data/multilingual/Latn.BIS/Sans_16/pdf_to_json_test_Latn.BIS_Sans_16.json 2>&1
Latn.BIS_Sans_8:
	-$(PYTHON) data/multilingual/Latn.BIS/Sans_8/pdf_to_json_test_Latn.BIS_Sans_8.py > data/multilingual/Latn.BIS/Sans_8/pdf_to_json_test_Latn.BIS_Sans_8.json 2>&1
Latn.BIS_Serif_12:
	-$(PYTHON) data/multilingual/Latn.BIS/Serif_12/pdf_to_json_test_Latn.BIS_Serif_12.py > data/multilingual/Latn.BIS/Serif_12/pdf_to_json_test_Latn.BIS_Serif_12.json 2>&1
Latn.BIS_Serif_16:
	-$(PYTHON) data/multilingual/Latn.BIS/Serif_16/pdf_to_json_test_Latn.BIS_Serif_16.py > data/multilingual/Latn.BIS/Serif_16/pdf_to_json_test_Latn.BIS_Serif_16.json 2>&1
Latn.BIS_Serif_8:
	-$(PYTHON) data/multilingual/Latn.BIS/Serif_8/pdf_to_json_test_Latn.BIS_Serif_8.py > data/multilingual/Latn.BIS/Serif_8/pdf_to_json_test_Latn.BIS_Serif_8.json 2>&1
Latn.BIS_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.BIS/Sun-ExtA_12/pdf_to_json_test_Latn.BIS_Sun-ExtA_12.py > data/multilingual/Latn.BIS/Sun-ExtA_12/pdf_to_json_test_Latn.BIS_Sun-ExtA_12.json 2>&1
Latn.BIS_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.BIS/Sun-ExtA_16/pdf_to_json_test_Latn.BIS_Sun-ExtA_16.py > data/multilingual/Latn.BIS/Sun-ExtA_16/pdf_to_json_test_Latn.BIS_Sun-ExtA_16.json 2>&1
Latn.BIS_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.BIS/Sun-ExtA_8/pdf_to_json_test_Latn.BIS_Sun-ExtA_8.py > data/multilingual/Latn.BIS/Sun-ExtA_8/pdf_to_json_test_Latn.BIS_Sun-ExtA_8.json 2>&1


Latn.BIS_all : Latn.BIS_Mono_12 Latn.BIS_Mono_16 Latn.BIS_Mono_8 Latn.BIS_Sans_12 Latn.BIS_Sans_16 Latn.BIS_Sans_8 Latn.BIS_Serif_12 Latn.BIS_Serif_16 Latn.BIS_Serif_8 Latn.BIS_Sun-ExtA_12 Latn.BIS_Sun-ExtA_16 Latn.BIS_Sun-ExtA_8
