PYTHON=python3


Ethi.AMH_Mono_12:
	-$(PYTHON) "data/multilingual/Ethi.AMH/Mono_12/pdf_to_json_test_Ethi.AMH_Mono_12.py" > "data/multilingual/Ethi.AMH/Mono_12/pdf_to_json_test_Ethi.AMH_Mono_12.json" 2>&1
Ethi.AMH_Mono_16:
	-$(PYTHON) "data/multilingual/Ethi.AMH/Mono_16/pdf_to_json_test_Ethi.AMH_Mono_16.py" > "data/multilingual/Ethi.AMH/Mono_16/pdf_to_json_test_Ethi.AMH_Mono_16.json" 2>&1
Ethi.AMH_Mono_8:
	-$(PYTHON) "data/multilingual/Ethi.AMH/Mono_8/pdf_to_json_test_Ethi.AMH_Mono_8.py" > "data/multilingual/Ethi.AMH/Mono_8/pdf_to_json_test_Ethi.AMH_Mono_8.json" 2>&1
Ethi.AMH_Sans_12:
	-$(PYTHON) "data/multilingual/Ethi.AMH/Sans_12/pdf_to_json_test_Ethi.AMH_Sans_12.py" > "data/multilingual/Ethi.AMH/Sans_12/pdf_to_json_test_Ethi.AMH_Sans_12.json" 2>&1
Ethi.AMH_Sans_16:
	-$(PYTHON) "data/multilingual/Ethi.AMH/Sans_16/pdf_to_json_test_Ethi.AMH_Sans_16.py" > "data/multilingual/Ethi.AMH/Sans_16/pdf_to_json_test_Ethi.AMH_Sans_16.json" 2>&1
Ethi.AMH_Sans_8:
	-$(PYTHON) "data/multilingual/Ethi.AMH/Sans_8/pdf_to_json_test_Ethi.AMH_Sans_8.py" > "data/multilingual/Ethi.AMH/Sans_8/pdf_to_json_test_Ethi.AMH_Sans_8.json" 2>&1
Ethi.AMH_Serif_12:
	-$(PYTHON) "data/multilingual/Ethi.AMH/Serif_12/pdf_to_json_test_Ethi.AMH_Serif_12.py" > "data/multilingual/Ethi.AMH/Serif_12/pdf_to_json_test_Ethi.AMH_Serif_12.json" 2>&1
Ethi.AMH_Serif_16:
	-$(PYTHON) "data/multilingual/Ethi.AMH/Serif_16/pdf_to_json_test_Ethi.AMH_Serif_16.py" > "data/multilingual/Ethi.AMH/Serif_16/pdf_to_json_test_Ethi.AMH_Serif_16.json" 2>&1
Ethi.AMH_Serif_8:
	-$(PYTHON) "data/multilingual/Ethi.AMH/Serif_8/pdf_to_json_test_Ethi.AMH_Serif_8.py" > "data/multilingual/Ethi.AMH/Serif_8/pdf_to_json_test_Ethi.AMH_Serif_8.json" 2>&1
Ethi.AMH_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Ethi.AMH/Sun-ExtA_12/pdf_to_json_test_Ethi.AMH_Sun-ExtA_12.py" > "data/multilingual/Ethi.AMH/Sun-ExtA_12/pdf_to_json_test_Ethi.AMH_Sun-ExtA_12.json" 2>&1
Ethi.AMH_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Ethi.AMH/Sun-ExtA_16/pdf_to_json_test_Ethi.AMH_Sun-ExtA_16.py" > "data/multilingual/Ethi.AMH/Sun-ExtA_16/pdf_to_json_test_Ethi.AMH_Sun-ExtA_16.json" 2>&1
Ethi.AMH_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Ethi.AMH/Sun-ExtA_8/pdf_to_json_test_Ethi.AMH_Sun-ExtA_8.py" > "data/multilingual/Ethi.AMH/Sun-ExtA_8/pdf_to_json_test_Ethi.AMH_Sun-ExtA_8.json" 2>&1


Ethi.AMH_all : Ethi.AMH_Mono_12 Ethi.AMH_Mono_16 Ethi.AMH_Mono_8 Ethi.AMH_Sans_12 Ethi.AMH_Sans_16 Ethi.AMH_Sans_8 Ethi.AMH_Serif_12 Ethi.AMH_Serif_16 Ethi.AMH_Serif_8 Ethi.AMH_Sun-ExtA_12 Ethi.AMH_Sun-ExtA_16 Ethi.AMH_Sun-ExtA_8
