PYTHON=python3


Deva.BHO_Mono_12:
	-$(PYTHON) data/multilingual/Deva.BHO/Mono_12/pdf_to_json_test_Deva.BHO_Mono_12.py > data/multilingual/Deva.BHO/Mono_12/pdf_to_json_test_Deva.BHO_Mono_12.json 2>&1
Deva.BHO_Mono_16:
	-$(PYTHON) data/multilingual/Deva.BHO/Mono_16/pdf_to_json_test_Deva.BHO_Mono_16.py > data/multilingual/Deva.BHO/Mono_16/pdf_to_json_test_Deva.BHO_Mono_16.json 2>&1
Deva.BHO_Mono_8:
	-$(PYTHON) data/multilingual/Deva.BHO/Mono_8/pdf_to_json_test_Deva.BHO_Mono_8.py > data/multilingual/Deva.BHO/Mono_8/pdf_to_json_test_Deva.BHO_Mono_8.json 2>&1
Deva.BHO_Sans_12:
	-$(PYTHON) data/multilingual/Deva.BHO/Sans_12/pdf_to_json_test_Deva.BHO_Sans_12.py > data/multilingual/Deva.BHO/Sans_12/pdf_to_json_test_Deva.BHO_Sans_12.json 2>&1
Deva.BHO_Sans_16:
	-$(PYTHON) data/multilingual/Deva.BHO/Sans_16/pdf_to_json_test_Deva.BHO_Sans_16.py > data/multilingual/Deva.BHO/Sans_16/pdf_to_json_test_Deva.BHO_Sans_16.json 2>&1
Deva.BHO_Sans_8:
	-$(PYTHON) data/multilingual/Deva.BHO/Sans_8/pdf_to_json_test_Deva.BHO_Sans_8.py > data/multilingual/Deva.BHO/Sans_8/pdf_to_json_test_Deva.BHO_Sans_8.json 2>&1
Deva.BHO_Serif_12:
	-$(PYTHON) data/multilingual/Deva.BHO/Serif_12/pdf_to_json_test_Deva.BHO_Serif_12.py > data/multilingual/Deva.BHO/Serif_12/pdf_to_json_test_Deva.BHO_Serif_12.json 2>&1
Deva.BHO_Serif_16:
	-$(PYTHON) data/multilingual/Deva.BHO/Serif_16/pdf_to_json_test_Deva.BHO_Serif_16.py > data/multilingual/Deva.BHO/Serif_16/pdf_to_json_test_Deva.BHO_Serif_16.json 2>&1
Deva.BHO_Serif_8:
	-$(PYTHON) data/multilingual/Deva.BHO/Serif_8/pdf_to_json_test_Deva.BHO_Serif_8.py > data/multilingual/Deva.BHO/Serif_8/pdf_to_json_test_Deva.BHO_Serif_8.json 2>&1
Deva.BHO_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Deva.BHO/Sun-ExtA_12/pdf_to_json_test_Deva.BHO_Sun-ExtA_12.py > data/multilingual/Deva.BHO/Sun-ExtA_12/pdf_to_json_test_Deva.BHO_Sun-ExtA_12.json 2>&1
Deva.BHO_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Deva.BHO/Sun-ExtA_16/pdf_to_json_test_Deva.BHO_Sun-ExtA_16.py > data/multilingual/Deva.BHO/Sun-ExtA_16/pdf_to_json_test_Deva.BHO_Sun-ExtA_16.json 2>&1
Deva.BHO_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Deva.BHO/Sun-ExtA_8/pdf_to_json_test_Deva.BHO_Sun-ExtA_8.py > data/multilingual/Deva.BHO/Sun-ExtA_8/pdf_to_json_test_Deva.BHO_Sun-ExtA_8.json 2>&1


Deva.BHO_all : Deva.BHO_Mono_12 Deva.BHO_Mono_16 Deva.BHO_Mono_8 Deva.BHO_Sans_12 Deva.BHO_Sans_16 Deva.BHO_Sans_8 Deva.BHO_Serif_12 Deva.BHO_Serif_16 Deva.BHO_Serif_8 Deva.BHO_Sun-ExtA_12 Deva.BHO_Sun-ExtA_16 Deva.BHO_Sun-ExtA_8
