PYTHON=python3


Latn.AYR_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.AYR/Mono_12/pdf_to_json_test_Latn.AYR_Mono_12.py" > "data/multilingual/Latn.AYR/Mono_12/pdf_to_json_test_Latn.AYR_Mono_12.json" 2>&1
Latn.AYR_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.AYR/Mono_16/pdf_to_json_test_Latn.AYR_Mono_16.py" > "data/multilingual/Latn.AYR/Mono_16/pdf_to_json_test_Latn.AYR_Mono_16.json" 2>&1
Latn.AYR_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.AYR/Mono_8/pdf_to_json_test_Latn.AYR_Mono_8.py" > "data/multilingual/Latn.AYR/Mono_8/pdf_to_json_test_Latn.AYR_Mono_8.json" 2>&1
Latn.AYR_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.AYR/Sans_12/pdf_to_json_test_Latn.AYR_Sans_12.py" > "data/multilingual/Latn.AYR/Sans_12/pdf_to_json_test_Latn.AYR_Sans_12.json" 2>&1
Latn.AYR_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.AYR/Sans_16/pdf_to_json_test_Latn.AYR_Sans_16.py" > "data/multilingual/Latn.AYR/Sans_16/pdf_to_json_test_Latn.AYR_Sans_16.json" 2>&1
Latn.AYR_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.AYR/Sans_8/pdf_to_json_test_Latn.AYR_Sans_8.py" > "data/multilingual/Latn.AYR/Sans_8/pdf_to_json_test_Latn.AYR_Sans_8.json" 2>&1
Latn.AYR_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.AYR/Serif_12/pdf_to_json_test_Latn.AYR_Serif_12.py" > "data/multilingual/Latn.AYR/Serif_12/pdf_to_json_test_Latn.AYR_Serif_12.json" 2>&1
Latn.AYR_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.AYR/Serif_16/pdf_to_json_test_Latn.AYR_Serif_16.py" > "data/multilingual/Latn.AYR/Serif_16/pdf_to_json_test_Latn.AYR_Serif_16.json" 2>&1
Latn.AYR_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.AYR/Serif_8/pdf_to_json_test_Latn.AYR_Serif_8.py" > "data/multilingual/Latn.AYR/Serif_8/pdf_to_json_test_Latn.AYR_Serif_8.json" 2>&1
Latn.AYR_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.AYR/Sun-ExtA_12/pdf_to_json_test_Latn.AYR_Sun-ExtA_12.py" > "data/multilingual/Latn.AYR/Sun-ExtA_12/pdf_to_json_test_Latn.AYR_Sun-ExtA_12.json" 2>&1
Latn.AYR_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.AYR/Sun-ExtA_16/pdf_to_json_test_Latn.AYR_Sun-ExtA_16.py" > "data/multilingual/Latn.AYR/Sun-ExtA_16/pdf_to_json_test_Latn.AYR_Sun-ExtA_16.json" 2>&1
Latn.AYR_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.AYR/Sun-ExtA_8/pdf_to_json_test_Latn.AYR_Sun-ExtA_8.py" > "data/multilingual/Latn.AYR/Sun-ExtA_8/pdf_to_json_test_Latn.AYR_Sun-ExtA_8.json" 2>&1


Latn.AYR_all : Latn.AYR_Mono_12 Latn.AYR_Mono_16 Latn.AYR_Mono_8 Latn.AYR_Sans_12 Latn.AYR_Sans_16 Latn.AYR_Sans_8 Latn.AYR_Serif_12 Latn.AYR_Serif_16 Latn.AYR_Serif_8 Latn.AYR_Sun-ExtA_12 Latn.AYR_Sun-ExtA_16 Latn.AYR_Sun-ExtA_8
