PYTHON=python3


Cyrl.NIO_Mono_12:
	-$(PYTHON) "data/multilingual/Cyrl.NIO/Mono_12/pdf_to_json_test_Cyrl.NIO_Mono_12.py" > "data/multilingual/Cyrl.NIO/Mono_12/pdf_to_json_test_Cyrl.NIO_Mono_12.json" 2>&1
Cyrl.NIO_Mono_16:
	-$(PYTHON) "data/multilingual/Cyrl.NIO/Mono_16/pdf_to_json_test_Cyrl.NIO_Mono_16.py" > "data/multilingual/Cyrl.NIO/Mono_16/pdf_to_json_test_Cyrl.NIO_Mono_16.json" 2>&1
Cyrl.NIO_Mono_8:
	-$(PYTHON) "data/multilingual/Cyrl.NIO/Mono_8/pdf_to_json_test_Cyrl.NIO_Mono_8.py" > "data/multilingual/Cyrl.NIO/Mono_8/pdf_to_json_test_Cyrl.NIO_Mono_8.json" 2>&1
Cyrl.NIO_Sans_12:
	-$(PYTHON) "data/multilingual/Cyrl.NIO/Sans_12/pdf_to_json_test_Cyrl.NIO_Sans_12.py" > "data/multilingual/Cyrl.NIO/Sans_12/pdf_to_json_test_Cyrl.NIO_Sans_12.json" 2>&1
Cyrl.NIO_Sans_16:
	-$(PYTHON) "data/multilingual/Cyrl.NIO/Sans_16/pdf_to_json_test_Cyrl.NIO_Sans_16.py" > "data/multilingual/Cyrl.NIO/Sans_16/pdf_to_json_test_Cyrl.NIO_Sans_16.json" 2>&1
Cyrl.NIO_Sans_8:
	-$(PYTHON) "data/multilingual/Cyrl.NIO/Sans_8/pdf_to_json_test_Cyrl.NIO_Sans_8.py" > "data/multilingual/Cyrl.NIO/Sans_8/pdf_to_json_test_Cyrl.NIO_Sans_8.json" 2>&1
Cyrl.NIO_Serif_12:
	-$(PYTHON) "data/multilingual/Cyrl.NIO/Serif_12/pdf_to_json_test_Cyrl.NIO_Serif_12.py" > "data/multilingual/Cyrl.NIO/Serif_12/pdf_to_json_test_Cyrl.NIO_Serif_12.json" 2>&1
Cyrl.NIO_Serif_16:
	-$(PYTHON) "data/multilingual/Cyrl.NIO/Serif_16/pdf_to_json_test_Cyrl.NIO_Serif_16.py" > "data/multilingual/Cyrl.NIO/Serif_16/pdf_to_json_test_Cyrl.NIO_Serif_16.json" 2>&1
Cyrl.NIO_Serif_8:
	-$(PYTHON) "data/multilingual/Cyrl.NIO/Serif_8/pdf_to_json_test_Cyrl.NIO_Serif_8.py" > "data/multilingual/Cyrl.NIO/Serif_8/pdf_to_json_test_Cyrl.NIO_Serif_8.json" 2>&1
Cyrl.NIO_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Cyrl.NIO/Sun-ExtA_12/pdf_to_json_test_Cyrl.NIO_Sun-ExtA_12.py" > "data/multilingual/Cyrl.NIO/Sun-ExtA_12/pdf_to_json_test_Cyrl.NIO_Sun-ExtA_12.json" 2>&1
Cyrl.NIO_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Cyrl.NIO/Sun-ExtA_16/pdf_to_json_test_Cyrl.NIO_Sun-ExtA_16.py" > "data/multilingual/Cyrl.NIO/Sun-ExtA_16/pdf_to_json_test_Cyrl.NIO_Sun-ExtA_16.json" 2>&1
Cyrl.NIO_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Cyrl.NIO/Sun-ExtA_8/pdf_to_json_test_Cyrl.NIO_Sun-ExtA_8.py" > "data/multilingual/Cyrl.NIO/Sun-ExtA_8/pdf_to_json_test_Cyrl.NIO_Sun-ExtA_8.json" 2>&1


Cyrl.NIO_all : Cyrl.NIO_Mono_12 Cyrl.NIO_Mono_16 Cyrl.NIO_Mono_8 Cyrl.NIO_Sans_12 Cyrl.NIO_Sans_16 Cyrl.NIO_Sans_8 Cyrl.NIO_Serif_12 Cyrl.NIO_Serif_16 Cyrl.NIO_Serif_8 Cyrl.NIO_Sun-ExtA_12 Cyrl.NIO_Sun-ExtA_16 Cyrl.NIO_Sun-ExtA_8
