PYTHON=python3


Latn.YAP_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.YAP/Mono_12/pdf_to_json_test_Latn.YAP_Mono_12.py" > "data/multilingual/Latn.YAP/Mono_12/pdf_to_json_test_Latn.YAP_Mono_12.json" 2>&1
Latn.YAP_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.YAP/Mono_16/pdf_to_json_test_Latn.YAP_Mono_16.py" > "data/multilingual/Latn.YAP/Mono_16/pdf_to_json_test_Latn.YAP_Mono_16.json" 2>&1
Latn.YAP_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.YAP/Mono_8/pdf_to_json_test_Latn.YAP_Mono_8.py" > "data/multilingual/Latn.YAP/Mono_8/pdf_to_json_test_Latn.YAP_Mono_8.json" 2>&1
Latn.YAP_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.YAP/Sans_12/pdf_to_json_test_Latn.YAP_Sans_12.py" > "data/multilingual/Latn.YAP/Sans_12/pdf_to_json_test_Latn.YAP_Sans_12.json" 2>&1
Latn.YAP_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.YAP/Sans_16/pdf_to_json_test_Latn.YAP_Sans_16.py" > "data/multilingual/Latn.YAP/Sans_16/pdf_to_json_test_Latn.YAP_Sans_16.json" 2>&1
Latn.YAP_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.YAP/Sans_8/pdf_to_json_test_Latn.YAP_Sans_8.py" > "data/multilingual/Latn.YAP/Sans_8/pdf_to_json_test_Latn.YAP_Sans_8.json" 2>&1
Latn.YAP_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.YAP/Serif_12/pdf_to_json_test_Latn.YAP_Serif_12.py" > "data/multilingual/Latn.YAP/Serif_12/pdf_to_json_test_Latn.YAP_Serif_12.json" 2>&1
Latn.YAP_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.YAP/Serif_16/pdf_to_json_test_Latn.YAP_Serif_16.py" > "data/multilingual/Latn.YAP/Serif_16/pdf_to_json_test_Latn.YAP_Serif_16.json" 2>&1
Latn.YAP_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.YAP/Serif_8/pdf_to_json_test_Latn.YAP_Serif_8.py" > "data/multilingual/Latn.YAP/Serif_8/pdf_to_json_test_Latn.YAP_Serif_8.json" 2>&1
Latn.YAP_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.YAP/Sun-ExtA_12/pdf_to_json_test_Latn.YAP_Sun-ExtA_12.py" > "data/multilingual/Latn.YAP/Sun-ExtA_12/pdf_to_json_test_Latn.YAP_Sun-ExtA_12.json" 2>&1
Latn.YAP_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.YAP/Sun-ExtA_16/pdf_to_json_test_Latn.YAP_Sun-ExtA_16.py" > "data/multilingual/Latn.YAP/Sun-ExtA_16/pdf_to_json_test_Latn.YAP_Sun-ExtA_16.json" 2>&1
Latn.YAP_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.YAP/Sun-ExtA_8/pdf_to_json_test_Latn.YAP_Sun-ExtA_8.py" > "data/multilingual/Latn.YAP/Sun-ExtA_8/pdf_to_json_test_Latn.YAP_Sun-ExtA_8.json" 2>&1


Latn.YAP_all : Latn.YAP_Mono_12 Latn.YAP_Mono_16 Latn.YAP_Mono_8 Latn.YAP_Sans_12 Latn.YAP_Sans_16 Latn.YAP_Sans_8 Latn.YAP_Serif_12 Latn.YAP_Serif_16 Latn.YAP_Serif_8 Latn.YAP_Sun-ExtA_12 Latn.YAP_Sun-ExtA_16 Latn.YAP_Sun-ExtA_8
