PYTHON=python3


Latn.IBO_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.IBO/Mono_12/pdf_to_json_test_Latn.IBO_Mono_12.py" > "data/multilingual/Latn.IBO/Mono_12/pdf_to_json_test_Latn.IBO_Mono_12.json" 2>&1
Latn.IBO_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.IBO/Mono_16/pdf_to_json_test_Latn.IBO_Mono_16.py" > "data/multilingual/Latn.IBO/Mono_16/pdf_to_json_test_Latn.IBO_Mono_16.json" 2>&1
Latn.IBO_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.IBO/Mono_8/pdf_to_json_test_Latn.IBO_Mono_8.py" > "data/multilingual/Latn.IBO/Mono_8/pdf_to_json_test_Latn.IBO_Mono_8.json" 2>&1
Latn.IBO_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.IBO/Sans_12/pdf_to_json_test_Latn.IBO_Sans_12.py" > "data/multilingual/Latn.IBO/Sans_12/pdf_to_json_test_Latn.IBO_Sans_12.json" 2>&1
Latn.IBO_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.IBO/Sans_16/pdf_to_json_test_Latn.IBO_Sans_16.py" > "data/multilingual/Latn.IBO/Sans_16/pdf_to_json_test_Latn.IBO_Sans_16.json" 2>&1
Latn.IBO_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.IBO/Sans_8/pdf_to_json_test_Latn.IBO_Sans_8.py" > "data/multilingual/Latn.IBO/Sans_8/pdf_to_json_test_Latn.IBO_Sans_8.json" 2>&1
Latn.IBO_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.IBO/Serif_12/pdf_to_json_test_Latn.IBO_Serif_12.py" > "data/multilingual/Latn.IBO/Serif_12/pdf_to_json_test_Latn.IBO_Serif_12.json" 2>&1
Latn.IBO_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.IBO/Serif_16/pdf_to_json_test_Latn.IBO_Serif_16.py" > "data/multilingual/Latn.IBO/Serif_16/pdf_to_json_test_Latn.IBO_Serif_16.json" 2>&1
Latn.IBO_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.IBO/Serif_8/pdf_to_json_test_Latn.IBO_Serif_8.py" > "data/multilingual/Latn.IBO/Serif_8/pdf_to_json_test_Latn.IBO_Serif_8.json" 2>&1
Latn.IBO_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.IBO/Sun-ExtA_12/pdf_to_json_test_Latn.IBO_Sun-ExtA_12.py" > "data/multilingual/Latn.IBO/Sun-ExtA_12/pdf_to_json_test_Latn.IBO_Sun-ExtA_12.json" 2>&1
Latn.IBO_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.IBO/Sun-ExtA_16/pdf_to_json_test_Latn.IBO_Sun-ExtA_16.py" > "data/multilingual/Latn.IBO/Sun-ExtA_16/pdf_to_json_test_Latn.IBO_Sun-ExtA_16.json" 2>&1
Latn.IBO_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.IBO/Sun-ExtA_8/pdf_to_json_test_Latn.IBO_Sun-ExtA_8.py" > "data/multilingual/Latn.IBO/Sun-ExtA_8/pdf_to_json_test_Latn.IBO_Sun-ExtA_8.json" 2>&1


Latn.IBO_all : Latn.IBO_Mono_12 Latn.IBO_Mono_16 Latn.IBO_Mono_8 Latn.IBO_Sans_12 Latn.IBO_Sans_16 Latn.IBO_Sans_8 Latn.IBO_Serif_12 Latn.IBO_Serif_16 Latn.IBO_Serif_8 Latn.IBO_Sun-ExtA_12 Latn.IBO_Sun-ExtA_16 Latn.IBO_Sun-ExtA_8
