PYTHON=python3


Latn.NOT_Mono_12:
	-$(PYTHON) data/multilingual/Latn.NOT/Mono_12/pdf_to_json_test_Latn.NOT_Mono_12.py > data/multilingual/Latn.NOT/Mono_12/pdf_to_json_test_Latn.NOT_Mono_12.json 2>&1
Latn.NOT_Mono_16:
	-$(PYTHON) data/multilingual/Latn.NOT/Mono_16/pdf_to_json_test_Latn.NOT_Mono_16.py > data/multilingual/Latn.NOT/Mono_16/pdf_to_json_test_Latn.NOT_Mono_16.json 2>&1
Latn.NOT_Mono_8:
	-$(PYTHON) data/multilingual/Latn.NOT/Mono_8/pdf_to_json_test_Latn.NOT_Mono_8.py > data/multilingual/Latn.NOT/Mono_8/pdf_to_json_test_Latn.NOT_Mono_8.json 2>&1
Latn.NOT_Sans_12:
	-$(PYTHON) data/multilingual/Latn.NOT/Sans_12/pdf_to_json_test_Latn.NOT_Sans_12.py > data/multilingual/Latn.NOT/Sans_12/pdf_to_json_test_Latn.NOT_Sans_12.json 2>&1
Latn.NOT_Sans_16:
	-$(PYTHON) data/multilingual/Latn.NOT/Sans_16/pdf_to_json_test_Latn.NOT_Sans_16.py > data/multilingual/Latn.NOT/Sans_16/pdf_to_json_test_Latn.NOT_Sans_16.json 2>&1
Latn.NOT_Sans_8:
	-$(PYTHON) data/multilingual/Latn.NOT/Sans_8/pdf_to_json_test_Latn.NOT_Sans_8.py > data/multilingual/Latn.NOT/Sans_8/pdf_to_json_test_Latn.NOT_Sans_8.json 2>&1
Latn.NOT_Serif_12:
	-$(PYTHON) data/multilingual/Latn.NOT/Serif_12/pdf_to_json_test_Latn.NOT_Serif_12.py > data/multilingual/Latn.NOT/Serif_12/pdf_to_json_test_Latn.NOT_Serif_12.json 2>&1
Latn.NOT_Serif_16:
	-$(PYTHON) data/multilingual/Latn.NOT/Serif_16/pdf_to_json_test_Latn.NOT_Serif_16.py > data/multilingual/Latn.NOT/Serif_16/pdf_to_json_test_Latn.NOT_Serif_16.json 2>&1
Latn.NOT_Serif_8:
	-$(PYTHON) data/multilingual/Latn.NOT/Serif_8/pdf_to_json_test_Latn.NOT_Serif_8.py > data/multilingual/Latn.NOT/Serif_8/pdf_to_json_test_Latn.NOT_Serif_8.json 2>&1
Latn.NOT_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.NOT/Sun-ExtA_12/pdf_to_json_test_Latn.NOT_Sun-ExtA_12.py > data/multilingual/Latn.NOT/Sun-ExtA_12/pdf_to_json_test_Latn.NOT_Sun-ExtA_12.json 2>&1
Latn.NOT_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.NOT/Sun-ExtA_16/pdf_to_json_test_Latn.NOT_Sun-ExtA_16.py > data/multilingual/Latn.NOT/Sun-ExtA_16/pdf_to_json_test_Latn.NOT_Sun-ExtA_16.json 2>&1
Latn.NOT_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.NOT/Sun-ExtA_8/pdf_to_json_test_Latn.NOT_Sun-ExtA_8.py > data/multilingual/Latn.NOT/Sun-ExtA_8/pdf_to_json_test_Latn.NOT_Sun-ExtA_8.json 2>&1


Latn.NOT_all : Latn.NOT_Mono_12 Latn.NOT_Mono_16 Latn.NOT_Mono_8 Latn.NOT_Sans_12 Latn.NOT_Sans_16 Latn.NOT_Sans_8 Latn.NOT_Serif_12 Latn.NOT_Serif_16 Latn.NOT_Serif_8 Latn.NOT_Sun-ExtA_12 Latn.NOT_Sun-ExtA_16 Latn.NOT_Sun-ExtA_8
