PYTHON=python3


Latn.BCI_Mono_12:
	-$(PYTHON) data/multilingual/Latn.BCI/Mono_12/pdf_to_json_test_Latn.BCI_Mono_12.py > data/multilingual/Latn.BCI/Mono_12/pdf_to_json_test_Latn.BCI_Mono_12.json 2>&1
Latn.BCI_Mono_16:
	-$(PYTHON) data/multilingual/Latn.BCI/Mono_16/pdf_to_json_test_Latn.BCI_Mono_16.py > data/multilingual/Latn.BCI/Mono_16/pdf_to_json_test_Latn.BCI_Mono_16.json 2>&1
Latn.BCI_Mono_8:
	-$(PYTHON) data/multilingual/Latn.BCI/Mono_8/pdf_to_json_test_Latn.BCI_Mono_8.py > data/multilingual/Latn.BCI/Mono_8/pdf_to_json_test_Latn.BCI_Mono_8.json 2>&1
Latn.BCI_Sans_12:
	-$(PYTHON) data/multilingual/Latn.BCI/Sans_12/pdf_to_json_test_Latn.BCI_Sans_12.py > data/multilingual/Latn.BCI/Sans_12/pdf_to_json_test_Latn.BCI_Sans_12.json 2>&1
Latn.BCI_Sans_16:
	-$(PYTHON) data/multilingual/Latn.BCI/Sans_16/pdf_to_json_test_Latn.BCI_Sans_16.py > data/multilingual/Latn.BCI/Sans_16/pdf_to_json_test_Latn.BCI_Sans_16.json 2>&1
Latn.BCI_Sans_8:
	-$(PYTHON) data/multilingual/Latn.BCI/Sans_8/pdf_to_json_test_Latn.BCI_Sans_8.py > data/multilingual/Latn.BCI/Sans_8/pdf_to_json_test_Latn.BCI_Sans_8.json 2>&1
Latn.BCI_Serif_12:
	-$(PYTHON) data/multilingual/Latn.BCI/Serif_12/pdf_to_json_test_Latn.BCI_Serif_12.py > data/multilingual/Latn.BCI/Serif_12/pdf_to_json_test_Latn.BCI_Serif_12.json 2>&1
Latn.BCI_Serif_16:
	-$(PYTHON) data/multilingual/Latn.BCI/Serif_16/pdf_to_json_test_Latn.BCI_Serif_16.py > data/multilingual/Latn.BCI/Serif_16/pdf_to_json_test_Latn.BCI_Serif_16.json 2>&1
Latn.BCI_Serif_8:
	-$(PYTHON) data/multilingual/Latn.BCI/Serif_8/pdf_to_json_test_Latn.BCI_Serif_8.py > data/multilingual/Latn.BCI/Serif_8/pdf_to_json_test_Latn.BCI_Serif_8.json 2>&1
Latn.BCI_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.BCI/Sun-ExtA_12/pdf_to_json_test_Latn.BCI_Sun-ExtA_12.py > data/multilingual/Latn.BCI/Sun-ExtA_12/pdf_to_json_test_Latn.BCI_Sun-ExtA_12.json 2>&1
Latn.BCI_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.BCI/Sun-ExtA_16/pdf_to_json_test_Latn.BCI_Sun-ExtA_16.py > data/multilingual/Latn.BCI/Sun-ExtA_16/pdf_to_json_test_Latn.BCI_Sun-ExtA_16.json 2>&1
Latn.BCI_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.BCI/Sun-ExtA_8/pdf_to_json_test_Latn.BCI_Sun-ExtA_8.py > data/multilingual/Latn.BCI/Sun-ExtA_8/pdf_to_json_test_Latn.BCI_Sun-ExtA_8.json 2>&1


Latn.BCI_all : Latn.BCI_Mono_12 Latn.BCI_Mono_16 Latn.BCI_Mono_8 Latn.BCI_Sans_12 Latn.BCI_Sans_16 Latn.BCI_Sans_8 Latn.BCI_Serif_12 Latn.BCI_Serif_16 Latn.BCI_Serif_8 Latn.BCI_Sun-ExtA_12 Latn.BCI_Sun-ExtA_16 Latn.BCI_Sun-ExtA_8
