PYTHON=python3


Latn.RUP_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.RUP/Mono_12/pdf_to_json_test_Latn.RUP_Mono_12.py" > "data/multilingual/Latn.RUP/Mono_12/pdf_to_json_test_Latn.RUP_Mono_12.json" 2>&1
Latn.RUP_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.RUP/Mono_16/pdf_to_json_test_Latn.RUP_Mono_16.py" > "data/multilingual/Latn.RUP/Mono_16/pdf_to_json_test_Latn.RUP_Mono_16.json" 2>&1
Latn.RUP_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.RUP/Mono_8/pdf_to_json_test_Latn.RUP_Mono_8.py" > "data/multilingual/Latn.RUP/Mono_8/pdf_to_json_test_Latn.RUP_Mono_8.json" 2>&1
Latn.RUP_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.RUP/Sans_12/pdf_to_json_test_Latn.RUP_Sans_12.py" > "data/multilingual/Latn.RUP/Sans_12/pdf_to_json_test_Latn.RUP_Sans_12.json" 2>&1
Latn.RUP_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.RUP/Sans_16/pdf_to_json_test_Latn.RUP_Sans_16.py" > "data/multilingual/Latn.RUP/Sans_16/pdf_to_json_test_Latn.RUP_Sans_16.json" 2>&1
Latn.RUP_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.RUP/Sans_8/pdf_to_json_test_Latn.RUP_Sans_8.py" > "data/multilingual/Latn.RUP/Sans_8/pdf_to_json_test_Latn.RUP_Sans_8.json" 2>&1
Latn.RUP_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.RUP/Serif_12/pdf_to_json_test_Latn.RUP_Serif_12.py" > "data/multilingual/Latn.RUP/Serif_12/pdf_to_json_test_Latn.RUP_Serif_12.json" 2>&1
Latn.RUP_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.RUP/Serif_16/pdf_to_json_test_Latn.RUP_Serif_16.py" > "data/multilingual/Latn.RUP/Serif_16/pdf_to_json_test_Latn.RUP_Serif_16.json" 2>&1
Latn.RUP_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.RUP/Serif_8/pdf_to_json_test_Latn.RUP_Serif_8.py" > "data/multilingual/Latn.RUP/Serif_8/pdf_to_json_test_Latn.RUP_Serif_8.json" 2>&1
Latn.RUP_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.RUP/Sun-ExtA_12/pdf_to_json_test_Latn.RUP_Sun-ExtA_12.py" > "data/multilingual/Latn.RUP/Sun-ExtA_12/pdf_to_json_test_Latn.RUP_Sun-ExtA_12.json" 2>&1
Latn.RUP_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.RUP/Sun-ExtA_16/pdf_to_json_test_Latn.RUP_Sun-ExtA_16.py" > "data/multilingual/Latn.RUP/Sun-ExtA_16/pdf_to_json_test_Latn.RUP_Sun-ExtA_16.json" 2>&1
Latn.RUP_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.RUP/Sun-ExtA_8/pdf_to_json_test_Latn.RUP_Sun-ExtA_8.py" > "data/multilingual/Latn.RUP/Sun-ExtA_8/pdf_to_json_test_Latn.RUP_Sun-ExtA_8.json" 2>&1


Latn.RUP_all : Latn.RUP_Mono_12 Latn.RUP_Mono_16 Latn.RUP_Mono_8 Latn.RUP_Sans_12 Latn.RUP_Sans_16 Latn.RUP_Sans_8 Latn.RUP_Serif_12 Latn.RUP_Serif_16 Latn.RUP_Serif_8 Latn.RUP_Sun-ExtA_12 Latn.RUP_Sun-ExtA_16 Latn.RUP_Sun-ExtA_8
