PYTHON=python3


Latn.TUK_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.TUK/Mono_12/pdf_to_json_test_Latn.TUK_Mono_12.py" > "data/multilingual/Latn.TUK/Mono_12/pdf_to_json_test_Latn.TUK_Mono_12.json" 2>&1
Latn.TUK_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.TUK/Mono_16/pdf_to_json_test_Latn.TUK_Mono_16.py" > "data/multilingual/Latn.TUK/Mono_16/pdf_to_json_test_Latn.TUK_Mono_16.json" 2>&1
Latn.TUK_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.TUK/Mono_8/pdf_to_json_test_Latn.TUK_Mono_8.py" > "data/multilingual/Latn.TUK/Mono_8/pdf_to_json_test_Latn.TUK_Mono_8.json" 2>&1
Latn.TUK_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.TUK/Sans_12/pdf_to_json_test_Latn.TUK_Sans_12.py" > "data/multilingual/Latn.TUK/Sans_12/pdf_to_json_test_Latn.TUK_Sans_12.json" 2>&1
Latn.TUK_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.TUK/Sans_16/pdf_to_json_test_Latn.TUK_Sans_16.py" > "data/multilingual/Latn.TUK/Sans_16/pdf_to_json_test_Latn.TUK_Sans_16.json" 2>&1
Latn.TUK_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.TUK/Sans_8/pdf_to_json_test_Latn.TUK_Sans_8.py" > "data/multilingual/Latn.TUK/Sans_8/pdf_to_json_test_Latn.TUK_Sans_8.json" 2>&1
Latn.TUK_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.TUK/Serif_12/pdf_to_json_test_Latn.TUK_Serif_12.py" > "data/multilingual/Latn.TUK/Serif_12/pdf_to_json_test_Latn.TUK_Serif_12.json" 2>&1
Latn.TUK_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.TUK/Serif_16/pdf_to_json_test_Latn.TUK_Serif_16.py" > "data/multilingual/Latn.TUK/Serif_16/pdf_to_json_test_Latn.TUK_Serif_16.json" 2>&1
Latn.TUK_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.TUK/Serif_8/pdf_to_json_test_Latn.TUK_Serif_8.py" > "data/multilingual/Latn.TUK/Serif_8/pdf_to_json_test_Latn.TUK_Serif_8.json" 2>&1
Latn.TUK_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.TUK/Sun-ExtA_12/pdf_to_json_test_Latn.TUK_Sun-ExtA_12.py" > "data/multilingual/Latn.TUK/Sun-ExtA_12/pdf_to_json_test_Latn.TUK_Sun-ExtA_12.json" 2>&1
Latn.TUK_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.TUK/Sun-ExtA_16/pdf_to_json_test_Latn.TUK_Sun-ExtA_16.py" > "data/multilingual/Latn.TUK/Sun-ExtA_16/pdf_to_json_test_Latn.TUK_Sun-ExtA_16.json" 2>&1
Latn.TUK_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.TUK/Sun-ExtA_8/pdf_to_json_test_Latn.TUK_Sun-ExtA_8.py" > "data/multilingual/Latn.TUK/Sun-ExtA_8/pdf_to_json_test_Latn.TUK_Sun-ExtA_8.json" 2>&1


Latn.TUK_all : Latn.TUK_Mono_12 Latn.TUK_Mono_16 Latn.TUK_Mono_8 Latn.TUK_Sans_12 Latn.TUK_Sans_16 Latn.TUK_Sans_8 Latn.TUK_Serif_12 Latn.TUK_Serif_16 Latn.TUK_Serif_8 Latn.TUK_Sun-ExtA_12 Latn.TUK_Sun-ExtA_16 Latn.TUK_Sun-ExtA_8
