PYTHON=python3


Latn.CHK_Mono_12:
	-$(PYTHON) data/multilingual/Latn.CHK/Mono_12/pdf_to_json_test_Latn.CHK_Mono_12.py > data/multilingual/Latn.CHK/Mono_12/pdf_to_json_test_Latn.CHK_Mono_12.json 2>&1
Latn.CHK_Mono_16:
	-$(PYTHON) data/multilingual/Latn.CHK/Mono_16/pdf_to_json_test_Latn.CHK_Mono_16.py > data/multilingual/Latn.CHK/Mono_16/pdf_to_json_test_Latn.CHK_Mono_16.json 2>&1
Latn.CHK_Mono_8:
	-$(PYTHON) data/multilingual/Latn.CHK/Mono_8/pdf_to_json_test_Latn.CHK_Mono_8.py > data/multilingual/Latn.CHK/Mono_8/pdf_to_json_test_Latn.CHK_Mono_8.json 2>&1
Latn.CHK_Sans_12:
	-$(PYTHON) data/multilingual/Latn.CHK/Sans_12/pdf_to_json_test_Latn.CHK_Sans_12.py > data/multilingual/Latn.CHK/Sans_12/pdf_to_json_test_Latn.CHK_Sans_12.json 2>&1
Latn.CHK_Sans_16:
	-$(PYTHON) data/multilingual/Latn.CHK/Sans_16/pdf_to_json_test_Latn.CHK_Sans_16.py > data/multilingual/Latn.CHK/Sans_16/pdf_to_json_test_Latn.CHK_Sans_16.json 2>&1
Latn.CHK_Sans_8:
	-$(PYTHON) data/multilingual/Latn.CHK/Sans_8/pdf_to_json_test_Latn.CHK_Sans_8.py > data/multilingual/Latn.CHK/Sans_8/pdf_to_json_test_Latn.CHK_Sans_8.json 2>&1
Latn.CHK_Serif_12:
	-$(PYTHON) data/multilingual/Latn.CHK/Serif_12/pdf_to_json_test_Latn.CHK_Serif_12.py > data/multilingual/Latn.CHK/Serif_12/pdf_to_json_test_Latn.CHK_Serif_12.json 2>&1
Latn.CHK_Serif_16:
	-$(PYTHON) data/multilingual/Latn.CHK/Serif_16/pdf_to_json_test_Latn.CHK_Serif_16.py > data/multilingual/Latn.CHK/Serif_16/pdf_to_json_test_Latn.CHK_Serif_16.json 2>&1
Latn.CHK_Serif_8:
	-$(PYTHON) data/multilingual/Latn.CHK/Serif_8/pdf_to_json_test_Latn.CHK_Serif_8.py > data/multilingual/Latn.CHK/Serif_8/pdf_to_json_test_Latn.CHK_Serif_8.json 2>&1
Latn.CHK_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.CHK/Sun-ExtA_12/pdf_to_json_test_Latn.CHK_Sun-ExtA_12.py > data/multilingual/Latn.CHK/Sun-ExtA_12/pdf_to_json_test_Latn.CHK_Sun-ExtA_12.json 2>&1
Latn.CHK_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.CHK/Sun-ExtA_16/pdf_to_json_test_Latn.CHK_Sun-ExtA_16.py > data/multilingual/Latn.CHK/Sun-ExtA_16/pdf_to_json_test_Latn.CHK_Sun-ExtA_16.json 2>&1
Latn.CHK_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.CHK/Sun-ExtA_8/pdf_to_json_test_Latn.CHK_Sun-ExtA_8.py > data/multilingual/Latn.CHK/Sun-ExtA_8/pdf_to_json_test_Latn.CHK_Sun-ExtA_8.json 2>&1


Latn.CHK_all : Latn.CHK_Mono_12 Latn.CHK_Mono_16 Latn.CHK_Mono_8 Latn.CHK_Sans_12 Latn.CHK_Sans_16 Latn.CHK_Sans_8 Latn.CHK_Serif_12 Latn.CHK_Serif_16 Latn.CHK_Serif_8 Latn.CHK_Sun-ExtA_12 Latn.CHK_Sun-ExtA_16 Latn.CHK_Sun-ExtA_8
