PYTHON=python3


Hans.CMN_Mono_12:
	-$(PYTHON) "data/multilingual/Hans.CMN/Mono_12/pdf_to_json_test_Hans.CMN_Mono_12.py" > "data/multilingual/Hans.CMN/Mono_12/pdf_to_json_test_Hans.CMN_Mono_12.json" 2>&1
Hans.CMN_Mono_16:
	-$(PYTHON) "data/multilingual/Hans.CMN/Mono_16/pdf_to_json_test_Hans.CMN_Mono_16.py" > "data/multilingual/Hans.CMN/Mono_16/pdf_to_json_test_Hans.CMN_Mono_16.json" 2>&1
Hans.CMN_Mono_8:
	-$(PYTHON) "data/multilingual/Hans.CMN/Mono_8/pdf_to_json_test_Hans.CMN_Mono_8.py" > "data/multilingual/Hans.CMN/Mono_8/pdf_to_json_test_Hans.CMN_Mono_8.json" 2>&1
Hans.CMN_Sans_12:
	-$(PYTHON) "data/multilingual/Hans.CMN/Sans_12/pdf_to_json_test_Hans.CMN_Sans_12.py" > "data/multilingual/Hans.CMN/Sans_12/pdf_to_json_test_Hans.CMN_Sans_12.json" 2>&1
Hans.CMN_Sans_16:
	-$(PYTHON) "data/multilingual/Hans.CMN/Sans_16/pdf_to_json_test_Hans.CMN_Sans_16.py" > "data/multilingual/Hans.CMN/Sans_16/pdf_to_json_test_Hans.CMN_Sans_16.json" 2>&1
Hans.CMN_Sans_8:
	-$(PYTHON) "data/multilingual/Hans.CMN/Sans_8/pdf_to_json_test_Hans.CMN_Sans_8.py" > "data/multilingual/Hans.CMN/Sans_8/pdf_to_json_test_Hans.CMN_Sans_8.json" 2>&1
Hans.CMN_Serif_12:
	-$(PYTHON) "data/multilingual/Hans.CMN/Serif_12/pdf_to_json_test_Hans.CMN_Serif_12.py" > "data/multilingual/Hans.CMN/Serif_12/pdf_to_json_test_Hans.CMN_Serif_12.json" 2>&1
Hans.CMN_Serif_16:
	-$(PYTHON) "data/multilingual/Hans.CMN/Serif_16/pdf_to_json_test_Hans.CMN_Serif_16.py" > "data/multilingual/Hans.CMN/Serif_16/pdf_to_json_test_Hans.CMN_Serif_16.json" 2>&1
Hans.CMN_Serif_8:
	-$(PYTHON) "data/multilingual/Hans.CMN/Serif_8/pdf_to_json_test_Hans.CMN_Serif_8.py" > "data/multilingual/Hans.CMN/Serif_8/pdf_to_json_test_Hans.CMN_Serif_8.json" 2>&1
Hans.CMN_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Hans.CMN/Sun-ExtA_12/pdf_to_json_test_Hans.CMN_Sun-ExtA_12.py" > "data/multilingual/Hans.CMN/Sun-ExtA_12/pdf_to_json_test_Hans.CMN_Sun-ExtA_12.json" 2>&1
Hans.CMN_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Hans.CMN/Sun-ExtA_16/pdf_to_json_test_Hans.CMN_Sun-ExtA_16.py" > "data/multilingual/Hans.CMN/Sun-ExtA_16/pdf_to_json_test_Hans.CMN_Sun-ExtA_16.json" 2>&1
Hans.CMN_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Hans.CMN/Sun-ExtA_8/pdf_to_json_test_Hans.CMN_Sun-ExtA_8.py" > "data/multilingual/Hans.CMN/Sun-ExtA_8/pdf_to_json_test_Hans.CMN_Sun-ExtA_8.json" 2>&1


Hans.CMN_all : Hans.CMN_Mono_12 Hans.CMN_Mono_16 Hans.CMN_Mono_8 Hans.CMN_Sans_12 Hans.CMN_Sans_16 Hans.CMN_Sans_8 Hans.CMN_Serif_12 Hans.CMN_Serif_16 Hans.CMN_Serif_8 Hans.CMN_Sun-ExtA_12 Hans.CMN_Sun-ExtA_16 Hans.CMN_Sun-ExtA_8
