PYTHON=python3


Arab.URD_Mono_12:
	-$(PYTHON) data/multilingual/Arab.URD/Mono_12/pdf_to_json_test_Arab.URD_Mono_12.py > data/multilingual/Arab.URD/Mono_12/pdf_to_json_test_Arab.URD_Mono_12.json 2>&1
Arab.URD_Mono_16:
	-$(PYTHON) data/multilingual/Arab.URD/Mono_16/pdf_to_json_test_Arab.URD_Mono_16.py > data/multilingual/Arab.URD/Mono_16/pdf_to_json_test_Arab.URD_Mono_16.json 2>&1
Arab.URD_Mono_8:
	-$(PYTHON) data/multilingual/Arab.URD/Mono_8/pdf_to_json_test_Arab.URD_Mono_8.py > data/multilingual/Arab.URD/Mono_8/pdf_to_json_test_Arab.URD_Mono_8.json 2>&1
Arab.URD_Sans_12:
	-$(PYTHON) data/multilingual/Arab.URD/Sans_12/pdf_to_json_test_Arab.URD_Sans_12.py > data/multilingual/Arab.URD/Sans_12/pdf_to_json_test_Arab.URD_Sans_12.json 2>&1
Arab.URD_Sans_16:
	-$(PYTHON) data/multilingual/Arab.URD/Sans_16/pdf_to_json_test_Arab.URD_Sans_16.py > data/multilingual/Arab.URD/Sans_16/pdf_to_json_test_Arab.URD_Sans_16.json 2>&1
Arab.URD_Sans_8:
	-$(PYTHON) data/multilingual/Arab.URD/Sans_8/pdf_to_json_test_Arab.URD_Sans_8.py > data/multilingual/Arab.URD/Sans_8/pdf_to_json_test_Arab.URD_Sans_8.json 2>&1
Arab.URD_Serif_12:
	-$(PYTHON) data/multilingual/Arab.URD/Serif_12/pdf_to_json_test_Arab.URD_Serif_12.py > data/multilingual/Arab.URD/Serif_12/pdf_to_json_test_Arab.URD_Serif_12.json 2>&1
Arab.URD_Serif_16:
	-$(PYTHON) data/multilingual/Arab.URD/Serif_16/pdf_to_json_test_Arab.URD_Serif_16.py > data/multilingual/Arab.URD/Serif_16/pdf_to_json_test_Arab.URD_Serif_16.json 2>&1
Arab.URD_Serif_8:
	-$(PYTHON) data/multilingual/Arab.URD/Serif_8/pdf_to_json_test_Arab.URD_Serif_8.py > data/multilingual/Arab.URD/Serif_8/pdf_to_json_test_Arab.URD_Serif_8.json 2>&1
Arab.URD_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Arab.URD/Sun-ExtA_12/pdf_to_json_test_Arab.URD_Sun-ExtA_12.py > data/multilingual/Arab.URD/Sun-ExtA_12/pdf_to_json_test_Arab.URD_Sun-ExtA_12.json 2>&1
Arab.URD_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Arab.URD/Sun-ExtA_16/pdf_to_json_test_Arab.URD_Sun-ExtA_16.py > data/multilingual/Arab.URD/Sun-ExtA_16/pdf_to_json_test_Arab.URD_Sun-ExtA_16.json 2>&1
Arab.URD_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Arab.URD/Sun-ExtA_8/pdf_to_json_test_Arab.URD_Sun-ExtA_8.py > data/multilingual/Arab.URD/Sun-ExtA_8/pdf_to_json_test_Arab.URD_Sun-ExtA_8.json 2>&1


Arab.URD_all : Arab.URD_Mono_12 Arab.URD_Mono_16 Arab.URD_Mono_8 Arab.URD_Sans_12 Arab.URD_Sans_16 Arab.URD_Sans_8 Arab.URD_Serif_12 Arab.URD_Serif_16 Arab.URD_Serif_8 Arab.URD_Sun-ExtA_12 Arab.URD_Sun-ExtA_16 Arab.URD_Sun-ExtA_8
