PYTHON=python3


Latn.NYA_Mono_12:
	-$(PYTHON) data/multilingual/Latn.NYA/Mono_12/pdf_to_json_test_Latn.NYA_Mono_12.py > data/multilingual/Latn.NYA/Mono_12/pdf_to_json_test_Latn.NYA_Mono_12.json 2>&1
Latn.NYA_Mono_16:
	-$(PYTHON) data/multilingual/Latn.NYA/Mono_16/pdf_to_json_test_Latn.NYA_Mono_16.py > data/multilingual/Latn.NYA/Mono_16/pdf_to_json_test_Latn.NYA_Mono_16.json 2>&1
Latn.NYA_Mono_8:
	-$(PYTHON) data/multilingual/Latn.NYA/Mono_8/pdf_to_json_test_Latn.NYA_Mono_8.py > data/multilingual/Latn.NYA/Mono_8/pdf_to_json_test_Latn.NYA_Mono_8.json 2>&1
Latn.NYA_Sans_12:
	-$(PYTHON) data/multilingual/Latn.NYA/Sans_12/pdf_to_json_test_Latn.NYA_Sans_12.py > data/multilingual/Latn.NYA/Sans_12/pdf_to_json_test_Latn.NYA_Sans_12.json 2>&1
Latn.NYA_Sans_16:
	-$(PYTHON) data/multilingual/Latn.NYA/Sans_16/pdf_to_json_test_Latn.NYA_Sans_16.py > data/multilingual/Latn.NYA/Sans_16/pdf_to_json_test_Latn.NYA_Sans_16.json 2>&1
Latn.NYA_Sans_8:
	-$(PYTHON) data/multilingual/Latn.NYA/Sans_8/pdf_to_json_test_Latn.NYA_Sans_8.py > data/multilingual/Latn.NYA/Sans_8/pdf_to_json_test_Latn.NYA_Sans_8.json 2>&1
Latn.NYA_Serif_12:
	-$(PYTHON) data/multilingual/Latn.NYA/Serif_12/pdf_to_json_test_Latn.NYA_Serif_12.py > data/multilingual/Latn.NYA/Serif_12/pdf_to_json_test_Latn.NYA_Serif_12.json 2>&1
Latn.NYA_Serif_16:
	-$(PYTHON) data/multilingual/Latn.NYA/Serif_16/pdf_to_json_test_Latn.NYA_Serif_16.py > data/multilingual/Latn.NYA/Serif_16/pdf_to_json_test_Latn.NYA_Serif_16.json 2>&1
Latn.NYA_Serif_8:
	-$(PYTHON) data/multilingual/Latn.NYA/Serif_8/pdf_to_json_test_Latn.NYA_Serif_8.py > data/multilingual/Latn.NYA/Serif_8/pdf_to_json_test_Latn.NYA_Serif_8.json 2>&1
Latn.NYA_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.NYA/Sun-ExtA_12/pdf_to_json_test_Latn.NYA_Sun-ExtA_12.py > data/multilingual/Latn.NYA/Sun-ExtA_12/pdf_to_json_test_Latn.NYA_Sun-ExtA_12.json 2>&1
Latn.NYA_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.NYA/Sun-ExtA_16/pdf_to_json_test_Latn.NYA_Sun-ExtA_16.py > data/multilingual/Latn.NYA/Sun-ExtA_16/pdf_to_json_test_Latn.NYA_Sun-ExtA_16.json 2>&1
Latn.NYA_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.NYA/Sun-ExtA_8/pdf_to_json_test_Latn.NYA_Sun-ExtA_8.py > data/multilingual/Latn.NYA/Sun-ExtA_8/pdf_to_json_test_Latn.NYA_Sun-ExtA_8.json 2>&1


Latn.NYA_all : Latn.NYA_Mono_12 Latn.NYA_Mono_16 Latn.NYA_Mono_8 Latn.NYA_Sans_12 Latn.NYA_Sans_16 Latn.NYA_Sans_8 Latn.NYA_Serif_12 Latn.NYA_Serif_16 Latn.NYA_Serif_8 Latn.NYA_Sun-ExtA_12 Latn.NYA_Sun-ExtA_16 Latn.NYA_Sun-ExtA_8
