PYTHON=python3


Armn.HYE_Mono_12:
	-$(PYTHON) "data/multilingual/Armn.HYE/Mono_12/pdf_to_json_test_Armn.HYE_Mono_12.py" > "data/multilingual/Armn.HYE/Mono_12/pdf_to_json_test_Armn.HYE_Mono_12.json" 2>&1
Armn.HYE_Mono_16:
	-$(PYTHON) "data/multilingual/Armn.HYE/Mono_16/pdf_to_json_test_Armn.HYE_Mono_16.py" > "data/multilingual/Armn.HYE/Mono_16/pdf_to_json_test_Armn.HYE_Mono_16.json" 2>&1
Armn.HYE_Mono_8:
	-$(PYTHON) "data/multilingual/Armn.HYE/Mono_8/pdf_to_json_test_Armn.HYE_Mono_8.py" > "data/multilingual/Armn.HYE/Mono_8/pdf_to_json_test_Armn.HYE_Mono_8.json" 2>&1
Armn.HYE_Sans_12:
	-$(PYTHON) "data/multilingual/Armn.HYE/Sans_12/pdf_to_json_test_Armn.HYE_Sans_12.py" > "data/multilingual/Armn.HYE/Sans_12/pdf_to_json_test_Armn.HYE_Sans_12.json" 2>&1
Armn.HYE_Sans_16:
	-$(PYTHON) "data/multilingual/Armn.HYE/Sans_16/pdf_to_json_test_Armn.HYE_Sans_16.py" > "data/multilingual/Armn.HYE/Sans_16/pdf_to_json_test_Armn.HYE_Sans_16.json" 2>&1
Armn.HYE_Sans_8:
	-$(PYTHON) "data/multilingual/Armn.HYE/Sans_8/pdf_to_json_test_Armn.HYE_Sans_8.py" > "data/multilingual/Armn.HYE/Sans_8/pdf_to_json_test_Armn.HYE_Sans_8.json" 2>&1
Armn.HYE_Serif_12:
	-$(PYTHON) "data/multilingual/Armn.HYE/Serif_12/pdf_to_json_test_Armn.HYE_Serif_12.py" > "data/multilingual/Armn.HYE/Serif_12/pdf_to_json_test_Armn.HYE_Serif_12.json" 2>&1
Armn.HYE_Serif_16:
	-$(PYTHON) "data/multilingual/Armn.HYE/Serif_16/pdf_to_json_test_Armn.HYE_Serif_16.py" > "data/multilingual/Armn.HYE/Serif_16/pdf_to_json_test_Armn.HYE_Serif_16.json" 2>&1
Armn.HYE_Serif_8:
	-$(PYTHON) "data/multilingual/Armn.HYE/Serif_8/pdf_to_json_test_Armn.HYE_Serif_8.py" > "data/multilingual/Armn.HYE/Serif_8/pdf_to_json_test_Armn.HYE_Serif_8.json" 2>&1
Armn.HYE_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Armn.HYE/Sun-ExtA_12/pdf_to_json_test_Armn.HYE_Sun-ExtA_12.py" > "data/multilingual/Armn.HYE/Sun-ExtA_12/pdf_to_json_test_Armn.HYE_Sun-ExtA_12.json" 2>&1
Armn.HYE_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Armn.HYE/Sun-ExtA_16/pdf_to_json_test_Armn.HYE_Sun-ExtA_16.py" > "data/multilingual/Armn.HYE/Sun-ExtA_16/pdf_to_json_test_Armn.HYE_Sun-ExtA_16.json" 2>&1
Armn.HYE_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Armn.HYE/Sun-ExtA_8/pdf_to_json_test_Armn.HYE_Sun-ExtA_8.py" > "data/multilingual/Armn.HYE/Sun-ExtA_8/pdf_to_json_test_Armn.HYE_Sun-ExtA_8.json" 2>&1


Armn.HYE_all : Armn.HYE_Mono_12 Armn.HYE_Mono_16 Armn.HYE_Mono_8 Armn.HYE_Sans_12 Armn.HYE_Sans_16 Armn.HYE_Sans_8 Armn.HYE_Serif_12 Armn.HYE_Serif_16 Armn.HYE_Serif_8 Armn.HYE_Sun-ExtA_12 Armn.HYE_Sun-ExtA_16 Armn.HYE_Sun-ExtA_8
