PYTHON=python3


Latn.HNS_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.HNS/Mono_12/pdf_to_json_test_Latn.HNS_Mono_12.py" > "data/multilingual/Latn.HNS/Mono_12/pdf_to_json_test_Latn.HNS_Mono_12.json" 2>&1
Latn.HNS_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.HNS/Mono_16/pdf_to_json_test_Latn.HNS_Mono_16.py" > "data/multilingual/Latn.HNS/Mono_16/pdf_to_json_test_Latn.HNS_Mono_16.json" 2>&1
Latn.HNS_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.HNS/Mono_8/pdf_to_json_test_Latn.HNS_Mono_8.py" > "data/multilingual/Latn.HNS/Mono_8/pdf_to_json_test_Latn.HNS_Mono_8.json" 2>&1
Latn.HNS_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.HNS/Sans_12/pdf_to_json_test_Latn.HNS_Sans_12.py" > "data/multilingual/Latn.HNS/Sans_12/pdf_to_json_test_Latn.HNS_Sans_12.json" 2>&1
Latn.HNS_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.HNS/Sans_16/pdf_to_json_test_Latn.HNS_Sans_16.py" > "data/multilingual/Latn.HNS/Sans_16/pdf_to_json_test_Latn.HNS_Sans_16.json" 2>&1
Latn.HNS_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.HNS/Sans_8/pdf_to_json_test_Latn.HNS_Sans_8.py" > "data/multilingual/Latn.HNS/Sans_8/pdf_to_json_test_Latn.HNS_Sans_8.json" 2>&1
Latn.HNS_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.HNS/Serif_12/pdf_to_json_test_Latn.HNS_Serif_12.py" > "data/multilingual/Latn.HNS/Serif_12/pdf_to_json_test_Latn.HNS_Serif_12.json" 2>&1
Latn.HNS_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.HNS/Serif_16/pdf_to_json_test_Latn.HNS_Serif_16.py" > "data/multilingual/Latn.HNS/Serif_16/pdf_to_json_test_Latn.HNS_Serif_16.json" 2>&1
Latn.HNS_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.HNS/Serif_8/pdf_to_json_test_Latn.HNS_Serif_8.py" > "data/multilingual/Latn.HNS/Serif_8/pdf_to_json_test_Latn.HNS_Serif_8.json" 2>&1
Latn.HNS_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.HNS/Sun-ExtA_12/pdf_to_json_test_Latn.HNS_Sun-ExtA_12.py" > "data/multilingual/Latn.HNS/Sun-ExtA_12/pdf_to_json_test_Latn.HNS_Sun-ExtA_12.json" 2>&1
Latn.HNS_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.HNS/Sun-ExtA_16/pdf_to_json_test_Latn.HNS_Sun-ExtA_16.py" > "data/multilingual/Latn.HNS/Sun-ExtA_16/pdf_to_json_test_Latn.HNS_Sun-ExtA_16.json" 2>&1
Latn.HNS_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.HNS/Sun-ExtA_8/pdf_to_json_test_Latn.HNS_Sun-ExtA_8.py" > "data/multilingual/Latn.HNS/Sun-ExtA_8/pdf_to_json_test_Latn.HNS_Sun-ExtA_8.json" 2>&1


Latn.HNS_all : Latn.HNS_Mono_12 Latn.HNS_Mono_16 Latn.HNS_Mono_8 Latn.HNS_Sans_12 Latn.HNS_Sans_16 Latn.HNS_Sans_8 Latn.HNS_Serif_12 Latn.HNS_Serif_16 Latn.HNS_Serif_8 Latn.HNS_Sun-ExtA_12 Latn.HNS_Sun-ExtA_16 Latn.HNS_Sun-ExtA_8
