PYTHON=python3


Latn.SRC_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.SRC/Mono_12/pdf_to_json_test_Latn.SRC_Mono_12.py" > "data/multilingual/Latn.SRC/Mono_12/pdf_to_json_test_Latn.SRC_Mono_12.json" 2>&1
Latn.SRC_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.SRC/Mono_16/pdf_to_json_test_Latn.SRC_Mono_16.py" > "data/multilingual/Latn.SRC/Mono_16/pdf_to_json_test_Latn.SRC_Mono_16.json" 2>&1
Latn.SRC_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.SRC/Mono_8/pdf_to_json_test_Latn.SRC_Mono_8.py" > "data/multilingual/Latn.SRC/Mono_8/pdf_to_json_test_Latn.SRC_Mono_8.json" 2>&1
Latn.SRC_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.SRC/Sans_12/pdf_to_json_test_Latn.SRC_Sans_12.py" > "data/multilingual/Latn.SRC/Sans_12/pdf_to_json_test_Latn.SRC_Sans_12.json" 2>&1
Latn.SRC_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.SRC/Sans_16/pdf_to_json_test_Latn.SRC_Sans_16.py" > "data/multilingual/Latn.SRC/Sans_16/pdf_to_json_test_Latn.SRC_Sans_16.json" 2>&1
Latn.SRC_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.SRC/Sans_8/pdf_to_json_test_Latn.SRC_Sans_8.py" > "data/multilingual/Latn.SRC/Sans_8/pdf_to_json_test_Latn.SRC_Sans_8.json" 2>&1
Latn.SRC_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.SRC/Serif_12/pdf_to_json_test_Latn.SRC_Serif_12.py" > "data/multilingual/Latn.SRC/Serif_12/pdf_to_json_test_Latn.SRC_Serif_12.json" 2>&1
Latn.SRC_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.SRC/Serif_16/pdf_to_json_test_Latn.SRC_Serif_16.py" > "data/multilingual/Latn.SRC/Serif_16/pdf_to_json_test_Latn.SRC_Serif_16.json" 2>&1
Latn.SRC_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.SRC/Serif_8/pdf_to_json_test_Latn.SRC_Serif_8.py" > "data/multilingual/Latn.SRC/Serif_8/pdf_to_json_test_Latn.SRC_Serif_8.json" 2>&1
Latn.SRC_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.SRC/Sun-ExtA_12/pdf_to_json_test_Latn.SRC_Sun-ExtA_12.py" > "data/multilingual/Latn.SRC/Sun-ExtA_12/pdf_to_json_test_Latn.SRC_Sun-ExtA_12.json" 2>&1
Latn.SRC_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.SRC/Sun-ExtA_16/pdf_to_json_test_Latn.SRC_Sun-ExtA_16.py" > "data/multilingual/Latn.SRC/Sun-ExtA_16/pdf_to_json_test_Latn.SRC_Sun-ExtA_16.json" 2>&1
Latn.SRC_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.SRC/Sun-ExtA_8/pdf_to_json_test_Latn.SRC_Sun-ExtA_8.py" > "data/multilingual/Latn.SRC/Sun-ExtA_8/pdf_to_json_test_Latn.SRC_Sun-ExtA_8.json" 2>&1


Latn.SRC_all : Latn.SRC_Mono_12 Latn.SRC_Mono_16 Latn.SRC_Mono_8 Latn.SRC_Sans_12 Latn.SRC_Sans_16 Latn.SRC_Sans_8 Latn.SRC_Serif_12 Latn.SRC_Serif_16 Latn.SRC_Serif_8 Latn.SRC_Sun-ExtA_12 Latn.SRC_Sun-ExtA_16 Latn.SRC_Sun-ExtA_8
