PYTHON=python3


Latn.GAZ_Mono_12:
	-$(PYTHON) data/multilingual/Latn.GAZ/Mono_12/pdf_to_json_test_Latn.GAZ_Mono_12.py > data/multilingual/Latn.GAZ/Mono_12/pdf_to_json_test_Latn.GAZ_Mono_12.json 2>&1
Latn.GAZ_Mono_16:
	-$(PYTHON) data/multilingual/Latn.GAZ/Mono_16/pdf_to_json_test_Latn.GAZ_Mono_16.py > data/multilingual/Latn.GAZ/Mono_16/pdf_to_json_test_Latn.GAZ_Mono_16.json 2>&1
Latn.GAZ_Mono_8:
	-$(PYTHON) data/multilingual/Latn.GAZ/Mono_8/pdf_to_json_test_Latn.GAZ_Mono_8.py > data/multilingual/Latn.GAZ/Mono_8/pdf_to_json_test_Latn.GAZ_Mono_8.json 2>&1
Latn.GAZ_Sans_12:
	-$(PYTHON) data/multilingual/Latn.GAZ/Sans_12/pdf_to_json_test_Latn.GAZ_Sans_12.py > data/multilingual/Latn.GAZ/Sans_12/pdf_to_json_test_Latn.GAZ_Sans_12.json 2>&1
Latn.GAZ_Sans_16:
	-$(PYTHON) data/multilingual/Latn.GAZ/Sans_16/pdf_to_json_test_Latn.GAZ_Sans_16.py > data/multilingual/Latn.GAZ/Sans_16/pdf_to_json_test_Latn.GAZ_Sans_16.json 2>&1
Latn.GAZ_Sans_8:
	-$(PYTHON) data/multilingual/Latn.GAZ/Sans_8/pdf_to_json_test_Latn.GAZ_Sans_8.py > data/multilingual/Latn.GAZ/Sans_8/pdf_to_json_test_Latn.GAZ_Sans_8.json 2>&1
Latn.GAZ_Serif_12:
	-$(PYTHON) data/multilingual/Latn.GAZ/Serif_12/pdf_to_json_test_Latn.GAZ_Serif_12.py > data/multilingual/Latn.GAZ/Serif_12/pdf_to_json_test_Latn.GAZ_Serif_12.json 2>&1
Latn.GAZ_Serif_16:
	-$(PYTHON) data/multilingual/Latn.GAZ/Serif_16/pdf_to_json_test_Latn.GAZ_Serif_16.py > data/multilingual/Latn.GAZ/Serif_16/pdf_to_json_test_Latn.GAZ_Serif_16.json 2>&1
Latn.GAZ_Serif_8:
	-$(PYTHON) data/multilingual/Latn.GAZ/Serif_8/pdf_to_json_test_Latn.GAZ_Serif_8.py > data/multilingual/Latn.GAZ/Serif_8/pdf_to_json_test_Latn.GAZ_Serif_8.json 2>&1
Latn.GAZ_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.GAZ/Sun-ExtA_12/pdf_to_json_test_Latn.GAZ_Sun-ExtA_12.py > data/multilingual/Latn.GAZ/Sun-ExtA_12/pdf_to_json_test_Latn.GAZ_Sun-ExtA_12.json 2>&1
Latn.GAZ_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.GAZ/Sun-ExtA_16/pdf_to_json_test_Latn.GAZ_Sun-ExtA_16.py > data/multilingual/Latn.GAZ/Sun-ExtA_16/pdf_to_json_test_Latn.GAZ_Sun-ExtA_16.json 2>&1
Latn.GAZ_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.GAZ/Sun-ExtA_8/pdf_to_json_test_Latn.GAZ_Sun-ExtA_8.py > data/multilingual/Latn.GAZ/Sun-ExtA_8/pdf_to_json_test_Latn.GAZ_Sun-ExtA_8.json 2>&1


Latn.GAZ_all : Latn.GAZ_Mono_12 Latn.GAZ_Mono_16 Latn.GAZ_Mono_8 Latn.GAZ_Sans_12 Latn.GAZ_Sans_16 Latn.GAZ_Sans_8 Latn.GAZ_Serif_12 Latn.GAZ_Serif_16 Latn.GAZ_Serif_8 Latn.GAZ_Sun-ExtA_12 Latn.GAZ_Sun-ExtA_16 Latn.GAZ_Sun-ExtA_8
