PYTHON=python3


Taml.TAM_Mono_12:
	-$(PYTHON) data/multilingual/Taml.TAM/Mono_12/pdf_to_json_test_Taml.TAM_Mono_12.py > data/multilingual/Taml.TAM/Mono_12/pdf_to_json_test_Taml.TAM_Mono_12.json 2>&1
Taml.TAM_Mono_16:
	-$(PYTHON) data/multilingual/Taml.TAM/Mono_16/pdf_to_json_test_Taml.TAM_Mono_16.py > data/multilingual/Taml.TAM/Mono_16/pdf_to_json_test_Taml.TAM_Mono_16.json 2>&1
Taml.TAM_Mono_8:
	-$(PYTHON) data/multilingual/Taml.TAM/Mono_8/pdf_to_json_test_Taml.TAM_Mono_8.py > data/multilingual/Taml.TAM/Mono_8/pdf_to_json_test_Taml.TAM_Mono_8.json 2>&1
Taml.TAM_Sans_12:
	-$(PYTHON) data/multilingual/Taml.TAM/Sans_12/pdf_to_json_test_Taml.TAM_Sans_12.py > data/multilingual/Taml.TAM/Sans_12/pdf_to_json_test_Taml.TAM_Sans_12.json 2>&1
Taml.TAM_Sans_16:
	-$(PYTHON) data/multilingual/Taml.TAM/Sans_16/pdf_to_json_test_Taml.TAM_Sans_16.py > data/multilingual/Taml.TAM/Sans_16/pdf_to_json_test_Taml.TAM_Sans_16.json 2>&1
Taml.TAM_Sans_8:
	-$(PYTHON) data/multilingual/Taml.TAM/Sans_8/pdf_to_json_test_Taml.TAM_Sans_8.py > data/multilingual/Taml.TAM/Sans_8/pdf_to_json_test_Taml.TAM_Sans_8.json 2>&1
Taml.TAM_Serif_12:
	-$(PYTHON) data/multilingual/Taml.TAM/Serif_12/pdf_to_json_test_Taml.TAM_Serif_12.py > data/multilingual/Taml.TAM/Serif_12/pdf_to_json_test_Taml.TAM_Serif_12.json 2>&1
Taml.TAM_Serif_16:
	-$(PYTHON) data/multilingual/Taml.TAM/Serif_16/pdf_to_json_test_Taml.TAM_Serif_16.py > data/multilingual/Taml.TAM/Serif_16/pdf_to_json_test_Taml.TAM_Serif_16.json 2>&1
Taml.TAM_Serif_8:
	-$(PYTHON) data/multilingual/Taml.TAM/Serif_8/pdf_to_json_test_Taml.TAM_Serif_8.py > data/multilingual/Taml.TAM/Serif_8/pdf_to_json_test_Taml.TAM_Serif_8.json 2>&1
Taml.TAM_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Taml.TAM/Sun-ExtA_12/pdf_to_json_test_Taml.TAM_Sun-ExtA_12.py > data/multilingual/Taml.TAM/Sun-ExtA_12/pdf_to_json_test_Taml.TAM_Sun-ExtA_12.json 2>&1
Taml.TAM_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Taml.TAM/Sun-ExtA_16/pdf_to_json_test_Taml.TAM_Sun-ExtA_16.py > data/multilingual/Taml.TAM/Sun-ExtA_16/pdf_to_json_test_Taml.TAM_Sun-ExtA_16.json 2>&1
Taml.TAM_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Taml.TAM/Sun-ExtA_8/pdf_to_json_test_Taml.TAM_Sun-ExtA_8.py > data/multilingual/Taml.TAM/Sun-ExtA_8/pdf_to_json_test_Taml.TAM_Sun-ExtA_8.json 2>&1


Taml.TAM_all : Taml.TAM_Mono_12 Taml.TAM_Mono_16 Taml.TAM_Mono_8 Taml.TAM_Sans_12 Taml.TAM_Sans_16 Taml.TAM_Sans_8 Taml.TAM_Serif_12 Taml.TAM_Serif_16 Taml.TAM_Serif_8 Taml.TAM_Sun-ExtA_12 Taml.TAM_Sun-ExtA_16 Taml.TAM_Sun-ExtA_8
