PYTHON=python3


Latn.KWI_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.KWI/Mono_12/pdf_to_json_test_Latn.KWI_Mono_12.py" > "data/multilingual/Latn.KWI/Mono_12/pdf_to_json_test_Latn.KWI_Mono_12.json" 2>&1
Latn.KWI_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.KWI/Mono_16/pdf_to_json_test_Latn.KWI_Mono_16.py" > "data/multilingual/Latn.KWI/Mono_16/pdf_to_json_test_Latn.KWI_Mono_16.json" 2>&1
Latn.KWI_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.KWI/Mono_8/pdf_to_json_test_Latn.KWI_Mono_8.py" > "data/multilingual/Latn.KWI/Mono_8/pdf_to_json_test_Latn.KWI_Mono_8.json" 2>&1
Latn.KWI_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.KWI/Sans_12/pdf_to_json_test_Latn.KWI_Sans_12.py" > "data/multilingual/Latn.KWI/Sans_12/pdf_to_json_test_Latn.KWI_Sans_12.json" 2>&1
Latn.KWI_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.KWI/Sans_16/pdf_to_json_test_Latn.KWI_Sans_16.py" > "data/multilingual/Latn.KWI/Sans_16/pdf_to_json_test_Latn.KWI_Sans_16.json" 2>&1
Latn.KWI_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.KWI/Sans_8/pdf_to_json_test_Latn.KWI_Sans_8.py" > "data/multilingual/Latn.KWI/Sans_8/pdf_to_json_test_Latn.KWI_Sans_8.json" 2>&1
Latn.KWI_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.KWI/Serif_12/pdf_to_json_test_Latn.KWI_Serif_12.py" > "data/multilingual/Latn.KWI/Serif_12/pdf_to_json_test_Latn.KWI_Serif_12.json" 2>&1
Latn.KWI_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.KWI/Serif_16/pdf_to_json_test_Latn.KWI_Serif_16.py" > "data/multilingual/Latn.KWI/Serif_16/pdf_to_json_test_Latn.KWI_Serif_16.json" 2>&1
Latn.KWI_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.KWI/Serif_8/pdf_to_json_test_Latn.KWI_Serif_8.py" > "data/multilingual/Latn.KWI/Serif_8/pdf_to_json_test_Latn.KWI_Serif_8.json" 2>&1
Latn.KWI_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.KWI/Sun-ExtA_12/pdf_to_json_test_Latn.KWI_Sun-ExtA_12.py" > "data/multilingual/Latn.KWI/Sun-ExtA_12/pdf_to_json_test_Latn.KWI_Sun-ExtA_12.json" 2>&1
Latn.KWI_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.KWI/Sun-ExtA_16/pdf_to_json_test_Latn.KWI_Sun-ExtA_16.py" > "data/multilingual/Latn.KWI/Sun-ExtA_16/pdf_to_json_test_Latn.KWI_Sun-ExtA_16.json" 2>&1
Latn.KWI_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.KWI/Sun-ExtA_8/pdf_to_json_test_Latn.KWI_Sun-ExtA_8.py" > "data/multilingual/Latn.KWI/Sun-ExtA_8/pdf_to_json_test_Latn.KWI_Sun-ExtA_8.json" 2>&1


Latn.KWI_all : Latn.KWI_Mono_12 Latn.KWI_Mono_16 Latn.KWI_Mono_8 Latn.KWI_Sans_12 Latn.KWI_Sans_16 Latn.KWI_Sans_8 Latn.KWI_Serif_12 Latn.KWI_Serif_16 Latn.KWI_Serif_8 Latn.KWI_Sun-ExtA_12 Latn.KWI_Sun-ExtA_16 Latn.KWI_Sun-ExtA_8
