PYTHON=python3


Thaa.DIV_Mono_12:
	-$(PYTHON) "data/multilingual/Thaa.DIV/Mono_12/pdf_to_json_test_Thaa.DIV_Mono_12.py" > "data/multilingual/Thaa.DIV/Mono_12/pdf_to_json_test_Thaa.DIV_Mono_12.json" 2>&1
Thaa.DIV_Mono_16:
	-$(PYTHON) "data/multilingual/Thaa.DIV/Mono_16/pdf_to_json_test_Thaa.DIV_Mono_16.py" > "data/multilingual/Thaa.DIV/Mono_16/pdf_to_json_test_Thaa.DIV_Mono_16.json" 2>&1
Thaa.DIV_Mono_8:
	-$(PYTHON) "data/multilingual/Thaa.DIV/Mono_8/pdf_to_json_test_Thaa.DIV_Mono_8.py" > "data/multilingual/Thaa.DIV/Mono_8/pdf_to_json_test_Thaa.DIV_Mono_8.json" 2>&1
Thaa.DIV_Sans_12:
	-$(PYTHON) "data/multilingual/Thaa.DIV/Sans_12/pdf_to_json_test_Thaa.DIV_Sans_12.py" > "data/multilingual/Thaa.DIV/Sans_12/pdf_to_json_test_Thaa.DIV_Sans_12.json" 2>&1
Thaa.DIV_Sans_16:
	-$(PYTHON) "data/multilingual/Thaa.DIV/Sans_16/pdf_to_json_test_Thaa.DIV_Sans_16.py" > "data/multilingual/Thaa.DIV/Sans_16/pdf_to_json_test_Thaa.DIV_Sans_16.json" 2>&1
Thaa.DIV_Sans_8:
	-$(PYTHON) "data/multilingual/Thaa.DIV/Sans_8/pdf_to_json_test_Thaa.DIV_Sans_8.py" > "data/multilingual/Thaa.DIV/Sans_8/pdf_to_json_test_Thaa.DIV_Sans_8.json" 2>&1
Thaa.DIV_Serif_12:
	-$(PYTHON) "data/multilingual/Thaa.DIV/Serif_12/pdf_to_json_test_Thaa.DIV_Serif_12.py" > "data/multilingual/Thaa.DIV/Serif_12/pdf_to_json_test_Thaa.DIV_Serif_12.json" 2>&1
Thaa.DIV_Serif_16:
	-$(PYTHON) "data/multilingual/Thaa.DIV/Serif_16/pdf_to_json_test_Thaa.DIV_Serif_16.py" > "data/multilingual/Thaa.DIV/Serif_16/pdf_to_json_test_Thaa.DIV_Serif_16.json" 2>&1
Thaa.DIV_Serif_8:
	-$(PYTHON) "data/multilingual/Thaa.DIV/Serif_8/pdf_to_json_test_Thaa.DIV_Serif_8.py" > "data/multilingual/Thaa.DIV/Serif_8/pdf_to_json_test_Thaa.DIV_Serif_8.json" 2>&1
Thaa.DIV_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Thaa.DIV/Sun-ExtA_12/pdf_to_json_test_Thaa.DIV_Sun-ExtA_12.py" > "data/multilingual/Thaa.DIV/Sun-ExtA_12/pdf_to_json_test_Thaa.DIV_Sun-ExtA_12.json" 2>&1
Thaa.DIV_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Thaa.DIV/Sun-ExtA_16/pdf_to_json_test_Thaa.DIV_Sun-ExtA_16.py" > "data/multilingual/Thaa.DIV/Sun-ExtA_16/pdf_to_json_test_Thaa.DIV_Sun-ExtA_16.json" 2>&1
Thaa.DIV_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Thaa.DIV/Sun-ExtA_8/pdf_to_json_test_Thaa.DIV_Sun-ExtA_8.py" > "data/multilingual/Thaa.DIV/Sun-ExtA_8/pdf_to_json_test_Thaa.DIV_Sun-ExtA_8.json" 2>&1


Thaa.DIV_all : Thaa.DIV_Mono_12 Thaa.DIV_Mono_16 Thaa.DIV_Mono_8 Thaa.DIV_Sans_12 Thaa.DIV_Sans_16 Thaa.DIV_Sans_8 Thaa.DIV_Serif_12 Thaa.DIV_Serif_16 Thaa.DIV_Serif_8 Thaa.DIV_Sun-ExtA_12 Thaa.DIV_Sun-ExtA_16 Thaa.DIV_Sun-ExtA_8
