PYTHON=python3


Latn.HUN_Mono_12:
	-$(PYTHON) data/multilingual/Latn.HUN/Mono_12/pdf_to_json_test_Latn.HUN_Mono_12.py > data/multilingual/Latn.HUN/Mono_12/pdf_to_json_test_Latn.HUN_Mono_12.json 2>&1
Latn.HUN_Mono_16:
	-$(PYTHON) data/multilingual/Latn.HUN/Mono_16/pdf_to_json_test_Latn.HUN_Mono_16.py > data/multilingual/Latn.HUN/Mono_16/pdf_to_json_test_Latn.HUN_Mono_16.json 2>&1
Latn.HUN_Mono_8:
	-$(PYTHON) data/multilingual/Latn.HUN/Mono_8/pdf_to_json_test_Latn.HUN_Mono_8.py > data/multilingual/Latn.HUN/Mono_8/pdf_to_json_test_Latn.HUN_Mono_8.json 2>&1
Latn.HUN_Sans_12:
	-$(PYTHON) data/multilingual/Latn.HUN/Sans_12/pdf_to_json_test_Latn.HUN_Sans_12.py > data/multilingual/Latn.HUN/Sans_12/pdf_to_json_test_Latn.HUN_Sans_12.json 2>&1
Latn.HUN_Sans_16:
	-$(PYTHON) data/multilingual/Latn.HUN/Sans_16/pdf_to_json_test_Latn.HUN_Sans_16.py > data/multilingual/Latn.HUN/Sans_16/pdf_to_json_test_Latn.HUN_Sans_16.json 2>&1
Latn.HUN_Sans_8:
	-$(PYTHON) data/multilingual/Latn.HUN/Sans_8/pdf_to_json_test_Latn.HUN_Sans_8.py > data/multilingual/Latn.HUN/Sans_8/pdf_to_json_test_Latn.HUN_Sans_8.json 2>&1
Latn.HUN_Serif_12:
	-$(PYTHON) data/multilingual/Latn.HUN/Serif_12/pdf_to_json_test_Latn.HUN_Serif_12.py > data/multilingual/Latn.HUN/Serif_12/pdf_to_json_test_Latn.HUN_Serif_12.json 2>&1
Latn.HUN_Serif_16:
	-$(PYTHON) data/multilingual/Latn.HUN/Serif_16/pdf_to_json_test_Latn.HUN_Serif_16.py > data/multilingual/Latn.HUN/Serif_16/pdf_to_json_test_Latn.HUN_Serif_16.json 2>&1
Latn.HUN_Serif_8:
	-$(PYTHON) data/multilingual/Latn.HUN/Serif_8/pdf_to_json_test_Latn.HUN_Serif_8.py > data/multilingual/Latn.HUN/Serif_8/pdf_to_json_test_Latn.HUN_Serif_8.json 2>&1
Latn.HUN_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.HUN/Sun-ExtA_12/pdf_to_json_test_Latn.HUN_Sun-ExtA_12.py > data/multilingual/Latn.HUN/Sun-ExtA_12/pdf_to_json_test_Latn.HUN_Sun-ExtA_12.json 2>&1
Latn.HUN_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.HUN/Sun-ExtA_16/pdf_to_json_test_Latn.HUN_Sun-ExtA_16.py > data/multilingual/Latn.HUN/Sun-ExtA_16/pdf_to_json_test_Latn.HUN_Sun-ExtA_16.json 2>&1
Latn.HUN_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.HUN/Sun-ExtA_8/pdf_to_json_test_Latn.HUN_Sun-ExtA_8.py > data/multilingual/Latn.HUN/Sun-ExtA_8/pdf_to_json_test_Latn.HUN_Sun-ExtA_8.json 2>&1


Latn.HUN_all : Latn.HUN_Mono_12 Latn.HUN_Mono_16 Latn.HUN_Mono_8 Latn.HUN_Sans_12 Latn.HUN_Sans_16 Latn.HUN_Sans_8 Latn.HUN_Serif_12 Latn.HUN_Serif_16 Latn.HUN_Serif_8 Latn.HUN_Sun-ExtA_12 Latn.HUN_Sun-ExtA_16 Latn.HUN_Sun-ExtA_8
