PYTHON=python3


Latn.AJG_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.AJG/Mono_12/pdf_to_json_test_Latn.AJG_Mono_12.py" > "data/multilingual/Latn.AJG/Mono_12/pdf_to_json_test_Latn.AJG_Mono_12.json" 2>&1
Latn.AJG_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.AJG/Mono_16/pdf_to_json_test_Latn.AJG_Mono_16.py" > "data/multilingual/Latn.AJG/Mono_16/pdf_to_json_test_Latn.AJG_Mono_16.json" 2>&1
Latn.AJG_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.AJG/Mono_8/pdf_to_json_test_Latn.AJG_Mono_8.py" > "data/multilingual/Latn.AJG/Mono_8/pdf_to_json_test_Latn.AJG_Mono_8.json" 2>&1
Latn.AJG_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.AJG/Sans_12/pdf_to_json_test_Latn.AJG_Sans_12.py" > "data/multilingual/Latn.AJG/Sans_12/pdf_to_json_test_Latn.AJG_Sans_12.json" 2>&1
Latn.AJG_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.AJG/Sans_16/pdf_to_json_test_Latn.AJG_Sans_16.py" > "data/multilingual/Latn.AJG/Sans_16/pdf_to_json_test_Latn.AJG_Sans_16.json" 2>&1
Latn.AJG_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.AJG/Sans_8/pdf_to_json_test_Latn.AJG_Sans_8.py" > "data/multilingual/Latn.AJG/Sans_8/pdf_to_json_test_Latn.AJG_Sans_8.json" 2>&1
Latn.AJG_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.AJG/Serif_12/pdf_to_json_test_Latn.AJG_Serif_12.py" > "data/multilingual/Latn.AJG/Serif_12/pdf_to_json_test_Latn.AJG_Serif_12.json" 2>&1
Latn.AJG_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.AJG/Serif_16/pdf_to_json_test_Latn.AJG_Serif_16.py" > "data/multilingual/Latn.AJG/Serif_16/pdf_to_json_test_Latn.AJG_Serif_16.json" 2>&1
Latn.AJG_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.AJG/Serif_8/pdf_to_json_test_Latn.AJG_Serif_8.py" > "data/multilingual/Latn.AJG/Serif_8/pdf_to_json_test_Latn.AJG_Serif_8.json" 2>&1
Latn.AJG_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.AJG/Sun-ExtA_12/pdf_to_json_test_Latn.AJG_Sun-ExtA_12.py" > "data/multilingual/Latn.AJG/Sun-ExtA_12/pdf_to_json_test_Latn.AJG_Sun-ExtA_12.json" 2>&1
Latn.AJG_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.AJG/Sun-ExtA_16/pdf_to_json_test_Latn.AJG_Sun-ExtA_16.py" > "data/multilingual/Latn.AJG/Sun-ExtA_16/pdf_to_json_test_Latn.AJG_Sun-ExtA_16.json" 2>&1
Latn.AJG_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.AJG/Sun-ExtA_8/pdf_to_json_test_Latn.AJG_Sun-ExtA_8.py" > "data/multilingual/Latn.AJG/Sun-ExtA_8/pdf_to_json_test_Latn.AJG_Sun-ExtA_8.json" 2>&1


Latn.AJG_all : Latn.AJG_Mono_12 Latn.AJG_Mono_16 Latn.AJG_Mono_8 Latn.AJG_Sans_12 Latn.AJG_Sans_16 Latn.AJG_Sans_8 Latn.AJG_Serif_12 Latn.AJG_Serif_16 Latn.AJG_Serif_8 Latn.AJG_Sun-ExtA_12 Latn.AJG_Sun-ExtA_16 Latn.AJG_Sun-ExtA_8
