PYTHON=python3


Cyrl.BUL_Mono_12:
	-$(PYTHON) "data/multilingual/Cyrl.BUL/Mono_12/pdf_to_json_test_Cyrl.BUL_Mono_12.py" > "data/multilingual/Cyrl.BUL/Mono_12/pdf_to_json_test_Cyrl.BUL_Mono_12.json" 2>&1
Cyrl.BUL_Mono_16:
	-$(PYTHON) "data/multilingual/Cyrl.BUL/Mono_16/pdf_to_json_test_Cyrl.BUL_Mono_16.py" > "data/multilingual/Cyrl.BUL/Mono_16/pdf_to_json_test_Cyrl.BUL_Mono_16.json" 2>&1
Cyrl.BUL_Mono_8:
	-$(PYTHON) "data/multilingual/Cyrl.BUL/Mono_8/pdf_to_json_test_Cyrl.BUL_Mono_8.py" > "data/multilingual/Cyrl.BUL/Mono_8/pdf_to_json_test_Cyrl.BUL_Mono_8.json" 2>&1
Cyrl.BUL_Sans_12:
	-$(PYTHON) "data/multilingual/Cyrl.BUL/Sans_12/pdf_to_json_test_Cyrl.BUL_Sans_12.py" > "data/multilingual/Cyrl.BUL/Sans_12/pdf_to_json_test_Cyrl.BUL_Sans_12.json" 2>&1
Cyrl.BUL_Sans_16:
	-$(PYTHON) "data/multilingual/Cyrl.BUL/Sans_16/pdf_to_json_test_Cyrl.BUL_Sans_16.py" > "data/multilingual/Cyrl.BUL/Sans_16/pdf_to_json_test_Cyrl.BUL_Sans_16.json" 2>&1
Cyrl.BUL_Sans_8:
	-$(PYTHON) "data/multilingual/Cyrl.BUL/Sans_8/pdf_to_json_test_Cyrl.BUL_Sans_8.py" > "data/multilingual/Cyrl.BUL/Sans_8/pdf_to_json_test_Cyrl.BUL_Sans_8.json" 2>&1
Cyrl.BUL_Serif_12:
	-$(PYTHON) "data/multilingual/Cyrl.BUL/Serif_12/pdf_to_json_test_Cyrl.BUL_Serif_12.py" > "data/multilingual/Cyrl.BUL/Serif_12/pdf_to_json_test_Cyrl.BUL_Serif_12.json" 2>&1
Cyrl.BUL_Serif_16:
	-$(PYTHON) "data/multilingual/Cyrl.BUL/Serif_16/pdf_to_json_test_Cyrl.BUL_Serif_16.py" > "data/multilingual/Cyrl.BUL/Serif_16/pdf_to_json_test_Cyrl.BUL_Serif_16.json" 2>&1
Cyrl.BUL_Serif_8:
	-$(PYTHON) "data/multilingual/Cyrl.BUL/Serif_8/pdf_to_json_test_Cyrl.BUL_Serif_8.py" > "data/multilingual/Cyrl.BUL/Serif_8/pdf_to_json_test_Cyrl.BUL_Serif_8.json" 2>&1
Cyrl.BUL_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Cyrl.BUL/Sun-ExtA_12/pdf_to_json_test_Cyrl.BUL_Sun-ExtA_12.py" > "data/multilingual/Cyrl.BUL/Sun-ExtA_12/pdf_to_json_test_Cyrl.BUL_Sun-ExtA_12.json" 2>&1
Cyrl.BUL_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Cyrl.BUL/Sun-ExtA_16/pdf_to_json_test_Cyrl.BUL_Sun-ExtA_16.py" > "data/multilingual/Cyrl.BUL/Sun-ExtA_16/pdf_to_json_test_Cyrl.BUL_Sun-ExtA_16.json" 2>&1
Cyrl.BUL_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Cyrl.BUL/Sun-ExtA_8/pdf_to_json_test_Cyrl.BUL_Sun-ExtA_8.py" > "data/multilingual/Cyrl.BUL/Sun-ExtA_8/pdf_to_json_test_Cyrl.BUL_Sun-ExtA_8.json" 2>&1


Cyrl.BUL_all : Cyrl.BUL_Mono_12 Cyrl.BUL_Mono_16 Cyrl.BUL_Mono_8 Cyrl.BUL_Sans_12 Cyrl.BUL_Sans_16 Cyrl.BUL_Sans_8 Cyrl.BUL_Serif_12 Cyrl.BUL_Serif_16 Cyrl.BUL_Serif_8 Cyrl.BUL_Sun-ExtA_12 Cyrl.BUL_Sun-ExtA_16 Cyrl.BUL_Sun-ExtA_8
