PYTHON=python3


Latn.QVC_Mono_12:
	-$(PYTHON) data/multilingual/Latn.QVC/Mono_12/pdf_to_json_test_Latn.QVC_Mono_12.py > data/multilingual/Latn.QVC/Mono_12/pdf_to_json_test_Latn.QVC_Mono_12.json 2>&1
Latn.QVC_Mono_16:
	-$(PYTHON) data/multilingual/Latn.QVC/Mono_16/pdf_to_json_test_Latn.QVC_Mono_16.py > data/multilingual/Latn.QVC/Mono_16/pdf_to_json_test_Latn.QVC_Mono_16.json 2>&1
Latn.QVC_Mono_8:
	-$(PYTHON) data/multilingual/Latn.QVC/Mono_8/pdf_to_json_test_Latn.QVC_Mono_8.py > data/multilingual/Latn.QVC/Mono_8/pdf_to_json_test_Latn.QVC_Mono_8.json 2>&1
Latn.QVC_Sans_12:
	-$(PYTHON) data/multilingual/Latn.QVC/Sans_12/pdf_to_json_test_Latn.QVC_Sans_12.py > data/multilingual/Latn.QVC/Sans_12/pdf_to_json_test_Latn.QVC_Sans_12.json 2>&1
Latn.QVC_Sans_16:
	-$(PYTHON) data/multilingual/Latn.QVC/Sans_16/pdf_to_json_test_Latn.QVC_Sans_16.py > data/multilingual/Latn.QVC/Sans_16/pdf_to_json_test_Latn.QVC_Sans_16.json 2>&1
Latn.QVC_Sans_8:
	-$(PYTHON) data/multilingual/Latn.QVC/Sans_8/pdf_to_json_test_Latn.QVC_Sans_8.py > data/multilingual/Latn.QVC/Sans_8/pdf_to_json_test_Latn.QVC_Sans_8.json 2>&1
Latn.QVC_Serif_12:
	-$(PYTHON) data/multilingual/Latn.QVC/Serif_12/pdf_to_json_test_Latn.QVC_Serif_12.py > data/multilingual/Latn.QVC/Serif_12/pdf_to_json_test_Latn.QVC_Serif_12.json 2>&1
Latn.QVC_Serif_16:
	-$(PYTHON) data/multilingual/Latn.QVC/Serif_16/pdf_to_json_test_Latn.QVC_Serif_16.py > data/multilingual/Latn.QVC/Serif_16/pdf_to_json_test_Latn.QVC_Serif_16.json 2>&1
Latn.QVC_Serif_8:
	-$(PYTHON) data/multilingual/Latn.QVC/Serif_8/pdf_to_json_test_Latn.QVC_Serif_8.py > data/multilingual/Latn.QVC/Serif_8/pdf_to_json_test_Latn.QVC_Serif_8.json 2>&1
Latn.QVC_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.QVC/Sun-ExtA_12/pdf_to_json_test_Latn.QVC_Sun-ExtA_12.py > data/multilingual/Latn.QVC/Sun-ExtA_12/pdf_to_json_test_Latn.QVC_Sun-ExtA_12.json 2>&1
Latn.QVC_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.QVC/Sun-ExtA_16/pdf_to_json_test_Latn.QVC_Sun-ExtA_16.py > data/multilingual/Latn.QVC/Sun-ExtA_16/pdf_to_json_test_Latn.QVC_Sun-ExtA_16.json 2>&1
Latn.QVC_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.QVC/Sun-ExtA_8/pdf_to_json_test_Latn.QVC_Sun-ExtA_8.py > data/multilingual/Latn.QVC/Sun-ExtA_8/pdf_to_json_test_Latn.QVC_Sun-ExtA_8.json 2>&1


Latn.QVC_all : Latn.QVC_Mono_12 Latn.QVC_Mono_16 Latn.QVC_Mono_8 Latn.QVC_Sans_12 Latn.QVC_Sans_16 Latn.QVC_Sans_8 Latn.QVC_Serif_12 Latn.QVC_Serif_16 Latn.QVC_Serif_8 Latn.QVC_Sun-ExtA_12 Latn.QVC_Sun-ExtA_16 Latn.QVC_Sun-ExtA_8
