PYTHON=python3


Latn.TET_Mono_12:
	-$(PYTHON) data/multilingual/Latn.TET/Mono_12/pdf_to_json_test_Latn.TET_Mono_12.py > data/multilingual/Latn.TET/Mono_12/pdf_to_json_test_Latn.TET_Mono_12.json 2>&1
Latn.TET_Mono_16:
	-$(PYTHON) data/multilingual/Latn.TET/Mono_16/pdf_to_json_test_Latn.TET_Mono_16.py > data/multilingual/Latn.TET/Mono_16/pdf_to_json_test_Latn.TET_Mono_16.json 2>&1
Latn.TET_Mono_8:
	-$(PYTHON) data/multilingual/Latn.TET/Mono_8/pdf_to_json_test_Latn.TET_Mono_8.py > data/multilingual/Latn.TET/Mono_8/pdf_to_json_test_Latn.TET_Mono_8.json 2>&1
Latn.TET_Sans_12:
	-$(PYTHON) data/multilingual/Latn.TET/Sans_12/pdf_to_json_test_Latn.TET_Sans_12.py > data/multilingual/Latn.TET/Sans_12/pdf_to_json_test_Latn.TET_Sans_12.json 2>&1
Latn.TET_Sans_16:
	-$(PYTHON) data/multilingual/Latn.TET/Sans_16/pdf_to_json_test_Latn.TET_Sans_16.py > data/multilingual/Latn.TET/Sans_16/pdf_to_json_test_Latn.TET_Sans_16.json 2>&1
Latn.TET_Sans_8:
	-$(PYTHON) data/multilingual/Latn.TET/Sans_8/pdf_to_json_test_Latn.TET_Sans_8.py > data/multilingual/Latn.TET/Sans_8/pdf_to_json_test_Latn.TET_Sans_8.json 2>&1
Latn.TET_Serif_12:
	-$(PYTHON) data/multilingual/Latn.TET/Serif_12/pdf_to_json_test_Latn.TET_Serif_12.py > data/multilingual/Latn.TET/Serif_12/pdf_to_json_test_Latn.TET_Serif_12.json 2>&1
Latn.TET_Serif_16:
	-$(PYTHON) data/multilingual/Latn.TET/Serif_16/pdf_to_json_test_Latn.TET_Serif_16.py > data/multilingual/Latn.TET/Serif_16/pdf_to_json_test_Latn.TET_Serif_16.json 2>&1
Latn.TET_Serif_8:
	-$(PYTHON) data/multilingual/Latn.TET/Serif_8/pdf_to_json_test_Latn.TET_Serif_8.py > data/multilingual/Latn.TET/Serif_8/pdf_to_json_test_Latn.TET_Serif_8.json 2>&1
Latn.TET_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.TET/Sun-ExtA_12/pdf_to_json_test_Latn.TET_Sun-ExtA_12.py > data/multilingual/Latn.TET/Sun-ExtA_12/pdf_to_json_test_Latn.TET_Sun-ExtA_12.json 2>&1
Latn.TET_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.TET/Sun-ExtA_16/pdf_to_json_test_Latn.TET_Sun-ExtA_16.py > data/multilingual/Latn.TET/Sun-ExtA_16/pdf_to_json_test_Latn.TET_Sun-ExtA_16.json 2>&1
Latn.TET_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.TET/Sun-ExtA_8/pdf_to_json_test_Latn.TET_Sun-ExtA_8.py > data/multilingual/Latn.TET/Sun-ExtA_8/pdf_to_json_test_Latn.TET_Sun-ExtA_8.json 2>&1


Latn.TET_all : Latn.TET_Mono_12 Latn.TET_Mono_16 Latn.TET_Mono_8 Latn.TET_Sans_12 Latn.TET_Sans_16 Latn.TET_Sans_8 Latn.TET_Serif_12 Latn.TET_Serif_16 Latn.TET_Serif_8 Latn.TET_Sun-ExtA_12 Latn.TET_Sun-ExtA_16 Latn.TET_Sun-ExtA_8
