PYTHON=python3


Latn.LOT_Mono_12:
	-$(PYTHON) data/multilingual/Latn.LOT/Mono_12/pdf_to_json_test_Latn.LOT_Mono_12.py > data/multilingual/Latn.LOT/Mono_12/pdf_to_json_test_Latn.LOT_Mono_12.json 2>&1
Latn.LOT_Mono_16:
	-$(PYTHON) data/multilingual/Latn.LOT/Mono_16/pdf_to_json_test_Latn.LOT_Mono_16.py > data/multilingual/Latn.LOT/Mono_16/pdf_to_json_test_Latn.LOT_Mono_16.json 2>&1
Latn.LOT_Mono_8:
	-$(PYTHON) data/multilingual/Latn.LOT/Mono_8/pdf_to_json_test_Latn.LOT_Mono_8.py > data/multilingual/Latn.LOT/Mono_8/pdf_to_json_test_Latn.LOT_Mono_8.json 2>&1
Latn.LOT_Sans_12:
	-$(PYTHON) data/multilingual/Latn.LOT/Sans_12/pdf_to_json_test_Latn.LOT_Sans_12.py > data/multilingual/Latn.LOT/Sans_12/pdf_to_json_test_Latn.LOT_Sans_12.json 2>&1
Latn.LOT_Sans_16:
	-$(PYTHON) data/multilingual/Latn.LOT/Sans_16/pdf_to_json_test_Latn.LOT_Sans_16.py > data/multilingual/Latn.LOT/Sans_16/pdf_to_json_test_Latn.LOT_Sans_16.json 2>&1
Latn.LOT_Sans_8:
	-$(PYTHON) data/multilingual/Latn.LOT/Sans_8/pdf_to_json_test_Latn.LOT_Sans_8.py > data/multilingual/Latn.LOT/Sans_8/pdf_to_json_test_Latn.LOT_Sans_8.json 2>&1
Latn.LOT_Serif_12:
	-$(PYTHON) data/multilingual/Latn.LOT/Serif_12/pdf_to_json_test_Latn.LOT_Serif_12.py > data/multilingual/Latn.LOT/Serif_12/pdf_to_json_test_Latn.LOT_Serif_12.json 2>&1
Latn.LOT_Serif_16:
	-$(PYTHON) data/multilingual/Latn.LOT/Serif_16/pdf_to_json_test_Latn.LOT_Serif_16.py > data/multilingual/Latn.LOT/Serif_16/pdf_to_json_test_Latn.LOT_Serif_16.json 2>&1
Latn.LOT_Serif_8:
	-$(PYTHON) data/multilingual/Latn.LOT/Serif_8/pdf_to_json_test_Latn.LOT_Serif_8.py > data/multilingual/Latn.LOT/Serif_8/pdf_to_json_test_Latn.LOT_Serif_8.json 2>&1
Latn.LOT_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.LOT/Sun-ExtA_12/pdf_to_json_test_Latn.LOT_Sun-ExtA_12.py > data/multilingual/Latn.LOT/Sun-ExtA_12/pdf_to_json_test_Latn.LOT_Sun-ExtA_12.json 2>&1
Latn.LOT_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.LOT/Sun-ExtA_16/pdf_to_json_test_Latn.LOT_Sun-ExtA_16.py > data/multilingual/Latn.LOT/Sun-ExtA_16/pdf_to_json_test_Latn.LOT_Sun-ExtA_16.json 2>&1
Latn.LOT_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.LOT/Sun-ExtA_8/pdf_to_json_test_Latn.LOT_Sun-ExtA_8.py > data/multilingual/Latn.LOT/Sun-ExtA_8/pdf_to_json_test_Latn.LOT_Sun-ExtA_8.json 2>&1


Latn.LOT_all : Latn.LOT_Mono_12 Latn.LOT_Mono_16 Latn.LOT_Mono_8 Latn.LOT_Sans_12 Latn.LOT_Sans_16 Latn.LOT_Sans_8 Latn.LOT_Serif_12 Latn.LOT_Serif_16 Latn.LOT_Serif_8 Latn.LOT_Sun-ExtA_12 Latn.LOT_Sun-ExtA_16 Latn.LOT_Sun-ExtA_8
