PYTHON=python3


Latn.BUC_Mono_12:
	-$(PYTHON) data/multilingual/Latn.BUC/Mono_12/pdf_to_json_test_Latn.BUC_Mono_12.py > data/multilingual/Latn.BUC/Mono_12/pdf_to_json_test_Latn.BUC_Mono_12.json 2>&1
Latn.BUC_Mono_16:
	-$(PYTHON) data/multilingual/Latn.BUC/Mono_16/pdf_to_json_test_Latn.BUC_Mono_16.py > data/multilingual/Latn.BUC/Mono_16/pdf_to_json_test_Latn.BUC_Mono_16.json 2>&1
Latn.BUC_Mono_8:
	-$(PYTHON) data/multilingual/Latn.BUC/Mono_8/pdf_to_json_test_Latn.BUC_Mono_8.py > data/multilingual/Latn.BUC/Mono_8/pdf_to_json_test_Latn.BUC_Mono_8.json 2>&1
Latn.BUC_Sans_12:
	-$(PYTHON) data/multilingual/Latn.BUC/Sans_12/pdf_to_json_test_Latn.BUC_Sans_12.py > data/multilingual/Latn.BUC/Sans_12/pdf_to_json_test_Latn.BUC_Sans_12.json 2>&1
Latn.BUC_Sans_16:
	-$(PYTHON) data/multilingual/Latn.BUC/Sans_16/pdf_to_json_test_Latn.BUC_Sans_16.py > data/multilingual/Latn.BUC/Sans_16/pdf_to_json_test_Latn.BUC_Sans_16.json 2>&1
Latn.BUC_Sans_8:
	-$(PYTHON) data/multilingual/Latn.BUC/Sans_8/pdf_to_json_test_Latn.BUC_Sans_8.py > data/multilingual/Latn.BUC/Sans_8/pdf_to_json_test_Latn.BUC_Sans_8.json 2>&1
Latn.BUC_Serif_12:
	-$(PYTHON) data/multilingual/Latn.BUC/Serif_12/pdf_to_json_test_Latn.BUC_Serif_12.py > data/multilingual/Latn.BUC/Serif_12/pdf_to_json_test_Latn.BUC_Serif_12.json 2>&1
Latn.BUC_Serif_16:
	-$(PYTHON) data/multilingual/Latn.BUC/Serif_16/pdf_to_json_test_Latn.BUC_Serif_16.py > data/multilingual/Latn.BUC/Serif_16/pdf_to_json_test_Latn.BUC_Serif_16.json 2>&1
Latn.BUC_Serif_8:
	-$(PYTHON) data/multilingual/Latn.BUC/Serif_8/pdf_to_json_test_Latn.BUC_Serif_8.py > data/multilingual/Latn.BUC/Serif_8/pdf_to_json_test_Latn.BUC_Serif_8.json 2>&1
Latn.BUC_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.BUC/Sun-ExtA_12/pdf_to_json_test_Latn.BUC_Sun-ExtA_12.py > data/multilingual/Latn.BUC/Sun-ExtA_12/pdf_to_json_test_Latn.BUC_Sun-ExtA_12.json 2>&1
Latn.BUC_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.BUC/Sun-ExtA_16/pdf_to_json_test_Latn.BUC_Sun-ExtA_16.py > data/multilingual/Latn.BUC/Sun-ExtA_16/pdf_to_json_test_Latn.BUC_Sun-ExtA_16.json 2>&1
Latn.BUC_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.BUC/Sun-ExtA_8/pdf_to_json_test_Latn.BUC_Sun-ExtA_8.py > data/multilingual/Latn.BUC/Sun-ExtA_8/pdf_to_json_test_Latn.BUC_Sun-ExtA_8.json 2>&1


Latn.BUC_all : Latn.BUC_Mono_12 Latn.BUC_Mono_16 Latn.BUC_Mono_8 Latn.BUC_Sans_12 Latn.BUC_Sans_16 Latn.BUC_Sans_8 Latn.BUC_Serif_12 Latn.BUC_Serif_16 Latn.BUC_Serif_8 Latn.BUC_Sun-ExtA_12 Latn.BUC_Sun-ExtA_16 Latn.BUC_Sun-ExtA_8
