PYTHON=python3


Adlm.FUF_Ebrima_12:
	-$(PYTHON) "data/multilingual/Adlm.FUF/Ebrima_12/pdf_to_json_test_Adlm.FUF_Ebrima_12.py" > "data/multilingual/Adlm.FUF/Ebrima_12/pdf_to_json_test_Adlm.FUF_Ebrima_12.json" 2>&1
Adlm.FUF_Ebrima_16:
	-$(PYTHON) "data/multilingual/Adlm.FUF/Ebrima_16/pdf_to_json_test_Adlm.FUF_Ebrima_16.py" > "data/multilingual/Adlm.FUF/Ebrima_16/pdf_to_json_test_Adlm.FUF_Ebrima_16.json" 2>&1
Adlm.FUF_Ebrima_8:
	-$(PYTHON) "data/multilingual/Adlm.FUF/Ebrima_8/pdf_to_json_test_Adlm.FUF_Ebrima_8.py" > "data/multilingual/Adlm.FUF/Ebrima_8/pdf_to_json_test_Adlm.FUF_Ebrima_8.json" 2>&1
Adlm.FUF_Noto_Sans_Adlam_12:
	-$(PYTHON) "data/multilingual/Adlm.FUF/Noto Sans Adlam_12/pdf_to_json_test_Adlm.FUF_Noto_Sans_Adlam_12.py" > "data/multilingual/Adlm.FUF/Noto Sans Adlam_12/pdf_to_json_test_Adlm.FUF_Noto_Sans_Adlam_12.json" 2>&1
Adlm.FUF_Noto_Sans_Adlam_16:
	-$(PYTHON) "data/multilingual/Adlm.FUF/Noto Sans Adlam_16/pdf_to_json_test_Adlm.FUF_Noto_Sans_Adlam_16.py" > "data/multilingual/Adlm.FUF/Noto Sans Adlam_16/pdf_to_json_test_Adlm.FUF_Noto_Sans_Adlam_16.json" 2>&1
Adlm.FUF_Noto_Sans_Adlam_8:
	-$(PYTHON) "data/multilingual/Adlm.FUF/Noto Sans Adlam_8/pdf_to_json_test_Adlm.FUF_Noto_Sans_Adlam_8.py" > "data/multilingual/Adlm.FUF/Noto Sans Adlam_8/pdf_to_json_test_Adlm.FUF_Noto_Sans_Adlam_8.json" 2>&1


Adlm.FUF_all : Adlm.FUF_Ebrima_12 Adlm.FUF_Ebrima_16 Adlm.FUF_Ebrima_8 Adlm.FUF_Noto_Sans_Adlam_12 Adlm.FUF_Noto_Sans_Adlam_16 Adlm.FUF_Noto_Sans_Adlam_8
