PYTHON=python3


Latn.YUA_Mono_12:
	-$(PYTHON) data/multilingual/Latn.YUA/Mono_12/pdf_to_json_test_Latn.YUA_Mono_12.py > data/multilingual/Latn.YUA/Mono_12/pdf_to_json_test_Latn.YUA_Mono_12.json 2>&1
Latn.YUA_Mono_16:
	-$(PYTHON) data/multilingual/Latn.YUA/Mono_16/pdf_to_json_test_Latn.YUA_Mono_16.py > data/multilingual/Latn.YUA/Mono_16/pdf_to_json_test_Latn.YUA_Mono_16.json 2>&1
Latn.YUA_Mono_8:
	-$(PYTHON) data/multilingual/Latn.YUA/Mono_8/pdf_to_json_test_Latn.YUA_Mono_8.py > data/multilingual/Latn.YUA/Mono_8/pdf_to_json_test_Latn.YUA_Mono_8.json 2>&1
Latn.YUA_Sans_12:
	-$(PYTHON) data/multilingual/Latn.YUA/Sans_12/pdf_to_json_test_Latn.YUA_Sans_12.py > data/multilingual/Latn.YUA/Sans_12/pdf_to_json_test_Latn.YUA_Sans_12.json 2>&1
Latn.YUA_Sans_16:
	-$(PYTHON) data/multilingual/Latn.YUA/Sans_16/pdf_to_json_test_Latn.YUA_Sans_16.py > data/multilingual/Latn.YUA/Sans_16/pdf_to_json_test_Latn.YUA_Sans_16.json 2>&1
Latn.YUA_Sans_8:
	-$(PYTHON) data/multilingual/Latn.YUA/Sans_8/pdf_to_json_test_Latn.YUA_Sans_8.py > data/multilingual/Latn.YUA/Sans_8/pdf_to_json_test_Latn.YUA_Sans_8.json 2>&1
Latn.YUA_Serif_12:
	-$(PYTHON) data/multilingual/Latn.YUA/Serif_12/pdf_to_json_test_Latn.YUA_Serif_12.py > data/multilingual/Latn.YUA/Serif_12/pdf_to_json_test_Latn.YUA_Serif_12.json 2>&1
Latn.YUA_Serif_16:
	-$(PYTHON) data/multilingual/Latn.YUA/Serif_16/pdf_to_json_test_Latn.YUA_Serif_16.py > data/multilingual/Latn.YUA/Serif_16/pdf_to_json_test_Latn.YUA_Serif_16.json 2>&1
Latn.YUA_Serif_8:
	-$(PYTHON) data/multilingual/Latn.YUA/Serif_8/pdf_to_json_test_Latn.YUA_Serif_8.py > data/multilingual/Latn.YUA/Serif_8/pdf_to_json_test_Latn.YUA_Serif_8.json 2>&1
Latn.YUA_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.YUA/Sun-ExtA_12/pdf_to_json_test_Latn.YUA_Sun-ExtA_12.py > data/multilingual/Latn.YUA/Sun-ExtA_12/pdf_to_json_test_Latn.YUA_Sun-ExtA_12.json 2>&1
Latn.YUA_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.YUA/Sun-ExtA_16/pdf_to_json_test_Latn.YUA_Sun-ExtA_16.py > data/multilingual/Latn.YUA/Sun-ExtA_16/pdf_to_json_test_Latn.YUA_Sun-ExtA_16.json 2>&1
Latn.YUA_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.YUA/Sun-ExtA_8/pdf_to_json_test_Latn.YUA_Sun-ExtA_8.py > data/multilingual/Latn.YUA/Sun-ExtA_8/pdf_to_json_test_Latn.YUA_Sun-ExtA_8.json 2>&1


Latn.YUA_all : Latn.YUA_Mono_12 Latn.YUA_Mono_16 Latn.YUA_Mono_8 Latn.YUA_Sans_12 Latn.YUA_Sans_16 Latn.YUA_Sans_8 Latn.YUA_Serif_12 Latn.YUA_Serif_16 Latn.YUA_Serif_8 Latn.YUA_Sun-ExtA_12 Latn.YUA_Sun-ExtA_16 Latn.YUA_Sun-ExtA_8
