PYTHON=python3


Latn.ZLM_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.ZLM/Mono_12/pdf_to_json_test_Latn.ZLM_Mono_12.py" > "data/multilingual/Latn.ZLM/Mono_12/pdf_to_json_test_Latn.ZLM_Mono_12.json" 2>&1
Latn.ZLM_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.ZLM/Mono_16/pdf_to_json_test_Latn.ZLM_Mono_16.py" > "data/multilingual/Latn.ZLM/Mono_16/pdf_to_json_test_Latn.ZLM_Mono_16.json" 2>&1
Latn.ZLM_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.ZLM/Mono_8/pdf_to_json_test_Latn.ZLM_Mono_8.py" > "data/multilingual/Latn.ZLM/Mono_8/pdf_to_json_test_Latn.ZLM_Mono_8.json" 2>&1
Latn.ZLM_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.ZLM/Sans_12/pdf_to_json_test_Latn.ZLM_Sans_12.py" > "data/multilingual/Latn.ZLM/Sans_12/pdf_to_json_test_Latn.ZLM_Sans_12.json" 2>&1
Latn.ZLM_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.ZLM/Sans_16/pdf_to_json_test_Latn.ZLM_Sans_16.py" > "data/multilingual/Latn.ZLM/Sans_16/pdf_to_json_test_Latn.ZLM_Sans_16.json" 2>&1
Latn.ZLM_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.ZLM/Sans_8/pdf_to_json_test_Latn.ZLM_Sans_8.py" > "data/multilingual/Latn.ZLM/Sans_8/pdf_to_json_test_Latn.ZLM_Sans_8.json" 2>&1
Latn.ZLM_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.ZLM/Serif_12/pdf_to_json_test_Latn.ZLM_Serif_12.py" > "data/multilingual/Latn.ZLM/Serif_12/pdf_to_json_test_Latn.ZLM_Serif_12.json" 2>&1
Latn.ZLM_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.ZLM/Serif_16/pdf_to_json_test_Latn.ZLM_Serif_16.py" > "data/multilingual/Latn.ZLM/Serif_16/pdf_to_json_test_Latn.ZLM_Serif_16.json" 2>&1
Latn.ZLM_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.ZLM/Serif_8/pdf_to_json_test_Latn.ZLM_Serif_8.py" > "data/multilingual/Latn.ZLM/Serif_8/pdf_to_json_test_Latn.ZLM_Serif_8.json" 2>&1
Latn.ZLM_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.ZLM/Sun-ExtA_12/pdf_to_json_test_Latn.ZLM_Sun-ExtA_12.py" > "data/multilingual/Latn.ZLM/Sun-ExtA_12/pdf_to_json_test_Latn.ZLM_Sun-ExtA_12.json" 2>&1
Latn.ZLM_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.ZLM/Sun-ExtA_16/pdf_to_json_test_Latn.ZLM_Sun-ExtA_16.py" > "data/multilingual/Latn.ZLM/Sun-ExtA_16/pdf_to_json_test_Latn.ZLM_Sun-ExtA_16.json" 2>&1
Latn.ZLM_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.ZLM/Sun-ExtA_8/pdf_to_json_test_Latn.ZLM_Sun-ExtA_8.py" > "data/multilingual/Latn.ZLM/Sun-ExtA_8/pdf_to_json_test_Latn.ZLM_Sun-ExtA_8.json" 2>&1


Latn.ZLM_all : Latn.ZLM_Mono_12 Latn.ZLM_Mono_16 Latn.ZLM_Mono_8 Latn.ZLM_Sans_12 Latn.ZLM_Sans_16 Latn.ZLM_Sans_8 Latn.ZLM_Serif_12 Latn.ZLM_Serif_16 Latn.ZLM_Serif_8 Latn.ZLM_Sun-ExtA_12 Latn.ZLM_Sun-ExtA_16 Latn.ZLM_Sun-ExtA_8
