PYTHON=python3


Latn.TUR_Mono_12:
	-$(PYTHON) data/multilingual/Latn.TUR/Mono_12/pdf_to_json_test_Latn.TUR_Mono_12.py > data/multilingual/Latn.TUR/Mono_12/pdf_to_json_test_Latn.TUR_Mono_12.json 2>&1
Latn.TUR_Mono_16:
	-$(PYTHON) data/multilingual/Latn.TUR/Mono_16/pdf_to_json_test_Latn.TUR_Mono_16.py > data/multilingual/Latn.TUR/Mono_16/pdf_to_json_test_Latn.TUR_Mono_16.json 2>&1
Latn.TUR_Mono_8:
	-$(PYTHON) data/multilingual/Latn.TUR/Mono_8/pdf_to_json_test_Latn.TUR_Mono_8.py > data/multilingual/Latn.TUR/Mono_8/pdf_to_json_test_Latn.TUR_Mono_8.json 2>&1
Latn.TUR_Sans_12:
	-$(PYTHON) data/multilingual/Latn.TUR/Sans_12/pdf_to_json_test_Latn.TUR_Sans_12.py > data/multilingual/Latn.TUR/Sans_12/pdf_to_json_test_Latn.TUR_Sans_12.json 2>&1
Latn.TUR_Sans_16:
	-$(PYTHON) data/multilingual/Latn.TUR/Sans_16/pdf_to_json_test_Latn.TUR_Sans_16.py > data/multilingual/Latn.TUR/Sans_16/pdf_to_json_test_Latn.TUR_Sans_16.json 2>&1
Latn.TUR_Sans_8:
	-$(PYTHON) data/multilingual/Latn.TUR/Sans_8/pdf_to_json_test_Latn.TUR_Sans_8.py > data/multilingual/Latn.TUR/Sans_8/pdf_to_json_test_Latn.TUR_Sans_8.json 2>&1
Latn.TUR_Serif_12:
	-$(PYTHON) data/multilingual/Latn.TUR/Serif_12/pdf_to_json_test_Latn.TUR_Serif_12.py > data/multilingual/Latn.TUR/Serif_12/pdf_to_json_test_Latn.TUR_Serif_12.json 2>&1
Latn.TUR_Serif_16:
	-$(PYTHON) data/multilingual/Latn.TUR/Serif_16/pdf_to_json_test_Latn.TUR_Serif_16.py > data/multilingual/Latn.TUR/Serif_16/pdf_to_json_test_Latn.TUR_Serif_16.json 2>&1
Latn.TUR_Serif_8:
	-$(PYTHON) data/multilingual/Latn.TUR/Serif_8/pdf_to_json_test_Latn.TUR_Serif_8.py > data/multilingual/Latn.TUR/Serif_8/pdf_to_json_test_Latn.TUR_Serif_8.json 2>&1
Latn.TUR_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.TUR/Sun-ExtA_12/pdf_to_json_test_Latn.TUR_Sun-ExtA_12.py > data/multilingual/Latn.TUR/Sun-ExtA_12/pdf_to_json_test_Latn.TUR_Sun-ExtA_12.json 2>&1
Latn.TUR_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.TUR/Sun-ExtA_16/pdf_to_json_test_Latn.TUR_Sun-ExtA_16.py > data/multilingual/Latn.TUR/Sun-ExtA_16/pdf_to_json_test_Latn.TUR_Sun-ExtA_16.json 2>&1
Latn.TUR_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.TUR/Sun-ExtA_8/pdf_to_json_test_Latn.TUR_Sun-ExtA_8.py > data/multilingual/Latn.TUR/Sun-ExtA_8/pdf_to_json_test_Latn.TUR_Sun-ExtA_8.json 2>&1


Latn.TUR_all : Latn.TUR_Mono_12 Latn.TUR_Mono_16 Latn.TUR_Mono_8 Latn.TUR_Sans_12 Latn.TUR_Sans_16 Latn.TUR_Sans_8 Latn.TUR_Serif_12 Latn.TUR_Serif_16 Latn.TUR_Serif_8 Latn.TUR_Sun-ExtA_12 Latn.TUR_Sun-ExtA_16 Latn.TUR_Sun-ExtA_8
