PYTHON=python3


Mymr.MYA_Mono_12:
	-$(PYTHON) "data/multilingual/Mymr.MYA/Mono_12/pdf_to_json_test_Mymr.MYA_Mono_12.py" > "data/multilingual/Mymr.MYA/Mono_12/pdf_to_json_test_Mymr.MYA_Mono_12.json" 2>&1
Mymr.MYA_Mono_16:
	-$(PYTHON) "data/multilingual/Mymr.MYA/Mono_16/pdf_to_json_test_Mymr.MYA_Mono_16.py" > "data/multilingual/Mymr.MYA/Mono_16/pdf_to_json_test_Mymr.MYA_Mono_16.json" 2>&1
Mymr.MYA_Mono_8:
	-$(PYTHON) "data/multilingual/Mymr.MYA/Mono_8/pdf_to_json_test_Mymr.MYA_Mono_8.py" > "data/multilingual/Mymr.MYA/Mono_8/pdf_to_json_test_Mymr.MYA_Mono_8.json" 2>&1
Mymr.MYA_Sans_12:
	-$(PYTHON) "data/multilingual/Mymr.MYA/Sans_12/pdf_to_json_test_Mymr.MYA_Sans_12.py" > "data/multilingual/Mymr.MYA/Sans_12/pdf_to_json_test_Mymr.MYA_Sans_12.json" 2>&1
Mymr.MYA_Sans_16:
	-$(PYTHON) "data/multilingual/Mymr.MYA/Sans_16/pdf_to_json_test_Mymr.MYA_Sans_16.py" > "data/multilingual/Mymr.MYA/Sans_16/pdf_to_json_test_Mymr.MYA_Sans_16.json" 2>&1
Mymr.MYA_Sans_8:
	-$(PYTHON) "data/multilingual/Mymr.MYA/Sans_8/pdf_to_json_test_Mymr.MYA_Sans_8.py" > "data/multilingual/Mymr.MYA/Sans_8/pdf_to_json_test_Mymr.MYA_Sans_8.json" 2>&1
Mymr.MYA_Serif_12:
	-$(PYTHON) "data/multilingual/Mymr.MYA/Serif_12/pdf_to_json_test_Mymr.MYA_Serif_12.py" > "data/multilingual/Mymr.MYA/Serif_12/pdf_to_json_test_Mymr.MYA_Serif_12.json" 2>&1
Mymr.MYA_Serif_16:
	-$(PYTHON) "data/multilingual/Mymr.MYA/Serif_16/pdf_to_json_test_Mymr.MYA_Serif_16.py" > "data/multilingual/Mymr.MYA/Serif_16/pdf_to_json_test_Mymr.MYA_Serif_16.json" 2>&1
Mymr.MYA_Serif_8:
	-$(PYTHON) "data/multilingual/Mymr.MYA/Serif_8/pdf_to_json_test_Mymr.MYA_Serif_8.py" > "data/multilingual/Mymr.MYA/Serif_8/pdf_to_json_test_Mymr.MYA_Serif_8.json" 2>&1
Mymr.MYA_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Mymr.MYA/Sun-ExtA_12/pdf_to_json_test_Mymr.MYA_Sun-ExtA_12.py" > "data/multilingual/Mymr.MYA/Sun-ExtA_12/pdf_to_json_test_Mymr.MYA_Sun-ExtA_12.json" 2>&1
Mymr.MYA_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Mymr.MYA/Sun-ExtA_16/pdf_to_json_test_Mymr.MYA_Sun-ExtA_16.py" > "data/multilingual/Mymr.MYA/Sun-ExtA_16/pdf_to_json_test_Mymr.MYA_Sun-ExtA_16.json" 2>&1
Mymr.MYA_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Mymr.MYA/Sun-ExtA_8/pdf_to_json_test_Mymr.MYA_Sun-ExtA_8.py" > "data/multilingual/Mymr.MYA/Sun-ExtA_8/pdf_to_json_test_Mymr.MYA_Sun-ExtA_8.json" 2>&1


Mymr.MYA_all : Mymr.MYA_Mono_12 Mymr.MYA_Mono_16 Mymr.MYA_Mono_8 Mymr.MYA_Sans_12 Mymr.MYA_Sans_16 Mymr.MYA_Sans_8 Mymr.MYA_Serif_12 Mymr.MYA_Serif_16 Mymr.MYA_Serif_8 Mymr.MYA_Sun-ExtA_12 Mymr.MYA_Sun-ExtA_16 Mymr.MYA_Sun-ExtA_8
