PYTHON=python3


Latn.NBL_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.NBL/Mono_12/pdf_to_json_test_Latn.NBL_Mono_12.py" > "data/multilingual/Latn.NBL/Mono_12/pdf_to_json_test_Latn.NBL_Mono_12.json" 2>&1
Latn.NBL_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.NBL/Mono_16/pdf_to_json_test_Latn.NBL_Mono_16.py" > "data/multilingual/Latn.NBL/Mono_16/pdf_to_json_test_Latn.NBL_Mono_16.json" 2>&1
Latn.NBL_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.NBL/Mono_8/pdf_to_json_test_Latn.NBL_Mono_8.py" > "data/multilingual/Latn.NBL/Mono_8/pdf_to_json_test_Latn.NBL_Mono_8.json" 2>&1
Latn.NBL_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.NBL/Sans_12/pdf_to_json_test_Latn.NBL_Sans_12.py" > "data/multilingual/Latn.NBL/Sans_12/pdf_to_json_test_Latn.NBL_Sans_12.json" 2>&1
Latn.NBL_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.NBL/Sans_16/pdf_to_json_test_Latn.NBL_Sans_16.py" > "data/multilingual/Latn.NBL/Sans_16/pdf_to_json_test_Latn.NBL_Sans_16.json" 2>&1
Latn.NBL_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.NBL/Sans_8/pdf_to_json_test_Latn.NBL_Sans_8.py" > "data/multilingual/Latn.NBL/Sans_8/pdf_to_json_test_Latn.NBL_Sans_8.json" 2>&1
Latn.NBL_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.NBL/Serif_12/pdf_to_json_test_Latn.NBL_Serif_12.py" > "data/multilingual/Latn.NBL/Serif_12/pdf_to_json_test_Latn.NBL_Serif_12.json" 2>&1
Latn.NBL_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.NBL/Serif_16/pdf_to_json_test_Latn.NBL_Serif_16.py" > "data/multilingual/Latn.NBL/Serif_16/pdf_to_json_test_Latn.NBL_Serif_16.json" 2>&1
Latn.NBL_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.NBL/Serif_8/pdf_to_json_test_Latn.NBL_Serif_8.py" > "data/multilingual/Latn.NBL/Serif_8/pdf_to_json_test_Latn.NBL_Serif_8.json" 2>&1
Latn.NBL_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.NBL/Sun-ExtA_12/pdf_to_json_test_Latn.NBL_Sun-ExtA_12.py" > "data/multilingual/Latn.NBL/Sun-ExtA_12/pdf_to_json_test_Latn.NBL_Sun-ExtA_12.json" 2>&1
Latn.NBL_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.NBL/Sun-ExtA_16/pdf_to_json_test_Latn.NBL_Sun-ExtA_16.py" > "data/multilingual/Latn.NBL/Sun-ExtA_16/pdf_to_json_test_Latn.NBL_Sun-ExtA_16.json" 2>&1
Latn.NBL_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.NBL/Sun-ExtA_8/pdf_to_json_test_Latn.NBL_Sun-ExtA_8.py" > "data/multilingual/Latn.NBL/Sun-ExtA_8/pdf_to_json_test_Latn.NBL_Sun-ExtA_8.json" 2>&1


Latn.NBL_all : Latn.NBL_Mono_12 Latn.NBL_Mono_16 Latn.NBL_Mono_8 Latn.NBL_Sans_12 Latn.NBL_Sans_16 Latn.NBL_Sans_8 Latn.NBL_Serif_12 Latn.NBL_Serif_16 Latn.NBL_Serif_8 Latn.NBL_Sun-ExtA_12 Latn.NBL_Sun-ExtA_16 Latn.NBL_Sun-ExtA_8
