PYTHON=python3


Cyrl.OSS_Mono_12:
	-$(PYTHON) "data/multilingual/Cyrl.OSS/Mono_12/pdf_to_json_test_Cyrl.OSS_Mono_12.py" > "data/multilingual/Cyrl.OSS/Mono_12/pdf_to_json_test_Cyrl.OSS_Mono_12.json" 2>&1
Cyrl.OSS_Mono_16:
	-$(PYTHON) "data/multilingual/Cyrl.OSS/Mono_16/pdf_to_json_test_Cyrl.OSS_Mono_16.py" > "data/multilingual/Cyrl.OSS/Mono_16/pdf_to_json_test_Cyrl.OSS_Mono_16.json" 2>&1
Cyrl.OSS_Mono_8:
	-$(PYTHON) "data/multilingual/Cyrl.OSS/Mono_8/pdf_to_json_test_Cyrl.OSS_Mono_8.py" > "data/multilingual/Cyrl.OSS/Mono_8/pdf_to_json_test_Cyrl.OSS_Mono_8.json" 2>&1
Cyrl.OSS_Sans_12:
	-$(PYTHON) "data/multilingual/Cyrl.OSS/Sans_12/pdf_to_json_test_Cyrl.OSS_Sans_12.py" > "data/multilingual/Cyrl.OSS/Sans_12/pdf_to_json_test_Cyrl.OSS_Sans_12.json" 2>&1
Cyrl.OSS_Sans_16:
	-$(PYTHON) "data/multilingual/Cyrl.OSS/Sans_16/pdf_to_json_test_Cyrl.OSS_Sans_16.py" > "data/multilingual/Cyrl.OSS/Sans_16/pdf_to_json_test_Cyrl.OSS_Sans_16.json" 2>&1
Cyrl.OSS_Sans_8:
	-$(PYTHON) "data/multilingual/Cyrl.OSS/Sans_8/pdf_to_json_test_Cyrl.OSS_Sans_8.py" > "data/multilingual/Cyrl.OSS/Sans_8/pdf_to_json_test_Cyrl.OSS_Sans_8.json" 2>&1
Cyrl.OSS_Serif_12:
	-$(PYTHON) "data/multilingual/Cyrl.OSS/Serif_12/pdf_to_json_test_Cyrl.OSS_Serif_12.py" > "data/multilingual/Cyrl.OSS/Serif_12/pdf_to_json_test_Cyrl.OSS_Serif_12.json" 2>&1
Cyrl.OSS_Serif_16:
	-$(PYTHON) "data/multilingual/Cyrl.OSS/Serif_16/pdf_to_json_test_Cyrl.OSS_Serif_16.py" > "data/multilingual/Cyrl.OSS/Serif_16/pdf_to_json_test_Cyrl.OSS_Serif_16.json" 2>&1
Cyrl.OSS_Serif_8:
	-$(PYTHON) "data/multilingual/Cyrl.OSS/Serif_8/pdf_to_json_test_Cyrl.OSS_Serif_8.py" > "data/multilingual/Cyrl.OSS/Serif_8/pdf_to_json_test_Cyrl.OSS_Serif_8.json" 2>&1
Cyrl.OSS_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Cyrl.OSS/Sun-ExtA_12/pdf_to_json_test_Cyrl.OSS_Sun-ExtA_12.py" > "data/multilingual/Cyrl.OSS/Sun-ExtA_12/pdf_to_json_test_Cyrl.OSS_Sun-ExtA_12.json" 2>&1
Cyrl.OSS_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Cyrl.OSS/Sun-ExtA_16/pdf_to_json_test_Cyrl.OSS_Sun-ExtA_16.py" > "data/multilingual/Cyrl.OSS/Sun-ExtA_16/pdf_to_json_test_Cyrl.OSS_Sun-ExtA_16.json" 2>&1
Cyrl.OSS_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Cyrl.OSS/Sun-ExtA_8/pdf_to_json_test_Cyrl.OSS_Sun-ExtA_8.py" > "data/multilingual/Cyrl.OSS/Sun-ExtA_8/pdf_to_json_test_Cyrl.OSS_Sun-ExtA_8.json" 2>&1


Cyrl.OSS_all : Cyrl.OSS_Mono_12 Cyrl.OSS_Mono_16 Cyrl.OSS_Mono_8 Cyrl.OSS_Sans_12 Cyrl.OSS_Sans_16 Cyrl.OSS_Sans_8 Cyrl.OSS_Serif_12 Cyrl.OSS_Serif_16 Cyrl.OSS_Serif_8 Cyrl.OSS_Sun-ExtA_12 Cyrl.OSS_Sun-ExtA_16 Cyrl.OSS_Sun-ExtA_8
