PYTHON=python3


Latn.HNJ_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.HNJ/Mono_12/pdf_to_json_test_Latn.HNJ_Mono_12.py" > "data/multilingual/Latn.HNJ/Mono_12/pdf_to_json_test_Latn.HNJ_Mono_12.json" 2>&1
Latn.HNJ_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.HNJ/Mono_16/pdf_to_json_test_Latn.HNJ_Mono_16.py" > "data/multilingual/Latn.HNJ/Mono_16/pdf_to_json_test_Latn.HNJ_Mono_16.json" 2>&1
Latn.HNJ_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.HNJ/Mono_8/pdf_to_json_test_Latn.HNJ_Mono_8.py" > "data/multilingual/Latn.HNJ/Mono_8/pdf_to_json_test_Latn.HNJ_Mono_8.json" 2>&1
Latn.HNJ_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.HNJ/Sans_12/pdf_to_json_test_Latn.HNJ_Sans_12.py" > "data/multilingual/Latn.HNJ/Sans_12/pdf_to_json_test_Latn.HNJ_Sans_12.json" 2>&1
Latn.HNJ_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.HNJ/Sans_16/pdf_to_json_test_Latn.HNJ_Sans_16.py" > "data/multilingual/Latn.HNJ/Sans_16/pdf_to_json_test_Latn.HNJ_Sans_16.json" 2>&1
Latn.HNJ_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.HNJ/Sans_8/pdf_to_json_test_Latn.HNJ_Sans_8.py" > "data/multilingual/Latn.HNJ/Sans_8/pdf_to_json_test_Latn.HNJ_Sans_8.json" 2>&1
Latn.HNJ_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.HNJ/Serif_12/pdf_to_json_test_Latn.HNJ_Serif_12.py" > "data/multilingual/Latn.HNJ/Serif_12/pdf_to_json_test_Latn.HNJ_Serif_12.json" 2>&1
Latn.HNJ_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.HNJ/Serif_16/pdf_to_json_test_Latn.HNJ_Serif_16.py" > "data/multilingual/Latn.HNJ/Serif_16/pdf_to_json_test_Latn.HNJ_Serif_16.json" 2>&1
Latn.HNJ_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.HNJ/Serif_8/pdf_to_json_test_Latn.HNJ_Serif_8.py" > "data/multilingual/Latn.HNJ/Serif_8/pdf_to_json_test_Latn.HNJ_Serif_8.json" 2>&1
Latn.HNJ_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.HNJ/Sun-ExtA_12/pdf_to_json_test_Latn.HNJ_Sun-ExtA_12.py" > "data/multilingual/Latn.HNJ/Sun-ExtA_12/pdf_to_json_test_Latn.HNJ_Sun-ExtA_12.json" 2>&1
Latn.HNJ_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.HNJ/Sun-ExtA_16/pdf_to_json_test_Latn.HNJ_Sun-ExtA_16.py" > "data/multilingual/Latn.HNJ/Sun-ExtA_16/pdf_to_json_test_Latn.HNJ_Sun-ExtA_16.json" 2>&1
Latn.HNJ_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.HNJ/Sun-ExtA_8/pdf_to_json_test_Latn.HNJ_Sun-ExtA_8.py" > "data/multilingual/Latn.HNJ/Sun-ExtA_8/pdf_to_json_test_Latn.HNJ_Sun-ExtA_8.json" 2>&1


Latn.HNJ_all : Latn.HNJ_Mono_12 Latn.HNJ_Mono_16 Latn.HNJ_Mono_8 Latn.HNJ_Sans_12 Latn.HNJ_Sans_16 Latn.HNJ_Sans_8 Latn.HNJ_Serif_12 Latn.HNJ_Serif_16 Latn.HNJ_Serif_8 Latn.HNJ_Sun-ExtA_12 Latn.HNJ_Sun-ExtA_16 Latn.HNJ_Sun-ExtA_8
