PYTHON=python3


Latn.LIA_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.LIA/Mono_12/pdf_to_json_test_Latn.LIA_Mono_12.py" > "data/multilingual/Latn.LIA/Mono_12/pdf_to_json_test_Latn.LIA_Mono_12.json" 2>&1
Latn.LIA_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.LIA/Mono_16/pdf_to_json_test_Latn.LIA_Mono_16.py" > "data/multilingual/Latn.LIA/Mono_16/pdf_to_json_test_Latn.LIA_Mono_16.json" 2>&1
Latn.LIA_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.LIA/Mono_8/pdf_to_json_test_Latn.LIA_Mono_8.py" > "data/multilingual/Latn.LIA/Mono_8/pdf_to_json_test_Latn.LIA_Mono_8.json" 2>&1
Latn.LIA_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.LIA/Sans_12/pdf_to_json_test_Latn.LIA_Sans_12.py" > "data/multilingual/Latn.LIA/Sans_12/pdf_to_json_test_Latn.LIA_Sans_12.json" 2>&1
Latn.LIA_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.LIA/Sans_16/pdf_to_json_test_Latn.LIA_Sans_16.py" > "data/multilingual/Latn.LIA/Sans_16/pdf_to_json_test_Latn.LIA_Sans_16.json" 2>&1
Latn.LIA_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.LIA/Sans_8/pdf_to_json_test_Latn.LIA_Sans_8.py" > "data/multilingual/Latn.LIA/Sans_8/pdf_to_json_test_Latn.LIA_Sans_8.json" 2>&1
Latn.LIA_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.LIA/Serif_12/pdf_to_json_test_Latn.LIA_Serif_12.py" > "data/multilingual/Latn.LIA/Serif_12/pdf_to_json_test_Latn.LIA_Serif_12.json" 2>&1
Latn.LIA_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.LIA/Serif_16/pdf_to_json_test_Latn.LIA_Serif_16.py" > "data/multilingual/Latn.LIA/Serif_16/pdf_to_json_test_Latn.LIA_Serif_16.json" 2>&1
Latn.LIA_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.LIA/Serif_8/pdf_to_json_test_Latn.LIA_Serif_8.py" > "data/multilingual/Latn.LIA/Serif_8/pdf_to_json_test_Latn.LIA_Serif_8.json" 2>&1
Latn.LIA_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.LIA/Sun-ExtA_12/pdf_to_json_test_Latn.LIA_Sun-ExtA_12.py" > "data/multilingual/Latn.LIA/Sun-ExtA_12/pdf_to_json_test_Latn.LIA_Sun-ExtA_12.json" 2>&1
Latn.LIA_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.LIA/Sun-ExtA_16/pdf_to_json_test_Latn.LIA_Sun-ExtA_16.py" > "data/multilingual/Latn.LIA/Sun-ExtA_16/pdf_to_json_test_Latn.LIA_Sun-ExtA_16.json" 2>&1
Latn.LIA_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.LIA/Sun-ExtA_8/pdf_to_json_test_Latn.LIA_Sun-ExtA_8.py" > "data/multilingual/Latn.LIA/Sun-ExtA_8/pdf_to_json_test_Latn.LIA_Sun-ExtA_8.json" 2>&1


Latn.LIA_all : Latn.LIA_Mono_12 Latn.LIA_Mono_16 Latn.LIA_Mono_8 Latn.LIA_Sans_12 Latn.LIA_Sans_16 Latn.LIA_Sans_8 Latn.LIA_Serif_12 Latn.LIA_Serif_16 Latn.LIA_Serif_8 Latn.LIA_Sun-ExtA_12 Latn.LIA_Sun-ExtA_16 Latn.LIA_Sun-ExtA_8
