PYTHON=python3


Guru.PAN_Mono_12:
	-$(PYTHON) "data/multilingual/Guru.PAN/Mono_12/pdf_to_json_test_Guru.PAN_Mono_12.py" > "data/multilingual/Guru.PAN/Mono_12/pdf_to_json_test_Guru.PAN_Mono_12.json" 2>&1
Guru.PAN_Mono_16:
	-$(PYTHON) "data/multilingual/Guru.PAN/Mono_16/pdf_to_json_test_Guru.PAN_Mono_16.py" > "data/multilingual/Guru.PAN/Mono_16/pdf_to_json_test_Guru.PAN_Mono_16.json" 2>&1
Guru.PAN_Mono_8:
	-$(PYTHON) "data/multilingual/Guru.PAN/Mono_8/pdf_to_json_test_Guru.PAN_Mono_8.py" > "data/multilingual/Guru.PAN/Mono_8/pdf_to_json_test_Guru.PAN_Mono_8.json" 2>&1
Guru.PAN_Sans_12:
	-$(PYTHON) "data/multilingual/Guru.PAN/Sans_12/pdf_to_json_test_Guru.PAN_Sans_12.py" > "data/multilingual/Guru.PAN/Sans_12/pdf_to_json_test_Guru.PAN_Sans_12.json" 2>&1
Guru.PAN_Sans_16:
	-$(PYTHON) "data/multilingual/Guru.PAN/Sans_16/pdf_to_json_test_Guru.PAN_Sans_16.py" > "data/multilingual/Guru.PAN/Sans_16/pdf_to_json_test_Guru.PAN_Sans_16.json" 2>&1
Guru.PAN_Sans_8:
	-$(PYTHON) "data/multilingual/Guru.PAN/Sans_8/pdf_to_json_test_Guru.PAN_Sans_8.py" > "data/multilingual/Guru.PAN/Sans_8/pdf_to_json_test_Guru.PAN_Sans_8.json" 2>&1
Guru.PAN_Serif_12:
	-$(PYTHON) "data/multilingual/Guru.PAN/Serif_12/pdf_to_json_test_Guru.PAN_Serif_12.py" > "data/multilingual/Guru.PAN/Serif_12/pdf_to_json_test_Guru.PAN_Serif_12.json" 2>&1
Guru.PAN_Serif_16:
	-$(PYTHON) "data/multilingual/Guru.PAN/Serif_16/pdf_to_json_test_Guru.PAN_Serif_16.py" > "data/multilingual/Guru.PAN/Serif_16/pdf_to_json_test_Guru.PAN_Serif_16.json" 2>&1
Guru.PAN_Serif_8:
	-$(PYTHON) "data/multilingual/Guru.PAN/Serif_8/pdf_to_json_test_Guru.PAN_Serif_8.py" > "data/multilingual/Guru.PAN/Serif_8/pdf_to_json_test_Guru.PAN_Serif_8.json" 2>&1
Guru.PAN_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Guru.PAN/Sun-ExtA_12/pdf_to_json_test_Guru.PAN_Sun-ExtA_12.py" > "data/multilingual/Guru.PAN/Sun-ExtA_12/pdf_to_json_test_Guru.PAN_Sun-ExtA_12.json" 2>&1
Guru.PAN_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Guru.PAN/Sun-ExtA_16/pdf_to_json_test_Guru.PAN_Sun-ExtA_16.py" > "data/multilingual/Guru.PAN/Sun-ExtA_16/pdf_to_json_test_Guru.PAN_Sun-ExtA_16.json" 2>&1
Guru.PAN_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Guru.PAN/Sun-ExtA_8/pdf_to_json_test_Guru.PAN_Sun-ExtA_8.py" > "data/multilingual/Guru.PAN/Sun-ExtA_8/pdf_to_json_test_Guru.PAN_Sun-ExtA_8.json" 2>&1


Guru.PAN_all : Guru.PAN_Mono_12 Guru.PAN_Mono_16 Guru.PAN_Mono_8 Guru.PAN_Sans_12 Guru.PAN_Sans_16 Guru.PAN_Sans_8 Guru.PAN_Serif_12 Guru.PAN_Serif_16 Guru.PAN_Serif_8 Guru.PAN_Sun-ExtA_12 Guru.PAN_Sun-ExtA_16 Guru.PAN_Sun-ExtA_8
