PYTHON=python3


Latn.PBB_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.PBB/Mono_12/pdf_to_json_test_Latn.PBB_Mono_12.py" > "data/multilingual/Latn.PBB/Mono_12/pdf_to_json_test_Latn.PBB_Mono_12.json" 2>&1
Latn.PBB_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.PBB/Mono_16/pdf_to_json_test_Latn.PBB_Mono_16.py" > "data/multilingual/Latn.PBB/Mono_16/pdf_to_json_test_Latn.PBB_Mono_16.json" 2>&1
Latn.PBB_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.PBB/Mono_8/pdf_to_json_test_Latn.PBB_Mono_8.py" > "data/multilingual/Latn.PBB/Mono_8/pdf_to_json_test_Latn.PBB_Mono_8.json" 2>&1
Latn.PBB_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.PBB/Sans_12/pdf_to_json_test_Latn.PBB_Sans_12.py" > "data/multilingual/Latn.PBB/Sans_12/pdf_to_json_test_Latn.PBB_Sans_12.json" 2>&1
Latn.PBB_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.PBB/Sans_16/pdf_to_json_test_Latn.PBB_Sans_16.py" > "data/multilingual/Latn.PBB/Sans_16/pdf_to_json_test_Latn.PBB_Sans_16.json" 2>&1
Latn.PBB_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.PBB/Sans_8/pdf_to_json_test_Latn.PBB_Sans_8.py" > "data/multilingual/Latn.PBB/Sans_8/pdf_to_json_test_Latn.PBB_Sans_8.json" 2>&1
Latn.PBB_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.PBB/Serif_12/pdf_to_json_test_Latn.PBB_Serif_12.py" > "data/multilingual/Latn.PBB/Serif_12/pdf_to_json_test_Latn.PBB_Serif_12.json" 2>&1
Latn.PBB_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.PBB/Serif_16/pdf_to_json_test_Latn.PBB_Serif_16.py" > "data/multilingual/Latn.PBB/Serif_16/pdf_to_json_test_Latn.PBB_Serif_16.json" 2>&1
Latn.PBB_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.PBB/Serif_8/pdf_to_json_test_Latn.PBB_Serif_8.py" > "data/multilingual/Latn.PBB/Serif_8/pdf_to_json_test_Latn.PBB_Serif_8.json" 2>&1
Latn.PBB_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.PBB/Sun-ExtA_12/pdf_to_json_test_Latn.PBB_Sun-ExtA_12.py" > "data/multilingual/Latn.PBB/Sun-ExtA_12/pdf_to_json_test_Latn.PBB_Sun-ExtA_12.json" 2>&1
Latn.PBB_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.PBB/Sun-ExtA_16/pdf_to_json_test_Latn.PBB_Sun-ExtA_16.py" > "data/multilingual/Latn.PBB/Sun-ExtA_16/pdf_to_json_test_Latn.PBB_Sun-ExtA_16.json" 2>&1
Latn.PBB_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.PBB/Sun-ExtA_8/pdf_to_json_test_Latn.PBB_Sun-ExtA_8.py" > "data/multilingual/Latn.PBB/Sun-ExtA_8/pdf_to_json_test_Latn.PBB_Sun-ExtA_8.json" 2>&1


Latn.PBB_all : Latn.PBB_Mono_12 Latn.PBB_Mono_16 Latn.PBB_Mono_8 Latn.PBB_Sans_12 Latn.PBB_Sans_16 Latn.PBB_Sans_8 Latn.PBB_Serif_12 Latn.PBB_Serif_16 Latn.PBB_Serif_8 Latn.PBB_Sun-ExtA_12 Latn.PBB_Sun-ExtA_16 Latn.PBB_Sun-ExtA_8
