PYTHON=python3


Arab.UIG_Mono_12:
	-$(PYTHON) data/multilingual/Arab.UIG/Mono_12/pdf_to_json_test_Arab.UIG_Mono_12.py > data/multilingual/Arab.UIG/Mono_12/pdf_to_json_test_Arab.UIG_Mono_12.json 2>&1
Arab.UIG_Mono_16:
	-$(PYTHON) data/multilingual/Arab.UIG/Mono_16/pdf_to_json_test_Arab.UIG_Mono_16.py > data/multilingual/Arab.UIG/Mono_16/pdf_to_json_test_Arab.UIG_Mono_16.json 2>&1
Arab.UIG_Mono_8:
	-$(PYTHON) data/multilingual/Arab.UIG/Mono_8/pdf_to_json_test_Arab.UIG_Mono_8.py > data/multilingual/Arab.UIG/Mono_8/pdf_to_json_test_Arab.UIG_Mono_8.json 2>&1
Arab.UIG_Sans_12:
	-$(PYTHON) data/multilingual/Arab.UIG/Sans_12/pdf_to_json_test_Arab.UIG_Sans_12.py > data/multilingual/Arab.UIG/Sans_12/pdf_to_json_test_Arab.UIG_Sans_12.json 2>&1
Arab.UIG_Sans_16:
	-$(PYTHON) data/multilingual/Arab.UIG/Sans_16/pdf_to_json_test_Arab.UIG_Sans_16.py > data/multilingual/Arab.UIG/Sans_16/pdf_to_json_test_Arab.UIG_Sans_16.json 2>&1
Arab.UIG_Sans_8:
	-$(PYTHON) data/multilingual/Arab.UIG/Sans_8/pdf_to_json_test_Arab.UIG_Sans_8.py > data/multilingual/Arab.UIG/Sans_8/pdf_to_json_test_Arab.UIG_Sans_8.json 2>&1
Arab.UIG_Serif_12:
	-$(PYTHON) data/multilingual/Arab.UIG/Serif_12/pdf_to_json_test_Arab.UIG_Serif_12.py > data/multilingual/Arab.UIG/Serif_12/pdf_to_json_test_Arab.UIG_Serif_12.json 2>&1
Arab.UIG_Serif_16:
	-$(PYTHON) data/multilingual/Arab.UIG/Serif_16/pdf_to_json_test_Arab.UIG_Serif_16.py > data/multilingual/Arab.UIG/Serif_16/pdf_to_json_test_Arab.UIG_Serif_16.json 2>&1
Arab.UIG_Serif_8:
	-$(PYTHON) data/multilingual/Arab.UIG/Serif_8/pdf_to_json_test_Arab.UIG_Serif_8.py > data/multilingual/Arab.UIG/Serif_8/pdf_to_json_test_Arab.UIG_Serif_8.json 2>&1
Arab.UIG_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Arab.UIG/Sun-ExtA_12/pdf_to_json_test_Arab.UIG_Sun-ExtA_12.py > data/multilingual/Arab.UIG/Sun-ExtA_12/pdf_to_json_test_Arab.UIG_Sun-ExtA_12.json 2>&1
Arab.UIG_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Arab.UIG/Sun-ExtA_16/pdf_to_json_test_Arab.UIG_Sun-ExtA_16.py > data/multilingual/Arab.UIG/Sun-ExtA_16/pdf_to_json_test_Arab.UIG_Sun-ExtA_16.json 2>&1
Arab.UIG_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Arab.UIG/Sun-ExtA_8/pdf_to_json_test_Arab.UIG_Sun-ExtA_8.py > data/multilingual/Arab.UIG/Sun-ExtA_8/pdf_to_json_test_Arab.UIG_Sun-ExtA_8.json 2>&1


Arab.UIG_all : Arab.UIG_Mono_12 Arab.UIG_Mono_16 Arab.UIG_Mono_8 Arab.UIG_Sans_12 Arab.UIG_Sans_16 Arab.UIG_Sans_8 Arab.UIG_Serif_12 Arab.UIG_Serif_16 Arab.UIG_Serif_8 Arab.UIG_Sun-ExtA_12 Arab.UIG_Sun-ExtA_16 Arab.UIG_Sun-ExtA_8
