PYTHON=python3


Latn.HAT_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.HAT/Mono_12/pdf_to_json_test_Latn.HAT_Mono_12.py" > "data/multilingual/Latn.HAT/Mono_12/pdf_to_json_test_Latn.HAT_Mono_12.json" 2>&1
Latn.HAT_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.HAT/Mono_16/pdf_to_json_test_Latn.HAT_Mono_16.py" > "data/multilingual/Latn.HAT/Mono_16/pdf_to_json_test_Latn.HAT_Mono_16.json" 2>&1
Latn.HAT_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.HAT/Mono_8/pdf_to_json_test_Latn.HAT_Mono_8.py" > "data/multilingual/Latn.HAT/Mono_8/pdf_to_json_test_Latn.HAT_Mono_8.json" 2>&1
Latn.HAT_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.HAT/Sans_12/pdf_to_json_test_Latn.HAT_Sans_12.py" > "data/multilingual/Latn.HAT/Sans_12/pdf_to_json_test_Latn.HAT_Sans_12.json" 2>&1
Latn.HAT_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.HAT/Sans_16/pdf_to_json_test_Latn.HAT_Sans_16.py" > "data/multilingual/Latn.HAT/Sans_16/pdf_to_json_test_Latn.HAT_Sans_16.json" 2>&1
Latn.HAT_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.HAT/Sans_8/pdf_to_json_test_Latn.HAT_Sans_8.py" > "data/multilingual/Latn.HAT/Sans_8/pdf_to_json_test_Latn.HAT_Sans_8.json" 2>&1
Latn.HAT_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.HAT/Serif_12/pdf_to_json_test_Latn.HAT_Serif_12.py" > "data/multilingual/Latn.HAT/Serif_12/pdf_to_json_test_Latn.HAT_Serif_12.json" 2>&1
Latn.HAT_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.HAT/Serif_16/pdf_to_json_test_Latn.HAT_Serif_16.py" > "data/multilingual/Latn.HAT/Serif_16/pdf_to_json_test_Latn.HAT_Serif_16.json" 2>&1
Latn.HAT_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.HAT/Serif_8/pdf_to_json_test_Latn.HAT_Serif_8.py" > "data/multilingual/Latn.HAT/Serif_8/pdf_to_json_test_Latn.HAT_Serif_8.json" 2>&1
Latn.HAT_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.HAT/Sun-ExtA_12/pdf_to_json_test_Latn.HAT_Sun-ExtA_12.py" > "data/multilingual/Latn.HAT/Sun-ExtA_12/pdf_to_json_test_Latn.HAT_Sun-ExtA_12.json" 2>&1
Latn.HAT_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.HAT/Sun-ExtA_16/pdf_to_json_test_Latn.HAT_Sun-ExtA_16.py" > "data/multilingual/Latn.HAT/Sun-ExtA_16/pdf_to_json_test_Latn.HAT_Sun-ExtA_16.json" 2>&1
Latn.HAT_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.HAT/Sun-ExtA_8/pdf_to_json_test_Latn.HAT_Sun-ExtA_8.py" > "data/multilingual/Latn.HAT/Sun-ExtA_8/pdf_to_json_test_Latn.HAT_Sun-ExtA_8.json" 2>&1


Latn.HAT_all : Latn.HAT_Mono_12 Latn.HAT_Mono_16 Latn.HAT_Mono_8 Latn.HAT_Sans_12 Latn.HAT_Sans_16 Latn.HAT_Sans_8 Latn.HAT_Serif_12 Latn.HAT_Serif_16 Latn.HAT_Serif_8 Latn.HAT_Sun-ExtA_12 Latn.HAT_Sun-ExtA_16 Latn.HAT_Sun-ExtA_8
