PYTHON=python3


Cyrl.KHK_Mono_12:
	-$(PYTHON) data/multilingual/Cyrl.KHK/Mono_12/pdf_to_json_test_Cyrl.KHK_Mono_12.py > data/multilingual/Cyrl.KHK/Mono_12/pdf_to_json_test_Cyrl.KHK_Mono_12.json 2>&1
Cyrl.KHK_Mono_16:
	-$(PYTHON) data/multilingual/Cyrl.KHK/Mono_16/pdf_to_json_test_Cyrl.KHK_Mono_16.py > data/multilingual/Cyrl.KHK/Mono_16/pdf_to_json_test_Cyrl.KHK_Mono_16.json 2>&1
Cyrl.KHK_Mono_8:
	-$(PYTHON) data/multilingual/Cyrl.KHK/Mono_8/pdf_to_json_test_Cyrl.KHK_Mono_8.py > data/multilingual/Cyrl.KHK/Mono_8/pdf_to_json_test_Cyrl.KHK_Mono_8.json 2>&1
Cyrl.KHK_Sans_12:
	-$(PYTHON) data/multilingual/Cyrl.KHK/Sans_12/pdf_to_json_test_Cyrl.KHK_Sans_12.py > data/multilingual/Cyrl.KHK/Sans_12/pdf_to_json_test_Cyrl.KHK_Sans_12.json 2>&1
Cyrl.KHK_Sans_16:
	-$(PYTHON) data/multilingual/Cyrl.KHK/Sans_16/pdf_to_json_test_Cyrl.KHK_Sans_16.py > data/multilingual/Cyrl.KHK/Sans_16/pdf_to_json_test_Cyrl.KHK_Sans_16.json 2>&1
Cyrl.KHK_Sans_8:
	-$(PYTHON) data/multilingual/Cyrl.KHK/Sans_8/pdf_to_json_test_Cyrl.KHK_Sans_8.py > data/multilingual/Cyrl.KHK/Sans_8/pdf_to_json_test_Cyrl.KHK_Sans_8.json 2>&1
Cyrl.KHK_Serif_12:
	-$(PYTHON) data/multilingual/Cyrl.KHK/Serif_12/pdf_to_json_test_Cyrl.KHK_Serif_12.py > data/multilingual/Cyrl.KHK/Serif_12/pdf_to_json_test_Cyrl.KHK_Serif_12.json 2>&1
Cyrl.KHK_Serif_16:
	-$(PYTHON) data/multilingual/Cyrl.KHK/Serif_16/pdf_to_json_test_Cyrl.KHK_Serif_16.py > data/multilingual/Cyrl.KHK/Serif_16/pdf_to_json_test_Cyrl.KHK_Serif_16.json 2>&1
Cyrl.KHK_Serif_8:
	-$(PYTHON) data/multilingual/Cyrl.KHK/Serif_8/pdf_to_json_test_Cyrl.KHK_Serif_8.py > data/multilingual/Cyrl.KHK/Serif_8/pdf_to_json_test_Cyrl.KHK_Serif_8.json 2>&1
Cyrl.KHK_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Cyrl.KHK/Sun-ExtA_12/pdf_to_json_test_Cyrl.KHK_Sun-ExtA_12.py > data/multilingual/Cyrl.KHK/Sun-ExtA_12/pdf_to_json_test_Cyrl.KHK_Sun-ExtA_12.json 2>&1
Cyrl.KHK_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Cyrl.KHK/Sun-ExtA_16/pdf_to_json_test_Cyrl.KHK_Sun-ExtA_16.py > data/multilingual/Cyrl.KHK/Sun-ExtA_16/pdf_to_json_test_Cyrl.KHK_Sun-ExtA_16.json 2>&1
Cyrl.KHK_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Cyrl.KHK/Sun-ExtA_8/pdf_to_json_test_Cyrl.KHK_Sun-ExtA_8.py > data/multilingual/Cyrl.KHK/Sun-ExtA_8/pdf_to_json_test_Cyrl.KHK_Sun-ExtA_8.json 2>&1


Cyrl.KHK_all : Cyrl.KHK_Mono_12 Cyrl.KHK_Mono_16 Cyrl.KHK_Mono_8 Cyrl.KHK_Sans_12 Cyrl.KHK_Sans_16 Cyrl.KHK_Sans_8 Cyrl.KHK_Serif_12 Cyrl.KHK_Serif_16 Cyrl.KHK_Serif_8 Cyrl.KHK_Sun-ExtA_12 Cyrl.KHK_Sun-ExtA_16 Cyrl.KHK_Sun-ExtA_8
