PYTHON=python3


Latn.CNH_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.CNH/Mono_12/pdf_to_json_test_Latn.CNH_Mono_12.py" > "data/multilingual/Latn.CNH/Mono_12/pdf_to_json_test_Latn.CNH_Mono_12.json" 2>&1
Latn.CNH_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.CNH/Mono_16/pdf_to_json_test_Latn.CNH_Mono_16.py" > "data/multilingual/Latn.CNH/Mono_16/pdf_to_json_test_Latn.CNH_Mono_16.json" 2>&1
Latn.CNH_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.CNH/Mono_8/pdf_to_json_test_Latn.CNH_Mono_8.py" > "data/multilingual/Latn.CNH/Mono_8/pdf_to_json_test_Latn.CNH_Mono_8.json" 2>&1
Latn.CNH_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.CNH/Sans_12/pdf_to_json_test_Latn.CNH_Sans_12.py" > "data/multilingual/Latn.CNH/Sans_12/pdf_to_json_test_Latn.CNH_Sans_12.json" 2>&1
Latn.CNH_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.CNH/Sans_16/pdf_to_json_test_Latn.CNH_Sans_16.py" > "data/multilingual/Latn.CNH/Sans_16/pdf_to_json_test_Latn.CNH_Sans_16.json" 2>&1
Latn.CNH_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.CNH/Sans_8/pdf_to_json_test_Latn.CNH_Sans_8.py" > "data/multilingual/Latn.CNH/Sans_8/pdf_to_json_test_Latn.CNH_Sans_8.json" 2>&1
Latn.CNH_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.CNH/Serif_12/pdf_to_json_test_Latn.CNH_Serif_12.py" > "data/multilingual/Latn.CNH/Serif_12/pdf_to_json_test_Latn.CNH_Serif_12.json" 2>&1
Latn.CNH_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.CNH/Serif_16/pdf_to_json_test_Latn.CNH_Serif_16.py" > "data/multilingual/Latn.CNH/Serif_16/pdf_to_json_test_Latn.CNH_Serif_16.json" 2>&1
Latn.CNH_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.CNH/Serif_8/pdf_to_json_test_Latn.CNH_Serif_8.py" > "data/multilingual/Latn.CNH/Serif_8/pdf_to_json_test_Latn.CNH_Serif_8.json" 2>&1
Latn.CNH_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.CNH/Sun-ExtA_12/pdf_to_json_test_Latn.CNH_Sun-ExtA_12.py" > "data/multilingual/Latn.CNH/Sun-ExtA_12/pdf_to_json_test_Latn.CNH_Sun-ExtA_12.json" 2>&1
Latn.CNH_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.CNH/Sun-ExtA_16/pdf_to_json_test_Latn.CNH_Sun-ExtA_16.py" > "data/multilingual/Latn.CNH/Sun-ExtA_16/pdf_to_json_test_Latn.CNH_Sun-ExtA_16.json" 2>&1
Latn.CNH_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.CNH/Sun-ExtA_8/pdf_to_json_test_Latn.CNH_Sun-ExtA_8.py" > "data/multilingual/Latn.CNH/Sun-ExtA_8/pdf_to_json_test_Latn.CNH_Sun-ExtA_8.json" 2>&1


Latn.CNH_all : Latn.CNH_Mono_12 Latn.CNH_Mono_16 Latn.CNH_Mono_8 Latn.CNH_Sans_12 Latn.CNH_Sans_16 Latn.CNH_Sans_8 Latn.CNH_Serif_12 Latn.CNH_Serif_16 Latn.CNH_Serif_8 Latn.CNH_Sun-ExtA_12 Latn.CNH_Sun-ExtA_16 Latn.CNH_Sun-ExtA_8
