PYTHON=python3


Latn.ISL_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.ISL/Mono_12/pdf_to_json_test_Latn.ISL_Mono_12.py" > "data/multilingual/Latn.ISL/Mono_12/pdf_to_json_test_Latn.ISL_Mono_12.json" 2>&1
Latn.ISL_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.ISL/Mono_16/pdf_to_json_test_Latn.ISL_Mono_16.py" > "data/multilingual/Latn.ISL/Mono_16/pdf_to_json_test_Latn.ISL_Mono_16.json" 2>&1
Latn.ISL_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.ISL/Mono_8/pdf_to_json_test_Latn.ISL_Mono_8.py" > "data/multilingual/Latn.ISL/Mono_8/pdf_to_json_test_Latn.ISL_Mono_8.json" 2>&1
Latn.ISL_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.ISL/Sans_12/pdf_to_json_test_Latn.ISL_Sans_12.py" > "data/multilingual/Latn.ISL/Sans_12/pdf_to_json_test_Latn.ISL_Sans_12.json" 2>&1
Latn.ISL_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.ISL/Sans_16/pdf_to_json_test_Latn.ISL_Sans_16.py" > "data/multilingual/Latn.ISL/Sans_16/pdf_to_json_test_Latn.ISL_Sans_16.json" 2>&1
Latn.ISL_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.ISL/Sans_8/pdf_to_json_test_Latn.ISL_Sans_8.py" > "data/multilingual/Latn.ISL/Sans_8/pdf_to_json_test_Latn.ISL_Sans_8.json" 2>&1
Latn.ISL_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.ISL/Serif_12/pdf_to_json_test_Latn.ISL_Serif_12.py" > "data/multilingual/Latn.ISL/Serif_12/pdf_to_json_test_Latn.ISL_Serif_12.json" 2>&1
Latn.ISL_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.ISL/Serif_16/pdf_to_json_test_Latn.ISL_Serif_16.py" > "data/multilingual/Latn.ISL/Serif_16/pdf_to_json_test_Latn.ISL_Serif_16.json" 2>&1
Latn.ISL_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.ISL/Serif_8/pdf_to_json_test_Latn.ISL_Serif_8.py" > "data/multilingual/Latn.ISL/Serif_8/pdf_to_json_test_Latn.ISL_Serif_8.json" 2>&1
Latn.ISL_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.ISL/Sun-ExtA_12/pdf_to_json_test_Latn.ISL_Sun-ExtA_12.py" > "data/multilingual/Latn.ISL/Sun-ExtA_12/pdf_to_json_test_Latn.ISL_Sun-ExtA_12.json" 2>&1
Latn.ISL_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.ISL/Sun-ExtA_16/pdf_to_json_test_Latn.ISL_Sun-ExtA_16.py" > "data/multilingual/Latn.ISL/Sun-ExtA_16/pdf_to_json_test_Latn.ISL_Sun-ExtA_16.json" 2>&1
Latn.ISL_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.ISL/Sun-ExtA_8/pdf_to_json_test_Latn.ISL_Sun-ExtA_8.py" > "data/multilingual/Latn.ISL/Sun-ExtA_8/pdf_to_json_test_Latn.ISL_Sun-ExtA_8.json" 2>&1


Latn.ISL_all : Latn.ISL_Mono_12 Latn.ISL_Mono_16 Latn.ISL_Mono_8 Latn.ISL_Sans_12 Latn.ISL_Sans_16 Latn.ISL_Sans_8 Latn.ISL_Serif_12 Latn.ISL_Serif_16 Latn.ISL_Serif_8 Latn.ISL_Sun-ExtA_12 Latn.ISL_Sun-ExtA_16 Latn.ISL_Sun-ExtA_8
