PYTHON=python3


Latn.IBB_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.IBB/Mono_12/pdf_to_json_test_Latn.IBB_Mono_12.py" > "data/multilingual/Latn.IBB/Mono_12/pdf_to_json_test_Latn.IBB_Mono_12.json" 2>&1
Latn.IBB_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.IBB/Mono_16/pdf_to_json_test_Latn.IBB_Mono_16.py" > "data/multilingual/Latn.IBB/Mono_16/pdf_to_json_test_Latn.IBB_Mono_16.json" 2>&1
Latn.IBB_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.IBB/Mono_8/pdf_to_json_test_Latn.IBB_Mono_8.py" > "data/multilingual/Latn.IBB/Mono_8/pdf_to_json_test_Latn.IBB_Mono_8.json" 2>&1
Latn.IBB_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.IBB/Sans_12/pdf_to_json_test_Latn.IBB_Sans_12.py" > "data/multilingual/Latn.IBB/Sans_12/pdf_to_json_test_Latn.IBB_Sans_12.json" 2>&1
Latn.IBB_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.IBB/Sans_16/pdf_to_json_test_Latn.IBB_Sans_16.py" > "data/multilingual/Latn.IBB/Sans_16/pdf_to_json_test_Latn.IBB_Sans_16.json" 2>&1
Latn.IBB_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.IBB/Sans_8/pdf_to_json_test_Latn.IBB_Sans_8.py" > "data/multilingual/Latn.IBB/Sans_8/pdf_to_json_test_Latn.IBB_Sans_8.json" 2>&1
Latn.IBB_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.IBB/Serif_12/pdf_to_json_test_Latn.IBB_Serif_12.py" > "data/multilingual/Latn.IBB/Serif_12/pdf_to_json_test_Latn.IBB_Serif_12.json" 2>&1
Latn.IBB_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.IBB/Serif_16/pdf_to_json_test_Latn.IBB_Serif_16.py" > "data/multilingual/Latn.IBB/Serif_16/pdf_to_json_test_Latn.IBB_Serif_16.json" 2>&1
Latn.IBB_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.IBB/Serif_8/pdf_to_json_test_Latn.IBB_Serif_8.py" > "data/multilingual/Latn.IBB/Serif_8/pdf_to_json_test_Latn.IBB_Serif_8.json" 2>&1
Latn.IBB_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.IBB/Sun-ExtA_12/pdf_to_json_test_Latn.IBB_Sun-ExtA_12.py" > "data/multilingual/Latn.IBB/Sun-ExtA_12/pdf_to_json_test_Latn.IBB_Sun-ExtA_12.json" 2>&1
Latn.IBB_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.IBB/Sun-ExtA_16/pdf_to_json_test_Latn.IBB_Sun-ExtA_16.py" > "data/multilingual/Latn.IBB/Sun-ExtA_16/pdf_to_json_test_Latn.IBB_Sun-ExtA_16.json" 2>&1
Latn.IBB_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.IBB/Sun-ExtA_8/pdf_to_json_test_Latn.IBB_Sun-ExtA_8.py" > "data/multilingual/Latn.IBB/Sun-ExtA_8/pdf_to_json_test_Latn.IBB_Sun-ExtA_8.json" 2>&1


Latn.IBB_all : Latn.IBB_Mono_12 Latn.IBB_Mono_16 Latn.IBB_Mono_8 Latn.IBB_Sans_12 Latn.IBB_Sans_16 Latn.IBB_Sans_8 Latn.IBB_Serif_12 Latn.IBB_Serif_16 Latn.IBB_Serif_8 Latn.IBB_Sun-ExtA_12 Latn.IBB_Sun-ExtA_16 Latn.IBB_Sun-ExtA_8
