PYTHON=python3


Geor.KAT_Mono_12:
	-$(PYTHON) data/multilingual/Geor.KAT/Mono_12/pdf_to_json_test_Geor.KAT_Mono_12.py > data/multilingual/Geor.KAT/Mono_12/pdf_to_json_test_Geor.KAT_Mono_12.json 2>&1
Geor.KAT_Mono_16:
	-$(PYTHON) data/multilingual/Geor.KAT/Mono_16/pdf_to_json_test_Geor.KAT_Mono_16.py > data/multilingual/Geor.KAT/Mono_16/pdf_to_json_test_Geor.KAT_Mono_16.json 2>&1
Geor.KAT_Mono_8:
	-$(PYTHON) data/multilingual/Geor.KAT/Mono_8/pdf_to_json_test_Geor.KAT_Mono_8.py > data/multilingual/Geor.KAT/Mono_8/pdf_to_json_test_Geor.KAT_Mono_8.json 2>&1
Geor.KAT_Sans_12:
	-$(PYTHON) data/multilingual/Geor.KAT/Sans_12/pdf_to_json_test_Geor.KAT_Sans_12.py > data/multilingual/Geor.KAT/Sans_12/pdf_to_json_test_Geor.KAT_Sans_12.json 2>&1
Geor.KAT_Sans_16:
	-$(PYTHON) data/multilingual/Geor.KAT/Sans_16/pdf_to_json_test_Geor.KAT_Sans_16.py > data/multilingual/Geor.KAT/Sans_16/pdf_to_json_test_Geor.KAT_Sans_16.json 2>&1
Geor.KAT_Sans_8:
	-$(PYTHON) data/multilingual/Geor.KAT/Sans_8/pdf_to_json_test_Geor.KAT_Sans_8.py > data/multilingual/Geor.KAT/Sans_8/pdf_to_json_test_Geor.KAT_Sans_8.json 2>&1
Geor.KAT_Serif_12:
	-$(PYTHON) data/multilingual/Geor.KAT/Serif_12/pdf_to_json_test_Geor.KAT_Serif_12.py > data/multilingual/Geor.KAT/Serif_12/pdf_to_json_test_Geor.KAT_Serif_12.json 2>&1
Geor.KAT_Serif_16:
	-$(PYTHON) data/multilingual/Geor.KAT/Serif_16/pdf_to_json_test_Geor.KAT_Serif_16.py > data/multilingual/Geor.KAT/Serif_16/pdf_to_json_test_Geor.KAT_Serif_16.json 2>&1
Geor.KAT_Serif_8:
	-$(PYTHON) data/multilingual/Geor.KAT/Serif_8/pdf_to_json_test_Geor.KAT_Serif_8.py > data/multilingual/Geor.KAT/Serif_8/pdf_to_json_test_Geor.KAT_Serif_8.json 2>&1
Geor.KAT_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Geor.KAT/Sun-ExtA_12/pdf_to_json_test_Geor.KAT_Sun-ExtA_12.py > data/multilingual/Geor.KAT/Sun-ExtA_12/pdf_to_json_test_Geor.KAT_Sun-ExtA_12.json 2>&1
Geor.KAT_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Geor.KAT/Sun-ExtA_16/pdf_to_json_test_Geor.KAT_Sun-ExtA_16.py > data/multilingual/Geor.KAT/Sun-ExtA_16/pdf_to_json_test_Geor.KAT_Sun-ExtA_16.json 2>&1
Geor.KAT_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Geor.KAT/Sun-ExtA_8/pdf_to_json_test_Geor.KAT_Sun-ExtA_8.py > data/multilingual/Geor.KAT/Sun-ExtA_8/pdf_to_json_test_Geor.KAT_Sun-ExtA_8.json 2>&1


Geor.KAT_all : Geor.KAT_Mono_12 Geor.KAT_Mono_16 Geor.KAT_Mono_8 Geor.KAT_Sans_12 Geor.KAT_Sans_16 Geor.KAT_Sans_8 Geor.KAT_Serif_12 Geor.KAT_Serif_16 Geor.KAT_Serif_8 Geor.KAT_Sun-ExtA_12 Geor.KAT_Sun-ExtA_16 Geor.KAT_Sun-ExtA_8
