PYTHON=python3


Latn.QXN_Mono_12:
	-$(PYTHON) data/multilingual/Latn.QXN/Mono_12/pdf_to_json_test_Latn.QXN_Mono_12.py > data/multilingual/Latn.QXN/Mono_12/pdf_to_json_test_Latn.QXN_Mono_12.json 2>&1
Latn.QXN_Mono_16:
	-$(PYTHON) data/multilingual/Latn.QXN/Mono_16/pdf_to_json_test_Latn.QXN_Mono_16.py > data/multilingual/Latn.QXN/Mono_16/pdf_to_json_test_Latn.QXN_Mono_16.json 2>&1
Latn.QXN_Mono_8:
	-$(PYTHON) data/multilingual/Latn.QXN/Mono_8/pdf_to_json_test_Latn.QXN_Mono_8.py > data/multilingual/Latn.QXN/Mono_8/pdf_to_json_test_Latn.QXN_Mono_8.json 2>&1
Latn.QXN_Sans_12:
	-$(PYTHON) data/multilingual/Latn.QXN/Sans_12/pdf_to_json_test_Latn.QXN_Sans_12.py > data/multilingual/Latn.QXN/Sans_12/pdf_to_json_test_Latn.QXN_Sans_12.json 2>&1
Latn.QXN_Sans_16:
	-$(PYTHON) data/multilingual/Latn.QXN/Sans_16/pdf_to_json_test_Latn.QXN_Sans_16.py > data/multilingual/Latn.QXN/Sans_16/pdf_to_json_test_Latn.QXN_Sans_16.json 2>&1
Latn.QXN_Sans_8:
	-$(PYTHON) data/multilingual/Latn.QXN/Sans_8/pdf_to_json_test_Latn.QXN_Sans_8.py > data/multilingual/Latn.QXN/Sans_8/pdf_to_json_test_Latn.QXN_Sans_8.json 2>&1
Latn.QXN_Serif_12:
	-$(PYTHON) data/multilingual/Latn.QXN/Serif_12/pdf_to_json_test_Latn.QXN_Serif_12.py > data/multilingual/Latn.QXN/Serif_12/pdf_to_json_test_Latn.QXN_Serif_12.json 2>&1
Latn.QXN_Serif_16:
	-$(PYTHON) data/multilingual/Latn.QXN/Serif_16/pdf_to_json_test_Latn.QXN_Serif_16.py > data/multilingual/Latn.QXN/Serif_16/pdf_to_json_test_Latn.QXN_Serif_16.json 2>&1
Latn.QXN_Serif_8:
	-$(PYTHON) data/multilingual/Latn.QXN/Serif_8/pdf_to_json_test_Latn.QXN_Serif_8.py > data/multilingual/Latn.QXN/Serif_8/pdf_to_json_test_Latn.QXN_Serif_8.json 2>&1
Latn.QXN_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.QXN/Sun-ExtA_12/pdf_to_json_test_Latn.QXN_Sun-ExtA_12.py > data/multilingual/Latn.QXN/Sun-ExtA_12/pdf_to_json_test_Latn.QXN_Sun-ExtA_12.json 2>&1
Latn.QXN_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.QXN/Sun-ExtA_16/pdf_to_json_test_Latn.QXN_Sun-ExtA_16.py > data/multilingual/Latn.QXN/Sun-ExtA_16/pdf_to_json_test_Latn.QXN_Sun-ExtA_16.json 2>&1
Latn.QXN_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.QXN/Sun-ExtA_8/pdf_to_json_test_Latn.QXN_Sun-ExtA_8.py > data/multilingual/Latn.QXN/Sun-ExtA_8/pdf_to_json_test_Latn.QXN_Sun-ExtA_8.json 2>&1


Latn.QXN_all : Latn.QXN_Mono_12 Latn.QXN_Mono_16 Latn.QXN_Mono_8 Latn.QXN_Sans_12 Latn.QXN_Sans_16 Latn.QXN_Sans_8 Latn.QXN_Serif_12 Latn.QXN_Serif_16 Latn.QXN_Serif_8 Latn.QXN_Sun-ExtA_12 Latn.QXN_Sun-ExtA_16 Latn.QXN_Sun-ExtA_8
