PYTHON=python3


Latn.ALS_Mono_12:
	-$(PYTHON) data/multilingual/Latn.ALS/Mono_12/pdf_to_json_test_Latn.ALS_Mono_12.py > data/multilingual/Latn.ALS/Mono_12/pdf_to_json_test_Latn.ALS_Mono_12.json 2>&1
Latn.ALS_Mono_16:
	-$(PYTHON) data/multilingual/Latn.ALS/Mono_16/pdf_to_json_test_Latn.ALS_Mono_16.py > data/multilingual/Latn.ALS/Mono_16/pdf_to_json_test_Latn.ALS_Mono_16.json 2>&1
Latn.ALS_Mono_8:
	-$(PYTHON) data/multilingual/Latn.ALS/Mono_8/pdf_to_json_test_Latn.ALS_Mono_8.py > data/multilingual/Latn.ALS/Mono_8/pdf_to_json_test_Latn.ALS_Mono_8.json 2>&1
Latn.ALS_Sans_12:
	-$(PYTHON) data/multilingual/Latn.ALS/Sans_12/pdf_to_json_test_Latn.ALS_Sans_12.py > data/multilingual/Latn.ALS/Sans_12/pdf_to_json_test_Latn.ALS_Sans_12.json 2>&1
Latn.ALS_Sans_16:
	-$(PYTHON) data/multilingual/Latn.ALS/Sans_16/pdf_to_json_test_Latn.ALS_Sans_16.py > data/multilingual/Latn.ALS/Sans_16/pdf_to_json_test_Latn.ALS_Sans_16.json 2>&1
Latn.ALS_Sans_8:
	-$(PYTHON) data/multilingual/Latn.ALS/Sans_8/pdf_to_json_test_Latn.ALS_Sans_8.py > data/multilingual/Latn.ALS/Sans_8/pdf_to_json_test_Latn.ALS_Sans_8.json 2>&1
Latn.ALS_Serif_12:
	-$(PYTHON) data/multilingual/Latn.ALS/Serif_12/pdf_to_json_test_Latn.ALS_Serif_12.py > data/multilingual/Latn.ALS/Serif_12/pdf_to_json_test_Latn.ALS_Serif_12.json 2>&1
Latn.ALS_Serif_16:
	-$(PYTHON) data/multilingual/Latn.ALS/Serif_16/pdf_to_json_test_Latn.ALS_Serif_16.py > data/multilingual/Latn.ALS/Serif_16/pdf_to_json_test_Latn.ALS_Serif_16.json 2>&1
Latn.ALS_Serif_8:
	-$(PYTHON) data/multilingual/Latn.ALS/Serif_8/pdf_to_json_test_Latn.ALS_Serif_8.py > data/multilingual/Latn.ALS/Serif_8/pdf_to_json_test_Latn.ALS_Serif_8.json 2>&1
Latn.ALS_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.ALS/Sun-ExtA_12/pdf_to_json_test_Latn.ALS_Sun-ExtA_12.py > data/multilingual/Latn.ALS/Sun-ExtA_12/pdf_to_json_test_Latn.ALS_Sun-ExtA_12.json 2>&1
Latn.ALS_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.ALS/Sun-ExtA_16/pdf_to_json_test_Latn.ALS_Sun-ExtA_16.py > data/multilingual/Latn.ALS/Sun-ExtA_16/pdf_to_json_test_Latn.ALS_Sun-ExtA_16.json 2>&1
Latn.ALS_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.ALS/Sun-ExtA_8/pdf_to_json_test_Latn.ALS_Sun-ExtA_8.py > data/multilingual/Latn.ALS/Sun-ExtA_8/pdf_to_json_test_Latn.ALS_Sun-ExtA_8.json 2>&1


Latn.ALS_all : Latn.ALS_Mono_12 Latn.ALS_Mono_16 Latn.ALS_Mono_8 Latn.ALS_Sans_12 Latn.ALS_Sans_16 Latn.ALS_Sans_8 Latn.ALS_Serif_12 Latn.ALS_Serif_16 Latn.ALS_Serif_8 Latn.ALS_Sun-ExtA_12 Latn.ALS_Sun-ExtA_16 Latn.ALS_Sun-ExtA_8
