PYTHON=python3


Mong.KHK_Mono_12:
	-$(PYTHON) "data/multilingual/Mong.KHK/Mono_12/pdf_to_json_test_Mong.KHK_Mono_12.py" > "data/multilingual/Mong.KHK/Mono_12/pdf_to_json_test_Mong.KHK_Mono_12.json" 2>&1
Mong.KHK_Mono_16:
	-$(PYTHON) "data/multilingual/Mong.KHK/Mono_16/pdf_to_json_test_Mong.KHK_Mono_16.py" > "data/multilingual/Mong.KHK/Mono_16/pdf_to_json_test_Mong.KHK_Mono_16.json" 2>&1
Mong.KHK_Mono_8:
	-$(PYTHON) "data/multilingual/Mong.KHK/Mono_8/pdf_to_json_test_Mong.KHK_Mono_8.py" > "data/multilingual/Mong.KHK/Mono_8/pdf_to_json_test_Mong.KHK_Mono_8.json" 2>&1
Mong.KHK_Sans_12:
	-$(PYTHON) "data/multilingual/Mong.KHK/Sans_12/pdf_to_json_test_Mong.KHK_Sans_12.py" > "data/multilingual/Mong.KHK/Sans_12/pdf_to_json_test_Mong.KHK_Sans_12.json" 2>&1
Mong.KHK_Sans_16:
	-$(PYTHON) "data/multilingual/Mong.KHK/Sans_16/pdf_to_json_test_Mong.KHK_Sans_16.py" > "data/multilingual/Mong.KHK/Sans_16/pdf_to_json_test_Mong.KHK_Sans_16.json" 2>&1
Mong.KHK_Sans_8:
	-$(PYTHON) "data/multilingual/Mong.KHK/Sans_8/pdf_to_json_test_Mong.KHK_Sans_8.py" > "data/multilingual/Mong.KHK/Sans_8/pdf_to_json_test_Mong.KHK_Sans_8.json" 2>&1
Mong.KHK_Serif_12:
	-$(PYTHON) "data/multilingual/Mong.KHK/Serif_12/pdf_to_json_test_Mong.KHK_Serif_12.py" > "data/multilingual/Mong.KHK/Serif_12/pdf_to_json_test_Mong.KHK_Serif_12.json" 2>&1
Mong.KHK_Serif_16:
	-$(PYTHON) "data/multilingual/Mong.KHK/Serif_16/pdf_to_json_test_Mong.KHK_Serif_16.py" > "data/multilingual/Mong.KHK/Serif_16/pdf_to_json_test_Mong.KHK_Serif_16.json" 2>&1
Mong.KHK_Serif_8:
	-$(PYTHON) "data/multilingual/Mong.KHK/Serif_8/pdf_to_json_test_Mong.KHK_Serif_8.py" > "data/multilingual/Mong.KHK/Serif_8/pdf_to_json_test_Mong.KHK_Serif_8.json" 2>&1
Mong.KHK_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Mong.KHK/Sun-ExtA_12/pdf_to_json_test_Mong.KHK_Sun-ExtA_12.py" > "data/multilingual/Mong.KHK/Sun-ExtA_12/pdf_to_json_test_Mong.KHK_Sun-ExtA_12.json" 2>&1
Mong.KHK_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Mong.KHK/Sun-ExtA_16/pdf_to_json_test_Mong.KHK_Sun-ExtA_16.py" > "data/multilingual/Mong.KHK/Sun-ExtA_16/pdf_to_json_test_Mong.KHK_Sun-ExtA_16.json" 2>&1
Mong.KHK_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Mong.KHK/Sun-ExtA_8/pdf_to_json_test_Mong.KHK_Sun-ExtA_8.py" > "data/multilingual/Mong.KHK/Sun-ExtA_8/pdf_to_json_test_Mong.KHK_Sun-ExtA_8.json" 2>&1


Mong.KHK_all : Mong.KHK_Mono_12 Mong.KHK_Mono_16 Mong.KHK_Mono_8 Mong.KHK_Sans_12 Mong.KHK_Sans_16 Mong.KHK_Sans_8 Mong.KHK_Serif_12 Mong.KHK_Serif_16 Mong.KHK_Serif_8 Mong.KHK_Sun-ExtA_12 Mong.KHK_Sun-ExtA_16 Mong.KHK_Sun-ExtA_8
