PYTHON=python3


Cyrl.YKG_Mono_12:
	-$(PYTHON) data/multilingual/Cyrl.YKG/Mono_12/pdf_to_json_test_Cyrl.YKG_Mono_12.py > data/multilingual/Cyrl.YKG/Mono_12/pdf_to_json_test_Cyrl.YKG_Mono_12.json 2>&1
Cyrl.YKG_Mono_16:
	-$(PYTHON) data/multilingual/Cyrl.YKG/Mono_16/pdf_to_json_test_Cyrl.YKG_Mono_16.py > data/multilingual/Cyrl.YKG/Mono_16/pdf_to_json_test_Cyrl.YKG_Mono_16.json 2>&1
Cyrl.YKG_Mono_8:
	-$(PYTHON) data/multilingual/Cyrl.YKG/Mono_8/pdf_to_json_test_Cyrl.YKG_Mono_8.py > data/multilingual/Cyrl.YKG/Mono_8/pdf_to_json_test_Cyrl.YKG_Mono_8.json 2>&1
Cyrl.YKG_Sans_12:
	-$(PYTHON) data/multilingual/Cyrl.YKG/Sans_12/pdf_to_json_test_Cyrl.YKG_Sans_12.py > data/multilingual/Cyrl.YKG/Sans_12/pdf_to_json_test_Cyrl.YKG_Sans_12.json 2>&1
Cyrl.YKG_Sans_16:
	-$(PYTHON) data/multilingual/Cyrl.YKG/Sans_16/pdf_to_json_test_Cyrl.YKG_Sans_16.py > data/multilingual/Cyrl.YKG/Sans_16/pdf_to_json_test_Cyrl.YKG_Sans_16.json 2>&1
Cyrl.YKG_Sans_8:
	-$(PYTHON) data/multilingual/Cyrl.YKG/Sans_8/pdf_to_json_test_Cyrl.YKG_Sans_8.py > data/multilingual/Cyrl.YKG/Sans_8/pdf_to_json_test_Cyrl.YKG_Sans_8.json 2>&1
Cyrl.YKG_Serif_12:
	-$(PYTHON) data/multilingual/Cyrl.YKG/Serif_12/pdf_to_json_test_Cyrl.YKG_Serif_12.py > data/multilingual/Cyrl.YKG/Serif_12/pdf_to_json_test_Cyrl.YKG_Serif_12.json 2>&1
Cyrl.YKG_Serif_16:
	-$(PYTHON) data/multilingual/Cyrl.YKG/Serif_16/pdf_to_json_test_Cyrl.YKG_Serif_16.py > data/multilingual/Cyrl.YKG/Serif_16/pdf_to_json_test_Cyrl.YKG_Serif_16.json 2>&1
Cyrl.YKG_Serif_8:
	-$(PYTHON) data/multilingual/Cyrl.YKG/Serif_8/pdf_to_json_test_Cyrl.YKG_Serif_8.py > data/multilingual/Cyrl.YKG/Serif_8/pdf_to_json_test_Cyrl.YKG_Serif_8.json 2>&1
Cyrl.YKG_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Cyrl.YKG/Sun-ExtA_12/pdf_to_json_test_Cyrl.YKG_Sun-ExtA_12.py > data/multilingual/Cyrl.YKG/Sun-ExtA_12/pdf_to_json_test_Cyrl.YKG_Sun-ExtA_12.json 2>&1
Cyrl.YKG_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Cyrl.YKG/Sun-ExtA_16/pdf_to_json_test_Cyrl.YKG_Sun-ExtA_16.py > data/multilingual/Cyrl.YKG/Sun-ExtA_16/pdf_to_json_test_Cyrl.YKG_Sun-ExtA_16.json 2>&1
Cyrl.YKG_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Cyrl.YKG/Sun-ExtA_8/pdf_to_json_test_Cyrl.YKG_Sun-ExtA_8.py > data/multilingual/Cyrl.YKG/Sun-ExtA_8/pdf_to_json_test_Cyrl.YKG_Sun-ExtA_8.json 2>&1


Cyrl.YKG_all : Cyrl.YKG_Mono_12 Cyrl.YKG_Mono_16 Cyrl.YKG_Mono_8 Cyrl.YKG_Sans_12 Cyrl.YKG_Sans_16 Cyrl.YKG_Sans_8 Cyrl.YKG_Serif_12 Cyrl.YKG_Serif_16 Cyrl.YKG_Serif_8 Cyrl.YKG_Sun-ExtA_12 Cyrl.YKG_Sun-ExtA_16 Cyrl.YKG_Sun-ExtA_8
