PYTHON=python3


Latn.QVN_Mono_12:
	-$(PYTHON) data/multilingual/Latn.QVN/Mono_12/pdf_to_json_test_Latn.QVN_Mono_12.py > data/multilingual/Latn.QVN/Mono_12/pdf_to_json_test_Latn.QVN_Mono_12.json 2>&1
Latn.QVN_Mono_16:
	-$(PYTHON) data/multilingual/Latn.QVN/Mono_16/pdf_to_json_test_Latn.QVN_Mono_16.py > data/multilingual/Latn.QVN/Mono_16/pdf_to_json_test_Latn.QVN_Mono_16.json 2>&1
Latn.QVN_Mono_8:
	-$(PYTHON) data/multilingual/Latn.QVN/Mono_8/pdf_to_json_test_Latn.QVN_Mono_8.py > data/multilingual/Latn.QVN/Mono_8/pdf_to_json_test_Latn.QVN_Mono_8.json 2>&1
Latn.QVN_Sans_12:
	-$(PYTHON) data/multilingual/Latn.QVN/Sans_12/pdf_to_json_test_Latn.QVN_Sans_12.py > data/multilingual/Latn.QVN/Sans_12/pdf_to_json_test_Latn.QVN_Sans_12.json 2>&1
Latn.QVN_Sans_16:
	-$(PYTHON) data/multilingual/Latn.QVN/Sans_16/pdf_to_json_test_Latn.QVN_Sans_16.py > data/multilingual/Latn.QVN/Sans_16/pdf_to_json_test_Latn.QVN_Sans_16.json 2>&1
Latn.QVN_Sans_8:
	-$(PYTHON) data/multilingual/Latn.QVN/Sans_8/pdf_to_json_test_Latn.QVN_Sans_8.py > data/multilingual/Latn.QVN/Sans_8/pdf_to_json_test_Latn.QVN_Sans_8.json 2>&1
Latn.QVN_Serif_12:
	-$(PYTHON) data/multilingual/Latn.QVN/Serif_12/pdf_to_json_test_Latn.QVN_Serif_12.py > data/multilingual/Latn.QVN/Serif_12/pdf_to_json_test_Latn.QVN_Serif_12.json 2>&1
Latn.QVN_Serif_16:
	-$(PYTHON) data/multilingual/Latn.QVN/Serif_16/pdf_to_json_test_Latn.QVN_Serif_16.py > data/multilingual/Latn.QVN/Serif_16/pdf_to_json_test_Latn.QVN_Serif_16.json 2>&1
Latn.QVN_Serif_8:
	-$(PYTHON) data/multilingual/Latn.QVN/Serif_8/pdf_to_json_test_Latn.QVN_Serif_8.py > data/multilingual/Latn.QVN/Serif_8/pdf_to_json_test_Latn.QVN_Serif_8.json 2>&1
Latn.QVN_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.QVN/Sun-ExtA_12/pdf_to_json_test_Latn.QVN_Sun-ExtA_12.py > data/multilingual/Latn.QVN/Sun-ExtA_12/pdf_to_json_test_Latn.QVN_Sun-ExtA_12.json 2>&1
Latn.QVN_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.QVN/Sun-ExtA_16/pdf_to_json_test_Latn.QVN_Sun-ExtA_16.py > data/multilingual/Latn.QVN/Sun-ExtA_16/pdf_to_json_test_Latn.QVN_Sun-ExtA_16.json 2>&1
Latn.QVN_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.QVN/Sun-ExtA_8/pdf_to_json_test_Latn.QVN_Sun-ExtA_8.py > data/multilingual/Latn.QVN/Sun-ExtA_8/pdf_to_json_test_Latn.QVN_Sun-ExtA_8.json 2>&1


Latn.QVN_all : Latn.QVN_Mono_12 Latn.QVN_Mono_16 Latn.QVN_Mono_8 Latn.QVN_Sans_12 Latn.QVN_Sans_16 Latn.QVN_Sans_8 Latn.QVN_Serif_12 Latn.QVN_Serif_16 Latn.QVN_Serif_8 Latn.QVN_Sun-ExtA_12 Latn.QVN_Sun-ExtA_16 Latn.QVN_Sun-ExtA_8
