PYTHON=python3


Cyrl.TUK_Mono_12:
	-$(PYTHON) data/multilingual/Cyrl.TUK/Mono_12/pdf_to_json_test_Cyrl.TUK_Mono_12.py > data/multilingual/Cyrl.TUK/Mono_12/pdf_to_json_test_Cyrl.TUK_Mono_12.json 2>&1
Cyrl.TUK_Mono_16:
	-$(PYTHON) data/multilingual/Cyrl.TUK/Mono_16/pdf_to_json_test_Cyrl.TUK_Mono_16.py > data/multilingual/Cyrl.TUK/Mono_16/pdf_to_json_test_Cyrl.TUK_Mono_16.json 2>&1
Cyrl.TUK_Mono_8:
	-$(PYTHON) data/multilingual/Cyrl.TUK/Mono_8/pdf_to_json_test_Cyrl.TUK_Mono_8.py > data/multilingual/Cyrl.TUK/Mono_8/pdf_to_json_test_Cyrl.TUK_Mono_8.json 2>&1
Cyrl.TUK_Sans_12:
	-$(PYTHON) data/multilingual/Cyrl.TUK/Sans_12/pdf_to_json_test_Cyrl.TUK_Sans_12.py > data/multilingual/Cyrl.TUK/Sans_12/pdf_to_json_test_Cyrl.TUK_Sans_12.json 2>&1
Cyrl.TUK_Sans_16:
	-$(PYTHON) data/multilingual/Cyrl.TUK/Sans_16/pdf_to_json_test_Cyrl.TUK_Sans_16.py > data/multilingual/Cyrl.TUK/Sans_16/pdf_to_json_test_Cyrl.TUK_Sans_16.json 2>&1
Cyrl.TUK_Sans_8:
	-$(PYTHON) data/multilingual/Cyrl.TUK/Sans_8/pdf_to_json_test_Cyrl.TUK_Sans_8.py > data/multilingual/Cyrl.TUK/Sans_8/pdf_to_json_test_Cyrl.TUK_Sans_8.json 2>&1
Cyrl.TUK_Serif_12:
	-$(PYTHON) data/multilingual/Cyrl.TUK/Serif_12/pdf_to_json_test_Cyrl.TUK_Serif_12.py > data/multilingual/Cyrl.TUK/Serif_12/pdf_to_json_test_Cyrl.TUK_Serif_12.json 2>&1
Cyrl.TUK_Serif_16:
	-$(PYTHON) data/multilingual/Cyrl.TUK/Serif_16/pdf_to_json_test_Cyrl.TUK_Serif_16.py > data/multilingual/Cyrl.TUK/Serif_16/pdf_to_json_test_Cyrl.TUK_Serif_16.json 2>&1
Cyrl.TUK_Serif_8:
	-$(PYTHON) data/multilingual/Cyrl.TUK/Serif_8/pdf_to_json_test_Cyrl.TUK_Serif_8.py > data/multilingual/Cyrl.TUK/Serif_8/pdf_to_json_test_Cyrl.TUK_Serif_8.json 2>&1
Cyrl.TUK_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Cyrl.TUK/Sun-ExtA_12/pdf_to_json_test_Cyrl.TUK_Sun-ExtA_12.py > data/multilingual/Cyrl.TUK/Sun-ExtA_12/pdf_to_json_test_Cyrl.TUK_Sun-ExtA_12.json 2>&1
Cyrl.TUK_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Cyrl.TUK/Sun-ExtA_16/pdf_to_json_test_Cyrl.TUK_Sun-ExtA_16.py > data/multilingual/Cyrl.TUK/Sun-ExtA_16/pdf_to_json_test_Cyrl.TUK_Sun-ExtA_16.json 2>&1
Cyrl.TUK_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Cyrl.TUK/Sun-ExtA_8/pdf_to_json_test_Cyrl.TUK_Sun-ExtA_8.py > data/multilingual/Cyrl.TUK/Sun-ExtA_8/pdf_to_json_test_Cyrl.TUK_Sun-ExtA_8.json 2>&1


Cyrl.TUK_all : Cyrl.TUK_Mono_12 Cyrl.TUK_Mono_16 Cyrl.TUK_Mono_8 Cyrl.TUK_Sans_12 Cyrl.TUK_Sans_16 Cyrl.TUK_Sans_8 Cyrl.TUK_Serif_12 Cyrl.TUK_Serif_16 Cyrl.TUK_Serif_8 Cyrl.TUK_Sun-ExtA_12 Cyrl.TUK_Sun-ExtA_16 Cyrl.TUK_Sun-ExtA_8
