PYTHON=python3


Deva.NPI_Mono_12:
	-$(PYTHON) data/multilingual/Deva.NPI/Mono_12/pdf_to_json_test_Deva.NPI_Mono_12.py > data/multilingual/Deva.NPI/Mono_12/pdf_to_json_test_Deva.NPI_Mono_12.json 2>&1
Deva.NPI_Mono_16:
	-$(PYTHON) data/multilingual/Deva.NPI/Mono_16/pdf_to_json_test_Deva.NPI_Mono_16.py > data/multilingual/Deva.NPI/Mono_16/pdf_to_json_test_Deva.NPI_Mono_16.json 2>&1
Deva.NPI_Mono_8:
	-$(PYTHON) data/multilingual/Deva.NPI/Mono_8/pdf_to_json_test_Deva.NPI_Mono_8.py > data/multilingual/Deva.NPI/Mono_8/pdf_to_json_test_Deva.NPI_Mono_8.json 2>&1
Deva.NPI_Sans_12:
	-$(PYTHON) data/multilingual/Deva.NPI/Sans_12/pdf_to_json_test_Deva.NPI_Sans_12.py > data/multilingual/Deva.NPI/Sans_12/pdf_to_json_test_Deva.NPI_Sans_12.json 2>&1
Deva.NPI_Sans_16:
	-$(PYTHON) data/multilingual/Deva.NPI/Sans_16/pdf_to_json_test_Deva.NPI_Sans_16.py > data/multilingual/Deva.NPI/Sans_16/pdf_to_json_test_Deva.NPI_Sans_16.json 2>&1
Deva.NPI_Sans_8:
	-$(PYTHON) data/multilingual/Deva.NPI/Sans_8/pdf_to_json_test_Deva.NPI_Sans_8.py > data/multilingual/Deva.NPI/Sans_8/pdf_to_json_test_Deva.NPI_Sans_8.json 2>&1
Deva.NPI_Serif_12:
	-$(PYTHON) data/multilingual/Deva.NPI/Serif_12/pdf_to_json_test_Deva.NPI_Serif_12.py > data/multilingual/Deva.NPI/Serif_12/pdf_to_json_test_Deva.NPI_Serif_12.json 2>&1
Deva.NPI_Serif_16:
	-$(PYTHON) data/multilingual/Deva.NPI/Serif_16/pdf_to_json_test_Deva.NPI_Serif_16.py > data/multilingual/Deva.NPI/Serif_16/pdf_to_json_test_Deva.NPI_Serif_16.json 2>&1
Deva.NPI_Serif_8:
	-$(PYTHON) data/multilingual/Deva.NPI/Serif_8/pdf_to_json_test_Deva.NPI_Serif_8.py > data/multilingual/Deva.NPI/Serif_8/pdf_to_json_test_Deva.NPI_Serif_8.json 2>&1
Deva.NPI_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Deva.NPI/Sun-ExtA_12/pdf_to_json_test_Deva.NPI_Sun-ExtA_12.py > data/multilingual/Deva.NPI/Sun-ExtA_12/pdf_to_json_test_Deva.NPI_Sun-ExtA_12.json 2>&1
Deva.NPI_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Deva.NPI/Sun-ExtA_16/pdf_to_json_test_Deva.NPI_Sun-ExtA_16.py > data/multilingual/Deva.NPI/Sun-ExtA_16/pdf_to_json_test_Deva.NPI_Sun-ExtA_16.json 2>&1
Deva.NPI_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Deva.NPI/Sun-ExtA_8/pdf_to_json_test_Deva.NPI_Sun-ExtA_8.py > data/multilingual/Deva.NPI/Sun-ExtA_8/pdf_to_json_test_Deva.NPI_Sun-ExtA_8.json 2>&1


Deva.NPI_all : Deva.NPI_Mono_12 Deva.NPI_Mono_16 Deva.NPI_Mono_8 Deva.NPI_Sans_12 Deva.NPI_Sans_16 Deva.NPI_Sans_8 Deva.NPI_Serif_12 Deva.NPI_Serif_16 Deva.NPI_Serif_8 Deva.NPI_Sun-ExtA_12 Deva.NPI_Sun-ExtA_16 Deva.NPI_Sun-ExtA_8
