PYTHON=python3


Latn.UMB_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.UMB/Mono_12/pdf_to_json_test_Latn.UMB_Mono_12.py" > "data/multilingual/Latn.UMB/Mono_12/pdf_to_json_test_Latn.UMB_Mono_12.json" 2>&1
Latn.UMB_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.UMB/Mono_16/pdf_to_json_test_Latn.UMB_Mono_16.py" > "data/multilingual/Latn.UMB/Mono_16/pdf_to_json_test_Latn.UMB_Mono_16.json" 2>&1
Latn.UMB_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.UMB/Mono_8/pdf_to_json_test_Latn.UMB_Mono_8.py" > "data/multilingual/Latn.UMB/Mono_8/pdf_to_json_test_Latn.UMB_Mono_8.json" 2>&1
Latn.UMB_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.UMB/Sans_12/pdf_to_json_test_Latn.UMB_Sans_12.py" > "data/multilingual/Latn.UMB/Sans_12/pdf_to_json_test_Latn.UMB_Sans_12.json" 2>&1
Latn.UMB_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.UMB/Sans_16/pdf_to_json_test_Latn.UMB_Sans_16.py" > "data/multilingual/Latn.UMB/Sans_16/pdf_to_json_test_Latn.UMB_Sans_16.json" 2>&1
Latn.UMB_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.UMB/Sans_8/pdf_to_json_test_Latn.UMB_Sans_8.py" > "data/multilingual/Latn.UMB/Sans_8/pdf_to_json_test_Latn.UMB_Sans_8.json" 2>&1
Latn.UMB_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.UMB/Serif_12/pdf_to_json_test_Latn.UMB_Serif_12.py" > "data/multilingual/Latn.UMB/Serif_12/pdf_to_json_test_Latn.UMB_Serif_12.json" 2>&1
Latn.UMB_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.UMB/Serif_16/pdf_to_json_test_Latn.UMB_Serif_16.py" > "data/multilingual/Latn.UMB/Serif_16/pdf_to_json_test_Latn.UMB_Serif_16.json" 2>&1
Latn.UMB_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.UMB/Serif_8/pdf_to_json_test_Latn.UMB_Serif_8.py" > "data/multilingual/Latn.UMB/Serif_8/pdf_to_json_test_Latn.UMB_Serif_8.json" 2>&1
Latn.UMB_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.UMB/Sun-ExtA_12/pdf_to_json_test_Latn.UMB_Sun-ExtA_12.py" > "data/multilingual/Latn.UMB/Sun-ExtA_12/pdf_to_json_test_Latn.UMB_Sun-ExtA_12.json" 2>&1
Latn.UMB_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.UMB/Sun-ExtA_16/pdf_to_json_test_Latn.UMB_Sun-ExtA_16.py" > "data/multilingual/Latn.UMB/Sun-ExtA_16/pdf_to_json_test_Latn.UMB_Sun-ExtA_16.json" 2>&1
Latn.UMB_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.UMB/Sun-ExtA_8/pdf_to_json_test_Latn.UMB_Sun-ExtA_8.py" > "data/multilingual/Latn.UMB/Sun-ExtA_8/pdf_to_json_test_Latn.UMB_Sun-ExtA_8.json" 2>&1


Latn.UMB_all : Latn.UMB_Mono_12 Latn.UMB_Mono_16 Latn.UMB_Mono_8 Latn.UMB_Sans_12 Latn.UMB_Sans_16 Latn.UMB_Sans_8 Latn.UMB_Serif_12 Latn.UMB_Serif_16 Latn.UMB_Serif_8 Latn.UMB_Sun-ExtA_12 Latn.UMB_Sun-ExtA_16 Latn.UMB_Sun-ExtA_8
