PYTHON=python3


Latn.NNO_Mono_12:
	-$(PYTHON) data/multilingual/Latn.NNO/Mono_12/pdf_to_json_test_Latn.NNO_Mono_12.py > data/multilingual/Latn.NNO/Mono_12/pdf_to_json_test_Latn.NNO_Mono_12.json 2>&1
Latn.NNO_Mono_16:
	-$(PYTHON) data/multilingual/Latn.NNO/Mono_16/pdf_to_json_test_Latn.NNO_Mono_16.py > data/multilingual/Latn.NNO/Mono_16/pdf_to_json_test_Latn.NNO_Mono_16.json 2>&1
Latn.NNO_Mono_8:
	-$(PYTHON) data/multilingual/Latn.NNO/Mono_8/pdf_to_json_test_Latn.NNO_Mono_8.py > data/multilingual/Latn.NNO/Mono_8/pdf_to_json_test_Latn.NNO_Mono_8.json 2>&1
Latn.NNO_Sans_12:
	-$(PYTHON) data/multilingual/Latn.NNO/Sans_12/pdf_to_json_test_Latn.NNO_Sans_12.py > data/multilingual/Latn.NNO/Sans_12/pdf_to_json_test_Latn.NNO_Sans_12.json 2>&1
Latn.NNO_Sans_16:
	-$(PYTHON) data/multilingual/Latn.NNO/Sans_16/pdf_to_json_test_Latn.NNO_Sans_16.py > data/multilingual/Latn.NNO/Sans_16/pdf_to_json_test_Latn.NNO_Sans_16.json 2>&1
Latn.NNO_Sans_8:
	-$(PYTHON) data/multilingual/Latn.NNO/Sans_8/pdf_to_json_test_Latn.NNO_Sans_8.py > data/multilingual/Latn.NNO/Sans_8/pdf_to_json_test_Latn.NNO_Sans_8.json 2>&1
Latn.NNO_Serif_12:
	-$(PYTHON) data/multilingual/Latn.NNO/Serif_12/pdf_to_json_test_Latn.NNO_Serif_12.py > data/multilingual/Latn.NNO/Serif_12/pdf_to_json_test_Latn.NNO_Serif_12.json 2>&1
Latn.NNO_Serif_16:
	-$(PYTHON) data/multilingual/Latn.NNO/Serif_16/pdf_to_json_test_Latn.NNO_Serif_16.py > data/multilingual/Latn.NNO/Serif_16/pdf_to_json_test_Latn.NNO_Serif_16.json 2>&1
Latn.NNO_Serif_8:
	-$(PYTHON) data/multilingual/Latn.NNO/Serif_8/pdf_to_json_test_Latn.NNO_Serif_8.py > data/multilingual/Latn.NNO/Serif_8/pdf_to_json_test_Latn.NNO_Serif_8.json 2>&1
Latn.NNO_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.NNO/Sun-ExtA_12/pdf_to_json_test_Latn.NNO_Sun-ExtA_12.py > data/multilingual/Latn.NNO/Sun-ExtA_12/pdf_to_json_test_Latn.NNO_Sun-ExtA_12.json 2>&1
Latn.NNO_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.NNO/Sun-ExtA_16/pdf_to_json_test_Latn.NNO_Sun-ExtA_16.py > data/multilingual/Latn.NNO/Sun-ExtA_16/pdf_to_json_test_Latn.NNO_Sun-ExtA_16.json 2>&1
Latn.NNO_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.NNO/Sun-ExtA_8/pdf_to_json_test_Latn.NNO_Sun-ExtA_8.py > data/multilingual/Latn.NNO/Sun-ExtA_8/pdf_to_json_test_Latn.NNO_Sun-ExtA_8.json 2>&1


Latn.NNO_all : Latn.NNO_Mono_12 Latn.NNO_Mono_16 Latn.NNO_Mono_8 Latn.NNO_Sans_12 Latn.NNO_Sans_16 Latn.NNO_Sans_8 Latn.NNO_Serif_12 Latn.NNO_Serif_16 Latn.NNO_Serif_8 Latn.NNO_Sun-ExtA_12 Latn.NNO_Sun-ExtA_16 Latn.NNO_Sun-ExtA_8
