PYTHON=python3


Latn.PON_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.PON/Mono_12/pdf_to_json_test_Latn.PON_Mono_12.py" > "data/multilingual/Latn.PON/Mono_12/pdf_to_json_test_Latn.PON_Mono_12.json" 2>&1
Latn.PON_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.PON/Mono_16/pdf_to_json_test_Latn.PON_Mono_16.py" > "data/multilingual/Latn.PON/Mono_16/pdf_to_json_test_Latn.PON_Mono_16.json" 2>&1
Latn.PON_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.PON/Mono_8/pdf_to_json_test_Latn.PON_Mono_8.py" > "data/multilingual/Latn.PON/Mono_8/pdf_to_json_test_Latn.PON_Mono_8.json" 2>&1
Latn.PON_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.PON/Sans_12/pdf_to_json_test_Latn.PON_Sans_12.py" > "data/multilingual/Latn.PON/Sans_12/pdf_to_json_test_Latn.PON_Sans_12.json" 2>&1
Latn.PON_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.PON/Sans_16/pdf_to_json_test_Latn.PON_Sans_16.py" > "data/multilingual/Latn.PON/Sans_16/pdf_to_json_test_Latn.PON_Sans_16.json" 2>&1
Latn.PON_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.PON/Sans_8/pdf_to_json_test_Latn.PON_Sans_8.py" > "data/multilingual/Latn.PON/Sans_8/pdf_to_json_test_Latn.PON_Sans_8.json" 2>&1
Latn.PON_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.PON/Serif_12/pdf_to_json_test_Latn.PON_Serif_12.py" > "data/multilingual/Latn.PON/Serif_12/pdf_to_json_test_Latn.PON_Serif_12.json" 2>&1
Latn.PON_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.PON/Serif_16/pdf_to_json_test_Latn.PON_Serif_16.py" > "data/multilingual/Latn.PON/Serif_16/pdf_to_json_test_Latn.PON_Serif_16.json" 2>&1
Latn.PON_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.PON/Serif_8/pdf_to_json_test_Latn.PON_Serif_8.py" > "data/multilingual/Latn.PON/Serif_8/pdf_to_json_test_Latn.PON_Serif_8.json" 2>&1
Latn.PON_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.PON/Sun-ExtA_12/pdf_to_json_test_Latn.PON_Sun-ExtA_12.py" > "data/multilingual/Latn.PON/Sun-ExtA_12/pdf_to_json_test_Latn.PON_Sun-ExtA_12.json" 2>&1
Latn.PON_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.PON/Sun-ExtA_16/pdf_to_json_test_Latn.PON_Sun-ExtA_16.py" > "data/multilingual/Latn.PON/Sun-ExtA_16/pdf_to_json_test_Latn.PON_Sun-ExtA_16.json" 2>&1
Latn.PON_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.PON/Sun-ExtA_8/pdf_to_json_test_Latn.PON_Sun-ExtA_8.py" > "data/multilingual/Latn.PON/Sun-ExtA_8/pdf_to_json_test_Latn.PON_Sun-ExtA_8.json" 2>&1


Latn.PON_all : Latn.PON_Mono_12 Latn.PON_Mono_16 Latn.PON_Mono_8 Latn.PON_Sans_12 Latn.PON_Sans_16 Latn.PON_Sans_8 Latn.PON_Serif_12 Latn.PON_Serif_16 Latn.PON_Serif_8 Latn.PON_Sun-ExtA_12 Latn.PON_Sun-ExtA_16 Latn.PON_Sun-ExtA_8
