PYTHON=python3


Latn.TEM_Mono_12:
	-$(PYTHON) data/multilingual/Latn.TEM/Mono_12/pdf_to_json_test_Latn.TEM_Mono_12.py > data/multilingual/Latn.TEM/Mono_12/pdf_to_json_test_Latn.TEM_Mono_12.json 2>&1
Latn.TEM_Mono_16:
	-$(PYTHON) data/multilingual/Latn.TEM/Mono_16/pdf_to_json_test_Latn.TEM_Mono_16.py > data/multilingual/Latn.TEM/Mono_16/pdf_to_json_test_Latn.TEM_Mono_16.json 2>&1
Latn.TEM_Mono_8:
	-$(PYTHON) data/multilingual/Latn.TEM/Mono_8/pdf_to_json_test_Latn.TEM_Mono_8.py > data/multilingual/Latn.TEM/Mono_8/pdf_to_json_test_Latn.TEM_Mono_8.json 2>&1
Latn.TEM_Sans_12:
	-$(PYTHON) data/multilingual/Latn.TEM/Sans_12/pdf_to_json_test_Latn.TEM_Sans_12.py > data/multilingual/Latn.TEM/Sans_12/pdf_to_json_test_Latn.TEM_Sans_12.json 2>&1
Latn.TEM_Sans_16:
	-$(PYTHON) data/multilingual/Latn.TEM/Sans_16/pdf_to_json_test_Latn.TEM_Sans_16.py > data/multilingual/Latn.TEM/Sans_16/pdf_to_json_test_Latn.TEM_Sans_16.json 2>&1
Latn.TEM_Sans_8:
	-$(PYTHON) data/multilingual/Latn.TEM/Sans_8/pdf_to_json_test_Latn.TEM_Sans_8.py > data/multilingual/Latn.TEM/Sans_8/pdf_to_json_test_Latn.TEM_Sans_8.json 2>&1
Latn.TEM_Serif_12:
	-$(PYTHON) data/multilingual/Latn.TEM/Serif_12/pdf_to_json_test_Latn.TEM_Serif_12.py > data/multilingual/Latn.TEM/Serif_12/pdf_to_json_test_Latn.TEM_Serif_12.json 2>&1
Latn.TEM_Serif_16:
	-$(PYTHON) data/multilingual/Latn.TEM/Serif_16/pdf_to_json_test_Latn.TEM_Serif_16.py > data/multilingual/Latn.TEM/Serif_16/pdf_to_json_test_Latn.TEM_Serif_16.json 2>&1
Latn.TEM_Serif_8:
	-$(PYTHON) data/multilingual/Latn.TEM/Serif_8/pdf_to_json_test_Latn.TEM_Serif_8.py > data/multilingual/Latn.TEM/Serif_8/pdf_to_json_test_Latn.TEM_Serif_8.json 2>&1
Latn.TEM_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.TEM/Sun-ExtA_12/pdf_to_json_test_Latn.TEM_Sun-ExtA_12.py > data/multilingual/Latn.TEM/Sun-ExtA_12/pdf_to_json_test_Latn.TEM_Sun-ExtA_12.json 2>&1
Latn.TEM_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.TEM/Sun-ExtA_16/pdf_to_json_test_Latn.TEM_Sun-ExtA_16.py > data/multilingual/Latn.TEM/Sun-ExtA_16/pdf_to_json_test_Latn.TEM_Sun-ExtA_16.json 2>&1
Latn.TEM_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.TEM/Sun-ExtA_8/pdf_to_json_test_Latn.TEM_Sun-ExtA_8.py > data/multilingual/Latn.TEM/Sun-ExtA_8/pdf_to_json_test_Latn.TEM_Sun-ExtA_8.json 2>&1


Latn.TEM_all : Latn.TEM_Mono_12 Latn.TEM_Mono_16 Latn.TEM_Mono_8 Latn.TEM_Sans_12 Latn.TEM_Sans_16 Latn.TEM_Sans_8 Latn.TEM_Serif_12 Latn.TEM_Serif_16 Latn.TEM_Serif_8 Latn.TEM_Sun-ExtA_12 Latn.TEM_Sun-ExtA_16 Latn.TEM_Sun-ExtA_8
