PYTHON=python3


Latn.TZM_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.TZM/Mono_12/pdf_to_json_test_Latn.TZM_Mono_12.py" > "data/multilingual/Latn.TZM/Mono_12/pdf_to_json_test_Latn.TZM_Mono_12.json" 2>&1
Latn.TZM_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.TZM/Mono_16/pdf_to_json_test_Latn.TZM_Mono_16.py" > "data/multilingual/Latn.TZM/Mono_16/pdf_to_json_test_Latn.TZM_Mono_16.json" 2>&1
Latn.TZM_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.TZM/Mono_8/pdf_to_json_test_Latn.TZM_Mono_8.py" > "data/multilingual/Latn.TZM/Mono_8/pdf_to_json_test_Latn.TZM_Mono_8.json" 2>&1
Latn.TZM_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.TZM/Sans_12/pdf_to_json_test_Latn.TZM_Sans_12.py" > "data/multilingual/Latn.TZM/Sans_12/pdf_to_json_test_Latn.TZM_Sans_12.json" 2>&1
Latn.TZM_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.TZM/Sans_16/pdf_to_json_test_Latn.TZM_Sans_16.py" > "data/multilingual/Latn.TZM/Sans_16/pdf_to_json_test_Latn.TZM_Sans_16.json" 2>&1
Latn.TZM_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.TZM/Sans_8/pdf_to_json_test_Latn.TZM_Sans_8.py" > "data/multilingual/Latn.TZM/Sans_8/pdf_to_json_test_Latn.TZM_Sans_8.json" 2>&1
Latn.TZM_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.TZM/Serif_12/pdf_to_json_test_Latn.TZM_Serif_12.py" > "data/multilingual/Latn.TZM/Serif_12/pdf_to_json_test_Latn.TZM_Serif_12.json" 2>&1
Latn.TZM_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.TZM/Serif_16/pdf_to_json_test_Latn.TZM_Serif_16.py" > "data/multilingual/Latn.TZM/Serif_16/pdf_to_json_test_Latn.TZM_Serif_16.json" 2>&1
Latn.TZM_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.TZM/Serif_8/pdf_to_json_test_Latn.TZM_Serif_8.py" > "data/multilingual/Latn.TZM/Serif_8/pdf_to_json_test_Latn.TZM_Serif_8.json" 2>&1
Latn.TZM_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.TZM/Sun-ExtA_12/pdf_to_json_test_Latn.TZM_Sun-ExtA_12.py" > "data/multilingual/Latn.TZM/Sun-ExtA_12/pdf_to_json_test_Latn.TZM_Sun-ExtA_12.json" 2>&1
Latn.TZM_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.TZM/Sun-ExtA_16/pdf_to_json_test_Latn.TZM_Sun-ExtA_16.py" > "data/multilingual/Latn.TZM/Sun-ExtA_16/pdf_to_json_test_Latn.TZM_Sun-ExtA_16.json" 2>&1
Latn.TZM_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.TZM/Sun-ExtA_8/pdf_to_json_test_Latn.TZM_Sun-ExtA_8.py" > "data/multilingual/Latn.TZM/Sun-ExtA_8/pdf_to_json_test_Latn.TZM_Sun-ExtA_8.json" 2>&1


Latn.TZM_all : Latn.TZM_Mono_12 Latn.TZM_Mono_16 Latn.TZM_Mono_8 Latn.TZM_Sans_12 Latn.TZM_Sans_16 Latn.TZM_Sans_8 Latn.TZM_Serif_12 Latn.TZM_Serif_16 Latn.TZM_Serif_8 Latn.TZM_Sun-ExtA_12 Latn.TZM_Sun-ExtA_16 Latn.TZM_Sun-ExtA_8
