PYTHON=python3


Latn.TZO_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.TZO/Mono_12/pdf_to_json_test_Latn.TZO_Mono_12.py" > "data/multilingual/Latn.TZO/Mono_12/pdf_to_json_test_Latn.TZO_Mono_12.json" 2>&1
Latn.TZO_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.TZO/Mono_16/pdf_to_json_test_Latn.TZO_Mono_16.py" > "data/multilingual/Latn.TZO/Mono_16/pdf_to_json_test_Latn.TZO_Mono_16.json" 2>&1
Latn.TZO_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.TZO/Mono_8/pdf_to_json_test_Latn.TZO_Mono_8.py" > "data/multilingual/Latn.TZO/Mono_8/pdf_to_json_test_Latn.TZO_Mono_8.json" 2>&1
Latn.TZO_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.TZO/Sans_12/pdf_to_json_test_Latn.TZO_Sans_12.py" > "data/multilingual/Latn.TZO/Sans_12/pdf_to_json_test_Latn.TZO_Sans_12.json" 2>&1
Latn.TZO_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.TZO/Sans_16/pdf_to_json_test_Latn.TZO_Sans_16.py" > "data/multilingual/Latn.TZO/Sans_16/pdf_to_json_test_Latn.TZO_Sans_16.json" 2>&1
Latn.TZO_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.TZO/Sans_8/pdf_to_json_test_Latn.TZO_Sans_8.py" > "data/multilingual/Latn.TZO/Sans_8/pdf_to_json_test_Latn.TZO_Sans_8.json" 2>&1
Latn.TZO_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.TZO/Serif_12/pdf_to_json_test_Latn.TZO_Serif_12.py" > "data/multilingual/Latn.TZO/Serif_12/pdf_to_json_test_Latn.TZO_Serif_12.json" 2>&1
Latn.TZO_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.TZO/Serif_16/pdf_to_json_test_Latn.TZO_Serif_16.py" > "data/multilingual/Latn.TZO/Serif_16/pdf_to_json_test_Latn.TZO_Serif_16.json" 2>&1
Latn.TZO_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.TZO/Serif_8/pdf_to_json_test_Latn.TZO_Serif_8.py" > "data/multilingual/Latn.TZO/Serif_8/pdf_to_json_test_Latn.TZO_Serif_8.json" 2>&1
Latn.TZO_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.TZO/Sun-ExtA_12/pdf_to_json_test_Latn.TZO_Sun-ExtA_12.py" > "data/multilingual/Latn.TZO/Sun-ExtA_12/pdf_to_json_test_Latn.TZO_Sun-ExtA_12.json" 2>&1
Latn.TZO_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.TZO/Sun-ExtA_16/pdf_to_json_test_Latn.TZO_Sun-ExtA_16.py" > "data/multilingual/Latn.TZO/Sun-ExtA_16/pdf_to_json_test_Latn.TZO_Sun-ExtA_16.json" 2>&1
Latn.TZO_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.TZO/Sun-ExtA_8/pdf_to_json_test_Latn.TZO_Sun-ExtA_8.py" > "data/multilingual/Latn.TZO/Sun-ExtA_8/pdf_to_json_test_Latn.TZO_Sun-ExtA_8.json" 2>&1


Latn.TZO_all : Latn.TZO_Mono_12 Latn.TZO_Mono_16 Latn.TZO_Mono_8 Latn.TZO_Sans_12 Latn.TZO_Sans_16 Latn.TZO_Sans_8 Latn.TZO_Serif_12 Latn.TZO_Serif_16 Latn.TZO_Serif_8 Latn.TZO_Sun-ExtA_12 Latn.TZO_Sun-ExtA_16 Latn.TZO_Sun-ExtA_8
