PYTHON=python3


Latn.COS_Mono_12:
	-$(PYTHON) data/multilingual/Latn.COS/Mono_12/pdf_to_json_test_Latn.COS_Mono_12.py > data/multilingual/Latn.COS/Mono_12/pdf_to_json_test_Latn.COS_Mono_12.json 2>&1
Latn.COS_Mono_16:
	-$(PYTHON) data/multilingual/Latn.COS/Mono_16/pdf_to_json_test_Latn.COS_Mono_16.py > data/multilingual/Latn.COS/Mono_16/pdf_to_json_test_Latn.COS_Mono_16.json 2>&1
Latn.COS_Mono_8:
	-$(PYTHON) data/multilingual/Latn.COS/Mono_8/pdf_to_json_test_Latn.COS_Mono_8.py > data/multilingual/Latn.COS/Mono_8/pdf_to_json_test_Latn.COS_Mono_8.json 2>&1
Latn.COS_Sans_12:
	-$(PYTHON) data/multilingual/Latn.COS/Sans_12/pdf_to_json_test_Latn.COS_Sans_12.py > data/multilingual/Latn.COS/Sans_12/pdf_to_json_test_Latn.COS_Sans_12.json 2>&1
Latn.COS_Sans_16:
	-$(PYTHON) data/multilingual/Latn.COS/Sans_16/pdf_to_json_test_Latn.COS_Sans_16.py > data/multilingual/Latn.COS/Sans_16/pdf_to_json_test_Latn.COS_Sans_16.json 2>&1
Latn.COS_Sans_8:
	-$(PYTHON) data/multilingual/Latn.COS/Sans_8/pdf_to_json_test_Latn.COS_Sans_8.py > data/multilingual/Latn.COS/Sans_8/pdf_to_json_test_Latn.COS_Sans_8.json 2>&1
Latn.COS_Serif_12:
	-$(PYTHON) data/multilingual/Latn.COS/Serif_12/pdf_to_json_test_Latn.COS_Serif_12.py > data/multilingual/Latn.COS/Serif_12/pdf_to_json_test_Latn.COS_Serif_12.json 2>&1
Latn.COS_Serif_16:
	-$(PYTHON) data/multilingual/Latn.COS/Serif_16/pdf_to_json_test_Latn.COS_Serif_16.py > data/multilingual/Latn.COS/Serif_16/pdf_to_json_test_Latn.COS_Serif_16.json 2>&1
Latn.COS_Serif_8:
	-$(PYTHON) data/multilingual/Latn.COS/Serif_8/pdf_to_json_test_Latn.COS_Serif_8.py > data/multilingual/Latn.COS/Serif_8/pdf_to_json_test_Latn.COS_Serif_8.json 2>&1
Latn.COS_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.COS/Sun-ExtA_12/pdf_to_json_test_Latn.COS_Sun-ExtA_12.py > data/multilingual/Latn.COS/Sun-ExtA_12/pdf_to_json_test_Latn.COS_Sun-ExtA_12.json 2>&1
Latn.COS_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.COS/Sun-ExtA_16/pdf_to_json_test_Latn.COS_Sun-ExtA_16.py > data/multilingual/Latn.COS/Sun-ExtA_16/pdf_to_json_test_Latn.COS_Sun-ExtA_16.json 2>&1
Latn.COS_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.COS/Sun-ExtA_8/pdf_to_json_test_Latn.COS_Sun-ExtA_8.py > data/multilingual/Latn.COS/Sun-ExtA_8/pdf_to_json_test_Latn.COS_Sun-ExtA_8.json 2>&1


Latn.COS_all : Latn.COS_Mono_12 Latn.COS_Mono_16 Latn.COS_Mono_8 Latn.COS_Sans_12 Latn.COS_Sans_16 Latn.COS_Sans_8 Latn.COS_Serif_12 Latn.COS_Serif_16 Latn.COS_Serif_8 Latn.COS_Sun-ExtA_12 Latn.COS_Sun-ExtA_16 Latn.COS_Sun-ExtA_8
