PYTHON=python3


Java.JAV_Javanese_Text_12:
	-$(PYTHON) "data/multilingual/Java.JAV/Javanese Text_12/pdf_to_json_test_Java.JAV_Javanese_Text_12.py" > "data/multilingual/Java.JAV/Javanese Text_12/pdf_to_json_test_Java.JAV_Javanese_Text_12.json" 2>&1
Java.JAV_Javanese_Text_16:
	-$(PYTHON) "data/multilingual/Java.JAV/Javanese Text_16/pdf_to_json_test_Java.JAV_Javanese_Text_16.py" > "data/multilingual/Java.JAV/Javanese Text_16/pdf_to_json_test_Java.JAV_Javanese_Text_16.json" 2>&1
Java.JAV_Javanese_Text_8:
	-$(PYTHON) "data/multilingual/Java.JAV/Javanese Text_8/pdf_to_json_test_Java.JAV_Javanese_Text_8.py" > "data/multilingual/Java.JAV/Javanese Text_8/pdf_to_json_test_Java.JAV_Javanese_Text_8.json" 2>&1
Java.JAV_Noto_Sans_Javanese_12:
	-$(PYTHON) "data/multilingual/Java.JAV/Noto Sans Javanese_12/pdf_to_json_test_Java.JAV_Noto_Sans_Javanese_12.py" > "data/multilingual/Java.JAV/Noto Sans Javanese_12/pdf_to_json_test_Java.JAV_Noto_Sans_Javanese_12.json" 2>&1
Java.JAV_Noto_Sans_Javanese_16:
	-$(PYTHON) "data/multilingual/Java.JAV/Noto Sans Javanese_16/pdf_to_json_test_Java.JAV_Noto_Sans_Javanese_16.py" > "data/multilingual/Java.JAV/Noto Sans Javanese_16/pdf_to_json_test_Java.JAV_Noto_Sans_Javanese_16.json" 2>&1
Java.JAV_Noto_Sans_Javanese_8:
	-$(PYTHON) "data/multilingual/Java.JAV/Noto Sans Javanese_8/pdf_to_json_test_Java.JAV_Noto_Sans_Javanese_8.py" > "data/multilingual/Java.JAV/Noto Sans Javanese_8/pdf_to_json_test_Java.JAV_Noto_Sans_Javanese_8.json" 2>&1


Java.JAV_all : Java.JAV_Javanese_Text_12 Java.JAV_Javanese_Text_16 Java.JAV_Javanese_Text_8 Java.JAV_Noto_Sans_Javanese_12 Java.JAV_Noto_Sans_Javanese_16 Java.JAV_Noto_Sans_Javanese_8
