PYTHON=python3


Latn.LAD_Mono_12:
	-$(PYTHON) data/multilingual/Latn.LAD/Mono_12/pdf_to_json_test_Latn.LAD_Mono_12.py > data/multilingual/Latn.LAD/Mono_12/pdf_to_json_test_Latn.LAD_Mono_12.json 2>&1
Latn.LAD_Mono_16:
	-$(PYTHON) data/multilingual/Latn.LAD/Mono_16/pdf_to_json_test_Latn.LAD_Mono_16.py > data/multilingual/Latn.LAD/Mono_16/pdf_to_json_test_Latn.LAD_Mono_16.json 2>&1
Latn.LAD_Mono_8:
	-$(PYTHON) data/multilingual/Latn.LAD/Mono_8/pdf_to_json_test_Latn.LAD_Mono_8.py > data/multilingual/Latn.LAD/Mono_8/pdf_to_json_test_Latn.LAD_Mono_8.json 2>&1
Latn.LAD_Sans_12:
	-$(PYTHON) data/multilingual/Latn.LAD/Sans_12/pdf_to_json_test_Latn.LAD_Sans_12.py > data/multilingual/Latn.LAD/Sans_12/pdf_to_json_test_Latn.LAD_Sans_12.json 2>&1
Latn.LAD_Sans_16:
	-$(PYTHON) data/multilingual/Latn.LAD/Sans_16/pdf_to_json_test_Latn.LAD_Sans_16.py > data/multilingual/Latn.LAD/Sans_16/pdf_to_json_test_Latn.LAD_Sans_16.json 2>&1
Latn.LAD_Sans_8:
	-$(PYTHON) data/multilingual/Latn.LAD/Sans_8/pdf_to_json_test_Latn.LAD_Sans_8.py > data/multilingual/Latn.LAD/Sans_8/pdf_to_json_test_Latn.LAD_Sans_8.json 2>&1
Latn.LAD_Serif_12:
	-$(PYTHON) data/multilingual/Latn.LAD/Serif_12/pdf_to_json_test_Latn.LAD_Serif_12.py > data/multilingual/Latn.LAD/Serif_12/pdf_to_json_test_Latn.LAD_Serif_12.json 2>&1
Latn.LAD_Serif_16:
	-$(PYTHON) data/multilingual/Latn.LAD/Serif_16/pdf_to_json_test_Latn.LAD_Serif_16.py > data/multilingual/Latn.LAD/Serif_16/pdf_to_json_test_Latn.LAD_Serif_16.json 2>&1
Latn.LAD_Serif_8:
	-$(PYTHON) data/multilingual/Latn.LAD/Serif_8/pdf_to_json_test_Latn.LAD_Serif_8.py > data/multilingual/Latn.LAD/Serif_8/pdf_to_json_test_Latn.LAD_Serif_8.json 2>&1
Latn.LAD_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.LAD/Sun-ExtA_12/pdf_to_json_test_Latn.LAD_Sun-ExtA_12.py > data/multilingual/Latn.LAD/Sun-ExtA_12/pdf_to_json_test_Latn.LAD_Sun-ExtA_12.json 2>&1
Latn.LAD_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.LAD/Sun-ExtA_16/pdf_to_json_test_Latn.LAD_Sun-ExtA_16.py > data/multilingual/Latn.LAD/Sun-ExtA_16/pdf_to_json_test_Latn.LAD_Sun-ExtA_16.json 2>&1
Latn.LAD_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.LAD/Sun-ExtA_8/pdf_to_json_test_Latn.LAD_Sun-ExtA_8.py > data/multilingual/Latn.LAD/Sun-ExtA_8/pdf_to_json_test_Latn.LAD_Sun-ExtA_8.json 2>&1


Latn.LAD_all : Latn.LAD_Mono_12 Latn.LAD_Mono_16 Latn.LAD_Mono_8 Latn.LAD_Sans_12 Latn.LAD_Sans_16 Latn.LAD_Sans_8 Latn.LAD_Serif_12 Latn.LAD_Serif_16 Latn.LAD_Serif_8 Latn.LAD_Sun-ExtA_12 Latn.LAD_Sun-ExtA_16 Latn.LAD_Sun-ExtA_8
