PYTHON=python3


Latn.LUA_Mono_12:
	-$(PYTHON) data/multilingual/Latn.LUA/Mono_12/pdf_to_json_test_Latn.LUA_Mono_12.py > data/multilingual/Latn.LUA/Mono_12/pdf_to_json_test_Latn.LUA_Mono_12.json 2>&1
Latn.LUA_Mono_16:
	-$(PYTHON) data/multilingual/Latn.LUA/Mono_16/pdf_to_json_test_Latn.LUA_Mono_16.py > data/multilingual/Latn.LUA/Mono_16/pdf_to_json_test_Latn.LUA_Mono_16.json 2>&1
Latn.LUA_Mono_8:
	-$(PYTHON) data/multilingual/Latn.LUA/Mono_8/pdf_to_json_test_Latn.LUA_Mono_8.py > data/multilingual/Latn.LUA/Mono_8/pdf_to_json_test_Latn.LUA_Mono_8.json 2>&1
Latn.LUA_Sans_12:
	-$(PYTHON) data/multilingual/Latn.LUA/Sans_12/pdf_to_json_test_Latn.LUA_Sans_12.py > data/multilingual/Latn.LUA/Sans_12/pdf_to_json_test_Latn.LUA_Sans_12.json 2>&1
Latn.LUA_Sans_16:
	-$(PYTHON) data/multilingual/Latn.LUA/Sans_16/pdf_to_json_test_Latn.LUA_Sans_16.py > data/multilingual/Latn.LUA/Sans_16/pdf_to_json_test_Latn.LUA_Sans_16.json 2>&1
Latn.LUA_Sans_8:
	-$(PYTHON) data/multilingual/Latn.LUA/Sans_8/pdf_to_json_test_Latn.LUA_Sans_8.py > data/multilingual/Latn.LUA/Sans_8/pdf_to_json_test_Latn.LUA_Sans_8.json 2>&1
Latn.LUA_Serif_12:
	-$(PYTHON) data/multilingual/Latn.LUA/Serif_12/pdf_to_json_test_Latn.LUA_Serif_12.py > data/multilingual/Latn.LUA/Serif_12/pdf_to_json_test_Latn.LUA_Serif_12.json 2>&1
Latn.LUA_Serif_16:
	-$(PYTHON) data/multilingual/Latn.LUA/Serif_16/pdf_to_json_test_Latn.LUA_Serif_16.py > data/multilingual/Latn.LUA/Serif_16/pdf_to_json_test_Latn.LUA_Serif_16.json 2>&1
Latn.LUA_Serif_8:
	-$(PYTHON) data/multilingual/Latn.LUA/Serif_8/pdf_to_json_test_Latn.LUA_Serif_8.py > data/multilingual/Latn.LUA/Serif_8/pdf_to_json_test_Latn.LUA_Serif_8.json 2>&1
Latn.LUA_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.LUA/Sun-ExtA_12/pdf_to_json_test_Latn.LUA_Sun-ExtA_12.py > data/multilingual/Latn.LUA/Sun-ExtA_12/pdf_to_json_test_Latn.LUA_Sun-ExtA_12.json 2>&1
Latn.LUA_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.LUA/Sun-ExtA_16/pdf_to_json_test_Latn.LUA_Sun-ExtA_16.py > data/multilingual/Latn.LUA/Sun-ExtA_16/pdf_to_json_test_Latn.LUA_Sun-ExtA_16.json 2>&1
Latn.LUA_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.LUA/Sun-ExtA_8/pdf_to_json_test_Latn.LUA_Sun-ExtA_8.py > data/multilingual/Latn.LUA/Sun-ExtA_8/pdf_to_json_test_Latn.LUA_Sun-ExtA_8.json 2>&1


Latn.LUA_all : Latn.LUA_Mono_12 Latn.LUA_Mono_16 Latn.LUA_Mono_8 Latn.LUA_Sans_12 Latn.LUA_Sans_16 Latn.LUA_Sans_8 Latn.LUA_Serif_12 Latn.LUA_Serif_16 Latn.LUA_Serif_8 Latn.LUA_Sun-ExtA_12 Latn.LUA_Sun-ExtA_16 Latn.LUA_Sun-ExtA_8
