PYTHON=python3


Latn.KEK_Mono_12:
	-$(PYTHON) data/multilingual/Latn.KEK/Mono_12/pdf_to_json_test_Latn.KEK_Mono_12.py > data/multilingual/Latn.KEK/Mono_12/pdf_to_json_test_Latn.KEK_Mono_12.json 2>&1
Latn.KEK_Mono_16:
	-$(PYTHON) data/multilingual/Latn.KEK/Mono_16/pdf_to_json_test_Latn.KEK_Mono_16.py > data/multilingual/Latn.KEK/Mono_16/pdf_to_json_test_Latn.KEK_Mono_16.json 2>&1
Latn.KEK_Mono_8:
	-$(PYTHON) data/multilingual/Latn.KEK/Mono_8/pdf_to_json_test_Latn.KEK_Mono_8.py > data/multilingual/Latn.KEK/Mono_8/pdf_to_json_test_Latn.KEK_Mono_8.json 2>&1
Latn.KEK_Sans_12:
	-$(PYTHON) data/multilingual/Latn.KEK/Sans_12/pdf_to_json_test_Latn.KEK_Sans_12.py > data/multilingual/Latn.KEK/Sans_12/pdf_to_json_test_Latn.KEK_Sans_12.json 2>&1
Latn.KEK_Sans_16:
	-$(PYTHON) data/multilingual/Latn.KEK/Sans_16/pdf_to_json_test_Latn.KEK_Sans_16.py > data/multilingual/Latn.KEK/Sans_16/pdf_to_json_test_Latn.KEK_Sans_16.json 2>&1
Latn.KEK_Sans_8:
	-$(PYTHON) data/multilingual/Latn.KEK/Sans_8/pdf_to_json_test_Latn.KEK_Sans_8.py > data/multilingual/Latn.KEK/Sans_8/pdf_to_json_test_Latn.KEK_Sans_8.json 2>&1
Latn.KEK_Serif_12:
	-$(PYTHON) data/multilingual/Latn.KEK/Serif_12/pdf_to_json_test_Latn.KEK_Serif_12.py > data/multilingual/Latn.KEK/Serif_12/pdf_to_json_test_Latn.KEK_Serif_12.json 2>&1
Latn.KEK_Serif_16:
	-$(PYTHON) data/multilingual/Latn.KEK/Serif_16/pdf_to_json_test_Latn.KEK_Serif_16.py > data/multilingual/Latn.KEK/Serif_16/pdf_to_json_test_Latn.KEK_Serif_16.json 2>&1
Latn.KEK_Serif_8:
	-$(PYTHON) data/multilingual/Latn.KEK/Serif_8/pdf_to_json_test_Latn.KEK_Serif_8.py > data/multilingual/Latn.KEK/Serif_8/pdf_to_json_test_Latn.KEK_Serif_8.json 2>&1
Latn.KEK_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.KEK/Sun-ExtA_12/pdf_to_json_test_Latn.KEK_Sun-ExtA_12.py > data/multilingual/Latn.KEK/Sun-ExtA_12/pdf_to_json_test_Latn.KEK_Sun-ExtA_12.json 2>&1
Latn.KEK_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.KEK/Sun-ExtA_16/pdf_to_json_test_Latn.KEK_Sun-ExtA_16.py > data/multilingual/Latn.KEK/Sun-ExtA_16/pdf_to_json_test_Latn.KEK_Sun-ExtA_16.json 2>&1
Latn.KEK_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.KEK/Sun-ExtA_8/pdf_to_json_test_Latn.KEK_Sun-ExtA_8.py > data/multilingual/Latn.KEK/Sun-ExtA_8/pdf_to_json_test_Latn.KEK_Sun-ExtA_8.json 2>&1


Latn.KEK_all : Latn.KEK_Mono_12 Latn.KEK_Mono_16 Latn.KEK_Mono_8 Latn.KEK_Sans_12 Latn.KEK_Sans_16 Latn.KEK_Sans_8 Latn.KEK_Serif_12 Latn.KEK_Serif_16 Latn.KEK_Serif_8 Latn.KEK_Sun-ExtA_12 Latn.KEK_Sun-ExtA_16 Latn.KEK_Sun-ExtA_8
