PYTHON=python3


Latn.QXU_Mono_12:
	-$(PYTHON) data/multilingual/Latn.QXU/Mono_12/pdf_to_json_test_Latn.QXU_Mono_12.py > data/multilingual/Latn.QXU/Mono_12/pdf_to_json_test_Latn.QXU_Mono_12.json 2>&1
Latn.QXU_Mono_16:
	-$(PYTHON) data/multilingual/Latn.QXU/Mono_16/pdf_to_json_test_Latn.QXU_Mono_16.py > data/multilingual/Latn.QXU/Mono_16/pdf_to_json_test_Latn.QXU_Mono_16.json 2>&1
Latn.QXU_Mono_8:
	-$(PYTHON) data/multilingual/Latn.QXU/Mono_8/pdf_to_json_test_Latn.QXU_Mono_8.py > data/multilingual/Latn.QXU/Mono_8/pdf_to_json_test_Latn.QXU_Mono_8.json 2>&1
Latn.QXU_Sans_12:
	-$(PYTHON) data/multilingual/Latn.QXU/Sans_12/pdf_to_json_test_Latn.QXU_Sans_12.py > data/multilingual/Latn.QXU/Sans_12/pdf_to_json_test_Latn.QXU_Sans_12.json 2>&1
Latn.QXU_Sans_16:
	-$(PYTHON) data/multilingual/Latn.QXU/Sans_16/pdf_to_json_test_Latn.QXU_Sans_16.py > data/multilingual/Latn.QXU/Sans_16/pdf_to_json_test_Latn.QXU_Sans_16.json 2>&1
Latn.QXU_Sans_8:
	-$(PYTHON) data/multilingual/Latn.QXU/Sans_8/pdf_to_json_test_Latn.QXU_Sans_8.py > data/multilingual/Latn.QXU/Sans_8/pdf_to_json_test_Latn.QXU_Sans_8.json 2>&1
Latn.QXU_Serif_12:
	-$(PYTHON) data/multilingual/Latn.QXU/Serif_12/pdf_to_json_test_Latn.QXU_Serif_12.py > data/multilingual/Latn.QXU/Serif_12/pdf_to_json_test_Latn.QXU_Serif_12.json 2>&1
Latn.QXU_Serif_16:
	-$(PYTHON) data/multilingual/Latn.QXU/Serif_16/pdf_to_json_test_Latn.QXU_Serif_16.py > data/multilingual/Latn.QXU/Serif_16/pdf_to_json_test_Latn.QXU_Serif_16.json 2>&1
Latn.QXU_Serif_8:
	-$(PYTHON) data/multilingual/Latn.QXU/Serif_8/pdf_to_json_test_Latn.QXU_Serif_8.py > data/multilingual/Latn.QXU/Serif_8/pdf_to_json_test_Latn.QXU_Serif_8.json 2>&1
Latn.QXU_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.QXU/Sun-ExtA_12/pdf_to_json_test_Latn.QXU_Sun-ExtA_12.py > data/multilingual/Latn.QXU/Sun-ExtA_12/pdf_to_json_test_Latn.QXU_Sun-ExtA_12.json 2>&1
Latn.QXU_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.QXU/Sun-ExtA_16/pdf_to_json_test_Latn.QXU_Sun-ExtA_16.py > data/multilingual/Latn.QXU/Sun-ExtA_16/pdf_to_json_test_Latn.QXU_Sun-ExtA_16.json 2>&1
Latn.QXU_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.QXU/Sun-ExtA_8/pdf_to_json_test_Latn.QXU_Sun-ExtA_8.py > data/multilingual/Latn.QXU/Sun-ExtA_8/pdf_to_json_test_Latn.QXU_Sun-ExtA_8.json 2>&1


Latn.QXU_all : Latn.QXU_Mono_12 Latn.QXU_Mono_16 Latn.QXU_Mono_8 Latn.QXU_Sans_12 Latn.QXU_Sans_16 Latn.QXU_Sans_8 Latn.QXU_Serif_12 Latn.QXU_Serif_16 Latn.QXU_Serif_8 Latn.QXU_Sun-ExtA_12 Latn.QXU_Sun-ExtA_16 Latn.QXU_Sun-ExtA_8
