PYTHON=python3


Cyrl.TYV_Mono_12:
	-$(PYTHON) "data/multilingual/Cyrl.TYV/Mono_12/pdf_to_json_test_Cyrl.TYV_Mono_12.py" > "data/multilingual/Cyrl.TYV/Mono_12/pdf_to_json_test_Cyrl.TYV_Mono_12.json" 2>&1
Cyrl.TYV_Mono_16:
	-$(PYTHON) "data/multilingual/Cyrl.TYV/Mono_16/pdf_to_json_test_Cyrl.TYV_Mono_16.py" > "data/multilingual/Cyrl.TYV/Mono_16/pdf_to_json_test_Cyrl.TYV_Mono_16.json" 2>&1
Cyrl.TYV_Mono_8:
	-$(PYTHON) "data/multilingual/Cyrl.TYV/Mono_8/pdf_to_json_test_Cyrl.TYV_Mono_8.py" > "data/multilingual/Cyrl.TYV/Mono_8/pdf_to_json_test_Cyrl.TYV_Mono_8.json" 2>&1
Cyrl.TYV_Sans_12:
	-$(PYTHON) "data/multilingual/Cyrl.TYV/Sans_12/pdf_to_json_test_Cyrl.TYV_Sans_12.py" > "data/multilingual/Cyrl.TYV/Sans_12/pdf_to_json_test_Cyrl.TYV_Sans_12.json" 2>&1
Cyrl.TYV_Sans_16:
	-$(PYTHON) "data/multilingual/Cyrl.TYV/Sans_16/pdf_to_json_test_Cyrl.TYV_Sans_16.py" > "data/multilingual/Cyrl.TYV/Sans_16/pdf_to_json_test_Cyrl.TYV_Sans_16.json" 2>&1
Cyrl.TYV_Sans_8:
	-$(PYTHON) "data/multilingual/Cyrl.TYV/Sans_8/pdf_to_json_test_Cyrl.TYV_Sans_8.py" > "data/multilingual/Cyrl.TYV/Sans_8/pdf_to_json_test_Cyrl.TYV_Sans_8.json" 2>&1
Cyrl.TYV_Serif_12:
	-$(PYTHON) "data/multilingual/Cyrl.TYV/Serif_12/pdf_to_json_test_Cyrl.TYV_Serif_12.py" > "data/multilingual/Cyrl.TYV/Serif_12/pdf_to_json_test_Cyrl.TYV_Serif_12.json" 2>&1
Cyrl.TYV_Serif_16:
	-$(PYTHON) "data/multilingual/Cyrl.TYV/Serif_16/pdf_to_json_test_Cyrl.TYV_Serif_16.py" > "data/multilingual/Cyrl.TYV/Serif_16/pdf_to_json_test_Cyrl.TYV_Serif_16.json" 2>&1
Cyrl.TYV_Serif_8:
	-$(PYTHON) "data/multilingual/Cyrl.TYV/Serif_8/pdf_to_json_test_Cyrl.TYV_Serif_8.py" > "data/multilingual/Cyrl.TYV/Serif_8/pdf_to_json_test_Cyrl.TYV_Serif_8.json" 2>&1
Cyrl.TYV_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Cyrl.TYV/Sun-ExtA_12/pdf_to_json_test_Cyrl.TYV_Sun-ExtA_12.py" > "data/multilingual/Cyrl.TYV/Sun-ExtA_12/pdf_to_json_test_Cyrl.TYV_Sun-ExtA_12.json" 2>&1
Cyrl.TYV_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Cyrl.TYV/Sun-ExtA_16/pdf_to_json_test_Cyrl.TYV_Sun-ExtA_16.py" > "data/multilingual/Cyrl.TYV/Sun-ExtA_16/pdf_to_json_test_Cyrl.TYV_Sun-ExtA_16.json" 2>&1
Cyrl.TYV_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Cyrl.TYV/Sun-ExtA_8/pdf_to_json_test_Cyrl.TYV_Sun-ExtA_8.py" > "data/multilingual/Cyrl.TYV/Sun-ExtA_8/pdf_to_json_test_Cyrl.TYV_Sun-ExtA_8.json" 2>&1


Cyrl.TYV_all : Cyrl.TYV_Mono_12 Cyrl.TYV_Mono_16 Cyrl.TYV_Mono_8 Cyrl.TYV_Sans_12 Cyrl.TYV_Sans_16 Cyrl.TYV_Sans_8 Cyrl.TYV_Serif_12 Cyrl.TYV_Serif_16 Cyrl.TYV_Serif_8 Cyrl.TYV_Sun-ExtA_12 Cyrl.TYV_Sun-ExtA_16 Cyrl.TYV_Sun-ExtA_8
