PYTHON=python3


Hani.YUE_Mono_12:
	-$(PYTHON) data/multilingual/Hani.YUE/Mono_12/pdf_to_json_test_Hani.YUE_Mono_12.py > data/multilingual/Hani.YUE/Mono_12/pdf_to_json_test_Hani.YUE_Mono_12.json 2>&1
Hani.YUE_Mono_16:
	-$(PYTHON) data/multilingual/Hani.YUE/Mono_16/pdf_to_json_test_Hani.YUE_Mono_16.py > data/multilingual/Hani.YUE/Mono_16/pdf_to_json_test_Hani.YUE_Mono_16.json 2>&1
Hani.YUE_Mono_8:
	-$(PYTHON) data/multilingual/Hani.YUE/Mono_8/pdf_to_json_test_Hani.YUE_Mono_8.py > data/multilingual/Hani.YUE/Mono_8/pdf_to_json_test_Hani.YUE_Mono_8.json 2>&1
Hani.YUE_Sans_12:
	-$(PYTHON) data/multilingual/Hani.YUE/Sans_12/pdf_to_json_test_Hani.YUE_Sans_12.py > data/multilingual/Hani.YUE/Sans_12/pdf_to_json_test_Hani.YUE_Sans_12.json 2>&1
Hani.YUE_Sans_16:
	-$(PYTHON) data/multilingual/Hani.YUE/Sans_16/pdf_to_json_test_Hani.YUE_Sans_16.py > data/multilingual/Hani.YUE/Sans_16/pdf_to_json_test_Hani.YUE_Sans_16.json 2>&1
Hani.YUE_Sans_8:
	-$(PYTHON) data/multilingual/Hani.YUE/Sans_8/pdf_to_json_test_Hani.YUE_Sans_8.py > data/multilingual/Hani.YUE/Sans_8/pdf_to_json_test_Hani.YUE_Sans_8.json 2>&1
Hani.YUE_Serif_12:
	-$(PYTHON) data/multilingual/Hani.YUE/Serif_12/pdf_to_json_test_Hani.YUE_Serif_12.py > data/multilingual/Hani.YUE/Serif_12/pdf_to_json_test_Hani.YUE_Serif_12.json 2>&1
Hani.YUE_Serif_16:
	-$(PYTHON) data/multilingual/Hani.YUE/Serif_16/pdf_to_json_test_Hani.YUE_Serif_16.py > data/multilingual/Hani.YUE/Serif_16/pdf_to_json_test_Hani.YUE_Serif_16.json 2>&1
Hani.YUE_Serif_8:
	-$(PYTHON) data/multilingual/Hani.YUE/Serif_8/pdf_to_json_test_Hani.YUE_Serif_8.py > data/multilingual/Hani.YUE/Serif_8/pdf_to_json_test_Hani.YUE_Serif_8.json 2>&1
Hani.YUE_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Hani.YUE/Sun-ExtA_12/pdf_to_json_test_Hani.YUE_Sun-ExtA_12.py > data/multilingual/Hani.YUE/Sun-ExtA_12/pdf_to_json_test_Hani.YUE_Sun-ExtA_12.json 2>&1
Hani.YUE_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Hani.YUE/Sun-ExtA_16/pdf_to_json_test_Hani.YUE_Sun-ExtA_16.py > data/multilingual/Hani.YUE/Sun-ExtA_16/pdf_to_json_test_Hani.YUE_Sun-ExtA_16.json 2>&1
Hani.YUE_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Hani.YUE/Sun-ExtA_8/pdf_to_json_test_Hani.YUE_Sun-ExtA_8.py > data/multilingual/Hani.YUE/Sun-ExtA_8/pdf_to_json_test_Hani.YUE_Sun-ExtA_8.json 2>&1


Hani.YUE_all : Hani.YUE_Mono_12 Hani.YUE_Mono_16 Hani.YUE_Mono_8 Hani.YUE_Sans_12 Hani.YUE_Sans_16 Hani.YUE_Sans_8 Hani.YUE_Serif_12 Hani.YUE_Serif_16 Hani.YUE_Serif_8 Hani.YUE_Sun-ExtA_12 Hani.YUE_Sun-ExtA_16 Hani.YUE_Sun-ExtA_8
