PYTHON=python3


Latn.KMR_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.KMR/Mono_12/pdf_to_json_test_Latn.KMR_Mono_12.py" > "data/multilingual/Latn.KMR/Mono_12/pdf_to_json_test_Latn.KMR_Mono_12.json" 2>&1
Latn.KMR_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.KMR/Mono_16/pdf_to_json_test_Latn.KMR_Mono_16.py" > "data/multilingual/Latn.KMR/Mono_16/pdf_to_json_test_Latn.KMR_Mono_16.json" 2>&1
Latn.KMR_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.KMR/Mono_8/pdf_to_json_test_Latn.KMR_Mono_8.py" > "data/multilingual/Latn.KMR/Mono_8/pdf_to_json_test_Latn.KMR_Mono_8.json" 2>&1
Latn.KMR_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.KMR/Sans_12/pdf_to_json_test_Latn.KMR_Sans_12.py" > "data/multilingual/Latn.KMR/Sans_12/pdf_to_json_test_Latn.KMR_Sans_12.json" 2>&1
Latn.KMR_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.KMR/Sans_16/pdf_to_json_test_Latn.KMR_Sans_16.py" > "data/multilingual/Latn.KMR/Sans_16/pdf_to_json_test_Latn.KMR_Sans_16.json" 2>&1
Latn.KMR_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.KMR/Sans_8/pdf_to_json_test_Latn.KMR_Sans_8.py" > "data/multilingual/Latn.KMR/Sans_8/pdf_to_json_test_Latn.KMR_Sans_8.json" 2>&1
Latn.KMR_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.KMR/Serif_12/pdf_to_json_test_Latn.KMR_Serif_12.py" > "data/multilingual/Latn.KMR/Serif_12/pdf_to_json_test_Latn.KMR_Serif_12.json" 2>&1
Latn.KMR_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.KMR/Serif_16/pdf_to_json_test_Latn.KMR_Serif_16.py" > "data/multilingual/Latn.KMR/Serif_16/pdf_to_json_test_Latn.KMR_Serif_16.json" 2>&1
Latn.KMR_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.KMR/Serif_8/pdf_to_json_test_Latn.KMR_Serif_8.py" > "data/multilingual/Latn.KMR/Serif_8/pdf_to_json_test_Latn.KMR_Serif_8.json" 2>&1
Latn.KMR_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.KMR/Sun-ExtA_12/pdf_to_json_test_Latn.KMR_Sun-ExtA_12.py" > "data/multilingual/Latn.KMR/Sun-ExtA_12/pdf_to_json_test_Latn.KMR_Sun-ExtA_12.json" 2>&1
Latn.KMR_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.KMR/Sun-ExtA_16/pdf_to_json_test_Latn.KMR_Sun-ExtA_16.py" > "data/multilingual/Latn.KMR/Sun-ExtA_16/pdf_to_json_test_Latn.KMR_Sun-ExtA_16.json" 2>&1
Latn.KMR_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.KMR/Sun-ExtA_8/pdf_to_json_test_Latn.KMR_Sun-ExtA_8.py" > "data/multilingual/Latn.KMR/Sun-ExtA_8/pdf_to_json_test_Latn.KMR_Sun-ExtA_8.json" 2>&1


Latn.KMR_all : Latn.KMR_Mono_12 Latn.KMR_Mono_16 Latn.KMR_Mono_8 Latn.KMR_Sans_12 Latn.KMR_Sans_16 Latn.KMR_Sans_8 Latn.KMR_Serif_12 Latn.KMR_Serif_16 Latn.KMR_Serif_8 Latn.KMR_Sun-ExtA_12 Latn.KMR_Sun-ExtA_16 Latn.KMR_Sun-ExtA_8
