PYTHON=python3


Hans.GAN_Mono_12:
	-$(PYTHON) "data/multilingual/Hans.GAN/Mono_12/pdf_to_json_test_Hans.GAN_Mono_12.py" > "data/multilingual/Hans.GAN/Mono_12/pdf_to_json_test_Hans.GAN_Mono_12.json" 2>&1
Hans.GAN_Mono_16:
	-$(PYTHON) "data/multilingual/Hans.GAN/Mono_16/pdf_to_json_test_Hans.GAN_Mono_16.py" > "data/multilingual/Hans.GAN/Mono_16/pdf_to_json_test_Hans.GAN_Mono_16.json" 2>&1
Hans.GAN_Mono_8:
	-$(PYTHON) "data/multilingual/Hans.GAN/Mono_8/pdf_to_json_test_Hans.GAN_Mono_8.py" > "data/multilingual/Hans.GAN/Mono_8/pdf_to_json_test_Hans.GAN_Mono_8.json" 2>&1
Hans.GAN_Sans_12:
	-$(PYTHON) "data/multilingual/Hans.GAN/Sans_12/pdf_to_json_test_Hans.GAN_Sans_12.py" > "data/multilingual/Hans.GAN/Sans_12/pdf_to_json_test_Hans.GAN_Sans_12.json" 2>&1
Hans.GAN_Sans_16:
	-$(PYTHON) "data/multilingual/Hans.GAN/Sans_16/pdf_to_json_test_Hans.GAN_Sans_16.py" > "data/multilingual/Hans.GAN/Sans_16/pdf_to_json_test_Hans.GAN_Sans_16.json" 2>&1
Hans.GAN_Sans_8:
	-$(PYTHON) "data/multilingual/Hans.GAN/Sans_8/pdf_to_json_test_Hans.GAN_Sans_8.py" > "data/multilingual/Hans.GAN/Sans_8/pdf_to_json_test_Hans.GAN_Sans_8.json" 2>&1
Hans.GAN_Serif_12:
	-$(PYTHON) "data/multilingual/Hans.GAN/Serif_12/pdf_to_json_test_Hans.GAN_Serif_12.py" > "data/multilingual/Hans.GAN/Serif_12/pdf_to_json_test_Hans.GAN_Serif_12.json" 2>&1
Hans.GAN_Serif_16:
	-$(PYTHON) "data/multilingual/Hans.GAN/Serif_16/pdf_to_json_test_Hans.GAN_Serif_16.py" > "data/multilingual/Hans.GAN/Serif_16/pdf_to_json_test_Hans.GAN_Serif_16.json" 2>&1
Hans.GAN_Serif_8:
	-$(PYTHON) "data/multilingual/Hans.GAN/Serif_8/pdf_to_json_test_Hans.GAN_Serif_8.py" > "data/multilingual/Hans.GAN/Serif_8/pdf_to_json_test_Hans.GAN_Serif_8.json" 2>&1
Hans.GAN_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Hans.GAN/Sun-ExtA_12/pdf_to_json_test_Hans.GAN_Sun-ExtA_12.py" > "data/multilingual/Hans.GAN/Sun-ExtA_12/pdf_to_json_test_Hans.GAN_Sun-ExtA_12.json" 2>&1
Hans.GAN_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Hans.GAN/Sun-ExtA_16/pdf_to_json_test_Hans.GAN_Sun-ExtA_16.py" > "data/multilingual/Hans.GAN/Sun-ExtA_16/pdf_to_json_test_Hans.GAN_Sun-ExtA_16.json" 2>&1
Hans.GAN_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Hans.GAN/Sun-ExtA_8/pdf_to_json_test_Hans.GAN_Sun-ExtA_8.py" > "data/multilingual/Hans.GAN/Sun-ExtA_8/pdf_to_json_test_Hans.GAN_Sun-ExtA_8.json" 2>&1


Hans.GAN_all : Hans.GAN_Mono_12 Hans.GAN_Mono_16 Hans.GAN_Mono_8 Hans.GAN_Sans_12 Hans.GAN_Sans_16 Hans.GAN_Sans_8 Hans.GAN_Serif_12 Hans.GAN_Serif_16 Hans.GAN_Serif_8 Hans.GAN_Sun-ExtA_12 Hans.GAN_Sun-ExtA_16 Hans.GAN_Sun-ExtA_8
