PYTHON=python3


Latn.SSW_Mono_12:
	-$(PYTHON) data/multilingual/Latn.SSW/Mono_12/pdf_to_json_test_Latn.SSW_Mono_12.py > data/multilingual/Latn.SSW/Mono_12/pdf_to_json_test_Latn.SSW_Mono_12.json 2>&1
Latn.SSW_Mono_16:
	-$(PYTHON) data/multilingual/Latn.SSW/Mono_16/pdf_to_json_test_Latn.SSW_Mono_16.py > data/multilingual/Latn.SSW/Mono_16/pdf_to_json_test_Latn.SSW_Mono_16.json 2>&1
Latn.SSW_Mono_8:
	-$(PYTHON) data/multilingual/Latn.SSW/Mono_8/pdf_to_json_test_Latn.SSW_Mono_8.py > data/multilingual/Latn.SSW/Mono_8/pdf_to_json_test_Latn.SSW_Mono_8.json 2>&1
Latn.SSW_Sans_12:
	-$(PYTHON) data/multilingual/Latn.SSW/Sans_12/pdf_to_json_test_Latn.SSW_Sans_12.py > data/multilingual/Latn.SSW/Sans_12/pdf_to_json_test_Latn.SSW_Sans_12.json 2>&1
Latn.SSW_Sans_16:
	-$(PYTHON) data/multilingual/Latn.SSW/Sans_16/pdf_to_json_test_Latn.SSW_Sans_16.py > data/multilingual/Latn.SSW/Sans_16/pdf_to_json_test_Latn.SSW_Sans_16.json 2>&1
Latn.SSW_Sans_8:
	-$(PYTHON) data/multilingual/Latn.SSW/Sans_8/pdf_to_json_test_Latn.SSW_Sans_8.py > data/multilingual/Latn.SSW/Sans_8/pdf_to_json_test_Latn.SSW_Sans_8.json 2>&1
Latn.SSW_Serif_12:
	-$(PYTHON) data/multilingual/Latn.SSW/Serif_12/pdf_to_json_test_Latn.SSW_Serif_12.py > data/multilingual/Latn.SSW/Serif_12/pdf_to_json_test_Latn.SSW_Serif_12.json 2>&1
Latn.SSW_Serif_16:
	-$(PYTHON) data/multilingual/Latn.SSW/Serif_16/pdf_to_json_test_Latn.SSW_Serif_16.py > data/multilingual/Latn.SSW/Serif_16/pdf_to_json_test_Latn.SSW_Serif_16.json 2>&1
Latn.SSW_Serif_8:
	-$(PYTHON) data/multilingual/Latn.SSW/Serif_8/pdf_to_json_test_Latn.SSW_Serif_8.py > data/multilingual/Latn.SSW/Serif_8/pdf_to_json_test_Latn.SSW_Serif_8.json 2>&1
Latn.SSW_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.SSW/Sun-ExtA_12/pdf_to_json_test_Latn.SSW_Sun-ExtA_12.py > data/multilingual/Latn.SSW/Sun-ExtA_12/pdf_to_json_test_Latn.SSW_Sun-ExtA_12.json 2>&1
Latn.SSW_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.SSW/Sun-ExtA_16/pdf_to_json_test_Latn.SSW_Sun-ExtA_16.py > data/multilingual/Latn.SSW/Sun-ExtA_16/pdf_to_json_test_Latn.SSW_Sun-ExtA_16.json 2>&1
Latn.SSW_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.SSW/Sun-ExtA_8/pdf_to_json_test_Latn.SSW_Sun-ExtA_8.py > data/multilingual/Latn.SSW/Sun-ExtA_8/pdf_to_json_test_Latn.SSW_Sun-ExtA_8.json 2>&1


Latn.SSW_all : Latn.SSW_Mono_12 Latn.SSW_Mono_16 Latn.SSW_Mono_8 Latn.SSW_Sans_12 Latn.SSW_Sans_16 Latn.SSW_Sans_8 Latn.SSW_Serif_12 Latn.SSW_Serif_16 Latn.SSW_Serif_8 Latn.SSW_Sun-ExtA_12 Latn.SSW_Sun-ExtA_16 Latn.SSW_Sun-ExtA_8
