PYTHON=python3


Latn.VEC_Mono_12:
	-$(PYTHON) data/multilingual/Latn.VEC/Mono_12/pdf_to_json_test_Latn.VEC_Mono_12.py > data/multilingual/Latn.VEC/Mono_12/pdf_to_json_test_Latn.VEC_Mono_12.json 2>&1
Latn.VEC_Mono_16:
	-$(PYTHON) data/multilingual/Latn.VEC/Mono_16/pdf_to_json_test_Latn.VEC_Mono_16.py > data/multilingual/Latn.VEC/Mono_16/pdf_to_json_test_Latn.VEC_Mono_16.json 2>&1
Latn.VEC_Mono_8:
	-$(PYTHON) data/multilingual/Latn.VEC/Mono_8/pdf_to_json_test_Latn.VEC_Mono_8.py > data/multilingual/Latn.VEC/Mono_8/pdf_to_json_test_Latn.VEC_Mono_8.json 2>&1
Latn.VEC_Sans_12:
	-$(PYTHON) data/multilingual/Latn.VEC/Sans_12/pdf_to_json_test_Latn.VEC_Sans_12.py > data/multilingual/Latn.VEC/Sans_12/pdf_to_json_test_Latn.VEC_Sans_12.json 2>&1
Latn.VEC_Sans_16:
	-$(PYTHON) data/multilingual/Latn.VEC/Sans_16/pdf_to_json_test_Latn.VEC_Sans_16.py > data/multilingual/Latn.VEC/Sans_16/pdf_to_json_test_Latn.VEC_Sans_16.json 2>&1
Latn.VEC_Sans_8:
	-$(PYTHON) data/multilingual/Latn.VEC/Sans_8/pdf_to_json_test_Latn.VEC_Sans_8.py > data/multilingual/Latn.VEC/Sans_8/pdf_to_json_test_Latn.VEC_Sans_8.json 2>&1
Latn.VEC_Serif_12:
	-$(PYTHON) data/multilingual/Latn.VEC/Serif_12/pdf_to_json_test_Latn.VEC_Serif_12.py > data/multilingual/Latn.VEC/Serif_12/pdf_to_json_test_Latn.VEC_Serif_12.json 2>&1
Latn.VEC_Serif_16:
	-$(PYTHON) data/multilingual/Latn.VEC/Serif_16/pdf_to_json_test_Latn.VEC_Serif_16.py > data/multilingual/Latn.VEC/Serif_16/pdf_to_json_test_Latn.VEC_Serif_16.json 2>&1
Latn.VEC_Serif_8:
	-$(PYTHON) data/multilingual/Latn.VEC/Serif_8/pdf_to_json_test_Latn.VEC_Serif_8.py > data/multilingual/Latn.VEC/Serif_8/pdf_to_json_test_Latn.VEC_Serif_8.json 2>&1
Latn.VEC_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.VEC/Sun-ExtA_12/pdf_to_json_test_Latn.VEC_Sun-ExtA_12.py > data/multilingual/Latn.VEC/Sun-ExtA_12/pdf_to_json_test_Latn.VEC_Sun-ExtA_12.json 2>&1
Latn.VEC_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.VEC/Sun-ExtA_16/pdf_to_json_test_Latn.VEC_Sun-ExtA_16.py > data/multilingual/Latn.VEC/Sun-ExtA_16/pdf_to_json_test_Latn.VEC_Sun-ExtA_16.json 2>&1
Latn.VEC_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.VEC/Sun-ExtA_8/pdf_to_json_test_Latn.VEC_Sun-ExtA_8.py > data/multilingual/Latn.VEC/Sun-ExtA_8/pdf_to_json_test_Latn.VEC_Sun-ExtA_8.json 2>&1


Latn.VEC_all : Latn.VEC_Mono_12 Latn.VEC_Mono_16 Latn.VEC_Mono_8 Latn.VEC_Sans_12 Latn.VEC_Sans_16 Latn.VEC_Sans_8 Latn.VEC_Serif_12 Latn.VEC_Serif_16 Latn.VEC_Serif_8 Latn.VEC_Sun-ExtA_12 Latn.VEC_Sun-ExtA_16 Latn.VEC_Sun-ExtA_8
