PYTHON=python3


Cyrl.BEL_Mono_12:
	-$(PYTHON) "data/multilingual/Cyrl.BEL/Mono_12/pdf_to_json_test_Cyrl.BEL_Mono_12.py" > "data/multilingual/Cyrl.BEL/Mono_12/pdf_to_json_test_Cyrl.BEL_Mono_12.json" 2>&1
Cyrl.BEL_Mono_16:
	-$(PYTHON) "data/multilingual/Cyrl.BEL/Mono_16/pdf_to_json_test_Cyrl.BEL_Mono_16.py" > "data/multilingual/Cyrl.BEL/Mono_16/pdf_to_json_test_Cyrl.BEL_Mono_16.json" 2>&1
Cyrl.BEL_Mono_8:
	-$(PYTHON) "data/multilingual/Cyrl.BEL/Mono_8/pdf_to_json_test_Cyrl.BEL_Mono_8.py" > "data/multilingual/Cyrl.BEL/Mono_8/pdf_to_json_test_Cyrl.BEL_Mono_8.json" 2>&1
Cyrl.BEL_Sans_12:
	-$(PYTHON) "data/multilingual/Cyrl.BEL/Sans_12/pdf_to_json_test_Cyrl.BEL_Sans_12.py" > "data/multilingual/Cyrl.BEL/Sans_12/pdf_to_json_test_Cyrl.BEL_Sans_12.json" 2>&1
Cyrl.BEL_Sans_16:
	-$(PYTHON) "data/multilingual/Cyrl.BEL/Sans_16/pdf_to_json_test_Cyrl.BEL_Sans_16.py" > "data/multilingual/Cyrl.BEL/Sans_16/pdf_to_json_test_Cyrl.BEL_Sans_16.json" 2>&1
Cyrl.BEL_Sans_8:
	-$(PYTHON) "data/multilingual/Cyrl.BEL/Sans_8/pdf_to_json_test_Cyrl.BEL_Sans_8.py" > "data/multilingual/Cyrl.BEL/Sans_8/pdf_to_json_test_Cyrl.BEL_Sans_8.json" 2>&1
Cyrl.BEL_Serif_12:
	-$(PYTHON) "data/multilingual/Cyrl.BEL/Serif_12/pdf_to_json_test_Cyrl.BEL_Serif_12.py" > "data/multilingual/Cyrl.BEL/Serif_12/pdf_to_json_test_Cyrl.BEL_Serif_12.json" 2>&1
Cyrl.BEL_Serif_16:
	-$(PYTHON) "data/multilingual/Cyrl.BEL/Serif_16/pdf_to_json_test_Cyrl.BEL_Serif_16.py" > "data/multilingual/Cyrl.BEL/Serif_16/pdf_to_json_test_Cyrl.BEL_Serif_16.json" 2>&1
Cyrl.BEL_Serif_8:
	-$(PYTHON) "data/multilingual/Cyrl.BEL/Serif_8/pdf_to_json_test_Cyrl.BEL_Serif_8.py" > "data/multilingual/Cyrl.BEL/Serif_8/pdf_to_json_test_Cyrl.BEL_Serif_8.json" 2>&1
Cyrl.BEL_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Cyrl.BEL/Sun-ExtA_12/pdf_to_json_test_Cyrl.BEL_Sun-ExtA_12.py" > "data/multilingual/Cyrl.BEL/Sun-ExtA_12/pdf_to_json_test_Cyrl.BEL_Sun-ExtA_12.json" 2>&1
Cyrl.BEL_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Cyrl.BEL/Sun-ExtA_16/pdf_to_json_test_Cyrl.BEL_Sun-ExtA_16.py" > "data/multilingual/Cyrl.BEL/Sun-ExtA_16/pdf_to_json_test_Cyrl.BEL_Sun-ExtA_16.json" 2>&1
Cyrl.BEL_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Cyrl.BEL/Sun-ExtA_8/pdf_to_json_test_Cyrl.BEL_Sun-ExtA_8.py" > "data/multilingual/Cyrl.BEL/Sun-ExtA_8/pdf_to_json_test_Cyrl.BEL_Sun-ExtA_8.json" 2>&1


Cyrl.BEL_all : Cyrl.BEL_Mono_12 Cyrl.BEL_Mono_16 Cyrl.BEL_Mono_8 Cyrl.BEL_Sans_12 Cyrl.BEL_Sans_16 Cyrl.BEL_Sans_8 Cyrl.BEL_Serif_12 Cyrl.BEL_Serif_16 Cyrl.BEL_Serif_8 Cyrl.BEL_Sun-ExtA_12 Cyrl.BEL_Sun-ExtA_16 Cyrl.BEL_Sun-ExtA_8
