PYTHON=python3


Latn.WOL_Mono_12:
	-$(PYTHON) data/multilingual/Latn.WOL/Mono_12/pdf_to_json_test_Latn.WOL_Mono_12.py > data/multilingual/Latn.WOL/Mono_12/pdf_to_json_test_Latn.WOL_Mono_12.json 2>&1
Latn.WOL_Mono_16:
	-$(PYTHON) data/multilingual/Latn.WOL/Mono_16/pdf_to_json_test_Latn.WOL_Mono_16.py > data/multilingual/Latn.WOL/Mono_16/pdf_to_json_test_Latn.WOL_Mono_16.json 2>&1
Latn.WOL_Mono_8:
	-$(PYTHON) data/multilingual/Latn.WOL/Mono_8/pdf_to_json_test_Latn.WOL_Mono_8.py > data/multilingual/Latn.WOL/Mono_8/pdf_to_json_test_Latn.WOL_Mono_8.json 2>&1
Latn.WOL_Sans_12:
	-$(PYTHON) data/multilingual/Latn.WOL/Sans_12/pdf_to_json_test_Latn.WOL_Sans_12.py > data/multilingual/Latn.WOL/Sans_12/pdf_to_json_test_Latn.WOL_Sans_12.json 2>&1
Latn.WOL_Sans_16:
	-$(PYTHON) data/multilingual/Latn.WOL/Sans_16/pdf_to_json_test_Latn.WOL_Sans_16.py > data/multilingual/Latn.WOL/Sans_16/pdf_to_json_test_Latn.WOL_Sans_16.json 2>&1
Latn.WOL_Sans_8:
	-$(PYTHON) data/multilingual/Latn.WOL/Sans_8/pdf_to_json_test_Latn.WOL_Sans_8.py > data/multilingual/Latn.WOL/Sans_8/pdf_to_json_test_Latn.WOL_Sans_8.json 2>&1
Latn.WOL_Serif_12:
	-$(PYTHON) data/multilingual/Latn.WOL/Serif_12/pdf_to_json_test_Latn.WOL_Serif_12.py > data/multilingual/Latn.WOL/Serif_12/pdf_to_json_test_Latn.WOL_Serif_12.json 2>&1
Latn.WOL_Serif_16:
	-$(PYTHON) data/multilingual/Latn.WOL/Serif_16/pdf_to_json_test_Latn.WOL_Serif_16.py > data/multilingual/Latn.WOL/Serif_16/pdf_to_json_test_Latn.WOL_Serif_16.json 2>&1
Latn.WOL_Serif_8:
	-$(PYTHON) data/multilingual/Latn.WOL/Serif_8/pdf_to_json_test_Latn.WOL_Serif_8.py > data/multilingual/Latn.WOL/Serif_8/pdf_to_json_test_Latn.WOL_Serif_8.json 2>&1
Latn.WOL_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.WOL/Sun-ExtA_12/pdf_to_json_test_Latn.WOL_Sun-ExtA_12.py > data/multilingual/Latn.WOL/Sun-ExtA_12/pdf_to_json_test_Latn.WOL_Sun-ExtA_12.json 2>&1
Latn.WOL_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.WOL/Sun-ExtA_16/pdf_to_json_test_Latn.WOL_Sun-ExtA_16.py > data/multilingual/Latn.WOL/Sun-ExtA_16/pdf_to_json_test_Latn.WOL_Sun-ExtA_16.json 2>&1
Latn.WOL_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.WOL/Sun-ExtA_8/pdf_to_json_test_Latn.WOL_Sun-ExtA_8.py > data/multilingual/Latn.WOL/Sun-ExtA_8/pdf_to_json_test_Latn.WOL_Sun-ExtA_8.json 2>&1


Latn.WOL_all : Latn.WOL_Mono_12 Latn.WOL_Mono_16 Latn.WOL_Mono_8 Latn.WOL_Sans_12 Latn.WOL_Sans_16 Latn.WOL_Sans_8 Latn.WOL_Serif_12 Latn.WOL_Serif_16 Latn.WOL_Serif_8 Latn.WOL_Sun-ExtA_12 Latn.WOL_Sun-ExtA_16 Latn.WOL_Sun-ExtA_8
