PYTHON=python3


Latn.POV_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.POV/Mono_12/pdf_to_json_test_Latn.POV_Mono_12.py" > "data/multilingual/Latn.POV/Mono_12/pdf_to_json_test_Latn.POV_Mono_12.json" 2>&1
Latn.POV_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.POV/Mono_16/pdf_to_json_test_Latn.POV_Mono_16.py" > "data/multilingual/Latn.POV/Mono_16/pdf_to_json_test_Latn.POV_Mono_16.json" 2>&1
Latn.POV_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.POV/Mono_8/pdf_to_json_test_Latn.POV_Mono_8.py" > "data/multilingual/Latn.POV/Mono_8/pdf_to_json_test_Latn.POV_Mono_8.json" 2>&1
Latn.POV_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.POV/Sans_12/pdf_to_json_test_Latn.POV_Sans_12.py" > "data/multilingual/Latn.POV/Sans_12/pdf_to_json_test_Latn.POV_Sans_12.json" 2>&1
Latn.POV_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.POV/Sans_16/pdf_to_json_test_Latn.POV_Sans_16.py" > "data/multilingual/Latn.POV/Sans_16/pdf_to_json_test_Latn.POV_Sans_16.json" 2>&1
Latn.POV_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.POV/Sans_8/pdf_to_json_test_Latn.POV_Sans_8.py" > "data/multilingual/Latn.POV/Sans_8/pdf_to_json_test_Latn.POV_Sans_8.json" 2>&1
Latn.POV_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.POV/Serif_12/pdf_to_json_test_Latn.POV_Serif_12.py" > "data/multilingual/Latn.POV/Serif_12/pdf_to_json_test_Latn.POV_Serif_12.json" 2>&1
Latn.POV_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.POV/Serif_16/pdf_to_json_test_Latn.POV_Serif_16.py" > "data/multilingual/Latn.POV/Serif_16/pdf_to_json_test_Latn.POV_Serif_16.json" 2>&1
Latn.POV_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.POV/Serif_8/pdf_to_json_test_Latn.POV_Serif_8.py" > "data/multilingual/Latn.POV/Serif_8/pdf_to_json_test_Latn.POV_Serif_8.json" 2>&1
Latn.POV_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.POV/Sun-ExtA_12/pdf_to_json_test_Latn.POV_Sun-ExtA_12.py" > "data/multilingual/Latn.POV/Sun-ExtA_12/pdf_to_json_test_Latn.POV_Sun-ExtA_12.json" 2>&1
Latn.POV_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.POV/Sun-ExtA_16/pdf_to_json_test_Latn.POV_Sun-ExtA_16.py" > "data/multilingual/Latn.POV/Sun-ExtA_16/pdf_to_json_test_Latn.POV_Sun-ExtA_16.json" 2>&1
Latn.POV_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.POV/Sun-ExtA_8/pdf_to_json_test_Latn.POV_Sun-ExtA_8.py" > "data/multilingual/Latn.POV/Sun-ExtA_8/pdf_to_json_test_Latn.POV_Sun-ExtA_8.json" 2>&1


Latn.POV_all : Latn.POV_Mono_12 Latn.POV_Mono_16 Latn.POV_Mono_8 Latn.POV_Sans_12 Latn.POV_Sans_16 Latn.POV_Sans_8 Latn.POV_Serif_12 Latn.POV_Serif_16 Latn.POV_Serif_8 Latn.POV_Sun-ExtA_12 Latn.POV_Sun-ExtA_16 Latn.POV_Sun-ExtA_8
