PYTHON=python3


Ethi.TIR_Mono_12:
	-$(PYTHON) data/multilingual/Ethi.TIR/Mono_12/pdf_to_json_test_Ethi.TIR_Mono_12.py > data/multilingual/Ethi.TIR/Mono_12/pdf_to_json_test_Ethi.TIR_Mono_12.json 2>&1
Ethi.TIR_Mono_16:
	-$(PYTHON) data/multilingual/Ethi.TIR/Mono_16/pdf_to_json_test_Ethi.TIR_Mono_16.py > data/multilingual/Ethi.TIR/Mono_16/pdf_to_json_test_Ethi.TIR_Mono_16.json 2>&1
Ethi.TIR_Mono_8:
	-$(PYTHON) data/multilingual/Ethi.TIR/Mono_8/pdf_to_json_test_Ethi.TIR_Mono_8.py > data/multilingual/Ethi.TIR/Mono_8/pdf_to_json_test_Ethi.TIR_Mono_8.json 2>&1
Ethi.TIR_Sans_12:
	-$(PYTHON) data/multilingual/Ethi.TIR/Sans_12/pdf_to_json_test_Ethi.TIR_Sans_12.py > data/multilingual/Ethi.TIR/Sans_12/pdf_to_json_test_Ethi.TIR_Sans_12.json 2>&1
Ethi.TIR_Sans_16:
	-$(PYTHON) data/multilingual/Ethi.TIR/Sans_16/pdf_to_json_test_Ethi.TIR_Sans_16.py > data/multilingual/Ethi.TIR/Sans_16/pdf_to_json_test_Ethi.TIR_Sans_16.json 2>&1
Ethi.TIR_Sans_8:
	-$(PYTHON) data/multilingual/Ethi.TIR/Sans_8/pdf_to_json_test_Ethi.TIR_Sans_8.py > data/multilingual/Ethi.TIR/Sans_8/pdf_to_json_test_Ethi.TIR_Sans_8.json 2>&1
Ethi.TIR_Serif_12:
	-$(PYTHON) data/multilingual/Ethi.TIR/Serif_12/pdf_to_json_test_Ethi.TIR_Serif_12.py > data/multilingual/Ethi.TIR/Serif_12/pdf_to_json_test_Ethi.TIR_Serif_12.json 2>&1
Ethi.TIR_Serif_16:
	-$(PYTHON) data/multilingual/Ethi.TIR/Serif_16/pdf_to_json_test_Ethi.TIR_Serif_16.py > data/multilingual/Ethi.TIR/Serif_16/pdf_to_json_test_Ethi.TIR_Serif_16.json 2>&1
Ethi.TIR_Serif_8:
	-$(PYTHON) data/multilingual/Ethi.TIR/Serif_8/pdf_to_json_test_Ethi.TIR_Serif_8.py > data/multilingual/Ethi.TIR/Serif_8/pdf_to_json_test_Ethi.TIR_Serif_8.json 2>&1
Ethi.TIR_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Ethi.TIR/Sun-ExtA_12/pdf_to_json_test_Ethi.TIR_Sun-ExtA_12.py > data/multilingual/Ethi.TIR/Sun-ExtA_12/pdf_to_json_test_Ethi.TIR_Sun-ExtA_12.json 2>&1
Ethi.TIR_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Ethi.TIR/Sun-ExtA_16/pdf_to_json_test_Ethi.TIR_Sun-ExtA_16.py > data/multilingual/Ethi.TIR/Sun-ExtA_16/pdf_to_json_test_Ethi.TIR_Sun-ExtA_16.json 2>&1
Ethi.TIR_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Ethi.TIR/Sun-ExtA_8/pdf_to_json_test_Ethi.TIR_Sun-ExtA_8.py > data/multilingual/Ethi.TIR/Sun-ExtA_8/pdf_to_json_test_Ethi.TIR_Sun-ExtA_8.json 2>&1


Ethi.TIR_all : Ethi.TIR_Mono_12 Ethi.TIR_Mono_16 Ethi.TIR_Mono_8 Ethi.TIR_Sans_12 Ethi.TIR_Sans_16 Ethi.TIR_Sans_8 Ethi.TIR_Serif_12 Ethi.TIR_Serif_16 Ethi.TIR_Serif_8 Ethi.TIR_Sun-ExtA_12 Ethi.TIR_Sun-ExtA_16 Ethi.TIR_Sun-ExtA_8
