PYTHON=python3


Latn.QVA_Mono_12:
	-$(PYTHON) data/multilingual/Latn.QVA/Mono_12/pdf_to_json_test_Latn.QVA_Mono_12.py > data/multilingual/Latn.QVA/Mono_12/pdf_to_json_test_Latn.QVA_Mono_12.json 2>&1
Latn.QVA_Mono_16:
	-$(PYTHON) data/multilingual/Latn.QVA/Mono_16/pdf_to_json_test_Latn.QVA_Mono_16.py > data/multilingual/Latn.QVA/Mono_16/pdf_to_json_test_Latn.QVA_Mono_16.json 2>&1
Latn.QVA_Mono_8:
	-$(PYTHON) data/multilingual/Latn.QVA/Mono_8/pdf_to_json_test_Latn.QVA_Mono_8.py > data/multilingual/Latn.QVA/Mono_8/pdf_to_json_test_Latn.QVA_Mono_8.json 2>&1
Latn.QVA_Sans_12:
	-$(PYTHON) data/multilingual/Latn.QVA/Sans_12/pdf_to_json_test_Latn.QVA_Sans_12.py > data/multilingual/Latn.QVA/Sans_12/pdf_to_json_test_Latn.QVA_Sans_12.json 2>&1
Latn.QVA_Sans_16:
	-$(PYTHON) data/multilingual/Latn.QVA/Sans_16/pdf_to_json_test_Latn.QVA_Sans_16.py > data/multilingual/Latn.QVA/Sans_16/pdf_to_json_test_Latn.QVA_Sans_16.json 2>&1
Latn.QVA_Sans_8:
	-$(PYTHON) data/multilingual/Latn.QVA/Sans_8/pdf_to_json_test_Latn.QVA_Sans_8.py > data/multilingual/Latn.QVA/Sans_8/pdf_to_json_test_Latn.QVA_Sans_8.json 2>&1
Latn.QVA_Serif_12:
	-$(PYTHON) data/multilingual/Latn.QVA/Serif_12/pdf_to_json_test_Latn.QVA_Serif_12.py > data/multilingual/Latn.QVA/Serif_12/pdf_to_json_test_Latn.QVA_Serif_12.json 2>&1
Latn.QVA_Serif_16:
	-$(PYTHON) data/multilingual/Latn.QVA/Serif_16/pdf_to_json_test_Latn.QVA_Serif_16.py > data/multilingual/Latn.QVA/Serif_16/pdf_to_json_test_Latn.QVA_Serif_16.json 2>&1
Latn.QVA_Serif_8:
	-$(PYTHON) data/multilingual/Latn.QVA/Serif_8/pdf_to_json_test_Latn.QVA_Serif_8.py > data/multilingual/Latn.QVA/Serif_8/pdf_to_json_test_Latn.QVA_Serif_8.json 2>&1
Latn.QVA_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.QVA/Sun-ExtA_12/pdf_to_json_test_Latn.QVA_Sun-ExtA_12.py > data/multilingual/Latn.QVA/Sun-ExtA_12/pdf_to_json_test_Latn.QVA_Sun-ExtA_12.json 2>&1
Latn.QVA_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.QVA/Sun-ExtA_16/pdf_to_json_test_Latn.QVA_Sun-ExtA_16.py > data/multilingual/Latn.QVA/Sun-ExtA_16/pdf_to_json_test_Latn.QVA_Sun-ExtA_16.json 2>&1
Latn.QVA_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.QVA/Sun-ExtA_8/pdf_to_json_test_Latn.QVA_Sun-ExtA_8.py > data/multilingual/Latn.QVA/Sun-ExtA_8/pdf_to_json_test_Latn.QVA_Sun-ExtA_8.json 2>&1


Latn.QVA_all : Latn.QVA_Mono_12 Latn.QVA_Mono_16 Latn.QVA_Mono_8 Latn.QVA_Sans_12 Latn.QVA_Sans_16 Latn.QVA_Sans_8 Latn.QVA_Serif_12 Latn.QVA_Serif_16 Latn.QVA_Serif_8 Latn.QVA_Sun-ExtA_12 Latn.QVA_Sun-ExtA_16 Latn.QVA_Sun-ExtA_8
