PYTHON=python3


Arab.ZLM_Mono_12:
	-$(PYTHON) data/multilingual/Arab.ZLM/Mono_12/pdf_to_json_test_Arab.ZLM_Mono_12.py > data/multilingual/Arab.ZLM/Mono_12/pdf_to_json_test_Arab.ZLM_Mono_12.json 2>&1
Arab.ZLM_Mono_16:
	-$(PYTHON) data/multilingual/Arab.ZLM/Mono_16/pdf_to_json_test_Arab.ZLM_Mono_16.py > data/multilingual/Arab.ZLM/Mono_16/pdf_to_json_test_Arab.ZLM_Mono_16.json 2>&1
Arab.ZLM_Mono_8:
	-$(PYTHON) data/multilingual/Arab.ZLM/Mono_8/pdf_to_json_test_Arab.ZLM_Mono_8.py > data/multilingual/Arab.ZLM/Mono_8/pdf_to_json_test_Arab.ZLM_Mono_8.json 2>&1
Arab.ZLM_Sans_12:
	-$(PYTHON) data/multilingual/Arab.ZLM/Sans_12/pdf_to_json_test_Arab.ZLM_Sans_12.py > data/multilingual/Arab.ZLM/Sans_12/pdf_to_json_test_Arab.ZLM_Sans_12.json 2>&1
Arab.ZLM_Sans_16:
	-$(PYTHON) data/multilingual/Arab.ZLM/Sans_16/pdf_to_json_test_Arab.ZLM_Sans_16.py > data/multilingual/Arab.ZLM/Sans_16/pdf_to_json_test_Arab.ZLM_Sans_16.json 2>&1
Arab.ZLM_Sans_8:
	-$(PYTHON) data/multilingual/Arab.ZLM/Sans_8/pdf_to_json_test_Arab.ZLM_Sans_8.py > data/multilingual/Arab.ZLM/Sans_8/pdf_to_json_test_Arab.ZLM_Sans_8.json 2>&1
Arab.ZLM_Serif_12:
	-$(PYTHON) data/multilingual/Arab.ZLM/Serif_12/pdf_to_json_test_Arab.ZLM_Serif_12.py > data/multilingual/Arab.ZLM/Serif_12/pdf_to_json_test_Arab.ZLM_Serif_12.json 2>&1
Arab.ZLM_Serif_16:
	-$(PYTHON) data/multilingual/Arab.ZLM/Serif_16/pdf_to_json_test_Arab.ZLM_Serif_16.py > data/multilingual/Arab.ZLM/Serif_16/pdf_to_json_test_Arab.ZLM_Serif_16.json 2>&1
Arab.ZLM_Serif_8:
	-$(PYTHON) data/multilingual/Arab.ZLM/Serif_8/pdf_to_json_test_Arab.ZLM_Serif_8.py > data/multilingual/Arab.ZLM/Serif_8/pdf_to_json_test_Arab.ZLM_Serif_8.json 2>&1
Arab.ZLM_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Arab.ZLM/Sun-ExtA_12/pdf_to_json_test_Arab.ZLM_Sun-ExtA_12.py > data/multilingual/Arab.ZLM/Sun-ExtA_12/pdf_to_json_test_Arab.ZLM_Sun-ExtA_12.json 2>&1
Arab.ZLM_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Arab.ZLM/Sun-ExtA_16/pdf_to_json_test_Arab.ZLM_Sun-ExtA_16.py > data/multilingual/Arab.ZLM/Sun-ExtA_16/pdf_to_json_test_Arab.ZLM_Sun-ExtA_16.json 2>&1
Arab.ZLM_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Arab.ZLM/Sun-ExtA_8/pdf_to_json_test_Arab.ZLM_Sun-ExtA_8.py > data/multilingual/Arab.ZLM/Sun-ExtA_8/pdf_to_json_test_Arab.ZLM_Sun-ExtA_8.json 2>&1


Arab.ZLM_all : Arab.ZLM_Mono_12 Arab.ZLM_Mono_16 Arab.ZLM_Mono_8 Arab.ZLM_Sans_12 Arab.ZLM_Sans_16 Arab.ZLM_Sans_8 Arab.ZLM_Serif_12 Arab.ZLM_Serif_16 Arab.ZLM_Serif_8 Arab.ZLM_Sun-ExtA_12 Arab.ZLM_Sun-ExtA_16 Arab.ZLM_Sun-ExtA_8
