PYTHON=python3


Hans.CJY_Mono_12:
	-$(PYTHON) data/multilingual/Hans.CJY/Mono_12/pdf_to_json_test_Hans.CJY_Mono_12.py > data/multilingual/Hans.CJY/Mono_12/pdf_to_json_test_Hans.CJY_Mono_12.json 2>&1
Hans.CJY_Mono_16:
	-$(PYTHON) data/multilingual/Hans.CJY/Mono_16/pdf_to_json_test_Hans.CJY_Mono_16.py > data/multilingual/Hans.CJY/Mono_16/pdf_to_json_test_Hans.CJY_Mono_16.json 2>&1
Hans.CJY_Mono_8:
	-$(PYTHON) data/multilingual/Hans.CJY/Mono_8/pdf_to_json_test_Hans.CJY_Mono_8.py > data/multilingual/Hans.CJY/Mono_8/pdf_to_json_test_Hans.CJY_Mono_8.json 2>&1
Hans.CJY_Sans_12:
	-$(PYTHON) data/multilingual/Hans.CJY/Sans_12/pdf_to_json_test_Hans.CJY_Sans_12.py > data/multilingual/Hans.CJY/Sans_12/pdf_to_json_test_Hans.CJY_Sans_12.json 2>&1
Hans.CJY_Sans_16:
	-$(PYTHON) data/multilingual/Hans.CJY/Sans_16/pdf_to_json_test_Hans.CJY_Sans_16.py > data/multilingual/Hans.CJY/Sans_16/pdf_to_json_test_Hans.CJY_Sans_16.json 2>&1
Hans.CJY_Sans_8:
	-$(PYTHON) data/multilingual/Hans.CJY/Sans_8/pdf_to_json_test_Hans.CJY_Sans_8.py > data/multilingual/Hans.CJY/Sans_8/pdf_to_json_test_Hans.CJY_Sans_8.json 2>&1
Hans.CJY_Serif_12:
	-$(PYTHON) data/multilingual/Hans.CJY/Serif_12/pdf_to_json_test_Hans.CJY_Serif_12.py > data/multilingual/Hans.CJY/Serif_12/pdf_to_json_test_Hans.CJY_Serif_12.json 2>&1
Hans.CJY_Serif_16:
	-$(PYTHON) data/multilingual/Hans.CJY/Serif_16/pdf_to_json_test_Hans.CJY_Serif_16.py > data/multilingual/Hans.CJY/Serif_16/pdf_to_json_test_Hans.CJY_Serif_16.json 2>&1
Hans.CJY_Serif_8:
	-$(PYTHON) data/multilingual/Hans.CJY/Serif_8/pdf_to_json_test_Hans.CJY_Serif_8.py > data/multilingual/Hans.CJY/Serif_8/pdf_to_json_test_Hans.CJY_Serif_8.json 2>&1
Hans.CJY_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Hans.CJY/Sun-ExtA_12/pdf_to_json_test_Hans.CJY_Sun-ExtA_12.py > data/multilingual/Hans.CJY/Sun-ExtA_12/pdf_to_json_test_Hans.CJY_Sun-ExtA_12.json 2>&1
Hans.CJY_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Hans.CJY/Sun-ExtA_16/pdf_to_json_test_Hans.CJY_Sun-ExtA_16.py > data/multilingual/Hans.CJY/Sun-ExtA_16/pdf_to_json_test_Hans.CJY_Sun-ExtA_16.json 2>&1
Hans.CJY_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Hans.CJY/Sun-ExtA_8/pdf_to_json_test_Hans.CJY_Sun-ExtA_8.py > data/multilingual/Hans.CJY/Sun-ExtA_8/pdf_to_json_test_Hans.CJY_Sun-ExtA_8.json 2>&1


Hans.CJY_all : Hans.CJY_Mono_12 Hans.CJY_Mono_16 Hans.CJY_Mono_8 Hans.CJY_Sans_12 Hans.CJY_Sans_16 Hans.CJY_Sans_8 Hans.CJY_Serif_12 Hans.CJY_Serif_16 Hans.CJY_Serif_8 Hans.CJY_Sun-ExtA_12 Hans.CJY_Sun-ExtA_16 Hans.CJY_Sun-ExtA_8
