PYTHON=python3


Cyrl.ALT_Mono_12:
	-$(PYTHON) data/multilingual/Cyrl.ALT/Mono_12/pdf_to_json_test_Cyrl.ALT_Mono_12.py > data/multilingual/Cyrl.ALT/Mono_12/pdf_to_json_test_Cyrl.ALT_Mono_12.json 2>&1
Cyrl.ALT_Mono_16:
	-$(PYTHON) data/multilingual/Cyrl.ALT/Mono_16/pdf_to_json_test_Cyrl.ALT_Mono_16.py > data/multilingual/Cyrl.ALT/Mono_16/pdf_to_json_test_Cyrl.ALT_Mono_16.json 2>&1
Cyrl.ALT_Mono_8:
	-$(PYTHON) data/multilingual/Cyrl.ALT/Mono_8/pdf_to_json_test_Cyrl.ALT_Mono_8.py > data/multilingual/Cyrl.ALT/Mono_8/pdf_to_json_test_Cyrl.ALT_Mono_8.json 2>&1
Cyrl.ALT_Sans_12:
	-$(PYTHON) data/multilingual/Cyrl.ALT/Sans_12/pdf_to_json_test_Cyrl.ALT_Sans_12.py > data/multilingual/Cyrl.ALT/Sans_12/pdf_to_json_test_Cyrl.ALT_Sans_12.json 2>&1
Cyrl.ALT_Sans_16:
	-$(PYTHON) data/multilingual/Cyrl.ALT/Sans_16/pdf_to_json_test_Cyrl.ALT_Sans_16.py > data/multilingual/Cyrl.ALT/Sans_16/pdf_to_json_test_Cyrl.ALT_Sans_16.json 2>&1
Cyrl.ALT_Sans_8:
	-$(PYTHON) data/multilingual/Cyrl.ALT/Sans_8/pdf_to_json_test_Cyrl.ALT_Sans_8.py > data/multilingual/Cyrl.ALT/Sans_8/pdf_to_json_test_Cyrl.ALT_Sans_8.json 2>&1
Cyrl.ALT_Serif_12:
	-$(PYTHON) data/multilingual/Cyrl.ALT/Serif_12/pdf_to_json_test_Cyrl.ALT_Serif_12.py > data/multilingual/Cyrl.ALT/Serif_12/pdf_to_json_test_Cyrl.ALT_Serif_12.json 2>&1
Cyrl.ALT_Serif_16:
	-$(PYTHON) data/multilingual/Cyrl.ALT/Serif_16/pdf_to_json_test_Cyrl.ALT_Serif_16.py > data/multilingual/Cyrl.ALT/Serif_16/pdf_to_json_test_Cyrl.ALT_Serif_16.json 2>&1
Cyrl.ALT_Serif_8:
	-$(PYTHON) data/multilingual/Cyrl.ALT/Serif_8/pdf_to_json_test_Cyrl.ALT_Serif_8.py > data/multilingual/Cyrl.ALT/Serif_8/pdf_to_json_test_Cyrl.ALT_Serif_8.json 2>&1
Cyrl.ALT_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Cyrl.ALT/Sun-ExtA_12/pdf_to_json_test_Cyrl.ALT_Sun-ExtA_12.py > data/multilingual/Cyrl.ALT/Sun-ExtA_12/pdf_to_json_test_Cyrl.ALT_Sun-ExtA_12.json 2>&1
Cyrl.ALT_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Cyrl.ALT/Sun-ExtA_16/pdf_to_json_test_Cyrl.ALT_Sun-ExtA_16.py > data/multilingual/Cyrl.ALT/Sun-ExtA_16/pdf_to_json_test_Cyrl.ALT_Sun-ExtA_16.json 2>&1
Cyrl.ALT_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Cyrl.ALT/Sun-ExtA_8/pdf_to_json_test_Cyrl.ALT_Sun-ExtA_8.py > data/multilingual/Cyrl.ALT/Sun-ExtA_8/pdf_to_json_test_Cyrl.ALT_Sun-ExtA_8.json 2>&1


Cyrl.ALT_all : Cyrl.ALT_Mono_12 Cyrl.ALT_Mono_16 Cyrl.ALT_Mono_8 Cyrl.ALT_Sans_12 Cyrl.ALT_Sans_16 Cyrl.ALT_Sans_8 Cyrl.ALT_Serif_12 Cyrl.ALT_Serif_16 Cyrl.ALT_Serif_8 Cyrl.ALT_Sun-ExtA_12 Cyrl.ALT_Sun-ExtA_16 Cyrl.ALT_Sun-ExtA_8
