PYTHON=python3


Latn.PAM_Mono_12:
	-$(PYTHON) data/multilingual/Latn.PAM/Mono_12/pdf_to_json_test_Latn.PAM_Mono_12.py > data/multilingual/Latn.PAM/Mono_12/pdf_to_json_test_Latn.PAM_Mono_12.json 2>&1
Latn.PAM_Mono_16:
	-$(PYTHON) data/multilingual/Latn.PAM/Mono_16/pdf_to_json_test_Latn.PAM_Mono_16.py > data/multilingual/Latn.PAM/Mono_16/pdf_to_json_test_Latn.PAM_Mono_16.json 2>&1
Latn.PAM_Mono_8:
	-$(PYTHON) data/multilingual/Latn.PAM/Mono_8/pdf_to_json_test_Latn.PAM_Mono_8.py > data/multilingual/Latn.PAM/Mono_8/pdf_to_json_test_Latn.PAM_Mono_8.json 2>&1
Latn.PAM_Sans_12:
	-$(PYTHON) data/multilingual/Latn.PAM/Sans_12/pdf_to_json_test_Latn.PAM_Sans_12.py > data/multilingual/Latn.PAM/Sans_12/pdf_to_json_test_Latn.PAM_Sans_12.json 2>&1
Latn.PAM_Sans_16:
	-$(PYTHON) data/multilingual/Latn.PAM/Sans_16/pdf_to_json_test_Latn.PAM_Sans_16.py > data/multilingual/Latn.PAM/Sans_16/pdf_to_json_test_Latn.PAM_Sans_16.json 2>&1
Latn.PAM_Sans_8:
	-$(PYTHON) data/multilingual/Latn.PAM/Sans_8/pdf_to_json_test_Latn.PAM_Sans_8.py > data/multilingual/Latn.PAM/Sans_8/pdf_to_json_test_Latn.PAM_Sans_8.json 2>&1
Latn.PAM_Serif_12:
	-$(PYTHON) data/multilingual/Latn.PAM/Serif_12/pdf_to_json_test_Latn.PAM_Serif_12.py > data/multilingual/Latn.PAM/Serif_12/pdf_to_json_test_Latn.PAM_Serif_12.json 2>&1
Latn.PAM_Serif_16:
	-$(PYTHON) data/multilingual/Latn.PAM/Serif_16/pdf_to_json_test_Latn.PAM_Serif_16.py > data/multilingual/Latn.PAM/Serif_16/pdf_to_json_test_Latn.PAM_Serif_16.json 2>&1
Latn.PAM_Serif_8:
	-$(PYTHON) data/multilingual/Latn.PAM/Serif_8/pdf_to_json_test_Latn.PAM_Serif_8.py > data/multilingual/Latn.PAM/Serif_8/pdf_to_json_test_Latn.PAM_Serif_8.json 2>&1
Latn.PAM_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.PAM/Sun-ExtA_12/pdf_to_json_test_Latn.PAM_Sun-ExtA_12.py > data/multilingual/Latn.PAM/Sun-ExtA_12/pdf_to_json_test_Latn.PAM_Sun-ExtA_12.json 2>&1
Latn.PAM_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.PAM/Sun-ExtA_16/pdf_to_json_test_Latn.PAM_Sun-ExtA_16.py > data/multilingual/Latn.PAM/Sun-ExtA_16/pdf_to_json_test_Latn.PAM_Sun-ExtA_16.json 2>&1
Latn.PAM_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.PAM/Sun-ExtA_8/pdf_to_json_test_Latn.PAM_Sun-ExtA_8.py > data/multilingual/Latn.PAM/Sun-ExtA_8/pdf_to_json_test_Latn.PAM_Sun-ExtA_8.json 2>&1


Latn.PAM_all : Latn.PAM_Mono_12 Latn.PAM_Mono_16 Latn.PAM_Mono_8 Latn.PAM_Sans_12 Latn.PAM_Sans_16 Latn.PAM_Sans_8 Latn.PAM_Serif_12 Latn.PAM_Serif_16 Latn.PAM_Serif_8 Latn.PAM_Sun-ExtA_12 Latn.PAM_Sun-ExtA_16 Latn.PAM_Sun-ExtA_8
