PYTHON=python3


Latn.TON_Mono_12:
	-$(PYTHON) data/multilingual/Latn.TON/Mono_12/pdf_to_json_test_Latn.TON_Mono_12.py > data/multilingual/Latn.TON/Mono_12/pdf_to_json_test_Latn.TON_Mono_12.json 2>&1
Latn.TON_Mono_16:
	-$(PYTHON) data/multilingual/Latn.TON/Mono_16/pdf_to_json_test_Latn.TON_Mono_16.py > data/multilingual/Latn.TON/Mono_16/pdf_to_json_test_Latn.TON_Mono_16.json 2>&1
Latn.TON_Mono_8:
	-$(PYTHON) data/multilingual/Latn.TON/Mono_8/pdf_to_json_test_Latn.TON_Mono_8.py > data/multilingual/Latn.TON/Mono_8/pdf_to_json_test_Latn.TON_Mono_8.json 2>&1
Latn.TON_Sans_12:
	-$(PYTHON) data/multilingual/Latn.TON/Sans_12/pdf_to_json_test_Latn.TON_Sans_12.py > data/multilingual/Latn.TON/Sans_12/pdf_to_json_test_Latn.TON_Sans_12.json 2>&1
Latn.TON_Sans_16:
	-$(PYTHON) data/multilingual/Latn.TON/Sans_16/pdf_to_json_test_Latn.TON_Sans_16.py > data/multilingual/Latn.TON/Sans_16/pdf_to_json_test_Latn.TON_Sans_16.json 2>&1
Latn.TON_Sans_8:
	-$(PYTHON) data/multilingual/Latn.TON/Sans_8/pdf_to_json_test_Latn.TON_Sans_8.py > data/multilingual/Latn.TON/Sans_8/pdf_to_json_test_Latn.TON_Sans_8.json 2>&1
Latn.TON_Serif_12:
	-$(PYTHON) data/multilingual/Latn.TON/Serif_12/pdf_to_json_test_Latn.TON_Serif_12.py > data/multilingual/Latn.TON/Serif_12/pdf_to_json_test_Latn.TON_Serif_12.json 2>&1
Latn.TON_Serif_16:
	-$(PYTHON) data/multilingual/Latn.TON/Serif_16/pdf_to_json_test_Latn.TON_Serif_16.py > data/multilingual/Latn.TON/Serif_16/pdf_to_json_test_Latn.TON_Serif_16.json 2>&1
Latn.TON_Serif_8:
	-$(PYTHON) data/multilingual/Latn.TON/Serif_8/pdf_to_json_test_Latn.TON_Serif_8.py > data/multilingual/Latn.TON/Serif_8/pdf_to_json_test_Latn.TON_Serif_8.json 2>&1
Latn.TON_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.TON/Sun-ExtA_12/pdf_to_json_test_Latn.TON_Sun-ExtA_12.py > data/multilingual/Latn.TON/Sun-ExtA_12/pdf_to_json_test_Latn.TON_Sun-ExtA_12.json 2>&1
Latn.TON_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.TON/Sun-ExtA_16/pdf_to_json_test_Latn.TON_Sun-ExtA_16.py > data/multilingual/Latn.TON/Sun-ExtA_16/pdf_to_json_test_Latn.TON_Sun-ExtA_16.json 2>&1
Latn.TON_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.TON/Sun-ExtA_8/pdf_to_json_test_Latn.TON_Sun-ExtA_8.py > data/multilingual/Latn.TON/Sun-ExtA_8/pdf_to_json_test_Latn.TON_Sun-ExtA_8.json 2>&1


Latn.TON_all : Latn.TON_Mono_12 Latn.TON_Mono_16 Latn.TON_Mono_8 Latn.TON_Sans_12 Latn.TON_Sans_16 Latn.TON_Sans_8 Latn.TON_Serif_12 Latn.TON_Serif_16 Latn.TON_Serif_8 Latn.TON_Sun-ExtA_12 Latn.TON_Sun-ExtA_16 Latn.TON_Sun-ExtA_8
