PYTHON=python3


Latn.QWH_Mono_12:
	-$(PYTHON) data/multilingual/Latn.QWH/Mono_12/pdf_to_json_test_Latn.QWH_Mono_12.py > data/multilingual/Latn.QWH/Mono_12/pdf_to_json_test_Latn.QWH_Mono_12.json 2>&1
Latn.QWH_Mono_16:
	-$(PYTHON) data/multilingual/Latn.QWH/Mono_16/pdf_to_json_test_Latn.QWH_Mono_16.py > data/multilingual/Latn.QWH/Mono_16/pdf_to_json_test_Latn.QWH_Mono_16.json 2>&1
Latn.QWH_Mono_8:
	-$(PYTHON) data/multilingual/Latn.QWH/Mono_8/pdf_to_json_test_Latn.QWH_Mono_8.py > data/multilingual/Latn.QWH/Mono_8/pdf_to_json_test_Latn.QWH_Mono_8.json 2>&1
Latn.QWH_Sans_12:
	-$(PYTHON) data/multilingual/Latn.QWH/Sans_12/pdf_to_json_test_Latn.QWH_Sans_12.py > data/multilingual/Latn.QWH/Sans_12/pdf_to_json_test_Latn.QWH_Sans_12.json 2>&1
Latn.QWH_Sans_16:
	-$(PYTHON) data/multilingual/Latn.QWH/Sans_16/pdf_to_json_test_Latn.QWH_Sans_16.py > data/multilingual/Latn.QWH/Sans_16/pdf_to_json_test_Latn.QWH_Sans_16.json 2>&1
Latn.QWH_Sans_8:
	-$(PYTHON) data/multilingual/Latn.QWH/Sans_8/pdf_to_json_test_Latn.QWH_Sans_8.py > data/multilingual/Latn.QWH/Sans_8/pdf_to_json_test_Latn.QWH_Sans_8.json 2>&1
Latn.QWH_Serif_12:
	-$(PYTHON) data/multilingual/Latn.QWH/Serif_12/pdf_to_json_test_Latn.QWH_Serif_12.py > data/multilingual/Latn.QWH/Serif_12/pdf_to_json_test_Latn.QWH_Serif_12.json 2>&1
Latn.QWH_Serif_16:
	-$(PYTHON) data/multilingual/Latn.QWH/Serif_16/pdf_to_json_test_Latn.QWH_Serif_16.py > data/multilingual/Latn.QWH/Serif_16/pdf_to_json_test_Latn.QWH_Serif_16.json 2>&1
Latn.QWH_Serif_8:
	-$(PYTHON) data/multilingual/Latn.QWH/Serif_8/pdf_to_json_test_Latn.QWH_Serif_8.py > data/multilingual/Latn.QWH/Serif_8/pdf_to_json_test_Latn.QWH_Serif_8.json 2>&1
Latn.QWH_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.QWH/Sun-ExtA_12/pdf_to_json_test_Latn.QWH_Sun-ExtA_12.py > data/multilingual/Latn.QWH/Sun-ExtA_12/pdf_to_json_test_Latn.QWH_Sun-ExtA_12.json 2>&1
Latn.QWH_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.QWH/Sun-ExtA_16/pdf_to_json_test_Latn.QWH_Sun-ExtA_16.py > data/multilingual/Latn.QWH/Sun-ExtA_16/pdf_to_json_test_Latn.QWH_Sun-ExtA_16.json 2>&1
Latn.QWH_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.QWH/Sun-ExtA_8/pdf_to_json_test_Latn.QWH_Sun-ExtA_8.py > data/multilingual/Latn.QWH/Sun-ExtA_8/pdf_to_json_test_Latn.QWH_Sun-ExtA_8.json 2>&1


Latn.QWH_all : Latn.QWH_Mono_12 Latn.QWH_Mono_16 Latn.QWH_Mono_8 Latn.QWH_Sans_12 Latn.QWH_Sans_16 Latn.QWH_Sans_8 Latn.QWH_Serif_12 Latn.QWH_Serif_16 Latn.QWH_Serif_8 Latn.QWH_Sun-ExtA_12 Latn.QWH_Sun-ExtA_16 Latn.QWH_Sun-ExtA_8
