PYTHON=python3


Latn.CAT_Mono_12:
	-$(PYTHON) data/multilingual/Latn.CAT/Mono_12/pdf_to_json_test_Latn.CAT_Mono_12.py > data/multilingual/Latn.CAT/Mono_12/pdf_to_json_test_Latn.CAT_Mono_12.json 2>&1
Latn.CAT_Mono_16:
	-$(PYTHON) data/multilingual/Latn.CAT/Mono_16/pdf_to_json_test_Latn.CAT_Mono_16.py > data/multilingual/Latn.CAT/Mono_16/pdf_to_json_test_Latn.CAT_Mono_16.json 2>&1
Latn.CAT_Mono_8:
	-$(PYTHON) data/multilingual/Latn.CAT/Mono_8/pdf_to_json_test_Latn.CAT_Mono_8.py > data/multilingual/Latn.CAT/Mono_8/pdf_to_json_test_Latn.CAT_Mono_8.json 2>&1
Latn.CAT_Sans_12:
	-$(PYTHON) data/multilingual/Latn.CAT/Sans_12/pdf_to_json_test_Latn.CAT_Sans_12.py > data/multilingual/Latn.CAT/Sans_12/pdf_to_json_test_Latn.CAT_Sans_12.json 2>&1
Latn.CAT_Sans_16:
	-$(PYTHON) data/multilingual/Latn.CAT/Sans_16/pdf_to_json_test_Latn.CAT_Sans_16.py > data/multilingual/Latn.CAT/Sans_16/pdf_to_json_test_Latn.CAT_Sans_16.json 2>&1
Latn.CAT_Sans_8:
	-$(PYTHON) data/multilingual/Latn.CAT/Sans_8/pdf_to_json_test_Latn.CAT_Sans_8.py > data/multilingual/Latn.CAT/Sans_8/pdf_to_json_test_Latn.CAT_Sans_8.json 2>&1
Latn.CAT_Serif_12:
	-$(PYTHON) data/multilingual/Latn.CAT/Serif_12/pdf_to_json_test_Latn.CAT_Serif_12.py > data/multilingual/Latn.CAT/Serif_12/pdf_to_json_test_Latn.CAT_Serif_12.json 2>&1
Latn.CAT_Serif_16:
	-$(PYTHON) data/multilingual/Latn.CAT/Serif_16/pdf_to_json_test_Latn.CAT_Serif_16.py > data/multilingual/Latn.CAT/Serif_16/pdf_to_json_test_Latn.CAT_Serif_16.json 2>&1
Latn.CAT_Serif_8:
	-$(PYTHON) data/multilingual/Latn.CAT/Serif_8/pdf_to_json_test_Latn.CAT_Serif_8.py > data/multilingual/Latn.CAT/Serif_8/pdf_to_json_test_Latn.CAT_Serif_8.json 2>&1
Latn.CAT_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.CAT/Sun-ExtA_12/pdf_to_json_test_Latn.CAT_Sun-ExtA_12.py > data/multilingual/Latn.CAT/Sun-ExtA_12/pdf_to_json_test_Latn.CAT_Sun-ExtA_12.json 2>&1
Latn.CAT_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.CAT/Sun-ExtA_16/pdf_to_json_test_Latn.CAT_Sun-ExtA_16.py > data/multilingual/Latn.CAT/Sun-ExtA_16/pdf_to_json_test_Latn.CAT_Sun-ExtA_16.json 2>&1
Latn.CAT_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.CAT/Sun-ExtA_8/pdf_to_json_test_Latn.CAT_Sun-ExtA_8.py > data/multilingual/Latn.CAT/Sun-ExtA_8/pdf_to_json_test_Latn.CAT_Sun-ExtA_8.json 2>&1


Latn.CAT_all : Latn.CAT_Mono_12 Latn.CAT_Mono_16 Latn.CAT_Mono_8 Latn.CAT_Sans_12 Latn.CAT_Sans_16 Latn.CAT_Sans_8 Latn.CAT_Serif_12 Latn.CAT_Serif_16 Latn.CAT_Serif_8 Latn.CAT_Sun-ExtA_12 Latn.CAT_Sun-ExtA_16 Latn.CAT_Sun-ExtA_8
