PYTHON=python3


Latn.LLD_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.LLD/Mono_12/pdf_to_json_test_Latn.LLD_Mono_12.py" > "data/multilingual/Latn.LLD/Mono_12/pdf_to_json_test_Latn.LLD_Mono_12.json" 2>&1
Latn.LLD_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.LLD/Mono_16/pdf_to_json_test_Latn.LLD_Mono_16.py" > "data/multilingual/Latn.LLD/Mono_16/pdf_to_json_test_Latn.LLD_Mono_16.json" 2>&1
Latn.LLD_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.LLD/Mono_8/pdf_to_json_test_Latn.LLD_Mono_8.py" > "data/multilingual/Latn.LLD/Mono_8/pdf_to_json_test_Latn.LLD_Mono_8.json" 2>&1
Latn.LLD_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.LLD/Sans_12/pdf_to_json_test_Latn.LLD_Sans_12.py" > "data/multilingual/Latn.LLD/Sans_12/pdf_to_json_test_Latn.LLD_Sans_12.json" 2>&1
Latn.LLD_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.LLD/Sans_16/pdf_to_json_test_Latn.LLD_Sans_16.py" > "data/multilingual/Latn.LLD/Sans_16/pdf_to_json_test_Latn.LLD_Sans_16.json" 2>&1
Latn.LLD_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.LLD/Sans_8/pdf_to_json_test_Latn.LLD_Sans_8.py" > "data/multilingual/Latn.LLD/Sans_8/pdf_to_json_test_Latn.LLD_Sans_8.json" 2>&1
Latn.LLD_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.LLD/Serif_12/pdf_to_json_test_Latn.LLD_Serif_12.py" > "data/multilingual/Latn.LLD/Serif_12/pdf_to_json_test_Latn.LLD_Serif_12.json" 2>&1
Latn.LLD_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.LLD/Serif_16/pdf_to_json_test_Latn.LLD_Serif_16.py" > "data/multilingual/Latn.LLD/Serif_16/pdf_to_json_test_Latn.LLD_Serif_16.json" 2>&1
Latn.LLD_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.LLD/Serif_8/pdf_to_json_test_Latn.LLD_Serif_8.py" > "data/multilingual/Latn.LLD/Serif_8/pdf_to_json_test_Latn.LLD_Serif_8.json" 2>&1
Latn.LLD_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.LLD/Sun-ExtA_12/pdf_to_json_test_Latn.LLD_Sun-ExtA_12.py" > "data/multilingual/Latn.LLD/Sun-ExtA_12/pdf_to_json_test_Latn.LLD_Sun-ExtA_12.json" 2>&1
Latn.LLD_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.LLD/Sun-ExtA_16/pdf_to_json_test_Latn.LLD_Sun-ExtA_16.py" > "data/multilingual/Latn.LLD/Sun-ExtA_16/pdf_to_json_test_Latn.LLD_Sun-ExtA_16.json" 2>&1
Latn.LLD_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.LLD/Sun-ExtA_8/pdf_to_json_test_Latn.LLD_Sun-ExtA_8.py" > "data/multilingual/Latn.LLD/Sun-ExtA_8/pdf_to_json_test_Latn.LLD_Sun-ExtA_8.json" 2>&1


Latn.LLD_all : Latn.LLD_Mono_12 Latn.LLD_Mono_16 Latn.LLD_Mono_8 Latn.LLD_Sans_12 Latn.LLD_Sans_16 Latn.LLD_Sans_8 Latn.LLD_Serif_12 Latn.LLD_Serif_16 Latn.LLD_Serif_8 Latn.LLD_Sun-ExtA_12 Latn.LLD_Sun-ExtA_16 Latn.LLD_Sun-ExtA_8
