PYTHON=python3


Deva.MAR_Mono_12:
	-$(PYTHON) data/multilingual/Deva.MAR/Mono_12/pdf_to_json_test_Deva.MAR_Mono_12.py > data/multilingual/Deva.MAR/Mono_12/pdf_to_json_test_Deva.MAR_Mono_12.json 2>&1
Deva.MAR_Mono_16:
	-$(PYTHON) data/multilingual/Deva.MAR/Mono_16/pdf_to_json_test_Deva.MAR_Mono_16.py > data/multilingual/Deva.MAR/Mono_16/pdf_to_json_test_Deva.MAR_Mono_16.json 2>&1
Deva.MAR_Mono_8:
	-$(PYTHON) data/multilingual/Deva.MAR/Mono_8/pdf_to_json_test_Deva.MAR_Mono_8.py > data/multilingual/Deva.MAR/Mono_8/pdf_to_json_test_Deva.MAR_Mono_8.json 2>&1
Deva.MAR_Sans_12:
	-$(PYTHON) data/multilingual/Deva.MAR/Sans_12/pdf_to_json_test_Deva.MAR_Sans_12.py > data/multilingual/Deva.MAR/Sans_12/pdf_to_json_test_Deva.MAR_Sans_12.json 2>&1
Deva.MAR_Sans_16:
	-$(PYTHON) data/multilingual/Deva.MAR/Sans_16/pdf_to_json_test_Deva.MAR_Sans_16.py > data/multilingual/Deva.MAR/Sans_16/pdf_to_json_test_Deva.MAR_Sans_16.json 2>&1
Deva.MAR_Sans_8:
	-$(PYTHON) data/multilingual/Deva.MAR/Sans_8/pdf_to_json_test_Deva.MAR_Sans_8.py > data/multilingual/Deva.MAR/Sans_8/pdf_to_json_test_Deva.MAR_Sans_8.json 2>&1
Deva.MAR_Serif_12:
	-$(PYTHON) data/multilingual/Deva.MAR/Serif_12/pdf_to_json_test_Deva.MAR_Serif_12.py > data/multilingual/Deva.MAR/Serif_12/pdf_to_json_test_Deva.MAR_Serif_12.json 2>&1
Deva.MAR_Serif_16:
	-$(PYTHON) data/multilingual/Deva.MAR/Serif_16/pdf_to_json_test_Deva.MAR_Serif_16.py > data/multilingual/Deva.MAR/Serif_16/pdf_to_json_test_Deva.MAR_Serif_16.json 2>&1
Deva.MAR_Serif_8:
	-$(PYTHON) data/multilingual/Deva.MAR/Serif_8/pdf_to_json_test_Deva.MAR_Serif_8.py > data/multilingual/Deva.MAR/Serif_8/pdf_to_json_test_Deva.MAR_Serif_8.json 2>&1
Deva.MAR_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Deva.MAR/Sun-ExtA_12/pdf_to_json_test_Deva.MAR_Sun-ExtA_12.py > data/multilingual/Deva.MAR/Sun-ExtA_12/pdf_to_json_test_Deva.MAR_Sun-ExtA_12.json 2>&1
Deva.MAR_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Deva.MAR/Sun-ExtA_16/pdf_to_json_test_Deva.MAR_Sun-ExtA_16.py > data/multilingual/Deva.MAR/Sun-ExtA_16/pdf_to_json_test_Deva.MAR_Sun-ExtA_16.json 2>&1
Deva.MAR_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Deva.MAR/Sun-ExtA_8/pdf_to_json_test_Deva.MAR_Sun-ExtA_8.py > data/multilingual/Deva.MAR/Sun-ExtA_8/pdf_to_json_test_Deva.MAR_Sun-ExtA_8.json 2>&1


Deva.MAR_all : Deva.MAR_Mono_12 Deva.MAR_Mono_16 Deva.MAR_Mono_8 Deva.MAR_Sans_12 Deva.MAR_Sans_16 Deva.MAR_Sans_8 Deva.MAR_Serif_12 Deva.MAR_Serif_16 Deva.MAR_Serif_8 Deva.MAR_Sun-ExtA_12 Deva.MAR_Sun-ExtA_16 Deva.MAR_Sun-ExtA_8
