PYTHON=python3


Latn.FIN_Mono_12:
	-$(PYTHON) data/multilingual/Latn.FIN/Mono_12/pdf_to_json_test_Latn.FIN_Mono_12.py > data/multilingual/Latn.FIN/Mono_12/pdf_to_json_test_Latn.FIN_Mono_12.json 2>&1
Latn.FIN_Mono_16:
	-$(PYTHON) data/multilingual/Latn.FIN/Mono_16/pdf_to_json_test_Latn.FIN_Mono_16.py > data/multilingual/Latn.FIN/Mono_16/pdf_to_json_test_Latn.FIN_Mono_16.json 2>&1
Latn.FIN_Mono_8:
	-$(PYTHON) data/multilingual/Latn.FIN/Mono_8/pdf_to_json_test_Latn.FIN_Mono_8.py > data/multilingual/Latn.FIN/Mono_8/pdf_to_json_test_Latn.FIN_Mono_8.json 2>&1
Latn.FIN_Sans_12:
	-$(PYTHON) data/multilingual/Latn.FIN/Sans_12/pdf_to_json_test_Latn.FIN_Sans_12.py > data/multilingual/Latn.FIN/Sans_12/pdf_to_json_test_Latn.FIN_Sans_12.json 2>&1
Latn.FIN_Sans_16:
	-$(PYTHON) data/multilingual/Latn.FIN/Sans_16/pdf_to_json_test_Latn.FIN_Sans_16.py > data/multilingual/Latn.FIN/Sans_16/pdf_to_json_test_Latn.FIN_Sans_16.json 2>&1
Latn.FIN_Sans_8:
	-$(PYTHON) data/multilingual/Latn.FIN/Sans_8/pdf_to_json_test_Latn.FIN_Sans_8.py > data/multilingual/Latn.FIN/Sans_8/pdf_to_json_test_Latn.FIN_Sans_8.json 2>&1
Latn.FIN_Serif_12:
	-$(PYTHON) data/multilingual/Latn.FIN/Serif_12/pdf_to_json_test_Latn.FIN_Serif_12.py > data/multilingual/Latn.FIN/Serif_12/pdf_to_json_test_Latn.FIN_Serif_12.json 2>&1
Latn.FIN_Serif_16:
	-$(PYTHON) data/multilingual/Latn.FIN/Serif_16/pdf_to_json_test_Latn.FIN_Serif_16.py > data/multilingual/Latn.FIN/Serif_16/pdf_to_json_test_Latn.FIN_Serif_16.json 2>&1
Latn.FIN_Serif_8:
	-$(PYTHON) data/multilingual/Latn.FIN/Serif_8/pdf_to_json_test_Latn.FIN_Serif_8.py > data/multilingual/Latn.FIN/Serif_8/pdf_to_json_test_Latn.FIN_Serif_8.json 2>&1
Latn.FIN_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.FIN/Sun-ExtA_12/pdf_to_json_test_Latn.FIN_Sun-ExtA_12.py > data/multilingual/Latn.FIN/Sun-ExtA_12/pdf_to_json_test_Latn.FIN_Sun-ExtA_12.json 2>&1
Latn.FIN_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.FIN/Sun-ExtA_16/pdf_to_json_test_Latn.FIN_Sun-ExtA_16.py > data/multilingual/Latn.FIN/Sun-ExtA_16/pdf_to_json_test_Latn.FIN_Sun-ExtA_16.json 2>&1
Latn.FIN_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.FIN/Sun-ExtA_8/pdf_to_json_test_Latn.FIN_Sun-ExtA_8.py > data/multilingual/Latn.FIN/Sun-ExtA_8/pdf_to_json_test_Latn.FIN_Sun-ExtA_8.json 2>&1


Latn.FIN_all : Latn.FIN_Mono_12 Latn.FIN_Mono_16 Latn.FIN_Mono_8 Latn.FIN_Sans_12 Latn.FIN_Sans_16 Latn.FIN_Sans_8 Latn.FIN_Serif_12 Latn.FIN_Serif_16 Latn.FIN_Serif_8 Latn.FIN_Sun-ExtA_12 Latn.FIN_Sun-ExtA_16 Latn.FIN_Sun-ExtA_8
