PYTHON=python3


Latn.KIN_Mono_12:
	-$(PYTHON) data/multilingual/Latn.KIN/Mono_12/pdf_to_json_test_Latn.KIN_Mono_12.py > data/multilingual/Latn.KIN/Mono_12/pdf_to_json_test_Latn.KIN_Mono_12.json 2>&1
Latn.KIN_Mono_16:
	-$(PYTHON) data/multilingual/Latn.KIN/Mono_16/pdf_to_json_test_Latn.KIN_Mono_16.py > data/multilingual/Latn.KIN/Mono_16/pdf_to_json_test_Latn.KIN_Mono_16.json 2>&1
Latn.KIN_Mono_8:
	-$(PYTHON) data/multilingual/Latn.KIN/Mono_8/pdf_to_json_test_Latn.KIN_Mono_8.py > data/multilingual/Latn.KIN/Mono_8/pdf_to_json_test_Latn.KIN_Mono_8.json 2>&1
Latn.KIN_Sans_12:
	-$(PYTHON) data/multilingual/Latn.KIN/Sans_12/pdf_to_json_test_Latn.KIN_Sans_12.py > data/multilingual/Latn.KIN/Sans_12/pdf_to_json_test_Latn.KIN_Sans_12.json 2>&1
Latn.KIN_Sans_16:
	-$(PYTHON) data/multilingual/Latn.KIN/Sans_16/pdf_to_json_test_Latn.KIN_Sans_16.py > data/multilingual/Latn.KIN/Sans_16/pdf_to_json_test_Latn.KIN_Sans_16.json 2>&1
Latn.KIN_Sans_8:
	-$(PYTHON) data/multilingual/Latn.KIN/Sans_8/pdf_to_json_test_Latn.KIN_Sans_8.py > data/multilingual/Latn.KIN/Sans_8/pdf_to_json_test_Latn.KIN_Sans_8.json 2>&1
Latn.KIN_Serif_12:
	-$(PYTHON) data/multilingual/Latn.KIN/Serif_12/pdf_to_json_test_Latn.KIN_Serif_12.py > data/multilingual/Latn.KIN/Serif_12/pdf_to_json_test_Latn.KIN_Serif_12.json 2>&1
Latn.KIN_Serif_16:
	-$(PYTHON) data/multilingual/Latn.KIN/Serif_16/pdf_to_json_test_Latn.KIN_Serif_16.py > data/multilingual/Latn.KIN/Serif_16/pdf_to_json_test_Latn.KIN_Serif_16.json 2>&1
Latn.KIN_Serif_8:
	-$(PYTHON) data/multilingual/Latn.KIN/Serif_8/pdf_to_json_test_Latn.KIN_Serif_8.py > data/multilingual/Latn.KIN/Serif_8/pdf_to_json_test_Latn.KIN_Serif_8.json 2>&1
Latn.KIN_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.KIN/Sun-ExtA_12/pdf_to_json_test_Latn.KIN_Sun-ExtA_12.py > data/multilingual/Latn.KIN/Sun-ExtA_12/pdf_to_json_test_Latn.KIN_Sun-ExtA_12.json 2>&1
Latn.KIN_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.KIN/Sun-ExtA_16/pdf_to_json_test_Latn.KIN_Sun-ExtA_16.py > data/multilingual/Latn.KIN/Sun-ExtA_16/pdf_to_json_test_Latn.KIN_Sun-ExtA_16.json 2>&1
Latn.KIN_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.KIN/Sun-ExtA_8/pdf_to_json_test_Latn.KIN_Sun-ExtA_8.py > data/multilingual/Latn.KIN/Sun-ExtA_8/pdf_to_json_test_Latn.KIN_Sun-ExtA_8.json 2>&1


Latn.KIN_all : Latn.KIN_Mono_12 Latn.KIN_Mono_16 Latn.KIN_Mono_8 Latn.KIN_Sans_12 Latn.KIN_Sans_16 Latn.KIN_Sans_8 Latn.KIN_Serif_12 Latn.KIN_Serif_16 Latn.KIN_Serif_8 Latn.KIN_Sun-ExtA_12 Latn.KIN_Sun-ExtA_16 Latn.KIN_Sun-ExtA_8
