PYTHON=python3


Latn.GAA_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.GAA/Mono_12/pdf_to_json_test_Latn.GAA_Mono_12.py" > "data/multilingual/Latn.GAA/Mono_12/pdf_to_json_test_Latn.GAA_Mono_12.json" 2>&1
Latn.GAA_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.GAA/Mono_16/pdf_to_json_test_Latn.GAA_Mono_16.py" > "data/multilingual/Latn.GAA/Mono_16/pdf_to_json_test_Latn.GAA_Mono_16.json" 2>&1
Latn.GAA_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.GAA/Mono_8/pdf_to_json_test_Latn.GAA_Mono_8.py" > "data/multilingual/Latn.GAA/Mono_8/pdf_to_json_test_Latn.GAA_Mono_8.json" 2>&1
Latn.GAA_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.GAA/Sans_12/pdf_to_json_test_Latn.GAA_Sans_12.py" > "data/multilingual/Latn.GAA/Sans_12/pdf_to_json_test_Latn.GAA_Sans_12.json" 2>&1
Latn.GAA_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.GAA/Sans_16/pdf_to_json_test_Latn.GAA_Sans_16.py" > "data/multilingual/Latn.GAA/Sans_16/pdf_to_json_test_Latn.GAA_Sans_16.json" 2>&1
Latn.GAA_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.GAA/Sans_8/pdf_to_json_test_Latn.GAA_Sans_8.py" > "data/multilingual/Latn.GAA/Sans_8/pdf_to_json_test_Latn.GAA_Sans_8.json" 2>&1
Latn.GAA_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.GAA/Serif_12/pdf_to_json_test_Latn.GAA_Serif_12.py" > "data/multilingual/Latn.GAA/Serif_12/pdf_to_json_test_Latn.GAA_Serif_12.json" 2>&1
Latn.GAA_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.GAA/Serif_16/pdf_to_json_test_Latn.GAA_Serif_16.py" > "data/multilingual/Latn.GAA/Serif_16/pdf_to_json_test_Latn.GAA_Serif_16.json" 2>&1
Latn.GAA_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.GAA/Serif_8/pdf_to_json_test_Latn.GAA_Serif_8.py" > "data/multilingual/Latn.GAA/Serif_8/pdf_to_json_test_Latn.GAA_Serif_8.json" 2>&1
Latn.GAA_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.GAA/Sun-ExtA_12/pdf_to_json_test_Latn.GAA_Sun-ExtA_12.py" > "data/multilingual/Latn.GAA/Sun-ExtA_12/pdf_to_json_test_Latn.GAA_Sun-ExtA_12.json" 2>&1
Latn.GAA_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.GAA/Sun-ExtA_16/pdf_to_json_test_Latn.GAA_Sun-ExtA_16.py" > "data/multilingual/Latn.GAA/Sun-ExtA_16/pdf_to_json_test_Latn.GAA_Sun-ExtA_16.json" 2>&1
Latn.GAA_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.GAA/Sun-ExtA_8/pdf_to_json_test_Latn.GAA_Sun-ExtA_8.py" > "data/multilingual/Latn.GAA/Sun-ExtA_8/pdf_to_json_test_Latn.GAA_Sun-ExtA_8.json" 2>&1


Latn.GAA_all : Latn.GAA_Mono_12 Latn.GAA_Mono_16 Latn.GAA_Mono_8 Latn.GAA_Sans_12 Latn.GAA_Sans_16 Latn.GAA_Sans_8 Latn.GAA_Serif_12 Latn.GAA_Serif_16 Latn.GAA_Serif_8 Latn.GAA_Sun-ExtA_12 Latn.GAA_Sun-ExtA_16 Latn.GAA_Sun-ExtA_8
