PYTHON=python3


Latn.MCF_Mono_12:
	-$(PYTHON) data/multilingual/Latn.MCF/Mono_12/pdf_to_json_test_Latn.MCF_Mono_12.py > data/multilingual/Latn.MCF/Mono_12/pdf_to_json_test_Latn.MCF_Mono_12.json 2>&1
Latn.MCF_Mono_16:
	-$(PYTHON) data/multilingual/Latn.MCF/Mono_16/pdf_to_json_test_Latn.MCF_Mono_16.py > data/multilingual/Latn.MCF/Mono_16/pdf_to_json_test_Latn.MCF_Mono_16.json 2>&1
Latn.MCF_Mono_8:
	-$(PYTHON) data/multilingual/Latn.MCF/Mono_8/pdf_to_json_test_Latn.MCF_Mono_8.py > data/multilingual/Latn.MCF/Mono_8/pdf_to_json_test_Latn.MCF_Mono_8.json 2>&1
Latn.MCF_Sans_12:
	-$(PYTHON) data/multilingual/Latn.MCF/Sans_12/pdf_to_json_test_Latn.MCF_Sans_12.py > data/multilingual/Latn.MCF/Sans_12/pdf_to_json_test_Latn.MCF_Sans_12.json 2>&1
Latn.MCF_Sans_16:
	-$(PYTHON) data/multilingual/Latn.MCF/Sans_16/pdf_to_json_test_Latn.MCF_Sans_16.py > data/multilingual/Latn.MCF/Sans_16/pdf_to_json_test_Latn.MCF_Sans_16.json 2>&1
Latn.MCF_Sans_8:
	-$(PYTHON) data/multilingual/Latn.MCF/Sans_8/pdf_to_json_test_Latn.MCF_Sans_8.py > data/multilingual/Latn.MCF/Sans_8/pdf_to_json_test_Latn.MCF_Sans_8.json 2>&1
Latn.MCF_Serif_12:
	-$(PYTHON) data/multilingual/Latn.MCF/Serif_12/pdf_to_json_test_Latn.MCF_Serif_12.py > data/multilingual/Latn.MCF/Serif_12/pdf_to_json_test_Latn.MCF_Serif_12.json 2>&1
Latn.MCF_Serif_16:
	-$(PYTHON) data/multilingual/Latn.MCF/Serif_16/pdf_to_json_test_Latn.MCF_Serif_16.py > data/multilingual/Latn.MCF/Serif_16/pdf_to_json_test_Latn.MCF_Serif_16.json 2>&1
Latn.MCF_Serif_8:
	-$(PYTHON) data/multilingual/Latn.MCF/Serif_8/pdf_to_json_test_Latn.MCF_Serif_8.py > data/multilingual/Latn.MCF/Serif_8/pdf_to_json_test_Latn.MCF_Serif_8.json 2>&1
Latn.MCF_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.MCF/Sun-ExtA_12/pdf_to_json_test_Latn.MCF_Sun-ExtA_12.py > data/multilingual/Latn.MCF/Sun-ExtA_12/pdf_to_json_test_Latn.MCF_Sun-ExtA_12.json 2>&1
Latn.MCF_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.MCF/Sun-ExtA_16/pdf_to_json_test_Latn.MCF_Sun-ExtA_16.py > data/multilingual/Latn.MCF/Sun-ExtA_16/pdf_to_json_test_Latn.MCF_Sun-ExtA_16.json 2>&1
Latn.MCF_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.MCF/Sun-ExtA_8/pdf_to_json_test_Latn.MCF_Sun-ExtA_8.py > data/multilingual/Latn.MCF/Sun-ExtA_8/pdf_to_json_test_Latn.MCF_Sun-ExtA_8.json 2>&1


Latn.MCF_all : Latn.MCF_Mono_12 Latn.MCF_Mono_16 Latn.MCF_Mono_8 Latn.MCF_Sans_12 Latn.MCF_Sans_16 Latn.MCF_Sans_8 Latn.MCF_Serif_12 Latn.MCF_Serif_16 Latn.MCF_Serif_8 Latn.MCF_Sun-ExtA_12 Latn.MCF_Sun-ExtA_16 Latn.MCF_Sun-ExtA_8
