PYTHON=python3


Tglg.TGL_Baybayin_Lopez_12:
	-$(PYTHON) "data/multilingual/Tglg.TGL/Baybayin Lopez_12/pdf_to_json_test_Tglg.TGL_Baybayin_Lopez_12.py" > "data/multilingual/Tglg.TGL/Baybayin Lopez_12/pdf_to_json_test_Tglg.TGL_Baybayin_Lopez_12.json" 2>&1
Tglg.TGL_Baybayin_Lopez_16:
	-$(PYTHON) "data/multilingual/Tglg.TGL/Baybayin Lopez_16/pdf_to_json_test_Tglg.TGL_Baybayin_Lopez_16.py" > "data/multilingual/Tglg.TGL/Baybayin Lopez_16/pdf_to_json_test_Tglg.TGL_Baybayin_Lopez_16.json" 2>&1
Tglg.TGL_Baybayin_Lopez_8:
	-$(PYTHON) "data/multilingual/Tglg.TGL/Baybayin Lopez_8/pdf_to_json_test_Tglg.TGL_Baybayin_Lopez_8.py" > "data/multilingual/Tglg.TGL/Baybayin Lopez_8/pdf_to_json_test_Tglg.TGL_Baybayin_Lopez_8.json" 2>&1
Tglg.TGL_Bikol_Mintz_12:
	-$(PYTHON) "data/multilingual/Tglg.TGL/Bikol Mintz_12/pdf_to_json_test_Tglg.TGL_Bikol_Mintz_12.py" > "data/multilingual/Tglg.TGL/Bikol Mintz_12/pdf_to_json_test_Tglg.TGL_Bikol_Mintz_12.json" 2>&1
Tglg.TGL_Bikol_Mintz_16:
	-$(PYTHON) "data/multilingual/Tglg.TGL/Bikol Mintz_16/pdf_to_json_test_Tglg.TGL_Bikol_Mintz_16.py" > "data/multilingual/Tglg.TGL/Bikol Mintz_16/pdf_to_json_test_Tglg.TGL_Bikol_Mintz_16.json" 2>&1
Tglg.TGL_Bikol_Mintz_8:
	-$(PYTHON) "data/multilingual/Tglg.TGL/Bikol Mintz_8/pdf_to_json_test_Tglg.TGL_Bikol_Mintz_8.py" > "data/multilingual/Tglg.TGL/Bikol Mintz_8/pdf_to_json_test_Tglg.TGL_Bikol_Mintz_8.json" 2>&1
Tglg.TGL_Bisaya_Hervas_12:
	-$(PYTHON) "data/multilingual/Tglg.TGL/Bisaya Hervas_12/pdf_to_json_test_Tglg.TGL_Bisaya_Hervas_12.py" > "data/multilingual/Tglg.TGL/Bisaya Hervas_12/pdf_to_json_test_Tglg.TGL_Bisaya_Hervas_12.json" 2>&1
Tglg.TGL_Bisaya_Hervas_16:
	-$(PYTHON) "data/multilingual/Tglg.TGL/Bisaya Hervas_16/pdf_to_json_test_Tglg.TGL_Bisaya_Hervas_16.py" > "data/multilingual/Tglg.TGL/Bisaya Hervas_16/pdf_to_json_test_Tglg.TGL_Bisaya_Hervas_16.json" 2>&1
Tglg.TGL_Bisaya_Hervas_8:
	-$(PYTHON) "data/multilingual/Tglg.TGL/Bisaya Hervas_8/pdf_to_json_test_Tglg.TGL_Bisaya_Hervas_8.py" > "data/multilingual/Tglg.TGL/Bisaya Hervas_8/pdf_to_json_test_Tglg.TGL_Bisaya_Hervas_8.json" 2>&1
Tglg.TGL_Quivira_12:
	-$(PYTHON) "data/multilingual/Tglg.TGL/Quivira_12/pdf_to_json_test_Tglg.TGL_Quivira_12.py" > "data/multilingual/Tglg.TGL/Quivira_12/pdf_to_json_test_Tglg.TGL_Quivira_12.json" 2>&1
Tglg.TGL_Quivira_16:
	-$(PYTHON) "data/multilingual/Tglg.TGL/Quivira_16/pdf_to_json_test_Tglg.TGL_Quivira_16.py" > "data/multilingual/Tglg.TGL/Quivira_16/pdf_to_json_test_Tglg.TGL_Quivira_16.json" 2>&1
Tglg.TGL_Quivira_8:
	-$(PYTHON) "data/multilingual/Tglg.TGL/Quivira_8/pdf_to_json_test_Tglg.TGL_Quivira_8.py" > "data/multilingual/Tglg.TGL/Quivira_8/pdf_to_json_test_Tglg.TGL_Quivira_8.json" 2>&1
Tglg.TGL_Tagalog_Stylized_12:
	-$(PYTHON) "data/multilingual/Tglg.TGL/Tagalog Stylized_12/pdf_to_json_test_Tglg.TGL_Tagalog_Stylized_12.py" > "data/multilingual/Tglg.TGL/Tagalog Stylized_12/pdf_to_json_test_Tglg.TGL_Tagalog_Stylized_12.json" 2>&1
Tglg.TGL_Tagalog_Stylized_16:
	-$(PYTHON) "data/multilingual/Tglg.TGL/Tagalog Stylized_16/pdf_to_json_test_Tglg.TGL_Tagalog_Stylized_16.py" > "data/multilingual/Tglg.TGL/Tagalog Stylized_16/pdf_to_json_test_Tglg.TGL_Tagalog_Stylized_16.json" 2>&1
Tglg.TGL_Tagalog_Stylized_8:
	-$(PYTHON) "data/multilingual/Tglg.TGL/Tagalog Stylized_8/pdf_to_json_test_Tglg.TGL_Tagalog_Stylized_8.py" > "data/multilingual/Tglg.TGL/Tagalog Stylized_8/pdf_to_json_test_Tglg.TGL_Tagalog_Stylized_8.json" 2>&1


Tglg.TGL_all : Tglg.TGL_Baybayin_Lopez_12 Tglg.TGL_Baybayin_Lopez_16 Tglg.TGL_Baybayin_Lopez_8 Tglg.TGL_Bikol_Mintz_12 Tglg.TGL_Bikol_Mintz_16 Tglg.TGL_Bikol_Mintz_8 Tglg.TGL_Bisaya_Hervas_12 Tglg.TGL_Bisaya_Hervas_16 Tglg.TGL_Bisaya_Hervas_8 Tglg.TGL_Quivira_12 Tglg.TGL_Quivira_16 Tglg.TGL_Quivira_8 Tglg.TGL_Tagalog_Stylized_12 Tglg.TGL_Tagalog_Stylized_16 Tglg.TGL_Tagalog_Stylized_8
