PYTHON=python3


Latn.MOS_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.MOS/Mono_12/pdf_to_json_test_Latn.MOS_Mono_12.py" > "data/multilingual/Latn.MOS/Mono_12/pdf_to_json_test_Latn.MOS_Mono_12.json" 2>&1
Latn.MOS_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.MOS/Mono_16/pdf_to_json_test_Latn.MOS_Mono_16.py" > "data/multilingual/Latn.MOS/Mono_16/pdf_to_json_test_Latn.MOS_Mono_16.json" 2>&1
Latn.MOS_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.MOS/Mono_8/pdf_to_json_test_Latn.MOS_Mono_8.py" > "data/multilingual/Latn.MOS/Mono_8/pdf_to_json_test_Latn.MOS_Mono_8.json" 2>&1
Latn.MOS_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.MOS/Sans_12/pdf_to_json_test_Latn.MOS_Sans_12.py" > "data/multilingual/Latn.MOS/Sans_12/pdf_to_json_test_Latn.MOS_Sans_12.json" 2>&1
Latn.MOS_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.MOS/Sans_16/pdf_to_json_test_Latn.MOS_Sans_16.py" > "data/multilingual/Latn.MOS/Sans_16/pdf_to_json_test_Latn.MOS_Sans_16.json" 2>&1
Latn.MOS_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.MOS/Sans_8/pdf_to_json_test_Latn.MOS_Sans_8.py" > "data/multilingual/Latn.MOS/Sans_8/pdf_to_json_test_Latn.MOS_Sans_8.json" 2>&1
Latn.MOS_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.MOS/Serif_12/pdf_to_json_test_Latn.MOS_Serif_12.py" > "data/multilingual/Latn.MOS/Serif_12/pdf_to_json_test_Latn.MOS_Serif_12.json" 2>&1
Latn.MOS_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.MOS/Serif_16/pdf_to_json_test_Latn.MOS_Serif_16.py" > "data/multilingual/Latn.MOS/Serif_16/pdf_to_json_test_Latn.MOS_Serif_16.json" 2>&1
Latn.MOS_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.MOS/Serif_8/pdf_to_json_test_Latn.MOS_Serif_8.py" > "data/multilingual/Latn.MOS/Serif_8/pdf_to_json_test_Latn.MOS_Serif_8.json" 2>&1
Latn.MOS_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.MOS/Sun-ExtA_12/pdf_to_json_test_Latn.MOS_Sun-ExtA_12.py" > "data/multilingual/Latn.MOS/Sun-ExtA_12/pdf_to_json_test_Latn.MOS_Sun-ExtA_12.json" 2>&1
Latn.MOS_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.MOS/Sun-ExtA_16/pdf_to_json_test_Latn.MOS_Sun-ExtA_16.py" > "data/multilingual/Latn.MOS/Sun-ExtA_16/pdf_to_json_test_Latn.MOS_Sun-ExtA_16.json" 2>&1
Latn.MOS_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.MOS/Sun-ExtA_8/pdf_to_json_test_Latn.MOS_Sun-ExtA_8.py" > "data/multilingual/Latn.MOS/Sun-ExtA_8/pdf_to_json_test_Latn.MOS_Sun-ExtA_8.json" 2>&1


Latn.MOS_all : Latn.MOS_Mono_12 Latn.MOS_Mono_16 Latn.MOS_Mono_8 Latn.MOS_Sans_12 Latn.MOS_Sans_16 Latn.MOS_Sans_8 Latn.MOS_Serif_12 Latn.MOS_Serif_16 Latn.MOS_Serif_8 Latn.MOS_Sun-ExtA_12 Latn.MOS_Sun-ExtA_16 Latn.MOS_Sun-ExtA_8
