PYTHON=python3


Latn.TOJ_Mono_12:
	-$(PYTHON) data/multilingual/Latn.TOJ/Mono_12/pdf_to_json_test_Latn.TOJ_Mono_12.py > data/multilingual/Latn.TOJ/Mono_12/pdf_to_json_test_Latn.TOJ_Mono_12.json 2>&1
Latn.TOJ_Mono_16:
	-$(PYTHON) data/multilingual/Latn.TOJ/Mono_16/pdf_to_json_test_Latn.TOJ_Mono_16.py > data/multilingual/Latn.TOJ/Mono_16/pdf_to_json_test_Latn.TOJ_Mono_16.json 2>&1
Latn.TOJ_Mono_8:
	-$(PYTHON) data/multilingual/Latn.TOJ/Mono_8/pdf_to_json_test_Latn.TOJ_Mono_8.py > data/multilingual/Latn.TOJ/Mono_8/pdf_to_json_test_Latn.TOJ_Mono_8.json 2>&1
Latn.TOJ_Sans_12:
	-$(PYTHON) data/multilingual/Latn.TOJ/Sans_12/pdf_to_json_test_Latn.TOJ_Sans_12.py > data/multilingual/Latn.TOJ/Sans_12/pdf_to_json_test_Latn.TOJ_Sans_12.json 2>&1
Latn.TOJ_Sans_16:
	-$(PYTHON) data/multilingual/Latn.TOJ/Sans_16/pdf_to_json_test_Latn.TOJ_Sans_16.py > data/multilingual/Latn.TOJ/Sans_16/pdf_to_json_test_Latn.TOJ_Sans_16.json 2>&1
Latn.TOJ_Sans_8:
	-$(PYTHON) data/multilingual/Latn.TOJ/Sans_8/pdf_to_json_test_Latn.TOJ_Sans_8.py > data/multilingual/Latn.TOJ/Sans_8/pdf_to_json_test_Latn.TOJ_Sans_8.json 2>&1
Latn.TOJ_Serif_12:
	-$(PYTHON) data/multilingual/Latn.TOJ/Serif_12/pdf_to_json_test_Latn.TOJ_Serif_12.py > data/multilingual/Latn.TOJ/Serif_12/pdf_to_json_test_Latn.TOJ_Serif_12.json 2>&1
Latn.TOJ_Serif_16:
	-$(PYTHON) data/multilingual/Latn.TOJ/Serif_16/pdf_to_json_test_Latn.TOJ_Serif_16.py > data/multilingual/Latn.TOJ/Serif_16/pdf_to_json_test_Latn.TOJ_Serif_16.json 2>&1
Latn.TOJ_Serif_8:
	-$(PYTHON) data/multilingual/Latn.TOJ/Serif_8/pdf_to_json_test_Latn.TOJ_Serif_8.py > data/multilingual/Latn.TOJ/Serif_8/pdf_to_json_test_Latn.TOJ_Serif_8.json 2>&1
Latn.TOJ_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.TOJ/Sun-ExtA_12/pdf_to_json_test_Latn.TOJ_Sun-ExtA_12.py > data/multilingual/Latn.TOJ/Sun-ExtA_12/pdf_to_json_test_Latn.TOJ_Sun-ExtA_12.json 2>&1
Latn.TOJ_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.TOJ/Sun-ExtA_16/pdf_to_json_test_Latn.TOJ_Sun-ExtA_16.py > data/multilingual/Latn.TOJ/Sun-ExtA_16/pdf_to_json_test_Latn.TOJ_Sun-ExtA_16.json 2>&1
Latn.TOJ_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.TOJ/Sun-ExtA_8/pdf_to_json_test_Latn.TOJ_Sun-ExtA_8.py > data/multilingual/Latn.TOJ/Sun-ExtA_8/pdf_to_json_test_Latn.TOJ_Sun-ExtA_8.json 2>&1


Latn.TOJ_all : Latn.TOJ_Mono_12 Latn.TOJ_Mono_16 Latn.TOJ_Mono_8 Latn.TOJ_Sans_12 Latn.TOJ_Sans_16 Latn.TOJ_Sans_8 Latn.TOJ_Serif_12 Latn.TOJ_Serif_16 Latn.TOJ_Serif_8 Latn.TOJ_Sun-ExtA_12 Latn.TOJ_Sun-ExtA_16 Latn.TOJ_Sun-ExtA_8
