PYTHON=python3


Latn.ROH_Mono_12:
	-$(PYTHON) data/multilingual/Latn.ROH/Mono_12/pdf_to_json_test_Latn.ROH_Mono_12.py > data/multilingual/Latn.ROH/Mono_12/pdf_to_json_test_Latn.ROH_Mono_12.json 2>&1
Latn.ROH_Mono_16:
	-$(PYTHON) data/multilingual/Latn.ROH/Mono_16/pdf_to_json_test_Latn.ROH_Mono_16.py > data/multilingual/Latn.ROH/Mono_16/pdf_to_json_test_Latn.ROH_Mono_16.json 2>&1
Latn.ROH_Mono_8:
	-$(PYTHON) data/multilingual/Latn.ROH/Mono_8/pdf_to_json_test_Latn.ROH_Mono_8.py > data/multilingual/Latn.ROH/Mono_8/pdf_to_json_test_Latn.ROH_Mono_8.json 2>&1
Latn.ROH_Sans_12:
	-$(PYTHON) data/multilingual/Latn.ROH/Sans_12/pdf_to_json_test_Latn.ROH_Sans_12.py > data/multilingual/Latn.ROH/Sans_12/pdf_to_json_test_Latn.ROH_Sans_12.json 2>&1
Latn.ROH_Sans_16:
	-$(PYTHON) data/multilingual/Latn.ROH/Sans_16/pdf_to_json_test_Latn.ROH_Sans_16.py > data/multilingual/Latn.ROH/Sans_16/pdf_to_json_test_Latn.ROH_Sans_16.json 2>&1
Latn.ROH_Sans_8:
	-$(PYTHON) data/multilingual/Latn.ROH/Sans_8/pdf_to_json_test_Latn.ROH_Sans_8.py > data/multilingual/Latn.ROH/Sans_8/pdf_to_json_test_Latn.ROH_Sans_8.json 2>&1
Latn.ROH_Serif_12:
	-$(PYTHON) data/multilingual/Latn.ROH/Serif_12/pdf_to_json_test_Latn.ROH_Serif_12.py > data/multilingual/Latn.ROH/Serif_12/pdf_to_json_test_Latn.ROH_Serif_12.json 2>&1
Latn.ROH_Serif_16:
	-$(PYTHON) data/multilingual/Latn.ROH/Serif_16/pdf_to_json_test_Latn.ROH_Serif_16.py > data/multilingual/Latn.ROH/Serif_16/pdf_to_json_test_Latn.ROH_Serif_16.json 2>&1
Latn.ROH_Serif_8:
	-$(PYTHON) data/multilingual/Latn.ROH/Serif_8/pdf_to_json_test_Latn.ROH_Serif_8.py > data/multilingual/Latn.ROH/Serif_8/pdf_to_json_test_Latn.ROH_Serif_8.json 2>&1
Latn.ROH_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.ROH/Sun-ExtA_12/pdf_to_json_test_Latn.ROH_Sun-ExtA_12.py > data/multilingual/Latn.ROH/Sun-ExtA_12/pdf_to_json_test_Latn.ROH_Sun-ExtA_12.json 2>&1
Latn.ROH_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.ROH/Sun-ExtA_16/pdf_to_json_test_Latn.ROH_Sun-ExtA_16.py > data/multilingual/Latn.ROH/Sun-ExtA_16/pdf_to_json_test_Latn.ROH_Sun-ExtA_16.json 2>&1
Latn.ROH_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.ROH/Sun-ExtA_8/pdf_to_json_test_Latn.ROH_Sun-ExtA_8.py > data/multilingual/Latn.ROH/Sun-ExtA_8/pdf_to_json_test_Latn.ROH_Sun-ExtA_8.json 2>&1


Latn.ROH_all : Latn.ROH_Mono_12 Latn.ROH_Mono_16 Latn.ROH_Mono_8 Latn.ROH_Sans_12 Latn.ROH_Sans_16 Latn.ROH_Sans_8 Latn.ROH_Serif_12 Latn.ROH_Serif_16 Latn.ROH_Serif_8 Latn.ROH_Sun-ExtA_12 Latn.ROH_Sun-ExtA_16 Latn.ROH_Sun-ExtA_8
