PYTHON=python3


Latn.DGA_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.DGA/Mono_12/pdf_to_json_test_Latn.DGA_Mono_12.py" > "data/multilingual/Latn.DGA/Mono_12/pdf_to_json_test_Latn.DGA_Mono_12.json" 2>&1
Latn.DGA_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.DGA/Mono_16/pdf_to_json_test_Latn.DGA_Mono_16.py" > "data/multilingual/Latn.DGA/Mono_16/pdf_to_json_test_Latn.DGA_Mono_16.json" 2>&1
Latn.DGA_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.DGA/Mono_8/pdf_to_json_test_Latn.DGA_Mono_8.py" > "data/multilingual/Latn.DGA/Mono_8/pdf_to_json_test_Latn.DGA_Mono_8.json" 2>&1
Latn.DGA_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.DGA/Sans_12/pdf_to_json_test_Latn.DGA_Sans_12.py" > "data/multilingual/Latn.DGA/Sans_12/pdf_to_json_test_Latn.DGA_Sans_12.json" 2>&1
Latn.DGA_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.DGA/Sans_16/pdf_to_json_test_Latn.DGA_Sans_16.py" > "data/multilingual/Latn.DGA/Sans_16/pdf_to_json_test_Latn.DGA_Sans_16.json" 2>&1
Latn.DGA_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.DGA/Sans_8/pdf_to_json_test_Latn.DGA_Sans_8.py" > "data/multilingual/Latn.DGA/Sans_8/pdf_to_json_test_Latn.DGA_Sans_8.json" 2>&1
Latn.DGA_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.DGA/Serif_12/pdf_to_json_test_Latn.DGA_Serif_12.py" > "data/multilingual/Latn.DGA/Serif_12/pdf_to_json_test_Latn.DGA_Serif_12.json" 2>&1
Latn.DGA_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.DGA/Serif_16/pdf_to_json_test_Latn.DGA_Serif_16.py" > "data/multilingual/Latn.DGA/Serif_16/pdf_to_json_test_Latn.DGA_Serif_16.json" 2>&1
Latn.DGA_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.DGA/Serif_8/pdf_to_json_test_Latn.DGA_Serif_8.py" > "data/multilingual/Latn.DGA/Serif_8/pdf_to_json_test_Latn.DGA_Serif_8.json" 2>&1
Latn.DGA_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.DGA/Sun-ExtA_12/pdf_to_json_test_Latn.DGA_Sun-ExtA_12.py" > "data/multilingual/Latn.DGA/Sun-ExtA_12/pdf_to_json_test_Latn.DGA_Sun-ExtA_12.json" 2>&1
Latn.DGA_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.DGA/Sun-ExtA_16/pdf_to_json_test_Latn.DGA_Sun-ExtA_16.py" > "data/multilingual/Latn.DGA/Sun-ExtA_16/pdf_to_json_test_Latn.DGA_Sun-ExtA_16.json" 2>&1
Latn.DGA_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.DGA/Sun-ExtA_8/pdf_to_json_test_Latn.DGA_Sun-ExtA_8.py" > "data/multilingual/Latn.DGA/Sun-ExtA_8/pdf_to_json_test_Latn.DGA_Sun-ExtA_8.json" 2>&1


Latn.DGA_all : Latn.DGA_Mono_12 Latn.DGA_Mono_16 Latn.DGA_Mono_8 Latn.DGA_Sans_12 Latn.DGA_Sans_16 Latn.DGA_Sans_8 Latn.DGA_Serif_12 Latn.DGA_Serif_16 Latn.DGA_Serif_8 Latn.DGA_Sun-ExtA_12 Latn.DGA_Sun-ExtA_16 Latn.DGA_Sun-ExtA_8
