PYTHON=python3


Lana.KKH_Noto_Sans_Tai_Tham_12:
	-$(PYTHON) data/multilingual/Lana.KKH/Noto Sans Tai Tham_12/pdf_to_json_test_Lana.KKH_Noto_Sans_Tai_Tham_12.py > data/multilingual/Lana.KKH/Noto Sans Tai Tham_12/pdf_to_json_test_Lana.KKH_Noto_Sans_Tai_Tham_12.json 2>&1
Lana.KKH_Noto_Sans_Tai_Tham_16:
	-$(PYTHON) data/multilingual/Lana.KKH/Noto Sans Tai Tham_16/pdf_to_json_test_Lana.KKH_Noto_Sans_Tai_Tham_16.py > data/multilingual/Lana.KKH/Noto Sans Tai Tham_16/pdf_to_json_test_Lana.KKH_Noto_Sans_Tai_Tham_16.json 2>&1
Lana.KKH_Noto_Sans_Tai_Tham_8:
	-$(PYTHON) data/multilingual/Lana.KKH/Noto Sans Tai Tham_8/pdf_to_json_test_Lana.KKH_Noto_Sans_Tai_Tham_8.py > data/multilingual/Lana.KKH/Noto Sans Tai Tham_8/pdf_to_json_test_Lana.KKH_Noto_Sans_Tai_Tham_8.json 2>&1


Lana.KKH_all : Lana.KKH_Noto_Sans_Tai_Tham_12 Lana.KKH_Noto_Sans_Tai_Tham_16 Lana.KKH_Noto_Sans_Tai_Tham_8
