PYTHON=python3


Latn.QUC_Mono_12:
	-$(PYTHON) data/multilingual/Latn.QUC/Mono_12/pdf_to_json_test_Latn.QUC_Mono_12.py > data/multilingual/Latn.QUC/Mono_12/pdf_to_json_test_Latn.QUC_Mono_12.json 2>&1
Latn.QUC_Mono_16:
	-$(PYTHON) data/multilingual/Latn.QUC/Mono_16/pdf_to_json_test_Latn.QUC_Mono_16.py > data/multilingual/Latn.QUC/Mono_16/pdf_to_json_test_Latn.QUC_Mono_16.json 2>&1
Latn.QUC_Mono_8:
	-$(PYTHON) data/multilingual/Latn.QUC/Mono_8/pdf_to_json_test_Latn.QUC_Mono_8.py > data/multilingual/Latn.QUC/Mono_8/pdf_to_json_test_Latn.QUC_Mono_8.json 2>&1
Latn.QUC_Sans_12:
	-$(PYTHON) data/multilingual/Latn.QUC/Sans_12/pdf_to_json_test_Latn.QUC_Sans_12.py > data/multilingual/Latn.QUC/Sans_12/pdf_to_json_test_Latn.QUC_Sans_12.json 2>&1
Latn.QUC_Sans_16:
	-$(PYTHON) data/multilingual/Latn.QUC/Sans_16/pdf_to_json_test_Latn.QUC_Sans_16.py > data/multilingual/Latn.QUC/Sans_16/pdf_to_json_test_Latn.QUC_Sans_16.json 2>&1
Latn.QUC_Sans_8:
	-$(PYTHON) data/multilingual/Latn.QUC/Sans_8/pdf_to_json_test_Latn.QUC_Sans_8.py > data/multilingual/Latn.QUC/Sans_8/pdf_to_json_test_Latn.QUC_Sans_8.json 2>&1
Latn.QUC_Serif_12:
	-$(PYTHON) data/multilingual/Latn.QUC/Serif_12/pdf_to_json_test_Latn.QUC_Serif_12.py > data/multilingual/Latn.QUC/Serif_12/pdf_to_json_test_Latn.QUC_Serif_12.json 2>&1
Latn.QUC_Serif_16:
	-$(PYTHON) data/multilingual/Latn.QUC/Serif_16/pdf_to_json_test_Latn.QUC_Serif_16.py > data/multilingual/Latn.QUC/Serif_16/pdf_to_json_test_Latn.QUC_Serif_16.json 2>&1
Latn.QUC_Serif_8:
	-$(PYTHON) data/multilingual/Latn.QUC/Serif_8/pdf_to_json_test_Latn.QUC_Serif_8.py > data/multilingual/Latn.QUC/Serif_8/pdf_to_json_test_Latn.QUC_Serif_8.json 2>&1
Latn.QUC_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.QUC/Sun-ExtA_12/pdf_to_json_test_Latn.QUC_Sun-ExtA_12.py > data/multilingual/Latn.QUC/Sun-ExtA_12/pdf_to_json_test_Latn.QUC_Sun-ExtA_12.json 2>&1
Latn.QUC_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.QUC/Sun-ExtA_16/pdf_to_json_test_Latn.QUC_Sun-ExtA_16.py > data/multilingual/Latn.QUC/Sun-ExtA_16/pdf_to_json_test_Latn.QUC_Sun-ExtA_16.json 2>&1
Latn.QUC_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.QUC/Sun-ExtA_8/pdf_to_json_test_Latn.QUC_Sun-ExtA_8.py > data/multilingual/Latn.QUC/Sun-ExtA_8/pdf_to_json_test_Latn.QUC_Sun-ExtA_8.json 2>&1


Latn.QUC_all : Latn.QUC_Mono_12 Latn.QUC_Mono_16 Latn.QUC_Mono_8 Latn.QUC_Sans_12 Latn.QUC_Sans_16 Latn.QUC_Sans_8 Latn.QUC_Serif_12 Latn.QUC_Serif_16 Latn.QUC_Serif_8 Latn.QUC_Sun-ExtA_12 Latn.QUC_Sun-ExtA_16 Latn.QUC_Sun-ExtA_8
