PYTHON=python3


Latn.MAH_Mono_12:
	-$(PYTHON) data/multilingual/Latn.MAH/Mono_12/pdf_to_json_test_Latn.MAH_Mono_12.py > data/multilingual/Latn.MAH/Mono_12/pdf_to_json_test_Latn.MAH_Mono_12.json 2>&1
Latn.MAH_Mono_16:
	-$(PYTHON) data/multilingual/Latn.MAH/Mono_16/pdf_to_json_test_Latn.MAH_Mono_16.py > data/multilingual/Latn.MAH/Mono_16/pdf_to_json_test_Latn.MAH_Mono_16.json 2>&1
Latn.MAH_Mono_8:
	-$(PYTHON) data/multilingual/Latn.MAH/Mono_8/pdf_to_json_test_Latn.MAH_Mono_8.py > data/multilingual/Latn.MAH/Mono_8/pdf_to_json_test_Latn.MAH_Mono_8.json 2>&1
Latn.MAH_Sans_12:
	-$(PYTHON) data/multilingual/Latn.MAH/Sans_12/pdf_to_json_test_Latn.MAH_Sans_12.py > data/multilingual/Latn.MAH/Sans_12/pdf_to_json_test_Latn.MAH_Sans_12.json 2>&1
Latn.MAH_Sans_16:
	-$(PYTHON) data/multilingual/Latn.MAH/Sans_16/pdf_to_json_test_Latn.MAH_Sans_16.py > data/multilingual/Latn.MAH/Sans_16/pdf_to_json_test_Latn.MAH_Sans_16.json 2>&1
Latn.MAH_Sans_8:
	-$(PYTHON) data/multilingual/Latn.MAH/Sans_8/pdf_to_json_test_Latn.MAH_Sans_8.py > data/multilingual/Latn.MAH/Sans_8/pdf_to_json_test_Latn.MAH_Sans_8.json 2>&1
Latn.MAH_Serif_12:
	-$(PYTHON) data/multilingual/Latn.MAH/Serif_12/pdf_to_json_test_Latn.MAH_Serif_12.py > data/multilingual/Latn.MAH/Serif_12/pdf_to_json_test_Latn.MAH_Serif_12.json 2>&1
Latn.MAH_Serif_16:
	-$(PYTHON) data/multilingual/Latn.MAH/Serif_16/pdf_to_json_test_Latn.MAH_Serif_16.py > data/multilingual/Latn.MAH/Serif_16/pdf_to_json_test_Latn.MAH_Serif_16.json 2>&1
Latn.MAH_Serif_8:
	-$(PYTHON) data/multilingual/Latn.MAH/Serif_8/pdf_to_json_test_Latn.MAH_Serif_8.py > data/multilingual/Latn.MAH/Serif_8/pdf_to_json_test_Latn.MAH_Serif_8.json 2>&1
Latn.MAH_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.MAH/Sun-ExtA_12/pdf_to_json_test_Latn.MAH_Sun-ExtA_12.py > data/multilingual/Latn.MAH/Sun-ExtA_12/pdf_to_json_test_Latn.MAH_Sun-ExtA_12.json 2>&1
Latn.MAH_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.MAH/Sun-ExtA_16/pdf_to_json_test_Latn.MAH_Sun-ExtA_16.py > data/multilingual/Latn.MAH/Sun-ExtA_16/pdf_to_json_test_Latn.MAH_Sun-ExtA_16.json 2>&1
Latn.MAH_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.MAH/Sun-ExtA_8/pdf_to_json_test_Latn.MAH_Sun-ExtA_8.py > data/multilingual/Latn.MAH/Sun-ExtA_8/pdf_to_json_test_Latn.MAH_Sun-ExtA_8.json 2>&1


Latn.MAH_all : Latn.MAH_Mono_12 Latn.MAH_Mono_16 Latn.MAH_Mono_8 Latn.MAH_Sans_12 Latn.MAH_Sans_16 Latn.MAH_Sans_8 Latn.MAH_Serif_12 Latn.MAH_Serif_16 Latn.MAH_Serif_8 Latn.MAH_Sun-ExtA_12 Latn.MAH_Sun-ExtA_16 Latn.MAH_Sun-ExtA_8
