PYTHON=python3


Hani.VIE_Mono_12:
	-$(PYTHON) "data/multilingual/Hani.VIE/Mono_12/pdf_to_json_test_Hani.VIE_Mono_12.py" > "data/multilingual/Hani.VIE/Mono_12/pdf_to_json_test_Hani.VIE_Mono_12.json" 2>&1
Hani.VIE_Mono_16:
	-$(PYTHON) "data/multilingual/Hani.VIE/Mono_16/pdf_to_json_test_Hani.VIE_Mono_16.py" > "data/multilingual/Hani.VIE/Mono_16/pdf_to_json_test_Hani.VIE_Mono_16.json" 2>&1
Hani.VIE_Mono_8:
	-$(PYTHON) "data/multilingual/Hani.VIE/Mono_8/pdf_to_json_test_Hani.VIE_Mono_8.py" > "data/multilingual/Hani.VIE/Mono_8/pdf_to_json_test_Hani.VIE_Mono_8.json" 2>&1
Hani.VIE_Sans_12:
	-$(PYTHON) "data/multilingual/Hani.VIE/Sans_12/pdf_to_json_test_Hani.VIE_Sans_12.py" > "data/multilingual/Hani.VIE/Sans_12/pdf_to_json_test_Hani.VIE_Sans_12.json" 2>&1
Hani.VIE_Sans_16:
	-$(PYTHON) "data/multilingual/Hani.VIE/Sans_16/pdf_to_json_test_Hani.VIE_Sans_16.py" > "data/multilingual/Hani.VIE/Sans_16/pdf_to_json_test_Hani.VIE_Sans_16.json" 2>&1
Hani.VIE_Sans_8:
	-$(PYTHON) "data/multilingual/Hani.VIE/Sans_8/pdf_to_json_test_Hani.VIE_Sans_8.py" > "data/multilingual/Hani.VIE/Sans_8/pdf_to_json_test_Hani.VIE_Sans_8.json" 2>&1
Hani.VIE_Serif_12:
	-$(PYTHON) "data/multilingual/Hani.VIE/Serif_12/pdf_to_json_test_Hani.VIE_Serif_12.py" > "data/multilingual/Hani.VIE/Serif_12/pdf_to_json_test_Hani.VIE_Serif_12.json" 2>&1
Hani.VIE_Serif_16:
	-$(PYTHON) "data/multilingual/Hani.VIE/Serif_16/pdf_to_json_test_Hani.VIE_Serif_16.py" > "data/multilingual/Hani.VIE/Serif_16/pdf_to_json_test_Hani.VIE_Serif_16.json" 2>&1
Hani.VIE_Serif_8:
	-$(PYTHON) "data/multilingual/Hani.VIE/Serif_8/pdf_to_json_test_Hani.VIE_Serif_8.py" > "data/multilingual/Hani.VIE/Serif_8/pdf_to_json_test_Hani.VIE_Serif_8.json" 2>&1
Hani.VIE_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Hani.VIE/Sun-ExtA_12/pdf_to_json_test_Hani.VIE_Sun-ExtA_12.py" > "data/multilingual/Hani.VIE/Sun-ExtA_12/pdf_to_json_test_Hani.VIE_Sun-ExtA_12.json" 2>&1
Hani.VIE_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Hani.VIE/Sun-ExtA_16/pdf_to_json_test_Hani.VIE_Sun-ExtA_16.py" > "data/multilingual/Hani.VIE/Sun-ExtA_16/pdf_to_json_test_Hani.VIE_Sun-ExtA_16.json" 2>&1
Hani.VIE_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Hani.VIE/Sun-ExtA_8/pdf_to_json_test_Hani.VIE_Sun-ExtA_8.py" > "data/multilingual/Hani.VIE/Sun-ExtA_8/pdf_to_json_test_Hani.VIE_Sun-ExtA_8.json" 2>&1


Hani.VIE_all : Hani.VIE_Mono_12 Hani.VIE_Mono_16 Hani.VIE_Mono_8 Hani.VIE_Sans_12 Hani.VIE_Sans_16 Hani.VIE_Sans_8 Hani.VIE_Serif_12 Hani.VIE_Serif_16 Hani.VIE_Serif_8 Hani.VIE_Sun-ExtA_12 Hani.VIE_Sun-ExtA_16 Hani.VIE_Sun-ExtA_8
