PYTHON=python3


Latn.FUF_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.FUF/Mono_12/pdf_to_json_test_Latn.FUF_Mono_12.py" > "data/multilingual/Latn.FUF/Mono_12/pdf_to_json_test_Latn.FUF_Mono_12.json" 2>&1
Latn.FUF_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.FUF/Mono_16/pdf_to_json_test_Latn.FUF_Mono_16.py" > "data/multilingual/Latn.FUF/Mono_16/pdf_to_json_test_Latn.FUF_Mono_16.json" 2>&1
Latn.FUF_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.FUF/Mono_8/pdf_to_json_test_Latn.FUF_Mono_8.py" > "data/multilingual/Latn.FUF/Mono_8/pdf_to_json_test_Latn.FUF_Mono_8.json" 2>&1
Latn.FUF_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.FUF/Sans_12/pdf_to_json_test_Latn.FUF_Sans_12.py" > "data/multilingual/Latn.FUF/Sans_12/pdf_to_json_test_Latn.FUF_Sans_12.json" 2>&1
Latn.FUF_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.FUF/Sans_16/pdf_to_json_test_Latn.FUF_Sans_16.py" > "data/multilingual/Latn.FUF/Sans_16/pdf_to_json_test_Latn.FUF_Sans_16.json" 2>&1
Latn.FUF_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.FUF/Sans_8/pdf_to_json_test_Latn.FUF_Sans_8.py" > "data/multilingual/Latn.FUF/Sans_8/pdf_to_json_test_Latn.FUF_Sans_8.json" 2>&1
Latn.FUF_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.FUF/Serif_12/pdf_to_json_test_Latn.FUF_Serif_12.py" > "data/multilingual/Latn.FUF/Serif_12/pdf_to_json_test_Latn.FUF_Serif_12.json" 2>&1
Latn.FUF_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.FUF/Serif_16/pdf_to_json_test_Latn.FUF_Serif_16.py" > "data/multilingual/Latn.FUF/Serif_16/pdf_to_json_test_Latn.FUF_Serif_16.json" 2>&1
Latn.FUF_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.FUF/Serif_8/pdf_to_json_test_Latn.FUF_Serif_8.py" > "data/multilingual/Latn.FUF/Serif_8/pdf_to_json_test_Latn.FUF_Serif_8.json" 2>&1
Latn.FUF_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.FUF/Sun-ExtA_12/pdf_to_json_test_Latn.FUF_Sun-ExtA_12.py" > "data/multilingual/Latn.FUF/Sun-ExtA_12/pdf_to_json_test_Latn.FUF_Sun-ExtA_12.json" 2>&1
Latn.FUF_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.FUF/Sun-ExtA_16/pdf_to_json_test_Latn.FUF_Sun-ExtA_16.py" > "data/multilingual/Latn.FUF/Sun-ExtA_16/pdf_to_json_test_Latn.FUF_Sun-ExtA_16.json" 2>&1
Latn.FUF_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.FUF/Sun-ExtA_8/pdf_to_json_test_Latn.FUF_Sun-ExtA_8.py" > "data/multilingual/Latn.FUF/Sun-ExtA_8/pdf_to_json_test_Latn.FUF_Sun-ExtA_8.json" 2>&1


Latn.FUF_all : Latn.FUF_Mono_12 Latn.FUF_Mono_16 Latn.FUF_Mono_8 Latn.FUF_Sans_12 Latn.FUF_Sans_16 Latn.FUF_Sans_8 Latn.FUF_Serif_12 Latn.FUF_Serif_16 Latn.FUF_Serif_8 Latn.FUF_Sun-ExtA_12 Latn.FUF_Sun-ExtA_16 Latn.FUF_Sun-ExtA_8
