PYTHON=python3


Latn.CNI_Mono_12:
	-$(PYTHON) data/multilingual/Latn.CNI/Mono_12/pdf_to_json_test_Latn.CNI_Mono_12.py > data/multilingual/Latn.CNI/Mono_12/pdf_to_json_test_Latn.CNI_Mono_12.json 2>&1
Latn.CNI_Mono_16:
	-$(PYTHON) data/multilingual/Latn.CNI/Mono_16/pdf_to_json_test_Latn.CNI_Mono_16.py > data/multilingual/Latn.CNI/Mono_16/pdf_to_json_test_Latn.CNI_Mono_16.json 2>&1
Latn.CNI_Mono_8:
	-$(PYTHON) data/multilingual/Latn.CNI/Mono_8/pdf_to_json_test_Latn.CNI_Mono_8.py > data/multilingual/Latn.CNI/Mono_8/pdf_to_json_test_Latn.CNI_Mono_8.json 2>&1
Latn.CNI_Sans_12:
	-$(PYTHON) data/multilingual/Latn.CNI/Sans_12/pdf_to_json_test_Latn.CNI_Sans_12.py > data/multilingual/Latn.CNI/Sans_12/pdf_to_json_test_Latn.CNI_Sans_12.json 2>&1
Latn.CNI_Sans_16:
	-$(PYTHON) data/multilingual/Latn.CNI/Sans_16/pdf_to_json_test_Latn.CNI_Sans_16.py > data/multilingual/Latn.CNI/Sans_16/pdf_to_json_test_Latn.CNI_Sans_16.json 2>&1
Latn.CNI_Sans_8:
	-$(PYTHON) data/multilingual/Latn.CNI/Sans_8/pdf_to_json_test_Latn.CNI_Sans_8.py > data/multilingual/Latn.CNI/Sans_8/pdf_to_json_test_Latn.CNI_Sans_8.json 2>&1
Latn.CNI_Serif_12:
	-$(PYTHON) data/multilingual/Latn.CNI/Serif_12/pdf_to_json_test_Latn.CNI_Serif_12.py > data/multilingual/Latn.CNI/Serif_12/pdf_to_json_test_Latn.CNI_Serif_12.json 2>&1
Latn.CNI_Serif_16:
	-$(PYTHON) data/multilingual/Latn.CNI/Serif_16/pdf_to_json_test_Latn.CNI_Serif_16.py > data/multilingual/Latn.CNI/Serif_16/pdf_to_json_test_Latn.CNI_Serif_16.json 2>&1
Latn.CNI_Serif_8:
	-$(PYTHON) data/multilingual/Latn.CNI/Serif_8/pdf_to_json_test_Latn.CNI_Serif_8.py > data/multilingual/Latn.CNI/Serif_8/pdf_to_json_test_Latn.CNI_Serif_8.json 2>&1
Latn.CNI_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.CNI/Sun-ExtA_12/pdf_to_json_test_Latn.CNI_Sun-ExtA_12.py > data/multilingual/Latn.CNI/Sun-ExtA_12/pdf_to_json_test_Latn.CNI_Sun-ExtA_12.json 2>&1
Latn.CNI_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.CNI/Sun-ExtA_16/pdf_to_json_test_Latn.CNI_Sun-ExtA_16.py > data/multilingual/Latn.CNI/Sun-ExtA_16/pdf_to_json_test_Latn.CNI_Sun-ExtA_16.json 2>&1
Latn.CNI_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.CNI/Sun-ExtA_8/pdf_to_json_test_Latn.CNI_Sun-ExtA_8.py > data/multilingual/Latn.CNI/Sun-ExtA_8/pdf_to_json_test_Latn.CNI_Sun-ExtA_8.json 2>&1


Latn.CNI_all : Latn.CNI_Mono_12 Latn.CNI_Mono_16 Latn.CNI_Mono_8 Latn.CNI_Sans_12 Latn.CNI_Sans_16 Latn.CNI_Sans_8 Latn.CNI_Serif_12 Latn.CNI_Serif_16 Latn.CNI_Serif_8 Latn.CNI_Sun-ExtA_12 Latn.CNI_Sun-ExtA_16 Latn.CNI_Sun-ExtA_8
