PYTHON=python3


Latn.CPU_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.CPU/Mono_12/pdf_to_json_test_Latn.CPU_Mono_12.py" > "data/multilingual/Latn.CPU/Mono_12/pdf_to_json_test_Latn.CPU_Mono_12.json" 2>&1
Latn.CPU_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.CPU/Mono_16/pdf_to_json_test_Latn.CPU_Mono_16.py" > "data/multilingual/Latn.CPU/Mono_16/pdf_to_json_test_Latn.CPU_Mono_16.json" 2>&1
Latn.CPU_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.CPU/Mono_8/pdf_to_json_test_Latn.CPU_Mono_8.py" > "data/multilingual/Latn.CPU/Mono_8/pdf_to_json_test_Latn.CPU_Mono_8.json" 2>&1
Latn.CPU_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.CPU/Sans_12/pdf_to_json_test_Latn.CPU_Sans_12.py" > "data/multilingual/Latn.CPU/Sans_12/pdf_to_json_test_Latn.CPU_Sans_12.json" 2>&1
Latn.CPU_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.CPU/Sans_16/pdf_to_json_test_Latn.CPU_Sans_16.py" > "data/multilingual/Latn.CPU/Sans_16/pdf_to_json_test_Latn.CPU_Sans_16.json" 2>&1
Latn.CPU_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.CPU/Sans_8/pdf_to_json_test_Latn.CPU_Sans_8.py" > "data/multilingual/Latn.CPU/Sans_8/pdf_to_json_test_Latn.CPU_Sans_8.json" 2>&1
Latn.CPU_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.CPU/Serif_12/pdf_to_json_test_Latn.CPU_Serif_12.py" > "data/multilingual/Latn.CPU/Serif_12/pdf_to_json_test_Latn.CPU_Serif_12.json" 2>&1
Latn.CPU_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.CPU/Serif_16/pdf_to_json_test_Latn.CPU_Serif_16.py" > "data/multilingual/Latn.CPU/Serif_16/pdf_to_json_test_Latn.CPU_Serif_16.json" 2>&1
Latn.CPU_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.CPU/Serif_8/pdf_to_json_test_Latn.CPU_Serif_8.py" > "data/multilingual/Latn.CPU/Serif_8/pdf_to_json_test_Latn.CPU_Serif_8.json" 2>&1
Latn.CPU_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.CPU/Sun-ExtA_12/pdf_to_json_test_Latn.CPU_Sun-ExtA_12.py" > "data/multilingual/Latn.CPU/Sun-ExtA_12/pdf_to_json_test_Latn.CPU_Sun-ExtA_12.json" 2>&1
Latn.CPU_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.CPU/Sun-ExtA_16/pdf_to_json_test_Latn.CPU_Sun-ExtA_16.py" > "data/multilingual/Latn.CPU/Sun-ExtA_16/pdf_to_json_test_Latn.CPU_Sun-ExtA_16.json" 2>&1
Latn.CPU_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.CPU/Sun-ExtA_8/pdf_to_json_test_Latn.CPU_Sun-ExtA_8.py" > "data/multilingual/Latn.CPU/Sun-ExtA_8/pdf_to_json_test_Latn.CPU_Sun-ExtA_8.json" 2>&1


Latn.CPU_all : Latn.CPU_Mono_12 Latn.CPU_Mono_16 Latn.CPU_Mono_8 Latn.CPU_Sans_12 Latn.CPU_Sans_16 Latn.CPU_Sans_8 Latn.CPU_Serif_12 Latn.CPU_Serif_16 Latn.CPU_Serif_8 Latn.CPU_Sun-ExtA_12 Latn.CPU_Sun-ExtA_16 Latn.CPU_Sun-ExtA_8
