PYTHON=python3


Latn.LIN_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.LIN/Mono_12/pdf_to_json_test_Latn.LIN_Mono_12.py" > "data/multilingual/Latn.LIN/Mono_12/pdf_to_json_test_Latn.LIN_Mono_12.json" 2>&1
Latn.LIN_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.LIN/Mono_16/pdf_to_json_test_Latn.LIN_Mono_16.py" > "data/multilingual/Latn.LIN/Mono_16/pdf_to_json_test_Latn.LIN_Mono_16.json" 2>&1
Latn.LIN_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.LIN/Mono_8/pdf_to_json_test_Latn.LIN_Mono_8.py" > "data/multilingual/Latn.LIN/Mono_8/pdf_to_json_test_Latn.LIN_Mono_8.json" 2>&1
Latn.LIN_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.LIN/Sans_12/pdf_to_json_test_Latn.LIN_Sans_12.py" > "data/multilingual/Latn.LIN/Sans_12/pdf_to_json_test_Latn.LIN_Sans_12.json" 2>&1
Latn.LIN_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.LIN/Sans_16/pdf_to_json_test_Latn.LIN_Sans_16.py" > "data/multilingual/Latn.LIN/Sans_16/pdf_to_json_test_Latn.LIN_Sans_16.json" 2>&1
Latn.LIN_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.LIN/Sans_8/pdf_to_json_test_Latn.LIN_Sans_8.py" > "data/multilingual/Latn.LIN/Sans_8/pdf_to_json_test_Latn.LIN_Sans_8.json" 2>&1
Latn.LIN_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.LIN/Serif_12/pdf_to_json_test_Latn.LIN_Serif_12.py" > "data/multilingual/Latn.LIN/Serif_12/pdf_to_json_test_Latn.LIN_Serif_12.json" 2>&1
Latn.LIN_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.LIN/Serif_16/pdf_to_json_test_Latn.LIN_Serif_16.py" > "data/multilingual/Latn.LIN/Serif_16/pdf_to_json_test_Latn.LIN_Serif_16.json" 2>&1
Latn.LIN_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.LIN/Serif_8/pdf_to_json_test_Latn.LIN_Serif_8.py" > "data/multilingual/Latn.LIN/Serif_8/pdf_to_json_test_Latn.LIN_Serif_8.json" 2>&1
Latn.LIN_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.LIN/Sun-ExtA_12/pdf_to_json_test_Latn.LIN_Sun-ExtA_12.py" > "data/multilingual/Latn.LIN/Sun-ExtA_12/pdf_to_json_test_Latn.LIN_Sun-ExtA_12.json" 2>&1
Latn.LIN_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.LIN/Sun-ExtA_16/pdf_to_json_test_Latn.LIN_Sun-ExtA_16.py" > "data/multilingual/Latn.LIN/Sun-ExtA_16/pdf_to_json_test_Latn.LIN_Sun-ExtA_16.json" 2>&1
Latn.LIN_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.LIN/Sun-ExtA_8/pdf_to_json_test_Latn.LIN_Sun-ExtA_8.py" > "data/multilingual/Latn.LIN/Sun-ExtA_8/pdf_to_json_test_Latn.LIN_Sun-ExtA_8.json" 2>&1


Latn.LIN_all : Latn.LIN_Mono_12 Latn.LIN_Mono_16 Latn.LIN_Mono_8 Latn.LIN_Sans_12 Latn.LIN_Sans_16 Latn.LIN_Sans_8 Latn.LIN_Serif_12 Latn.LIN_Serif_16 Latn.LIN_Serif_8 Latn.LIN_Sun-ExtA_12 Latn.LIN_Sun-ExtA_16 Latn.LIN_Sun-ExtA_8
