PYTHON=python3


Latn.COT_Mono_12:
	-$(PYTHON) data/multilingual/Latn.COT/Mono_12/pdf_to_json_test_Latn.COT_Mono_12.py > data/multilingual/Latn.COT/Mono_12/pdf_to_json_test_Latn.COT_Mono_12.json 2>&1
Latn.COT_Mono_16:
	-$(PYTHON) data/multilingual/Latn.COT/Mono_16/pdf_to_json_test_Latn.COT_Mono_16.py > data/multilingual/Latn.COT/Mono_16/pdf_to_json_test_Latn.COT_Mono_16.json 2>&1
Latn.COT_Mono_8:
	-$(PYTHON) data/multilingual/Latn.COT/Mono_8/pdf_to_json_test_Latn.COT_Mono_8.py > data/multilingual/Latn.COT/Mono_8/pdf_to_json_test_Latn.COT_Mono_8.json 2>&1
Latn.COT_Sans_12:
	-$(PYTHON) data/multilingual/Latn.COT/Sans_12/pdf_to_json_test_Latn.COT_Sans_12.py > data/multilingual/Latn.COT/Sans_12/pdf_to_json_test_Latn.COT_Sans_12.json 2>&1
Latn.COT_Sans_16:
	-$(PYTHON) data/multilingual/Latn.COT/Sans_16/pdf_to_json_test_Latn.COT_Sans_16.py > data/multilingual/Latn.COT/Sans_16/pdf_to_json_test_Latn.COT_Sans_16.json 2>&1
Latn.COT_Sans_8:
	-$(PYTHON) data/multilingual/Latn.COT/Sans_8/pdf_to_json_test_Latn.COT_Sans_8.py > data/multilingual/Latn.COT/Sans_8/pdf_to_json_test_Latn.COT_Sans_8.json 2>&1
Latn.COT_Serif_12:
	-$(PYTHON) data/multilingual/Latn.COT/Serif_12/pdf_to_json_test_Latn.COT_Serif_12.py > data/multilingual/Latn.COT/Serif_12/pdf_to_json_test_Latn.COT_Serif_12.json 2>&1
Latn.COT_Serif_16:
	-$(PYTHON) data/multilingual/Latn.COT/Serif_16/pdf_to_json_test_Latn.COT_Serif_16.py > data/multilingual/Latn.COT/Serif_16/pdf_to_json_test_Latn.COT_Serif_16.json 2>&1
Latn.COT_Serif_8:
	-$(PYTHON) data/multilingual/Latn.COT/Serif_8/pdf_to_json_test_Latn.COT_Serif_8.py > data/multilingual/Latn.COT/Serif_8/pdf_to_json_test_Latn.COT_Serif_8.json 2>&1
Latn.COT_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.COT/Sun-ExtA_12/pdf_to_json_test_Latn.COT_Sun-ExtA_12.py > data/multilingual/Latn.COT/Sun-ExtA_12/pdf_to_json_test_Latn.COT_Sun-ExtA_12.json 2>&1
Latn.COT_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.COT/Sun-ExtA_16/pdf_to_json_test_Latn.COT_Sun-ExtA_16.py > data/multilingual/Latn.COT/Sun-ExtA_16/pdf_to_json_test_Latn.COT_Sun-ExtA_16.json 2>&1
Latn.COT_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.COT/Sun-ExtA_8/pdf_to_json_test_Latn.COT_Sun-ExtA_8.py > data/multilingual/Latn.COT/Sun-ExtA_8/pdf_to_json_test_Latn.COT_Sun-ExtA_8.json 2>&1


Latn.COT_all : Latn.COT_Mono_12 Latn.COT_Mono_16 Latn.COT_Mono_8 Latn.COT_Sans_12 Latn.COT_Sans_16 Latn.COT_Sans_8 Latn.COT_Serif_12 Latn.COT_Serif_16 Latn.COT_Serif_8 Latn.COT_Sun-ExtA_12 Latn.COT_Sun-ExtA_16 Latn.COT_Sun-ExtA_8
