PYTHON=python3


Latn.FAO_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.FAO/Mono_12/pdf_to_json_test_Latn.FAO_Mono_12.py" > "data/multilingual/Latn.FAO/Mono_12/pdf_to_json_test_Latn.FAO_Mono_12.json" 2>&1
Latn.FAO_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.FAO/Mono_16/pdf_to_json_test_Latn.FAO_Mono_16.py" > "data/multilingual/Latn.FAO/Mono_16/pdf_to_json_test_Latn.FAO_Mono_16.json" 2>&1
Latn.FAO_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.FAO/Mono_8/pdf_to_json_test_Latn.FAO_Mono_8.py" > "data/multilingual/Latn.FAO/Mono_8/pdf_to_json_test_Latn.FAO_Mono_8.json" 2>&1
Latn.FAO_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.FAO/Sans_12/pdf_to_json_test_Latn.FAO_Sans_12.py" > "data/multilingual/Latn.FAO/Sans_12/pdf_to_json_test_Latn.FAO_Sans_12.json" 2>&1
Latn.FAO_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.FAO/Sans_16/pdf_to_json_test_Latn.FAO_Sans_16.py" > "data/multilingual/Latn.FAO/Sans_16/pdf_to_json_test_Latn.FAO_Sans_16.json" 2>&1
Latn.FAO_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.FAO/Sans_8/pdf_to_json_test_Latn.FAO_Sans_8.py" > "data/multilingual/Latn.FAO/Sans_8/pdf_to_json_test_Latn.FAO_Sans_8.json" 2>&1
Latn.FAO_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.FAO/Serif_12/pdf_to_json_test_Latn.FAO_Serif_12.py" > "data/multilingual/Latn.FAO/Serif_12/pdf_to_json_test_Latn.FAO_Serif_12.json" 2>&1
Latn.FAO_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.FAO/Serif_16/pdf_to_json_test_Latn.FAO_Serif_16.py" > "data/multilingual/Latn.FAO/Serif_16/pdf_to_json_test_Latn.FAO_Serif_16.json" 2>&1
Latn.FAO_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.FAO/Serif_8/pdf_to_json_test_Latn.FAO_Serif_8.py" > "data/multilingual/Latn.FAO/Serif_8/pdf_to_json_test_Latn.FAO_Serif_8.json" 2>&1
Latn.FAO_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.FAO/Sun-ExtA_12/pdf_to_json_test_Latn.FAO_Sun-ExtA_12.py" > "data/multilingual/Latn.FAO/Sun-ExtA_12/pdf_to_json_test_Latn.FAO_Sun-ExtA_12.json" 2>&1
Latn.FAO_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.FAO/Sun-ExtA_16/pdf_to_json_test_Latn.FAO_Sun-ExtA_16.py" > "data/multilingual/Latn.FAO/Sun-ExtA_16/pdf_to_json_test_Latn.FAO_Sun-ExtA_16.json" 2>&1
Latn.FAO_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.FAO/Sun-ExtA_8/pdf_to_json_test_Latn.FAO_Sun-ExtA_8.py" > "data/multilingual/Latn.FAO/Sun-ExtA_8/pdf_to_json_test_Latn.FAO_Sun-ExtA_8.json" 2>&1


Latn.FAO_all : Latn.FAO_Mono_12 Latn.FAO_Mono_16 Latn.FAO_Mono_8 Latn.FAO_Sans_12 Latn.FAO_Sans_16 Latn.FAO_Sans_8 Latn.FAO_Serif_12 Latn.FAO_Serif_16 Latn.FAO_Serif_8 Latn.FAO_Sun-ExtA_12 Latn.FAO_Sun-ExtA_16 Latn.FAO_Sun-ExtA_8
