PYTHON=python3


Latn.QUH_Mono_12:
	-$(PYTHON) data/multilingual/Latn.QUH/Mono_12/pdf_to_json_test_Latn.QUH_Mono_12.py > data/multilingual/Latn.QUH/Mono_12/pdf_to_json_test_Latn.QUH_Mono_12.json 2>&1
Latn.QUH_Mono_16:
	-$(PYTHON) data/multilingual/Latn.QUH/Mono_16/pdf_to_json_test_Latn.QUH_Mono_16.py > data/multilingual/Latn.QUH/Mono_16/pdf_to_json_test_Latn.QUH_Mono_16.json 2>&1
Latn.QUH_Mono_8:
	-$(PYTHON) data/multilingual/Latn.QUH/Mono_8/pdf_to_json_test_Latn.QUH_Mono_8.py > data/multilingual/Latn.QUH/Mono_8/pdf_to_json_test_Latn.QUH_Mono_8.json 2>&1
Latn.QUH_Sans_12:
	-$(PYTHON) data/multilingual/Latn.QUH/Sans_12/pdf_to_json_test_Latn.QUH_Sans_12.py > data/multilingual/Latn.QUH/Sans_12/pdf_to_json_test_Latn.QUH_Sans_12.json 2>&1
Latn.QUH_Sans_16:
	-$(PYTHON) data/multilingual/Latn.QUH/Sans_16/pdf_to_json_test_Latn.QUH_Sans_16.py > data/multilingual/Latn.QUH/Sans_16/pdf_to_json_test_Latn.QUH_Sans_16.json 2>&1
Latn.QUH_Sans_8:
	-$(PYTHON) data/multilingual/Latn.QUH/Sans_8/pdf_to_json_test_Latn.QUH_Sans_8.py > data/multilingual/Latn.QUH/Sans_8/pdf_to_json_test_Latn.QUH_Sans_8.json 2>&1
Latn.QUH_Serif_12:
	-$(PYTHON) data/multilingual/Latn.QUH/Serif_12/pdf_to_json_test_Latn.QUH_Serif_12.py > data/multilingual/Latn.QUH/Serif_12/pdf_to_json_test_Latn.QUH_Serif_12.json 2>&1
Latn.QUH_Serif_16:
	-$(PYTHON) data/multilingual/Latn.QUH/Serif_16/pdf_to_json_test_Latn.QUH_Serif_16.py > data/multilingual/Latn.QUH/Serif_16/pdf_to_json_test_Latn.QUH_Serif_16.json 2>&1
Latn.QUH_Serif_8:
	-$(PYTHON) data/multilingual/Latn.QUH/Serif_8/pdf_to_json_test_Latn.QUH_Serif_8.py > data/multilingual/Latn.QUH/Serif_8/pdf_to_json_test_Latn.QUH_Serif_8.json 2>&1
Latn.QUH_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.QUH/Sun-ExtA_12/pdf_to_json_test_Latn.QUH_Sun-ExtA_12.py > data/multilingual/Latn.QUH/Sun-ExtA_12/pdf_to_json_test_Latn.QUH_Sun-ExtA_12.json 2>&1
Latn.QUH_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.QUH/Sun-ExtA_16/pdf_to_json_test_Latn.QUH_Sun-ExtA_16.py > data/multilingual/Latn.QUH/Sun-ExtA_16/pdf_to_json_test_Latn.QUH_Sun-ExtA_16.json 2>&1
Latn.QUH_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.QUH/Sun-ExtA_8/pdf_to_json_test_Latn.QUH_Sun-ExtA_8.py > data/multilingual/Latn.QUH/Sun-ExtA_8/pdf_to_json_test_Latn.QUH_Sun-ExtA_8.json 2>&1


Latn.QUH_all : Latn.QUH_Mono_12 Latn.QUH_Mono_16 Latn.QUH_Mono_8 Latn.QUH_Sans_12 Latn.QUH_Sans_16 Latn.QUH_Sans_8 Latn.QUH_Serif_12 Latn.QUH_Serif_16 Latn.QUH_Serif_8 Latn.QUH_Sun-ExtA_12 Latn.QUH_Sun-ExtA_16 Latn.QUH_Sun-ExtA_8
