PYTHON=python3


Latn.YAD_Mono_12:
	-$(PYTHON) data/multilingual/Latn.YAD/Mono_12/pdf_to_json_test_Latn.YAD_Mono_12.py > data/multilingual/Latn.YAD/Mono_12/pdf_to_json_test_Latn.YAD_Mono_12.json 2>&1
Latn.YAD_Mono_16:
	-$(PYTHON) data/multilingual/Latn.YAD/Mono_16/pdf_to_json_test_Latn.YAD_Mono_16.py > data/multilingual/Latn.YAD/Mono_16/pdf_to_json_test_Latn.YAD_Mono_16.json 2>&1
Latn.YAD_Mono_8:
	-$(PYTHON) data/multilingual/Latn.YAD/Mono_8/pdf_to_json_test_Latn.YAD_Mono_8.py > data/multilingual/Latn.YAD/Mono_8/pdf_to_json_test_Latn.YAD_Mono_8.json 2>&1
Latn.YAD_Sans_12:
	-$(PYTHON) data/multilingual/Latn.YAD/Sans_12/pdf_to_json_test_Latn.YAD_Sans_12.py > data/multilingual/Latn.YAD/Sans_12/pdf_to_json_test_Latn.YAD_Sans_12.json 2>&1
Latn.YAD_Sans_16:
	-$(PYTHON) data/multilingual/Latn.YAD/Sans_16/pdf_to_json_test_Latn.YAD_Sans_16.py > data/multilingual/Latn.YAD/Sans_16/pdf_to_json_test_Latn.YAD_Sans_16.json 2>&1
Latn.YAD_Sans_8:
	-$(PYTHON) data/multilingual/Latn.YAD/Sans_8/pdf_to_json_test_Latn.YAD_Sans_8.py > data/multilingual/Latn.YAD/Sans_8/pdf_to_json_test_Latn.YAD_Sans_8.json 2>&1
Latn.YAD_Serif_12:
	-$(PYTHON) data/multilingual/Latn.YAD/Serif_12/pdf_to_json_test_Latn.YAD_Serif_12.py > data/multilingual/Latn.YAD/Serif_12/pdf_to_json_test_Latn.YAD_Serif_12.json 2>&1
Latn.YAD_Serif_16:
	-$(PYTHON) data/multilingual/Latn.YAD/Serif_16/pdf_to_json_test_Latn.YAD_Serif_16.py > data/multilingual/Latn.YAD/Serif_16/pdf_to_json_test_Latn.YAD_Serif_16.json 2>&1
Latn.YAD_Serif_8:
	-$(PYTHON) data/multilingual/Latn.YAD/Serif_8/pdf_to_json_test_Latn.YAD_Serif_8.py > data/multilingual/Latn.YAD/Serif_8/pdf_to_json_test_Latn.YAD_Serif_8.json 2>&1
Latn.YAD_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.YAD/Sun-ExtA_12/pdf_to_json_test_Latn.YAD_Sun-ExtA_12.py > data/multilingual/Latn.YAD/Sun-ExtA_12/pdf_to_json_test_Latn.YAD_Sun-ExtA_12.json 2>&1
Latn.YAD_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.YAD/Sun-ExtA_16/pdf_to_json_test_Latn.YAD_Sun-ExtA_16.py > data/multilingual/Latn.YAD/Sun-ExtA_16/pdf_to_json_test_Latn.YAD_Sun-ExtA_16.json 2>&1
Latn.YAD_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.YAD/Sun-ExtA_8/pdf_to_json_test_Latn.YAD_Sun-ExtA_8.py > data/multilingual/Latn.YAD/Sun-ExtA_8/pdf_to_json_test_Latn.YAD_Sun-ExtA_8.json 2>&1


Latn.YAD_all : Latn.YAD_Mono_12 Latn.YAD_Mono_16 Latn.YAD_Mono_8 Latn.YAD_Sans_12 Latn.YAD_Sans_16 Latn.YAD_Sans_8 Latn.YAD_Serif_12 Latn.YAD_Serif_16 Latn.YAD_Serif_8 Latn.YAD_Sun-ExtA_12 Latn.YAD_Sun-ExtA_16 Latn.YAD_Sun-ExtA_8
