PYTHON=python3


Latn.TDT_Mono_12:
	-$(PYTHON) data/multilingual/Latn.TDT/Mono_12/pdf_to_json_test_Latn.TDT_Mono_12.py > data/multilingual/Latn.TDT/Mono_12/pdf_to_json_test_Latn.TDT_Mono_12.json 2>&1
Latn.TDT_Mono_16:
	-$(PYTHON) data/multilingual/Latn.TDT/Mono_16/pdf_to_json_test_Latn.TDT_Mono_16.py > data/multilingual/Latn.TDT/Mono_16/pdf_to_json_test_Latn.TDT_Mono_16.json 2>&1
Latn.TDT_Mono_8:
	-$(PYTHON) data/multilingual/Latn.TDT/Mono_8/pdf_to_json_test_Latn.TDT_Mono_8.py > data/multilingual/Latn.TDT/Mono_8/pdf_to_json_test_Latn.TDT_Mono_8.json 2>&1
Latn.TDT_Sans_12:
	-$(PYTHON) data/multilingual/Latn.TDT/Sans_12/pdf_to_json_test_Latn.TDT_Sans_12.py > data/multilingual/Latn.TDT/Sans_12/pdf_to_json_test_Latn.TDT_Sans_12.json 2>&1
Latn.TDT_Sans_16:
	-$(PYTHON) data/multilingual/Latn.TDT/Sans_16/pdf_to_json_test_Latn.TDT_Sans_16.py > data/multilingual/Latn.TDT/Sans_16/pdf_to_json_test_Latn.TDT_Sans_16.json 2>&1
Latn.TDT_Sans_8:
	-$(PYTHON) data/multilingual/Latn.TDT/Sans_8/pdf_to_json_test_Latn.TDT_Sans_8.py > data/multilingual/Latn.TDT/Sans_8/pdf_to_json_test_Latn.TDT_Sans_8.json 2>&1
Latn.TDT_Serif_12:
	-$(PYTHON) data/multilingual/Latn.TDT/Serif_12/pdf_to_json_test_Latn.TDT_Serif_12.py > data/multilingual/Latn.TDT/Serif_12/pdf_to_json_test_Latn.TDT_Serif_12.json 2>&1
Latn.TDT_Serif_16:
	-$(PYTHON) data/multilingual/Latn.TDT/Serif_16/pdf_to_json_test_Latn.TDT_Serif_16.py > data/multilingual/Latn.TDT/Serif_16/pdf_to_json_test_Latn.TDT_Serif_16.json 2>&1
Latn.TDT_Serif_8:
	-$(PYTHON) data/multilingual/Latn.TDT/Serif_8/pdf_to_json_test_Latn.TDT_Serif_8.py > data/multilingual/Latn.TDT/Serif_8/pdf_to_json_test_Latn.TDT_Serif_8.json 2>&1
Latn.TDT_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.TDT/Sun-ExtA_12/pdf_to_json_test_Latn.TDT_Sun-ExtA_12.py > data/multilingual/Latn.TDT/Sun-ExtA_12/pdf_to_json_test_Latn.TDT_Sun-ExtA_12.json 2>&1
Latn.TDT_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.TDT/Sun-ExtA_16/pdf_to_json_test_Latn.TDT_Sun-ExtA_16.py > data/multilingual/Latn.TDT/Sun-ExtA_16/pdf_to_json_test_Latn.TDT_Sun-ExtA_16.json 2>&1
Latn.TDT_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.TDT/Sun-ExtA_8/pdf_to_json_test_Latn.TDT_Sun-ExtA_8.py > data/multilingual/Latn.TDT/Sun-ExtA_8/pdf_to_json_test_Latn.TDT_Sun-ExtA_8.json 2>&1


Latn.TDT_all : Latn.TDT_Mono_12 Latn.TDT_Mono_16 Latn.TDT_Mono_8 Latn.TDT_Sans_12 Latn.TDT_Sans_16 Latn.TDT_Sans_8 Latn.TDT_Serif_12 Latn.TDT_Serif_16 Latn.TDT_Serif_8 Latn.TDT_Sun-ExtA_12 Latn.TDT_Sun-ExtA_16 Latn.TDT_Sun-ExtA_8
