PYTHON=python3


Latn.CKB_Mono_12:
	-$(PYTHON) data/multilingual/Latn.CKB/Mono_12/pdf_to_json_test_Latn.CKB_Mono_12.py > data/multilingual/Latn.CKB/Mono_12/pdf_to_json_test_Latn.CKB_Mono_12.json 2>&1
Latn.CKB_Mono_16:
	-$(PYTHON) data/multilingual/Latn.CKB/Mono_16/pdf_to_json_test_Latn.CKB_Mono_16.py > data/multilingual/Latn.CKB/Mono_16/pdf_to_json_test_Latn.CKB_Mono_16.json 2>&1
Latn.CKB_Mono_8:
	-$(PYTHON) data/multilingual/Latn.CKB/Mono_8/pdf_to_json_test_Latn.CKB_Mono_8.py > data/multilingual/Latn.CKB/Mono_8/pdf_to_json_test_Latn.CKB_Mono_8.json 2>&1
Latn.CKB_Sans_12:
	-$(PYTHON) data/multilingual/Latn.CKB/Sans_12/pdf_to_json_test_Latn.CKB_Sans_12.py > data/multilingual/Latn.CKB/Sans_12/pdf_to_json_test_Latn.CKB_Sans_12.json 2>&1
Latn.CKB_Sans_16:
	-$(PYTHON) data/multilingual/Latn.CKB/Sans_16/pdf_to_json_test_Latn.CKB_Sans_16.py > data/multilingual/Latn.CKB/Sans_16/pdf_to_json_test_Latn.CKB_Sans_16.json 2>&1
Latn.CKB_Sans_8:
	-$(PYTHON) data/multilingual/Latn.CKB/Sans_8/pdf_to_json_test_Latn.CKB_Sans_8.py > data/multilingual/Latn.CKB/Sans_8/pdf_to_json_test_Latn.CKB_Sans_8.json 2>&1
Latn.CKB_Serif_12:
	-$(PYTHON) data/multilingual/Latn.CKB/Serif_12/pdf_to_json_test_Latn.CKB_Serif_12.py > data/multilingual/Latn.CKB/Serif_12/pdf_to_json_test_Latn.CKB_Serif_12.json 2>&1
Latn.CKB_Serif_16:
	-$(PYTHON) data/multilingual/Latn.CKB/Serif_16/pdf_to_json_test_Latn.CKB_Serif_16.py > data/multilingual/Latn.CKB/Serif_16/pdf_to_json_test_Latn.CKB_Serif_16.json 2>&1
Latn.CKB_Serif_8:
	-$(PYTHON) data/multilingual/Latn.CKB/Serif_8/pdf_to_json_test_Latn.CKB_Serif_8.py > data/multilingual/Latn.CKB/Serif_8/pdf_to_json_test_Latn.CKB_Serif_8.json 2>&1
Latn.CKB_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.CKB/Sun-ExtA_12/pdf_to_json_test_Latn.CKB_Sun-ExtA_12.py > data/multilingual/Latn.CKB/Sun-ExtA_12/pdf_to_json_test_Latn.CKB_Sun-ExtA_12.json 2>&1
Latn.CKB_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.CKB/Sun-ExtA_16/pdf_to_json_test_Latn.CKB_Sun-ExtA_16.py > data/multilingual/Latn.CKB/Sun-ExtA_16/pdf_to_json_test_Latn.CKB_Sun-ExtA_16.json 2>&1
Latn.CKB_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.CKB/Sun-ExtA_8/pdf_to_json_test_Latn.CKB_Sun-ExtA_8.py > data/multilingual/Latn.CKB/Sun-ExtA_8/pdf_to_json_test_Latn.CKB_Sun-ExtA_8.json 2>&1


Latn.CKB_all : Latn.CKB_Mono_12 Latn.CKB_Mono_16 Latn.CKB_Mono_8 Latn.CKB_Sans_12 Latn.CKB_Sans_16 Latn.CKB_Sans_8 Latn.CKB_Serif_12 Latn.CKB_Serif_16 Latn.CKB_Serif_8 Latn.CKB_Sun-ExtA_12 Latn.CKB_Sun-ExtA_16 Latn.CKB_Sun-ExtA_8
