PYTHON=python3


Latn.GAG_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.GAG/Mono_12/pdf_to_json_test_Latn.GAG_Mono_12.py" > "data/multilingual/Latn.GAG/Mono_12/pdf_to_json_test_Latn.GAG_Mono_12.json" 2>&1
Latn.GAG_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.GAG/Mono_16/pdf_to_json_test_Latn.GAG_Mono_16.py" > "data/multilingual/Latn.GAG/Mono_16/pdf_to_json_test_Latn.GAG_Mono_16.json" 2>&1
Latn.GAG_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.GAG/Mono_8/pdf_to_json_test_Latn.GAG_Mono_8.py" > "data/multilingual/Latn.GAG/Mono_8/pdf_to_json_test_Latn.GAG_Mono_8.json" 2>&1
Latn.GAG_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.GAG/Sans_12/pdf_to_json_test_Latn.GAG_Sans_12.py" > "data/multilingual/Latn.GAG/Sans_12/pdf_to_json_test_Latn.GAG_Sans_12.json" 2>&1
Latn.GAG_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.GAG/Sans_16/pdf_to_json_test_Latn.GAG_Sans_16.py" > "data/multilingual/Latn.GAG/Sans_16/pdf_to_json_test_Latn.GAG_Sans_16.json" 2>&1
Latn.GAG_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.GAG/Sans_8/pdf_to_json_test_Latn.GAG_Sans_8.py" > "data/multilingual/Latn.GAG/Sans_8/pdf_to_json_test_Latn.GAG_Sans_8.json" 2>&1
Latn.GAG_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.GAG/Serif_12/pdf_to_json_test_Latn.GAG_Serif_12.py" > "data/multilingual/Latn.GAG/Serif_12/pdf_to_json_test_Latn.GAG_Serif_12.json" 2>&1
Latn.GAG_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.GAG/Serif_16/pdf_to_json_test_Latn.GAG_Serif_16.py" > "data/multilingual/Latn.GAG/Serif_16/pdf_to_json_test_Latn.GAG_Serif_16.json" 2>&1
Latn.GAG_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.GAG/Serif_8/pdf_to_json_test_Latn.GAG_Serif_8.py" > "data/multilingual/Latn.GAG/Serif_8/pdf_to_json_test_Latn.GAG_Serif_8.json" 2>&1
Latn.GAG_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.GAG/Sun-ExtA_12/pdf_to_json_test_Latn.GAG_Sun-ExtA_12.py" > "data/multilingual/Latn.GAG/Sun-ExtA_12/pdf_to_json_test_Latn.GAG_Sun-ExtA_12.json" 2>&1
Latn.GAG_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.GAG/Sun-ExtA_16/pdf_to_json_test_Latn.GAG_Sun-ExtA_16.py" > "data/multilingual/Latn.GAG/Sun-ExtA_16/pdf_to_json_test_Latn.GAG_Sun-ExtA_16.json" 2>&1
Latn.GAG_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.GAG/Sun-ExtA_8/pdf_to_json_test_Latn.GAG_Sun-ExtA_8.py" > "data/multilingual/Latn.GAG/Sun-ExtA_8/pdf_to_json_test_Latn.GAG_Sun-ExtA_8.json" 2>&1


Latn.GAG_all : Latn.GAG_Mono_12 Latn.GAG_Mono_16 Latn.GAG_Mono_8 Latn.GAG_Sans_12 Latn.GAG_Sans_16 Latn.GAG_Sans_8 Latn.GAG_Serif_12 Latn.GAG_Serif_16 Latn.GAG_Serif_8 Latn.GAG_Sun-ExtA_12 Latn.GAG_Sun-ExtA_16 Latn.GAG_Sun-ExtA_8
