PYTHON=python3


Latn.LIT_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.LIT/Mono_12/pdf_to_json_test_Latn.LIT_Mono_12.py" > "data/multilingual/Latn.LIT/Mono_12/pdf_to_json_test_Latn.LIT_Mono_12.json" 2>&1
Latn.LIT_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.LIT/Mono_16/pdf_to_json_test_Latn.LIT_Mono_16.py" > "data/multilingual/Latn.LIT/Mono_16/pdf_to_json_test_Latn.LIT_Mono_16.json" 2>&1
Latn.LIT_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.LIT/Mono_8/pdf_to_json_test_Latn.LIT_Mono_8.py" > "data/multilingual/Latn.LIT/Mono_8/pdf_to_json_test_Latn.LIT_Mono_8.json" 2>&1
Latn.LIT_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.LIT/Sans_12/pdf_to_json_test_Latn.LIT_Sans_12.py" > "data/multilingual/Latn.LIT/Sans_12/pdf_to_json_test_Latn.LIT_Sans_12.json" 2>&1
Latn.LIT_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.LIT/Sans_16/pdf_to_json_test_Latn.LIT_Sans_16.py" > "data/multilingual/Latn.LIT/Sans_16/pdf_to_json_test_Latn.LIT_Sans_16.json" 2>&1
Latn.LIT_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.LIT/Sans_8/pdf_to_json_test_Latn.LIT_Sans_8.py" > "data/multilingual/Latn.LIT/Sans_8/pdf_to_json_test_Latn.LIT_Sans_8.json" 2>&1
Latn.LIT_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.LIT/Serif_12/pdf_to_json_test_Latn.LIT_Serif_12.py" > "data/multilingual/Latn.LIT/Serif_12/pdf_to_json_test_Latn.LIT_Serif_12.json" 2>&1
Latn.LIT_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.LIT/Serif_16/pdf_to_json_test_Latn.LIT_Serif_16.py" > "data/multilingual/Latn.LIT/Serif_16/pdf_to_json_test_Latn.LIT_Serif_16.json" 2>&1
Latn.LIT_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.LIT/Serif_8/pdf_to_json_test_Latn.LIT_Serif_8.py" > "data/multilingual/Latn.LIT/Serif_8/pdf_to_json_test_Latn.LIT_Serif_8.json" 2>&1
Latn.LIT_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.LIT/Sun-ExtA_12/pdf_to_json_test_Latn.LIT_Sun-ExtA_12.py" > "data/multilingual/Latn.LIT/Sun-ExtA_12/pdf_to_json_test_Latn.LIT_Sun-ExtA_12.json" 2>&1
Latn.LIT_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.LIT/Sun-ExtA_16/pdf_to_json_test_Latn.LIT_Sun-ExtA_16.py" > "data/multilingual/Latn.LIT/Sun-ExtA_16/pdf_to_json_test_Latn.LIT_Sun-ExtA_16.json" 2>&1
Latn.LIT_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.LIT/Sun-ExtA_8/pdf_to_json_test_Latn.LIT_Sun-ExtA_8.py" > "data/multilingual/Latn.LIT/Sun-ExtA_8/pdf_to_json_test_Latn.LIT_Sun-ExtA_8.json" 2>&1


Latn.LIT_all : Latn.LIT_Mono_12 Latn.LIT_Mono_16 Latn.LIT_Mono_8 Latn.LIT_Sans_12 Latn.LIT_Sans_16 Latn.LIT_Sans_8 Latn.LIT_Serif_12 Latn.LIT_Serif_16 Latn.LIT_Serif_8 Latn.LIT_Sun-ExtA_12 Latn.LIT_Sun-ExtA_16 Latn.LIT_Sun-ExtA_8
