PYTHON=python3


Deva.SAN_Mono_12:
	-$(PYTHON) data/multilingual/Deva.SAN/Mono_12/pdf_to_json_test_Deva.SAN_Mono_12.py > data/multilingual/Deva.SAN/Mono_12/pdf_to_json_test_Deva.SAN_Mono_12.json 2>&1
Deva.SAN_Mono_16:
	-$(PYTHON) data/multilingual/Deva.SAN/Mono_16/pdf_to_json_test_Deva.SAN_Mono_16.py > data/multilingual/Deva.SAN/Mono_16/pdf_to_json_test_Deva.SAN_Mono_16.json 2>&1
Deva.SAN_Mono_8:
	-$(PYTHON) data/multilingual/Deva.SAN/Mono_8/pdf_to_json_test_Deva.SAN_Mono_8.py > data/multilingual/Deva.SAN/Mono_8/pdf_to_json_test_Deva.SAN_Mono_8.json 2>&1
Deva.SAN_Sans_12:
	-$(PYTHON) data/multilingual/Deva.SAN/Sans_12/pdf_to_json_test_Deva.SAN_Sans_12.py > data/multilingual/Deva.SAN/Sans_12/pdf_to_json_test_Deva.SAN_Sans_12.json 2>&1
Deva.SAN_Sans_16:
	-$(PYTHON) data/multilingual/Deva.SAN/Sans_16/pdf_to_json_test_Deva.SAN_Sans_16.py > data/multilingual/Deva.SAN/Sans_16/pdf_to_json_test_Deva.SAN_Sans_16.json 2>&1
Deva.SAN_Sans_8:
	-$(PYTHON) data/multilingual/Deva.SAN/Sans_8/pdf_to_json_test_Deva.SAN_Sans_8.py > data/multilingual/Deva.SAN/Sans_8/pdf_to_json_test_Deva.SAN_Sans_8.json 2>&1
Deva.SAN_Serif_12:
	-$(PYTHON) data/multilingual/Deva.SAN/Serif_12/pdf_to_json_test_Deva.SAN_Serif_12.py > data/multilingual/Deva.SAN/Serif_12/pdf_to_json_test_Deva.SAN_Serif_12.json 2>&1
Deva.SAN_Serif_16:
	-$(PYTHON) data/multilingual/Deva.SAN/Serif_16/pdf_to_json_test_Deva.SAN_Serif_16.py > data/multilingual/Deva.SAN/Serif_16/pdf_to_json_test_Deva.SAN_Serif_16.json 2>&1
Deva.SAN_Serif_8:
	-$(PYTHON) data/multilingual/Deva.SAN/Serif_8/pdf_to_json_test_Deva.SAN_Serif_8.py > data/multilingual/Deva.SAN/Serif_8/pdf_to_json_test_Deva.SAN_Serif_8.json 2>&1
Deva.SAN_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Deva.SAN/Sun-ExtA_12/pdf_to_json_test_Deva.SAN_Sun-ExtA_12.py > data/multilingual/Deva.SAN/Sun-ExtA_12/pdf_to_json_test_Deva.SAN_Sun-ExtA_12.json 2>&1
Deva.SAN_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Deva.SAN/Sun-ExtA_16/pdf_to_json_test_Deva.SAN_Sun-ExtA_16.py > data/multilingual/Deva.SAN/Sun-ExtA_16/pdf_to_json_test_Deva.SAN_Sun-ExtA_16.json 2>&1
Deva.SAN_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Deva.SAN/Sun-ExtA_8/pdf_to_json_test_Deva.SAN_Sun-ExtA_8.py > data/multilingual/Deva.SAN/Sun-ExtA_8/pdf_to_json_test_Deva.SAN_Sun-ExtA_8.json 2>&1


Deva.SAN_all : Deva.SAN_Mono_12 Deva.SAN_Mono_16 Deva.SAN_Mono_8 Deva.SAN_Sans_12 Deva.SAN_Sans_16 Deva.SAN_Sans_8 Deva.SAN_Serif_12 Deva.SAN_Serif_16 Deva.SAN_Serif_8 Deva.SAN_Sun-ExtA_12 Deva.SAN_Sun-ExtA_16 Deva.SAN_Sun-ExtA_8
