PYTHON=python3


Latn.ZYB_Mono_12:
	-$(PYTHON) data/multilingual/Latn.ZYB/Mono_12/pdf_to_json_test_Latn.ZYB_Mono_12.py > data/multilingual/Latn.ZYB/Mono_12/pdf_to_json_test_Latn.ZYB_Mono_12.json 2>&1
Latn.ZYB_Mono_16:
	-$(PYTHON) data/multilingual/Latn.ZYB/Mono_16/pdf_to_json_test_Latn.ZYB_Mono_16.py > data/multilingual/Latn.ZYB/Mono_16/pdf_to_json_test_Latn.ZYB_Mono_16.json 2>&1
Latn.ZYB_Mono_8:
	-$(PYTHON) data/multilingual/Latn.ZYB/Mono_8/pdf_to_json_test_Latn.ZYB_Mono_8.py > data/multilingual/Latn.ZYB/Mono_8/pdf_to_json_test_Latn.ZYB_Mono_8.json 2>&1
Latn.ZYB_Sans_12:
	-$(PYTHON) data/multilingual/Latn.ZYB/Sans_12/pdf_to_json_test_Latn.ZYB_Sans_12.py > data/multilingual/Latn.ZYB/Sans_12/pdf_to_json_test_Latn.ZYB_Sans_12.json 2>&1
Latn.ZYB_Sans_16:
	-$(PYTHON) data/multilingual/Latn.ZYB/Sans_16/pdf_to_json_test_Latn.ZYB_Sans_16.py > data/multilingual/Latn.ZYB/Sans_16/pdf_to_json_test_Latn.ZYB_Sans_16.json 2>&1
Latn.ZYB_Sans_8:
	-$(PYTHON) data/multilingual/Latn.ZYB/Sans_8/pdf_to_json_test_Latn.ZYB_Sans_8.py > data/multilingual/Latn.ZYB/Sans_8/pdf_to_json_test_Latn.ZYB_Sans_8.json 2>&1
Latn.ZYB_Serif_12:
	-$(PYTHON) data/multilingual/Latn.ZYB/Serif_12/pdf_to_json_test_Latn.ZYB_Serif_12.py > data/multilingual/Latn.ZYB/Serif_12/pdf_to_json_test_Latn.ZYB_Serif_12.json 2>&1
Latn.ZYB_Serif_16:
	-$(PYTHON) data/multilingual/Latn.ZYB/Serif_16/pdf_to_json_test_Latn.ZYB_Serif_16.py > data/multilingual/Latn.ZYB/Serif_16/pdf_to_json_test_Latn.ZYB_Serif_16.json 2>&1
Latn.ZYB_Serif_8:
	-$(PYTHON) data/multilingual/Latn.ZYB/Serif_8/pdf_to_json_test_Latn.ZYB_Serif_8.py > data/multilingual/Latn.ZYB/Serif_8/pdf_to_json_test_Latn.ZYB_Serif_8.json 2>&1
Latn.ZYB_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.ZYB/Sun-ExtA_12/pdf_to_json_test_Latn.ZYB_Sun-ExtA_12.py > data/multilingual/Latn.ZYB/Sun-ExtA_12/pdf_to_json_test_Latn.ZYB_Sun-ExtA_12.json 2>&1
Latn.ZYB_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.ZYB/Sun-ExtA_16/pdf_to_json_test_Latn.ZYB_Sun-ExtA_16.py > data/multilingual/Latn.ZYB/Sun-ExtA_16/pdf_to_json_test_Latn.ZYB_Sun-ExtA_16.json 2>&1
Latn.ZYB_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.ZYB/Sun-ExtA_8/pdf_to_json_test_Latn.ZYB_Sun-ExtA_8.py > data/multilingual/Latn.ZYB/Sun-ExtA_8/pdf_to_json_test_Latn.ZYB_Sun-ExtA_8.json 2>&1


Latn.ZYB_all : Latn.ZYB_Mono_12 Latn.ZYB_Mono_16 Latn.ZYB_Mono_8 Latn.ZYB_Sans_12 Latn.ZYB_Sans_16 Latn.ZYB_Sans_8 Latn.ZYB_Serif_12 Latn.ZYB_Serif_16 Latn.ZYB_Serif_8 Latn.ZYB_Sun-ExtA_12 Latn.ZYB_Sun-ExtA_16 Latn.ZYB_Sun-ExtA_8
