PYTHON=python3


Arab.PES_Mono_12:
	-$(PYTHON) "data/multilingual/Arab.PES/Mono_12/pdf_to_json_test_Arab.PES_Mono_12.py" > "data/multilingual/Arab.PES/Mono_12/pdf_to_json_test_Arab.PES_Mono_12.json" 2>&1
Arab.PES_Mono_16:
	-$(PYTHON) "data/multilingual/Arab.PES/Mono_16/pdf_to_json_test_Arab.PES_Mono_16.py" > "data/multilingual/Arab.PES/Mono_16/pdf_to_json_test_Arab.PES_Mono_16.json" 2>&1
Arab.PES_Mono_8:
	-$(PYTHON) "data/multilingual/Arab.PES/Mono_8/pdf_to_json_test_Arab.PES_Mono_8.py" > "data/multilingual/Arab.PES/Mono_8/pdf_to_json_test_Arab.PES_Mono_8.json" 2>&1
Arab.PES_Sans_12:
	-$(PYTHON) "data/multilingual/Arab.PES/Sans_12/pdf_to_json_test_Arab.PES_Sans_12.py" > "data/multilingual/Arab.PES/Sans_12/pdf_to_json_test_Arab.PES_Sans_12.json" 2>&1
Arab.PES_Sans_16:
	-$(PYTHON) "data/multilingual/Arab.PES/Sans_16/pdf_to_json_test_Arab.PES_Sans_16.py" > "data/multilingual/Arab.PES/Sans_16/pdf_to_json_test_Arab.PES_Sans_16.json" 2>&1
Arab.PES_Sans_8:
	-$(PYTHON) "data/multilingual/Arab.PES/Sans_8/pdf_to_json_test_Arab.PES_Sans_8.py" > "data/multilingual/Arab.PES/Sans_8/pdf_to_json_test_Arab.PES_Sans_8.json" 2>&1
Arab.PES_Serif_12:
	-$(PYTHON) "data/multilingual/Arab.PES/Serif_12/pdf_to_json_test_Arab.PES_Serif_12.py" > "data/multilingual/Arab.PES/Serif_12/pdf_to_json_test_Arab.PES_Serif_12.json" 2>&1
Arab.PES_Serif_16:
	-$(PYTHON) "data/multilingual/Arab.PES/Serif_16/pdf_to_json_test_Arab.PES_Serif_16.py" > "data/multilingual/Arab.PES/Serif_16/pdf_to_json_test_Arab.PES_Serif_16.json" 2>&1
Arab.PES_Serif_8:
	-$(PYTHON) "data/multilingual/Arab.PES/Serif_8/pdf_to_json_test_Arab.PES_Serif_8.py" > "data/multilingual/Arab.PES/Serif_8/pdf_to_json_test_Arab.PES_Serif_8.json" 2>&1
Arab.PES_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Arab.PES/Sun-ExtA_12/pdf_to_json_test_Arab.PES_Sun-ExtA_12.py" > "data/multilingual/Arab.PES/Sun-ExtA_12/pdf_to_json_test_Arab.PES_Sun-ExtA_12.json" 2>&1
Arab.PES_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Arab.PES/Sun-ExtA_16/pdf_to_json_test_Arab.PES_Sun-ExtA_16.py" > "data/multilingual/Arab.PES/Sun-ExtA_16/pdf_to_json_test_Arab.PES_Sun-ExtA_16.json" 2>&1
Arab.PES_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Arab.PES/Sun-ExtA_8/pdf_to_json_test_Arab.PES_Sun-ExtA_8.py" > "data/multilingual/Arab.PES/Sun-ExtA_8/pdf_to_json_test_Arab.PES_Sun-ExtA_8.json" 2>&1


Arab.PES_all : Arab.PES_Mono_12 Arab.PES_Mono_16 Arab.PES_Mono_8 Arab.PES_Sans_12 Arab.PES_Sans_16 Arab.PES_Sans_8 Arab.PES_Serif_12 Arab.PES_Serif_16 Arab.PES_Serif_8 Arab.PES_Sun-ExtA_12 Arab.PES_Sun-ExtA_16 Arab.PES_Sun-ExtA_8
