PYTHON=python3


Latn.KAL_Mono_12:
	-$(PYTHON) data/multilingual/Latn.KAL/Mono_12/pdf_to_json_test_Latn.KAL_Mono_12.py > data/multilingual/Latn.KAL/Mono_12/pdf_to_json_test_Latn.KAL_Mono_12.json 2>&1
Latn.KAL_Mono_16:
	-$(PYTHON) data/multilingual/Latn.KAL/Mono_16/pdf_to_json_test_Latn.KAL_Mono_16.py > data/multilingual/Latn.KAL/Mono_16/pdf_to_json_test_Latn.KAL_Mono_16.json 2>&1
Latn.KAL_Mono_8:
	-$(PYTHON) data/multilingual/Latn.KAL/Mono_8/pdf_to_json_test_Latn.KAL_Mono_8.py > data/multilingual/Latn.KAL/Mono_8/pdf_to_json_test_Latn.KAL_Mono_8.json 2>&1
Latn.KAL_Sans_12:
	-$(PYTHON) data/multilingual/Latn.KAL/Sans_12/pdf_to_json_test_Latn.KAL_Sans_12.py > data/multilingual/Latn.KAL/Sans_12/pdf_to_json_test_Latn.KAL_Sans_12.json 2>&1
Latn.KAL_Sans_16:
	-$(PYTHON) data/multilingual/Latn.KAL/Sans_16/pdf_to_json_test_Latn.KAL_Sans_16.py > data/multilingual/Latn.KAL/Sans_16/pdf_to_json_test_Latn.KAL_Sans_16.json 2>&1
Latn.KAL_Sans_8:
	-$(PYTHON) data/multilingual/Latn.KAL/Sans_8/pdf_to_json_test_Latn.KAL_Sans_8.py > data/multilingual/Latn.KAL/Sans_8/pdf_to_json_test_Latn.KAL_Sans_8.json 2>&1
Latn.KAL_Serif_12:
	-$(PYTHON) data/multilingual/Latn.KAL/Serif_12/pdf_to_json_test_Latn.KAL_Serif_12.py > data/multilingual/Latn.KAL/Serif_12/pdf_to_json_test_Latn.KAL_Serif_12.json 2>&1
Latn.KAL_Serif_16:
	-$(PYTHON) data/multilingual/Latn.KAL/Serif_16/pdf_to_json_test_Latn.KAL_Serif_16.py > data/multilingual/Latn.KAL/Serif_16/pdf_to_json_test_Latn.KAL_Serif_16.json 2>&1
Latn.KAL_Serif_8:
	-$(PYTHON) data/multilingual/Latn.KAL/Serif_8/pdf_to_json_test_Latn.KAL_Serif_8.py > data/multilingual/Latn.KAL/Serif_8/pdf_to_json_test_Latn.KAL_Serif_8.json 2>&1
Latn.KAL_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.KAL/Sun-ExtA_12/pdf_to_json_test_Latn.KAL_Sun-ExtA_12.py > data/multilingual/Latn.KAL/Sun-ExtA_12/pdf_to_json_test_Latn.KAL_Sun-ExtA_12.json 2>&1
Latn.KAL_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.KAL/Sun-ExtA_16/pdf_to_json_test_Latn.KAL_Sun-ExtA_16.py > data/multilingual/Latn.KAL/Sun-ExtA_16/pdf_to_json_test_Latn.KAL_Sun-ExtA_16.json 2>&1
Latn.KAL_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.KAL/Sun-ExtA_8/pdf_to_json_test_Latn.KAL_Sun-ExtA_8.py > data/multilingual/Latn.KAL/Sun-ExtA_8/pdf_to_json_test_Latn.KAL_Sun-ExtA_8.json 2>&1


Latn.KAL_all : Latn.KAL_Mono_12 Latn.KAL_Mono_16 Latn.KAL_Mono_8 Latn.KAL_Sans_12 Latn.KAL_Sans_16 Latn.KAL_Sans_8 Latn.KAL_Serif_12 Latn.KAL_Serif_16 Latn.KAL_Serif_8 Latn.KAL_Sun-ExtA_12 Latn.KAL_Sun-ExtA_16 Latn.KAL_Sun-ExtA_8
