PYTHON=python3


Tfng.TZM_Mono_12:
	-$(PYTHON) "data/multilingual/Tfng.TZM/Mono_12/pdf_to_json_test_Tfng.TZM_Mono_12.py" > "data/multilingual/Tfng.TZM/Mono_12/pdf_to_json_test_Tfng.TZM_Mono_12.json" 2>&1
Tfng.TZM_Mono_16:
	-$(PYTHON) "data/multilingual/Tfng.TZM/Mono_16/pdf_to_json_test_Tfng.TZM_Mono_16.py" > "data/multilingual/Tfng.TZM/Mono_16/pdf_to_json_test_Tfng.TZM_Mono_16.json" 2>&1
Tfng.TZM_Mono_8:
	-$(PYTHON) "data/multilingual/Tfng.TZM/Mono_8/pdf_to_json_test_Tfng.TZM_Mono_8.py" > "data/multilingual/Tfng.TZM/Mono_8/pdf_to_json_test_Tfng.TZM_Mono_8.json" 2>&1
Tfng.TZM_Sans_12:
	-$(PYTHON) "data/multilingual/Tfng.TZM/Sans_12/pdf_to_json_test_Tfng.TZM_Sans_12.py" > "data/multilingual/Tfng.TZM/Sans_12/pdf_to_json_test_Tfng.TZM_Sans_12.json" 2>&1
Tfng.TZM_Sans_16:
	-$(PYTHON) "data/multilingual/Tfng.TZM/Sans_16/pdf_to_json_test_Tfng.TZM_Sans_16.py" > "data/multilingual/Tfng.TZM/Sans_16/pdf_to_json_test_Tfng.TZM_Sans_16.json" 2>&1
Tfng.TZM_Sans_8:
	-$(PYTHON) "data/multilingual/Tfng.TZM/Sans_8/pdf_to_json_test_Tfng.TZM_Sans_8.py" > "data/multilingual/Tfng.TZM/Sans_8/pdf_to_json_test_Tfng.TZM_Sans_8.json" 2>&1
Tfng.TZM_Serif_12:
	-$(PYTHON) "data/multilingual/Tfng.TZM/Serif_12/pdf_to_json_test_Tfng.TZM_Serif_12.py" > "data/multilingual/Tfng.TZM/Serif_12/pdf_to_json_test_Tfng.TZM_Serif_12.json" 2>&1
Tfng.TZM_Serif_16:
	-$(PYTHON) "data/multilingual/Tfng.TZM/Serif_16/pdf_to_json_test_Tfng.TZM_Serif_16.py" > "data/multilingual/Tfng.TZM/Serif_16/pdf_to_json_test_Tfng.TZM_Serif_16.json" 2>&1
Tfng.TZM_Serif_8:
	-$(PYTHON) "data/multilingual/Tfng.TZM/Serif_8/pdf_to_json_test_Tfng.TZM_Serif_8.py" > "data/multilingual/Tfng.TZM/Serif_8/pdf_to_json_test_Tfng.TZM_Serif_8.json" 2>&1
Tfng.TZM_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Tfng.TZM/Sun-ExtA_12/pdf_to_json_test_Tfng.TZM_Sun-ExtA_12.py" > "data/multilingual/Tfng.TZM/Sun-ExtA_12/pdf_to_json_test_Tfng.TZM_Sun-ExtA_12.json" 2>&1
Tfng.TZM_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Tfng.TZM/Sun-ExtA_16/pdf_to_json_test_Tfng.TZM_Sun-ExtA_16.py" > "data/multilingual/Tfng.TZM/Sun-ExtA_16/pdf_to_json_test_Tfng.TZM_Sun-ExtA_16.json" 2>&1
Tfng.TZM_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Tfng.TZM/Sun-ExtA_8/pdf_to_json_test_Tfng.TZM_Sun-ExtA_8.py" > "data/multilingual/Tfng.TZM/Sun-ExtA_8/pdf_to_json_test_Tfng.TZM_Sun-ExtA_8.json" 2>&1


Tfng.TZM_all : Tfng.TZM_Mono_12 Tfng.TZM_Mono_16 Tfng.TZM_Mono_8 Tfng.TZM_Sans_12 Tfng.TZM_Sans_16 Tfng.TZM_Sans_8 Tfng.TZM_Serif_12 Tfng.TZM_Serif_16 Tfng.TZM_Serif_8 Tfng.TZM_Sun-ExtA_12 Tfng.TZM_Sun-ExtA_16 Tfng.TZM_Sun-ExtA_8
