PYTHON=python3


Latn.NBA_Mono_12:
	-$(PYTHON) data/multilingual/Latn.NBA/Mono_12/pdf_to_json_test_Latn.NBA_Mono_12.py > data/multilingual/Latn.NBA/Mono_12/pdf_to_json_test_Latn.NBA_Mono_12.json 2>&1
Latn.NBA_Mono_16:
	-$(PYTHON) data/multilingual/Latn.NBA/Mono_16/pdf_to_json_test_Latn.NBA_Mono_16.py > data/multilingual/Latn.NBA/Mono_16/pdf_to_json_test_Latn.NBA_Mono_16.json 2>&1
Latn.NBA_Mono_8:
	-$(PYTHON) data/multilingual/Latn.NBA/Mono_8/pdf_to_json_test_Latn.NBA_Mono_8.py > data/multilingual/Latn.NBA/Mono_8/pdf_to_json_test_Latn.NBA_Mono_8.json 2>&1
Latn.NBA_Sans_12:
	-$(PYTHON) data/multilingual/Latn.NBA/Sans_12/pdf_to_json_test_Latn.NBA_Sans_12.py > data/multilingual/Latn.NBA/Sans_12/pdf_to_json_test_Latn.NBA_Sans_12.json 2>&1
Latn.NBA_Sans_16:
	-$(PYTHON) data/multilingual/Latn.NBA/Sans_16/pdf_to_json_test_Latn.NBA_Sans_16.py > data/multilingual/Latn.NBA/Sans_16/pdf_to_json_test_Latn.NBA_Sans_16.json 2>&1
Latn.NBA_Sans_8:
	-$(PYTHON) data/multilingual/Latn.NBA/Sans_8/pdf_to_json_test_Latn.NBA_Sans_8.py > data/multilingual/Latn.NBA/Sans_8/pdf_to_json_test_Latn.NBA_Sans_8.json 2>&1
Latn.NBA_Serif_12:
	-$(PYTHON) data/multilingual/Latn.NBA/Serif_12/pdf_to_json_test_Latn.NBA_Serif_12.py > data/multilingual/Latn.NBA/Serif_12/pdf_to_json_test_Latn.NBA_Serif_12.json 2>&1
Latn.NBA_Serif_16:
	-$(PYTHON) data/multilingual/Latn.NBA/Serif_16/pdf_to_json_test_Latn.NBA_Serif_16.py > data/multilingual/Latn.NBA/Serif_16/pdf_to_json_test_Latn.NBA_Serif_16.json 2>&1
Latn.NBA_Serif_8:
	-$(PYTHON) data/multilingual/Latn.NBA/Serif_8/pdf_to_json_test_Latn.NBA_Serif_8.py > data/multilingual/Latn.NBA/Serif_8/pdf_to_json_test_Latn.NBA_Serif_8.json 2>&1
Latn.NBA_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.NBA/Sun-ExtA_12/pdf_to_json_test_Latn.NBA_Sun-ExtA_12.py > data/multilingual/Latn.NBA/Sun-ExtA_12/pdf_to_json_test_Latn.NBA_Sun-ExtA_12.json 2>&1
Latn.NBA_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.NBA/Sun-ExtA_16/pdf_to_json_test_Latn.NBA_Sun-ExtA_16.py > data/multilingual/Latn.NBA/Sun-ExtA_16/pdf_to_json_test_Latn.NBA_Sun-ExtA_16.json 2>&1
Latn.NBA_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.NBA/Sun-ExtA_8/pdf_to_json_test_Latn.NBA_Sun-ExtA_8.py > data/multilingual/Latn.NBA/Sun-ExtA_8/pdf_to_json_test_Latn.NBA_Sun-ExtA_8.json 2>&1


Latn.NBA_all : Latn.NBA_Mono_12 Latn.NBA_Mono_16 Latn.NBA_Mono_8 Latn.NBA_Sans_12 Latn.NBA_Sans_16 Latn.NBA_Sans_8 Latn.NBA_Serif_12 Latn.NBA_Serif_16 Latn.NBA_Serif_8 Latn.NBA_Sun-ExtA_12 Latn.NBA_Sun-ExtA_16 Latn.NBA_Sun-ExtA_8
