PYTHON=python3


Latn.SOT_Mono_12:
	-$(PYTHON) data/multilingual/Latn.SOT/Mono_12/pdf_to_json_test_Latn.SOT_Mono_12.py > data/multilingual/Latn.SOT/Mono_12/pdf_to_json_test_Latn.SOT_Mono_12.json 2>&1
Latn.SOT_Mono_16:
	-$(PYTHON) data/multilingual/Latn.SOT/Mono_16/pdf_to_json_test_Latn.SOT_Mono_16.py > data/multilingual/Latn.SOT/Mono_16/pdf_to_json_test_Latn.SOT_Mono_16.json 2>&1
Latn.SOT_Mono_8:
	-$(PYTHON) data/multilingual/Latn.SOT/Mono_8/pdf_to_json_test_Latn.SOT_Mono_8.py > data/multilingual/Latn.SOT/Mono_8/pdf_to_json_test_Latn.SOT_Mono_8.json 2>&1
Latn.SOT_Sans_12:
	-$(PYTHON) data/multilingual/Latn.SOT/Sans_12/pdf_to_json_test_Latn.SOT_Sans_12.py > data/multilingual/Latn.SOT/Sans_12/pdf_to_json_test_Latn.SOT_Sans_12.json 2>&1
Latn.SOT_Sans_16:
	-$(PYTHON) data/multilingual/Latn.SOT/Sans_16/pdf_to_json_test_Latn.SOT_Sans_16.py > data/multilingual/Latn.SOT/Sans_16/pdf_to_json_test_Latn.SOT_Sans_16.json 2>&1
Latn.SOT_Sans_8:
	-$(PYTHON) data/multilingual/Latn.SOT/Sans_8/pdf_to_json_test_Latn.SOT_Sans_8.py > data/multilingual/Latn.SOT/Sans_8/pdf_to_json_test_Latn.SOT_Sans_8.json 2>&1
Latn.SOT_Serif_12:
	-$(PYTHON) data/multilingual/Latn.SOT/Serif_12/pdf_to_json_test_Latn.SOT_Serif_12.py > data/multilingual/Latn.SOT/Serif_12/pdf_to_json_test_Latn.SOT_Serif_12.json 2>&1
Latn.SOT_Serif_16:
	-$(PYTHON) data/multilingual/Latn.SOT/Serif_16/pdf_to_json_test_Latn.SOT_Serif_16.py > data/multilingual/Latn.SOT/Serif_16/pdf_to_json_test_Latn.SOT_Serif_16.json 2>&1
Latn.SOT_Serif_8:
	-$(PYTHON) data/multilingual/Latn.SOT/Serif_8/pdf_to_json_test_Latn.SOT_Serif_8.py > data/multilingual/Latn.SOT/Serif_8/pdf_to_json_test_Latn.SOT_Serif_8.json 2>&1
Latn.SOT_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.SOT/Sun-ExtA_12/pdf_to_json_test_Latn.SOT_Sun-ExtA_12.py > data/multilingual/Latn.SOT/Sun-ExtA_12/pdf_to_json_test_Latn.SOT_Sun-ExtA_12.json 2>&1
Latn.SOT_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.SOT/Sun-ExtA_16/pdf_to_json_test_Latn.SOT_Sun-ExtA_16.py > data/multilingual/Latn.SOT/Sun-ExtA_16/pdf_to_json_test_Latn.SOT_Sun-ExtA_16.json 2>&1
Latn.SOT_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.SOT/Sun-ExtA_8/pdf_to_json_test_Latn.SOT_Sun-ExtA_8.py > data/multilingual/Latn.SOT/Sun-ExtA_8/pdf_to_json_test_Latn.SOT_Sun-ExtA_8.json 2>&1


Latn.SOT_all : Latn.SOT_Mono_12 Latn.SOT_Mono_16 Latn.SOT_Mono_8 Latn.SOT_Sans_12 Latn.SOT_Sans_16 Latn.SOT_Sans_8 Latn.SOT_Serif_12 Latn.SOT_Serif_16 Latn.SOT_Serif_8 Latn.SOT_Sun-ExtA_12 Latn.SOT_Sun-ExtA_16 Latn.SOT_Sun-ExtA_8
