PYTHON=python3


Latn.RMN_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.RMN/Mono_12/pdf_to_json_test_Latn.RMN_Mono_12.py" > "data/multilingual/Latn.RMN/Mono_12/pdf_to_json_test_Latn.RMN_Mono_12.json" 2>&1
Latn.RMN_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.RMN/Mono_16/pdf_to_json_test_Latn.RMN_Mono_16.py" > "data/multilingual/Latn.RMN/Mono_16/pdf_to_json_test_Latn.RMN_Mono_16.json" 2>&1
Latn.RMN_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.RMN/Mono_8/pdf_to_json_test_Latn.RMN_Mono_8.py" > "data/multilingual/Latn.RMN/Mono_8/pdf_to_json_test_Latn.RMN_Mono_8.json" 2>&1
Latn.RMN_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.RMN/Sans_12/pdf_to_json_test_Latn.RMN_Sans_12.py" > "data/multilingual/Latn.RMN/Sans_12/pdf_to_json_test_Latn.RMN_Sans_12.json" 2>&1
Latn.RMN_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.RMN/Sans_16/pdf_to_json_test_Latn.RMN_Sans_16.py" > "data/multilingual/Latn.RMN/Sans_16/pdf_to_json_test_Latn.RMN_Sans_16.json" 2>&1
Latn.RMN_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.RMN/Sans_8/pdf_to_json_test_Latn.RMN_Sans_8.py" > "data/multilingual/Latn.RMN/Sans_8/pdf_to_json_test_Latn.RMN_Sans_8.json" 2>&1
Latn.RMN_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.RMN/Serif_12/pdf_to_json_test_Latn.RMN_Serif_12.py" > "data/multilingual/Latn.RMN/Serif_12/pdf_to_json_test_Latn.RMN_Serif_12.json" 2>&1
Latn.RMN_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.RMN/Serif_16/pdf_to_json_test_Latn.RMN_Serif_16.py" > "data/multilingual/Latn.RMN/Serif_16/pdf_to_json_test_Latn.RMN_Serif_16.json" 2>&1
Latn.RMN_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.RMN/Serif_8/pdf_to_json_test_Latn.RMN_Serif_8.py" > "data/multilingual/Latn.RMN/Serif_8/pdf_to_json_test_Latn.RMN_Serif_8.json" 2>&1
Latn.RMN_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.RMN/Sun-ExtA_12/pdf_to_json_test_Latn.RMN_Sun-ExtA_12.py" > "data/multilingual/Latn.RMN/Sun-ExtA_12/pdf_to_json_test_Latn.RMN_Sun-ExtA_12.json" 2>&1
Latn.RMN_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.RMN/Sun-ExtA_16/pdf_to_json_test_Latn.RMN_Sun-ExtA_16.py" > "data/multilingual/Latn.RMN/Sun-ExtA_16/pdf_to_json_test_Latn.RMN_Sun-ExtA_16.json" 2>&1
Latn.RMN_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.RMN/Sun-ExtA_8/pdf_to_json_test_Latn.RMN_Sun-ExtA_8.py" > "data/multilingual/Latn.RMN/Sun-ExtA_8/pdf_to_json_test_Latn.RMN_Sun-ExtA_8.json" 2>&1


Latn.RMN_all : Latn.RMN_Mono_12 Latn.RMN_Mono_16 Latn.RMN_Mono_8 Latn.RMN_Sans_12 Latn.RMN_Sans_16 Latn.RMN_Sans_8 Latn.RMN_Serif_12 Latn.RMN_Serif_16 Latn.RMN_Serif_8 Latn.RMN_Sun-ExtA_12 Latn.RMN_Sun-ExtA_16 Latn.RMN_Sun-ExtA_8
