PYTHON=python3


Latn.CES_Mono_12:
	-$(PYTHON) data/multilingual/Latn.CES/Mono_12/pdf_to_json_test_Latn.CES_Mono_12.py > data/multilingual/Latn.CES/Mono_12/pdf_to_json_test_Latn.CES_Mono_12.json 2>&1
Latn.CES_Mono_16:
	-$(PYTHON) data/multilingual/Latn.CES/Mono_16/pdf_to_json_test_Latn.CES_Mono_16.py > data/multilingual/Latn.CES/Mono_16/pdf_to_json_test_Latn.CES_Mono_16.json 2>&1
Latn.CES_Mono_8:
	-$(PYTHON) data/multilingual/Latn.CES/Mono_8/pdf_to_json_test_Latn.CES_Mono_8.py > data/multilingual/Latn.CES/Mono_8/pdf_to_json_test_Latn.CES_Mono_8.json 2>&1
Latn.CES_Sans_12:
	-$(PYTHON) data/multilingual/Latn.CES/Sans_12/pdf_to_json_test_Latn.CES_Sans_12.py > data/multilingual/Latn.CES/Sans_12/pdf_to_json_test_Latn.CES_Sans_12.json 2>&1
Latn.CES_Sans_16:
	-$(PYTHON) data/multilingual/Latn.CES/Sans_16/pdf_to_json_test_Latn.CES_Sans_16.py > data/multilingual/Latn.CES/Sans_16/pdf_to_json_test_Latn.CES_Sans_16.json 2>&1
Latn.CES_Sans_8:
	-$(PYTHON) data/multilingual/Latn.CES/Sans_8/pdf_to_json_test_Latn.CES_Sans_8.py > data/multilingual/Latn.CES/Sans_8/pdf_to_json_test_Latn.CES_Sans_8.json 2>&1
Latn.CES_Serif_12:
	-$(PYTHON) data/multilingual/Latn.CES/Serif_12/pdf_to_json_test_Latn.CES_Serif_12.py > data/multilingual/Latn.CES/Serif_12/pdf_to_json_test_Latn.CES_Serif_12.json 2>&1
Latn.CES_Serif_16:
	-$(PYTHON) data/multilingual/Latn.CES/Serif_16/pdf_to_json_test_Latn.CES_Serif_16.py > data/multilingual/Latn.CES/Serif_16/pdf_to_json_test_Latn.CES_Serif_16.json 2>&1
Latn.CES_Serif_8:
	-$(PYTHON) data/multilingual/Latn.CES/Serif_8/pdf_to_json_test_Latn.CES_Serif_8.py > data/multilingual/Latn.CES/Serif_8/pdf_to_json_test_Latn.CES_Serif_8.json 2>&1
Latn.CES_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.CES/Sun-ExtA_12/pdf_to_json_test_Latn.CES_Sun-ExtA_12.py > data/multilingual/Latn.CES/Sun-ExtA_12/pdf_to_json_test_Latn.CES_Sun-ExtA_12.json 2>&1
Latn.CES_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.CES/Sun-ExtA_16/pdf_to_json_test_Latn.CES_Sun-ExtA_16.py > data/multilingual/Latn.CES/Sun-ExtA_16/pdf_to_json_test_Latn.CES_Sun-ExtA_16.json 2>&1
Latn.CES_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.CES/Sun-ExtA_8/pdf_to_json_test_Latn.CES_Sun-ExtA_8.py > data/multilingual/Latn.CES/Sun-ExtA_8/pdf_to_json_test_Latn.CES_Sun-ExtA_8.json 2>&1


Latn.CES_all : Latn.CES_Mono_12 Latn.CES_Mono_16 Latn.CES_Mono_8 Latn.CES_Sans_12 Latn.CES_Sans_16 Latn.CES_Sans_8 Latn.CES_Serif_12 Latn.CES_Serif_16 Latn.CES_Serif_8 Latn.CES_Sun-ExtA_12 Latn.CES_Sun-ExtA_16 Latn.CES_Sun-ExtA_8
