PYTHON=python3


Cyrl.KBD_Mono_12:
	-$(PYTHON) "data/multilingual/Cyrl.KBD/Mono_12/pdf_to_json_test_Cyrl.KBD_Mono_12.py" > "data/multilingual/Cyrl.KBD/Mono_12/pdf_to_json_test_Cyrl.KBD_Mono_12.json" 2>&1
Cyrl.KBD_Mono_16:
	-$(PYTHON) "data/multilingual/Cyrl.KBD/Mono_16/pdf_to_json_test_Cyrl.KBD_Mono_16.py" > "data/multilingual/Cyrl.KBD/Mono_16/pdf_to_json_test_Cyrl.KBD_Mono_16.json" 2>&1
Cyrl.KBD_Mono_8:
	-$(PYTHON) "data/multilingual/Cyrl.KBD/Mono_8/pdf_to_json_test_Cyrl.KBD_Mono_8.py" > "data/multilingual/Cyrl.KBD/Mono_8/pdf_to_json_test_Cyrl.KBD_Mono_8.json" 2>&1
Cyrl.KBD_Sans_12:
	-$(PYTHON) "data/multilingual/Cyrl.KBD/Sans_12/pdf_to_json_test_Cyrl.KBD_Sans_12.py" > "data/multilingual/Cyrl.KBD/Sans_12/pdf_to_json_test_Cyrl.KBD_Sans_12.json" 2>&1
Cyrl.KBD_Sans_16:
	-$(PYTHON) "data/multilingual/Cyrl.KBD/Sans_16/pdf_to_json_test_Cyrl.KBD_Sans_16.py" > "data/multilingual/Cyrl.KBD/Sans_16/pdf_to_json_test_Cyrl.KBD_Sans_16.json" 2>&1
Cyrl.KBD_Sans_8:
	-$(PYTHON) "data/multilingual/Cyrl.KBD/Sans_8/pdf_to_json_test_Cyrl.KBD_Sans_8.py" > "data/multilingual/Cyrl.KBD/Sans_8/pdf_to_json_test_Cyrl.KBD_Sans_8.json" 2>&1
Cyrl.KBD_Serif_12:
	-$(PYTHON) "data/multilingual/Cyrl.KBD/Serif_12/pdf_to_json_test_Cyrl.KBD_Serif_12.py" > "data/multilingual/Cyrl.KBD/Serif_12/pdf_to_json_test_Cyrl.KBD_Serif_12.json" 2>&1
Cyrl.KBD_Serif_16:
	-$(PYTHON) "data/multilingual/Cyrl.KBD/Serif_16/pdf_to_json_test_Cyrl.KBD_Serif_16.py" > "data/multilingual/Cyrl.KBD/Serif_16/pdf_to_json_test_Cyrl.KBD_Serif_16.json" 2>&1
Cyrl.KBD_Serif_8:
	-$(PYTHON) "data/multilingual/Cyrl.KBD/Serif_8/pdf_to_json_test_Cyrl.KBD_Serif_8.py" > "data/multilingual/Cyrl.KBD/Serif_8/pdf_to_json_test_Cyrl.KBD_Serif_8.json" 2>&1
Cyrl.KBD_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Cyrl.KBD/Sun-ExtA_12/pdf_to_json_test_Cyrl.KBD_Sun-ExtA_12.py" > "data/multilingual/Cyrl.KBD/Sun-ExtA_12/pdf_to_json_test_Cyrl.KBD_Sun-ExtA_12.json" 2>&1
Cyrl.KBD_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Cyrl.KBD/Sun-ExtA_16/pdf_to_json_test_Cyrl.KBD_Sun-ExtA_16.py" > "data/multilingual/Cyrl.KBD/Sun-ExtA_16/pdf_to_json_test_Cyrl.KBD_Sun-ExtA_16.json" 2>&1
Cyrl.KBD_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Cyrl.KBD/Sun-ExtA_8/pdf_to_json_test_Cyrl.KBD_Sun-ExtA_8.py" > "data/multilingual/Cyrl.KBD/Sun-ExtA_8/pdf_to_json_test_Cyrl.KBD_Sun-ExtA_8.json" 2>&1


Cyrl.KBD_all : Cyrl.KBD_Mono_12 Cyrl.KBD_Mono_16 Cyrl.KBD_Mono_8 Cyrl.KBD_Sans_12 Cyrl.KBD_Sans_16 Cyrl.KBD_Sans_8 Cyrl.KBD_Serif_12 Cyrl.KBD_Serif_16 Cyrl.KBD_Serif_8 Cyrl.KBD_Sun-ExtA_12 Cyrl.KBD_Sun-ExtA_16 Cyrl.KBD_Sun-ExtA_8
