PYTHON=python3


Latn.NHN_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.NHN/Mono_12/pdf_to_json_test_Latn.NHN_Mono_12.py" > "data/multilingual/Latn.NHN/Mono_12/pdf_to_json_test_Latn.NHN_Mono_12.json" 2>&1
Latn.NHN_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.NHN/Mono_16/pdf_to_json_test_Latn.NHN_Mono_16.py" > "data/multilingual/Latn.NHN/Mono_16/pdf_to_json_test_Latn.NHN_Mono_16.json" 2>&1
Latn.NHN_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.NHN/Mono_8/pdf_to_json_test_Latn.NHN_Mono_8.py" > "data/multilingual/Latn.NHN/Mono_8/pdf_to_json_test_Latn.NHN_Mono_8.json" 2>&1
Latn.NHN_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.NHN/Sans_12/pdf_to_json_test_Latn.NHN_Sans_12.py" > "data/multilingual/Latn.NHN/Sans_12/pdf_to_json_test_Latn.NHN_Sans_12.json" 2>&1
Latn.NHN_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.NHN/Sans_16/pdf_to_json_test_Latn.NHN_Sans_16.py" > "data/multilingual/Latn.NHN/Sans_16/pdf_to_json_test_Latn.NHN_Sans_16.json" 2>&1
Latn.NHN_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.NHN/Sans_8/pdf_to_json_test_Latn.NHN_Sans_8.py" > "data/multilingual/Latn.NHN/Sans_8/pdf_to_json_test_Latn.NHN_Sans_8.json" 2>&1
Latn.NHN_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.NHN/Serif_12/pdf_to_json_test_Latn.NHN_Serif_12.py" > "data/multilingual/Latn.NHN/Serif_12/pdf_to_json_test_Latn.NHN_Serif_12.json" 2>&1
Latn.NHN_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.NHN/Serif_16/pdf_to_json_test_Latn.NHN_Serif_16.py" > "data/multilingual/Latn.NHN/Serif_16/pdf_to_json_test_Latn.NHN_Serif_16.json" 2>&1
Latn.NHN_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.NHN/Serif_8/pdf_to_json_test_Latn.NHN_Serif_8.py" > "data/multilingual/Latn.NHN/Serif_8/pdf_to_json_test_Latn.NHN_Serif_8.json" 2>&1
Latn.NHN_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.NHN/Sun-ExtA_12/pdf_to_json_test_Latn.NHN_Sun-ExtA_12.py" > "data/multilingual/Latn.NHN/Sun-ExtA_12/pdf_to_json_test_Latn.NHN_Sun-ExtA_12.json" 2>&1
Latn.NHN_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.NHN/Sun-ExtA_16/pdf_to_json_test_Latn.NHN_Sun-ExtA_16.py" > "data/multilingual/Latn.NHN/Sun-ExtA_16/pdf_to_json_test_Latn.NHN_Sun-ExtA_16.json" 2>&1
Latn.NHN_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.NHN/Sun-ExtA_8/pdf_to_json_test_Latn.NHN_Sun-ExtA_8.py" > "data/multilingual/Latn.NHN/Sun-ExtA_8/pdf_to_json_test_Latn.NHN_Sun-ExtA_8.json" 2>&1


Latn.NHN_all : Latn.NHN_Mono_12 Latn.NHN_Mono_16 Latn.NHN_Mono_8 Latn.NHN_Sans_12 Latn.NHN_Sans_16 Latn.NHN_Sans_8 Latn.NHN_Serif_12 Latn.NHN_Serif_16 Latn.NHN_Serif_8 Latn.NHN_Sun-ExtA_12 Latn.NHN_Sun-ExtA_16 Latn.NHN_Sun-ExtA_8
