PYTHON=python3


Latn.FUR_Mono_12:
	-$(PYTHON) data/multilingual/Latn.FUR/Mono_12/pdf_to_json_test_Latn.FUR_Mono_12.py > data/multilingual/Latn.FUR/Mono_12/pdf_to_json_test_Latn.FUR_Mono_12.json 2>&1
Latn.FUR_Mono_16:
	-$(PYTHON) data/multilingual/Latn.FUR/Mono_16/pdf_to_json_test_Latn.FUR_Mono_16.py > data/multilingual/Latn.FUR/Mono_16/pdf_to_json_test_Latn.FUR_Mono_16.json 2>&1
Latn.FUR_Mono_8:
	-$(PYTHON) data/multilingual/Latn.FUR/Mono_8/pdf_to_json_test_Latn.FUR_Mono_8.py > data/multilingual/Latn.FUR/Mono_8/pdf_to_json_test_Latn.FUR_Mono_8.json 2>&1
Latn.FUR_Sans_12:
	-$(PYTHON) data/multilingual/Latn.FUR/Sans_12/pdf_to_json_test_Latn.FUR_Sans_12.py > data/multilingual/Latn.FUR/Sans_12/pdf_to_json_test_Latn.FUR_Sans_12.json 2>&1
Latn.FUR_Sans_16:
	-$(PYTHON) data/multilingual/Latn.FUR/Sans_16/pdf_to_json_test_Latn.FUR_Sans_16.py > data/multilingual/Latn.FUR/Sans_16/pdf_to_json_test_Latn.FUR_Sans_16.json 2>&1
Latn.FUR_Sans_8:
	-$(PYTHON) data/multilingual/Latn.FUR/Sans_8/pdf_to_json_test_Latn.FUR_Sans_8.py > data/multilingual/Latn.FUR/Sans_8/pdf_to_json_test_Latn.FUR_Sans_8.json 2>&1
Latn.FUR_Serif_12:
	-$(PYTHON) data/multilingual/Latn.FUR/Serif_12/pdf_to_json_test_Latn.FUR_Serif_12.py > data/multilingual/Latn.FUR/Serif_12/pdf_to_json_test_Latn.FUR_Serif_12.json 2>&1
Latn.FUR_Serif_16:
	-$(PYTHON) data/multilingual/Latn.FUR/Serif_16/pdf_to_json_test_Latn.FUR_Serif_16.py > data/multilingual/Latn.FUR/Serif_16/pdf_to_json_test_Latn.FUR_Serif_16.json 2>&1
Latn.FUR_Serif_8:
	-$(PYTHON) data/multilingual/Latn.FUR/Serif_8/pdf_to_json_test_Latn.FUR_Serif_8.py > data/multilingual/Latn.FUR/Serif_8/pdf_to_json_test_Latn.FUR_Serif_8.json 2>&1
Latn.FUR_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.FUR/Sun-ExtA_12/pdf_to_json_test_Latn.FUR_Sun-ExtA_12.py > data/multilingual/Latn.FUR/Sun-ExtA_12/pdf_to_json_test_Latn.FUR_Sun-ExtA_12.json 2>&1
Latn.FUR_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.FUR/Sun-ExtA_16/pdf_to_json_test_Latn.FUR_Sun-ExtA_16.py > data/multilingual/Latn.FUR/Sun-ExtA_16/pdf_to_json_test_Latn.FUR_Sun-ExtA_16.json 2>&1
Latn.FUR_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.FUR/Sun-ExtA_8/pdf_to_json_test_Latn.FUR_Sun-ExtA_8.py > data/multilingual/Latn.FUR/Sun-ExtA_8/pdf_to_json_test_Latn.FUR_Sun-ExtA_8.json 2>&1


Latn.FUR_all : Latn.FUR_Mono_12 Latn.FUR_Mono_16 Latn.FUR_Mono_8 Latn.FUR_Sans_12 Latn.FUR_Sans_16 Latn.FUR_Sans_8 Latn.FUR_Serif_12 Latn.FUR_Serif_16 Latn.FUR_Serif_8 Latn.FUR_Sun-ExtA_12 Latn.FUR_Sun-ExtA_16 Latn.FUR_Sun-ExtA_8
