PYTHON=python3


Latn.EPO_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.EPO/Mono_12/pdf_to_json_test_Latn.EPO_Mono_12.py" > "data/multilingual/Latn.EPO/Mono_12/pdf_to_json_test_Latn.EPO_Mono_12.json" 2>&1
Latn.EPO_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.EPO/Mono_16/pdf_to_json_test_Latn.EPO_Mono_16.py" > "data/multilingual/Latn.EPO/Mono_16/pdf_to_json_test_Latn.EPO_Mono_16.json" 2>&1
Latn.EPO_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.EPO/Mono_8/pdf_to_json_test_Latn.EPO_Mono_8.py" > "data/multilingual/Latn.EPO/Mono_8/pdf_to_json_test_Latn.EPO_Mono_8.json" 2>&1
Latn.EPO_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.EPO/Sans_12/pdf_to_json_test_Latn.EPO_Sans_12.py" > "data/multilingual/Latn.EPO/Sans_12/pdf_to_json_test_Latn.EPO_Sans_12.json" 2>&1
Latn.EPO_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.EPO/Sans_16/pdf_to_json_test_Latn.EPO_Sans_16.py" > "data/multilingual/Latn.EPO/Sans_16/pdf_to_json_test_Latn.EPO_Sans_16.json" 2>&1
Latn.EPO_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.EPO/Sans_8/pdf_to_json_test_Latn.EPO_Sans_8.py" > "data/multilingual/Latn.EPO/Sans_8/pdf_to_json_test_Latn.EPO_Sans_8.json" 2>&1
Latn.EPO_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.EPO/Serif_12/pdf_to_json_test_Latn.EPO_Serif_12.py" > "data/multilingual/Latn.EPO/Serif_12/pdf_to_json_test_Latn.EPO_Serif_12.json" 2>&1
Latn.EPO_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.EPO/Serif_16/pdf_to_json_test_Latn.EPO_Serif_16.py" > "data/multilingual/Latn.EPO/Serif_16/pdf_to_json_test_Latn.EPO_Serif_16.json" 2>&1
Latn.EPO_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.EPO/Serif_8/pdf_to_json_test_Latn.EPO_Serif_8.py" > "data/multilingual/Latn.EPO/Serif_8/pdf_to_json_test_Latn.EPO_Serif_8.json" 2>&1
Latn.EPO_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.EPO/Sun-ExtA_12/pdf_to_json_test_Latn.EPO_Sun-ExtA_12.py" > "data/multilingual/Latn.EPO/Sun-ExtA_12/pdf_to_json_test_Latn.EPO_Sun-ExtA_12.json" 2>&1
Latn.EPO_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.EPO/Sun-ExtA_16/pdf_to_json_test_Latn.EPO_Sun-ExtA_16.py" > "data/multilingual/Latn.EPO/Sun-ExtA_16/pdf_to_json_test_Latn.EPO_Sun-ExtA_16.json" 2>&1
Latn.EPO_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.EPO/Sun-ExtA_8/pdf_to_json_test_Latn.EPO_Sun-ExtA_8.py" > "data/multilingual/Latn.EPO/Sun-ExtA_8/pdf_to_json_test_Latn.EPO_Sun-ExtA_8.json" 2>&1


Latn.EPO_all : Latn.EPO_Mono_12 Latn.EPO_Mono_16 Latn.EPO_Mono_8 Latn.EPO_Sans_12 Latn.EPO_Sans_16 Latn.EPO_Sans_8 Latn.EPO_Serif_12 Latn.EPO_Serif_16 Latn.EPO_Serif_8 Latn.EPO_Sun-ExtA_12 Latn.EPO_Sun-ExtA_16 Latn.EPO_Sun-ExtA_8
