PYTHON=python3


Latn.AME_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.AME/Mono_12/pdf_to_json_test_Latn.AME_Mono_12.py" > "data/multilingual/Latn.AME/Mono_12/pdf_to_json_test_Latn.AME_Mono_12.json" 2>&1
Latn.AME_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.AME/Mono_16/pdf_to_json_test_Latn.AME_Mono_16.py" > "data/multilingual/Latn.AME/Mono_16/pdf_to_json_test_Latn.AME_Mono_16.json" 2>&1
Latn.AME_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.AME/Mono_8/pdf_to_json_test_Latn.AME_Mono_8.py" > "data/multilingual/Latn.AME/Mono_8/pdf_to_json_test_Latn.AME_Mono_8.json" 2>&1
Latn.AME_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.AME/Sans_12/pdf_to_json_test_Latn.AME_Sans_12.py" > "data/multilingual/Latn.AME/Sans_12/pdf_to_json_test_Latn.AME_Sans_12.json" 2>&1
Latn.AME_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.AME/Sans_16/pdf_to_json_test_Latn.AME_Sans_16.py" > "data/multilingual/Latn.AME/Sans_16/pdf_to_json_test_Latn.AME_Sans_16.json" 2>&1
Latn.AME_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.AME/Sans_8/pdf_to_json_test_Latn.AME_Sans_8.py" > "data/multilingual/Latn.AME/Sans_8/pdf_to_json_test_Latn.AME_Sans_8.json" 2>&1
Latn.AME_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.AME/Serif_12/pdf_to_json_test_Latn.AME_Serif_12.py" > "data/multilingual/Latn.AME/Serif_12/pdf_to_json_test_Latn.AME_Serif_12.json" 2>&1
Latn.AME_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.AME/Serif_16/pdf_to_json_test_Latn.AME_Serif_16.py" > "data/multilingual/Latn.AME/Serif_16/pdf_to_json_test_Latn.AME_Serif_16.json" 2>&1
Latn.AME_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.AME/Serif_8/pdf_to_json_test_Latn.AME_Serif_8.py" > "data/multilingual/Latn.AME/Serif_8/pdf_to_json_test_Latn.AME_Serif_8.json" 2>&1
Latn.AME_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.AME/Sun-ExtA_12/pdf_to_json_test_Latn.AME_Sun-ExtA_12.py" > "data/multilingual/Latn.AME/Sun-ExtA_12/pdf_to_json_test_Latn.AME_Sun-ExtA_12.json" 2>&1
Latn.AME_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.AME/Sun-ExtA_16/pdf_to_json_test_Latn.AME_Sun-ExtA_16.py" > "data/multilingual/Latn.AME/Sun-ExtA_16/pdf_to_json_test_Latn.AME_Sun-ExtA_16.json" 2>&1
Latn.AME_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.AME/Sun-ExtA_8/pdf_to_json_test_Latn.AME_Sun-ExtA_8.py" > "data/multilingual/Latn.AME/Sun-ExtA_8/pdf_to_json_test_Latn.AME_Sun-ExtA_8.json" 2>&1


Latn.AME_all : Latn.AME_Mono_12 Latn.AME_Mono_16 Latn.AME_Mono_8 Latn.AME_Sans_12 Latn.AME_Sans_16 Latn.AME_Sans_8 Latn.AME_Serif_12 Latn.AME_Serif_16 Latn.AME_Serif_8 Latn.AME_Sun-ExtA_12 Latn.AME_Sun-ExtA_16 Latn.AME_Sun-ExtA_8
