PYTHON=python3


Latn.ACE_Mono_12:
	-$(PYTHON) data/multilingual/Latn.ACE/Mono_12/pdf_to_json_test_Latn.ACE_Mono_12.py > data/multilingual/Latn.ACE/Mono_12/pdf_to_json_test_Latn.ACE_Mono_12.json 2>&1
Latn.ACE_Mono_16:
	-$(PYTHON) data/multilingual/Latn.ACE/Mono_16/pdf_to_json_test_Latn.ACE_Mono_16.py > data/multilingual/Latn.ACE/Mono_16/pdf_to_json_test_Latn.ACE_Mono_16.json 2>&1
Latn.ACE_Mono_8:
	-$(PYTHON) data/multilingual/Latn.ACE/Mono_8/pdf_to_json_test_Latn.ACE_Mono_8.py > data/multilingual/Latn.ACE/Mono_8/pdf_to_json_test_Latn.ACE_Mono_8.json 2>&1
Latn.ACE_Sans_12:
	-$(PYTHON) data/multilingual/Latn.ACE/Sans_12/pdf_to_json_test_Latn.ACE_Sans_12.py > data/multilingual/Latn.ACE/Sans_12/pdf_to_json_test_Latn.ACE_Sans_12.json 2>&1
Latn.ACE_Sans_16:
	-$(PYTHON) data/multilingual/Latn.ACE/Sans_16/pdf_to_json_test_Latn.ACE_Sans_16.py > data/multilingual/Latn.ACE/Sans_16/pdf_to_json_test_Latn.ACE_Sans_16.json 2>&1
Latn.ACE_Sans_8:
	-$(PYTHON) data/multilingual/Latn.ACE/Sans_8/pdf_to_json_test_Latn.ACE_Sans_8.py > data/multilingual/Latn.ACE/Sans_8/pdf_to_json_test_Latn.ACE_Sans_8.json 2>&1
Latn.ACE_Serif_12:
	-$(PYTHON) data/multilingual/Latn.ACE/Serif_12/pdf_to_json_test_Latn.ACE_Serif_12.py > data/multilingual/Latn.ACE/Serif_12/pdf_to_json_test_Latn.ACE_Serif_12.json 2>&1
Latn.ACE_Serif_16:
	-$(PYTHON) data/multilingual/Latn.ACE/Serif_16/pdf_to_json_test_Latn.ACE_Serif_16.py > data/multilingual/Latn.ACE/Serif_16/pdf_to_json_test_Latn.ACE_Serif_16.json 2>&1
Latn.ACE_Serif_8:
	-$(PYTHON) data/multilingual/Latn.ACE/Serif_8/pdf_to_json_test_Latn.ACE_Serif_8.py > data/multilingual/Latn.ACE/Serif_8/pdf_to_json_test_Latn.ACE_Serif_8.json 2>&1
Latn.ACE_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.ACE/Sun-ExtA_12/pdf_to_json_test_Latn.ACE_Sun-ExtA_12.py > data/multilingual/Latn.ACE/Sun-ExtA_12/pdf_to_json_test_Latn.ACE_Sun-ExtA_12.json 2>&1
Latn.ACE_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.ACE/Sun-ExtA_16/pdf_to_json_test_Latn.ACE_Sun-ExtA_16.py > data/multilingual/Latn.ACE/Sun-ExtA_16/pdf_to_json_test_Latn.ACE_Sun-ExtA_16.json 2>&1
Latn.ACE_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.ACE/Sun-ExtA_8/pdf_to_json_test_Latn.ACE_Sun-ExtA_8.py > data/multilingual/Latn.ACE/Sun-ExtA_8/pdf_to_json_test_Latn.ACE_Sun-ExtA_8.json 2>&1


Latn.ACE_all : Latn.ACE_Mono_12 Latn.ACE_Mono_16 Latn.ACE_Mono_8 Latn.ACE_Sans_12 Latn.ACE_Sans_16 Latn.ACE_Sans_8 Latn.ACE_Serif_12 Latn.ACE_Serif_16 Latn.ACE_Serif_8 Latn.ACE_Sun-ExtA_12 Latn.ACE_Sun-ExtA_16 Latn.ACE_Sun-ExtA_8
