PYTHON=python3


Latn.TPI_Mono_12:
	-$(PYTHON) data/multilingual/Latn.TPI/Mono_12/pdf_to_json_test_Latn.TPI_Mono_12.py > data/multilingual/Latn.TPI/Mono_12/pdf_to_json_test_Latn.TPI_Mono_12.json 2>&1
Latn.TPI_Mono_16:
	-$(PYTHON) data/multilingual/Latn.TPI/Mono_16/pdf_to_json_test_Latn.TPI_Mono_16.py > data/multilingual/Latn.TPI/Mono_16/pdf_to_json_test_Latn.TPI_Mono_16.json 2>&1
Latn.TPI_Mono_8:
	-$(PYTHON) data/multilingual/Latn.TPI/Mono_8/pdf_to_json_test_Latn.TPI_Mono_8.py > data/multilingual/Latn.TPI/Mono_8/pdf_to_json_test_Latn.TPI_Mono_8.json 2>&1
Latn.TPI_Sans_12:
	-$(PYTHON) data/multilingual/Latn.TPI/Sans_12/pdf_to_json_test_Latn.TPI_Sans_12.py > data/multilingual/Latn.TPI/Sans_12/pdf_to_json_test_Latn.TPI_Sans_12.json 2>&1
Latn.TPI_Sans_16:
	-$(PYTHON) data/multilingual/Latn.TPI/Sans_16/pdf_to_json_test_Latn.TPI_Sans_16.py > data/multilingual/Latn.TPI/Sans_16/pdf_to_json_test_Latn.TPI_Sans_16.json 2>&1
Latn.TPI_Sans_8:
	-$(PYTHON) data/multilingual/Latn.TPI/Sans_8/pdf_to_json_test_Latn.TPI_Sans_8.py > data/multilingual/Latn.TPI/Sans_8/pdf_to_json_test_Latn.TPI_Sans_8.json 2>&1
Latn.TPI_Serif_12:
	-$(PYTHON) data/multilingual/Latn.TPI/Serif_12/pdf_to_json_test_Latn.TPI_Serif_12.py > data/multilingual/Latn.TPI/Serif_12/pdf_to_json_test_Latn.TPI_Serif_12.json 2>&1
Latn.TPI_Serif_16:
	-$(PYTHON) data/multilingual/Latn.TPI/Serif_16/pdf_to_json_test_Latn.TPI_Serif_16.py > data/multilingual/Latn.TPI/Serif_16/pdf_to_json_test_Latn.TPI_Serif_16.json 2>&1
Latn.TPI_Serif_8:
	-$(PYTHON) data/multilingual/Latn.TPI/Serif_8/pdf_to_json_test_Latn.TPI_Serif_8.py > data/multilingual/Latn.TPI/Serif_8/pdf_to_json_test_Latn.TPI_Serif_8.json 2>&1
Latn.TPI_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.TPI/Sun-ExtA_12/pdf_to_json_test_Latn.TPI_Sun-ExtA_12.py > data/multilingual/Latn.TPI/Sun-ExtA_12/pdf_to_json_test_Latn.TPI_Sun-ExtA_12.json 2>&1
Latn.TPI_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.TPI/Sun-ExtA_16/pdf_to_json_test_Latn.TPI_Sun-ExtA_16.py > data/multilingual/Latn.TPI/Sun-ExtA_16/pdf_to_json_test_Latn.TPI_Sun-ExtA_16.json 2>&1
Latn.TPI_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.TPI/Sun-ExtA_8/pdf_to_json_test_Latn.TPI_Sun-ExtA_8.py > data/multilingual/Latn.TPI/Sun-ExtA_8/pdf_to_json_test_Latn.TPI_Sun-ExtA_8.json 2>&1


Latn.TPI_all : Latn.TPI_Mono_12 Latn.TPI_Mono_16 Latn.TPI_Mono_8 Latn.TPI_Sans_12 Latn.TPI_Sans_16 Latn.TPI_Sans_8 Latn.TPI_Serif_12 Latn.TPI_Serif_16 Latn.TPI_Serif_8 Latn.TPI_Sun-ExtA_12 Latn.TPI_Sun-ExtA_16 Latn.TPI_Sun-ExtA_8
