PYTHON=python3


Latn.HMS_Mono_12:
	-$(PYTHON) data/multilingual/Latn.HMS/Mono_12/pdf_to_json_test_Latn.HMS_Mono_12.py > data/multilingual/Latn.HMS/Mono_12/pdf_to_json_test_Latn.HMS_Mono_12.json 2>&1
Latn.HMS_Mono_16:
	-$(PYTHON) data/multilingual/Latn.HMS/Mono_16/pdf_to_json_test_Latn.HMS_Mono_16.py > data/multilingual/Latn.HMS/Mono_16/pdf_to_json_test_Latn.HMS_Mono_16.json 2>&1
Latn.HMS_Mono_8:
	-$(PYTHON) data/multilingual/Latn.HMS/Mono_8/pdf_to_json_test_Latn.HMS_Mono_8.py > data/multilingual/Latn.HMS/Mono_8/pdf_to_json_test_Latn.HMS_Mono_8.json 2>&1
Latn.HMS_Sans_12:
	-$(PYTHON) data/multilingual/Latn.HMS/Sans_12/pdf_to_json_test_Latn.HMS_Sans_12.py > data/multilingual/Latn.HMS/Sans_12/pdf_to_json_test_Latn.HMS_Sans_12.json 2>&1
Latn.HMS_Sans_16:
	-$(PYTHON) data/multilingual/Latn.HMS/Sans_16/pdf_to_json_test_Latn.HMS_Sans_16.py > data/multilingual/Latn.HMS/Sans_16/pdf_to_json_test_Latn.HMS_Sans_16.json 2>&1
Latn.HMS_Sans_8:
	-$(PYTHON) data/multilingual/Latn.HMS/Sans_8/pdf_to_json_test_Latn.HMS_Sans_8.py > data/multilingual/Latn.HMS/Sans_8/pdf_to_json_test_Latn.HMS_Sans_8.json 2>&1
Latn.HMS_Serif_12:
	-$(PYTHON) data/multilingual/Latn.HMS/Serif_12/pdf_to_json_test_Latn.HMS_Serif_12.py > data/multilingual/Latn.HMS/Serif_12/pdf_to_json_test_Latn.HMS_Serif_12.json 2>&1
Latn.HMS_Serif_16:
	-$(PYTHON) data/multilingual/Latn.HMS/Serif_16/pdf_to_json_test_Latn.HMS_Serif_16.py > data/multilingual/Latn.HMS/Serif_16/pdf_to_json_test_Latn.HMS_Serif_16.json 2>&1
Latn.HMS_Serif_8:
	-$(PYTHON) data/multilingual/Latn.HMS/Serif_8/pdf_to_json_test_Latn.HMS_Serif_8.py > data/multilingual/Latn.HMS/Serif_8/pdf_to_json_test_Latn.HMS_Serif_8.json 2>&1
Latn.HMS_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.HMS/Sun-ExtA_12/pdf_to_json_test_Latn.HMS_Sun-ExtA_12.py > data/multilingual/Latn.HMS/Sun-ExtA_12/pdf_to_json_test_Latn.HMS_Sun-ExtA_12.json 2>&1
Latn.HMS_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.HMS/Sun-ExtA_16/pdf_to_json_test_Latn.HMS_Sun-ExtA_16.py > data/multilingual/Latn.HMS/Sun-ExtA_16/pdf_to_json_test_Latn.HMS_Sun-ExtA_16.json 2>&1
Latn.HMS_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.HMS/Sun-ExtA_8/pdf_to_json_test_Latn.HMS_Sun-ExtA_8.py > data/multilingual/Latn.HMS/Sun-ExtA_8/pdf_to_json_test_Latn.HMS_Sun-ExtA_8.json 2>&1


Latn.HMS_all : Latn.HMS_Mono_12 Latn.HMS_Mono_16 Latn.HMS_Mono_8 Latn.HMS_Sans_12 Latn.HMS_Sans_16 Latn.HMS_Sans_8 Latn.HMS_Serif_12 Latn.HMS_Serif_16 Latn.HMS_Serif_8 Latn.HMS_Sun-ExtA_12 Latn.HMS_Sun-ExtA_16 Latn.HMS_Sun-ExtA_8
