PYTHON=python3


Latn.QUY_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.QUY/Mono_12/pdf_to_json_test_Latn.QUY_Mono_12.py" > "data/multilingual/Latn.QUY/Mono_12/pdf_to_json_test_Latn.QUY_Mono_12.json" 2>&1
Latn.QUY_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.QUY/Mono_16/pdf_to_json_test_Latn.QUY_Mono_16.py" > "data/multilingual/Latn.QUY/Mono_16/pdf_to_json_test_Latn.QUY_Mono_16.json" 2>&1
Latn.QUY_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.QUY/Mono_8/pdf_to_json_test_Latn.QUY_Mono_8.py" > "data/multilingual/Latn.QUY/Mono_8/pdf_to_json_test_Latn.QUY_Mono_8.json" 2>&1
Latn.QUY_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.QUY/Sans_12/pdf_to_json_test_Latn.QUY_Sans_12.py" > "data/multilingual/Latn.QUY/Sans_12/pdf_to_json_test_Latn.QUY_Sans_12.json" 2>&1
Latn.QUY_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.QUY/Sans_16/pdf_to_json_test_Latn.QUY_Sans_16.py" > "data/multilingual/Latn.QUY/Sans_16/pdf_to_json_test_Latn.QUY_Sans_16.json" 2>&1
Latn.QUY_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.QUY/Sans_8/pdf_to_json_test_Latn.QUY_Sans_8.py" > "data/multilingual/Latn.QUY/Sans_8/pdf_to_json_test_Latn.QUY_Sans_8.json" 2>&1
Latn.QUY_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.QUY/Serif_12/pdf_to_json_test_Latn.QUY_Serif_12.py" > "data/multilingual/Latn.QUY/Serif_12/pdf_to_json_test_Latn.QUY_Serif_12.json" 2>&1
Latn.QUY_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.QUY/Serif_16/pdf_to_json_test_Latn.QUY_Serif_16.py" > "data/multilingual/Latn.QUY/Serif_16/pdf_to_json_test_Latn.QUY_Serif_16.json" 2>&1
Latn.QUY_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.QUY/Serif_8/pdf_to_json_test_Latn.QUY_Serif_8.py" > "data/multilingual/Latn.QUY/Serif_8/pdf_to_json_test_Latn.QUY_Serif_8.json" 2>&1
Latn.QUY_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.QUY/Sun-ExtA_12/pdf_to_json_test_Latn.QUY_Sun-ExtA_12.py" > "data/multilingual/Latn.QUY/Sun-ExtA_12/pdf_to_json_test_Latn.QUY_Sun-ExtA_12.json" 2>&1
Latn.QUY_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.QUY/Sun-ExtA_16/pdf_to_json_test_Latn.QUY_Sun-ExtA_16.py" > "data/multilingual/Latn.QUY/Sun-ExtA_16/pdf_to_json_test_Latn.QUY_Sun-ExtA_16.json" 2>&1
Latn.QUY_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.QUY/Sun-ExtA_8/pdf_to_json_test_Latn.QUY_Sun-ExtA_8.py" > "data/multilingual/Latn.QUY/Sun-ExtA_8/pdf_to_json_test_Latn.QUY_Sun-ExtA_8.json" 2>&1


Latn.QUY_all : Latn.QUY_Mono_12 Latn.QUY_Mono_16 Latn.QUY_Mono_8 Latn.QUY_Sans_12 Latn.QUY_Sans_16 Latn.QUY_Sans_8 Latn.QUY_Serif_12 Latn.QUY_Serif_16 Latn.QUY_Serif_8 Latn.QUY_Sun-ExtA_12 Latn.QUY_Sun-ExtA_16 Latn.QUY_Sun-ExtA_8
