PYTHON=python3


Latn.SHP_Mono_12:
	-$(PYTHON) data/multilingual/Latn.SHP/Mono_12/pdf_to_json_test_Latn.SHP_Mono_12.py > data/multilingual/Latn.SHP/Mono_12/pdf_to_json_test_Latn.SHP_Mono_12.json 2>&1
Latn.SHP_Mono_16:
	-$(PYTHON) data/multilingual/Latn.SHP/Mono_16/pdf_to_json_test_Latn.SHP_Mono_16.py > data/multilingual/Latn.SHP/Mono_16/pdf_to_json_test_Latn.SHP_Mono_16.json 2>&1
Latn.SHP_Mono_8:
	-$(PYTHON) data/multilingual/Latn.SHP/Mono_8/pdf_to_json_test_Latn.SHP_Mono_8.py > data/multilingual/Latn.SHP/Mono_8/pdf_to_json_test_Latn.SHP_Mono_8.json 2>&1
Latn.SHP_Sans_12:
	-$(PYTHON) data/multilingual/Latn.SHP/Sans_12/pdf_to_json_test_Latn.SHP_Sans_12.py > data/multilingual/Latn.SHP/Sans_12/pdf_to_json_test_Latn.SHP_Sans_12.json 2>&1
Latn.SHP_Sans_16:
	-$(PYTHON) data/multilingual/Latn.SHP/Sans_16/pdf_to_json_test_Latn.SHP_Sans_16.py > data/multilingual/Latn.SHP/Sans_16/pdf_to_json_test_Latn.SHP_Sans_16.json 2>&1
Latn.SHP_Sans_8:
	-$(PYTHON) data/multilingual/Latn.SHP/Sans_8/pdf_to_json_test_Latn.SHP_Sans_8.py > data/multilingual/Latn.SHP/Sans_8/pdf_to_json_test_Latn.SHP_Sans_8.json 2>&1
Latn.SHP_Serif_12:
	-$(PYTHON) data/multilingual/Latn.SHP/Serif_12/pdf_to_json_test_Latn.SHP_Serif_12.py > data/multilingual/Latn.SHP/Serif_12/pdf_to_json_test_Latn.SHP_Serif_12.json 2>&1
Latn.SHP_Serif_16:
	-$(PYTHON) data/multilingual/Latn.SHP/Serif_16/pdf_to_json_test_Latn.SHP_Serif_16.py > data/multilingual/Latn.SHP/Serif_16/pdf_to_json_test_Latn.SHP_Serif_16.json 2>&1
Latn.SHP_Serif_8:
	-$(PYTHON) data/multilingual/Latn.SHP/Serif_8/pdf_to_json_test_Latn.SHP_Serif_8.py > data/multilingual/Latn.SHP/Serif_8/pdf_to_json_test_Latn.SHP_Serif_8.json 2>&1
Latn.SHP_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.SHP/Sun-ExtA_12/pdf_to_json_test_Latn.SHP_Sun-ExtA_12.py > data/multilingual/Latn.SHP/Sun-ExtA_12/pdf_to_json_test_Latn.SHP_Sun-ExtA_12.json 2>&1
Latn.SHP_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.SHP/Sun-ExtA_16/pdf_to_json_test_Latn.SHP_Sun-ExtA_16.py > data/multilingual/Latn.SHP/Sun-ExtA_16/pdf_to_json_test_Latn.SHP_Sun-ExtA_16.json 2>&1
Latn.SHP_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.SHP/Sun-ExtA_8/pdf_to_json_test_Latn.SHP_Sun-ExtA_8.py > data/multilingual/Latn.SHP/Sun-ExtA_8/pdf_to_json_test_Latn.SHP_Sun-ExtA_8.json 2>&1


Latn.SHP_all : Latn.SHP_Mono_12 Latn.SHP_Mono_16 Latn.SHP_Mono_8 Latn.SHP_Sans_12 Latn.SHP_Sans_16 Latn.SHP_Sans_8 Latn.SHP_Serif_12 Latn.SHP_Serif_16 Latn.SHP_Serif_8 Latn.SHP_Sun-ExtA_12 Latn.SHP_Sun-ExtA_16 Latn.SHP_Sun-ExtA_8
