PYTHON=python3


Latn.WLN_Mono_12:
	-$(PYTHON) data/multilingual/Latn.WLN/Mono_12/pdf_to_json_test_Latn.WLN_Mono_12.py > data/multilingual/Latn.WLN/Mono_12/pdf_to_json_test_Latn.WLN_Mono_12.json 2>&1
Latn.WLN_Mono_16:
	-$(PYTHON) data/multilingual/Latn.WLN/Mono_16/pdf_to_json_test_Latn.WLN_Mono_16.py > data/multilingual/Latn.WLN/Mono_16/pdf_to_json_test_Latn.WLN_Mono_16.json 2>&1
Latn.WLN_Mono_8:
	-$(PYTHON) data/multilingual/Latn.WLN/Mono_8/pdf_to_json_test_Latn.WLN_Mono_8.py > data/multilingual/Latn.WLN/Mono_8/pdf_to_json_test_Latn.WLN_Mono_8.json 2>&1
Latn.WLN_Sans_12:
	-$(PYTHON) data/multilingual/Latn.WLN/Sans_12/pdf_to_json_test_Latn.WLN_Sans_12.py > data/multilingual/Latn.WLN/Sans_12/pdf_to_json_test_Latn.WLN_Sans_12.json 2>&1
Latn.WLN_Sans_16:
	-$(PYTHON) data/multilingual/Latn.WLN/Sans_16/pdf_to_json_test_Latn.WLN_Sans_16.py > data/multilingual/Latn.WLN/Sans_16/pdf_to_json_test_Latn.WLN_Sans_16.json 2>&1
Latn.WLN_Sans_8:
	-$(PYTHON) data/multilingual/Latn.WLN/Sans_8/pdf_to_json_test_Latn.WLN_Sans_8.py > data/multilingual/Latn.WLN/Sans_8/pdf_to_json_test_Latn.WLN_Sans_8.json 2>&1
Latn.WLN_Serif_12:
	-$(PYTHON) data/multilingual/Latn.WLN/Serif_12/pdf_to_json_test_Latn.WLN_Serif_12.py > data/multilingual/Latn.WLN/Serif_12/pdf_to_json_test_Latn.WLN_Serif_12.json 2>&1
Latn.WLN_Serif_16:
	-$(PYTHON) data/multilingual/Latn.WLN/Serif_16/pdf_to_json_test_Latn.WLN_Serif_16.py > data/multilingual/Latn.WLN/Serif_16/pdf_to_json_test_Latn.WLN_Serif_16.json 2>&1
Latn.WLN_Serif_8:
	-$(PYTHON) data/multilingual/Latn.WLN/Serif_8/pdf_to_json_test_Latn.WLN_Serif_8.py > data/multilingual/Latn.WLN/Serif_8/pdf_to_json_test_Latn.WLN_Serif_8.json 2>&1
Latn.WLN_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.WLN/Sun-ExtA_12/pdf_to_json_test_Latn.WLN_Sun-ExtA_12.py > data/multilingual/Latn.WLN/Sun-ExtA_12/pdf_to_json_test_Latn.WLN_Sun-ExtA_12.json 2>&1
Latn.WLN_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.WLN/Sun-ExtA_16/pdf_to_json_test_Latn.WLN_Sun-ExtA_16.py > data/multilingual/Latn.WLN/Sun-ExtA_16/pdf_to_json_test_Latn.WLN_Sun-ExtA_16.json 2>&1
Latn.WLN_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.WLN/Sun-ExtA_8/pdf_to_json_test_Latn.WLN_Sun-ExtA_8.py > data/multilingual/Latn.WLN/Sun-ExtA_8/pdf_to_json_test_Latn.WLN_Sun-ExtA_8.json 2>&1


Latn.WLN_all : Latn.WLN_Mono_12 Latn.WLN_Mono_16 Latn.WLN_Mono_8 Latn.WLN_Sans_12 Latn.WLN_Sans_16 Latn.WLN_Sans_8 Latn.WLN_Serif_12 Latn.WLN_Serif_16 Latn.WLN_Serif_8 Latn.WLN_Sun-ExtA_12 Latn.WLN_Sun-ExtA_16 Latn.WLN_Sun-ExtA_8
