PYTHON=python3


Knda.KAN_Mono_12:
	-$(PYTHON) data/multilingual/Knda.KAN/Mono_12/pdf_to_json_test_Knda.KAN_Mono_12.py > data/multilingual/Knda.KAN/Mono_12/pdf_to_json_test_Knda.KAN_Mono_12.json 2>&1
Knda.KAN_Mono_16:
	-$(PYTHON) data/multilingual/Knda.KAN/Mono_16/pdf_to_json_test_Knda.KAN_Mono_16.py > data/multilingual/Knda.KAN/Mono_16/pdf_to_json_test_Knda.KAN_Mono_16.json 2>&1
Knda.KAN_Mono_8:
	-$(PYTHON) data/multilingual/Knda.KAN/Mono_8/pdf_to_json_test_Knda.KAN_Mono_8.py > data/multilingual/Knda.KAN/Mono_8/pdf_to_json_test_Knda.KAN_Mono_8.json 2>&1
Knda.KAN_Sans_12:
	-$(PYTHON) data/multilingual/Knda.KAN/Sans_12/pdf_to_json_test_Knda.KAN_Sans_12.py > data/multilingual/Knda.KAN/Sans_12/pdf_to_json_test_Knda.KAN_Sans_12.json 2>&1
Knda.KAN_Sans_16:
	-$(PYTHON) data/multilingual/Knda.KAN/Sans_16/pdf_to_json_test_Knda.KAN_Sans_16.py > data/multilingual/Knda.KAN/Sans_16/pdf_to_json_test_Knda.KAN_Sans_16.json 2>&1
Knda.KAN_Sans_8:
	-$(PYTHON) data/multilingual/Knda.KAN/Sans_8/pdf_to_json_test_Knda.KAN_Sans_8.py > data/multilingual/Knda.KAN/Sans_8/pdf_to_json_test_Knda.KAN_Sans_8.json 2>&1
Knda.KAN_Serif_12:
	-$(PYTHON) data/multilingual/Knda.KAN/Serif_12/pdf_to_json_test_Knda.KAN_Serif_12.py > data/multilingual/Knda.KAN/Serif_12/pdf_to_json_test_Knda.KAN_Serif_12.json 2>&1
Knda.KAN_Serif_16:
	-$(PYTHON) data/multilingual/Knda.KAN/Serif_16/pdf_to_json_test_Knda.KAN_Serif_16.py > data/multilingual/Knda.KAN/Serif_16/pdf_to_json_test_Knda.KAN_Serif_16.json 2>&1
Knda.KAN_Serif_8:
	-$(PYTHON) data/multilingual/Knda.KAN/Serif_8/pdf_to_json_test_Knda.KAN_Serif_8.py > data/multilingual/Knda.KAN/Serif_8/pdf_to_json_test_Knda.KAN_Serif_8.json 2>&1
Knda.KAN_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Knda.KAN/Sun-ExtA_12/pdf_to_json_test_Knda.KAN_Sun-ExtA_12.py > data/multilingual/Knda.KAN/Sun-ExtA_12/pdf_to_json_test_Knda.KAN_Sun-ExtA_12.json 2>&1
Knda.KAN_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Knda.KAN/Sun-ExtA_16/pdf_to_json_test_Knda.KAN_Sun-ExtA_16.py > data/multilingual/Knda.KAN/Sun-ExtA_16/pdf_to_json_test_Knda.KAN_Sun-ExtA_16.json 2>&1
Knda.KAN_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Knda.KAN/Sun-ExtA_8/pdf_to_json_test_Knda.KAN_Sun-ExtA_8.py > data/multilingual/Knda.KAN/Sun-ExtA_8/pdf_to_json_test_Knda.KAN_Sun-ExtA_8.json 2>&1


Knda.KAN_all : Knda.KAN_Mono_12 Knda.KAN_Mono_16 Knda.KAN_Mono_8 Knda.KAN_Sans_12 Knda.KAN_Sans_16 Knda.KAN_Sans_8 Knda.KAN_Serif_12 Knda.KAN_Serif_16 Knda.KAN_Serif_8 Knda.KAN_Sun-ExtA_12 Knda.KAN_Sun-ExtA_16 Knda.KAN_Sun-ExtA_8
