PYTHON=python3


Latn.AUC_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.AUC/Mono_12/pdf_to_json_test_Latn.AUC_Mono_12.py" > "data/multilingual/Latn.AUC/Mono_12/pdf_to_json_test_Latn.AUC_Mono_12.json" 2>&1
Latn.AUC_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.AUC/Mono_16/pdf_to_json_test_Latn.AUC_Mono_16.py" > "data/multilingual/Latn.AUC/Mono_16/pdf_to_json_test_Latn.AUC_Mono_16.json" 2>&1
Latn.AUC_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.AUC/Mono_8/pdf_to_json_test_Latn.AUC_Mono_8.py" > "data/multilingual/Latn.AUC/Mono_8/pdf_to_json_test_Latn.AUC_Mono_8.json" 2>&1
Latn.AUC_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.AUC/Sans_12/pdf_to_json_test_Latn.AUC_Sans_12.py" > "data/multilingual/Latn.AUC/Sans_12/pdf_to_json_test_Latn.AUC_Sans_12.json" 2>&1
Latn.AUC_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.AUC/Sans_16/pdf_to_json_test_Latn.AUC_Sans_16.py" > "data/multilingual/Latn.AUC/Sans_16/pdf_to_json_test_Latn.AUC_Sans_16.json" 2>&1
Latn.AUC_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.AUC/Sans_8/pdf_to_json_test_Latn.AUC_Sans_8.py" > "data/multilingual/Latn.AUC/Sans_8/pdf_to_json_test_Latn.AUC_Sans_8.json" 2>&1
Latn.AUC_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.AUC/Serif_12/pdf_to_json_test_Latn.AUC_Serif_12.py" > "data/multilingual/Latn.AUC/Serif_12/pdf_to_json_test_Latn.AUC_Serif_12.json" 2>&1
Latn.AUC_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.AUC/Serif_16/pdf_to_json_test_Latn.AUC_Serif_16.py" > "data/multilingual/Latn.AUC/Serif_16/pdf_to_json_test_Latn.AUC_Serif_16.json" 2>&1
Latn.AUC_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.AUC/Serif_8/pdf_to_json_test_Latn.AUC_Serif_8.py" > "data/multilingual/Latn.AUC/Serif_8/pdf_to_json_test_Latn.AUC_Serif_8.json" 2>&1
Latn.AUC_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.AUC/Sun-ExtA_12/pdf_to_json_test_Latn.AUC_Sun-ExtA_12.py" > "data/multilingual/Latn.AUC/Sun-ExtA_12/pdf_to_json_test_Latn.AUC_Sun-ExtA_12.json" 2>&1
Latn.AUC_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.AUC/Sun-ExtA_16/pdf_to_json_test_Latn.AUC_Sun-ExtA_16.py" > "data/multilingual/Latn.AUC/Sun-ExtA_16/pdf_to_json_test_Latn.AUC_Sun-ExtA_16.json" 2>&1
Latn.AUC_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.AUC/Sun-ExtA_8/pdf_to_json_test_Latn.AUC_Sun-ExtA_8.py" > "data/multilingual/Latn.AUC/Sun-ExtA_8/pdf_to_json_test_Latn.AUC_Sun-ExtA_8.json" 2>&1


Latn.AUC_all : Latn.AUC_Mono_12 Latn.AUC_Mono_16 Latn.AUC_Mono_8 Latn.AUC_Sans_12 Latn.AUC_Sans_16 Latn.AUC_Sans_8 Latn.AUC_Serif_12 Latn.AUC_Serif_16 Latn.AUC_Serif_8 Latn.AUC_Sun-ExtA_12 Latn.AUC_Sun-ExtA_16 Latn.AUC_Sun-ExtA_8
