PYTHON=python3


Latn.NZI_Mono_12:
	-$(PYTHON) data/multilingual/Latn.NZI/Mono_12/pdf_to_json_test_Latn.NZI_Mono_12.py > data/multilingual/Latn.NZI/Mono_12/pdf_to_json_test_Latn.NZI_Mono_12.json 2>&1
Latn.NZI_Mono_16:
	-$(PYTHON) data/multilingual/Latn.NZI/Mono_16/pdf_to_json_test_Latn.NZI_Mono_16.py > data/multilingual/Latn.NZI/Mono_16/pdf_to_json_test_Latn.NZI_Mono_16.json 2>&1
Latn.NZI_Mono_8:
	-$(PYTHON) data/multilingual/Latn.NZI/Mono_8/pdf_to_json_test_Latn.NZI_Mono_8.py > data/multilingual/Latn.NZI/Mono_8/pdf_to_json_test_Latn.NZI_Mono_8.json 2>&1
Latn.NZI_Sans_12:
	-$(PYTHON) data/multilingual/Latn.NZI/Sans_12/pdf_to_json_test_Latn.NZI_Sans_12.py > data/multilingual/Latn.NZI/Sans_12/pdf_to_json_test_Latn.NZI_Sans_12.json 2>&1
Latn.NZI_Sans_16:
	-$(PYTHON) data/multilingual/Latn.NZI/Sans_16/pdf_to_json_test_Latn.NZI_Sans_16.py > data/multilingual/Latn.NZI/Sans_16/pdf_to_json_test_Latn.NZI_Sans_16.json 2>&1
Latn.NZI_Sans_8:
	-$(PYTHON) data/multilingual/Latn.NZI/Sans_8/pdf_to_json_test_Latn.NZI_Sans_8.py > data/multilingual/Latn.NZI/Sans_8/pdf_to_json_test_Latn.NZI_Sans_8.json 2>&1
Latn.NZI_Serif_12:
	-$(PYTHON) data/multilingual/Latn.NZI/Serif_12/pdf_to_json_test_Latn.NZI_Serif_12.py > data/multilingual/Latn.NZI/Serif_12/pdf_to_json_test_Latn.NZI_Serif_12.json 2>&1
Latn.NZI_Serif_16:
	-$(PYTHON) data/multilingual/Latn.NZI/Serif_16/pdf_to_json_test_Latn.NZI_Serif_16.py > data/multilingual/Latn.NZI/Serif_16/pdf_to_json_test_Latn.NZI_Serif_16.json 2>&1
Latn.NZI_Serif_8:
	-$(PYTHON) data/multilingual/Latn.NZI/Serif_8/pdf_to_json_test_Latn.NZI_Serif_8.py > data/multilingual/Latn.NZI/Serif_8/pdf_to_json_test_Latn.NZI_Serif_8.json 2>&1
Latn.NZI_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.NZI/Sun-ExtA_12/pdf_to_json_test_Latn.NZI_Sun-ExtA_12.py > data/multilingual/Latn.NZI/Sun-ExtA_12/pdf_to_json_test_Latn.NZI_Sun-ExtA_12.json 2>&1
Latn.NZI_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.NZI/Sun-ExtA_16/pdf_to_json_test_Latn.NZI_Sun-ExtA_16.py > data/multilingual/Latn.NZI/Sun-ExtA_16/pdf_to_json_test_Latn.NZI_Sun-ExtA_16.json 2>&1
Latn.NZI_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.NZI/Sun-ExtA_8/pdf_to_json_test_Latn.NZI_Sun-ExtA_8.py > data/multilingual/Latn.NZI/Sun-ExtA_8/pdf_to_json_test_Latn.NZI_Sun-ExtA_8.json 2>&1


Latn.NZI_all : Latn.NZI_Mono_12 Latn.NZI_Mono_16 Latn.NZI_Mono_8 Latn.NZI_Sans_12 Latn.NZI_Sans_16 Latn.NZI_Sans_8 Latn.NZI_Serif_12 Latn.NZI_Serif_16 Latn.NZI_Serif_8 Latn.NZI_Sun-ExtA_12 Latn.NZI_Sun-ExtA_16 Latn.NZI_Sun-ExtA_8
