PYTHON=python3


Cyrl.ADY_Mono_12:
	-$(PYTHON) data/multilingual/Cyrl.ADY/Mono_12/pdf_to_json_test_Cyrl.ADY_Mono_12.py > data/multilingual/Cyrl.ADY/Mono_12/pdf_to_json_test_Cyrl.ADY_Mono_12.json 2>&1
Cyrl.ADY_Mono_16:
	-$(PYTHON) data/multilingual/Cyrl.ADY/Mono_16/pdf_to_json_test_Cyrl.ADY_Mono_16.py > data/multilingual/Cyrl.ADY/Mono_16/pdf_to_json_test_Cyrl.ADY_Mono_16.json 2>&1
Cyrl.ADY_Mono_8:
	-$(PYTHON) data/multilingual/Cyrl.ADY/Mono_8/pdf_to_json_test_Cyrl.ADY_Mono_8.py > data/multilingual/Cyrl.ADY/Mono_8/pdf_to_json_test_Cyrl.ADY_Mono_8.json 2>&1
Cyrl.ADY_Sans_12:
	-$(PYTHON) data/multilingual/Cyrl.ADY/Sans_12/pdf_to_json_test_Cyrl.ADY_Sans_12.py > data/multilingual/Cyrl.ADY/Sans_12/pdf_to_json_test_Cyrl.ADY_Sans_12.json 2>&1
Cyrl.ADY_Sans_16:
	-$(PYTHON) data/multilingual/Cyrl.ADY/Sans_16/pdf_to_json_test_Cyrl.ADY_Sans_16.py > data/multilingual/Cyrl.ADY/Sans_16/pdf_to_json_test_Cyrl.ADY_Sans_16.json 2>&1
Cyrl.ADY_Sans_8:
	-$(PYTHON) data/multilingual/Cyrl.ADY/Sans_8/pdf_to_json_test_Cyrl.ADY_Sans_8.py > data/multilingual/Cyrl.ADY/Sans_8/pdf_to_json_test_Cyrl.ADY_Sans_8.json 2>&1
Cyrl.ADY_Serif_12:
	-$(PYTHON) data/multilingual/Cyrl.ADY/Serif_12/pdf_to_json_test_Cyrl.ADY_Serif_12.py > data/multilingual/Cyrl.ADY/Serif_12/pdf_to_json_test_Cyrl.ADY_Serif_12.json 2>&1
Cyrl.ADY_Serif_16:
	-$(PYTHON) data/multilingual/Cyrl.ADY/Serif_16/pdf_to_json_test_Cyrl.ADY_Serif_16.py > data/multilingual/Cyrl.ADY/Serif_16/pdf_to_json_test_Cyrl.ADY_Serif_16.json 2>&1
Cyrl.ADY_Serif_8:
	-$(PYTHON) data/multilingual/Cyrl.ADY/Serif_8/pdf_to_json_test_Cyrl.ADY_Serif_8.py > data/multilingual/Cyrl.ADY/Serif_8/pdf_to_json_test_Cyrl.ADY_Serif_8.json 2>&1
Cyrl.ADY_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Cyrl.ADY/Sun-ExtA_12/pdf_to_json_test_Cyrl.ADY_Sun-ExtA_12.py > data/multilingual/Cyrl.ADY/Sun-ExtA_12/pdf_to_json_test_Cyrl.ADY_Sun-ExtA_12.json 2>&1
Cyrl.ADY_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Cyrl.ADY/Sun-ExtA_16/pdf_to_json_test_Cyrl.ADY_Sun-ExtA_16.py > data/multilingual/Cyrl.ADY/Sun-ExtA_16/pdf_to_json_test_Cyrl.ADY_Sun-ExtA_16.json 2>&1
Cyrl.ADY_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Cyrl.ADY/Sun-ExtA_8/pdf_to_json_test_Cyrl.ADY_Sun-ExtA_8.py > data/multilingual/Cyrl.ADY/Sun-ExtA_8/pdf_to_json_test_Cyrl.ADY_Sun-ExtA_8.json 2>&1


Cyrl.ADY_all : Cyrl.ADY_Mono_12 Cyrl.ADY_Mono_16 Cyrl.ADY_Mono_8 Cyrl.ADY_Sans_12 Cyrl.ADY_Sans_16 Cyrl.ADY_Sans_8 Cyrl.ADY_Serif_12 Cyrl.ADY_Serif_16 Cyrl.ADY_Serif_8 Cyrl.ADY_Sun-ExtA_12 Cyrl.ADY_Sun-ExtA_16 Cyrl.ADY_Sun-ExtA_8
