PYTHON=python3


Latn.POR_Mono_12:
	-$(PYTHON) data/multilingual/Latn.POR/Mono_12/pdf_to_json_test_Latn.POR_Mono_12.py > data/multilingual/Latn.POR/Mono_12/pdf_to_json_test_Latn.POR_Mono_12.json 2>&1
Latn.POR_Mono_16:
	-$(PYTHON) data/multilingual/Latn.POR/Mono_16/pdf_to_json_test_Latn.POR_Mono_16.py > data/multilingual/Latn.POR/Mono_16/pdf_to_json_test_Latn.POR_Mono_16.json 2>&1
Latn.POR_Mono_8:
	-$(PYTHON) data/multilingual/Latn.POR/Mono_8/pdf_to_json_test_Latn.POR_Mono_8.py > data/multilingual/Latn.POR/Mono_8/pdf_to_json_test_Latn.POR_Mono_8.json 2>&1
Latn.POR_Sans_12:
	-$(PYTHON) data/multilingual/Latn.POR/Sans_12/pdf_to_json_test_Latn.POR_Sans_12.py > data/multilingual/Latn.POR/Sans_12/pdf_to_json_test_Latn.POR_Sans_12.json 2>&1
Latn.POR_Sans_16:
	-$(PYTHON) data/multilingual/Latn.POR/Sans_16/pdf_to_json_test_Latn.POR_Sans_16.py > data/multilingual/Latn.POR/Sans_16/pdf_to_json_test_Latn.POR_Sans_16.json 2>&1
Latn.POR_Sans_8:
	-$(PYTHON) data/multilingual/Latn.POR/Sans_8/pdf_to_json_test_Latn.POR_Sans_8.py > data/multilingual/Latn.POR/Sans_8/pdf_to_json_test_Latn.POR_Sans_8.json 2>&1
Latn.POR_Serif_12:
	-$(PYTHON) data/multilingual/Latn.POR/Serif_12/pdf_to_json_test_Latn.POR_Serif_12.py > data/multilingual/Latn.POR/Serif_12/pdf_to_json_test_Latn.POR_Serif_12.json 2>&1
Latn.POR_Serif_16:
	-$(PYTHON) data/multilingual/Latn.POR/Serif_16/pdf_to_json_test_Latn.POR_Serif_16.py > data/multilingual/Latn.POR/Serif_16/pdf_to_json_test_Latn.POR_Serif_16.json 2>&1
Latn.POR_Serif_8:
	-$(PYTHON) data/multilingual/Latn.POR/Serif_8/pdf_to_json_test_Latn.POR_Serif_8.py > data/multilingual/Latn.POR/Serif_8/pdf_to_json_test_Latn.POR_Serif_8.json 2>&1
Latn.POR_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.POR/Sun-ExtA_12/pdf_to_json_test_Latn.POR_Sun-ExtA_12.py > data/multilingual/Latn.POR/Sun-ExtA_12/pdf_to_json_test_Latn.POR_Sun-ExtA_12.json 2>&1
Latn.POR_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.POR/Sun-ExtA_16/pdf_to_json_test_Latn.POR_Sun-ExtA_16.py > data/multilingual/Latn.POR/Sun-ExtA_16/pdf_to_json_test_Latn.POR_Sun-ExtA_16.json 2>&1
Latn.POR_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.POR/Sun-ExtA_8/pdf_to_json_test_Latn.POR_Sun-ExtA_8.py > data/multilingual/Latn.POR/Sun-ExtA_8/pdf_to_json_test_Latn.POR_Sun-ExtA_8.json 2>&1


Latn.POR_all : Latn.POR_Mono_12 Latn.POR_Mono_16 Latn.POR_Mono_8 Latn.POR_Sans_12 Latn.POR_Sans_16 Latn.POR_Sans_8 Latn.POR_Serif_12 Latn.POR_Serif_16 Latn.POR_Serif_8 Latn.POR_Sun-ExtA_12 Latn.POR_Sun-ExtA_16 Latn.POR_Sun-ExtA_8
