PYTHON=python3


Latn.LOB_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.LOB/Mono_12/pdf_to_json_test_Latn.LOB_Mono_12.py" > "data/multilingual/Latn.LOB/Mono_12/pdf_to_json_test_Latn.LOB_Mono_12.json" 2>&1
Latn.LOB_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.LOB/Mono_16/pdf_to_json_test_Latn.LOB_Mono_16.py" > "data/multilingual/Latn.LOB/Mono_16/pdf_to_json_test_Latn.LOB_Mono_16.json" 2>&1
Latn.LOB_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.LOB/Mono_8/pdf_to_json_test_Latn.LOB_Mono_8.py" > "data/multilingual/Latn.LOB/Mono_8/pdf_to_json_test_Latn.LOB_Mono_8.json" 2>&1
Latn.LOB_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.LOB/Sans_12/pdf_to_json_test_Latn.LOB_Sans_12.py" > "data/multilingual/Latn.LOB/Sans_12/pdf_to_json_test_Latn.LOB_Sans_12.json" 2>&1
Latn.LOB_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.LOB/Sans_16/pdf_to_json_test_Latn.LOB_Sans_16.py" > "data/multilingual/Latn.LOB/Sans_16/pdf_to_json_test_Latn.LOB_Sans_16.json" 2>&1
Latn.LOB_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.LOB/Sans_8/pdf_to_json_test_Latn.LOB_Sans_8.py" > "data/multilingual/Latn.LOB/Sans_8/pdf_to_json_test_Latn.LOB_Sans_8.json" 2>&1
Latn.LOB_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.LOB/Serif_12/pdf_to_json_test_Latn.LOB_Serif_12.py" > "data/multilingual/Latn.LOB/Serif_12/pdf_to_json_test_Latn.LOB_Serif_12.json" 2>&1
Latn.LOB_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.LOB/Serif_16/pdf_to_json_test_Latn.LOB_Serif_16.py" > "data/multilingual/Latn.LOB/Serif_16/pdf_to_json_test_Latn.LOB_Serif_16.json" 2>&1
Latn.LOB_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.LOB/Serif_8/pdf_to_json_test_Latn.LOB_Serif_8.py" > "data/multilingual/Latn.LOB/Serif_8/pdf_to_json_test_Latn.LOB_Serif_8.json" 2>&1
Latn.LOB_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.LOB/Sun-ExtA_12/pdf_to_json_test_Latn.LOB_Sun-ExtA_12.py" > "data/multilingual/Latn.LOB/Sun-ExtA_12/pdf_to_json_test_Latn.LOB_Sun-ExtA_12.json" 2>&1
Latn.LOB_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.LOB/Sun-ExtA_16/pdf_to_json_test_Latn.LOB_Sun-ExtA_16.py" > "data/multilingual/Latn.LOB/Sun-ExtA_16/pdf_to_json_test_Latn.LOB_Sun-ExtA_16.json" 2>&1
Latn.LOB_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.LOB/Sun-ExtA_8/pdf_to_json_test_Latn.LOB_Sun-ExtA_8.py" > "data/multilingual/Latn.LOB/Sun-ExtA_8/pdf_to_json_test_Latn.LOB_Sun-ExtA_8.json" 2>&1


Latn.LOB_all : Latn.LOB_Mono_12 Latn.LOB_Mono_16 Latn.LOB_Mono_8 Latn.LOB_Sans_12 Latn.LOB_Sans_16 Latn.LOB_Sans_8 Latn.LOB_Serif_12 Latn.LOB_Serif_16 Latn.LOB_Serif_8 Latn.LOB_Sun-ExtA_12 Latn.LOB_Sun-ExtA_16 Latn.LOB_Sun-ExtA_8
