PYTHON=python3


Beng.BEN_Mono_12:
	-$(PYTHON) "data/multilingual/Beng.BEN/Mono_12/pdf_to_json_test_Beng.BEN_Mono_12.py" > "data/multilingual/Beng.BEN/Mono_12/pdf_to_json_test_Beng.BEN_Mono_12.json" 2>&1
Beng.BEN_Mono_16:
	-$(PYTHON) "data/multilingual/Beng.BEN/Mono_16/pdf_to_json_test_Beng.BEN_Mono_16.py" > "data/multilingual/Beng.BEN/Mono_16/pdf_to_json_test_Beng.BEN_Mono_16.json" 2>&1
Beng.BEN_Mono_8:
	-$(PYTHON) "data/multilingual/Beng.BEN/Mono_8/pdf_to_json_test_Beng.BEN_Mono_8.py" > "data/multilingual/Beng.BEN/Mono_8/pdf_to_json_test_Beng.BEN_Mono_8.json" 2>&1
Beng.BEN_Sans_12:
	-$(PYTHON) "data/multilingual/Beng.BEN/Sans_12/pdf_to_json_test_Beng.BEN_Sans_12.py" > "data/multilingual/Beng.BEN/Sans_12/pdf_to_json_test_Beng.BEN_Sans_12.json" 2>&1
Beng.BEN_Sans_16:
	-$(PYTHON) "data/multilingual/Beng.BEN/Sans_16/pdf_to_json_test_Beng.BEN_Sans_16.py" > "data/multilingual/Beng.BEN/Sans_16/pdf_to_json_test_Beng.BEN_Sans_16.json" 2>&1
Beng.BEN_Sans_8:
	-$(PYTHON) "data/multilingual/Beng.BEN/Sans_8/pdf_to_json_test_Beng.BEN_Sans_8.py" > "data/multilingual/Beng.BEN/Sans_8/pdf_to_json_test_Beng.BEN_Sans_8.json" 2>&1
Beng.BEN_Serif_12:
	-$(PYTHON) "data/multilingual/Beng.BEN/Serif_12/pdf_to_json_test_Beng.BEN_Serif_12.py" > "data/multilingual/Beng.BEN/Serif_12/pdf_to_json_test_Beng.BEN_Serif_12.json" 2>&1
Beng.BEN_Serif_16:
	-$(PYTHON) "data/multilingual/Beng.BEN/Serif_16/pdf_to_json_test_Beng.BEN_Serif_16.py" > "data/multilingual/Beng.BEN/Serif_16/pdf_to_json_test_Beng.BEN_Serif_16.json" 2>&1
Beng.BEN_Serif_8:
	-$(PYTHON) "data/multilingual/Beng.BEN/Serif_8/pdf_to_json_test_Beng.BEN_Serif_8.py" > "data/multilingual/Beng.BEN/Serif_8/pdf_to_json_test_Beng.BEN_Serif_8.json" 2>&1
Beng.BEN_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Beng.BEN/Sun-ExtA_12/pdf_to_json_test_Beng.BEN_Sun-ExtA_12.py" > "data/multilingual/Beng.BEN/Sun-ExtA_12/pdf_to_json_test_Beng.BEN_Sun-ExtA_12.json" 2>&1
Beng.BEN_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Beng.BEN/Sun-ExtA_16/pdf_to_json_test_Beng.BEN_Sun-ExtA_16.py" > "data/multilingual/Beng.BEN/Sun-ExtA_16/pdf_to_json_test_Beng.BEN_Sun-ExtA_16.json" 2>&1
Beng.BEN_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Beng.BEN/Sun-ExtA_8/pdf_to_json_test_Beng.BEN_Sun-ExtA_8.py" > "data/multilingual/Beng.BEN/Sun-ExtA_8/pdf_to_json_test_Beng.BEN_Sun-ExtA_8.json" 2>&1


Beng.BEN_all : Beng.BEN_Mono_12 Beng.BEN_Mono_16 Beng.BEN_Mono_8 Beng.BEN_Sans_12 Beng.BEN_Sans_16 Beng.BEN_Sans_8 Beng.BEN_Serif_12 Beng.BEN_Serif_16 Beng.BEN_Serif_8 Beng.BEN_Sun-ExtA_12 Beng.BEN_Sun-ExtA_16 Beng.BEN_Sun-ExtA_8
