PYTHON=python3


Latn.LTZ_Mono_12:
	-$(PYTHON) data/multilingual/Latn.LTZ/Mono_12/pdf_to_json_test_Latn.LTZ_Mono_12.py > data/multilingual/Latn.LTZ/Mono_12/pdf_to_json_test_Latn.LTZ_Mono_12.json 2>&1
Latn.LTZ_Mono_16:
	-$(PYTHON) data/multilingual/Latn.LTZ/Mono_16/pdf_to_json_test_Latn.LTZ_Mono_16.py > data/multilingual/Latn.LTZ/Mono_16/pdf_to_json_test_Latn.LTZ_Mono_16.json 2>&1
Latn.LTZ_Mono_8:
	-$(PYTHON) data/multilingual/Latn.LTZ/Mono_8/pdf_to_json_test_Latn.LTZ_Mono_8.py > data/multilingual/Latn.LTZ/Mono_8/pdf_to_json_test_Latn.LTZ_Mono_8.json 2>&1
Latn.LTZ_Sans_12:
	-$(PYTHON) data/multilingual/Latn.LTZ/Sans_12/pdf_to_json_test_Latn.LTZ_Sans_12.py > data/multilingual/Latn.LTZ/Sans_12/pdf_to_json_test_Latn.LTZ_Sans_12.json 2>&1
Latn.LTZ_Sans_16:
	-$(PYTHON) data/multilingual/Latn.LTZ/Sans_16/pdf_to_json_test_Latn.LTZ_Sans_16.py > data/multilingual/Latn.LTZ/Sans_16/pdf_to_json_test_Latn.LTZ_Sans_16.json 2>&1
Latn.LTZ_Sans_8:
	-$(PYTHON) data/multilingual/Latn.LTZ/Sans_8/pdf_to_json_test_Latn.LTZ_Sans_8.py > data/multilingual/Latn.LTZ/Sans_8/pdf_to_json_test_Latn.LTZ_Sans_8.json 2>&1
Latn.LTZ_Serif_12:
	-$(PYTHON) data/multilingual/Latn.LTZ/Serif_12/pdf_to_json_test_Latn.LTZ_Serif_12.py > data/multilingual/Latn.LTZ/Serif_12/pdf_to_json_test_Latn.LTZ_Serif_12.json 2>&1
Latn.LTZ_Serif_16:
	-$(PYTHON) data/multilingual/Latn.LTZ/Serif_16/pdf_to_json_test_Latn.LTZ_Serif_16.py > data/multilingual/Latn.LTZ/Serif_16/pdf_to_json_test_Latn.LTZ_Serif_16.json 2>&1
Latn.LTZ_Serif_8:
	-$(PYTHON) data/multilingual/Latn.LTZ/Serif_8/pdf_to_json_test_Latn.LTZ_Serif_8.py > data/multilingual/Latn.LTZ/Serif_8/pdf_to_json_test_Latn.LTZ_Serif_8.json 2>&1
Latn.LTZ_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.LTZ/Sun-ExtA_12/pdf_to_json_test_Latn.LTZ_Sun-ExtA_12.py > data/multilingual/Latn.LTZ/Sun-ExtA_12/pdf_to_json_test_Latn.LTZ_Sun-ExtA_12.json 2>&1
Latn.LTZ_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.LTZ/Sun-ExtA_16/pdf_to_json_test_Latn.LTZ_Sun-ExtA_16.py > data/multilingual/Latn.LTZ/Sun-ExtA_16/pdf_to_json_test_Latn.LTZ_Sun-ExtA_16.json 2>&1
Latn.LTZ_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.LTZ/Sun-ExtA_8/pdf_to_json_test_Latn.LTZ_Sun-ExtA_8.py > data/multilingual/Latn.LTZ/Sun-ExtA_8/pdf_to_json_test_Latn.LTZ_Sun-ExtA_8.json 2>&1


Latn.LTZ_all : Latn.LTZ_Mono_12 Latn.LTZ_Mono_16 Latn.LTZ_Mono_8 Latn.LTZ_Sans_12 Latn.LTZ_Sans_16 Latn.LTZ_Sans_8 Latn.LTZ_Serif_12 Latn.LTZ_Serif_16 Latn.LTZ_Serif_8 Latn.LTZ_Sun-ExtA_12 Latn.LTZ_Sun-ExtA_16 Latn.LTZ_Sun-ExtA_8
