PYTHON=python3


Tavt.BLT_Tai_Heritage_Pro_12:
	-$(PYTHON) "data/multilingual/Tavt.BLT/Tai Heritage Pro_12/pdf_to_json_test_Tavt.BLT_Tai_Heritage_Pro_12.py" > "data/multilingual/Tavt.BLT/Tai Heritage Pro_12/pdf_to_json_test_Tavt.BLT_Tai_Heritage_Pro_12.json" 2>&1
Tavt.BLT_Tai_Heritage_Pro_16:
	-$(PYTHON) "data/multilingual/Tavt.BLT/Tai Heritage Pro_16/pdf_to_json_test_Tavt.BLT_Tai_Heritage_Pro_16.py" > "data/multilingual/Tavt.BLT/Tai Heritage Pro_16/pdf_to_json_test_Tavt.BLT_Tai_Heritage_Pro_16.json" 2>&1
Tavt.BLT_Tai_Heritage_Pro_8:
	-$(PYTHON) "data/multilingual/Tavt.BLT/Tai Heritage Pro_8/pdf_to_json_test_Tavt.BLT_Tai_Heritage_Pro_8.py" > "data/multilingual/Tavt.BLT/Tai Heritage Pro_8/pdf_to_json_test_Tavt.BLT_Tai_Heritage_Pro_8.json" 2>&1


Tavt.BLT_all : Tavt.BLT_Tai_Heritage_Pro_12 Tavt.BLT_Tai_Heritage_Pro_16 Tavt.BLT_Tai_Heritage_Pro_8
