PYTHON=python3


Deva.HIN_Mono_12:
	-$(PYTHON) data/multilingual/Deva.HIN/Mono_12/pdf_to_json_test_Deva.HIN_Mono_12.py > data/multilingual/Deva.HIN/Mono_12/pdf_to_json_test_Deva.HIN_Mono_12.json 2>&1
Deva.HIN_Mono_16:
	-$(PYTHON) data/multilingual/Deva.HIN/Mono_16/pdf_to_json_test_Deva.HIN_Mono_16.py > data/multilingual/Deva.HIN/Mono_16/pdf_to_json_test_Deva.HIN_Mono_16.json 2>&1
Deva.HIN_Mono_8:
	-$(PYTHON) data/multilingual/Deva.HIN/Mono_8/pdf_to_json_test_Deva.HIN_Mono_8.py > data/multilingual/Deva.HIN/Mono_8/pdf_to_json_test_Deva.HIN_Mono_8.json 2>&1
Deva.HIN_Sans_12:
	-$(PYTHON) data/multilingual/Deva.HIN/Sans_12/pdf_to_json_test_Deva.HIN_Sans_12.py > data/multilingual/Deva.HIN/Sans_12/pdf_to_json_test_Deva.HIN_Sans_12.json 2>&1
Deva.HIN_Sans_16:
	-$(PYTHON) data/multilingual/Deva.HIN/Sans_16/pdf_to_json_test_Deva.HIN_Sans_16.py > data/multilingual/Deva.HIN/Sans_16/pdf_to_json_test_Deva.HIN_Sans_16.json 2>&1
Deva.HIN_Sans_8:
	-$(PYTHON) data/multilingual/Deva.HIN/Sans_8/pdf_to_json_test_Deva.HIN_Sans_8.py > data/multilingual/Deva.HIN/Sans_8/pdf_to_json_test_Deva.HIN_Sans_8.json 2>&1
Deva.HIN_Serif_12:
	-$(PYTHON) data/multilingual/Deva.HIN/Serif_12/pdf_to_json_test_Deva.HIN_Serif_12.py > data/multilingual/Deva.HIN/Serif_12/pdf_to_json_test_Deva.HIN_Serif_12.json 2>&1
Deva.HIN_Serif_16:
	-$(PYTHON) data/multilingual/Deva.HIN/Serif_16/pdf_to_json_test_Deva.HIN_Serif_16.py > data/multilingual/Deva.HIN/Serif_16/pdf_to_json_test_Deva.HIN_Serif_16.json 2>&1
Deva.HIN_Serif_8:
	-$(PYTHON) data/multilingual/Deva.HIN/Serif_8/pdf_to_json_test_Deva.HIN_Serif_8.py > data/multilingual/Deva.HIN/Serif_8/pdf_to_json_test_Deva.HIN_Serif_8.json 2>&1
Deva.HIN_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Deva.HIN/Sun-ExtA_12/pdf_to_json_test_Deva.HIN_Sun-ExtA_12.py > data/multilingual/Deva.HIN/Sun-ExtA_12/pdf_to_json_test_Deva.HIN_Sun-ExtA_12.json 2>&1
Deva.HIN_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Deva.HIN/Sun-ExtA_16/pdf_to_json_test_Deva.HIN_Sun-ExtA_16.py > data/multilingual/Deva.HIN/Sun-ExtA_16/pdf_to_json_test_Deva.HIN_Sun-ExtA_16.json 2>&1
Deva.HIN_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Deva.HIN/Sun-ExtA_8/pdf_to_json_test_Deva.HIN_Sun-ExtA_8.py > data/multilingual/Deva.HIN/Sun-ExtA_8/pdf_to_json_test_Deva.HIN_Sun-ExtA_8.json 2>&1


Deva.HIN_all : Deva.HIN_Mono_12 Deva.HIN_Mono_16 Deva.HIN_Mono_8 Deva.HIN_Sans_12 Deva.HIN_Sans_16 Deva.HIN_Sans_8 Deva.HIN_Serif_12 Deva.HIN_Serif_16 Deva.HIN_Serif_8 Deva.HIN_Sun-ExtA_12 Deva.HIN_Sun-ExtA_16 Deva.HIN_Sun-ExtA_8
