PYTHON=python3


Latn.JAV_Mono_12:
	-$(PYTHON) data/multilingual/Latn.JAV/Mono_12/pdf_to_json_test_Latn.JAV_Mono_12.py > data/multilingual/Latn.JAV/Mono_12/pdf_to_json_test_Latn.JAV_Mono_12.json 2>&1
Latn.JAV_Mono_16:
	-$(PYTHON) data/multilingual/Latn.JAV/Mono_16/pdf_to_json_test_Latn.JAV_Mono_16.py > data/multilingual/Latn.JAV/Mono_16/pdf_to_json_test_Latn.JAV_Mono_16.json 2>&1
Latn.JAV_Mono_8:
	-$(PYTHON) data/multilingual/Latn.JAV/Mono_8/pdf_to_json_test_Latn.JAV_Mono_8.py > data/multilingual/Latn.JAV/Mono_8/pdf_to_json_test_Latn.JAV_Mono_8.json 2>&1
Latn.JAV_Sans_12:
	-$(PYTHON) data/multilingual/Latn.JAV/Sans_12/pdf_to_json_test_Latn.JAV_Sans_12.py > data/multilingual/Latn.JAV/Sans_12/pdf_to_json_test_Latn.JAV_Sans_12.json 2>&1
Latn.JAV_Sans_16:
	-$(PYTHON) data/multilingual/Latn.JAV/Sans_16/pdf_to_json_test_Latn.JAV_Sans_16.py > data/multilingual/Latn.JAV/Sans_16/pdf_to_json_test_Latn.JAV_Sans_16.json 2>&1
Latn.JAV_Sans_8:
	-$(PYTHON) data/multilingual/Latn.JAV/Sans_8/pdf_to_json_test_Latn.JAV_Sans_8.py > data/multilingual/Latn.JAV/Sans_8/pdf_to_json_test_Latn.JAV_Sans_8.json 2>&1
Latn.JAV_Serif_12:
	-$(PYTHON) data/multilingual/Latn.JAV/Serif_12/pdf_to_json_test_Latn.JAV_Serif_12.py > data/multilingual/Latn.JAV/Serif_12/pdf_to_json_test_Latn.JAV_Serif_12.json 2>&1
Latn.JAV_Serif_16:
	-$(PYTHON) data/multilingual/Latn.JAV/Serif_16/pdf_to_json_test_Latn.JAV_Serif_16.py > data/multilingual/Latn.JAV/Serif_16/pdf_to_json_test_Latn.JAV_Serif_16.json 2>&1
Latn.JAV_Serif_8:
	-$(PYTHON) data/multilingual/Latn.JAV/Serif_8/pdf_to_json_test_Latn.JAV_Serif_8.py > data/multilingual/Latn.JAV/Serif_8/pdf_to_json_test_Latn.JAV_Serif_8.json 2>&1
Latn.JAV_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.JAV/Sun-ExtA_12/pdf_to_json_test_Latn.JAV_Sun-ExtA_12.py > data/multilingual/Latn.JAV/Sun-ExtA_12/pdf_to_json_test_Latn.JAV_Sun-ExtA_12.json 2>&1
Latn.JAV_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.JAV/Sun-ExtA_16/pdf_to_json_test_Latn.JAV_Sun-ExtA_16.py > data/multilingual/Latn.JAV/Sun-ExtA_16/pdf_to_json_test_Latn.JAV_Sun-ExtA_16.json 2>&1
Latn.JAV_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.JAV/Sun-ExtA_8/pdf_to_json_test_Latn.JAV_Sun-ExtA_8.py > data/multilingual/Latn.JAV/Sun-ExtA_8/pdf_to_json_test_Latn.JAV_Sun-ExtA_8.json 2>&1


Latn.JAV_all : Latn.JAV_Mono_12 Latn.JAV_Mono_16 Latn.JAV_Mono_8 Latn.JAV_Sans_12 Latn.JAV_Sans_16 Latn.JAV_Sans_8 Latn.JAV_Serif_12 Latn.JAV_Serif_16 Latn.JAV_Serif_8 Latn.JAV_Sun-ExtA_12 Latn.JAV_Sun-ExtA_16 Latn.JAV_Sun-ExtA_8
