PYTHON=python3


Latn.MLT_Mono_12:
	-$(PYTHON) data/multilingual/Latn.MLT/Mono_12/pdf_to_json_test_Latn.MLT_Mono_12.py > data/multilingual/Latn.MLT/Mono_12/pdf_to_json_test_Latn.MLT_Mono_12.json 2>&1
Latn.MLT_Mono_16:
	-$(PYTHON) data/multilingual/Latn.MLT/Mono_16/pdf_to_json_test_Latn.MLT_Mono_16.py > data/multilingual/Latn.MLT/Mono_16/pdf_to_json_test_Latn.MLT_Mono_16.json 2>&1
Latn.MLT_Mono_8:
	-$(PYTHON) data/multilingual/Latn.MLT/Mono_8/pdf_to_json_test_Latn.MLT_Mono_8.py > data/multilingual/Latn.MLT/Mono_8/pdf_to_json_test_Latn.MLT_Mono_8.json 2>&1
Latn.MLT_Sans_12:
	-$(PYTHON) data/multilingual/Latn.MLT/Sans_12/pdf_to_json_test_Latn.MLT_Sans_12.py > data/multilingual/Latn.MLT/Sans_12/pdf_to_json_test_Latn.MLT_Sans_12.json 2>&1
Latn.MLT_Sans_16:
	-$(PYTHON) data/multilingual/Latn.MLT/Sans_16/pdf_to_json_test_Latn.MLT_Sans_16.py > data/multilingual/Latn.MLT/Sans_16/pdf_to_json_test_Latn.MLT_Sans_16.json 2>&1
Latn.MLT_Sans_8:
	-$(PYTHON) data/multilingual/Latn.MLT/Sans_8/pdf_to_json_test_Latn.MLT_Sans_8.py > data/multilingual/Latn.MLT/Sans_8/pdf_to_json_test_Latn.MLT_Sans_8.json 2>&1
Latn.MLT_Serif_12:
	-$(PYTHON) data/multilingual/Latn.MLT/Serif_12/pdf_to_json_test_Latn.MLT_Serif_12.py > data/multilingual/Latn.MLT/Serif_12/pdf_to_json_test_Latn.MLT_Serif_12.json 2>&1
Latn.MLT_Serif_16:
	-$(PYTHON) data/multilingual/Latn.MLT/Serif_16/pdf_to_json_test_Latn.MLT_Serif_16.py > data/multilingual/Latn.MLT/Serif_16/pdf_to_json_test_Latn.MLT_Serif_16.json 2>&1
Latn.MLT_Serif_8:
	-$(PYTHON) data/multilingual/Latn.MLT/Serif_8/pdf_to_json_test_Latn.MLT_Serif_8.py > data/multilingual/Latn.MLT/Serif_8/pdf_to_json_test_Latn.MLT_Serif_8.json 2>&1
Latn.MLT_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.MLT/Sun-ExtA_12/pdf_to_json_test_Latn.MLT_Sun-ExtA_12.py > data/multilingual/Latn.MLT/Sun-ExtA_12/pdf_to_json_test_Latn.MLT_Sun-ExtA_12.json 2>&1
Latn.MLT_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.MLT/Sun-ExtA_16/pdf_to_json_test_Latn.MLT_Sun-ExtA_16.py > data/multilingual/Latn.MLT/Sun-ExtA_16/pdf_to_json_test_Latn.MLT_Sun-ExtA_16.json 2>&1
Latn.MLT_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.MLT/Sun-ExtA_8/pdf_to_json_test_Latn.MLT_Sun-ExtA_8.py > data/multilingual/Latn.MLT/Sun-ExtA_8/pdf_to_json_test_Latn.MLT_Sun-ExtA_8.json 2>&1


Latn.MLT_all : Latn.MLT_Mono_12 Latn.MLT_Mono_16 Latn.MLT_Mono_8 Latn.MLT_Sans_12 Latn.MLT_Sans_16 Latn.MLT_Sans_8 Latn.MLT_Serif_12 Latn.MLT_Serif_16 Latn.MLT_Serif_8 Latn.MLT_Sun-ExtA_12 Latn.MLT_Sun-ExtA_16 Latn.MLT_Sun-ExtA_8
