PYTHON=python3


Latn.DAG_Mono_12:
	-$(PYTHON) data/multilingual/Latn.DAG/Mono_12/pdf_to_json_test_Latn.DAG_Mono_12.py > data/multilingual/Latn.DAG/Mono_12/pdf_to_json_test_Latn.DAG_Mono_12.json 2>&1
Latn.DAG_Mono_16:
	-$(PYTHON) data/multilingual/Latn.DAG/Mono_16/pdf_to_json_test_Latn.DAG_Mono_16.py > data/multilingual/Latn.DAG/Mono_16/pdf_to_json_test_Latn.DAG_Mono_16.json 2>&1
Latn.DAG_Mono_8:
	-$(PYTHON) data/multilingual/Latn.DAG/Mono_8/pdf_to_json_test_Latn.DAG_Mono_8.py > data/multilingual/Latn.DAG/Mono_8/pdf_to_json_test_Latn.DAG_Mono_8.json 2>&1
Latn.DAG_Sans_12:
	-$(PYTHON) data/multilingual/Latn.DAG/Sans_12/pdf_to_json_test_Latn.DAG_Sans_12.py > data/multilingual/Latn.DAG/Sans_12/pdf_to_json_test_Latn.DAG_Sans_12.json 2>&1
Latn.DAG_Sans_16:
	-$(PYTHON) data/multilingual/Latn.DAG/Sans_16/pdf_to_json_test_Latn.DAG_Sans_16.py > data/multilingual/Latn.DAG/Sans_16/pdf_to_json_test_Latn.DAG_Sans_16.json 2>&1
Latn.DAG_Sans_8:
	-$(PYTHON) data/multilingual/Latn.DAG/Sans_8/pdf_to_json_test_Latn.DAG_Sans_8.py > data/multilingual/Latn.DAG/Sans_8/pdf_to_json_test_Latn.DAG_Sans_8.json 2>&1
Latn.DAG_Serif_12:
	-$(PYTHON) data/multilingual/Latn.DAG/Serif_12/pdf_to_json_test_Latn.DAG_Serif_12.py > data/multilingual/Latn.DAG/Serif_12/pdf_to_json_test_Latn.DAG_Serif_12.json 2>&1
Latn.DAG_Serif_16:
	-$(PYTHON) data/multilingual/Latn.DAG/Serif_16/pdf_to_json_test_Latn.DAG_Serif_16.py > data/multilingual/Latn.DAG/Serif_16/pdf_to_json_test_Latn.DAG_Serif_16.json 2>&1
Latn.DAG_Serif_8:
	-$(PYTHON) data/multilingual/Latn.DAG/Serif_8/pdf_to_json_test_Latn.DAG_Serif_8.py > data/multilingual/Latn.DAG/Serif_8/pdf_to_json_test_Latn.DAG_Serif_8.json 2>&1
Latn.DAG_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.DAG/Sun-ExtA_12/pdf_to_json_test_Latn.DAG_Sun-ExtA_12.py > data/multilingual/Latn.DAG/Sun-ExtA_12/pdf_to_json_test_Latn.DAG_Sun-ExtA_12.json 2>&1
Latn.DAG_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.DAG/Sun-ExtA_16/pdf_to_json_test_Latn.DAG_Sun-ExtA_16.py > data/multilingual/Latn.DAG/Sun-ExtA_16/pdf_to_json_test_Latn.DAG_Sun-ExtA_16.json 2>&1
Latn.DAG_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.DAG/Sun-ExtA_8/pdf_to_json_test_Latn.DAG_Sun-ExtA_8.py > data/multilingual/Latn.DAG/Sun-ExtA_8/pdf_to_json_test_Latn.DAG_Sun-ExtA_8.json 2>&1


Latn.DAG_all : Latn.DAG_Mono_12 Latn.DAG_Mono_16 Latn.DAG_Mono_8 Latn.DAG_Sans_12 Latn.DAG_Sans_16 Latn.DAG_Sans_8 Latn.DAG_Serif_12 Latn.DAG_Serif_16 Latn.DAG_Serif_8 Latn.DAG_Sun-ExtA_12 Latn.DAG_Sun-ExtA_16 Latn.DAG_Sun-ExtA_8
