PYTHON=python3


Latn.SUN_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.SUN/Mono_12/pdf_to_json_test_Latn.SUN_Mono_12.py" > "data/multilingual/Latn.SUN/Mono_12/pdf_to_json_test_Latn.SUN_Mono_12.json" 2>&1
Latn.SUN_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.SUN/Mono_16/pdf_to_json_test_Latn.SUN_Mono_16.py" > "data/multilingual/Latn.SUN/Mono_16/pdf_to_json_test_Latn.SUN_Mono_16.json" 2>&1
Latn.SUN_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.SUN/Mono_8/pdf_to_json_test_Latn.SUN_Mono_8.py" > "data/multilingual/Latn.SUN/Mono_8/pdf_to_json_test_Latn.SUN_Mono_8.json" 2>&1
Latn.SUN_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.SUN/Sans_12/pdf_to_json_test_Latn.SUN_Sans_12.py" > "data/multilingual/Latn.SUN/Sans_12/pdf_to_json_test_Latn.SUN_Sans_12.json" 2>&1
Latn.SUN_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.SUN/Sans_16/pdf_to_json_test_Latn.SUN_Sans_16.py" > "data/multilingual/Latn.SUN/Sans_16/pdf_to_json_test_Latn.SUN_Sans_16.json" 2>&1
Latn.SUN_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.SUN/Sans_8/pdf_to_json_test_Latn.SUN_Sans_8.py" > "data/multilingual/Latn.SUN/Sans_8/pdf_to_json_test_Latn.SUN_Sans_8.json" 2>&1
Latn.SUN_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.SUN/Serif_12/pdf_to_json_test_Latn.SUN_Serif_12.py" > "data/multilingual/Latn.SUN/Serif_12/pdf_to_json_test_Latn.SUN_Serif_12.json" 2>&1
Latn.SUN_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.SUN/Serif_16/pdf_to_json_test_Latn.SUN_Serif_16.py" > "data/multilingual/Latn.SUN/Serif_16/pdf_to_json_test_Latn.SUN_Serif_16.json" 2>&1
Latn.SUN_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.SUN/Serif_8/pdf_to_json_test_Latn.SUN_Serif_8.py" > "data/multilingual/Latn.SUN/Serif_8/pdf_to_json_test_Latn.SUN_Serif_8.json" 2>&1
Latn.SUN_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.SUN/Sun-ExtA_12/pdf_to_json_test_Latn.SUN_Sun-ExtA_12.py" > "data/multilingual/Latn.SUN/Sun-ExtA_12/pdf_to_json_test_Latn.SUN_Sun-ExtA_12.json" 2>&1
Latn.SUN_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.SUN/Sun-ExtA_16/pdf_to_json_test_Latn.SUN_Sun-ExtA_16.py" > "data/multilingual/Latn.SUN/Sun-ExtA_16/pdf_to_json_test_Latn.SUN_Sun-ExtA_16.json" 2>&1
Latn.SUN_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.SUN/Sun-ExtA_8/pdf_to_json_test_Latn.SUN_Sun-ExtA_8.py" > "data/multilingual/Latn.SUN/Sun-ExtA_8/pdf_to_json_test_Latn.SUN_Sun-ExtA_8.json" 2>&1


Latn.SUN_all : Latn.SUN_Mono_12 Latn.SUN_Mono_16 Latn.SUN_Mono_8 Latn.SUN_Sans_12 Latn.SUN_Sans_16 Latn.SUN_Sans_8 Latn.SUN_Serif_12 Latn.SUN_Serif_16 Latn.SUN_Serif_8 Latn.SUN_Sun-ExtA_12 Latn.SUN_Sun-ExtA_16 Latn.SUN_Sun-ExtA_8
