PYTHON=python3


Latn.HAW_Mono_12:
	-$(PYTHON) data/multilingual/Latn.HAW/Mono_12/pdf_to_json_test_Latn.HAW_Mono_12.py > data/multilingual/Latn.HAW/Mono_12/pdf_to_json_test_Latn.HAW_Mono_12.json 2>&1
Latn.HAW_Mono_16:
	-$(PYTHON) data/multilingual/Latn.HAW/Mono_16/pdf_to_json_test_Latn.HAW_Mono_16.py > data/multilingual/Latn.HAW/Mono_16/pdf_to_json_test_Latn.HAW_Mono_16.json 2>&1
Latn.HAW_Mono_8:
	-$(PYTHON) data/multilingual/Latn.HAW/Mono_8/pdf_to_json_test_Latn.HAW_Mono_8.py > data/multilingual/Latn.HAW/Mono_8/pdf_to_json_test_Latn.HAW_Mono_8.json 2>&1
Latn.HAW_Sans_12:
	-$(PYTHON) data/multilingual/Latn.HAW/Sans_12/pdf_to_json_test_Latn.HAW_Sans_12.py > data/multilingual/Latn.HAW/Sans_12/pdf_to_json_test_Latn.HAW_Sans_12.json 2>&1
Latn.HAW_Sans_16:
	-$(PYTHON) data/multilingual/Latn.HAW/Sans_16/pdf_to_json_test_Latn.HAW_Sans_16.py > data/multilingual/Latn.HAW/Sans_16/pdf_to_json_test_Latn.HAW_Sans_16.json 2>&1
Latn.HAW_Sans_8:
	-$(PYTHON) data/multilingual/Latn.HAW/Sans_8/pdf_to_json_test_Latn.HAW_Sans_8.py > data/multilingual/Latn.HAW/Sans_8/pdf_to_json_test_Latn.HAW_Sans_8.json 2>&1
Latn.HAW_Serif_12:
	-$(PYTHON) data/multilingual/Latn.HAW/Serif_12/pdf_to_json_test_Latn.HAW_Serif_12.py > data/multilingual/Latn.HAW/Serif_12/pdf_to_json_test_Latn.HAW_Serif_12.json 2>&1
Latn.HAW_Serif_16:
	-$(PYTHON) data/multilingual/Latn.HAW/Serif_16/pdf_to_json_test_Latn.HAW_Serif_16.py > data/multilingual/Latn.HAW/Serif_16/pdf_to_json_test_Latn.HAW_Serif_16.json 2>&1
Latn.HAW_Serif_8:
	-$(PYTHON) data/multilingual/Latn.HAW/Serif_8/pdf_to_json_test_Latn.HAW_Serif_8.py > data/multilingual/Latn.HAW/Serif_8/pdf_to_json_test_Latn.HAW_Serif_8.json 2>&1
Latn.HAW_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.HAW/Sun-ExtA_12/pdf_to_json_test_Latn.HAW_Sun-ExtA_12.py > data/multilingual/Latn.HAW/Sun-ExtA_12/pdf_to_json_test_Latn.HAW_Sun-ExtA_12.json 2>&1
Latn.HAW_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.HAW/Sun-ExtA_16/pdf_to_json_test_Latn.HAW_Sun-ExtA_16.py > data/multilingual/Latn.HAW/Sun-ExtA_16/pdf_to_json_test_Latn.HAW_Sun-ExtA_16.json 2>&1
Latn.HAW_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.HAW/Sun-ExtA_8/pdf_to_json_test_Latn.HAW_Sun-ExtA_8.py > data/multilingual/Latn.HAW/Sun-ExtA_8/pdf_to_json_test_Latn.HAW_Sun-ExtA_8.json 2>&1


Latn.HAW_all : Latn.HAW_Mono_12 Latn.HAW_Mono_16 Latn.HAW_Mono_8 Latn.HAW_Sans_12 Latn.HAW_Sans_16 Latn.HAW_Sans_8 Latn.HAW_Serif_12 Latn.HAW_Serif_16 Latn.HAW_Serif_8 Latn.HAW_Sun-ExtA_12 Latn.HAW_Sun-ExtA_16 Latn.HAW_Sun-ExtA_8
