PYTHON=python3


Latn.MIQ_Mono_12:
	-$(PYTHON) data/multilingual/Latn.MIQ/Mono_12/pdf_to_json_test_Latn.MIQ_Mono_12.py > data/multilingual/Latn.MIQ/Mono_12/pdf_to_json_test_Latn.MIQ_Mono_12.json 2>&1
Latn.MIQ_Mono_16:
	-$(PYTHON) data/multilingual/Latn.MIQ/Mono_16/pdf_to_json_test_Latn.MIQ_Mono_16.py > data/multilingual/Latn.MIQ/Mono_16/pdf_to_json_test_Latn.MIQ_Mono_16.json 2>&1
Latn.MIQ_Mono_8:
	-$(PYTHON) data/multilingual/Latn.MIQ/Mono_8/pdf_to_json_test_Latn.MIQ_Mono_8.py > data/multilingual/Latn.MIQ/Mono_8/pdf_to_json_test_Latn.MIQ_Mono_8.json 2>&1
Latn.MIQ_Sans_12:
	-$(PYTHON) data/multilingual/Latn.MIQ/Sans_12/pdf_to_json_test_Latn.MIQ_Sans_12.py > data/multilingual/Latn.MIQ/Sans_12/pdf_to_json_test_Latn.MIQ_Sans_12.json 2>&1
Latn.MIQ_Sans_16:
	-$(PYTHON) data/multilingual/Latn.MIQ/Sans_16/pdf_to_json_test_Latn.MIQ_Sans_16.py > data/multilingual/Latn.MIQ/Sans_16/pdf_to_json_test_Latn.MIQ_Sans_16.json 2>&1
Latn.MIQ_Sans_8:
	-$(PYTHON) data/multilingual/Latn.MIQ/Sans_8/pdf_to_json_test_Latn.MIQ_Sans_8.py > data/multilingual/Latn.MIQ/Sans_8/pdf_to_json_test_Latn.MIQ_Sans_8.json 2>&1
Latn.MIQ_Serif_12:
	-$(PYTHON) data/multilingual/Latn.MIQ/Serif_12/pdf_to_json_test_Latn.MIQ_Serif_12.py > data/multilingual/Latn.MIQ/Serif_12/pdf_to_json_test_Latn.MIQ_Serif_12.json 2>&1
Latn.MIQ_Serif_16:
	-$(PYTHON) data/multilingual/Latn.MIQ/Serif_16/pdf_to_json_test_Latn.MIQ_Serif_16.py > data/multilingual/Latn.MIQ/Serif_16/pdf_to_json_test_Latn.MIQ_Serif_16.json 2>&1
Latn.MIQ_Serif_8:
	-$(PYTHON) data/multilingual/Latn.MIQ/Serif_8/pdf_to_json_test_Latn.MIQ_Serif_8.py > data/multilingual/Latn.MIQ/Serif_8/pdf_to_json_test_Latn.MIQ_Serif_8.json 2>&1
Latn.MIQ_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.MIQ/Sun-ExtA_12/pdf_to_json_test_Latn.MIQ_Sun-ExtA_12.py > data/multilingual/Latn.MIQ/Sun-ExtA_12/pdf_to_json_test_Latn.MIQ_Sun-ExtA_12.json 2>&1
Latn.MIQ_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.MIQ/Sun-ExtA_16/pdf_to_json_test_Latn.MIQ_Sun-ExtA_16.py > data/multilingual/Latn.MIQ/Sun-ExtA_16/pdf_to_json_test_Latn.MIQ_Sun-ExtA_16.json 2>&1
Latn.MIQ_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.MIQ/Sun-ExtA_8/pdf_to_json_test_Latn.MIQ_Sun-ExtA_8.py > data/multilingual/Latn.MIQ/Sun-ExtA_8/pdf_to_json_test_Latn.MIQ_Sun-ExtA_8.json 2>&1


Latn.MIQ_all : Latn.MIQ_Mono_12 Latn.MIQ_Mono_16 Latn.MIQ_Mono_8 Latn.MIQ_Sans_12 Latn.MIQ_Sans_16 Latn.MIQ_Sans_8 Latn.MIQ_Serif_12 Latn.MIQ_Serif_16 Latn.MIQ_Serif_8 Latn.MIQ_Sun-ExtA_12 Latn.MIQ_Sun-ExtA_16 Latn.MIQ_Sun-ExtA_8
