PYTHON=python3


Latn.PLT_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.PLT/Mono_12/pdf_to_json_test_Latn.PLT_Mono_12.py" > "data/multilingual/Latn.PLT/Mono_12/pdf_to_json_test_Latn.PLT_Mono_12.json" 2>&1
Latn.PLT_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.PLT/Mono_16/pdf_to_json_test_Latn.PLT_Mono_16.py" > "data/multilingual/Latn.PLT/Mono_16/pdf_to_json_test_Latn.PLT_Mono_16.json" 2>&1
Latn.PLT_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.PLT/Mono_8/pdf_to_json_test_Latn.PLT_Mono_8.py" > "data/multilingual/Latn.PLT/Mono_8/pdf_to_json_test_Latn.PLT_Mono_8.json" 2>&1
Latn.PLT_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.PLT/Sans_12/pdf_to_json_test_Latn.PLT_Sans_12.py" > "data/multilingual/Latn.PLT/Sans_12/pdf_to_json_test_Latn.PLT_Sans_12.json" 2>&1
Latn.PLT_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.PLT/Sans_16/pdf_to_json_test_Latn.PLT_Sans_16.py" > "data/multilingual/Latn.PLT/Sans_16/pdf_to_json_test_Latn.PLT_Sans_16.json" 2>&1
Latn.PLT_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.PLT/Sans_8/pdf_to_json_test_Latn.PLT_Sans_8.py" > "data/multilingual/Latn.PLT/Sans_8/pdf_to_json_test_Latn.PLT_Sans_8.json" 2>&1
Latn.PLT_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.PLT/Serif_12/pdf_to_json_test_Latn.PLT_Serif_12.py" > "data/multilingual/Latn.PLT/Serif_12/pdf_to_json_test_Latn.PLT_Serif_12.json" 2>&1
Latn.PLT_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.PLT/Serif_16/pdf_to_json_test_Latn.PLT_Serif_16.py" > "data/multilingual/Latn.PLT/Serif_16/pdf_to_json_test_Latn.PLT_Serif_16.json" 2>&1
Latn.PLT_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.PLT/Serif_8/pdf_to_json_test_Latn.PLT_Serif_8.py" > "data/multilingual/Latn.PLT/Serif_8/pdf_to_json_test_Latn.PLT_Serif_8.json" 2>&1
Latn.PLT_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.PLT/Sun-ExtA_12/pdf_to_json_test_Latn.PLT_Sun-ExtA_12.py" > "data/multilingual/Latn.PLT/Sun-ExtA_12/pdf_to_json_test_Latn.PLT_Sun-ExtA_12.json" 2>&1
Latn.PLT_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.PLT/Sun-ExtA_16/pdf_to_json_test_Latn.PLT_Sun-ExtA_16.py" > "data/multilingual/Latn.PLT/Sun-ExtA_16/pdf_to_json_test_Latn.PLT_Sun-ExtA_16.json" 2>&1
Latn.PLT_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.PLT/Sun-ExtA_8/pdf_to_json_test_Latn.PLT_Sun-ExtA_8.py" > "data/multilingual/Latn.PLT/Sun-ExtA_8/pdf_to_json_test_Latn.PLT_Sun-ExtA_8.json" 2>&1


Latn.PLT_all : Latn.PLT_Mono_12 Latn.PLT_Mono_16 Latn.PLT_Mono_8 Latn.PLT_Sans_12 Latn.PLT_Sans_16 Latn.PLT_Sans_8 Latn.PLT_Serif_12 Latn.PLT_Serif_16 Latn.PLT_Serif_8 Latn.PLT_Sun-ExtA_12 Latn.PLT_Sun-ExtA_16 Latn.PLT_Sun-ExtA_8
