PYTHON=python3


Latn.OCI_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.OCI/Mono_12/pdf_to_json_test_Latn.OCI_Mono_12.py" > "data/multilingual/Latn.OCI/Mono_12/pdf_to_json_test_Latn.OCI_Mono_12.json" 2>&1
Latn.OCI_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.OCI/Mono_16/pdf_to_json_test_Latn.OCI_Mono_16.py" > "data/multilingual/Latn.OCI/Mono_16/pdf_to_json_test_Latn.OCI_Mono_16.json" 2>&1
Latn.OCI_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.OCI/Mono_8/pdf_to_json_test_Latn.OCI_Mono_8.py" > "data/multilingual/Latn.OCI/Mono_8/pdf_to_json_test_Latn.OCI_Mono_8.json" 2>&1
Latn.OCI_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.OCI/Sans_12/pdf_to_json_test_Latn.OCI_Sans_12.py" > "data/multilingual/Latn.OCI/Sans_12/pdf_to_json_test_Latn.OCI_Sans_12.json" 2>&1
Latn.OCI_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.OCI/Sans_16/pdf_to_json_test_Latn.OCI_Sans_16.py" > "data/multilingual/Latn.OCI/Sans_16/pdf_to_json_test_Latn.OCI_Sans_16.json" 2>&1
Latn.OCI_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.OCI/Sans_8/pdf_to_json_test_Latn.OCI_Sans_8.py" > "data/multilingual/Latn.OCI/Sans_8/pdf_to_json_test_Latn.OCI_Sans_8.json" 2>&1
Latn.OCI_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.OCI/Serif_12/pdf_to_json_test_Latn.OCI_Serif_12.py" > "data/multilingual/Latn.OCI/Serif_12/pdf_to_json_test_Latn.OCI_Serif_12.json" 2>&1
Latn.OCI_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.OCI/Serif_16/pdf_to_json_test_Latn.OCI_Serif_16.py" > "data/multilingual/Latn.OCI/Serif_16/pdf_to_json_test_Latn.OCI_Serif_16.json" 2>&1
Latn.OCI_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.OCI/Serif_8/pdf_to_json_test_Latn.OCI_Serif_8.py" > "data/multilingual/Latn.OCI/Serif_8/pdf_to_json_test_Latn.OCI_Serif_8.json" 2>&1
Latn.OCI_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.OCI/Sun-ExtA_12/pdf_to_json_test_Latn.OCI_Sun-ExtA_12.py" > "data/multilingual/Latn.OCI/Sun-ExtA_12/pdf_to_json_test_Latn.OCI_Sun-ExtA_12.json" 2>&1
Latn.OCI_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.OCI/Sun-ExtA_16/pdf_to_json_test_Latn.OCI_Sun-ExtA_16.py" > "data/multilingual/Latn.OCI/Sun-ExtA_16/pdf_to_json_test_Latn.OCI_Sun-ExtA_16.json" 2>&1
Latn.OCI_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.OCI/Sun-ExtA_8/pdf_to_json_test_Latn.OCI_Sun-ExtA_8.py" > "data/multilingual/Latn.OCI/Sun-ExtA_8/pdf_to_json_test_Latn.OCI_Sun-ExtA_8.json" 2>&1


Latn.OCI_all : Latn.OCI_Mono_12 Latn.OCI_Mono_16 Latn.OCI_Mono_8 Latn.OCI_Sans_12 Latn.OCI_Sans_16 Latn.OCI_Sans_8 Latn.OCI_Serif_12 Latn.OCI_Serif_16 Latn.OCI_Serif_8 Latn.OCI_Sun-ExtA_12 Latn.OCI_Sun-ExtA_16 Latn.OCI_Sun-ExtA_8
