PYTHON=python3


Latn.DYO_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.DYO/Mono_12/pdf_to_json_test_Latn.DYO_Mono_12.py" > "data/multilingual/Latn.DYO/Mono_12/pdf_to_json_test_Latn.DYO_Mono_12.json" 2>&1
Latn.DYO_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.DYO/Mono_16/pdf_to_json_test_Latn.DYO_Mono_16.py" > "data/multilingual/Latn.DYO/Mono_16/pdf_to_json_test_Latn.DYO_Mono_16.json" 2>&1
Latn.DYO_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.DYO/Mono_8/pdf_to_json_test_Latn.DYO_Mono_8.py" > "data/multilingual/Latn.DYO/Mono_8/pdf_to_json_test_Latn.DYO_Mono_8.json" 2>&1
Latn.DYO_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.DYO/Sans_12/pdf_to_json_test_Latn.DYO_Sans_12.py" > "data/multilingual/Latn.DYO/Sans_12/pdf_to_json_test_Latn.DYO_Sans_12.json" 2>&1
Latn.DYO_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.DYO/Sans_16/pdf_to_json_test_Latn.DYO_Sans_16.py" > "data/multilingual/Latn.DYO/Sans_16/pdf_to_json_test_Latn.DYO_Sans_16.json" 2>&1
Latn.DYO_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.DYO/Sans_8/pdf_to_json_test_Latn.DYO_Sans_8.py" > "data/multilingual/Latn.DYO/Sans_8/pdf_to_json_test_Latn.DYO_Sans_8.json" 2>&1
Latn.DYO_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.DYO/Serif_12/pdf_to_json_test_Latn.DYO_Serif_12.py" > "data/multilingual/Latn.DYO/Serif_12/pdf_to_json_test_Latn.DYO_Serif_12.json" 2>&1
Latn.DYO_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.DYO/Serif_16/pdf_to_json_test_Latn.DYO_Serif_16.py" > "data/multilingual/Latn.DYO/Serif_16/pdf_to_json_test_Latn.DYO_Serif_16.json" 2>&1
Latn.DYO_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.DYO/Serif_8/pdf_to_json_test_Latn.DYO_Serif_8.py" > "data/multilingual/Latn.DYO/Serif_8/pdf_to_json_test_Latn.DYO_Serif_8.json" 2>&1
Latn.DYO_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.DYO/Sun-ExtA_12/pdf_to_json_test_Latn.DYO_Sun-ExtA_12.py" > "data/multilingual/Latn.DYO/Sun-ExtA_12/pdf_to_json_test_Latn.DYO_Sun-ExtA_12.json" 2>&1
Latn.DYO_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.DYO/Sun-ExtA_16/pdf_to_json_test_Latn.DYO_Sun-ExtA_16.py" > "data/multilingual/Latn.DYO/Sun-ExtA_16/pdf_to_json_test_Latn.DYO_Sun-ExtA_16.json" 2>&1
Latn.DYO_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.DYO/Sun-ExtA_8/pdf_to_json_test_Latn.DYO_Sun-ExtA_8.py" > "data/multilingual/Latn.DYO/Sun-ExtA_8/pdf_to_json_test_Latn.DYO_Sun-ExtA_8.json" 2>&1


Latn.DYO_all : Latn.DYO_Mono_12 Latn.DYO_Mono_16 Latn.DYO_Mono_8 Latn.DYO_Sans_12 Latn.DYO_Sans_16 Latn.DYO_Sans_8 Latn.DYO_Serif_12 Latn.DYO_Serif_16 Latn.DYO_Serif_8 Latn.DYO_Sun-ExtA_12 Latn.DYO_Sun-ExtA_16 Latn.DYO_Sun-ExtA_8
