PYTHON=python3


Latn.HEA_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.HEA/Mono_12/pdf_to_json_test_Latn.HEA_Mono_12.py" > "data/multilingual/Latn.HEA/Mono_12/pdf_to_json_test_Latn.HEA_Mono_12.json" 2>&1
Latn.HEA_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.HEA/Mono_16/pdf_to_json_test_Latn.HEA_Mono_16.py" > "data/multilingual/Latn.HEA/Mono_16/pdf_to_json_test_Latn.HEA_Mono_16.json" 2>&1
Latn.HEA_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.HEA/Mono_8/pdf_to_json_test_Latn.HEA_Mono_8.py" > "data/multilingual/Latn.HEA/Mono_8/pdf_to_json_test_Latn.HEA_Mono_8.json" 2>&1
Latn.HEA_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.HEA/Sans_12/pdf_to_json_test_Latn.HEA_Sans_12.py" > "data/multilingual/Latn.HEA/Sans_12/pdf_to_json_test_Latn.HEA_Sans_12.json" 2>&1
Latn.HEA_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.HEA/Sans_16/pdf_to_json_test_Latn.HEA_Sans_16.py" > "data/multilingual/Latn.HEA/Sans_16/pdf_to_json_test_Latn.HEA_Sans_16.json" 2>&1
Latn.HEA_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.HEA/Sans_8/pdf_to_json_test_Latn.HEA_Sans_8.py" > "data/multilingual/Latn.HEA/Sans_8/pdf_to_json_test_Latn.HEA_Sans_8.json" 2>&1
Latn.HEA_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.HEA/Serif_12/pdf_to_json_test_Latn.HEA_Serif_12.py" > "data/multilingual/Latn.HEA/Serif_12/pdf_to_json_test_Latn.HEA_Serif_12.json" 2>&1
Latn.HEA_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.HEA/Serif_16/pdf_to_json_test_Latn.HEA_Serif_16.py" > "data/multilingual/Latn.HEA/Serif_16/pdf_to_json_test_Latn.HEA_Serif_16.json" 2>&1
Latn.HEA_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.HEA/Serif_8/pdf_to_json_test_Latn.HEA_Serif_8.py" > "data/multilingual/Latn.HEA/Serif_8/pdf_to_json_test_Latn.HEA_Serif_8.json" 2>&1
Latn.HEA_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.HEA/Sun-ExtA_12/pdf_to_json_test_Latn.HEA_Sun-ExtA_12.py" > "data/multilingual/Latn.HEA/Sun-ExtA_12/pdf_to_json_test_Latn.HEA_Sun-ExtA_12.json" 2>&1
Latn.HEA_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.HEA/Sun-ExtA_16/pdf_to_json_test_Latn.HEA_Sun-ExtA_16.py" > "data/multilingual/Latn.HEA/Sun-ExtA_16/pdf_to_json_test_Latn.HEA_Sun-ExtA_16.json" 2>&1
Latn.HEA_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.HEA/Sun-ExtA_8/pdf_to_json_test_Latn.HEA_Sun-ExtA_8.py" > "data/multilingual/Latn.HEA/Sun-ExtA_8/pdf_to_json_test_Latn.HEA_Sun-ExtA_8.json" 2>&1


Latn.HEA_all : Latn.HEA_Mono_12 Latn.HEA_Mono_16 Latn.HEA_Mono_8 Latn.HEA_Sans_12 Latn.HEA_Sans_16 Latn.HEA_Sans_8 Latn.HEA_Serif_12 Latn.HEA_Serif_16 Latn.HEA_Serif_8 Latn.HEA_Sun-ExtA_12 Latn.HEA_Sun-ExtA_16 Latn.HEA_Sun-ExtA_8
