PYTHON=python3


Latn.ZRO_Mono_12:
	-$(PYTHON) data/multilingual/Latn.ZRO/Mono_12/pdf_to_json_test_Latn.ZRO_Mono_12.py > data/multilingual/Latn.ZRO/Mono_12/pdf_to_json_test_Latn.ZRO_Mono_12.json 2>&1
Latn.ZRO_Mono_16:
	-$(PYTHON) data/multilingual/Latn.ZRO/Mono_16/pdf_to_json_test_Latn.ZRO_Mono_16.py > data/multilingual/Latn.ZRO/Mono_16/pdf_to_json_test_Latn.ZRO_Mono_16.json 2>&1
Latn.ZRO_Mono_8:
	-$(PYTHON) data/multilingual/Latn.ZRO/Mono_8/pdf_to_json_test_Latn.ZRO_Mono_8.py > data/multilingual/Latn.ZRO/Mono_8/pdf_to_json_test_Latn.ZRO_Mono_8.json 2>&1
Latn.ZRO_Sans_12:
	-$(PYTHON) data/multilingual/Latn.ZRO/Sans_12/pdf_to_json_test_Latn.ZRO_Sans_12.py > data/multilingual/Latn.ZRO/Sans_12/pdf_to_json_test_Latn.ZRO_Sans_12.json 2>&1
Latn.ZRO_Sans_16:
	-$(PYTHON) data/multilingual/Latn.ZRO/Sans_16/pdf_to_json_test_Latn.ZRO_Sans_16.py > data/multilingual/Latn.ZRO/Sans_16/pdf_to_json_test_Latn.ZRO_Sans_16.json 2>&1
Latn.ZRO_Sans_8:
	-$(PYTHON) data/multilingual/Latn.ZRO/Sans_8/pdf_to_json_test_Latn.ZRO_Sans_8.py > data/multilingual/Latn.ZRO/Sans_8/pdf_to_json_test_Latn.ZRO_Sans_8.json 2>&1
Latn.ZRO_Serif_12:
	-$(PYTHON) data/multilingual/Latn.ZRO/Serif_12/pdf_to_json_test_Latn.ZRO_Serif_12.py > data/multilingual/Latn.ZRO/Serif_12/pdf_to_json_test_Latn.ZRO_Serif_12.json 2>&1
Latn.ZRO_Serif_16:
	-$(PYTHON) data/multilingual/Latn.ZRO/Serif_16/pdf_to_json_test_Latn.ZRO_Serif_16.py > data/multilingual/Latn.ZRO/Serif_16/pdf_to_json_test_Latn.ZRO_Serif_16.json 2>&1
Latn.ZRO_Serif_8:
	-$(PYTHON) data/multilingual/Latn.ZRO/Serif_8/pdf_to_json_test_Latn.ZRO_Serif_8.py > data/multilingual/Latn.ZRO/Serif_8/pdf_to_json_test_Latn.ZRO_Serif_8.json 2>&1
Latn.ZRO_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.ZRO/Sun-ExtA_12/pdf_to_json_test_Latn.ZRO_Sun-ExtA_12.py > data/multilingual/Latn.ZRO/Sun-ExtA_12/pdf_to_json_test_Latn.ZRO_Sun-ExtA_12.json 2>&1
Latn.ZRO_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.ZRO/Sun-ExtA_16/pdf_to_json_test_Latn.ZRO_Sun-ExtA_16.py > data/multilingual/Latn.ZRO/Sun-ExtA_16/pdf_to_json_test_Latn.ZRO_Sun-ExtA_16.json 2>&1
Latn.ZRO_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.ZRO/Sun-ExtA_8/pdf_to_json_test_Latn.ZRO_Sun-ExtA_8.py > data/multilingual/Latn.ZRO/Sun-ExtA_8/pdf_to_json_test_Latn.ZRO_Sun-ExtA_8.json 2>&1


Latn.ZRO_all : Latn.ZRO_Mono_12 Latn.ZRO_Mono_16 Latn.ZRO_Mono_8 Latn.ZRO_Sans_12 Latn.ZRO_Sans_16 Latn.ZRO_Sans_8 Latn.ZRO_Serif_12 Latn.ZRO_Serif_16 Latn.ZRO_Serif_8 Latn.ZRO_Sun-ExtA_12 Latn.ZRO_Sun-ExtA_16 Latn.ZRO_Sun-ExtA_8
