PYTHON=python3


Latn.KNG_Mono_12:
	-$(PYTHON) data/multilingual/Latn.KNG/Mono_12/pdf_to_json_test_Latn.KNG_Mono_12.py > data/multilingual/Latn.KNG/Mono_12/pdf_to_json_test_Latn.KNG_Mono_12.json 2>&1
Latn.KNG_Mono_16:
	-$(PYTHON) data/multilingual/Latn.KNG/Mono_16/pdf_to_json_test_Latn.KNG_Mono_16.py > data/multilingual/Latn.KNG/Mono_16/pdf_to_json_test_Latn.KNG_Mono_16.json 2>&1
Latn.KNG_Mono_8:
	-$(PYTHON) data/multilingual/Latn.KNG/Mono_8/pdf_to_json_test_Latn.KNG_Mono_8.py > data/multilingual/Latn.KNG/Mono_8/pdf_to_json_test_Latn.KNG_Mono_8.json 2>&1
Latn.KNG_Sans_12:
	-$(PYTHON) data/multilingual/Latn.KNG/Sans_12/pdf_to_json_test_Latn.KNG_Sans_12.py > data/multilingual/Latn.KNG/Sans_12/pdf_to_json_test_Latn.KNG_Sans_12.json 2>&1
Latn.KNG_Sans_16:
	-$(PYTHON) data/multilingual/Latn.KNG/Sans_16/pdf_to_json_test_Latn.KNG_Sans_16.py > data/multilingual/Latn.KNG/Sans_16/pdf_to_json_test_Latn.KNG_Sans_16.json 2>&1
Latn.KNG_Sans_8:
	-$(PYTHON) data/multilingual/Latn.KNG/Sans_8/pdf_to_json_test_Latn.KNG_Sans_8.py > data/multilingual/Latn.KNG/Sans_8/pdf_to_json_test_Latn.KNG_Sans_8.json 2>&1
Latn.KNG_Serif_12:
	-$(PYTHON) data/multilingual/Latn.KNG/Serif_12/pdf_to_json_test_Latn.KNG_Serif_12.py > data/multilingual/Latn.KNG/Serif_12/pdf_to_json_test_Latn.KNG_Serif_12.json 2>&1
Latn.KNG_Serif_16:
	-$(PYTHON) data/multilingual/Latn.KNG/Serif_16/pdf_to_json_test_Latn.KNG_Serif_16.py > data/multilingual/Latn.KNG/Serif_16/pdf_to_json_test_Latn.KNG_Serif_16.json 2>&1
Latn.KNG_Serif_8:
	-$(PYTHON) data/multilingual/Latn.KNG/Serif_8/pdf_to_json_test_Latn.KNG_Serif_8.py > data/multilingual/Latn.KNG/Serif_8/pdf_to_json_test_Latn.KNG_Serif_8.json 2>&1
Latn.KNG_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.KNG/Sun-ExtA_12/pdf_to_json_test_Latn.KNG_Sun-ExtA_12.py > data/multilingual/Latn.KNG/Sun-ExtA_12/pdf_to_json_test_Latn.KNG_Sun-ExtA_12.json 2>&1
Latn.KNG_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.KNG/Sun-ExtA_16/pdf_to_json_test_Latn.KNG_Sun-ExtA_16.py > data/multilingual/Latn.KNG/Sun-ExtA_16/pdf_to_json_test_Latn.KNG_Sun-ExtA_16.json 2>&1
Latn.KNG_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.KNG/Sun-ExtA_8/pdf_to_json_test_Latn.KNG_Sun-ExtA_8.py > data/multilingual/Latn.KNG/Sun-ExtA_8/pdf_to_json_test_Latn.KNG_Sun-ExtA_8.json 2>&1


Latn.KNG_all : Latn.KNG_Mono_12 Latn.KNG_Mono_16 Latn.KNG_Mono_8 Latn.KNG_Sans_12 Latn.KNG_Sans_16 Latn.KNG_Sans_8 Latn.KNG_Serif_12 Latn.KNG_Serif_16 Latn.KNG_Serif_8 Latn.KNG_Sun-ExtA_12 Latn.KNG_Sun-ExtA_16 Latn.KNG_Sun-ExtA_8
