PYTHON=python3


Latn.TLY_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.TLY/Mono_12/pdf_to_json_test_Latn.TLY_Mono_12.py" > "data/multilingual/Latn.TLY/Mono_12/pdf_to_json_test_Latn.TLY_Mono_12.json" 2>&1
Latn.TLY_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.TLY/Mono_16/pdf_to_json_test_Latn.TLY_Mono_16.py" > "data/multilingual/Latn.TLY/Mono_16/pdf_to_json_test_Latn.TLY_Mono_16.json" 2>&1
Latn.TLY_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.TLY/Mono_8/pdf_to_json_test_Latn.TLY_Mono_8.py" > "data/multilingual/Latn.TLY/Mono_8/pdf_to_json_test_Latn.TLY_Mono_8.json" 2>&1
Latn.TLY_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.TLY/Sans_12/pdf_to_json_test_Latn.TLY_Sans_12.py" > "data/multilingual/Latn.TLY/Sans_12/pdf_to_json_test_Latn.TLY_Sans_12.json" 2>&1
Latn.TLY_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.TLY/Sans_16/pdf_to_json_test_Latn.TLY_Sans_16.py" > "data/multilingual/Latn.TLY/Sans_16/pdf_to_json_test_Latn.TLY_Sans_16.json" 2>&1
Latn.TLY_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.TLY/Sans_8/pdf_to_json_test_Latn.TLY_Sans_8.py" > "data/multilingual/Latn.TLY/Sans_8/pdf_to_json_test_Latn.TLY_Sans_8.json" 2>&1
Latn.TLY_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.TLY/Serif_12/pdf_to_json_test_Latn.TLY_Serif_12.py" > "data/multilingual/Latn.TLY/Serif_12/pdf_to_json_test_Latn.TLY_Serif_12.json" 2>&1
Latn.TLY_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.TLY/Serif_16/pdf_to_json_test_Latn.TLY_Serif_16.py" > "data/multilingual/Latn.TLY/Serif_16/pdf_to_json_test_Latn.TLY_Serif_16.json" 2>&1
Latn.TLY_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.TLY/Serif_8/pdf_to_json_test_Latn.TLY_Serif_8.py" > "data/multilingual/Latn.TLY/Serif_8/pdf_to_json_test_Latn.TLY_Serif_8.json" 2>&1
Latn.TLY_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.TLY/Sun-ExtA_12/pdf_to_json_test_Latn.TLY_Sun-ExtA_12.py" > "data/multilingual/Latn.TLY/Sun-ExtA_12/pdf_to_json_test_Latn.TLY_Sun-ExtA_12.json" 2>&1
Latn.TLY_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.TLY/Sun-ExtA_16/pdf_to_json_test_Latn.TLY_Sun-ExtA_16.py" > "data/multilingual/Latn.TLY/Sun-ExtA_16/pdf_to_json_test_Latn.TLY_Sun-ExtA_16.json" 2>&1
Latn.TLY_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.TLY/Sun-ExtA_8/pdf_to_json_test_Latn.TLY_Sun-ExtA_8.py" > "data/multilingual/Latn.TLY/Sun-ExtA_8/pdf_to_json_test_Latn.TLY_Sun-ExtA_8.json" 2>&1


Latn.TLY_all : Latn.TLY_Mono_12 Latn.TLY_Mono_16 Latn.TLY_Mono_8 Latn.TLY_Sans_12 Latn.TLY_Sans_16 Latn.TLY_Sans_8 Latn.TLY_Serif_12 Latn.TLY_Serif_16 Latn.TLY_Serif_8 Latn.TLY_Sun-ExtA_12 Latn.TLY_Sun-ExtA_16 Latn.TLY_Sun-ExtA_8
