PYTHON=python3


Latn.AZJ_Mono_12:
	-$(PYTHON) data/multilingual/Latn.AZJ/Mono_12/pdf_to_json_test_Latn.AZJ_Mono_12.py > data/multilingual/Latn.AZJ/Mono_12/pdf_to_json_test_Latn.AZJ_Mono_12.json 2>&1
Latn.AZJ_Mono_16:
	-$(PYTHON) data/multilingual/Latn.AZJ/Mono_16/pdf_to_json_test_Latn.AZJ_Mono_16.py > data/multilingual/Latn.AZJ/Mono_16/pdf_to_json_test_Latn.AZJ_Mono_16.json 2>&1
Latn.AZJ_Mono_8:
	-$(PYTHON) data/multilingual/Latn.AZJ/Mono_8/pdf_to_json_test_Latn.AZJ_Mono_8.py > data/multilingual/Latn.AZJ/Mono_8/pdf_to_json_test_Latn.AZJ_Mono_8.json 2>&1
Latn.AZJ_Sans_12:
	-$(PYTHON) data/multilingual/Latn.AZJ/Sans_12/pdf_to_json_test_Latn.AZJ_Sans_12.py > data/multilingual/Latn.AZJ/Sans_12/pdf_to_json_test_Latn.AZJ_Sans_12.json 2>&1
Latn.AZJ_Sans_16:
	-$(PYTHON) data/multilingual/Latn.AZJ/Sans_16/pdf_to_json_test_Latn.AZJ_Sans_16.py > data/multilingual/Latn.AZJ/Sans_16/pdf_to_json_test_Latn.AZJ_Sans_16.json 2>&1
Latn.AZJ_Sans_8:
	-$(PYTHON) data/multilingual/Latn.AZJ/Sans_8/pdf_to_json_test_Latn.AZJ_Sans_8.py > data/multilingual/Latn.AZJ/Sans_8/pdf_to_json_test_Latn.AZJ_Sans_8.json 2>&1
Latn.AZJ_Serif_12:
	-$(PYTHON) data/multilingual/Latn.AZJ/Serif_12/pdf_to_json_test_Latn.AZJ_Serif_12.py > data/multilingual/Latn.AZJ/Serif_12/pdf_to_json_test_Latn.AZJ_Serif_12.json 2>&1
Latn.AZJ_Serif_16:
	-$(PYTHON) data/multilingual/Latn.AZJ/Serif_16/pdf_to_json_test_Latn.AZJ_Serif_16.py > data/multilingual/Latn.AZJ/Serif_16/pdf_to_json_test_Latn.AZJ_Serif_16.json 2>&1
Latn.AZJ_Serif_8:
	-$(PYTHON) data/multilingual/Latn.AZJ/Serif_8/pdf_to_json_test_Latn.AZJ_Serif_8.py > data/multilingual/Latn.AZJ/Serif_8/pdf_to_json_test_Latn.AZJ_Serif_8.json 2>&1
Latn.AZJ_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.AZJ/Sun-ExtA_12/pdf_to_json_test_Latn.AZJ_Sun-ExtA_12.py > data/multilingual/Latn.AZJ/Sun-ExtA_12/pdf_to_json_test_Latn.AZJ_Sun-ExtA_12.json 2>&1
Latn.AZJ_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.AZJ/Sun-ExtA_16/pdf_to_json_test_Latn.AZJ_Sun-ExtA_16.py > data/multilingual/Latn.AZJ/Sun-ExtA_16/pdf_to_json_test_Latn.AZJ_Sun-ExtA_16.json 2>&1
Latn.AZJ_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.AZJ/Sun-ExtA_8/pdf_to_json_test_Latn.AZJ_Sun-ExtA_8.py > data/multilingual/Latn.AZJ/Sun-ExtA_8/pdf_to_json_test_Latn.AZJ_Sun-ExtA_8.json 2>&1


Latn.AZJ_all : Latn.AZJ_Mono_12 Latn.AZJ_Mono_16 Latn.AZJ_Mono_8 Latn.AZJ_Sans_12 Latn.AZJ_Sans_16 Latn.AZJ_Sans_8 Latn.AZJ_Serif_12 Latn.AZJ_Serif_16 Latn.AZJ_Serif_8 Latn.AZJ_Sun-ExtA_12 Latn.AZJ_Sun-ExtA_16 Latn.AZJ_Sun-ExtA_8
