PYTHON=python3


Cyrl.KAZ_Mono_12:
	-$(PYTHON) data/multilingual/Cyrl.KAZ/Mono_12/pdf_to_json_test_Cyrl.KAZ_Mono_12.py > data/multilingual/Cyrl.KAZ/Mono_12/pdf_to_json_test_Cyrl.KAZ_Mono_12.json 2>&1
Cyrl.KAZ_Mono_16:
	-$(PYTHON) data/multilingual/Cyrl.KAZ/Mono_16/pdf_to_json_test_Cyrl.KAZ_Mono_16.py > data/multilingual/Cyrl.KAZ/Mono_16/pdf_to_json_test_Cyrl.KAZ_Mono_16.json 2>&1
Cyrl.KAZ_Mono_8:
	-$(PYTHON) data/multilingual/Cyrl.KAZ/Mono_8/pdf_to_json_test_Cyrl.KAZ_Mono_8.py > data/multilingual/Cyrl.KAZ/Mono_8/pdf_to_json_test_Cyrl.KAZ_Mono_8.json 2>&1
Cyrl.KAZ_Sans_12:
	-$(PYTHON) data/multilingual/Cyrl.KAZ/Sans_12/pdf_to_json_test_Cyrl.KAZ_Sans_12.py > data/multilingual/Cyrl.KAZ/Sans_12/pdf_to_json_test_Cyrl.KAZ_Sans_12.json 2>&1
Cyrl.KAZ_Sans_16:
	-$(PYTHON) data/multilingual/Cyrl.KAZ/Sans_16/pdf_to_json_test_Cyrl.KAZ_Sans_16.py > data/multilingual/Cyrl.KAZ/Sans_16/pdf_to_json_test_Cyrl.KAZ_Sans_16.json 2>&1
Cyrl.KAZ_Sans_8:
	-$(PYTHON) data/multilingual/Cyrl.KAZ/Sans_8/pdf_to_json_test_Cyrl.KAZ_Sans_8.py > data/multilingual/Cyrl.KAZ/Sans_8/pdf_to_json_test_Cyrl.KAZ_Sans_8.json 2>&1
Cyrl.KAZ_Serif_12:
	-$(PYTHON) data/multilingual/Cyrl.KAZ/Serif_12/pdf_to_json_test_Cyrl.KAZ_Serif_12.py > data/multilingual/Cyrl.KAZ/Serif_12/pdf_to_json_test_Cyrl.KAZ_Serif_12.json 2>&1
Cyrl.KAZ_Serif_16:
	-$(PYTHON) data/multilingual/Cyrl.KAZ/Serif_16/pdf_to_json_test_Cyrl.KAZ_Serif_16.py > data/multilingual/Cyrl.KAZ/Serif_16/pdf_to_json_test_Cyrl.KAZ_Serif_16.json 2>&1
Cyrl.KAZ_Serif_8:
	-$(PYTHON) data/multilingual/Cyrl.KAZ/Serif_8/pdf_to_json_test_Cyrl.KAZ_Serif_8.py > data/multilingual/Cyrl.KAZ/Serif_8/pdf_to_json_test_Cyrl.KAZ_Serif_8.json 2>&1
Cyrl.KAZ_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Cyrl.KAZ/Sun-ExtA_12/pdf_to_json_test_Cyrl.KAZ_Sun-ExtA_12.py > data/multilingual/Cyrl.KAZ/Sun-ExtA_12/pdf_to_json_test_Cyrl.KAZ_Sun-ExtA_12.json 2>&1
Cyrl.KAZ_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Cyrl.KAZ/Sun-ExtA_16/pdf_to_json_test_Cyrl.KAZ_Sun-ExtA_16.py > data/multilingual/Cyrl.KAZ/Sun-ExtA_16/pdf_to_json_test_Cyrl.KAZ_Sun-ExtA_16.json 2>&1
Cyrl.KAZ_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Cyrl.KAZ/Sun-ExtA_8/pdf_to_json_test_Cyrl.KAZ_Sun-ExtA_8.py > data/multilingual/Cyrl.KAZ/Sun-ExtA_8/pdf_to_json_test_Cyrl.KAZ_Sun-ExtA_8.json 2>&1


Cyrl.KAZ_all : Cyrl.KAZ_Mono_12 Cyrl.KAZ_Mono_16 Cyrl.KAZ_Mono_8 Cyrl.KAZ_Sans_12 Cyrl.KAZ_Sans_16 Cyrl.KAZ_Sans_8 Cyrl.KAZ_Serif_12 Cyrl.KAZ_Serif_16 Cyrl.KAZ_Serif_8 Cyrl.KAZ_Sun-ExtA_12 Cyrl.KAZ_Sun-ExtA_16 Cyrl.KAZ_Sun-ExtA_8
