PYTHON=python3


Latn.KEA_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.KEA/Mono_12/pdf_to_json_test_Latn.KEA_Mono_12.py" > "data/multilingual/Latn.KEA/Mono_12/pdf_to_json_test_Latn.KEA_Mono_12.json" 2>&1
Latn.KEA_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.KEA/Mono_16/pdf_to_json_test_Latn.KEA_Mono_16.py" > "data/multilingual/Latn.KEA/Mono_16/pdf_to_json_test_Latn.KEA_Mono_16.json" 2>&1
Latn.KEA_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.KEA/Mono_8/pdf_to_json_test_Latn.KEA_Mono_8.py" > "data/multilingual/Latn.KEA/Mono_8/pdf_to_json_test_Latn.KEA_Mono_8.json" 2>&1
Latn.KEA_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.KEA/Sans_12/pdf_to_json_test_Latn.KEA_Sans_12.py" > "data/multilingual/Latn.KEA/Sans_12/pdf_to_json_test_Latn.KEA_Sans_12.json" 2>&1
Latn.KEA_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.KEA/Sans_16/pdf_to_json_test_Latn.KEA_Sans_16.py" > "data/multilingual/Latn.KEA/Sans_16/pdf_to_json_test_Latn.KEA_Sans_16.json" 2>&1
Latn.KEA_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.KEA/Sans_8/pdf_to_json_test_Latn.KEA_Sans_8.py" > "data/multilingual/Latn.KEA/Sans_8/pdf_to_json_test_Latn.KEA_Sans_8.json" 2>&1
Latn.KEA_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.KEA/Serif_12/pdf_to_json_test_Latn.KEA_Serif_12.py" > "data/multilingual/Latn.KEA/Serif_12/pdf_to_json_test_Latn.KEA_Serif_12.json" 2>&1
Latn.KEA_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.KEA/Serif_16/pdf_to_json_test_Latn.KEA_Serif_16.py" > "data/multilingual/Latn.KEA/Serif_16/pdf_to_json_test_Latn.KEA_Serif_16.json" 2>&1
Latn.KEA_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.KEA/Serif_8/pdf_to_json_test_Latn.KEA_Serif_8.py" > "data/multilingual/Latn.KEA/Serif_8/pdf_to_json_test_Latn.KEA_Serif_8.json" 2>&1
Latn.KEA_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.KEA/Sun-ExtA_12/pdf_to_json_test_Latn.KEA_Sun-ExtA_12.py" > "data/multilingual/Latn.KEA/Sun-ExtA_12/pdf_to_json_test_Latn.KEA_Sun-ExtA_12.json" 2>&1
Latn.KEA_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.KEA/Sun-ExtA_16/pdf_to_json_test_Latn.KEA_Sun-ExtA_16.py" > "data/multilingual/Latn.KEA/Sun-ExtA_16/pdf_to_json_test_Latn.KEA_Sun-ExtA_16.json" 2>&1
Latn.KEA_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.KEA/Sun-ExtA_8/pdf_to_json_test_Latn.KEA_Sun-ExtA_8.py" > "data/multilingual/Latn.KEA/Sun-ExtA_8/pdf_to_json_test_Latn.KEA_Sun-ExtA_8.json" 2>&1


Latn.KEA_all : Latn.KEA_Mono_12 Latn.KEA_Mono_16 Latn.KEA_Mono_8 Latn.KEA_Sans_12 Latn.KEA_Sans_16 Latn.KEA_Sans_8 Latn.KEA_Serif_12 Latn.KEA_Serif_16 Latn.KEA_Serif_8 Latn.KEA_Sun-ExtA_12 Latn.KEA_Sun-ExtA_16 Latn.KEA_Sun-ExtA_8
