PYTHON=python3


Latn.QVH_Mono_12:
	-$(PYTHON) data/multilingual/Latn.QVH/Mono_12/pdf_to_json_test_Latn.QVH_Mono_12.py > data/multilingual/Latn.QVH/Mono_12/pdf_to_json_test_Latn.QVH_Mono_12.json 2>&1
Latn.QVH_Mono_16:
	-$(PYTHON) data/multilingual/Latn.QVH/Mono_16/pdf_to_json_test_Latn.QVH_Mono_16.py > data/multilingual/Latn.QVH/Mono_16/pdf_to_json_test_Latn.QVH_Mono_16.json 2>&1
Latn.QVH_Mono_8:
	-$(PYTHON) data/multilingual/Latn.QVH/Mono_8/pdf_to_json_test_Latn.QVH_Mono_8.py > data/multilingual/Latn.QVH/Mono_8/pdf_to_json_test_Latn.QVH_Mono_8.json 2>&1
Latn.QVH_Sans_12:
	-$(PYTHON) data/multilingual/Latn.QVH/Sans_12/pdf_to_json_test_Latn.QVH_Sans_12.py > data/multilingual/Latn.QVH/Sans_12/pdf_to_json_test_Latn.QVH_Sans_12.json 2>&1
Latn.QVH_Sans_16:
	-$(PYTHON) data/multilingual/Latn.QVH/Sans_16/pdf_to_json_test_Latn.QVH_Sans_16.py > data/multilingual/Latn.QVH/Sans_16/pdf_to_json_test_Latn.QVH_Sans_16.json 2>&1
Latn.QVH_Sans_8:
	-$(PYTHON) data/multilingual/Latn.QVH/Sans_8/pdf_to_json_test_Latn.QVH_Sans_8.py > data/multilingual/Latn.QVH/Sans_8/pdf_to_json_test_Latn.QVH_Sans_8.json 2>&1
Latn.QVH_Serif_12:
	-$(PYTHON) data/multilingual/Latn.QVH/Serif_12/pdf_to_json_test_Latn.QVH_Serif_12.py > data/multilingual/Latn.QVH/Serif_12/pdf_to_json_test_Latn.QVH_Serif_12.json 2>&1
Latn.QVH_Serif_16:
	-$(PYTHON) data/multilingual/Latn.QVH/Serif_16/pdf_to_json_test_Latn.QVH_Serif_16.py > data/multilingual/Latn.QVH/Serif_16/pdf_to_json_test_Latn.QVH_Serif_16.json 2>&1
Latn.QVH_Serif_8:
	-$(PYTHON) data/multilingual/Latn.QVH/Serif_8/pdf_to_json_test_Latn.QVH_Serif_8.py > data/multilingual/Latn.QVH/Serif_8/pdf_to_json_test_Latn.QVH_Serif_8.json 2>&1
Latn.QVH_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.QVH/Sun-ExtA_12/pdf_to_json_test_Latn.QVH_Sun-ExtA_12.py > data/multilingual/Latn.QVH/Sun-ExtA_12/pdf_to_json_test_Latn.QVH_Sun-ExtA_12.json 2>&1
Latn.QVH_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.QVH/Sun-ExtA_16/pdf_to_json_test_Latn.QVH_Sun-ExtA_16.py > data/multilingual/Latn.QVH/Sun-ExtA_16/pdf_to_json_test_Latn.QVH_Sun-ExtA_16.json 2>&1
Latn.QVH_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.QVH/Sun-ExtA_8/pdf_to_json_test_Latn.QVH_Sun-ExtA_8.py > data/multilingual/Latn.QVH/Sun-ExtA_8/pdf_to_json_test_Latn.QVH_Sun-ExtA_8.json 2>&1


Latn.QVH_all : Latn.QVH_Mono_12 Latn.QVH_Mono_16 Latn.QVH_Mono_8 Latn.QVH_Sans_12 Latn.QVH_Sans_16 Latn.QVH_Sans_8 Latn.QVH_Serif_12 Latn.QVH_Serif_16 Latn.QVH_Serif_8 Latn.QVH_Sun-ExtA_12 Latn.QVH_Sun-ExtA_16 Latn.QVH_Sun-ExtA_8
