PYTHON=python3


Latn.BIN_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.BIN/Mono_12/pdf_to_json_test_Latn.BIN_Mono_12.py" > "data/multilingual/Latn.BIN/Mono_12/pdf_to_json_test_Latn.BIN_Mono_12.json" 2>&1
Latn.BIN_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.BIN/Mono_16/pdf_to_json_test_Latn.BIN_Mono_16.py" > "data/multilingual/Latn.BIN/Mono_16/pdf_to_json_test_Latn.BIN_Mono_16.json" 2>&1
Latn.BIN_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.BIN/Mono_8/pdf_to_json_test_Latn.BIN_Mono_8.py" > "data/multilingual/Latn.BIN/Mono_8/pdf_to_json_test_Latn.BIN_Mono_8.json" 2>&1
Latn.BIN_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.BIN/Sans_12/pdf_to_json_test_Latn.BIN_Sans_12.py" > "data/multilingual/Latn.BIN/Sans_12/pdf_to_json_test_Latn.BIN_Sans_12.json" 2>&1
Latn.BIN_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.BIN/Sans_16/pdf_to_json_test_Latn.BIN_Sans_16.py" > "data/multilingual/Latn.BIN/Sans_16/pdf_to_json_test_Latn.BIN_Sans_16.json" 2>&1
Latn.BIN_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.BIN/Sans_8/pdf_to_json_test_Latn.BIN_Sans_8.py" > "data/multilingual/Latn.BIN/Sans_8/pdf_to_json_test_Latn.BIN_Sans_8.json" 2>&1
Latn.BIN_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.BIN/Serif_12/pdf_to_json_test_Latn.BIN_Serif_12.py" > "data/multilingual/Latn.BIN/Serif_12/pdf_to_json_test_Latn.BIN_Serif_12.json" 2>&1
Latn.BIN_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.BIN/Serif_16/pdf_to_json_test_Latn.BIN_Serif_16.py" > "data/multilingual/Latn.BIN/Serif_16/pdf_to_json_test_Latn.BIN_Serif_16.json" 2>&1
Latn.BIN_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.BIN/Serif_8/pdf_to_json_test_Latn.BIN_Serif_8.py" > "data/multilingual/Latn.BIN/Serif_8/pdf_to_json_test_Latn.BIN_Serif_8.json" 2>&1
Latn.BIN_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.BIN/Sun-ExtA_12/pdf_to_json_test_Latn.BIN_Sun-ExtA_12.py" > "data/multilingual/Latn.BIN/Sun-ExtA_12/pdf_to_json_test_Latn.BIN_Sun-ExtA_12.json" 2>&1
Latn.BIN_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.BIN/Sun-ExtA_16/pdf_to_json_test_Latn.BIN_Sun-ExtA_16.py" > "data/multilingual/Latn.BIN/Sun-ExtA_16/pdf_to_json_test_Latn.BIN_Sun-ExtA_16.json" 2>&1
Latn.BIN_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.BIN/Sun-ExtA_8/pdf_to_json_test_Latn.BIN_Sun-ExtA_8.py" > "data/multilingual/Latn.BIN/Sun-ExtA_8/pdf_to_json_test_Latn.BIN_Sun-ExtA_8.json" 2>&1


Latn.BIN_all : Latn.BIN_Mono_12 Latn.BIN_Mono_16 Latn.BIN_Mono_8 Latn.BIN_Sans_12 Latn.BIN_Sans_16 Latn.BIN_Sans_8 Latn.BIN_Serif_12 Latn.BIN_Serif_16 Latn.BIN_Serif_8 Latn.BIN_Sun-ExtA_12 Latn.BIN_Sun-ExtA_16 Latn.BIN_Sun-ExtA_8
