PYTHON=python3


Latn.SEY_Mono_12:
	-$(PYTHON) data/multilingual/Latn.SEY/Mono_12/pdf_to_json_test_Latn.SEY_Mono_12.py > data/multilingual/Latn.SEY/Mono_12/pdf_to_json_test_Latn.SEY_Mono_12.json 2>&1
Latn.SEY_Mono_16:
	-$(PYTHON) data/multilingual/Latn.SEY/Mono_16/pdf_to_json_test_Latn.SEY_Mono_16.py > data/multilingual/Latn.SEY/Mono_16/pdf_to_json_test_Latn.SEY_Mono_16.json 2>&1
Latn.SEY_Mono_8:
	-$(PYTHON) data/multilingual/Latn.SEY/Mono_8/pdf_to_json_test_Latn.SEY_Mono_8.py > data/multilingual/Latn.SEY/Mono_8/pdf_to_json_test_Latn.SEY_Mono_8.json 2>&1
Latn.SEY_Sans_12:
	-$(PYTHON) data/multilingual/Latn.SEY/Sans_12/pdf_to_json_test_Latn.SEY_Sans_12.py > data/multilingual/Latn.SEY/Sans_12/pdf_to_json_test_Latn.SEY_Sans_12.json 2>&1
Latn.SEY_Sans_16:
	-$(PYTHON) data/multilingual/Latn.SEY/Sans_16/pdf_to_json_test_Latn.SEY_Sans_16.py > data/multilingual/Latn.SEY/Sans_16/pdf_to_json_test_Latn.SEY_Sans_16.json 2>&1
Latn.SEY_Sans_8:
	-$(PYTHON) data/multilingual/Latn.SEY/Sans_8/pdf_to_json_test_Latn.SEY_Sans_8.py > data/multilingual/Latn.SEY/Sans_8/pdf_to_json_test_Latn.SEY_Sans_8.json 2>&1
Latn.SEY_Serif_12:
	-$(PYTHON) data/multilingual/Latn.SEY/Serif_12/pdf_to_json_test_Latn.SEY_Serif_12.py > data/multilingual/Latn.SEY/Serif_12/pdf_to_json_test_Latn.SEY_Serif_12.json 2>&1
Latn.SEY_Serif_16:
	-$(PYTHON) data/multilingual/Latn.SEY/Serif_16/pdf_to_json_test_Latn.SEY_Serif_16.py > data/multilingual/Latn.SEY/Serif_16/pdf_to_json_test_Latn.SEY_Serif_16.json 2>&1
Latn.SEY_Serif_8:
	-$(PYTHON) data/multilingual/Latn.SEY/Serif_8/pdf_to_json_test_Latn.SEY_Serif_8.py > data/multilingual/Latn.SEY/Serif_8/pdf_to_json_test_Latn.SEY_Serif_8.json 2>&1
Latn.SEY_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.SEY/Sun-ExtA_12/pdf_to_json_test_Latn.SEY_Sun-ExtA_12.py > data/multilingual/Latn.SEY/Sun-ExtA_12/pdf_to_json_test_Latn.SEY_Sun-ExtA_12.json 2>&1
Latn.SEY_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.SEY/Sun-ExtA_16/pdf_to_json_test_Latn.SEY_Sun-ExtA_16.py > data/multilingual/Latn.SEY/Sun-ExtA_16/pdf_to_json_test_Latn.SEY_Sun-ExtA_16.json 2>&1
Latn.SEY_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.SEY/Sun-ExtA_8/pdf_to_json_test_Latn.SEY_Sun-ExtA_8.py > data/multilingual/Latn.SEY/Sun-ExtA_8/pdf_to_json_test_Latn.SEY_Sun-ExtA_8.json 2>&1


Latn.SEY_all : Latn.SEY_Mono_12 Latn.SEY_Mono_16 Latn.SEY_Mono_8 Latn.SEY_Sans_12 Latn.SEY_Sans_16 Latn.SEY_Sans_8 Latn.SEY_Serif_12 Latn.SEY_Serif_16 Latn.SEY_Serif_8 Latn.SEY_Sun-ExtA_12 Latn.SEY_Sun-ExtA_16 Latn.SEY_Sun-ExtA_8
