PYTHON=python3


Latn.QVM_Mono_12:
	-$(PYTHON) data/multilingual/Latn.QVM/Mono_12/pdf_to_json_test_Latn.QVM_Mono_12.py > data/multilingual/Latn.QVM/Mono_12/pdf_to_json_test_Latn.QVM_Mono_12.json 2>&1
Latn.QVM_Mono_16:
	-$(PYTHON) data/multilingual/Latn.QVM/Mono_16/pdf_to_json_test_Latn.QVM_Mono_16.py > data/multilingual/Latn.QVM/Mono_16/pdf_to_json_test_Latn.QVM_Mono_16.json 2>&1
Latn.QVM_Mono_8:
	-$(PYTHON) data/multilingual/Latn.QVM/Mono_8/pdf_to_json_test_Latn.QVM_Mono_8.py > data/multilingual/Latn.QVM/Mono_8/pdf_to_json_test_Latn.QVM_Mono_8.json 2>&1
Latn.QVM_Sans_12:
	-$(PYTHON) data/multilingual/Latn.QVM/Sans_12/pdf_to_json_test_Latn.QVM_Sans_12.py > data/multilingual/Latn.QVM/Sans_12/pdf_to_json_test_Latn.QVM_Sans_12.json 2>&1
Latn.QVM_Sans_16:
	-$(PYTHON) data/multilingual/Latn.QVM/Sans_16/pdf_to_json_test_Latn.QVM_Sans_16.py > data/multilingual/Latn.QVM/Sans_16/pdf_to_json_test_Latn.QVM_Sans_16.json 2>&1
Latn.QVM_Sans_8:
	-$(PYTHON) data/multilingual/Latn.QVM/Sans_8/pdf_to_json_test_Latn.QVM_Sans_8.py > data/multilingual/Latn.QVM/Sans_8/pdf_to_json_test_Latn.QVM_Sans_8.json 2>&1
Latn.QVM_Serif_12:
	-$(PYTHON) data/multilingual/Latn.QVM/Serif_12/pdf_to_json_test_Latn.QVM_Serif_12.py > data/multilingual/Latn.QVM/Serif_12/pdf_to_json_test_Latn.QVM_Serif_12.json 2>&1
Latn.QVM_Serif_16:
	-$(PYTHON) data/multilingual/Latn.QVM/Serif_16/pdf_to_json_test_Latn.QVM_Serif_16.py > data/multilingual/Latn.QVM/Serif_16/pdf_to_json_test_Latn.QVM_Serif_16.json 2>&1
Latn.QVM_Serif_8:
	-$(PYTHON) data/multilingual/Latn.QVM/Serif_8/pdf_to_json_test_Latn.QVM_Serif_8.py > data/multilingual/Latn.QVM/Serif_8/pdf_to_json_test_Latn.QVM_Serif_8.json 2>&1
Latn.QVM_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.QVM/Sun-ExtA_12/pdf_to_json_test_Latn.QVM_Sun-ExtA_12.py > data/multilingual/Latn.QVM/Sun-ExtA_12/pdf_to_json_test_Latn.QVM_Sun-ExtA_12.json 2>&1
Latn.QVM_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.QVM/Sun-ExtA_16/pdf_to_json_test_Latn.QVM_Sun-ExtA_16.py > data/multilingual/Latn.QVM/Sun-ExtA_16/pdf_to_json_test_Latn.QVM_Sun-ExtA_16.json 2>&1
Latn.QVM_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.QVM/Sun-ExtA_8/pdf_to_json_test_Latn.QVM_Sun-ExtA_8.py > data/multilingual/Latn.QVM/Sun-ExtA_8/pdf_to_json_test_Latn.QVM_Sun-ExtA_8.json 2>&1


Latn.QVM_all : Latn.QVM_Mono_12 Latn.QVM_Mono_16 Latn.QVM_Mono_8 Latn.QVM_Sans_12 Latn.QVM_Sans_16 Latn.QVM_Sans_8 Latn.QVM_Serif_12 Latn.QVM_Serif_16 Latn.QVM_Serif_8 Latn.QVM_Sun-ExtA_12 Latn.QVM_Sun-ExtA_16 Latn.QVM_Sun-ExtA_8
