PYTHON=python3


Latn.KBP_Mono_12:
	-$(PYTHON) data/multilingual/Latn.KBP/Mono_12/pdf_to_json_test_Latn.KBP_Mono_12.py > data/multilingual/Latn.KBP/Mono_12/pdf_to_json_test_Latn.KBP_Mono_12.json 2>&1
Latn.KBP_Mono_16:
	-$(PYTHON) data/multilingual/Latn.KBP/Mono_16/pdf_to_json_test_Latn.KBP_Mono_16.py > data/multilingual/Latn.KBP/Mono_16/pdf_to_json_test_Latn.KBP_Mono_16.json 2>&1
Latn.KBP_Mono_8:
	-$(PYTHON) data/multilingual/Latn.KBP/Mono_8/pdf_to_json_test_Latn.KBP_Mono_8.py > data/multilingual/Latn.KBP/Mono_8/pdf_to_json_test_Latn.KBP_Mono_8.json 2>&1
Latn.KBP_Sans_12:
	-$(PYTHON) data/multilingual/Latn.KBP/Sans_12/pdf_to_json_test_Latn.KBP_Sans_12.py > data/multilingual/Latn.KBP/Sans_12/pdf_to_json_test_Latn.KBP_Sans_12.json 2>&1
Latn.KBP_Sans_16:
	-$(PYTHON) data/multilingual/Latn.KBP/Sans_16/pdf_to_json_test_Latn.KBP_Sans_16.py > data/multilingual/Latn.KBP/Sans_16/pdf_to_json_test_Latn.KBP_Sans_16.json 2>&1
Latn.KBP_Sans_8:
	-$(PYTHON) data/multilingual/Latn.KBP/Sans_8/pdf_to_json_test_Latn.KBP_Sans_8.py > data/multilingual/Latn.KBP/Sans_8/pdf_to_json_test_Latn.KBP_Sans_8.json 2>&1
Latn.KBP_Serif_12:
	-$(PYTHON) data/multilingual/Latn.KBP/Serif_12/pdf_to_json_test_Latn.KBP_Serif_12.py > data/multilingual/Latn.KBP/Serif_12/pdf_to_json_test_Latn.KBP_Serif_12.json 2>&1
Latn.KBP_Serif_16:
	-$(PYTHON) data/multilingual/Latn.KBP/Serif_16/pdf_to_json_test_Latn.KBP_Serif_16.py > data/multilingual/Latn.KBP/Serif_16/pdf_to_json_test_Latn.KBP_Serif_16.json 2>&1
Latn.KBP_Serif_8:
	-$(PYTHON) data/multilingual/Latn.KBP/Serif_8/pdf_to_json_test_Latn.KBP_Serif_8.py > data/multilingual/Latn.KBP/Serif_8/pdf_to_json_test_Latn.KBP_Serif_8.json 2>&1
Latn.KBP_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.KBP/Sun-ExtA_12/pdf_to_json_test_Latn.KBP_Sun-ExtA_12.py > data/multilingual/Latn.KBP/Sun-ExtA_12/pdf_to_json_test_Latn.KBP_Sun-ExtA_12.json 2>&1
Latn.KBP_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.KBP/Sun-ExtA_16/pdf_to_json_test_Latn.KBP_Sun-ExtA_16.py > data/multilingual/Latn.KBP/Sun-ExtA_16/pdf_to_json_test_Latn.KBP_Sun-ExtA_16.json 2>&1
Latn.KBP_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.KBP/Sun-ExtA_8/pdf_to_json_test_Latn.KBP_Sun-ExtA_8.py > data/multilingual/Latn.KBP/Sun-ExtA_8/pdf_to_json_test_Latn.KBP_Sun-ExtA_8.json 2>&1


Latn.KBP_all : Latn.KBP_Mono_12 Latn.KBP_Mono_16 Latn.KBP_Mono_8 Latn.KBP_Sans_12 Latn.KBP_Sans_16 Latn.KBP_Sans_8 Latn.KBP_Serif_12 Latn.KBP_Serif_16 Latn.KBP_Serif_8 Latn.KBP_Sun-ExtA_12 Latn.KBP_Sun-ExtA_16 Latn.KBP_Sun-ExtA_8
