PYTHON=python3


Latn.MCD_Mono_12:
	-$(PYTHON) data/multilingual/Latn.MCD/Mono_12/pdf_to_json_test_Latn.MCD_Mono_12.py > data/multilingual/Latn.MCD/Mono_12/pdf_to_json_test_Latn.MCD_Mono_12.json 2>&1
Latn.MCD_Mono_16:
	-$(PYTHON) data/multilingual/Latn.MCD/Mono_16/pdf_to_json_test_Latn.MCD_Mono_16.py > data/multilingual/Latn.MCD/Mono_16/pdf_to_json_test_Latn.MCD_Mono_16.json 2>&1
Latn.MCD_Mono_8:
	-$(PYTHON) data/multilingual/Latn.MCD/Mono_8/pdf_to_json_test_Latn.MCD_Mono_8.py > data/multilingual/Latn.MCD/Mono_8/pdf_to_json_test_Latn.MCD_Mono_8.json 2>&1
Latn.MCD_Sans_12:
	-$(PYTHON) data/multilingual/Latn.MCD/Sans_12/pdf_to_json_test_Latn.MCD_Sans_12.py > data/multilingual/Latn.MCD/Sans_12/pdf_to_json_test_Latn.MCD_Sans_12.json 2>&1
Latn.MCD_Sans_16:
	-$(PYTHON) data/multilingual/Latn.MCD/Sans_16/pdf_to_json_test_Latn.MCD_Sans_16.py > data/multilingual/Latn.MCD/Sans_16/pdf_to_json_test_Latn.MCD_Sans_16.json 2>&1
Latn.MCD_Sans_8:
	-$(PYTHON) data/multilingual/Latn.MCD/Sans_8/pdf_to_json_test_Latn.MCD_Sans_8.py > data/multilingual/Latn.MCD/Sans_8/pdf_to_json_test_Latn.MCD_Sans_8.json 2>&1
Latn.MCD_Serif_12:
	-$(PYTHON) data/multilingual/Latn.MCD/Serif_12/pdf_to_json_test_Latn.MCD_Serif_12.py > data/multilingual/Latn.MCD/Serif_12/pdf_to_json_test_Latn.MCD_Serif_12.json 2>&1
Latn.MCD_Serif_16:
	-$(PYTHON) data/multilingual/Latn.MCD/Serif_16/pdf_to_json_test_Latn.MCD_Serif_16.py > data/multilingual/Latn.MCD/Serif_16/pdf_to_json_test_Latn.MCD_Serif_16.json 2>&1
Latn.MCD_Serif_8:
	-$(PYTHON) data/multilingual/Latn.MCD/Serif_8/pdf_to_json_test_Latn.MCD_Serif_8.py > data/multilingual/Latn.MCD/Serif_8/pdf_to_json_test_Latn.MCD_Serif_8.json 2>&1
Latn.MCD_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.MCD/Sun-ExtA_12/pdf_to_json_test_Latn.MCD_Sun-ExtA_12.py > data/multilingual/Latn.MCD/Sun-ExtA_12/pdf_to_json_test_Latn.MCD_Sun-ExtA_12.json 2>&1
Latn.MCD_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.MCD/Sun-ExtA_16/pdf_to_json_test_Latn.MCD_Sun-ExtA_16.py > data/multilingual/Latn.MCD/Sun-ExtA_16/pdf_to_json_test_Latn.MCD_Sun-ExtA_16.json 2>&1
Latn.MCD_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.MCD/Sun-ExtA_8/pdf_to_json_test_Latn.MCD_Sun-ExtA_8.py > data/multilingual/Latn.MCD/Sun-ExtA_8/pdf_to_json_test_Latn.MCD_Sun-ExtA_8.json 2>&1


Latn.MCD_all : Latn.MCD_Mono_12 Latn.MCD_Mono_16 Latn.MCD_Mono_8 Latn.MCD_Sans_12 Latn.MCD_Sans_16 Latn.MCD_Sans_8 Latn.MCD_Serif_12 Latn.MCD_Serif_16 Latn.MCD_Serif_8 Latn.MCD_Sun-ExtA_12 Latn.MCD_Sun-ExtA_16 Latn.MCD_Sun-ExtA_8
