PYTHON=python3


Arab.PNB_Mono_12:
	-$(PYTHON) "data/multilingual/Arab.PNB/Mono_12/pdf_to_json_test_Arab.PNB_Mono_12.py" > "data/multilingual/Arab.PNB/Mono_12/pdf_to_json_test_Arab.PNB_Mono_12.json" 2>&1
Arab.PNB_Mono_16:
	-$(PYTHON) "data/multilingual/Arab.PNB/Mono_16/pdf_to_json_test_Arab.PNB_Mono_16.py" > "data/multilingual/Arab.PNB/Mono_16/pdf_to_json_test_Arab.PNB_Mono_16.json" 2>&1
Arab.PNB_Mono_8:
	-$(PYTHON) "data/multilingual/Arab.PNB/Mono_8/pdf_to_json_test_Arab.PNB_Mono_8.py" > "data/multilingual/Arab.PNB/Mono_8/pdf_to_json_test_Arab.PNB_Mono_8.json" 2>&1
Arab.PNB_Sans_12:
	-$(PYTHON) "data/multilingual/Arab.PNB/Sans_12/pdf_to_json_test_Arab.PNB_Sans_12.py" > "data/multilingual/Arab.PNB/Sans_12/pdf_to_json_test_Arab.PNB_Sans_12.json" 2>&1
Arab.PNB_Sans_16:
	-$(PYTHON) "data/multilingual/Arab.PNB/Sans_16/pdf_to_json_test_Arab.PNB_Sans_16.py" > "data/multilingual/Arab.PNB/Sans_16/pdf_to_json_test_Arab.PNB_Sans_16.json" 2>&1
Arab.PNB_Sans_8:
	-$(PYTHON) "data/multilingual/Arab.PNB/Sans_8/pdf_to_json_test_Arab.PNB_Sans_8.py" > "data/multilingual/Arab.PNB/Sans_8/pdf_to_json_test_Arab.PNB_Sans_8.json" 2>&1
Arab.PNB_Serif_12:
	-$(PYTHON) "data/multilingual/Arab.PNB/Serif_12/pdf_to_json_test_Arab.PNB_Serif_12.py" > "data/multilingual/Arab.PNB/Serif_12/pdf_to_json_test_Arab.PNB_Serif_12.json" 2>&1
Arab.PNB_Serif_16:
	-$(PYTHON) "data/multilingual/Arab.PNB/Serif_16/pdf_to_json_test_Arab.PNB_Serif_16.py" > "data/multilingual/Arab.PNB/Serif_16/pdf_to_json_test_Arab.PNB_Serif_16.json" 2>&1
Arab.PNB_Serif_8:
	-$(PYTHON) "data/multilingual/Arab.PNB/Serif_8/pdf_to_json_test_Arab.PNB_Serif_8.py" > "data/multilingual/Arab.PNB/Serif_8/pdf_to_json_test_Arab.PNB_Serif_8.json" 2>&1
Arab.PNB_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Arab.PNB/Sun-ExtA_12/pdf_to_json_test_Arab.PNB_Sun-ExtA_12.py" > "data/multilingual/Arab.PNB/Sun-ExtA_12/pdf_to_json_test_Arab.PNB_Sun-ExtA_12.json" 2>&1
Arab.PNB_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Arab.PNB/Sun-ExtA_16/pdf_to_json_test_Arab.PNB_Sun-ExtA_16.py" > "data/multilingual/Arab.PNB/Sun-ExtA_16/pdf_to_json_test_Arab.PNB_Sun-ExtA_16.json" 2>&1
Arab.PNB_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Arab.PNB/Sun-ExtA_8/pdf_to_json_test_Arab.PNB_Sun-ExtA_8.py" > "data/multilingual/Arab.PNB/Sun-ExtA_8/pdf_to_json_test_Arab.PNB_Sun-ExtA_8.json" 2>&1


Arab.PNB_all : Arab.PNB_Mono_12 Arab.PNB_Mono_16 Arab.PNB_Mono_8 Arab.PNB_Sans_12 Arab.PNB_Sans_16 Arab.PNB_Sans_8 Arab.PNB_Serif_12 Arab.PNB_Serif_16 Arab.PNB_Serif_8 Arab.PNB_Sun-ExtA_12 Arab.PNB_Sun-ExtA_16 Arab.PNB_Sun-ExtA_8
