PYTHON=python3


Latn.WAR_Mono_12:
	-$(PYTHON) data/multilingual/Latn.WAR/Mono_12/pdf_to_json_test_Latn.WAR_Mono_12.py > data/multilingual/Latn.WAR/Mono_12/pdf_to_json_test_Latn.WAR_Mono_12.json 2>&1
Latn.WAR_Mono_16:
	-$(PYTHON) data/multilingual/Latn.WAR/Mono_16/pdf_to_json_test_Latn.WAR_Mono_16.py > data/multilingual/Latn.WAR/Mono_16/pdf_to_json_test_Latn.WAR_Mono_16.json 2>&1
Latn.WAR_Mono_8:
	-$(PYTHON) data/multilingual/Latn.WAR/Mono_8/pdf_to_json_test_Latn.WAR_Mono_8.py > data/multilingual/Latn.WAR/Mono_8/pdf_to_json_test_Latn.WAR_Mono_8.json 2>&1
Latn.WAR_Sans_12:
	-$(PYTHON) data/multilingual/Latn.WAR/Sans_12/pdf_to_json_test_Latn.WAR_Sans_12.py > data/multilingual/Latn.WAR/Sans_12/pdf_to_json_test_Latn.WAR_Sans_12.json 2>&1
Latn.WAR_Sans_16:
	-$(PYTHON) data/multilingual/Latn.WAR/Sans_16/pdf_to_json_test_Latn.WAR_Sans_16.py > data/multilingual/Latn.WAR/Sans_16/pdf_to_json_test_Latn.WAR_Sans_16.json 2>&1
Latn.WAR_Sans_8:
	-$(PYTHON) data/multilingual/Latn.WAR/Sans_8/pdf_to_json_test_Latn.WAR_Sans_8.py > data/multilingual/Latn.WAR/Sans_8/pdf_to_json_test_Latn.WAR_Sans_8.json 2>&1
Latn.WAR_Serif_12:
	-$(PYTHON) data/multilingual/Latn.WAR/Serif_12/pdf_to_json_test_Latn.WAR_Serif_12.py > data/multilingual/Latn.WAR/Serif_12/pdf_to_json_test_Latn.WAR_Serif_12.json 2>&1
Latn.WAR_Serif_16:
	-$(PYTHON) data/multilingual/Latn.WAR/Serif_16/pdf_to_json_test_Latn.WAR_Serif_16.py > data/multilingual/Latn.WAR/Serif_16/pdf_to_json_test_Latn.WAR_Serif_16.json 2>&1
Latn.WAR_Serif_8:
	-$(PYTHON) data/multilingual/Latn.WAR/Serif_8/pdf_to_json_test_Latn.WAR_Serif_8.py > data/multilingual/Latn.WAR/Serif_8/pdf_to_json_test_Latn.WAR_Serif_8.json 2>&1
Latn.WAR_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.WAR/Sun-ExtA_12/pdf_to_json_test_Latn.WAR_Sun-ExtA_12.py > data/multilingual/Latn.WAR/Sun-ExtA_12/pdf_to_json_test_Latn.WAR_Sun-ExtA_12.json 2>&1
Latn.WAR_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.WAR/Sun-ExtA_16/pdf_to_json_test_Latn.WAR_Sun-ExtA_16.py > data/multilingual/Latn.WAR/Sun-ExtA_16/pdf_to_json_test_Latn.WAR_Sun-ExtA_16.json 2>&1
Latn.WAR_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.WAR/Sun-ExtA_8/pdf_to_json_test_Latn.WAR_Sun-ExtA_8.py > data/multilingual/Latn.WAR/Sun-ExtA_8/pdf_to_json_test_Latn.WAR_Sun-ExtA_8.json 2>&1


Latn.WAR_all : Latn.WAR_Mono_12 Latn.WAR_Mono_16 Latn.WAR_Mono_8 Latn.WAR_Sans_12 Latn.WAR_Sans_16 Latn.WAR_Sans_8 Latn.WAR_Serif_12 Latn.WAR_Serif_16 Latn.WAR_Serif_8 Latn.WAR_Sun-ExtA_12 Latn.WAR_Sun-ExtA_16 Latn.WAR_Sun-ExtA_8
