PYTHON=python3


Latn.GLA_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.GLA/Mono_12/pdf_to_json_test_Latn.GLA_Mono_12.py" > "data/multilingual/Latn.GLA/Mono_12/pdf_to_json_test_Latn.GLA_Mono_12.json" 2>&1
Latn.GLA_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.GLA/Mono_16/pdf_to_json_test_Latn.GLA_Mono_16.py" > "data/multilingual/Latn.GLA/Mono_16/pdf_to_json_test_Latn.GLA_Mono_16.json" 2>&1
Latn.GLA_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.GLA/Mono_8/pdf_to_json_test_Latn.GLA_Mono_8.py" > "data/multilingual/Latn.GLA/Mono_8/pdf_to_json_test_Latn.GLA_Mono_8.json" 2>&1
Latn.GLA_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.GLA/Sans_12/pdf_to_json_test_Latn.GLA_Sans_12.py" > "data/multilingual/Latn.GLA/Sans_12/pdf_to_json_test_Latn.GLA_Sans_12.json" 2>&1
Latn.GLA_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.GLA/Sans_16/pdf_to_json_test_Latn.GLA_Sans_16.py" > "data/multilingual/Latn.GLA/Sans_16/pdf_to_json_test_Latn.GLA_Sans_16.json" 2>&1
Latn.GLA_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.GLA/Sans_8/pdf_to_json_test_Latn.GLA_Sans_8.py" > "data/multilingual/Latn.GLA/Sans_8/pdf_to_json_test_Latn.GLA_Sans_8.json" 2>&1
Latn.GLA_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.GLA/Serif_12/pdf_to_json_test_Latn.GLA_Serif_12.py" > "data/multilingual/Latn.GLA/Serif_12/pdf_to_json_test_Latn.GLA_Serif_12.json" 2>&1
Latn.GLA_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.GLA/Serif_16/pdf_to_json_test_Latn.GLA_Serif_16.py" > "data/multilingual/Latn.GLA/Serif_16/pdf_to_json_test_Latn.GLA_Serif_16.json" 2>&1
Latn.GLA_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.GLA/Serif_8/pdf_to_json_test_Latn.GLA_Serif_8.py" > "data/multilingual/Latn.GLA/Serif_8/pdf_to_json_test_Latn.GLA_Serif_8.json" 2>&1
Latn.GLA_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.GLA/Sun-ExtA_12/pdf_to_json_test_Latn.GLA_Sun-ExtA_12.py" > "data/multilingual/Latn.GLA/Sun-ExtA_12/pdf_to_json_test_Latn.GLA_Sun-ExtA_12.json" 2>&1
Latn.GLA_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.GLA/Sun-ExtA_16/pdf_to_json_test_Latn.GLA_Sun-ExtA_16.py" > "data/multilingual/Latn.GLA/Sun-ExtA_16/pdf_to_json_test_Latn.GLA_Sun-ExtA_16.json" 2>&1
Latn.GLA_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.GLA/Sun-ExtA_8/pdf_to_json_test_Latn.GLA_Sun-ExtA_8.py" > "data/multilingual/Latn.GLA/Sun-ExtA_8/pdf_to_json_test_Latn.GLA_Sun-ExtA_8.json" 2>&1


Latn.GLA_all : Latn.GLA_Mono_12 Latn.GLA_Mono_16 Latn.GLA_Mono_8 Latn.GLA_Sans_12 Latn.GLA_Sans_16 Latn.GLA_Sans_8 Latn.GLA_Serif_12 Latn.GLA_Serif_16 Latn.GLA_Serif_8 Latn.GLA_Sun-ExtA_12 Latn.GLA_Sun-ExtA_16 Latn.GLA_Sun-ExtA_8
