PYTHON=python3


Latn.GLG_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.GLG/Mono_12/pdf_to_json_test_Latn.GLG_Mono_12.py" > "data/multilingual/Latn.GLG/Mono_12/pdf_to_json_test_Latn.GLG_Mono_12.json" 2>&1
Latn.GLG_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.GLG/Mono_16/pdf_to_json_test_Latn.GLG_Mono_16.py" > "data/multilingual/Latn.GLG/Mono_16/pdf_to_json_test_Latn.GLG_Mono_16.json" 2>&1
Latn.GLG_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.GLG/Mono_8/pdf_to_json_test_Latn.GLG_Mono_8.py" > "data/multilingual/Latn.GLG/Mono_8/pdf_to_json_test_Latn.GLG_Mono_8.json" 2>&1
Latn.GLG_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.GLG/Sans_12/pdf_to_json_test_Latn.GLG_Sans_12.py" > "data/multilingual/Latn.GLG/Sans_12/pdf_to_json_test_Latn.GLG_Sans_12.json" 2>&1
Latn.GLG_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.GLG/Sans_16/pdf_to_json_test_Latn.GLG_Sans_16.py" > "data/multilingual/Latn.GLG/Sans_16/pdf_to_json_test_Latn.GLG_Sans_16.json" 2>&1
Latn.GLG_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.GLG/Sans_8/pdf_to_json_test_Latn.GLG_Sans_8.py" > "data/multilingual/Latn.GLG/Sans_8/pdf_to_json_test_Latn.GLG_Sans_8.json" 2>&1
Latn.GLG_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.GLG/Serif_12/pdf_to_json_test_Latn.GLG_Serif_12.py" > "data/multilingual/Latn.GLG/Serif_12/pdf_to_json_test_Latn.GLG_Serif_12.json" 2>&1
Latn.GLG_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.GLG/Serif_16/pdf_to_json_test_Latn.GLG_Serif_16.py" > "data/multilingual/Latn.GLG/Serif_16/pdf_to_json_test_Latn.GLG_Serif_16.json" 2>&1
Latn.GLG_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.GLG/Serif_8/pdf_to_json_test_Latn.GLG_Serif_8.py" > "data/multilingual/Latn.GLG/Serif_8/pdf_to_json_test_Latn.GLG_Serif_8.json" 2>&1
Latn.GLG_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.GLG/Sun-ExtA_12/pdf_to_json_test_Latn.GLG_Sun-ExtA_12.py" > "data/multilingual/Latn.GLG/Sun-ExtA_12/pdf_to_json_test_Latn.GLG_Sun-ExtA_12.json" 2>&1
Latn.GLG_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.GLG/Sun-ExtA_16/pdf_to_json_test_Latn.GLG_Sun-ExtA_16.py" > "data/multilingual/Latn.GLG/Sun-ExtA_16/pdf_to_json_test_Latn.GLG_Sun-ExtA_16.json" 2>&1
Latn.GLG_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.GLG/Sun-ExtA_8/pdf_to_json_test_Latn.GLG_Sun-ExtA_8.py" > "data/multilingual/Latn.GLG/Sun-ExtA_8/pdf_to_json_test_Latn.GLG_Sun-ExtA_8.json" 2>&1


Latn.GLG_all : Latn.GLG_Mono_12 Latn.GLG_Mono_16 Latn.GLG_Mono_8 Latn.GLG_Sans_12 Latn.GLG_Sans_16 Latn.GLG_Sans_8 Latn.GLG_Serif_12 Latn.GLG_Serif_16 Latn.GLG_Serif_8 Latn.GLG_Sun-ExtA_12 Latn.GLG_Sun-ExtA_16 Latn.GLG_Sun-ExtA_8
