PYTHON=python3


Latn.VEP_Mono_12:
	-$(PYTHON) data/multilingual/Latn.VEP/Mono_12/pdf_to_json_test_Latn.VEP_Mono_12.py > data/multilingual/Latn.VEP/Mono_12/pdf_to_json_test_Latn.VEP_Mono_12.json 2>&1
Latn.VEP_Mono_16:
	-$(PYTHON) data/multilingual/Latn.VEP/Mono_16/pdf_to_json_test_Latn.VEP_Mono_16.py > data/multilingual/Latn.VEP/Mono_16/pdf_to_json_test_Latn.VEP_Mono_16.json 2>&1
Latn.VEP_Mono_8:
	-$(PYTHON) data/multilingual/Latn.VEP/Mono_8/pdf_to_json_test_Latn.VEP_Mono_8.py > data/multilingual/Latn.VEP/Mono_8/pdf_to_json_test_Latn.VEP_Mono_8.json 2>&1
Latn.VEP_Sans_12:
	-$(PYTHON) data/multilingual/Latn.VEP/Sans_12/pdf_to_json_test_Latn.VEP_Sans_12.py > data/multilingual/Latn.VEP/Sans_12/pdf_to_json_test_Latn.VEP_Sans_12.json 2>&1
Latn.VEP_Sans_16:
	-$(PYTHON) data/multilingual/Latn.VEP/Sans_16/pdf_to_json_test_Latn.VEP_Sans_16.py > data/multilingual/Latn.VEP/Sans_16/pdf_to_json_test_Latn.VEP_Sans_16.json 2>&1
Latn.VEP_Sans_8:
	-$(PYTHON) data/multilingual/Latn.VEP/Sans_8/pdf_to_json_test_Latn.VEP_Sans_8.py > data/multilingual/Latn.VEP/Sans_8/pdf_to_json_test_Latn.VEP_Sans_8.json 2>&1
Latn.VEP_Serif_12:
	-$(PYTHON) data/multilingual/Latn.VEP/Serif_12/pdf_to_json_test_Latn.VEP_Serif_12.py > data/multilingual/Latn.VEP/Serif_12/pdf_to_json_test_Latn.VEP_Serif_12.json 2>&1
Latn.VEP_Serif_16:
	-$(PYTHON) data/multilingual/Latn.VEP/Serif_16/pdf_to_json_test_Latn.VEP_Serif_16.py > data/multilingual/Latn.VEP/Serif_16/pdf_to_json_test_Latn.VEP_Serif_16.json 2>&1
Latn.VEP_Serif_8:
	-$(PYTHON) data/multilingual/Latn.VEP/Serif_8/pdf_to_json_test_Latn.VEP_Serif_8.py > data/multilingual/Latn.VEP/Serif_8/pdf_to_json_test_Latn.VEP_Serif_8.json 2>&1
Latn.VEP_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.VEP/Sun-ExtA_12/pdf_to_json_test_Latn.VEP_Sun-ExtA_12.py > data/multilingual/Latn.VEP/Sun-ExtA_12/pdf_to_json_test_Latn.VEP_Sun-ExtA_12.json 2>&1
Latn.VEP_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.VEP/Sun-ExtA_16/pdf_to_json_test_Latn.VEP_Sun-ExtA_16.py > data/multilingual/Latn.VEP/Sun-ExtA_16/pdf_to_json_test_Latn.VEP_Sun-ExtA_16.json 2>&1
Latn.VEP_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.VEP/Sun-ExtA_8/pdf_to_json_test_Latn.VEP_Sun-ExtA_8.py > data/multilingual/Latn.VEP/Sun-ExtA_8/pdf_to_json_test_Latn.VEP_Sun-ExtA_8.json 2>&1


Latn.VEP_all : Latn.VEP_Mono_12 Latn.VEP_Mono_16 Latn.VEP_Mono_8 Latn.VEP_Sans_12 Latn.VEP_Sans_16 Latn.VEP_Sans_8 Latn.VEP_Serif_12 Latn.VEP_Serif_16 Latn.VEP_Serif_8 Latn.VEP_Sun-ExtA_12 Latn.VEP_Sun-ExtA_16 Latn.VEP_Sun-ExtA_8
