PYTHON=python3


Deva.TAJ_Mono_12:
	-$(PYTHON) data/multilingual/Deva.TAJ/Mono_12/pdf_to_json_test_Deva.TAJ_Mono_12.py > data/multilingual/Deva.TAJ/Mono_12/pdf_to_json_test_Deva.TAJ_Mono_12.json 2>&1
Deva.TAJ_Mono_16:
	-$(PYTHON) data/multilingual/Deva.TAJ/Mono_16/pdf_to_json_test_Deva.TAJ_Mono_16.py > data/multilingual/Deva.TAJ/Mono_16/pdf_to_json_test_Deva.TAJ_Mono_16.json 2>&1
Deva.TAJ_Mono_8:
	-$(PYTHON) data/multilingual/Deva.TAJ/Mono_8/pdf_to_json_test_Deva.TAJ_Mono_8.py > data/multilingual/Deva.TAJ/Mono_8/pdf_to_json_test_Deva.TAJ_Mono_8.json 2>&1
Deva.TAJ_Sans_12:
	-$(PYTHON) data/multilingual/Deva.TAJ/Sans_12/pdf_to_json_test_Deva.TAJ_Sans_12.py > data/multilingual/Deva.TAJ/Sans_12/pdf_to_json_test_Deva.TAJ_Sans_12.json 2>&1
Deva.TAJ_Sans_16:
	-$(PYTHON) data/multilingual/Deva.TAJ/Sans_16/pdf_to_json_test_Deva.TAJ_Sans_16.py > data/multilingual/Deva.TAJ/Sans_16/pdf_to_json_test_Deva.TAJ_Sans_16.json 2>&1
Deva.TAJ_Sans_8:
	-$(PYTHON) data/multilingual/Deva.TAJ/Sans_8/pdf_to_json_test_Deva.TAJ_Sans_8.py > data/multilingual/Deva.TAJ/Sans_8/pdf_to_json_test_Deva.TAJ_Sans_8.json 2>&1
Deva.TAJ_Serif_12:
	-$(PYTHON) data/multilingual/Deva.TAJ/Serif_12/pdf_to_json_test_Deva.TAJ_Serif_12.py > data/multilingual/Deva.TAJ/Serif_12/pdf_to_json_test_Deva.TAJ_Serif_12.json 2>&1
Deva.TAJ_Serif_16:
	-$(PYTHON) data/multilingual/Deva.TAJ/Serif_16/pdf_to_json_test_Deva.TAJ_Serif_16.py > data/multilingual/Deva.TAJ/Serif_16/pdf_to_json_test_Deva.TAJ_Serif_16.json 2>&1
Deva.TAJ_Serif_8:
	-$(PYTHON) data/multilingual/Deva.TAJ/Serif_8/pdf_to_json_test_Deva.TAJ_Serif_8.py > data/multilingual/Deva.TAJ/Serif_8/pdf_to_json_test_Deva.TAJ_Serif_8.json 2>&1
Deva.TAJ_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Deva.TAJ/Sun-ExtA_12/pdf_to_json_test_Deva.TAJ_Sun-ExtA_12.py > data/multilingual/Deva.TAJ/Sun-ExtA_12/pdf_to_json_test_Deva.TAJ_Sun-ExtA_12.json 2>&1
Deva.TAJ_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Deva.TAJ/Sun-ExtA_16/pdf_to_json_test_Deva.TAJ_Sun-ExtA_16.py > data/multilingual/Deva.TAJ/Sun-ExtA_16/pdf_to_json_test_Deva.TAJ_Sun-ExtA_16.json 2>&1
Deva.TAJ_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Deva.TAJ/Sun-ExtA_8/pdf_to_json_test_Deva.TAJ_Sun-ExtA_8.py > data/multilingual/Deva.TAJ/Sun-ExtA_8/pdf_to_json_test_Deva.TAJ_Sun-ExtA_8.json 2>&1


Deva.TAJ_all : Deva.TAJ_Mono_12 Deva.TAJ_Mono_16 Deva.TAJ_Mono_8 Deva.TAJ_Sans_12 Deva.TAJ_Sans_16 Deva.TAJ_Sans_8 Deva.TAJ_Serif_12 Deva.TAJ_Serif_16 Deva.TAJ_Serif_8 Deva.TAJ_Sun-ExtA_12 Deva.TAJ_Sun-ExtA_16 Deva.TAJ_Sun-ExtA_8
