PYTHON=python3


Gran.SAN_sampradaya_12:
	-$(PYTHON) "data/multilingual/Gran.SAN/sampradaya_12/pdf_to_json_test_Gran.SAN_sampradaya_12.py" > "data/multilingual/Gran.SAN/sampradaya_12/pdf_to_json_test_Gran.SAN_sampradaya_12.json" 2>&1
Gran.SAN_sampradaya_16:
	-$(PYTHON) "data/multilingual/Gran.SAN/sampradaya_16/pdf_to_json_test_Gran.SAN_sampradaya_16.py" > "data/multilingual/Gran.SAN/sampradaya_16/pdf_to_json_test_Gran.SAN_sampradaya_16.json" 2>&1
Gran.SAN_sampradaya_8:
	-$(PYTHON) "data/multilingual/Gran.SAN/sampradaya_8/pdf_to_json_test_Gran.SAN_sampradaya_8.py" > "data/multilingual/Gran.SAN/sampradaya_8/pdf_to_json_test_Gran.SAN_sampradaya_8.json" 2>&1


Gran.SAN_all : Gran.SAN_sampradaya_12 Gran.SAN_sampradaya_16 Gran.SAN_sampradaya_8
