PYTHON=python3


Latn.DDN_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.DDN/Mono_12/pdf_to_json_test_Latn.DDN_Mono_12.py" > "data/multilingual/Latn.DDN/Mono_12/pdf_to_json_test_Latn.DDN_Mono_12.json" 2>&1
Latn.DDN_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.DDN/Mono_16/pdf_to_json_test_Latn.DDN_Mono_16.py" > "data/multilingual/Latn.DDN/Mono_16/pdf_to_json_test_Latn.DDN_Mono_16.json" 2>&1
Latn.DDN_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.DDN/Mono_8/pdf_to_json_test_Latn.DDN_Mono_8.py" > "data/multilingual/Latn.DDN/Mono_8/pdf_to_json_test_Latn.DDN_Mono_8.json" 2>&1
Latn.DDN_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.DDN/Sans_12/pdf_to_json_test_Latn.DDN_Sans_12.py" > "data/multilingual/Latn.DDN/Sans_12/pdf_to_json_test_Latn.DDN_Sans_12.json" 2>&1
Latn.DDN_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.DDN/Sans_16/pdf_to_json_test_Latn.DDN_Sans_16.py" > "data/multilingual/Latn.DDN/Sans_16/pdf_to_json_test_Latn.DDN_Sans_16.json" 2>&1
Latn.DDN_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.DDN/Sans_8/pdf_to_json_test_Latn.DDN_Sans_8.py" > "data/multilingual/Latn.DDN/Sans_8/pdf_to_json_test_Latn.DDN_Sans_8.json" 2>&1
Latn.DDN_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.DDN/Serif_12/pdf_to_json_test_Latn.DDN_Serif_12.py" > "data/multilingual/Latn.DDN/Serif_12/pdf_to_json_test_Latn.DDN_Serif_12.json" 2>&1
Latn.DDN_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.DDN/Serif_16/pdf_to_json_test_Latn.DDN_Serif_16.py" > "data/multilingual/Latn.DDN/Serif_16/pdf_to_json_test_Latn.DDN_Serif_16.json" 2>&1
Latn.DDN_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.DDN/Serif_8/pdf_to_json_test_Latn.DDN_Serif_8.py" > "data/multilingual/Latn.DDN/Serif_8/pdf_to_json_test_Latn.DDN_Serif_8.json" 2>&1
Latn.DDN_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.DDN/Sun-ExtA_12/pdf_to_json_test_Latn.DDN_Sun-ExtA_12.py" > "data/multilingual/Latn.DDN/Sun-ExtA_12/pdf_to_json_test_Latn.DDN_Sun-ExtA_12.json" 2>&1
Latn.DDN_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.DDN/Sun-ExtA_16/pdf_to_json_test_Latn.DDN_Sun-ExtA_16.py" > "data/multilingual/Latn.DDN/Sun-ExtA_16/pdf_to_json_test_Latn.DDN_Sun-ExtA_16.json" 2>&1
Latn.DDN_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.DDN/Sun-ExtA_8/pdf_to_json_test_Latn.DDN_Sun-ExtA_8.py" > "data/multilingual/Latn.DDN/Sun-ExtA_8/pdf_to_json_test_Latn.DDN_Sun-ExtA_8.json" 2>&1


Latn.DDN_all : Latn.DDN_Mono_12 Latn.DDN_Mono_16 Latn.DDN_Mono_8 Latn.DDN_Sans_12 Latn.DDN_Sans_16 Latn.DDN_Sans_8 Latn.DDN_Serif_12 Latn.DDN_Serif_16 Latn.DDN_Serif_8 Latn.DDN_Sun-ExtA_12 Latn.DDN_Sun-ExtA_16 Latn.DDN_Sun-ExtA_8
