PYTHON=python3


Latn.LUS_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.LUS/Mono_12/pdf_to_json_test_Latn.LUS_Mono_12.py" > "data/multilingual/Latn.LUS/Mono_12/pdf_to_json_test_Latn.LUS_Mono_12.json" 2>&1
Latn.LUS_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.LUS/Mono_16/pdf_to_json_test_Latn.LUS_Mono_16.py" > "data/multilingual/Latn.LUS/Mono_16/pdf_to_json_test_Latn.LUS_Mono_16.json" 2>&1
Latn.LUS_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.LUS/Mono_8/pdf_to_json_test_Latn.LUS_Mono_8.py" > "data/multilingual/Latn.LUS/Mono_8/pdf_to_json_test_Latn.LUS_Mono_8.json" 2>&1
Latn.LUS_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.LUS/Sans_12/pdf_to_json_test_Latn.LUS_Sans_12.py" > "data/multilingual/Latn.LUS/Sans_12/pdf_to_json_test_Latn.LUS_Sans_12.json" 2>&1
Latn.LUS_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.LUS/Sans_16/pdf_to_json_test_Latn.LUS_Sans_16.py" > "data/multilingual/Latn.LUS/Sans_16/pdf_to_json_test_Latn.LUS_Sans_16.json" 2>&1
Latn.LUS_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.LUS/Sans_8/pdf_to_json_test_Latn.LUS_Sans_8.py" > "data/multilingual/Latn.LUS/Sans_8/pdf_to_json_test_Latn.LUS_Sans_8.json" 2>&1
Latn.LUS_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.LUS/Serif_12/pdf_to_json_test_Latn.LUS_Serif_12.py" > "data/multilingual/Latn.LUS/Serif_12/pdf_to_json_test_Latn.LUS_Serif_12.json" 2>&1
Latn.LUS_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.LUS/Serif_16/pdf_to_json_test_Latn.LUS_Serif_16.py" > "data/multilingual/Latn.LUS/Serif_16/pdf_to_json_test_Latn.LUS_Serif_16.json" 2>&1
Latn.LUS_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.LUS/Serif_8/pdf_to_json_test_Latn.LUS_Serif_8.py" > "data/multilingual/Latn.LUS/Serif_8/pdf_to_json_test_Latn.LUS_Serif_8.json" 2>&1
Latn.LUS_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.LUS/Sun-ExtA_12/pdf_to_json_test_Latn.LUS_Sun-ExtA_12.py" > "data/multilingual/Latn.LUS/Sun-ExtA_12/pdf_to_json_test_Latn.LUS_Sun-ExtA_12.json" 2>&1
Latn.LUS_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.LUS/Sun-ExtA_16/pdf_to_json_test_Latn.LUS_Sun-ExtA_16.py" > "data/multilingual/Latn.LUS/Sun-ExtA_16/pdf_to_json_test_Latn.LUS_Sun-ExtA_16.json" 2>&1
Latn.LUS_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.LUS/Sun-ExtA_8/pdf_to_json_test_Latn.LUS_Sun-ExtA_8.py" > "data/multilingual/Latn.LUS/Sun-ExtA_8/pdf_to_json_test_Latn.LUS_Sun-ExtA_8.json" 2>&1


Latn.LUS_all : Latn.LUS_Mono_12 Latn.LUS_Mono_16 Latn.LUS_Mono_8 Latn.LUS_Sans_12 Latn.LUS_Sans_16 Latn.LUS_Sans_8 Latn.LUS_Serif_12 Latn.LUS_Serif_16 Latn.LUS_Serif_8 Latn.LUS_Sun-ExtA_12 Latn.LUS_Sun-ExtA_16 Latn.LUS_Sun-ExtA_8
