PYTHON=python3


Latn.BAN_Mono_12:
	-$(PYTHON) data/multilingual/Latn.BAN/Mono_12/pdf_to_json_test_Latn.BAN_Mono_12.py > data/multilingual/Latn.BAN/Mono_12/pdf_to_json_test_Latn.BAN_Mono_12.json 2>&1
Latn.BAN_Mono_16:
	-$(PYTHON) data/multilingual/Latn.BAN/Mono_16/pdf_to_json_test_Latn.BAN_Mono_16.py > data/multilingual/Latn.BAN/Mono_16/pdf_to_json_test_Latn.BAN_Mono_16.json 2>&1
Latn.BAN_Mono_8:
	-$(PYTHON) data/multilingual/Latn.BAN/Mono_8/pdf_to_json_test_Latn.BAN_Mono_8.py > data/multilingual/Latn.BAN/Mono_8/pdf_to_json_test_Latn.BAN_Mono_8.json 2>&1
Latn.BAN_Sans_12:
	-$(PYTHON) data/multilingual/Latn.BAN/Sans_12/pdf_to_json_test_Latn.BAN_Sans_12.py > data/multilingual/Latn.BAN/Sans_12/pdf_to_json_test_Latn.BAN_Sans_12.json 2>&1
Latn.BAN_Sans_16:
	-$(PYTHON) data/multilingual/Latn.BAN/Sans_16/pdf_to_json_test_Latn.BAN_Sans_16.py > data/multilingual/Latn.BAN/Sans_16/pdf_to_json_test_Latn.BAN_Sans_16.json 2>&1
Latn.BAN_Sans_8:
	-$(PYTHON) data/multilingual/Latn.BAN/Sans_8/pdf_to_json_test_Latn.BAN_Sans_8.py > data/multilingual/Latn.BAN/Sans_8/pdf_to_json_test_Latn.BAN_Sans_8.json 2>&1
Latn.BAN_Serif_12:
	-$(PYTHON) data/multilingual/Latn.BAN/Serif_12/pdf_to_json_test_Latn.BAN_Serif_12.py > data/multilingual/Latn.BAN/Serif_12/pdf_to_json_test_Latn.BAN_Serif_12.json 2>&1
Latn.BAN_Serif_16:
	-$(PYTHON) data/multilingual/Latn.BAN/Serif_16/pdf_to_json_test_Latn.BAN_Serif_16.py > data/multilingual/Latn.BAN/Serif_16/pdf_to_json_test_Latn.BAN_Serif_16.json 2>&1
Latn.BAN_Serif_8:
	-$(PYTHON) data/multilingual/Latn.BAN/Serif_8/pdf_to_json_test_Latn.BAN_Serif_8.py > data/multilingual/Latn.BAN/Serif_8/pdf_to_json_test_Latn.BAN_Serif_8.json 2>&1
Latn.BAN_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.BAN/Sun-ExtA_12/pdf_to_json_test_Latn.BAN_Sun-ExtA_12.py > data/multilingual/Latn.BAN/Sun-ExtA_12/pdf_to_json_test_Latn.BAN_Sun-ExtA_12.json 2>&1
Latn.BAN_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.BAN/Sun-ExtA_16/pdf_to_json_test_Latn.BAN_Sun-ExtA_16.py > data/multilingual/Latn.BAN/Sun-ExtA_16/pdf_to_json_test_Latn.BAN_Sun-ExtA_16.json 2>&1
Latn.BAN_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.BAN/Sun-ExtA_8/pdf_to_json_test_Latn.BAN_Sun-ExtA_8.py > data/multilingual/Latn.BAN/Sun-ExtA_8/pdf_to_json_test_Latn.BAN_Sun-ExtA_8.json 2>&1


Latn.BAN_all : Latn.BAN_Mono_12 Latn.BAN_Mono_16 Latn.BAN_Mono_8 Latn.BAN_Sans_12 Latn.BAN_Sans_16 Latn.BAN_Sans_8 Latn.BAN_Serif_12 Latn.BAN_Serif_16 Latn.BAN_Serif_8 Latn.BAN_Sun-ExtA_12 Latn.BAN_Sun-ExtA_16 Latn.BAN_Sun-ExtA_8
