PYTHON=python3


Latn.KHA_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.KHA/Mono_12/pdf_to_json_test_Latn.KHA_Mono_12.py" > "data/multilingual/Latn.KHA/Mono_12/pdf_to_json_test_Latn.KHA_Mono_12.json" 2>&1
Latn.KHA_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.KHA/Mono_16/pdf_to_json_test_Latn.KHA_Mono_16.py" > "data/multilingual/Latn.KHA/Mono_16/pdf_to_json_test_Latn.KHA_Mono_16.json" 2>&1
Latn.KHA_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.KHA/Mono_8/pdf_to_json_test_Latn.KHA_Mono_8.py" > "data/multilingual/Latn.KHA/Mono_8/pdf_to_json_test_Latn.KHA_Mono_8.json" 2>&1
Latn.KHA_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.KHA/Sans_12/pdf_to_json_test_Latn.KHA_Sans_12.py" > "data/multilingual/Latn.KHA/Sans_12/pdf_to_json_test_Latn.KHA_Sans_12.json" 2>&1
Latn.KHA_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.KHA/Sans_16/pdf_to_json_test_Latn.KHA_Sans_16.py" > "data/multilingual/Latn.KHA/Sans_16/pdf_to_json_test_Latn.KHA_Sans_16.json" 2>&1
Latn.KHA_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.KHA/Sans_8/pdf_to_json_test_Latn.KHA_Sans_8.py" > "data/multilingual/Latn.KHA/Sans_8/pdf_to_json_test_Latn.KHA_Sans_8.json" 2>&1
Latn.KHA_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.KHA/Serif_12/pdf_to_json_test_Latn.KHA_Serif_12.py" > "data/multilingual/Latn.KHA/Serif_12/pdf_to_json_test_Latn.KHA_Serif_12.json" 2>&1
Latn.KHA_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.KHA/Serif_16/pdf_to_json_test_Latn.KHA_Serif_16.py" > "data/multilingual/Latn.KHA/Serif_16/pdf_to_json_test_Latn.KHA_Serif_16.json" 2>&1
Latn.KHA_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.KHA/Serif_8/pdf_to_json_test_Latn.KHA_Serif_8.py" > "data/multilingual/Latn.KHA/Serif_8/pdf_to_json_test_Latn.KHA_Serif_8.json" 2>&1
Latn.KHA_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.KHA/Sun-ExtA_12/pdf_to_json_test_Latn.KHA_Sun-ExtA_12.py" > "data/multilingual/Latn.KHA/Sun-ExtA_12/pdf_to_json_test_Latn.KHA_Sun-ExtA_12.json" 2>&1
Latn.KHA_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.KHA/Sun-ExtA_16/pdf_to_json_test_Latn.KHA_Sun-ExtA_16.py" > "data/multilingual/Latn.KHA/Sun-ExtA_16/pdf_to_json_test_Latn.KHA_Sun-ExtA_16.json" 2>&1
Latn.KHA_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.KHA/Sun-ExtA_8/pdf_to_json_test_Latn.KHA_Sun-ExtA_8.py" > "data/multilingual/Latn.KHA/Sun-ExtA_8/pdf_to_json_test_Latn.KHA_Sun-ExtA_8.json" 2>&1


Latn.KHA_all : Latn.KHA_Mono_12 Latn.KHA_Mono_16 Latn.KHA_Mono_8 Latn.KHA_Sans_12 Latn.KHA_Sans_16 Latn.KHA_Sans_8 Latn.KHA_Serif_12 Latn.KHA_Serif_16 Latn.KHA_Serif_8 Latn.KHA_Sun-ExtA_12 Latn.KHA_Sun-ExtA_16 Latn.KHA_Sun-ExtA_8
