PYTHON=python3


Cyrl.OAA_Mono_12:
	-$(PYTHON) data/multilingual/Cyrl.OAA/Mono_12/pdf_to_json_test_Cyrl.OAA_Mono_12.py > data/multilingual/Cyrl.OAA/Mono_12/pdf_to_json_test_Cyrl.OAA_Mono_12.json 2>&1
Cyrl.OAA_Mono_16:
	-$(PYTHON) data/multilingual/Cyrl.OAA/Mono_16/pdf_to_json_test_Cyrl.OAA_Mono_16.py > data/multilingual/Cyrl.OAA/Mono_16/pdf_to_json_test_Cyrl.OAA_Mono_16.json 2>&1
Cyrl.OAA_Mono_8:
	-$(PYTHON) data/multilingual/Cyrl.OAA/Mono_8/pdf_to_json_test_Cyrl.OAA_Mono_8.py > data/multilingual/Cyrl.OAA/Mono_8/pdf_to_json_test_Cyrl.OAA_Mono_8.json 2>&1
Cyrl.OAA_Sans_12:
	-$(PYTHON) data/multilingual/Cyrl.OAA/Sans_12/pdf_to_json_test_Cyrl.OAA_Sans_12.py > data/multilingual/Cyrl.OAA/Sans_12/pdf_to_json_test_Cyrl.OAA_Sans_12.json 2>&1
Cyrl.OAA_Sans_16:
	-$(PYTHON) data/multilingual/Cyrl.OAA/Sans_16/pdf_to_json_test_Cyrl.OAA_Sans_16.py > data/multilingual/Cyrl.OAA/Sans_16/pdf_to_json_test_Cyrl.OAA_Sans_16.json 2>&1
Cyrl.OAA_Sans_8:
	-$(PYTHON) data/multilingual/Cyrl.OAA/Sans_8/pdf_to_json_test_Cyrl.OAA_Sans_8.py > data/multilingual/Cyrl.OAA/Sans_8/pdf_to_json_test_Cyrl.OAA_Sans_8.json 2>&1
Cyrl.OAA_Serif_12:
	-$(PYTHON) data/multilingual/Cyrl.OAA/Serif_12/pdf_to_json_test_Cyrl.OAA_Serif_12.py > data/multilingual/Cyrl.OAA/Serif_12/pdf_to_json_test_Cyrl.OAA_Serif_12.json 2>&1
Cyrl.OAA_Serif_16:
	-$(PYTHON) data/multilingual/Cyrl.OAA/Serif_16/pdf_to_json_test_Cyrl.OAA_Serif_16.py > data/multilingual/Cyrl.OAA/Serif_16/pdf_to_json_test_Cyrl.OAA_Serif_16.json 2>&1
Cyrl.OAA_Serif_8:
	-$(PYTHON) data/multilingual/Cyrl.OAA/Serif_8/pdf_to_json_test_Cyrl.OAA_Serif_8.py > data/multilingual/Cyrl.OAA/Serif_8/pdf_to_json_test_Cyrl.OAA_Serif_8.json 2>&1
Cyrl.OAA_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Cyrl.OAA/Sun-ExtA_12/pdf_to_json_test_Cyrl.OAA_Sun-ExtA_12.py > data/multilingual/Cyrl.OAA/Sun-ExtA_12/pdf_to_json_test_Cyrl.OAA_Sun-ExtA_12.json 2>&1
Cyrl.OAA_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Cyrl.OAA/Sun-ExtA_16/pdf_to_json_test_Cyrl.OAA_Sun-ExtA_16.py > data/multilingual/Cyrl.OAA/Sun-ExtA_16/pdf_to_json_test_Cyrl.OAA_Sun-ExtA_16.json 2>&1
Cyrl.OAA_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Cyrl.OAA/Sun-ExtA_8/pdf_to_json_test_Cyrl.OAA_Sun-ExtA_8.py > data/multilingual/Cyrl.OAA/Sun-ExtA_8/pdf_to_json_test_Cyrl.OAA_Sun-ExtA_8.json 2>&1


Cyrl.OAA_all : Cyrl.OAA_Mono_12 Cyrl.OAA_Mono_16 Cyrl.OAA_Mono_8 Cyrl.OAA_Sans_12 Cyrl.OAA_Sans_16 Cyrl.OAA_Sans_8 Cyrl.OAA_Serif_12 Cyrl.OAA_Serif_16 Cyrl.OAA_Serif_8 Cyrl.OAA_Sun-ExtA_12 Cyrl.OAA_Sun-ExtA_16 Cyrl.OAA_Sun-ExtA_8
