PYTHON=python3


Latn.KTU_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.KTU/Mono_12/pdf_to_json_test_Latn.KTU_Mono_12.py" > "data/multilingual/Latn.KTU/Mono_12/pdf_to_json_test_Latn.KTU_Mono_12.json" 2>&1
Latn.KTU_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.KTU/Mono_16/pdf_to_json_test_Latn.KTU_Mono_16.py" > "data/multilingual/Latn.KTU/Mono_16/pdf_to_json_test_Latn.KTU_Mono_16.json" 2>&1
Latn.KTU_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.KTU/Mono_8/pdf_to_json_test_Latn.KTU_Mono_8.py" > "data/multilingual/Latn.KTU/Mono_8/pdf_to_json_test_Latn.KTU_Mono_8.json" 2>&1
Latn.KTU_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.KTU/Sans_12/pdf_to_json_test_Latn.KTU_Sans_12.py" > "data/multilingual/Latn.KTU/Sans_12/pdf_to_json_test_Latn.KTU_Sans_12.json" 2>&1
Latn.KTU_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.KTU/Sans_16/pdf_to_json_test_Latn.KTU_Sans_16.py" > "data/multilingual/Latn.KTU/Sans_16/pdf_to_json_test_Latn.KTU_Sans_16.json" 2>&1
Latn.KTU_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.KTU/Sans_8/pdf_to_json_test_Latn.KTU_Sans_8.py" > "data/multilingual/Latn.KTU/Sans_8/pdf_to_json_test_Latn.KTU_Sans_8.json" 2>&1
Latn.KTU_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.KTU/Serif_12/pdf_to_json_test_Latn.KTU_Serif_12.py" > "data/multilingual/Latn.KTU/Serif_12/pdf_to_json_test_Latn.KTU_Serif_12.json" 2>&1
Latn.KTU_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.KTU/Serif_16/pdf_to_json_test_Latn.KTU_Serif_16.py" > "data/multilingual/Latn.KTU/Serif_16/pdf_to_json_test_Latn.KTU_Serif_16.json" 2>&1
Latn.KTU_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.KTU/Serif_8/pdf_to_json_test_Latn.KTU_Serif_8.py" > "data/multilingual/Latn.KTU/Serif_8/pdf_to_json_test_Latn.KTU_Serif_8.json" 2>&1
Latn.KTU_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.KTU/Sun-ExtA_12/pdf_to_json_test_Latn.KTU_Sun-ExtA_12.py" > "data/multilingual/Latn.KTU/Sun-ExtA_12/pdf_to_json_test_Latn.KTU_Sun-ExtA_12.json" 2>&1
Latn.KTU_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.KTU/Sun-ExtA_16/pdf_to_json_test_Latn.KTU_Sun-ExtA_16.py" > "data/multilingual/Latn.KTU/Sun-ExtA_16/pdf_to_json_test_Latn.KTU_Sun-ExtA_16.json" 2>&1
Latn.KTU_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.KTU/Sun-ExtA_8/pdf_to_json_test_Latn.KTU_Sun-ExtA_8.py" > "data/multilingual/Latn.KTU/Sun-ExtA_8/pdf_to_json_test_Latn.KTU_Sun-ExtA_8.json" 2>&1


Latn.KTU_all : Latn.KTU_Mono_12 Latn.KTU_Mono_16 Latn.KTU_Mono_8 Latn.KTU_Sans_12 Latn.KTU_Sans_16 Latn.KTU_Sans_8 Latn.KTU_Serif_12 Latn.KTU_Serif_16 Latn.KTU_Serif_8 Latn.KTU_Sun-ExtA_12 Latn.KTU_Sun-ExtA_16 Latn.KTU_Sun-ExtA_8
