PYTHON=python3


Cyrl.SAH_Mono_12:
	-$(PYTHON) "data/multilingual/Cyrl.SAH/Mono_12/pdf_to_json_test_Cyrl.SAH_Mono_12.py" > "data/multilingual/Cyrl.SAH/Mono_12/pdf_to_json_test_Cyrl.SAH_Mono_12.json" 2>&1
Cyrl.SAH_Mono_16:
	-$(PYTHON) "data/multilingual/Cyrl.SAH/Mono_16/pdf_to_json_test_Cyrl.SAH_Mono_16.py" > "data/multilingual/Cyrl.SAH/Mono_16/pdf_to_json_test_Cyrl.SAH_Mono_16.json" 2>&1
Cyrl.SAH_Mono_8:
	-$(PYTHON) "data/multilingual/Cyrl.SAH/Mono_8/pdf_to_json_test_Cyrl.SAH_Mono_8.py" > "data/multilingual/Cyrl.SAH/Mono_8/pdf_to_json_test_Cyrl.SAH_Mono_8.json" 2>&1
Cyrl.SAH_Sans_12:
	-$(PYTHON) "data/multilingual/Cyrl.SAH/Sans_12/pdf_to_json_test_Cyrl.SAH_Sans_12.py" > "data/multilingual/Cyrl.SAH/Sans_12/pdf_to_json_test_Cyrl.SAH_Sans_12.json" 2>&1
Cyrl.SAH_Sans_16:
	-$(PYTHON) "data/multilingual/Cyrl.SAH/Sans_16/pdf_to_json_test_Cyrl.SAH_Sans_16.py" > "data/multilingual/Cyrl.SAH/Sans_16/pdf_to_json_test_Cyrl.SAH_Sans_16.json" 2>&1
Cyrl.SAH_Sans_8:
	-$(PYTHON) "data/multilingual/Cyrl.SAH/Sans_8/pdf_to_json_test_Cyrl.SAH_Sans_8.py" > "data/multilingual/Cyrl.SAH/Sans_8/pdf_to_json_test_Cyrl.SAH_Sans_8.json" 2>&1
Cyrl.SAH_Serif_12:
	-$(PYTHON) "data/multilingual/Cyrl.SAH/Serif_12/pdf_to_json_test_Cyrl.SAH_Serif_12.py" > "data/multilingual/Cyrl.SAH/Serif_12/pdf_to_json_test_Cyrl.SAH_Serif_12.json" 2>&1
Cyrl.SAH_Serif_16:
	-$(PYTHON) "data/multilingual/Cyrl.SAH/Serif_16/pdf_to_json_test_Cyrl.SAH_Serif_16.py" > "data/multilingual/Cyrl.SAH/Serif_16/pdf_to_json_test_Cyrl.SAH_Serif_16.json" 2>&1
Cyrl.SAH_Serif_8:
	-$(PYTHON) "data/multilingual/Cyrl.SAH/Serif_8/pdf_to_json_test_Cyrl.SAH_Serif_8.py" > "data/multilingual/Cyrl.SAH/Serif_8/pdf_to_json_test_Cyrl.SAH_Serif_8.json" 2>&1
Cyrl.SAH_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Cyrl.SAH/Sun-ExtA_12/pdf_to_json_test_Cyrl.SAH_Sun-ExtA_12.py" > "data/multilingual/Cyrl.SAH/Sun-ExtA_12/pdf_to_json_test_Cyrl.SAH_Sun-ExtA_12.json" 2>&1
Cyrl.SAH_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Cyrl.SAH/Sun-ExtA_16/pdf_to_json_test_Cyrl.SAH_Sun-ExtA_16.py" > "data/multilingual/Cyrl.SAH/Sun-ExtA_16/pdf_to_json_test_Cyrl.SAH_Sun-ExtA_16.json" 2>&1
Cyrl.SAH_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Cyrl.SAH/Sun-ExtA_8/pdf_to_json_test_Cyrl.SAH_Sun-ExtA_8.py" > "data/multilingual/Cyrl.SAH/Sun-ExtA_8/pdf_to_json_test_Cyrl.SAH_Sun-ExtA_8.json" 2>&1


Cyrl.SAH_all : Cyrl.SAH_Mono_12 Cyrl.SAH_Mono_16 Cyrl.SAH_Mono_8 Cyrl.SAH_Sans_12 Cyrl.SAH_Sans_16 Cyrl.SAH_Sans_8 Cyrl.SAH_Serif_12 Cyrl.SAH_Serif_16 Cyrl.SAH_Serif_8 Cyrl.SAH_Sun-ExtA_12 Cyrl.SAH_Sun-ExtA_16 Cyrl.SAH_Sun-ExtA_8
