PYTHON=python3


Latn.ILO_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.ILO/Mono_12/pdf_to_json_test_Latn.ILO_Mono_12.py" > "data/multilingual/Latn.ILO/Mono_12/pdf_to_json_test_Latn.ILO_Mono_12.json" 2>&1
Latn.ILO_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.ILO/Mono_16/pdf_to_json_test_Latn.ILO_Mono_16.py" > "data/multilingual/Latn.ILO/Mono_16/pdf_to_json_test_Latn.ILO_Mono_16.json" 2>&1
Latn.ILO_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.ILO/Mono_8/pdf_to_json_test_Latn.ILO_Mono_8.py" > "data/multilingual/Latn.ILO/Mono_8/pdf_to_json_test_Latn.ILO_Mono_8.json" 2>&1
Latn.ILO_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.ILO/Sans_12/pdf_to_json_test_Latn.ILO_Sans_12.py" > "data/multilingual/Latn.ILO/Sans_12/pdf_to_json_test_Latn.ILO_Sans_12.json" 2>&1
Latn.ILO_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.ILO/Sans_16/pdf_to_json_test_Latn.ILO_Sans_16.py" > "data/multilingual/Latn.ILO/Sans_16/pdf_to_json_test_Latn.ILO_Sans_16.json" 2>&1
Latn.ILO_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.ILO/Sans_8/pdf_to_json_test_Latn.ILO_Sans_8.py" > "data/multilingual/Latn.ILO/Sans_8/pdf_to_json_test_Latn.ILO_Sans_8.json" 2>&1
Latn.ILO_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.ILO/Serif_12/pdf_to_json_test_Latn.ILO_Serif_12.py" > "data/multilingual/Latn.ILO/Serif_12/pdf_to_json_test_Latn.ILO_Serif_12.json" 2>&1
Latn.ILO_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.ILO/Serif_16/pdf_to_json_test_Latn.ILO_Serif_16.py" > "data/multilingual/Latn.ILO/Serif_16/pdf_to_json_test_Latn.ILO_Serif_16.json" 2>&1
Latn.ILO_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.ILO/Serif_8/pdf_to_json_test_Latn.ILO_Serif_8.py" > "data/multilingual/Latn.ILO/Serif_8/pdf_to_json_test_Latn.ILO_Serif_8.json" 2>&1
Latn.ILO_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.ILO/Sun-ExtA_12/pdf_to_json_test_Latn.ILO_Sun-ExtA_12.py" > "data/multilingual/Latn.ILO/Sun-ExtA_12/pdf_to_json_test_Latn.ILO_Sun-ExtA_12.json" 2>&1
Latn.ILO_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.ILO/Sun-ExtA_16/pdf_to_json_test_Latn.ILO_Sun-ExtA_16.py" > "data/multilingual/Latn.ILO/Sun-ExtA_16/pdf_to_json_test_Latn.ILO_Sun-ExtA_16.json" 2>&1
Latn.ILO_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.ILO/Sun-ExtA_8/pdf_to_json_test_Latn.ILO_Sun-ExtA_8.py" > "data/multilingual/Latn.ILO/Sun-ExtA_8/pdf_to_json_test_Latn.ILO_Sun-ExtA_8.json" 2>&1


Latn.ILO_all : Latn.ILO_Mono_12 Latn.ILO_Mono_16 Latn.ILO_Mono_8 Latn.ILO_Sans_12 Latn.ILO_Sans_16 Latn.ILO_Sans_8 Latn.ILO_Serif_12 Latn.ILO_Serif_16 Latn.ILO_Serif_8 Latn.ILO_Sun-ExtA_12 Latn.ILO_Sun-ExtA_16 Latn.ILO_Sun-ExtA_8
