PYTHON=python3


Cakm.CCP_Alaam_12:
	-$(PYTHON) data/multilingual/Cakm.CCP/Alaam_12/pdf_to_json_test_Cakm.CCP_Alaam_12.py > data/multilingual/Cakm.CCP/Alaam_12/pdf_to_json_test_Cakm.CCP_Alaam_12.json 2>&1
Cakm.CCP_Alaam_16:
	-$(PYTHON) data/multilingual/Cakm.CCP/Alaam_16/pdf_to_json_test_Cakm.CCP_Alaam_16.py > data/multilingual/Cakm.CCP/Alaam_16/pdf_to_json_test_Cakm.CCP_Alaam_16.json 2>&1
Cakm.CCP_Alaam_8:
	-$(PYTHON) data/multilingual/Cakm.CCP/Alaam_8/pdf_to_json_test_Cakm.CCP_Alaam_8.py > data/multilingual/Cakm.CCP/Alaam_8/pdf_to_json_test_Cakm.CCP_Alaam_8.json 2>&1
Cakm.CCP_BivuNabaKhamaC_12:
	-$(PYTHON) data/multilingual/Cakm.CCP/BivuNabaKhamaC_12/pdf_to_json_test_Cakm.CCP_BivuNabaKhamaC_12.py > data/multilingual/Cakm.CCP/BivuNabaKhamaC_12/pdf_to_json_test_Cakm.CCP_BivuNabaKhamaC_12.json 2>&1
Cakm.CCP_BivuNabaKhamaC_16:
	-$(PYTHON) data/multilingual/Cakm.CCP/BivuNabaKhamaC_16/pdf_to_json_test_Cakm.CCP_BivuNabaKhamaC_16.py > data/multilingual/Cakm.CCP/BivuNabaKhamaC_16/pdf_to_json_test_Cakm.CCP_BivuNabaKhamaC_16.json 2>&1
Cakm.CCP_BivuNabaKhamaC_8:
	-$(PYTHON) data/multilingual/Cakm.CCP/BivuNabaKhamaC_8/pdf_to_json_test_Cakm.CCP_BivuNabaKhamaC_8.py > data/multilingual/Cakm.CCP/BivuNabaKhamaC_8/pdf_to_json_test_Cakm.CCP_BivuNabaKhamaC_8.json 2>&1


Cakm.CCP_all : Cakm.CCP_Alaam_12 Cakm.CCP_Alaam_16 Cakm.CCP_Alaam_8 Cakm.CCP_BivuNabaKhamaC_12 Cakm.CCP_BivuNabaKhamaC_16 Cakm.CCP_BivuNabaKhamaC_8
