PYTHON=python3


Hans.WUU_Mono_12:
	-$(PYTHON) "data/multilingual/Hans.WUU/Mono_12/pdf_to_json_test_Hans.WUU_Mono_12.py" > "data/multilingual/Hans.WUU/Mono_12/pdf_to_json_test_Hans.WUU_Mono_12.json" 2>&1
Hans.WUU_Mono_16:
	-$(PYTHON) "data/multilingual/Hans.WUU/Mono_16/pdf_to_json_test_Hans.WUU_Mono_16.py" > "data/multilingual/Hans.WUU/Mono_16/pdf_to_json_test_Hans.WUU_Mono_16.json" 2>&1
Hans.WUU_Mono_8:
	-$(PYTHON) "data/multilingual/Hans.WUU/Mono_8/pdf_to_json_test_Hans.WUU_Mono_8.py" > "data/multilingual/Hans.WUU/Mono_8/pdf_to_json_test_Hans.WUU_Mono_8.json" 2>&1
Hans.WUU_Sans_12:
	-$(PYTHON) "data/multilingual/Hans.WUU/Sans_12/pdf_to_json_test_Hans.WUU_Sans_12.py" > "data/multilingual/Hans.WUU/Sans_12/pdf_to_json_test_Hans.WUU_Sans_12.json" 2>&1
Hans.WUU_Sans_16:
	-$(PYTHON) "data/multilingual/Hans.WUU/Sans_16/pdf_to_json_test_Hans.WUU_Sans_16.py" > "data/multilingual/Hans.WUU/Sans_16/pdf_to_json_test_Hans.WUU_Sans_16.json" 2>&1
Hans.WUU_Sans_8:
	-$(PYTHON) "data/multilingual/Hans.WUU/Sans_8/pdf_to_json_test_Hans.WUU_Sans_8.py" > "data/multilingual/Hans.WUU/Sans_8/pdf_to_json_test_Hans.WUU_Sans_8.json" 2>&1
Hans.WUU_Serif_12:
	-$(PYTHON) "data/multilingual/Hans.WUU/Serif_12/pdf_to_json_test_Hans.WUU_Serif_12.py" > "data/multilingual/Hans.WUU/Serif_12/pdf_to_json_test_Hans.WUU_Serif_12.json" 2>&1
Hans.WUU_Serif_16:
	-$(PYTHON) "data/multilingual/Hans.WUU/Serif_16/pdf_to_json_test_Hans.WUU_Serif_16.py" > "data/multilingual/Hans.WUU/Serif_16/pdf_to_json_test_Hans.WUU_Serif_16.json" 2>&1
Hans.WUU_Serif_8:
	-$(PYTHON) "data/multilingual/Hans.WUU/Serif_8/pdf_to_json_test_Hans.WUU_Serif_8.py" > "data/multilingual/Hans.WUU/Serif_8/pdf_to_json_test_Hans.WUU_Serif_8.json" 2>&1
Hans.WUU_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Hans.WUU/Sun-ExtA_12/pdf_to_json_test_Hans.WUU_Sun-ExtA_12.py" > "data/multilingual/Hans.WUU/Sun-ExtA_12/pdf_to_json_test_Hans.WUU_Sun-ExtA_12.json" 2>&1
Hans.WUU_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Hans.WUU/Sun-ExtA_16/pdf_to_json_test_Hans.WUU_Sun-ExtA_16.py" > "data/multilingual/Hans.WUU/Sun-ExtA_16/pdf_to_json_test_Hans.WUU_Sun-ExtA_16.json" 2>&1
Hans.WUU_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Hans.WUU/Sun-ExtA_8/pdf_to_json_test_Hans.WUU_Sun-ExtA_8.py" > "data/multilingual/Hans.WUU/Sun-ExtA_8/pdf_to_json_test_Hans.WUU_Sun-ExtA_8.json" 2>&1


Hans.WUU_all : Hans.WUU_Mono_12 Hans.WUU_Mono_16 Hans.WUU_Mono_8 Hans.WUU_Sans_12 Hans.WUU_Sans_16 Hans.WUU_Sans_8 Hans.WUU_Serif_12 Hans.WUU_Serif_16 Hans.WUU_Serif_8 Hans.WUU_Sun-ExtA_12 Hans.WUU_Sun-ExtA_16 Hans.WUU_Sun-ExtA_8
