PYTHON=python3


Latn.CAK_Mono_12:
	-$(PYTHON) data/multilingual/Latn.CAK/Mono_12/pdf_to_json_test_Latn.CAK_Mono_12.py > data/multilingual/Latn.CAK/Mono_12/pdf_to_json_test_Latn.CAK_Mono_12.json 2>&1
Latn.CAK_Mono_16:
	-$(PYTHON) data/multilingual/Latn.CAK/Mono_16/pdf_to_json_test_Latn.CAK_Mono_16.py > data/multilingual/Latn.CAK/Mono_16/pdf_to_json_test_Latn.CAK_Mono_16.json 2>&1
Latn.CAK_Mono_8:
	-$(PYTHON) data/multilingual/Latn.CAK/Mono_8/pdf_to_json_test_Latn.CAK_Mono_8.py > data/multilingual/Latn.CAK/Mono_8/pdf_to_json_test_Latn.CAK_Mono_8.json 2>&1
Latn.CAK_Sans_12:
	-$(PYTHON) data/multilingual/Latn.CAK/Sans_12/pdf_to_json_test_Latn.CAK_Sans_12.py > data/multilingual/Latn.CAK/Sans_12/pdf_to_json_test_Latn.CAK_Sans_12.json 2>&1
Latn.CAK_Sans_16:
	-$(PYTHON) data/multilingual/Latn.CAK/Sans_16/pdf_to_json_test_Latn.CAK_Sans_16.py > data/multilingual/Latn.CAK/Sans_16/pdf_to_json_test_Latn.CAK_Sans_16.json 2>&1
Latn.CAK_Sans_8:
	-$(PYTHON) data/multilingual/Latn.CAK/Sans_8/pdf_to_json_test_Latn.CAK_Sans_8.py > data/multilingual/Latn.CAK/Sans_8/pdf_to_json_test_Latn.CAK_Sans_8.json 2>&1
Latn.CAK_Serif_12:
	-$(PYTHON) data/multilingual/Latn.CAK/Serif_12/pdf_to_json_test_Latn.CAK_Serif_12.py > data/multilingual/Latn.CAK/Serif_12/pdf_to_json_test_Latn.CAK_Serif_12.json 2>&1
Latn.CAK_Serif_16:
	-$(PYTHON) data/multilingual/Latn.CAK/Serif_16/pdf_to_json_test_Latn.CAK_Serif_16.py > data/multilingual/Latn.CAK/Serif_16/pdf_to_json_test_Latn.CAK_Serif_16.json 2>&1
Latn.CAK_Serif_8:
	-$(PYTHON) data/multilingual/Latn.CAK/Serif_8/pdf_to_json_test_Latn.CAK_Serif_8.py > data/multilingual/Latn.CAK/Serif_8/pdf_to_json_test_Latn.CAK_Serif_8.json 2>&1
Latn.CAK_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.CAK/Sun-ExtA_12/pdf_to_json_test_Latn.CAK_Sun-ExtA_12.py > data/multilingual/Latn.CAK/Sun-ExtA_12/pdf_to_json_test_Latn.CAK_Sun-ExtA_12.json 2>&1
Latn.CAK_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.CAK/Sun-ExtA_16/pdf_to_json_test_Latn.CAK_Sun-ExtA_16.py > data/multilingual/Latn.CAK/Sun-ExtA_16/pdf_to_json_test_Latn.CAK_Sun-ExtA_16.json 2>&1
Latn.CAK_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.CAK/Sun-ExtA_8/pdf_to_json_test_Latn.CAK_Sun-ExtA_8.py > data/multilingual/Latn.CAK/Sun-ExtA_8/pdf_to_json_test_Latn.CAK_Sun-ExtA_8.json 2>&1


Latn.CAK_all : Latn.CAK_Mono_12 Latn.CAK_Mono_16 Latn.CAK_Mono_8 Latn.CAK_Sans_12 Latn.CAK_Sans_16 Latn.CAK_Sans_8 Latn.CAK_Serif_12 Latn.CAK_Serif_16 Latn.CAK_Serif_8 Latn.CAK_Sun-ExtA_12 Latn.CAK_Sun-ExtA_16 Latn.CAK_Sun-ExtA_8
