PYTHON=python3


Latn.CJK_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.CJK/Mono_12/pdf_to_json_test_Latn.CJK_Mono_12.py" > "data/multilingual/Latn.CJK/Mono_12/pdf_to_json_test_Latn.CJK_Mono_12.json" 2>&1
Latn.CJK_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.CJK/Mono_16/pdf_to_json_test_Latn.CJK_Mono_16.py" > "data/multilingual/Latn.CJK/Mono_16/pdf_to_json_test_Latn.CJK_Mono_16.json" 2>&1
Latn.CJK_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.CJK/Mono_8/pdf_to_json_test_Latn.CJK_Mono_8.py" > "data/multilingual/Latn.CJK/Mono_8/pdf_to_json_test_Latn.CJK_Mono_8.json" 2>&1
Latn.CJK_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.CJK/Sans_12/pdf_to_json_test_Latn.CJK_Sans_12.py" > "data/multilingual/Latn.CJK/Sans_12/pdf_to_json_test_Latn.CJK_Sans_12.json" 2>&1
Latn.CJK_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.CJK/Sans_16/pdf_to_json_test_Latn.CJK_Sans_16.py" > "data/multilingual/Latn.CJK/Sans_16/pdf_to_json_test_Latn.CJK_Sans_16.json" 2>&1
Latn.CJK_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.CJK/Sans_8/pdf_to_json_test_Latn.CJK_Sans_8.py" > "data/multilingual/Latn.CJK/Sans_8/pdf_to_json_test_Latn.CJK_Sans_8.json" 2>&1
Latn.CJK_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.CJK/Serif_12/pdf_to_json_test_Latn.CJK_Serif_12.py" > "data/multilingual/Latn.CJK/Serif_12/pdf_to_json_test_Latn.CJK_Serif_12.json" 2>&1
Latn.CJK_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.CJK/Serif_16/pdf_to_json_test_Latn.CJK_Serif_16.py" > "data/multilingual/Latn.CJK/Serif_16/pdf_to_json_test_Latn.CJK_Serif_16.json" 2>&1
Latn.CJK_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.CJK/Serif_8/pdf_to_json_test_Latn.CJK_Serif_8.py" > "data/multilingual/Latn.CJK/Serif_8/pdf_to_json_test_Latn.CJK_Serif_8.json" 2>&1
Latn.CJK_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.CJK/Sun-ExtA_12/pdf_to_json_test_Latn.CJK_Sun-ExtA_12.py" > "data/multilingual/Latn.CJK/Sun-ExtA_12/pdf_to_json_test_Latn.CJK_Sun-ExtA_12.json" 2>&1
Latn.CJK_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.CJK/Sun-ExtA_16/pdf_to_json_test_Latn.CJK_Sun-ExtA_16.py" > "data/multilingual/Latn.CJK/Sun-ExtA_16/pdf_to_json_test_Latn.CJK_Sun-ExtA_16.json" 2>&1
Latn.CJK_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.CJK/Sun-ExtA_8/pdf_to_json_test_Latn.CJK_Sun-ExtA_8.py" > "data/multilingual/Latn.CJK/Sun-ExtA_8/pdf_to_json_test_Latn.CJK_Sun-ExtA_8.json" 2>&1


Latn.CJK_all : Latn.CJK_Mono_12 Latn.CJK_Mono_16 Latn.CJK_Mono_8 Latn.CJK_Sans_12 Latn.CJK_Sans_16 Latn.CJK_Sans_8 Latn.CJK_Serif_12 Latn.CJK_Serif_16 Latn.CJK_Serif_8 Latn.CJK_Sun-ExtA_12 Latn.CJK_Sun-ExtA_16 Latn.CJK_Sun-ExtA_8
