PYTHON=python3


Hant.CMN_Mono_12:
	-$(PYTHON) data/multilingual/Hant.CMN/Mono_12/pdf_to_json_test_Hant.CMN_Mono_12.py > data/multilingual/Hant.CMN/Mono_12/pdf_to_json_test_Hant.CMN_Mono_12.json 2>&1
Hant.CMN_Mono_16:
	-$(PYTHON) data/multilingual/Hant.CMN/Mono_16/pdf_to_json_test_Hant.CMN_Mono_16.py > data/multilingual/Hant.CMN/Mono_16/pdf_to_json_test_Hant.CMN_Mono_16.json 2>&1
Hant.CMN_Mono_8:
	-$(PYTHON) data/multilingual/Hant.CMN/Mono_8/pdf_to_json_test_Hant.CMN_Mono_8.py > data/multilingual/Hant.CMN/Mono_8/pdf_to_json_test_Hant.CMN_Mono_8.json 2>&1
Hant.CMN_Sans_12:
	-$(PYTHON) data/multilingual/Hant.CMN/Sans_12/pdf_to_json_test_Hant.CMN_Sans_12.py > data/multilingual/Hant.CMN/Sans_12/pdf_to_json_test_Hant.CMN_Sans_12.json 2>&1
Hant.CMN_Sans_16:
	-$(PYTHON) data/multilingual/Hant.CMN/Sans_16/pdf_to_json_test_Hant.CMN_Sans_16.py > data/multilingual/Hant.CMN/Sans_16/pdf_to_json_test_Hant.CMN_Sans_16.json 2>&1
Hant.CMN_Sans_8:
	-$(PYTHON) data/multilingual/Hant.CMN/Sans_8/pdf_to_json_test_Hant.CMN_Sans_8.py > data/multilingual/Hant.CMN/Sans_8/pdf_to_json_test_Hant.CMN_Sans_8.json 2>&1
Hant.CMN_Serif_12:
	-$(PYTHON) data/multilingual/Hant.CMN/Serif_12/pdf_to_json_test_Hant.CMN_Serif_12.py > data/multilingual/Hant.CMN/Serif_12/pdf_to_json_test_Hant.CMN_Serif_12.json 2>&1
Hant.CMN_Serif_16:
	-$(PYTHON) data/multilingual/Hant.CMN/Serif_16/pdf_to_json_test_Hant.CMN_Serif_16.py > data/multilingual/Hant.CMN/Serif_16/pdf_to_json_test_Hant.CMN_Serif_16.json 2>&1
Hant.CMN_Serif_8:
	-$(PYTHON) data/multilingual/Hant.CMN/Serif_8/pdf_to_json_test_Hant.CMN_Serif_8.py > data/multilingual/Hant.CMN/Serif_8/pdf_to_json_test_Hant.CMN_Serif_8.json 2>&1
Hant.CMN_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Hant.CMN/Sun-ExtA_12/pdf_to_json_test_Hant.CMN_Sun-ExtA_12.py > data/multilingual/Hant.CMN/Sun-ExtA_12/pdf_to_json_test_Hant.CMN_Sun-ExtA_12.json 2>&1
Hant.CMN_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Hant.CMN/Sun-ExtA_16/pdf_to_json_test_Hant.CMN_Sun-ExtA_16.py > data/multilingual/Hant.CMN/Sun-ExtA_16/pdf_to_json_test_Hant.CMN_Sun-ExtA_16.json 2>&1
Hant.CMN_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Hant.CMN/Sun-ExtA_8/pdf_to_json_test_Hant.CMN_Sun-ExtA_8.py > data/multilingual/Hant.CMN/Sun-ExtA_8/pdf_to_json_test_Hant.CMN_Sun-ExtA_8.json 2>&1


Hant.CMN_all : Hant.CMN_Mono_12 Hant.CMN_Mono_16 Hant.CMN_Mono_8 Hant.CMN_Sans_12 Hant.CMN_Sans_16 Hant.CMN_Sans_8 Hant.CMN_Serif_12 Hant.CMN_Serif_16 Hant.CMN_Serif_8 Hant.CMN_Sun-ExtA_12 Hant.CMN_Sun-ExtA_16 Hant.CMN_Sun-ExtA_8
