PYTHON=python3


Latn.SLK_Mono_12:
	-$(PYTHON) data/multilingual/Latn.SLK/Mono_12/pdf_to_json_test_Latn.SLK_Mono_12.py > data/multilingual/Latn.SLK/Mono_12/pdf_to_json_test_Latn.SLK_Mono_12.json 2>&1
Latn.SLK_Mono_16:
	-$(PYTHON) data/multilingual/Latn.SLK/Mono_16/pdf_to_json_test_Latn.SLK_Mono_16.py > data/multilingual/Latn.SLK/Mono_16/pdf_to_json_test_Latn.SLK_Mono_16.json 2>&1
Latn.SLK_Mono_8:
	-$(PYTHON) data/multilingual/Latn.SLK/Mono_8/pdf_to_json_test_Latn.SLK_Mono_8.py > data/multilingual/Latn.SLK/Mono_8/pdf_to_json_test_Latn.SLK_Mono_8.json 2>&1
Latn.SLK_Sans_12:
	-$(PYTHON) data/multilingual/Latn.SLK/Sans_12/pdf_to_json_test_Latn.SLK_Sans_12.py > data/multilingual/Latn.SLK/Sans_12/pdf_to_json_test_Latn.SLK_Sans_12.json 2>&1
Latn.SLK_Sans_16:
	-$(PYTHON) data/multilingual/Latn.SLK/Sans_16/pdf_to_json_test_Latn.SLK_Sans_16.py > data/multilingual/Latn.SLK/Sans_16/pdf_to_json_test_Latn.SLK_Sans_16.json 2>&1
Latn.SLK_Sans_8:
	-$(PYTHON) data/multilingual/Latn.SLK/Sans_8/pdf_to_json_test_Latn.SLK_Sans_8.py > data/multilingual/Latn.SLK/Sans_8/pdf_to_json_test_Latn.SLK_Sans_8.json 2>&1
Latn.SLK_Serif_12:
	-$(PYTHON) data/multilingual/Latn.SLK/Serif_12/pdf_to_json_test_Latn.SLK_Serif_12.py > data/multilingual/Latn.SLK/Serif_12/pdf_to_json_test_Latn.SLK_Serif_12.json 2>&1
Latn.SLK_Serif_16:
	-$(PYTHON) data/multilingual/Latn.SLK/Serif_16/pdf_to_json_test_Latn.SLK_Serif_16.py > data/multilingual/Latn.SLK/Serif_16/pdf_to_json_test_Latn.SLK_Serif_16.json 2>&1
Latn.SLK_Serif_8:
	-$(PYTHON) data/multilingual/Latn.SLK/Serif_8/pdf_to_json_test_Latn.SLK_Serif_8.py > data/multilingual/Latn.SLK/Serif_8/pdf_to_json_test_Latn.SLK_Serif_8.json 2>&1
Latn.SLK_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.SLK/Sun-ExtA_12/pdf_to_json_test_Latn.SLK_Sun-ExtA_12.py > data/multilingual/Latn.SLK/Sun-ExtA_12/pdf_to_json_test_Latn.SLK_Sun-ExtA_12.json 2>&1
Latn.SLK_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.SLK/Sun-ExtA_16/pdf_to_json_test_Latn.SLK_Sun-ExtA_16.py > data/multilingual/Latn.SLK/Sun-ExtA_16/pdf_to_json_test_Latn.SLK_Sun-ExtA_16.json 2>&1
Latn.SLK_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.SLK/Sun-ExtA_8/pdf_to_json_test_Latn.SLK_Sun-ExtA_8.py > data/multilingual/Latn.SLK/Sun-ExtA_8/pdf_to_json_test_Latn.SLK_Sun-ExtA_8.json 2>&1


Latn.SLK_all : Latn.SLK_Mono_12 Latn.SLK_Mono_16 Latn.SLK_Mono_8 Latn.SLK_Sans_12 Latn.SLK_Sans_16 Latn.SLK_Sans_8 Latn.SLK_Serif_12 Latn.SLK_Serif_16 Latn.SLK_Serif_8 Latn.SLK_Sun-ExtA_12 Latn.SLK_Sun-ExtA_16 Latn.SLK_Sun-ExtA_8
