PYTHON=python3


Latn.SUS_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.SUS/Mono_12/pdf_to_json_test_Latn.SUS_Mono_12.py" > "data/multilingual/Latn.SUS/Mono_12/pdf_to_json_test_Latn.SUS_Mono_12.json" 2>&1
Latn.SUS_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.SUS/Mono_16/pdf_to_json_test_Latn.SUS_Mono_16.py" > "data/multilingual/Latn.SUS/Mono_16/pdf_to_json_test_Latn.SUS_Mono_16.json" 2>&1
Latn.SUS_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.SUS/Mono_8/pdf_to_json_test_Latn.SUS_Mono_8.py" > "data/multilingual/Latn.SUS/Mono_8/pdf_to_json_test_Latn.SUS_Mono_8.json" 2>&1
Latn.SUS_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.SUS/Sans_12/pdf_to_json_test_Latn.SUS_Sans_12.py" > "data/multilingual/Latn.SUS/Sans_12/pdf_to_json_test_Latn.SUS_Sans_12.json" 2>&1
Latn.SUS_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.SUS/Sans_16/pdf_to_json_test_Latn.SUS_Sans_16.py" > "data/multilingual/Latn.SUS/Sans_16/pdf_to_json_test_Latn.SUS_Sans_16.json" 2>&1
Latn.SUS_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.SUS/Sans_8/pdf_to_json_test_Latn.SUS_Sans_8.py" > "data/multilingual/Latn.SUS/Sans_8/pdf_to_json_test_Latn.SUS_Sans_8.json" 2>&1
Latn.SUS_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.SUS/Serif_12/pdf_to_json_test_Latn.SUS_Serif_12.py" > "data/multilingual/Latn.SUS/Serif_12/pdf_to_json_test_Latn.SUS_Serif_12.json" 2>&1
Latn.SUS_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.SUS/Serif_16/pdf_to_json_test_Latn.SUS_Serif_16.py" > "data/multilingual/Latn.SUS/Serif_16/pdf_to_json_test_Latn.SUS_Serif_16.json" 2>&1
Latn.SUS_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.SUS/Serif_8/pdf_to_json_test_Latn.SUS_Serif_8.py" > "data/multilingual/Latn.SUS/Serif_8/pdf_to_json_test_Latn.SUS_Serif_8.json" 2>&1
Latn.SUS_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.SUS/Sun-ExtA_12/pdf_to_json_test_Latn.SUS_Sun-ExtA_12.py" > "data/multilingual/Latn.SUS/Sun-ExtA_12/pdf_to_json_test_Latn.SUS_Sun-ExtA_12.json" 2>&1
Latn.SUS_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.SUS/Sun-ExtA_16/pdf_to_json_test_Latn.SUS_Sun-ExtA_16.py" > "data/multilingual/Latn.SUS/Sun-ExtA_16/pdf_to_json_test_Latn.SUS_Sun-ExtA_16.json" 2>&1
Latn.SUS_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.SUS/Sun-ExtA_8/pdf_to_json_test_Latn.SUS_Sun-ExtA_8.py" > "data/multilingual/Latn.SUS/Sun-ExtA_8/pdf_to_json_test_Latn.SUS_Sun-ExtA_8.json" 2>&1


Latn.SUS_all : Latn.SUS_Mono_12 Latn.SUS_Mono_16 Latn.SUS_Mono_8 Latn.SUS_Sans_12 Latn.SUS_Sans_16 Latn.SUS_Sans_8 Latn.SUS_Serif_12 Latn.SUS_Serif_16 Latn.SUS_Serif_8 Latn.SUS_Sun-ExtA_12 Latn.SUS_Sun-ExtA_16 Latn.SUS_Sun-ExtA_8
