PYTHON=python3


Latn.SWB_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.SWB/Mono_12/pdf_to_json_test_Latn.SWB_Mono_12.py" > "data/multilingual/Latn.SWB/Mono_12/pdf_to_json_test_Latn.SWB_Mono_12.json" 2>&1
Latn.SWB_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.SWB/Mono_16/pdf_to_json_test_Latn.SWB_Mono_16.py" > "data/multilingual/Latn.SWB/Mono_16/pdf_to_json_test_Latn.SWB_Mono_16.json" 2>&1
Latn.SWB_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.SWB/Mono_8/pdf_to_json_test_Latn.SWB_Mono_8.py" > "data/multilingual/Latn.SWB/Mono_8/pdf_to_json_test_Latn.SWB_Mono_8.json" 2>&1
Latn.SWB_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.SWB/Sans_12/pdf_to_json_test_Latn.SWB_Sans_12.py" > "data/multilingual/Latn.SWB/Sans_12/pdf_to_json_test_Latn.SWB_Sans_12.json" 2>&1
Latn.SWB_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.SWB/Sans_16/pdf_to_json_test_Latn.SWB_Sans_16.py" > "data/multilingual/Latn.SWB/Sans_16/pdf_to_json_test_Latn.SWB_Sans_16.json" 2>&1
Latn.SWB_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.SWB/Sans_8/pdf_to_json_test_Latn.SWB_Sans_8.py" > "data/multilingual/Latn.SWB/Sans_8/pdf_to_json_test_Latn.SWB_Sans_8.json" 2>&1
Latn.SWB_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.SWB/Serif_12/pdf_to_json_test_Latn.SWB_Serif_12.py" > "data/multilingual/Latn.SWB/Serif_12/pdf_to_json_test_Latn.SWB_Serif_12.json" 2>&1
Latn.SWB_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.SWB/Serif_16/pdf_to_json_test_Latn.SWB_Serif_16.py" > "data/multilingual/Latn.SWB/Serif_16/pdf_to_json_test_Latn.SWB_Serif_16.json" 2>&1
Latn.SWB_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.SWB/Serif_8/pdf_to_json_test_Latn.SWB_Serif_8.py" > "data/multilingual/Latn.SWB/Serif_8/pdf_to_json_test_Latn.SWB_Serif_8.json" 2>&1
Latn.SWB_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.SWB/Sun-ExtA_12/pdf_to_json_test_Latn.SWB_Sun-ExtA_12.py" > "data/multilingual/Latn.SWB/Sun-ExtA_12/pdf_to_json_test_Latn.SWB_Sun-ExtA_12.json" 2>&1
Latn.SWB_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.SWB/Sun-ExtA_16/pdf_to_json_test_Latn.SWB_Sun-ExtA_16.py" > "data/multilingual/Latn.SWB/Sun-ExtA_16/pdf_to_json_test_Latn.SWB_Sun-ExtA_16.json" 2>&1
Latn.SWB_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.SWB/Sun-ExtA_8/pdf_to_json_test_Latn.SWB_Sun-ExtA_8.py" > "data/multilingual/Latn.SWB/Sun-ExtA_8/pdf_to_json_test_Latn.SWB_Sun-ExtA_8.json" 2>&1


Latn.SWB_all : Latn.SWB_Mono_12 Latn.SWB_Mono_16 Latn.SWB_Mono_8 Latn.SWB_Sans_12 Latn.SWB_Sans_16 Latn.SWB_Sans_8 Latn.SWB_Serif_12 Latn.SWB_Serif_16 Latn.SWB_Serif_8 Latn.SWB_Sun-ExtA_12 Latn.SWB_Sun-ExtA_16 Latn.SWB_Sun-ExtA_8
