PYTHON=python3


Latn.SWE_Mono_12:
	-$(PYTHON) data/multilingual/Latn.SWE/Mono_12/pdf_to_json_test_Latn.SWE_Mono_12.py > data/multilingual/Latn.SWE/Mono_12/pdf_to_json_test_Latn.SWE_Mono_12.json 2>&1
Latn.SWE_Mono_16:
	-$(PYTHON) data/multilingual/Latn.SWE/Mono_16/pdf_to_json_test_Latn.SWE_Mono_16.py > data/multilingual/Latn.SWE/Mono_16/pdf_to_json_test_Latn.SWE_Mono_16.json 2>&1
Latn.SWE_Mono_8:
	-$(PYTHON) data/multilingual/Latn.SWE/Mono_8/pdf_to_json_test_Latn.SWE_Mono_8.py > data/multilingual/Latn.SWE/Mono_8/pdf_to_json_test_Latn.SWE_Mono_8.json 2>&1
Latn.SWE_Sans_12:
	-$(PYTHON) data/multilingual/Latn.SWE/Sans_12/pdf_to_json_test_Latn.SWE_Sans_12.py > data/multilingual/Latn.SWE/Sans_12/pdf_to_json_test_Latn.SWE_Sans_12.json 2>&1
Latn.SWE_Sans_16:
	-$(PYTHON) data/multilingual/Latn.SWE/Sans_16/pdf_to_json_test_Latn.SWE_Sans_16.py > data/multilingual/Latn.SWE/Sans_16/pdf_to_json_test_Latn.SWE_Sans_16.json 2>&1
Latn.SWE_Sans_8:
	-$(PYTHON) data/multilingual/Latn.SWE/Sans_8/pdf_to_json_test_Latn.SWE_Sans_8.py > data/multilingual/Latn.SWE/Sans_8/pdf_to_json_test_Latn.SWE_Sans_8.json 2>&1
Latn.SWE_Serif_12:
	-$(PYTHON) data/multilingual/Latn.SWE/Serif_12/pdf_to_json_test_Latn.SWE_Serif_12.py > data/multilingual/Latn.SWE/Serif_12/pdf_to_json_test_Latn.SWE_Serif_12.json 2>&1
Latn.SWE_Serif_16:
	-$(PYTHON) data/multilingual/Latn.SWE/Serif_16/pdf_to_json_test_Latn.SWE_Serif_16.py > data/multilingual/Latn.SWE/Serif_16/pdf_to_json_test_Latn.SWE_Serif_16.json 2>&1
Latn.SWE_Serif_8:
	-$(PYTHON) data/multilingual/Latn.SWE/Serif_8/pdf_to_json_test_Latn.SWE_Serif_8.py > data/multilingual/Latn.SWE/Serif_8/pdf_to_json_test_Latn.SWE_Serif_8.json 2>&1
Latn.SWE_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.SWE/Sun-ExtA_12/pdf_to_json_test_Latn.SWE_Sun-ExtA_12.py > data/multilingual/Latn.SWE/Sun-ExtA_12/pdf_to_json_test_Latn.SWE_Sun-ExtA_12.json 2>&1
Latn.SWE_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.SWE/Sun-ExtA_16/pdf_to_json_test_Latn.SWE_Sun-ExtA_16.py > data/multilingual/Latn.SWE/Sun-ExtA_16/pdf_to_json_test_Latn.SWE_Sun-ExtA_16.json 2>&1
Latn.SWE_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.SWE/Sun-ExtA_8/pdf_to_json_test_Latn.SWE_Sun-ExtA_8.py > data/multilingual/Latn.SWE/Sun-ExtA_8/pdf_to_json_test_Latn.SWE_Sun-ExtA_8.json 2>&1


Latn.SWE_all : Latn.SWE_Mono_12 Latn.SWE_Mono_16 Latn.SWE_Mono_8 Latn.SWE_Sans_12 Latn.SWE_Sans_16 Latn.SWE_Sans_8 Latn.SWE_Serif_12 Latn.SWE_Serif_16 Latn.SWE_Serif_8 Latn.SWE_Sun-ExtA_12 Latn.SWE_Sun-ExtA_16 Latn.SWE_Sun-ExtA_8
