PYTHON=python3


Latn.MIC_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.MIC/Mono_12/pdf_to_json_test_Latn.MIC_Mono_12.py" > "data/multilingual/Latn.MIC/Mono_12/pdf_to_json_test_Latn.MIC_Mono_12.json" 2>&1
Latn.MIC_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.MIC/Mono_16/pdf_to_json_test_Latn.MIC_Mono_16.py" > "data/multilingual/Latn.MIC/Mono_16/pdf_to_json_test_Latn.MIC_Mono_16.json" 2>&1
Latn.MIC_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.MIC/Mono_8/pdf_to_json_test_Latn.MIC_Mono_8.py" > "data/multilingual/Latn.MIC/Mono_8/pdf_to_json_test_Latn.MIC_Mono_8.json" 2>&1
Latn.MIC_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.MIC/Sans_12/pdf_to_json_test_Latn.MIC_Sans_12.py" > "data/multilingual/Latn.MIC/Sans_12/pdf_to_json_test_Latn.MIC_Sans_12.json" 2>&1
Latn.MIC_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.MIC/Sans_16/pdf_to_json_test_Latn.MIC_Sans_16.py" > "data/multilingual/Latn.MIC/Sans_16/pdf_to_json_test_Latn.MIC_Sans_16.json" 2>&1
Latn.MIC_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.MIC/Sans_8/pdf_to_json_test_Latn.MIC_Sans_8.py" > "data/multilingual/Latn.MIC/Sans_8/pdf_to_json_test_Latn.MIC_Sans_8.json" 2>&1
Latn.MIC_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.MIC/Serif_12/pdf_to_json_test_Latn.MIC_Serif_12.py" > "data/multilingual/Latn.MIC/Serif_12/pdf_to_json_test_Latn.MIC_Serif_12.json" 2>&1
Latn.MIC_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.MIC/Serif_16/pdf_to_json_test_Latn.MIC_Serif_16.py" > "data/multilingual/Latn.MIC/Serif_16/pdf_to_json_test_Latn.MIC_Serif_16.json" 2>&1
Latn.MIC_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.MIC/Serif_8/pdf_to_json_test_Latn.MIC_Serif_8.py" > "data/multilingual/Latn.MIC/Serif_8/pdf_to_json_test_Latn.MIC_Serif_8.json" 2>&1
Latn.MIC_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.MIC/Sun-ExtA_12/pdf_to_json_test_Latn.MIC_Sun-ExtA_12.py" > "data/multilingual/Latn.MIC/Sun-ExtA_12/pdf_to_json_test_Latn.MIC_Sun-ExtA_12.json" 2>&1
Latn.MIC_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.MIC/Sun-ExtA_16/pdf_to_json_test_Latn.MIC_Sun-ExtA_16.py" > "data/multilingual/Latn.MIC/Sun-ExtA_16/pdf_to_json_test_Latn.MIC_Sun-ExtA_16.json" 2>&1
Latn.MIC_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.MIC/Sun-ExtA_8/pdf_to_json_test_Latn.MIC_Sun-ExtA_8.py" > "data/multilingual/Latn.MIC/Sun-ExtA_8/pdf_to_json_test_Latn.MIC_Sun-ExtA_8.json" 2>&1


Latn.MIC_all : Latn.MIC_Mono_12 Latn.MIC_Mono_16 Latn.MIC_Mono_8 Latn.MIC_Sans_12 Latn.MIC_Sans_16 Latn.MIC_Sans_8 Latn.MIC_Serif_12 Latn.MIC_Serif_16 Latn.MIC_Serif_8 Latn.MIC_Sun-ExtA_12 Latn.MIC_Sun-ExtA_16 Latn.MIC_Sun-ExtA_8
