PYTHON=python3


Latn.BAX_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.BAX/Mono_12/pdf_to_json_test_Latn.BAX_Mono_12.py" > "data/multilingual/Latn.BAX/Mono_12/pdf_to_json_test_Latn.BAX_Mono_12.json" 2>&1
Latn.BAX_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.BAX/Mono_16/pdf_to_json_test_Latn.BAX_Mono_16.py" > "data/multilingual/Latn.BAX/Mono_16/pdf_to_json_test_Latn.BAX_Mono_16.json" 2>&1
Latn.BAX_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.BAX/Mono_8/pdf_to_json_test_Latn.BAX_Mono_8.py" > "data/multilingual/Latn.BAX/Mono_8/pdf_to_json_test_Latn.BAX_Mono_8.json" 2>&1
Latn.BAX_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.BAX/Sans_12/pdf_to_json_test_Latn.BAX_Sans_12.py" > "data/multilingual/Latn.BAX/Sans_12/pdf_to_json_test_Latn.BAX_Sans_12.json" 2>&1
Latn.BAX_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.BAX/Sans_16/pdf_to_json_test_Latn.BAX_Sans_16.py" > "data/multilingual/Latn.BAX/Sans_16/pdf_to_json_test_Latn.BAX_Sans_16.json" 2>&1
Latn.BAX_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.BAX/Sans_8/pdf_to_json_test_Latn.BAX_Sans_8.py" > "data/multilingual/Latn.BAX/Sans_8/pdf_to_json_test_Latn.BAX_Sans_8.json" 2>&1
Latn.BAX_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.BAX/Serif_12/pdf_to_json_test_Latn.BAX_Serif_12.py" > "data/multilingual/Latn.BAX/Serif_12/pdf_to_json_test_Latn.BAX_Serif_12.json" 2>&1
Latn.BAX_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.BAX/Serif_16/pdf_to_json_test_Latn.BAX_Serif_16.py" > "data/multilingual/Latn.BAX/Serif_16/pdf_to_json_test_Latn.BAX_Serif_16.json" 2>&1
Latn.BAX_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.BAX/Serif_8/pdf_to_json_test_Latn.BAX_Serif_8.py" > "data/multilingual/Latn.BAX/Serif_8/pdf_to_json_test_Latn.BAX_Serif_8.json" 2>&1
Latn.BAX_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.BAX/Sun-ExtA_12/pdf_to_json_test_Latn.BAX_Sun-ExtA_12.py" > "data/multilingual/Latn.BAX/Sun-ExtA_12/pdf_to_json_test_Latn.BAX_Sun-ExtA_12.json" 2>&1
Latn.BAX_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.BAX/Sun-ExtA_16/pdf_to_json_test_Latn.BAX_Sun-ExtA_16.py" > "data/multilingual/Latn.BAX/Sun-ExtA_16/pdf_to_json_test_Latn.BAX_Sun-ExtA_16.json" 2>&1
Latn.BAX_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.BAX/Sun-ExtA_8/pdf_to_json_test_Latn.BAX_Sun-ExtA_8.py" > "data/multilingual/Latn.BAX/Sun-ExtA_8/pdf_to_json_test_Latn.BAX_Sun-ExtA_8.json" 2>&1


Latn.BAX_all : Latn.BAX_Mono_12 Latn.BAX_Mono_16 Latn.BAX_Mono_8 Latn.BAX_Sans_12 Latn.BAX_Sans_16 Latn.BAX_Sans_8 Latn.BAX_Serif_12 Latn.BAX_Serif_16 Latn.BAX_Serif_8 Latn.BAX_Sun-ExtA_12 Latn.BAX_Sun-ExtA_16 Latn.BAX_Sun-ExtA_8
