PYTHON=python3


Thai.THA_Mono_12:
	-$(PYTHON) "data/multilingual/Thai.THA/Mono_12/pdf_to_json_test_Thai.THA_Mono_12.py" > "data/multilingual/Thai.THA/Mono_12/pdf_to_json_test_Thai.THA_Mono_12.json" 2>&1
Thai.THA_Mono_16:
	-$(PYTHON) "data/multilingual/Thai.THA/Mono_16/pdf_to_json_test_Thai.THA_Mono_16.py" > "data/multilingual/Thai.THA/Mono_16/pdf_to_json_test_Thai.THA_Mono_16.json" 2>&1
Thai.THA_Mono_8:
	-$(PYTHON) "data/multilingual/Thai.THA/Mono_8/pdf_to_json_test_Thai.THA_Mono_8.py" > "data/multilingual/Thai.THA/Mono_8/pdf_to_json_test_Thai.THA_Mono_8.json" 2>&1
Thai.THA_Sans_12:
	-$(PYTHON) "data/multilingual/Thai.THA/Sans_12/pdf_to_json_test_Thai.THA_Sans_12.py" > "data/multilingual/Thai.THA/Sans_12/pdf_to_json_test_Thai.THA_Sans_12.json" 2>&1
Thai.THA_Sans_16:
	-$(PYTHON) "data/multilingual/Thai.THA/Sans_16/pdf_to_json_test_Thai.THA_Sans_16.py" > "data/multilingual/Thai.THA/Sans_16/pdf_to_json_test_Thai.THA_Sans_16.json" 2>&1
Thai.THA_Sans_8:
	-$(PYTHON) "data/multilingual/Thai.THA/Sans_8/pdf_to_json_test_Thai.THA_Sans_8.py" > "data/multilingual/Thai.THA/Sans_8/pdf_to_json_test_Thai.THA_Sans_8.json" 2>&1
Thai.THA_Serif_12:
	-$(PYTHON) "data/multilingual/Thai.THA/Serif_12/pdf_to_json_test_Thai.THA_Serif_12.py" > "data/multilingual/Thai.THA/Serif_12/pdf_to_json_test_Thai.THA_Serif_12.json" 2>&1
Thai.THA_Serif_16:
	-$(PYTHON) "data/multilingual/Thai.THA/Serif_16/pdf_to_json_test_Thai.THA_Serif_16.py" > "data/multilingual/Thai.THA/Serif_16/pdf_to_json_test_Thai.THA_Serif_16.json" 2>&1
Thai.THA_Serif_8:
	-$(PYTHON) "data/multilingual/Thai.THA/Serif_8/pdf_to_json_test_Thai.THA_Serif_8.py" > "data/multilingual/Thai.THA/Serif_8/pdf_to_json_test_Thai.THA_Serif_8.json" 2>&1
Thai.THA_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Thai.THA/Sun-ExtA_12/pdf_to_json_test_Thai.THA_Sun-ExtA_12.py" > "data/multilingual/Thai.THA/Sun-ExtA_12/pdf_to_json_test_Thai.THA_Sun-ExtA_12.json" 2>&1
Thai.THA_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Thai.THA/Sun-ExtA_16/pdf_to_json_test_Thai.THA_Sun-ExtA_16.py" > "data/multilingual/Thai.THA/Sun-ExtA_16/pdf_to_json_test_Thai.THA_Sun-ExtA_16.json" 2>&1
Thai.THA_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Thai.THA/Sun-ExtA_8/pdf_to_json_test_Thai.THA_Sun-ExtA_8.py" > "data/multilingual/Thai.THA/Sun-ExtA_8/pdf_to_json_test_Thai.THA_Sun-ExtA_8.json" 2>&1


Thai.THA_all : Thai.THA_Mono_12 Thai.THA_Mono_16 Thai.THA_Mono_8 Thai.THA_Sans_12 Thai.THA_Sans_16 Thai.THA_Sans_8 Thai.THA_Serif_12 Thai.THA_Serif_16 Thai.THA_Serif_8 Thai.THA_Sun-ExtA_12 Thai.THA_Sun-ExtA_16 Thai.THA_Sun-ExtA_8
