PYTHON=python3


Latn.MIN_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.MIN/Mono_12/pdf_to_json_test_Latn.MIN_Mono_12.py" > "data/multilingual/Latn.MIN/Mono_12/pdf_to_json_test_Latn.MIN_Mono_12.json" 2>&1
Latn.MIN_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.MIN/Mono_16/pdf_to_json_test_Latn.MIN_Mono_16.py" > "data/multilingual/Latn.MIN/Mono_16/pdf_to_json_test_Latn.MIN_Mono_16.json" 2>&1
Latn.MIN_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.MIN/Mono_8/pdf_to_json_test_Latn.MIN_Mono_8.py" > "data/multilingual/Latn.MIN/Mono_8/pdf_to_json_test_Latn.MIN_Mono_8.json" 2>&1
Latn.MIN_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.MIN/Sans_12/pdf_to_json_test_Latn.MIN_Sans_12.py" > "data/multilingual/Latn.MIN/Sans_12/pdf_to_json_test_Latn.MIN_Sans_12.json" 2>&1
Latn.MIN_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.MIN/Sans_16/pdf_to_json_test_Latn.MIN_Sans_16.py" > "data/multilingual/Latn.MIN/Sans_16/pdf_to_json_test_Latn.MIN_Sans_16.json" 2>&1
Latn.MIN_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.MIN/Sans_8/pdf_to_json_test_Latn.MIN_Sans_8.py" > "data/multilingual/Latn.MIN/Sans_8/pdf_to_json_test_Latn.MIN_Sans_8.json" 2>&1
Latn.MIN_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.MIN/Serif_12/pdf_to_json_test_Latn.MIN_Serif_12.py" > "data/multilingual/Latn.MIN/Serif_12/pdf_to_json_test_Latn.MIN_Serif_12.json" 2>&1
Latn.MIN_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.MIN/Serif_16/pdf_to_json_test_Latn.MIN_Serif_16.py" > "data/multilingual/Latn.MIN/Serif_16/pdf_to_json_test_Latn.MIN_Serif_16.json" 2>&1
Latn.MIN_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.MIN/Serif_8/pdf_to_json_test_Latn.MIN_Serif_8.py" > "data/multilingual/Latn.MIN/Serif_8/pdf_to_json_test_Latn.MIN_Serif_8.json" 2>&1
Latn.MIN_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.MIN/Sun-ExtA_12/pdf_to_json_test_Latn.MIN_Sun-ExtA_12.py" > "data/multilingual/Latn.MIN/Sun-ExtA_12/pdf_to_json_test_Latn.MIN_Sun-ExtA_12.json" 2>&1
Latn.MIN_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.MIN/Sun-ExtA_16/pdf_to_json_test_Latn.MIN_Sun-ExtA_16.py" > "data/multilingual/Latn.MIN/Sun-ExtA_16/pdf_to_json_test_Latn.MIN_Sun-ExtA_16.json" 2>&1
Latn.MIN_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.MIN/Sun-ExtA_8/pdf_to_json_test_Latn.MIN_Sun-ExtA_8.py" > "data/multilingual/Latn.MIN/Sun-ExtA_8/pdf_to_json_test_Latn.MIN_Sun-ExtA_8.json" 2>&1


Latn.MIN_all : Latn.MIN_Mono_12 Latn.MIN_Mono_16 Latn.MIN_Mono_8 Latn.MIN_Sans_12 Latn.MIN_Sans_16 Latn.MIN_Sans_8 Latn.MIN_Serif_12 Latn.MIN_Serif_16 Latn.MIN_Serif_8 Latn.MIN_Sun-ExtA_12 Latn.MIN_Sun-ExtA_16 Latn.MIN_Sun-ExtA_8
