PYTHON=python3


Latn.NYN_Mono_12:
	-$(PYTHON) data/multilingual/Latn.NYN/Mono_12/pdf_to_json_test_Latn.NYN_Mono_12.py > data/multilingual/Latn.NYN/Mono_12/pdf_to_json_test_Latn.NYN_Mono_12.json 2>&1
Latn.NYN_Mono_16:
	-$(PYTHON) data/multilingual/Latn.NYN/Mono_16/pdf_to_json_test_Latn.NYN_Mono_16.py > data/multilingual/Latn.NYN/Mono_16/pdf_to_json_test_Latn.NYN_Mono_16.json 2>&1
Latn.NYN_Mono_8:
	-$(PYTHON) data/multilingual/Latn.NYN/Mono_8/pdf_to_json_test_Latn.NYN_Mono_8.py > data/multilingual/Latn.NYN/Mono_8/pdf_to_json_test_Latn.NYN_Mono_8.json 2>&1
Latn.NYN_Sans_12:
	-$(PYTHON) data/multilingual/Latn.NYN/Sans_12/pdf_to_json_test_Latn.NYN_Sans_12.py > data/multilingual/Latn.NYN/Sans_12/pdf_to_json_test_Latn.NYN_Sans_12.json 2>&1
Latn.NYN_Sans_16:
	-$(PYTHON) data/multilingual/Latn.NYN/Sans_16/pdf_to_json_test_Latn.NYN_Sans_16.py > data/multilingual/Latn.NYN/Sans_16/pdf_to_json_test_Latn.NYN_Sans_16.json 2>&1
Latn.NYN_Sans_8:
	-$(PYTHON) data/multilingual/Latn.NYN/Sans_8/pdf_to_json_test_Latn.NYN_Sans_8.py > data/multilingual/Latn.NYN/Sans_8/pdf_to_json_test_Latn.NYN_Sans_8.json 2>&1
Latn.NYN_Serif_12:
	-$(PYTHON) data/multilingual/Latn.NYN/Serif_12/pdf_to_json_test_Latn.NYN_Serif_12.py > data/multilingual/Latn.NYN/Serif_12/pdf_to_json_test_Latn.NYN_Serif_12.json 2>&1
Latn.NYN_Serif_16:
	-$(PYTHON) data/multilingual/Latn.NYN/Serif_16/pdf_to_json_test_Latn.NYN_Serif_16.py > data/multilingual/Latn.NYN/Serif_16/pdf_to_json_test_Latn.NYN_Serif_16.json 2>&1
Latn.NYN_Serif_8:
	-$(PYTHON) data/multilingual/Latn.NYN/Serif_8/pdf_to_json_test_Latn.NYN_Serif_8.py > data/multilingual/Latn.NYN/Serif_8/pdf_to_json_test_Latn.NYN_Serif_8.json 2>&1
Latn.NYN_Sun-ExtA_12:
	-$(PYTHON) data/multilingual/Latn.NYN/Sun-ExtA_12/pdf_to_json_test_Latn.NYN_Sun-ExtA_12.py > data/multilingual/Latn.NYN/Sun-ExtA_12/pdf_to_json_test_Latn.NYN_Sun-ExtA_12.json 2>&1
Latn.NYN_Sun-ExtA_16:
	-$(PYTHON) data/multilingual/Latn.NYN/Sun-ExtA_16/pdf_to_json_test_Latn.NYN_Sun-ExtA_16.py > data/multilingual/Latn.NYN/Sun-ExtA_16/pdf_to_json_test_Latn.NYN_Sun-ExtA_16.json 2>&1
Latn.NYN_Sun-ExtA_8:
	-$(PYTHON) data/multilingual/Latn.NYN/Sun-ExtA_8/pdf_to_json_test_Latn.NYN_Sun-ExtA_8.py > data/multilingual/Latn.NYN/Sun-ExtA_8/pdf_to_json_test_Latn.NYN_Sun-ExtA_8.json 2>&1


Latn.NYN_all : Latn.NYN_Mono_12 Latn.NYN_Mono_16 Latn.NYN_Mono_8 Latn.NYN_Sans_12 Latn.NYN_Sans_16 Latn.NYN_Sans_8 Latn.NYN_Serif_12 Latn.NYN_Serif_16 Latn.NYN_Serif_8 Latn.NYN_Sun-ExtA_12 Latn.NYN_Sun-ExtA_16 Latn.NYN_Sun-ExtA_8
