PYTHON=python3


Latn.CHA_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.CHA/Mono_12/pdf_to_json_test_Latn.CHA_Mono_12.py" > "data/multilingual/Latn.CHA/Mono_12/pdf_to_json_test_Latn.CHA_Mono_12.json" 2>&1
Latn.CHA_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.CHA/Mono_16/pdf_to_json_test_Latn.CHA_Mono_16.py" > "data/multilingual/Latn.CHA/Mono_16/pdf_to_json_test_Latn.CHA_Mono_16.json" 2>&1
Latn.CHA_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.CHA/Mono_8/pdf_to_json_test_Latn.CHA_Mono_8.py" > "data/multilingual/Latn.CHA/Mono_8/pdf_to_json_test_Latn.CHA_Mono_8.json" 2>&1
Latn.CHA_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.CHA/Sans_12/pdf_to_json_test_Latn.CHA_Sans_12.py" > "data/multilingual/Latn.CHA/Sans_12/pdf_to_json_test_Latn.CHA_Sans_12.json" 2>&1
Latn.CHA_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.CHA/Sans_16/pdf_to_json_test_Latn.CHA_Sans_16.py" > "data/multilingual/Latn.CHA/Sans_16/pdf_to_json_test_Latn.CHA_Sans_16.json" 2>&1
Latn.CHA_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.CHA/Sans_8/pdf_to_json_test_Latn.CHA_Sans_8.py" > "data/multilingual/Latn.CHA/Sans_8/pdf_to_json_test_Latn.CHA_Sans_8.json" 2>&1
Latn.CHA_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.CHA/Serif_12/pdf_to_json_test_Latn.CHA_Serif_12.py" > "data/multilingual/Latn.CHA/Serif_12/pdf_to_json_test_Latn.CHA_Serif_12.json" 2>&1
Latn.CHA_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.CHA/Serif_16/pdf_to_json_test_Latn.CHA_Serif_16.py" > "data/multilingual/Latn.CHA/Serif_16/pdf_to_json_test_Latn.CHA_Serif_16.json" 2>&1
Latn.CHA_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.CHA/Serif_8/pdf_to_json_test_Latn.CHA_Serif_8.py" > "data/multilingual/Latn.CHA/Serif_8/pdf_to_json_test_Latn.CHA_Serif_8.json" 2>&1
Latn.CHA_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.CHA/Sun-ExtA_12/pdf_to_json_test_Latn.CHA_Sun-ExtA_12.py" > "data/multilingual/Latn.CHA/Sun-ExtA_12/pdf_to_json_test_Latn.CHA_Sun-ExtA_12.json" 2>&1
Latn.CHA_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.CHA/Sun-ExtA_16/pdf_to_json_test_Latn.CHA_Sun-ExtA_16.py" > "data/multilingual/Latn.CHA/Sun-ExtA_16/pdf_to_json_test_Latn.CHA_Sun-ExtA_16.json" 2>&1
Latn.CHA_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.CHA/Sun-ExtA_8/pdf_to_json_test_Latn.CHA_Sun-ExtA_8.py" > "data/multilingual/Latn.CHA/Sun-ExtA_8/pdf_to_json_test_Latn.CHA_Sun-ExtA_8.json" 2>&1


Latn.CHA_all : Latn.CHA_Mono_12 Latn.CHA_Mono_16 Latn.CHA_Mono_8 Latn.CHA_Sans_12 Latn.CHA_Sans_16 Latn.CHA_Sans_8 Latn.CHA_Serif_12 Latn.CHA_Serif_16 Latn.CHA_Serif_8 Latn.CHA_Sun-ExtA_12 Latn.CHA_Sun-ExtA_16 Latn.CHA_Sun-ExtA_8
