PYTHON=python3


Latn.AST_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.AST/Mono_12/pdf_to_json_test_Latn.AST_Mono_12.py" > "data/multilingual/Latn.AST/Mono_12/pdf_to_json_test_Latn.AST_Mono_12.json" 2>&1
Latn.AST_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.AST/Mono_16/pdf_to_json_test_Latn.AST_Mono_16.py" > "data/multilingual/Latn.AST/Mono_16/pdf_to_json_test_Latn.AST_Mono_16.json" 2>&1
Latn.AST_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.AST/Mono_8/pdf_to_json_test_Latn.AST_Mono_8.py" > "data/multilingual/Latn.AST/Mono_8/pdf_to_json_test_Latn.AST_Mono_8.json" 2>&1
Latn.AST_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.AST/Sans_12/pdf_to_json_test_Latn.AST_Sans_12.py" > "data/multilingual/Latn.AST/Sans_12/pdf_to_json_test_Latn.AST_Sans_12.json" 2>&1
Latn.AST_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.AST/Sans_16/pdf_to_json_test_Latn.AST_Sans_16.py" > "data/multilingual/Latn.AST/Sans_16/pdf_to_json_test_Latn.AST_Sans_16.json" 2>&1
Latn.AST_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.AST/Sans_8/pdf_to_json_test_Latn.AST_Sans_8.py" > "data/multilingual/Latn.AST/Sans_8/pdf_to_json_test_Latn.AST_Sans_8.json" 2>&1
Latn.AST_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.AST/Serif_12/pdf_to_json_test_Latn.AST_Serif_12.py" > "data/multilingual/Latn.AST/Serif_12/pdf_to_json_test_Latn.AST_Serif_12.json" 2>&1
Latn.AST_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.AST/Serif_16/pdf_to_json_test_Latn.AST_Serif_16.py" > "data/multilingual/Latn.AST/Serif_16/pdf_to_json_test_Latn.AST_Serif_16.json" 2>&1
Latn.AST_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.AST/Serif_8/pdf_to_json_test_Latn.AST_Serif_8.py" > "data/multilingual/Latn.AST/Serif_8/pdf_to_json_test_Latn.AST_Serif_8.json" 2>&1
Latn.AST_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.AST/Sun-ExtA_12/pdf_to_json_test_Latn.AST_Sun-ExtA_12.py" > "data/multilingual/Latn.AST/Sun-ExtA_12/pdf_to_json_test_Latn.AST_Sun-ExtA_12.json" 2>&1
Latn.AST_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.AST/Sun-ExtA_16/pdf_to_json_test_Latn.AST_Sun-ExtA_16.py" > "data/multilingual/Latn.AST/Sun-ExtA_16/pdf_to_json_test_Latn.AST_Sun-ExtA_16.json" 2>&1
Latn.AST_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.AST/Sun-ExtA_8/pdf_to_json_test_Latn.AST_Sun-ExtA_8.py" > "data/multilingual/Latn.AST/Sun-ExtA_8/pdf_to_json_test_Latn.AST_Sun-ExtA_8.json" 2>&1


Latn.AST_all : Latn.AST_Mono_12 Latn.AST_Mono_16 Latn.AST_Mono_8 Latn.AST_Sans_12 Latn.AST_Sans_16 Latn.AST_Sans_8 Latn.AST_Serif_12 Latn.AST_Serif_16 Latn.AST_Serif_8 Latn.AST_Sun-ExtA_12 Latn.AST_Sun-ExtA_16 Latn.AST_Sun-ExtA_8
