PYTHON=python3


Latn.AMC_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.AMC/Mono_12/pdf_to_json_test_Latn.AMC_Mono_12.py" > "data/multilingual/Latn.AMC/Mono_12/pdf_to_json_test_Latn.AMC_Mono_12.json" 2>&1
Latn.AMC_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.AMC/Mono_16/pdf_to_json_test_Latn.AMC_Mono_16.py" > "data/multilingual/Latn.AMC/Mono_16/pdf_to_json_test_Latn.AMC_Mono_16.json" 2>&1
Latn.AMC_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.AMC/Mono_8/pdf_to_json_test_Latn.AMC_Mono_8.py" > "data/multilingual/Latn.AMC/Mono_8/pdf_to_json_test_Latn.AMC_Mono_8.json" 2>&1
Latn.AMC_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.AMC/Sans_12/pdf_to_json_test_Latn.AMC_Sans_12.py" > "data/multilingual/Latn.AMC/Sans_12/pdf_to_json_test_Latn.AMC_Sans_12.json" 2>&1
Latn.AMC_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.AMC/Sans_16/pdf_to_json_test_Latn.AMC_Sans_16.py" > "data/multilingual/Latn.AMC/Sans_16/pdf_to_json_test_Latn.AMC_Sans_16.json" 2>&1
Latn.AMC_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.AMC/Sans_8/pdf_to_json_test_Latn.AMC_Sans_8.py" > "data/multilingual/Latn.AMC/Sans_8/pdf_to_json_test_Latn.AMC_Sans_8.json" 2>&1
Latn.AMC_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.AMC/Serif_12/pdf_to_json_test_Latn.AMC_Serif_12.py" > "data/multilingual/Latn.AMC/Serif_12/pdf_to_json_test_Latn.AMC_Serif_12.json" 2>&1
Latn.AMC_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.AMC/Serif_16/pdf_to_json_test_Latn.AMC_Serif_16.py" > "data/multilingual/Latn.AMC/Serif_16/pdf_to_json_test_Latn.AMC_Serif_16.json" 2>&1
Latn.AMC_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.AMC/Serif_8/pdf_to_json_test_Latn.AMC_Serif_8.py" > "data/multilingual/Latn.AMC/Serif_8/pdf_to_json_test_Latn.AMC_Serif_8.json" 2>&1
Latn.AMC_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.AMC/Sun-ExtA_12/pdf_to_json_test_Latn.AMC_Sun-ExtA_12.py" > "data/multilingual/Latn.AMC/Sun-ExtA_12/pdf_to_json_test_Latn.AMC_Sun-ExtA_12.json" 2>&1
Latn.AMC_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.AMC/Sun-ExtA_16/pdf_to_json_test_Latn.AMC_Sun-ExtA_16.py" > "data/multilingual/Latn.AMC/Sun-ExtA_16/pdf_to_json_test_Latn.AMC_Sun-ExtA_16.json" 2>&1
Latn.AMC_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.AMC/Sun-ExtA_8/pdf_to_json_test_Latn.AMC_Sun-ExtA_8.py" > "data/multilingual/Latn.AMC/Sun-ExtA_8/pdf_to_json_test_Latn.AMC_Sun-ExtA_8.json" 2>&1


Latn.AMC_all : Latn.AMC_Mono_12 Latn.AMC_Mono_16 Latn.AMC_Mono_8 Latn.AMC_Sans_12 Latn.AMC_Sans_16 Latn.AMC_Sans_8 Latn.AMC_Serif_12 Latn.AMC_Serif_16 Latn.AMC_Serif_8 Latn.AMC_Sun-ExtA_12 Latn.AMC_Sun-ExtA_16 Latn.AMC_Sun-ExtA_8
