PYTHON=python3


Vaii.VAI_Mono_12:
	-$(PYTHON) "data/multilingual/Vaii.VAI/Mono_12/pdf_to_json_test_Vaii.VAI_Mono_12.py" > "data/multilingual/Vaii.VAI/Mono_12/pdf_to_json_test_Vaii.VAI_Mono_12.json" 2>&1
Vaii.VAI_Mono_16:
	-$(PYTHON) "data/multilingual/Vaii.VAI/Mono_16/pdf_to_json_test_Vaii.VAI_Mono_16.py" > "data/multilingual/Vaii.VAI/Mono_16/pdf_to_json_test_Vaii.VAI_Mono_16.json" 2>&1
Vaii.VAI_Mono_8:
	-$(PYTHON) "data/multilingual/Vaii.VAI/Mono_8/pdf_to_json_test_Vaii.VAI_Mono_8.py" > "data/multilingual/Vaii.VAI/Mono_8/pdf_to_json_test_Vaii.VAI_Mono_8.json" 2>&1
Vaii.VAI_Sans_12:
	-$(PYTHON) "data/multilingual/Vaii.VAI/Sans_12/pdf_to_json_test_Vaii.VAI_Sans_12.py" > "data/multilingual/Vaii.VAI/Sans_12/pdf_to_json_test_Vaii.VAI_Sans_12.json" 2>&1
Vaii.VAI_Sans_16:
	-$(PYTHON) "data/multilingual/Vaii.VAI/Sans_16/pdf_to_json_test_Vaii.VAI_Sans_16.py" > "data/multilingual/Vaii.VAI/Sans_16/pdf_to_json_test_Vaii.VAI_Sans_16.json" 2>&1
Vaii.VAI_Sans_8:
	-$(PYTHON) "data/multilingual/Vaii.VAI/Sans_8/pdf_to_json_test_Vaii.VAI_Sans_8.py" > "data/multilingual/Vaii.VAI/Sans_8/pdf_to_json_test_Vaii.VAI_Sans_8.json" 2>&1
Vaii.VAI_Serif_12:
	-$(PYTHON) "data/multilingual/Vaii.VAI/Serif_12/pdf_to_json_test_Vaii.VAI_Serif_12.py" > "data/multilingual/Vaii.VAI/Serif_12/pdf_to_json_test_Vaii.VAI_Serif_12.json" 2>&1
Vaii.VAI_Serif_16:
	-$(PYTHON) "data/multilingual/Vaii.VAI/Serif_16/pdf_to_json_test_Vaii.VAI_Serif_16.py" > "data/multilingual/Vaii.VAI/Serif_16/pdf_to_json_test_Vaii.VAI_Serif_16.json" 2>&1
Vaii.VAI_Serif_8:
	-$(PYTHON) "data/multilingual/Vaii.VAI/Serif_8/pdf_to_json_test_Vaii.VAI_Serif_8.py" > "data/multilingual/Vaii.VAI/Serif_8/pdf_to_json_test_Vaii.VAI_Serif_8.json" 2>&1
Vaii.VAI_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Vaii.VAI/Sun-ExtA_12/pdf_to_json_test_Vaii.VAI_Sun-ExtA_12.py" > "data/multilingual/Vaii.VAI/Sun-ExtA_12/pdf_to_json_test_Vaii.VAI_Sun-ExtA_12.json" 2>&1
Vaii.VAI_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Vaii.VAI/Sun-ExtA_16/pdf_to_json_test_Vaii.VAI_Sun-ExtA_16.py" > "data/multilingual/Vaii.VAI/Sun-ExtA_16/pdf_to_json_test_Vaii.VAI_Sun-ExtA_16.json" 2>&1
Vaii.VAI_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Vaii.VAI/Sun-ExtA_8/pdf_to_json_test_Vaii.VAI_Sun-ExtA_8.py" > "data/multilingual/Vaii.VAI/Sun-ExtA_8/pdf_to_json_test_Vaii.VAI_Sun-ExtA_8.json" 2>&1


Vaii.VAI_all : Vaii.VAI_Mono_12 Vaii.VAI_Mono_16 Vaii.VAI_Mono_8 Vaii.VAI_Sans_12 Vaii.VAI_Sans_16 Vaii.VAI_Sans_8 Vaii.VAI_Serif_12 Vaii.VAI_Serif_16 Vaii.VAI_Serif_8 Vaii.VAI_Sun-ExtA_12 Vaii.VAI_Sun-ExtA_16 Vaii.VAI_Sun-ExtA_8
