PYTHON=python3


Latn.VMW_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.VMW/Mono_12/pdf_to_json_test_Latn.VMW_Mono_12.py" > "data/multilingual/Latn.VMW/Mono_12/pdf_to_json_test_Latn.VMW_Mono_12.json" 2>&1
Latn.VMW_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.VMW/Mono_16/pdf_to_json_test_Latn.VMW_Mono_16.py" > "data/multilingual/Latn.VMW/Mono_16/pdf_to_json_test_Latn.VMW_Mono_16.json" 2>&1
Latn.VMW_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.VMW/Mono_8/pdf_to_json_test_Latn.VMW_Mono_8.py" > "data/multilingual/Latn.VMW/Mono_8/pdf_to_json_test_Latn.VMW_Mono_8.json" 2>&1
Latn.VMW_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.VMW/Sans_12/pdf_to_json_test_Latn.VMW_Sans_12.py" > "data/multilingual/Latn.VMW/Sans_12/pdf_to_json_test_Latn.VMW_Sans_12.json" 2>&1
Latn.VMW_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.VMW/Sans_16/pdf_to_json_test_Latn.VMW_Sans_16.py" > "data/multilingual/Latn.VMW/Sans_16/pdf_to_json_test_Latn.VMW_Sans_16.json" 2>&1
Latn.VMW_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.VMW/Sans_8/pdf_to_json_test_Latn.VMW_Sans_8.py" > "data/multilingual/Latn.VMW/Sans_8/pdf_to_json_test_Latn.VMW_Sans_8.json" 2>&1
Latn.VMW_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.VMW/Serif_12/pdf_to_json_test_Latn.VMW_Serif_12.py" > "data/multilingual/Latn.VMW/Serif_12/pdf_to_json_test_Latn.VMW_Serif_12.json" 2>&1
Latn.VMW_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.VMW/Serif_16/pdf_to_json_test_Latn.VMW_Serif_16.py" > "data/multilingual/Latn.VMW/Serif_16/pdf_to_json_test_Latn.VMW_Serif_16.json" 2>&1
Latn.VMW_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.VMW/Serif_8/pdf_to_json_test_Latn.VMW_Serif_8.py" > "data/multilingual/Latn.VMW/Serif_8/pdf_to_json_test_Latn.VMW_Serif_8.json" 2>&1
Latn.VMW_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.VMW/Sun-ExtA_12/pdf_to_json_test_Latn.VMW_Sun-ExtA_12.py" > "data/multilingual/Latn.VMW/Sun-ExtA_12/pdf_to_json_test_Latn.VMW_Sun-ExtA_12.json" 2>&1
Latn.VMW_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.VMW/Sun-ExtA_16/pdf_to_json_test_Latn.VMW_Sun-ExtA_16.py" > "data/multilingual/Latn.VMW/Sun-ExtA_16/pdf_to_json_test_Latn.VMW_Sun-ExtA_16.json" 2>&1
Latn.VMW_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.VMW/Sun-ExtA_8/pdf_to_json_test_Latn.VMW_Sun-ExtA_8.py" > "data/multilingual/Latn.VMW/Sun-ExtA_8/pdf_to_json_test_Latn.VMW_Sun-ExtA_8.json" 2>&1


Latn.VMW_all : Latn.VMW_Mono_12 Latn.VMW_Mono_16 Latn.VMW_Mono_8 Latn.VMW_Sans_12 Latn.VMW_Sans_16 Latn.VMW_Sans_8 Latn.VMW_Serif_12 Latn.VMW_Serif_16 Latn.VMW_Serif_8 Latn.VMW_Sun-ExtA_12 Latn.VMW_Sun-ExtA_16 Latn.VMW_Sun-ExtA_8
