PYTHON=python3


Latn.QUZ_Mono_12:
	-$(PYTHON) "data/multilingual/Latn.QUZ/Mono_12/pdf_to_json_test_Latn.QUZ_Mono_12.py" > "data/multilingual/Latn.QUZ/Mono_12/pdf_to_json_test_Latn.QUZ_Mono_12.json" 2>&1
Latn.QUZ_Mono_16:
	-$(PYTHON) "data/multilingual/Latn.QUZ/Mono_16/pdf_to_json_test_Latn.QUZ_Mono_16.py" > "data/multilingual/Latn.QUZ/Mono_16/pdf_to_json_test_Latn.QUZ_Mono_16.json" 2>&1
Latn.QUZ_Mono_8:
	-$(PYTHON) "data/multilingual/Latn.QUZ/Mono_8/pdf_to_json_test_Latn.QUZ_Mono_8.py" > "data/multilingual/Latn.QUZ/Mono_8/pdf_to_json_test_Latn.QUZ_Mono_8.json" 2>&1
Latn.QUZ_Sans_12:
	-$(PYTHON) "data/multilingual/Latn.QUZ/Sans_12/pdf_to_json_test_Latn.QUZ_Sans_12.py" > "data/multilingual/Latn.QUZ/Sans_12/pdf_to_json_test_Latn.QUZ_Sans_12.json" 2>&1
Latn.QUZ_Sans_16:
	-$(PYTHON) "data/multilingual/Latn.QUZ/Sans_16/pdf_to_json_test_Latn.QUZ_Sans_16.py" > "data/multilingual/Latn.QUZ/Sans_16/pdf_to_json_test_Latn.QUZ_Sans_16.json" 2>&1
Latn.QUZ_Sans_8:
	-$(PYTHON) "data/multilingual/Latn.QUZ/Sans_8/pdf_to_json_test_Latn.QUZ_Sans_8.py" > "data/multilingual/Latn.QUZ/Sans_8/pdf_to_json_test_Latn.QUZ_Sans_8.json" 2>&1
Latn.QUZ_Serif_12:
	-$(PYTHON) "data/multilingual/Latn.QUZ/Serif_12/pdf_to_json_test_Latn.QUZ_Serif_12.py" > "data/multilingual/Latn.QUZ/Serif_12/pdf_to_json_test_Latn.QUZ_Serif_12.json" 2>&1
Latn.QUZ_Serif_16:
	-$(PYTHON) "data/multilingual/Latn.QUZ/Serif_16/pdf_to_json_test_Latn.QUZ_Serif_16.py" > "data/multilingual/Latn.QUZ/Serif_16/pdf_to_json_test_Latn.QUZ_Serif_16.json" 2>&1
Latn.QUZ_Serif_8:
	-$(PYTHON) "data/multilingual/Latn.QUZ/Serif_8/pdf_to_json_test_Latn.QUZ_Serif_8.py" > "data/multilingual/Latn.QUZ/Serif_8/pdf_to_json_test_Latn.QUZ_Serif_8.json" 2>&1
Latn.QUZ_Sun-ExtA_12:
	-$(PYTHON) "data/multilingual/Latn.QUZ/Sun-ExtA_12/pdf_to_json_test_Latn.QUZ_Sun-ExtA_12.py" > "data/multilingual/Latn.QUZ/Sun-ExtA_12/pdf_to_json_test_Latn.QUZ_Sun-ExtA_12.json" 2>&1
Latn.QUZ_Sun-ExtA_16:
	-$(PYTHON) "data/multilingual/Latn.QUZ/Sun-ExtA_16/pdf_to_json_test_Latn.QUZ_Sun-ExtA_16.py" > "data/multilingual/Latn.QUZ/Sun-ExtA_16/pdf_to_json_test_Latn.QUZ_Sun-ExtA_16.json" 2>&1
Latn.QUZ_Sun-ExtA_8:
	-$(PYTHON) "data/multilingual/Latn.QUZ/Sun-ExtA_8/pdf_to_json_test_Latn.QUZ_Sun-ExtA_8.py" > "data/multilingual/Latn.QUZ/Sun-ExtA_8/pdf_to_json_test_Latn.QUZ_Sun-ExtA_8.json" 2>&1


Latn.QUZ_all : Latn.QUZ_Mono_12 Latn.QUZ_Mono_16 Latn.QUZ_Mono_8 Latn.QUZ_Sans_12 Latn.QUZ_Sans_16 Latn.QUZ_Sans_8 Latn.QUZ_Serif_12 Latn.QUZ_Serif_16 Latn.QUZ_Serif_8 Latn.QUZ_Sun-ExtA_12 Latn.QUZ_Sun-ExtA_16 Latn.QUZ_Sun-ExtA_8
